### ISSUE TITLE
Dragging Konva Canvas to DOM

### ISSUE THREAD

**Issue by erictuvesson** [konvajs/konva#1000]
Is there a example of dragging from Konva Canvas to DOM?

I found this which is DOM to Konva Canvas, but I would like to be able to do it both ways.
https://konvajs.org/docs/sandbox/Drop_DOM_Element.html

**Comment by lavrton** [comment]
What do you want to draggle outside? Can you describe your use case?

`Konva` nodes can not be visible outside of a `Stage`. So it does make much sense to drag them outside.

**Comment by erictuvesson** [comment]
In my scenario I want to be able to drag nodes outside of the canvas using `DataTransfer` where I can set my own context.
https://www.w3schools.com/html/html5_draganddrop.asp

For example in the Drop DOM Element example, dragging an image to the canvas and then dragging it back to the DOM, which in turn removes it from the canvas.

The main goal is to be able to interact between DOM and Konva both ways.

**Comment by lavrton** [comment]
Ok, so as I mentioned we can't draw konva nodes outside of the canvas element. What you can do is:

1. When an object goes close to the edge of the canvas or out of the viewport you need to emulate dragging with DOM.
2. Create a draggable DOM object, like an image that mimics the visual representation of your canvas shape.
3. on `mousemove` update the position of that DOM element manually on the page with absolute position.
4. on `mouseup` check drop position and do you drop logic.

In sum:
1. I don't see any ways to use HTML5 drag&drop for elements from canvas
2. You can emulate such drag by creating and moving DOM element manually
3. All of this is out of Konva control.

**Comment by erictuvesson** [comment]
I don't want to draw the elements outside of the canvas element.

So to solve this I have to create a temporary DOM element and then manually fire the event with the context I want?

I don't think you understand what I am trying to achieve, but maybe I should look for a more complete framework.

**Comment by lavrton** [comment]
> I want to be able to drag nodes outside of the canvas

That is what you said. So I pointed out that Konva can't draw outside of the canvas. So I suggested creating an external DOM element, so visually it may look like you drag a node outside of the canvas.

**Comment by erictuvesson** [comment]
Dragging is creating a DOM DataTransfer context with a image generated image or a custom, it can be empty as well. It won't render the konva node outside the canvas.
The main goal is to be able to have the context when dragging, from and to the canvas. 

The only thing I want is to be able to use the drag and drop API, from your explanation it doesn't seem like that is supported. 😞

**Comment by lavrton** [comment]
It is not. Be default `Konva` disables native HTML5 drag&drop behavior to allows its own drag&drop abilities for nodes. I am not sure what can be done here to enable it back.

**Comment by erictuvesson** [comment]
In the Konva drag events we do have a DragEvent, correct?

I saw this in another example earlier.
https://konvajs.org/docs/drag_and_drop/Drop_Events.html
```js
previousShape.fire(
  'dragleave',
  {
    type: 'dragleave',
    target: previousShape,
    evt: evt.evt,
  },
  true
);
```

In that case I would expect that the event is `DragEvent` ? _(I think I even tested this)_

If that were the case we could update the DataTransfer context there, I am not sure if that in turn have to be passed to the DOM somehow.

**Comment by lavrton** [comment]
My suggestion is not to use html5 drag&drop API here. So there will be no `DataTransfer`. Just save such data somewhere else in JS environment (a variable or a state of the application).

**Comment by erictuvesson** [comment]
Okay so no drag and drop API solution?

Maybe remove it as a feature from the website too then?

**Comment by lavrton** [comment]
The demo on the site is not HTML5 API. It is a working demo. Why should we remove it?

**Comment by erictuvesson** [comment]
I didn't say remove the demo, I said remove it as a presented feature which is stated on the website. Since it doesn't have drag and drop support.

**Comment by lavrton** [comment]
Konva itself supports dragging nodes. But it is not the same as HTML5 drag&drop https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Drag_operations for DOM elements. It works in a very different way.
