### ISSUE TITLE
transform  snaps

### ISSUE THREAD

**Issue by z411500976** [konvajs/konva#1001]
How to achieve transform  snaps 
such as aligning other node during transformation
Can you give me an idea? Thank you

![8djmz-olq4o](https://user-images.githubusercontent.com/24216715/97103996-1f1c3500-16eb-11eb-8d70-3cd597ac6ccf.gif)

**Comment by lavrton** [comment]
Did you try anything?

I think you can start from `transform` event. Then you need to calculate snap sizes. And if a node is closed to that size, snap it to that value.

**Comment by z411500976** [comment]
Thanks for your advice,
I found that boundBoxFunc can be used, I will try again, thanks again
