### ISSUE TITLE
Drag speed

### ISSUE THREAD

**Issue by lumenier1** [konvajs/konva#1003]
This will be nice feature to set drag speed of an object.

I.e. if you need to throttle dragging speed of an object on `dragmove` event.

```
var draggingObj = new Konva.Image({
   image: imageObj,
   x: stage.width() / 2 - 200 / 2,
   y: stage.height() / 2 - 137 / 2,
   width: 200,
   height: 137,
   draggable: true,
   dragSpeed: 0.7, // <-- from 0 to 1
});
```

Why? This feature will be very helpful for games, CAD and art projects.

Cases:

1) slow down scope sight movement for 2D shooter
2) slow down paint brush to draw more accurate and smooth lines (lazy drawing)
3) particle interaction with slowed down draggable object

And many more.

**Comment by lavrton** [comment]
Thanks for the suggestion, but I don't think that feature will be useful. In other to implement all of these features you can just use `touchmove` and `mousemove` events and make your own "dragSpeed" implementation. Or you can still use a draggable object as "drag target", but slow down another object's movements.
