### ISSUE TITLE
The underline property of the Text exceeds the clip scope

### ISSUE THREAD

**Issue by MrErHu** [konvajs/konva#1005]
I am develop a spreadsheet using konva，I found that the underline of the Text will exceed the scope of the clip.
Below is the code example：
https://jsbin.com/tojidufumu/6/edit?html,js,output

**Comment by lavrton** [comment]
Looks like it is a bug in Chrome. It works ok in Safari in FF.

**Comment by MrErHu** [comment]
Can it be solved or bypassed? @lavrton

**Comment by lavrton** [comment]
The best way to solve it is to create a bug report in Chrome bugtracker.

As a workaround, you may try to use a different `clipHeight` value.  For that example `clipHeight: 26.5` works as expected.
