### ISSUE TITLE
Text on path not properly aligned. Wrong Chars spacing.

### ISSUE THREAD

**Issue by ramonortigosa** [konvajs/konva#1006]
Hi:
I am trying to create an export to SVG tool using konva but it seems that any text on a path is not properly aligned. The spacing between letters does not work fine too. An example:

https://jsfiddle.net/ortigosa/myj576fh/2/

<img width="607" alt="konva1" src="https://user-images.githubusercontent.com/5767717/97708559-48f1a500-1ab9-11eb-9fa7-a18afe7d1ad1.png">

What I am doing wrong?
Thanks!

**Comment by lavrton** [comment]
You are doing all correctly. Our calculations are just not perfect.

**Comment by ramonortigosa** [comment]
I see.. thanks for the reply.

**Comment by lavrton** [comment]
Let's keep it open, so we can fix it sooner or later.

**Comment by maloguertin** [comment]
> Let's keep it open, so we can fix it sooner or later.

If you want some inspiration this code seems to do a good job at spacing and centering a text on a bezier curve:

https://riptutorial.com/html5-canvas/example/19302/text-on-curve--cubic-and-quadratic-beziers

I still need to tweak it but the red text is with code inspired from this website and the black on is using html SVG text on path:


![Screenshot from 2020-11-24 15-18-41](https://user-images.githubusercontent.com/6407064/100146912-a2ef4b80-2e68-11eb-9448-9f4233bd185c.png)

**Comment by lavrton** [comment]
I am going to close the issue for now, because I am not sure about the good solution for the Konva side. 
As workaround `letterSpacing` and `kerningFunc` can be used to fix it.
