### ISSUE TITLE
fillPatternScale on iPhone 5S (iOS 10)

### ISSUE THREAD

**Issue by goodwin74** [konvajs/konva#1007]
**fillPatternScale** not work on iPhone 5S (iOS 10)
How to fix it?
![Безымянный](https://user-images.githubusercontent.com/15101984/98434017-e746c180-20dc-11eb-8803-af6352d1e4e6.png)

**Comment by lavrton** [comment]
Probably only by drawing an image into an external canvas with manual scaling of that canvas. And then use THAT canvas for fill pattern image.
