### ISSUE TITLE
FR: Export IFrame type

### ISSUE THREAD

**Issue by rhofour** [konvajs/konva#1009]
It doesn't look like the IFrame type is exported currently.

I'm using a Konva.Animation and it'd be nice to have the right type for the function parameter.

**Comment by lavrton** [comment]
Why do you need it? If you use `Konva.Animation` typescript will automatically suggest types for you.

**Comment by rhofour** [comment]
Right now my code looks like this:
`new Konva.Animation((frame: any | undefined) => {`

I'd rather be able to replace the any with the appropriate type, but while TypeScript knows it should be IFrame, it's not exported so I can't use it in the annotation.

**Comment by lavrton** [comment]
But why do you need to define type at all? Just do
```
new Konva.Animation((frame) => {
  // here typescript will know what iframe is
});
```

**Comment by rhofour** [comment]
It's certainly not necessary, I just like the extra context when reading the code.

**Comment by lavrton** [comment]
```js
import { IFrame } from 'konva/types/types';
```
