### ISSUE TITLE
Is it possible to "share" groups (or layers) among separate stages?

### ISSUE THREAD

**Issue by Harti** [konvajs/konva#101]
Heya,

first of all, thanks for further maintaining this excellent library for KineticJS's sake! :)

I got the following situation:
I have two adjacent `div` elements that each contain a `Konva.Stage` (it is a requirement that they stay two separate `div`s). However, both `Stage`s are supposed to share the *very same set* of (animated) `Konva.Circle`s, including their positions.
The animation speed and direction of each `Circle` are determined (once) at random and will therefore vary for each instance. At a later point of time I would like to be able to manipulate each `Circle`'s velocity/direction (depending on certain events).

```
(Stage) mainStage
+--- (Layer) mainLayer
     +--- (Rect) grayBackground
      +--- (Group) "circles" (globalCompositeOperation: lighter)

(Stage) infoStage
+--- (Layer) infoLayer
      +--- (Rect) violetBackground
      +--- (Group) "circles" (globalCompositeOperation: lighter)
```

**I am unable to create a `Konva.Group` or `Konva.Layer` and add it to multiple stages.** Once I try to do that, the respective Group/Layer is removed from the stage it was originally added to. That makes perfect sense looking at the documentation and the way Konva is built.

This architecture, however, got me stuck. Now, I *could* use an array to store my custom circle objects and (re-)instantiate `Konva.Circle` (as well as `Konva.Animation`) instances at runtime, returning a `Konva.Layer`, but this approach will most likely yield major performance issues for large amounts of shapes.

Right now, as a workaround, I'm creating two different `Konva.Group`s and add objects like so:
```
    var mainCircles = new Konva.Group();
    var infoCircles = new Konva.Group();

    ...

    infoCircles.add(circle);
    mainCircles.add(circle.clone());
```
..., resulting in lots of duplicate code (which is probably also less performant because more animations have to be calculated).

Is there an elegant (i.e. performant) way to share the same set of `Konva.Shape`s or (better yet) a `Konva.Group`s among multiple layers/stages? 

Thanks in advance,

Harti

**Comment by lavrton** [comment]
How you are sharing circle's properties? You want to have one circle on two stages. So EVERY property will be the same on both stages, right?

**Comment by Harti** [comment]
Yes, exactly! 
Let's say I have a circle c1 with { x: 100, y: 100, fill: 'red' }. I'd like to be able to add c1 to both infoStage and mainStage, so the circle will be drawn on both canvases at (100, 100) with red color. 
And c1 shall be animated to e.g. (150,150) within 5 seconds. This should happen on both stages as well.

(Sorry for the short and unformatted reply, I'm currently on mobile)

**Comment by lavrton** [comment]
Ok.
I don't think konva will have support for multiple parents for node.
So I think you can:
1. Continue do what you are doing right now.
2. Use this small trick: move all shapes, that need to be duplicated in one layer on first stage. In second stage you need to create layer with one `Konva.Image`. Use canvas of first layer as source of `Konva.Image` in second layer. So it will be something like:
```
var layer1 = new Konva.Layer():
// create circles
// ..
var layer2 = new Konva.Layer();
var image = new Konva.Image({
    image: layer1.canvas._canvas
});
layer2.add(image);
```
