### ISSUE TITLE
PointerEvent support

### ISSUE THREAD

**Issue by xxlee0927** [konvajs/konva#1011]
Is the `Stage` instance support `PointerEvent`?
There is some code about `PointerEvent` in `Stage.ts`, but I can't listen the event by neither `on` nor `addEventListener`.

**Comment by lavrton** [comment]
Right now it is hidden under the flag:

```js
Konva._pointerEventsEnabled = true;
```

It Is is not powerful enough compared to touch or mouse events.

Why do you need it?

**Comment by xxlee0927** [comment]
Thanks for reply.
Currently I handle touch event by transform `TouchEvent` into `MouseEvent` manually by adding clientX, clientY, and so on in `touches[0]`. 
(suppose there are only one touch now)
With `PointerEvent`, I can do this job gracefully, and determine the event is triggered by which `pointerType`.
It will help a lot in my project!

**Comment by lavrton** [comment]
You can just use `stage.getPointerPosition()` for universal position of mouse/touch.

**Comment by xxlee0927** [comment]
That's good. But how can I determine whether is `pen` or `touch` without `TouchEvent.pointerType`?

**Comment by lavrton** [comment]
Probably you can't. Why do you need it?

**Comment by xxlee0927** [comment]
Our user are supposed to use mouse or pen to draw due to the job on our product is required high precision.
Therefore, we'd like to ignore touch by finger to prevent weird behavior when drawing by pen (hands may touch the screen at the same time).

**Comment by lavrton** [comment]
Full support for pointers events is there now with `konva@8`.
