### ISSUE TITLE
Triangle (Regular Polygon with three sides) has issue with Transformer

### ISSUE THREAD

**Issue by raminious** [konvajs/konva#1015]
Triangle corners doesn't fit to Transformer corners. I think the bottom gap should remove 

![image](https://user-images.githubusercontent.com/334716/99236154-dfd39680-2807-11eb-910e-b7130ed3fa41.png)

you can find the reproducible example here:
https://codesandbox.io/s/patient-cookies-xeeke?file=/src/index.ts

**Comment by lavrton** [comment]
A bounding box of any regular polygon is approximated into the circle shape with the same radius. Only triangle produces such an edge case.

I don't have any plans to fix the behavior.

As the solution, use `Konva.Path` for triangle instead of `Konva.RegularPolygon`.

**Comment by raminious** [comment]
actually it has issue with other polygon shapes.

![image](https://user-images.githubusercontent.com/334716/99276434-b897bc00-283d-11eb-9739-6b2b680f7f52.png)

**Comment by lavrton** [comment]
Ok. I changed my mind. The fix is on the master. Will be published later.
