### ISSUE TITLE
Mobile events are not bubbling 

### ISSUE THREAD

**Issue by maloguertin** [konvajs/konva#1019]
When you attach a click event to a parent of the Konva stage the event is not bubbled on mobile but it is on desktop.

https://jsbin.com/najizolulu/edit?output

Try click the stage with a desktop browser and a mobile one (chrome's mobile preview will also produce this bug)

**Comment by lavrton** [comment]
`Konva` prevents default behavior on mobile. Mostly for better drag&drop support. If you need to return it back use `preventDefault: false` for the shape.
