### ISSUE TITLE
Problems with border in Persian text

### ISSUE THREAD

**Issue by mohsensd1373** [konvajs/konva#1022]
Hello
Please look at this problem
https://jsbin.com/jedirus/edit?html,js,output
And give me a solution
Sorry, I do not speak English and I use a translator
Thanks

**Comment by lavrton** [comment]
Use the last version of konva and `fillAfterStrokeEnabled: true` property for `Konva.Text`.

https://jsbin.com/wotapocalu/1/edit?html,js,output
