### ISSUE TITLE
`onTransformEnd` handler only fires for the first selected element, when rotating/resizing them together, with multiple selection

### ISSUE THREAD

**Issue by matejcsok-istvan** [konvajs/konva#1023]
Hello,

I have an issue after implementing multiple selection:
[I would like to refer to a demo you created, because it also has this issue](https://codesandbox.io/s/react-konva-multiple-selection-tgggi?file=/src/index.js:6421-7231)

There is an `onTransformEnd` handler on the `Rect` component, but if I select both elements and rotate them, only the first selected item's handler fires.
But if I drag both elements together that fires both  items' `onDragEnd` handlers.

Is it the expected behaviour? Do you know any workaround to solve this issue?
Please let me know if you need more information.
Thanks!

**Comment by lavrton** [comment]
That is a bad bug. Thanks for the report. I made a release `konva@7.2.1` with a fix.

**Comment by matejcsok-istvan** [comment]
Thanks for the quick fix, it works now!
