### ISSUE TITLE
Text transformer's origin drifts over time if text has a stroke

### ISSUE THREAD

**Issue by Trinovantes** [konvajs/konva#1024]
I'm trying to replicate Photoshop's text controls where the transform anchor handles only rescale the textbox rather than the text itself. Here's the code that I have so far: https://jsfiddle.net/rfjzq1g9/1/

One minor issue I noticed is that dragging the anchor over time slowly shifts the transformer's origin (e.g. dragging the bottom right anchor slowly shifts the top left anchor). This only happens when the text has a stroke. If I comment out the stroke property on line 28, then it works as expected and the top left anchor stays in place.

![2020-12-09 03-26-29](https://user-images.githubusercontent.com/458691/101604616-295e6e00-39cf-11eb-8987-e8bed730a5f1.gif)

Obviously this is an extreme edge case and I don't actually expect users to do this in practice but I think it's a nice-to-have polish.

**Comment by lavrton** [comment]
Such jumps are here because of your reset logic:

```js
textbox.on('transform', () => {
    const t = textbox
    const width = Math.abs(t.width() * t.scaleX())
    const height = Math.abs(t.height() * t.scaleY())
    const scaleX = t.scaleX() < 0 ? -1 : 1
    const scaleY = t.scaleY() < 0 ? -1 : 1
    const rotation = t.rotation()

    t.setAttrs({
        width,
        height,
        scaleX,
        scaleY,
        rotation,
    })
    group.draw()
})
```

Default `Konva.Transformer` doesn't produce such behaviour. As the simple workaround just use `ignoreStroke: true` for `Konva.Transformer`.
