### ISSUE TITLE
[Suggestion] Add cornerRadius to custom Shapes

### ISSUE THREAD

**Issue by crllrd** [konvajs/konva#1025]
Currently, the cornerRadius (set/get) attribute does not exist on custom shapes.
 
 I suppose  it's because it's had to detect if shape has corner, and you can just update path if you know exactly what you need.
 Although I think it'll be easier to update/change Shape with this feature, and it'll give opportunity to update shape from client side, inputing  cornerRadius value

I had to add to custom setter in my project (example below), of course it's just a workaround .

I would really appreciate  your opinion, is this something worth  implementing?

```
new Konva.Shape({
        data: pathData,
        cornerRadius: 0,
        ...
        setCornerRadius(value: number) {
          this.cornerRadius = value;
        },
        sceneFunc(context, shape) {
         const shapeRadius = shape.getAttr('cornerRadius');
         drawPathBasedOnRadius(pathData, shapeRadius, context);
}
```

Thanks in regards.

**Comment by lavrton** [comment]
I don't think there is any simple way to support `cornerRadius` for any shape. If you want to draw a custom shape with a corner radius, you can just use `cornerRadius` custom attribute, as you do it in your sample.

For getters/setters there are:

```js
shape.setAttr('cornerRadius', 5);
shape.getAttr('cornerRadius');
```

**Comment by crllrd** [comment]
Thanks for your answer, I believe it make sense. I think we can close this issue.
