### ISSUE TITLE
EXIF data missing

### ISSUE THREAD

**Issue by danieljsimpson** [konvajs/konva#1026]
We are using "Konva.Image.fromURL" to load in JPEG images that contain EXIF data, such as lat/long of where the picture was taken. However, when we do Konva.Stage.toDataURL({mimeType: 'image/jpge'}), we notice that the image doesn't have any EXIF data.

I'm not sure if the EXIF data is lost on load or save, but wanted to request a fix so that the EXIF data can be preserved.

**Comment by lavrton** [comment]
Konva doesn't support and it will never support that. Canvas doesn't have any information about EXIF from images.

Also, what do you expect to have in EXIF if you draw several images?

You have to manually work with EXIF data. Manually load and save it back. Take a look here: https://github.com/exif-js/exif-js
