### ISSUE TITLE
Intersects function inconsistent on Dragging event and Mouse events.

### ISSUE THREAD

**Issue by vsantosu** [konvajs/konva#1027]
Hello Konva Team,

I'm experiencing some issues while trying to use the 'intersects' function...

The issue is the following:

For the following code snipped:

```                  
                        x=evt.x;
                        y=evt.y;
                        let intersects = wedge.intersects({x,y});
                        console.log(intersects)
```

If executed in an 'onDragMove' event, it returns FALSE. If it is executed in an 'onMouseOver' event it returns TRUE... 

I'm missing something? Perhaps something with the redrawing cycle? 

More elaborated situation:

I have a circle on top of a wedge, if I mouse over and execute that code inside an onMouseOver event handler (x,y is the position of the circle on top of the wedge) intersection returns true, if I drag the circle even when the x,y coordinates are over the wedge, intersection returns false.

**Comment by lavrton** [comment]
We have such behavior because of dragging performance optimizations. Hit testing is skipped when any node is dragged. 
I don't think it is a correct behavior when you call `shape.intersects()` manually. I made a fix and will publish it later.

As workaround you can do this:

```js
Konva.hitOnDragEnabled = true;
let intersects = wedge.intersects({x,y});
Konva.hitOnDragEnabled = false;
```

**Comment by vsantosu** [comment]
Thanks so much @lavrton! works like a charm!!
