### ISSUE TITLE
Konva.Shape bug?

### ISSUE THREAD

**Issue by xiongshuang** [konvajs/konva#1028]
![image](https://user-images.githubusercontent.com/48544740/101973114-83ca2980-3c70-11eb-800f-451539a8d267.png)

Transformer positional fault

**Comment by lavrton** [comment]
Can you make a demo?

Do you use a custom shape? If so, take a look here - https://stackoverflow.com/questions/50571367/konvajs-custom-shapes-and-transformers

**Comment by xiongshuang** [comment]
Ok, I see. It has to set the width and height. thank you
