### ISSUE TITLE
Screen size change demo

### ISSUE THREAD

**Issue by pmros** [konvajs/konva#103]
I'd like to see a demo where screen size changes and canvas would adjust (responsive design). I think it would be a very useful demo because today applications have to adapt their size to many screen sizes on many devices. 
Thank you for konva!

**Comment by pgrodrigues** [comment]
+1, a starting point if anyone's interested: https://coderwall.com/p/dy_dla/scale-your-kineticjs-game-dynamically

**Comment by lavrton** [comment]
I think this tutorial is good. Usually I am using same approach.

But basically for me "responsive design" for `canvas` (or `svg` element) is very unclear term. As usually when we are using "responsive design" term we a taking about common html components like texts, images etc. So "adaptation" for such components works via css.

You have to write "adaptation" for canvas in your own way via javascript. As for different projects "responsive design" for canvas may work in completely different way. For example you have chart on canvas. Probably you can not scale it to fit a screen as graphics will be too small and user will see nothing.
Make sense?

**Comment by Pmleader** [comment]
I usually combine an automatically re-sizing canvas with a pinch zoom functionality.
This way the canvas adjust to small screen sizes but a mobile user can still zoom in to see smaller details.

**Comment by microcipcip** [comment]
Wouldn't be easier to add a parameter, for example `responsive: true` to the `stage` and make it responsive with pure CSS? See [example here](http://codepen.io/microcipcip/pen/WwYyBd)

**Comment by lavrton** [comment]
@microcipcip such approach will break a lot of things. Hit detection (as size is changing), drag&drop, hight quality picture (zoomed canvas will blur).

**Comment by lavrton** [comment]
I added simple demo here: http://konvajs.github.io/docs/sandbox/Responsive_Canvas.html
