### ISSUE TITLE
Konva.Line with tension doesn't calculate width / height properly and cannot be cached

### ISSUE THREAD

**Issue by danielcrisp** [konvajs/konva#1030]
I've been trying to cache a `Konva.Line` instance, but have been encountering the following error message:

    Konva error: Can not cache the node. Width or height of the node equals 0. Caching is skipped.

I've checked the width and height of the line manually, e.g. using `node.width()`, and both return `NaN` when the line config has a `tension` value. If I remove the `tension` value then the width and height are correct and the node can be cached.

Here's a demo:

https://jsbin.com/pikuwaw/2/edit?html,js,console,output

**Comment by lavrton** [comment]
That is a bug. Thanks for the report. I will publish the release later.
