### ISSUE TITLE
[Question]How shall use dash attribute with Konva.Line

### ISSUE THREAD

**Issue by fengxinming** [konvajs/konva#1034]
I am going to draw a polygon with Konva.Line, and the one of sides is dashed line if it is not a confirmed line, that is like the below video.

https://user-images.githubusercontent.com/6262382/102973874-82cead00-4538-11eb-99d9-4de656e510f3.mp4

**Comment by lavrton** [comment]
So do you want to have a dashed just one side? If so - just use several `Konva.Line`.

**Comment by fengxinming** [comment]
@lavrton Is it only one way? or could you support this feature in `Konva.Line`?

**Comment by lavrton** [comment]
> or could you support this feature in Konva.Line?

No, I don't think it makes much sense. It will complicate API and the codebase.

Another solution is to just draw into canvas manually with a custom shape. https://konvajs.org/docs/shapes/Custom.html
