### ISSUE TITLE
[Feature] Konva.Arrow could not change arrow style

### ISSUE THREAD

**Issue by fengxinming** [konvajs/konva#1036]
Konva.Arrow could not change arrow style to below style
![20201225154810](https://user-images.githubusercontent.com/6262382/103126631-dd4b4300-46c9-11eb-88b5-10ddc72098d5.jpg)

**Comment by lavrton** [comment]
Closing as not a priory. You can use custom shape, `Konva.Path` or several `Konva.Line` objects to make such drawing
