### ISSUE TITLE
Textpath When the data property changes, the position is so skewed that I can't see it

### ISSUE THREAD

**Issue by GuoChen-thlg** [konvajs/konva#1037]
When I change the value of the data attribute, it is offset, I don't know whether it is the offset caused by data or something, and I get zero width and zero height，

Here's an example : https://jsbin.com/juzoxuwiru/edit?js,output

**Comment by lavrton** [comment]
Can you clarify your issue?

I tried your demo with the last konva version: https://jsbin.com/nupiloqaci/1/edit?html,js,output
The output looks correct to me.

**Comment by GuoChen-thlg** [comment]
> Can you clarify your issue?
> 
> I tried your demo with the last konva version: https://jsbin.com/nupiloqaci/1/edit?html,js,output
> The output looks correct to me.

So the first thing I'll show you is the first TextPath data property x property =0 y property =0 and it's on the left and the top,
When I switched to the second data attribute (skull), its position changed and it was no longer on the far left and top. I don't know what caused it, and I don't know much about SVG,

**Comment by lavrton** [comment]
It is not in `top-left` because this is how the `data` attribute is defined on your second TextPath. If you need to start it from top-left you may need to manually move it using the `offset` property
