### ISSUE TITLE
Konva supports path animation? For example, it defines an arc and generates an animation according to the arc trajectory

### ISSUE THREAD

**Issue by codcer** [konvajs/konva#1038]
Thank you for submitting an issue!

Please make sure to check current open and closed issues to see if your question has been asked or answered before.
If you have just a question (not a bug or a feature request) it is better to ask it in [Stackoverflow](http://stackoverflow.com/questions/tagged/konvajs).

If you have a bug, please, try to create a reproducible example with jsfiddle (or any similar service).
You can use [this JSBIN](https://jsbin.com/tekehizuta/1/edit?html,js,output) as a template.

**Comment by lavrton** [comment]
No. `Konva` doesn't have direct support for that.

But you can use https://developer.mozilla.org/en-US/docs/Web/API/SVGPathElement/getPointAtLength or `konvaPath.getPointAtLength()` function to calculate the position of an element on the path and animate according to these calculations.
