### ISSUE TITLE
[Feature] drag button support

### ISSUE THREAD

**Issue by wxfred** [konvajs/konva#1039]
I want to drag the stage with middle mouse button, and drag other nodes with left mouse button.
Is it possible to add a config to determine which mouse button for dragging?

**Comment by lavrton** [comment]
https://konvajs.org/api/Konva.html#.dragButtons

**Comment by wxfred** [comment]
I mean different node have different drag button, not the global setting. Is it possible?

**Comment by lavrton** [comment]
Not direct API, but this can work:

```js
node.on('mousedown', (e) => {
 if (e.evt.button === 3) {
   node.startDrag();
 }
});
```

**Comment by wxfred** [comment]
Thanks a lot!
