### ISSUE TITLE
measureText unreliable on Opera 9.80 Android?

### ISSUE THREAD

**Issue by kennardconsulting** [konvajs/konva#104]
I'm seeing the following problem running Konva JS on Opera 9.80 on Android:

Cannot convert 'v.measureText(a)' to object
User-Agent: Opera/9.80 (Android; Opera Mini/7.5.35721/37.7011; U; en) Presto/2.12.423 Version/12.16

Looks like this is coming from _getTextSize internally. I'm sure this is Opera's bug (works everywhere else), but is there a workaround?

**Comment by lavrton** [comment]
I am not sure it is related to `Konva`.
