### ISSUE TITLE
Poor performance with many Text layers that have stroke and shadow

### ISSUE THREAD

**Issue by Joebayld** [konvajs/konva#1042]
Hi, 

I've encountered this strange issue in my project since updating to v7.0.0, and it was fine in v6.0.0. It has to do with many layers of text that have both a stroke and a shadow. I've created a sample project to demonstrate it. 

Simply lasso select anywhere in the group and observe the speed of the fill color changing, then change the Konva version to v7.0.3 and notice the slow behavior. I've also noticed the performance is very poor when zooming in/out of the canvas too. 

Note: this is a very simple example. In my project it uses more complex groups and the performance drop is far worse. Any ideas what is causing this?

https://jsbin.com/hodisekada/1/edit?html,js,output

**Comment by lavrton** [comment]
It is related to rendering fixes with a case when a shape has a stroke and shadow at the same time.  Konva is using buffer canvas to render every `Konva.Text` instance.
The simplest way to resolve it is to set `shape.shadowForStrokeEnabled(false)`.  

https://jsbin.com/kametitupo/1/edit?html,js,output
