### ISSUE TITLE
scaling

### ISSUE THREAD

**Issue by kyle-hensoon** [konvajs/konva#1043]
in my projact i have two button for zoom in/out

for zoom in  i do this in react konva 
  const zoomIn = useCallback(() => {
    if (scale < 3) {
      onChangeScale(0.25);
    }
  }, [scale, onChangeScale]);

  const zoomOut = useCallback(() => {
    if (scale > 0.25) {
      onChangeScale(-0.25);
    }
  }, [scale, onChangeScale]);

and my initial scale is 1, finally my problem 
is after zoom in , its going to top left corner , but i want just zoom on center of stage or in my case image

**Comment by lavrton** [comment]
There are two ways:
1. Setup offset usage. https://konvajs.org/docs/posts/Position_vs_Offset.html
2. Just update the position of the stage, when you change the scale. Similar to how it is done here: https://konvajs.org/docs/sandbox/Zooming_Relative_To_Pointer.html
