### ISSUE TITLE
"Zooming stage relative to pointer position" example does not work in Safari

### ISSUE THREAD

**Issue by JoeDuncko** [konvajs/konva#1044]
"Zooming stage relative to pointer position" example does not work in Safari. Tried on both Safari 13.1.1 and 14.0.2

It appears that pinching to zoom on Safari does not trigger the `onWheel` event. 

Link to the example: https://konvajs.org/docs/sandbox/Zooming_Relative_To_Pointer.html

Thanks!

**Comment by lavrton** [comment]
It does work on desktop Safari. The demo is not designed for touch devices.

> Instructions: **Mousewheel** over canvas.

**Comment by JoeDuncko** [comment]
Er, I am using Safari on MacOS. I'm pinching to zoom, not two finger scrolling (which works). Pinch to Zoom works in other desktop browsers with this example, so I think it's a reasonable expectation for it to work on Safari as well.

Is there a browser limitation here?

**Comment by lavrton** [comment]
Probably different browsers trigger pinch events differently.

**Comment by JoeDuncko** [comment]
Looks like you're right. Found this: https://stackoverflow.com/questions/15416851/catching-mac-trackpad-zoom/37183950#37183950
