### ISSUE TITLE
Adding "tension" property to Konva.Arrow options breaks layer.getClientRect

### ISSUE THREAD

**Issue by bobbzorzen** [konvajs/konva#1045]
If you create a new Konva.Arrow with the property "tension" with a non zero value you can no longer use the layer.getClientRect method, it returns NaN on all the values.

I've got no clue what causes this issue but it definately seems like a bug

Fiddle that reproduces issue in as small an example as i can make it
https://jsfiddle.net/L9jp7m3e/1/

**Comment by lavrton** [comment]
Works just fine with the last version of Konva. https://jsfiddle.net/4xmcyfdn/
