### ISSUE TITLE
Failed to execute 'arc' on 'CanvasRenderingContext2D

### ISSUE THREAD

**Issue by fengxinming** [konvajs/konva#1046]
```
Error: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-39) is negative.
    at Konva.SceneContext.arc (konva.min.js:12)
    at Konva.Rect._sceneFunc (konva.min.js:26)
    at Konva.Rect.drawScene (konva.min.js:26)
    at konva.min.js:26
    at Konva.Collection.each (konva.min.js:12)
    at Konva.Layer._drawChildren (konva.min.js:26)
    at Konva.Layer.drawScene (konva.min.js:26)
    at Konva.Layer.drawScene (konva.min.js:26)
    at Konva.Layer.draw (konva.min.js:12)
    at documidute.js:22
```

**Here is a reproduction demo**

https://jsbin.com/documidute/1/edit?html,js,output

**Comment by lavrton** [comment]
Just don't use negative width/height for the Rect. I don't think we should support such usage. Probably we need to add a warning for such case.

**Comment by fengxinming** [comment]
@lavrton It works well without cornerRadius attribute with Konva.Rect. in production we probably move the mouse to draw Rect from left to right，so width/height value would be negative.

**Comment by lavrton** [comment]
> It works well without cornerRadius attribute with Konva.Rect

Yes. Because a rectangle without a corner radius uses much simpler draw function without calling `context.arc()` function.

> in production we probably move the mouse to draw Rect from left to right，so the width/height value would be negative.

For that case, you need to start changing {x, y} position and keep size attributes positive.

**Comment by fengxinming** [comment]
@lavrton Fine!
