### ISSUE TITLE
Inconsistent behavior of lines / strokes with large negative numbers since Chromium 88

### ISSUE THREAD

**Issue by Seblor** [konvajs/konva#1048]
Hello,

I updated my Chrome browser version to 88 and I noticed an inconsistent behavior of strokes (lines or rectangle borders).

I wanted to have a line that never ends so I set its starting point to `-Number.MAX_SAFE_INTEGER`, and it worked great until the update.

Now instead of starting from the far left outside of the screen, the line starts from the middle of the canvas.

In the case of a rectangle, the inner rectangle draws correctly, but its border starts to be drawn from the middle of the canvas.

In my demo, I have a line that starts on the far left, up to X=100, and a rectangle which origin is set to the far left with a very large width. Here is the link: https://jsbin.com/pupagekobu/edit

Here is the behavior I noticed:

| Origin        | Behavior |
| ------------- |-------------|
| -2*1e12 | The line doesn't draw and the rectangle's border only draws from the center of the canvas<br>(Note that the rectangle draws correctly if its width is set to `Number.MAX_SAFE_INTEGER` or the stage's width is above 1862) |
| -1e12 | The line doesn't draw and the rectangle draws properly |
| -1e9 | Both are drawn |

This happend with both Chrome 88 and Edge 88, but Firefox 85 works fine.

Here is a video of what happens on my end:
![recording (9)](https://user-images.githubusercontent.com/3054920/106066070-7b349200-60fc-11eb-93df-fac89b747b5d.gif)

**Comment by lavrton** [comment]
I don't think we can/should do anything here from the Konva side. That is how canvas works now in Chrome.

From my side, I don't recommend using such large values for any properties. Even if a part of a shape is outside the viewport, it may consume resources to render it. So it is better to have values close to the visible viewport.
