### ISSUE TITLE
[Feature] Make `Image` have `cornerRadius` like `Rect`

### ISSUE THREAD

**Issue by deadcoder0904** [konvajs/konva#1049]
I set `cornerRadius` on `Rect` & wanted to have the same effect on `Image` but found out that `Image` doesn't support `cornerRadius` property.

The reason I want this is to not make the downloadable asset which is a combination of `Rect` & `Image` look a complete square or rectangle. A little corner radius would look much better. What do you think?

**Comment by lavrton** [comment]
I don't have any plans to add such a feature there.

You can use clipping on groups to create such an effect. Take a look here for demo: https://stackoverflow.com/a/56040003/512042

**Comment by deadcoder0904** [comment]
I tried doing it. But I have an `array` instead of a `number` so it couldn't use `+` operator. How should I make the inner image the same shape as the outer one? And if I want to completely change the corner radius, do I need to change the math?

![clip in konva](https://user-images.githubusercontent.com/16436270/107117206-a5c1e000-689e-11eb-9305-2feebc12a3c3.png)

Codesandbox 👉 https://codesandbox.io/s/clip-rounded-image-in-react-konva-09d2l?file=/src/App.tsx

```tsx
<Stage width={width} height={height}>
  <Layer>
    <Rect
      width={width / 2}
      height={height / 2}
      x={20}
      y={20}
      fill=""
      cornerRadius={10}
      shadowEnabled={true}
      shadowColor="#bada41"
      shadowBlur={50}
      shadowOffset={{ x: 10, y: 10 }}
      shadowOpacity={1}
      shadow={10}
    />
    <Rect
      width={width / 2}
      height={height / 2}
      x={20}
      y={20}
      cornerRadius={cornerRadius}
      fill="palevioletred"
    />
    <Group
      clipFunc={(ctx: any) => {
        ctx.beginPath()
        ctx.moveTo(x + cornerRadius[0], y)
        ctx.lineTo(x + width - cornerRadius[0], y)
        ctx.quadraticCurveTo(x + width, y, x + width, y + cornerRadius[0])
        ctx.lineTo(x + width, y + height - cornerRadius[1])
        ctx.quadraticCurveTo(
          x + width,
          y + height,
          x + width - cornerRadius[1],
          y + height
        )
        ctx.lineTo(x + cornerRadius[1], y + height)
        ctx.quadraticCurveTo(x, y + height, x, y + height - cornerRadius[2])
        ctx.lineTo(x, y + cornerRadius[2])
        ctx.quadraticCurveTo(x, y, x + cornerRadius[3], y)
        ctx.closePath()
      }}
    >
      <Image
        image={img}
        width={width / 4}
        height={height / 4}
        x={40}
        y={40}
        fill="blue"
      />
    </Group>
  </Layer>
</Stage>
```

**Comment by lavrton** [comment]
https://codesandbox.io/s/react-konva-image-clip-demo-x4i2d

**Comment by deadcoder0904** [comment]
Thank you once again @lavrton, works like a charm 🙌

Lmk if u have any links around the interwebs where the math behind this or similar thing is explained.

As working with Konva is basically calculations all the time & I waste a lot of time on this. Would love to learn the basics once & for all ;)
