### ISSUE TITLE
draggable problems when mouse out of stage

### ISSUE THREAD

**Issue by ddcovery** [konvajs/konva#105]
Hello,

Basically, I have an stage with an image that user can "pann and zoom".  Image is bigger than stage and user drags image to center it freely.  Problem is when, while dragging, the mouse leaves the stage zone (something usual when you drag/drop big objects into small viewport/stage):  the X,Y coordinates of the image are "reseted" abruptly to the original ones before you began to drag.  This is really awful behaviour:  as an example, can you imagine someone dragging something in photoshop with this limitation?.  

I don't know which version of konva introduced this behaviour change, but Anton, pls, keep in consideration restore the original behaviour.  Optimizations can't be an excuse to limit basic expected user experience.

Thanks in advance.

**Comment by lavrton** [comment]
Should be fixed in last 0.10.0 version. Check it.

**Comment by ddcovery** [comment]
Thanks  @lavrton 

Chrome works properly, but Firefox doesn't calculate correctly coordinates  and Image position changed abruptly depending of stage container position (paddings, positions, and so on). (I'm using Firefox 42)

**Comment by lavrton** [comment]
Ok. Thanks. I will take a look.

**Comment by lavrton** [comment]
Hi. Test last version from repo. Is it better now?

**Comment by ddcovery** [comment]
Hi @lavrton.   Tested and working.  Thanks a lot.
