### ISSUE TITLE
Resizing svgs in Firefox

### ISSUE THREAD

**Issue by nasradin07** [konvajs/konva#1050]
If I try to resize svg  horizontally and vertically (in Firefox) it works fine. But if I try resizing in one direction (horizontally or vertivally) the image doesn't scale properly. 

In Chrome this works fine, but in Firefox it does not.

Jsfiddle is bellow,
https://jsbin.com/raqaxaqase/edit?js,output

**Comment by lavrton** [comment]
That is browser behavior. I don't think we should do anything here from the Konva side.

As a workaround draw the image into an external canvas. Use that canvas as `image`. https://jsbin.com/geracamape/edit?js,output

P.S. You can increase the canvas size to increase the quality.
