### ISSUE TITLE
hitStrokeWidth touch versus mouse

### ISSUE THREAD

**Issue by Joebayld** [konvajs/konva#1051]
Hey there, 

I'm wondering if there's an elegant to have a different `hitStrokeWidth` based on if the event is a touch event versus a click event. 

The reason for this is that I use a larger width to account for touchscreen fingers, but the mouse has more precision and I don't quite need this as high. 

Thoughts on this? 

thanks!
Joe

**Comment by lavrton** [comment]
```js
const TOUCH_DEVICE = 'ontouchstart' in window;

shape.histStrokeWidth(TOUCH_DEVICE ? 10 : 'auto');
```
