### ISSUE TITLE
[Bug] Shadow only gets applied when you provide a fill

### ISSUE THREAD

**Issue by deadcoder0904** [konvajs/konva#1052]
I have a simple app where I have navbar & body. I have to apply shadow to `navbar+body` so I create a `Rect` with `navbar+body`'s `width` & `height` & apply shadow to that `Rect`. The shadow does not appear unless I provide a `fill`. I also have to use a separate `Rect` for box-shadow since both `navbar` & `body` are 2 different `Rect`'s so I can't just apply shadow to any one of them as they only make half of the puzzle.

The following is a simplified example.

Here's a demo → https://codesandbox.io/s/shadow-in-react-konva-gu0sc?file=/src/App.tsx

The code is pretty simple:

```tsx
import { Stage, Layer, Rect } from "react-konva"

export default function App() {
	const width = window.innerWidth
	const height = window.innerHeight
	return (
		<div className="App">
			<h1
				style={{
					paddingLeft: 20,
				}}
			>
				Shadow in Konva
			</h1>
			<Stage width={width} height={height}>
				<Layer>
					<Rect
						width={width / 2}
						height={height / 2}
						x={20}
						y={20}
						fill=""
						cornerRadius={10}
						shadowEnabled={true}
						shadowColor="#bada41"
						shadowBlur={50}
						shadowOffset={{ x: 10, y: 10 }}
						shadowOpacity={1}
						shadow={10}
					/>
					<Rect
						width={width / 2}
						height={height / 2}
						x={20}
						y={20}
						fill="pink"
					/>
				</Layer>
			</Stage>
		</div>
	)
}
```

I have this `pink` rectangle below which I am trying to show a shadow.

![pink](https://user-images.githubusercontent.com/16436270/106873133-2693a700-66fa-11eb-8243-66893ac8c09d.png)

The above rectangle has an empty fill ,i.e, `fill=""` but if I put `fill="red"` in it then the shadow automatically appears.

![red](https://user-images.githubusercontent.com/16436270/106873723-bfc2bd80-66fa-11eb-8670-da052714c95f.png)

Seems like a bug?

**Comment by lavrton** [comment]
No, it is not a bug, it is expected behavior. Shadow depends on fill. That is how shadow works in html5 canvas. 

As a workaround, you may try to convert your several rectangles into ONE image and apply shadow to it.

**Comment by deadcoder0904** [comment]
Cool. I fixed it by placing the rectangle below my `navbar+body` & gave it `white` fill for now but since it's behind it so it isn't visible to the user anyways :)
