### ISSUE TITLE
Zoom with Cache performance

### ISSUE THREAD

**Issue by rebinnaf** [konvajs/konva#1054]
I have over 10000 shapes in a layer of the stage just like the demo I have put the link and an image in another layer in the background, and I want to have a smooth zoom, however, I think it is not smooth. I just tried to cache all the layers of the stage in zooming, but still not smooth. I wanted to know if there is any way to improve it. Thank you very much for the great Konva.

https://jsfiddle.net/adx0t2c3/3/

**Comment by lavrton** [comment]
For me, it works very fast and smooth. Why do you see any lags?

**Comment by rebinnaf** [comment]
https://user-images.githubusercontent.com/32017122/106899202-53e85100-670a-11eb-9efd-a7138cdbef51.mov

This is what I see when I scroll the stage. It's not consistent for me.

**Comment by lavrton** [comment]
Hmm.. Is it the same cached version? What browser/OS do you have?

That is what I see:
https://user-images.githubusercontent.com/1443320/106900526-9f780c00-66c4-11eb-8009-1a2823c38523.mp4

It is very smooth for me. I don't see any simple ways to improve the performance. Probably using lower `pixelRatio` for cache function will help.

**Comment by rebinnaf** [comment]
yeah, just I made it 40000 shapes to convey what I mean. I used safari in macOS Catalina version 10.15.4. Now, I just tested it in chrome and it seems promising. So the problem is just for the safari and It's ok in my case; thank you very much!
