### ISSUE TITLE
Cache thousands shapes time

### ISSUE THREAD

**Issue by rebinnaf** [konvajs/konva#1055]
The time that caching takes for 100 shapes is about 16ms, and for 10000 shapes is 600ms. In my usecase, since I want to cache the layer before the zoom-start(wheel start) and then clearCache after zoom-end(wheel-end) (I want the shapes to be reactive), so I cache the layer each time I want to zoom, and this delay repeats. I will be really grateful if there is any way to improve it. 
https://jsfiddle.net/me85hw1L/20/

**Comment by lavrton** [comment]
Then you may try to cache BEFORE zoom action. For example inside mouseenter event. Also you can convert layer into image and keep that image on memory, before scale, replace all rectangles with just one image. on scale end, remove image, add rectangles back.
