### ISSUE TITLE
Arrow transformer not dragging along with arrow

### ISSUE THREAD

**Issue by atologist-preyash** [konvajs/konva#1056]
On dragging arrow, how I make transformer drag too?

https://codesandbox.io/s/arrow-transformer-7uphd
@lavrton stuck here, need help.

**Comment by lavrton** [comment]
I don't see how you reflect the position change of the arrow back to your anchors. You have `xAndY` prop in `<AnchorDrawable />` that you didn't use.

**Comment by atologist-preyash** [comment]
xAndY prop is not helping with the expected output. Let me know if you find any solution.

**Comment by lavrton** [comment]
https://codesandbox.io/s/arrow-transformer-forked-j5dvn?file=/index.js

**Comment by atologist-preyash** [comment]
Thanks you for the input
