### ISSUE TITLE
With create-react-app and Typescript Stage object does not have a height() and width() defined so layer.height() fails.

### ISSUE THREAD

**Issue by aledelgo** [konvajs/konva#1058]
Hello,
i'm trying to use Konva in a create-react-app generated project with typescript.
i'm not using konva-react on pourpose and i'm just using it with plain Typescript.

when i call someLayer.height() i get this.parent.height is not a function and infact calling stage.height() in the console give me the same error...

this works fine if i use the plain library... suppose babel or webpack do something strange in the bundling process but dont know what.
any hint?
thanks for the help

**Comment by lavrton** [comment]
Can you make a demo?

**Comment by aledelgo** [comment]
I'm gonna close this. after 2 hours i found the invisible bug in my code...
in the intent of setting size of the stage, i ended up replacing the getter/setter function with *values*

code was like this...
`stage.width=400`

strange that there was not any warning by typescript linter...
