### ISSUE TITLE
Mouse events not working on IE11

### ISSUE THREAD

**Issue by idoschor** [konvajs/konva#106]
This stated at v.0.10.0, still working on v0.9.5.
Specifically, events binded to nodes have an "offset" - the event fires when the cursor is next to the node.
The drag demo doesn't work at all.

**Comment by lavrton** [comment]
@idoschor thanks for report. Will look soon.

**Comment by lavrton** [comment]
@idoschor can you provide any example?
I made initial test with IE11 and Edge. Everything works fine.

**Comment by idoschor** [comment]
@lavrton 
http://codepen.io/anon/pen/averpd

**Comment by lavrton** [comment]
I tested your demo with last build from master (http://rawgit.com/konvajs/konva/master/konva.js). Works fine. @idoschor, can you confirm?

**Comment by idoschor** [comment]
Yes, with that build it works. Thanks!
