### ISSUE TITLE
Feature Request - Stroke position

### ISSUE THREAD

**Issue by Joebayld** [konvajs/konva#1061]
I'm wondering if there could be an API for stroke position. Currently, the stroke is centered along the path, but it could be useful for having the stroke inside or outside the shape. There was a previous issue that was similar that I'm referencing: 

https://github.com/konvajs/konva/issues/438

Here is a screenshot from the vector app Sketch. There are options for the stroke being inside, centered, or outside. 
![image](https://user-images.githubusercontent.com/9399317/107898889-bce17d00-6ef1-11eb-988d-a7d7cf44a522.png)

I know I can go around this by changing my rect position and size, but that seems like something that can be improved. Especially when dealing with a 1 pixel stroke, I would need to move my rect position to `x: 0.5, y: 0.5` for it to be inside...not too pretty. 

Proposed api would be: 
`strokePosition` or `strokeAlign: 'center' (default) | 'inside' | 'outside' `

Happy to hear your thoughts on this! 

Joe

**Comment by lavrton** [comment]
I don't think it is simply possible with 2d canvas API. Canvas is drawing stroke on `center`. And there are no ways to change the behavior. The only workaround is to use several shapes. One of the shapes is adjusted manually to draw the stroke.

Automatic calculations for "adjusted" shape inside the Konva framework will be too complex.
