### ISSUE TITLE
Line Pointer position issue after scaling the stage

### ISSUE THREAD

**Issue by Bilal14078** [konvajs/konva#1062]
Hi,

I'm facing an issue with line pointers after scaling the stage. Please see the following attached video
https://drive.google.com/file/d/1mFNtTgS1ClySIoVprVb7GItthcG4RMDb/view

I'm scaling the stage using my following function

makeCanvasResponsive() {
    var container = document.querySelector('#stage-parent');
    var containerWidth = container['offsetWidth'];
    const stageWidth = 1000;
    const stageHeight = 1000;
    var scale = containerWidth / stageWidth;
    this.stage.width(stageWidth * scale);
    this.stage.height(stageHeight * scale);
    this.stage.scale({ x: scale, y: scale });
    this.stage.draw();
  }

**Comment by lavrton** [comment]
If you use scaling you need to calculate the new line point differently. `stage.getPointerPosition()` returns the absolute position of the pointer relative top-left of the canvas element.

This post will help you: https://konvajs.org/docs/sandbox/Relative_Pointer_Position.html#page-title

**Comment by Bilal14078** [comment]
Alright thanks, I have fixed it using getRelativePointerPosition method,  can you please provide me link of any demo related to addition of straight lines in konva canvas ?


Thanks
