### ISSUE TITLE
Text area not showing keyboard on mobile

### ISSUE THREAD

**Issue by Bilal14078** [konvajs/konva#1063]
Hi,

When I click on text area in mobile, its not opening keyboard for typing text in it. 
Can you please suggest any solution for that?

Thanks

**Comment by lavrton** [comment]
What text area? DOM? Or `Konva.Text`?

**Comment by Bilal14078** [comment]
Konva.Text, please see the attached image

![image](https://user-images.githubusercontent.com/29977481/108380543-c25c0180-7228-11eb-9021-54bd795b65aa.png)

**Comment by lavrton** [comment]
`Konva.Text` is not editable. If you want to edit it (with a keyboard) you have to use DOM input or textarea. For demo see: https://konvajs.org/docs/sandbox/Editable_Text.html#page-title

**Comment by Bilal14078** [comment]
Yes I understand that when I double click on it it shows text area for input but it don't show that text area when I tap on it from mobile screen. I'm facing this issue in mobile but its working fine in desktop.

**Comment by lavrton** [comment]
Hard to say. It is not really Konva related.

**Comment by Bilal14078** [comment]
Even when I used text fields in the mentioned following link from mobile, they are still not showing text area, seems like it needs to trigger keyboard on tab
https://konvajs.org/docs/sandbox/Editable_Text.html#page-title 

Thanks

**Comment by lavrton** [comment]
I just slightly updated the demo to trigger mobile events. It works ok for me. I see a keyboard on mobile.

**Comment by Bilal14078** [comment]
alright thanks working fine now,  

Thanks for your quick replies :)
