### ISSUE TITLE
Slow performance once Transformer select multiple nodes

### ISSUE THREAD

**Issue by live9080** [konvajs/konva#1064]
Once lots of nodes was selected in the transformer, Any update will be very slow.

If no node was selcted:  20ms
If 1000 nodes was selected: 800ms 

Currently, I have to unselcted the nodes, then change the stage postion, then selcted the nodes agagin with a hack way.
Do we have a plan to optimize the performance in the near future? I don't think 1000 nodes should be a large data.
Or Am I using it the wrong way?  Thanks.

You could have preview link here: [demo](https://jsbin.com/dulaxikedo/edit?html,js,output)

**Comment by lavrton** [comment]
You are using it correctly.

> Do we have a plan to optimize the performance in the near future?

No, right now I don't see any simple ways to optimize it.

**Comment by live9080** [comment]
Got it. Thanks very much~

**Comment by zkobrinsky** [comment]
I'm also running into a transformer with a lot of nodes causing problems. Any updates on this?

**Comment by lavrton** [comment]
@zkobrinsky make a demo with the new issue opened.
