### ISSUE TITLE
Trigger mouseup or click event programmatically on konva.stage

### ISSUE THREAD

**Issue by Bilal14078** [konvajs/konva#1065]
Hi,

I'm unable to trigger events on konva stage programmatically, can you please inform me how can I trigger events programmatically ?

I'm using following method to dispatch event but its not working

stage.dispatchEvent(new Event('mousedown'));

Thanks

**Comment by lavrton** [comment]
Why do you need it?

**Comment by Bilal14078** [comment]
I need it in my code logic but I got it working now. Thanks
