### ISSUE TITLE
Konva Text position issue on page scroll

### ISSUE THREAD

**Issue by Bilal14078** [konvajs/konva#1068]
HI,

I'm facing an issue in text area position when I double click on konva text after scrolling my page then text area is jumped on top of whiteboard and doesnt match the position of konva text, although its working fine without scrolling page.  
I have also applied scaling on my konva stage.

Please see the following video for reference 
https://drive.google.com/file/d/1SnWUTi3O0zCmdEDh341RxRxVfNH9ifWL/view

Thanks

**Comment by lavrton** [comment]
The question is not really related to `Konva`. You just need to find a better way to position the DOM node over the stage. Do you use the absolute position of the text input?  Do you use the absolute position of a text node for the position of text input?

**Comment by Bilal14078** [comment]
Yes I'm doing same as you did in your demo i.e https://konvajs.org/docs/sandbox/Editable_Text.html

It was working fine before scroll on my page. seems your formula for calculating text area position depends on page body position.

**Comment by lavrton** [comment]
I slightly updated the demo for that case.
