### ISSUE TITLE
Allow removeChildren / destroyChildren methods to specify a filter

### ISSUE THREAD

**Issue by boyanio** [konvajs/konva#1069]
I have a layer that contains many shapes (of a different kind) and I want to destroy most of them. I am trying the following:

```
this.layer.getChildren().each((child) => {
  if (shouldDelete(child)) {
    child.destroy();
  }
});
this.layer.draw();
```

However, for some reason, not all shapes that meet the criterion are deleted afterward. So I am wondering if this is the correct way to do it.

Maybe we could allow `removeChildren` and `destroyChildren` to receive an optional filter. I could help with a PR.

**Comment by lavrton** [comment]
While you iterate and destroy, it may skip some children, because destroying is removing elements from an iteration array of children. As the solution, just filter first and then destroy;

```js
const childrenToDestroy = this.layer.getChildren().filter(child => shouldDelete(child));
childrenToDestroy.forEach(child => child.destroy());
```

**Comment by boyanio** [comment]
Thanks for the heads up! This would solve my issue, but I am still thinking when deleting many shapes if it would make sense to optimize it. I can see you do some optimizations in `destroyChildren`

**Comment by lavrton** [comment]
I don't have any plans to optimize that use case. Probably instead of destroying some children, it will be faster to:

1. Remove (not destroy) all children from the parent
2. Iterate over them, on iteration destroy a child OR add it back to the parent
