### ISSUE TITLE
cors error when inspect menu is closed, but everything works correctly when inspect menu is open 

### ISSUE THREAD

**Issue by clevermatem** [konvajs/konva#1070]
Hello, 
I had this weird error that I didn't understand its source:
-I am showing an image and applying filters like this :
`buildViewer = () => {
    this.stage = new Konva.Stage({ container: this.containerRef.current });
    this.stage.add(this.imageLayer);
    this.stage.add(this.annotationLayer);

    this.stage.on("click", (e) => {
      if (e.target.getClassName() === "Image") {
        this.transformer.nodes([]);
        this.activeShape?.findOne(".label").setAttr("visible", false);
        this.activeShape = null;
      } else {
        this.transformer.nodes([e.target]);
      }
    });

    this._shapeList = this.props.annotations.map((item) => {
      const rect = this.makeRect(item);
      this.annotationLayer.add(rect);
      return rect;
    });

    Konva.Image.fromURL(this.props.imageUrl, (bookImg) => {
      this.bookImg= bookImg;
      const parentHeight = this.props.parentContainer.current.offsetHeight;
      const parentWidth = this.props.parentContainer.current.offsetWidth;

      const widthScale = parentWidth / this.bookImg.width();
      this.stage.width(parentWidth);
      this.stage.height(parentHeight);
      this.fitStageIntoParentContainer();

      this.bookImg.width(parentWidth);
      this.bookImg.height(this.bookImg.height() * widthScale);

      this.bookImg.cache();
      this.bookImg.brightness(0);
      this.bookImg.contrast(0);
      this.bookImg.embossBlend(true);
      this.bookImg.embossDirection("top");
      this.bookImg.embossWhiteLevel(0);
      this.bookImg.embossStrength(0);

      this.bookImg.filters([
        Konva.Filters.Brighten, // -1 and 1.
        Konva.Filters.Contrast, //-100 and 100
        Konva.Filters.Emboss, //0 and 100 (limited to 20)
      ]);

      this.imageLayer.add(this.bookImg);

      this.imageLayer.draw();
      this.annotationLayer.draw();
    }
    
    );
    this.annotationLayer.batchDraw();
  };`

`  componentDidMount = () => {
    this.annotationLayer.add(this.transformer);
    this.buildViewer();
    window.addEventListener("resize", this.fitStageIntoParentContainer);
  };`

I use AWS S3 bucket this is my cors rules :
`[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "PUT",
            "POST",
            "DELETE"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [
            "x-amz-server-side-encryption",
            "x-amz-request-id",
            "x-amz-id-2"
        ],
        "MaxAgeSeconds": 3000
    }
]`

 everything works perfectly when chrome's  inspect menu is open, 
when it's closed the image doesn't load and I get these 2 errors:

*Access to image at 'https://my_own_aws_s3_bucket/my_image' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

*Failed to load resource: net::ERR_FAILED

BUT everything works completely fine when inspect menu is open and no errors are thrown.

**Comment by lavrton** [comment]
It may be blocked, because of the cache used in the browser. Try to reset the cache, or change the URL to force cache reset.

Take a look here: https://stackoverflow.com/questions/44800431/caching-effect-on-cors-no-access-control-allow-origin-header-is-present-on-th

I am closing the issue because it is not related to Konva.

**Comment by clevermatem** [comment]
ok thank you,
