### ISSUE TITLE
Defining Canvas boundary issue

### ISSUE THREAD

**Issue by Bilal14078** [konvajs/konva#1071]
Hi,

I'm unable to set any boundary of canvas like when I drag shape out of the canvas then I'm not able to redrag it into the canvas. 
Is there any way to stop dragging shapes out of the canvas.

Please see the following video for reference.
https://drive.google.com/file/d/1Iq3ZpAOoxCZ5HAPpAc8QXDNXxQUhS-4B/view

Thanks

**Comment by lavrton** [comment]
https://konvajs.org/docs/drag_and_drop/Simple_Drag_Bounds.html

https://konvajs.org/docs/drag_and_drop/Complex_Drag_and_Drop.html

**Comment by Bilal14078** [comment]
What If I want to bound drag on complete stage as I'm not using groups and in other case if I apply dragBoundFunc direct on shape then what should I do set bound in square boundary as you are doing with circular boundary ?

**Comment by lavrton** [comment]
Sorry, I don't understand your question.

Also take a look at this demo: https://jsbin.com/gakelemuru/edit?js,output
