### ISSUE TITLE
How to use hitStrokeWidth in Transformer

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/konva#1072]
I'm using Transformer in that how can I apply hitStrokeWidth for the Transformer.

**Comment by lavrton** [comment]
Why do you need it?

**Comment by mdmusaib** [comment]
Because I'm not able to transform the shape from near anchor point , but it is transforming from the exact anchor point not from the nearest anchor point.

**Comment by lavrton** [comment]
```js
transformer.find('._anchor').hitStrokeWidth(20);
```
