### ISSUE TITLE
Name feature slow when destroying shapes

### ISSUE THREAD

**Issue by VanquishedWombat** [konvajs/konva#1073]
Konva has the excellent 'name' feature, where we can assign an arbitrary and non-unique name to a shape like we can assign class names to an html element in css.  The find() function then allows us to find shapes with a given name. 

Issue:
====

The problem comes when we call destroychildren or destroy.

Line 40 of Node.ts shows:
```
export const _addName = function (node: any, name: string) {
  if (name) {
    if (!names[name]) {
      names[name] = [];
    }
    names[name].push(node);
  }
};

export const _removeName = function (name: string, _id: number) {
  if (!name) {
    return;
  }
  var nodes = names[name];
  if (!nodes) {
    return;
  }
  for (var n = 0; n < nodes.length; n++) {
    var no = nodes[n];
    if (no._id === _id) {
      nodes.splice(n, 1);
    }
  }
  if (nodes.length === 0) {
    delete names[name];
  }
}; 
```
In _addName we can see the name being added to the names object as a new array, and the id of the object being assigned the name is then pushed into the array.

The problem comes with the for-next loop in the _removeName function. Where there are a large number of shapes with the same name and the for-next loop is used to drive a comparison identifying the object to be removed via its id.  The for-next process can take a long time. A case with 12k objects can remove the objects in 60ms if there is no name assignment to shapes, but takes 10seconds+ where they are assigned the same name. See https://codepen.io/JEE42/pen/xxRpJdR.

Potential fix
========

Instead of using array storage for assignment of names, us an object. 

_addName would change as below. The critical alteration is that the names[name] item is now an object, not an array. This is followed in the assignment of the node id into the object.
```
export const _addName = function (node: any, name: string) {
  if (name) {
    if (!names[name]) {
      names[name] = {};
    }
    names[name].[node.id] = node.id;
  }
};
```
_removeName  is then altered to remove the object instance in the names list as 
```
delete names[name].[node.id];
```
This removes the need for the costly for-next loop in the remove step. Elsewhere in the codebase, if it is necessary to iterate over the objects in a names list then we can use the object entries approach - see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries.

**Comment by lavrton** [comment]
We can do something much better here. Just remove `_addName`, `_removeName`, `_addId` and `_removeId` functions. A long time ago all names and ids were registered into a special object for indexing and faster search. But was not giving much perf benefits and had some unexpected behavior. So `find` methods in not using the index anymore. But I saved it just for fewer breaking changes.

So I think we should just get rid of all these functions.

**Comment by VanquishedWombat** [comment]
That sounds interesting - is the indexing code in the current code base, I am interested to see how it works?

**Comment by lavrton** [comment]
Well, it is not that interesting. For example this is id register:

```js
const _addId = function (node: Node, id: string | undefined) {
  if (!id) {
    return;
  }
  ids[id] = node;
};
```

The idea that next time you want to search an element with some id you don't need to check all the children, just do this:

```js
Container.prototype.findById = function (id) {
   // instead of checking everything child just do this
   const node = ids[id];
   if (this.isParentOf(node)) {
      return node;
   }
   return false;
}
```

Now every time you have any changes in `id` attribute you just need to update the index with `_addId` or `_removeId`.

That approach is fast but has many other issues, so I removed it and checking all children.
