### ISSUE TITLE
Right click while dragging not registering properly

### ISSUE THREAD

**Issue by Joebayld** [konvajs/konva#1076]
So my issue is kind of two parts. 

First off - I'm using `vue-konva`, and I only want to get the left mouse clicks. And when doing the event `@mousedown.left="onMouseDown"`, right clicks are still registering. Is that normal? 

ALSO - the bigger issue I'm having. 

I use events on the stage to help manage selection, however, when dragging an item THEN right clicking on the item as you're dragging it, the stage click handler isn't properly formatted. It seems to be missing the target that you're dragging. 

In vue, the `target` and the `currentTarget` are both the stage, but the `target` should still be the object I'm dragging as that's what I'm clicking. Example link below, try dragging the circle with your left mouse button, and while dragging, right click on it. This interruption is A: something I want to ignore, and B: should still be registering the target properly as the circle.

https://jsbin.com/poqutikani/3/edit?js,console,output
![image](https://user-images.githubusercontent.com/9399317/109372587-1d13df80-785f-11eb-9708-7f35d6bb64e8.png)

**Comment by lavrton** [comment]
About the first issue, `vue-konva` doesn't support modifiers right now https://github.com/konvajs/vue-konva/issues/98. But you can check `e.evt.button` manually.

About the second issue, by default Konva is disabling the hit graph on drag for performance reasons. Clicking while dragging is a super rare use case (why do you need it?). To enable hit graph you can do this: `Konva.hitOnDragEnabled = true`.
