### ISSUE TITLE
Scaling SVG in Firefox

### ISSUE THREAD

**Issue by bollerdominik** [konvajs/konva#1077]
Hi
I am trying to place a svg in my stage as described in #677

I was able to render the SVG in Firefox. However, It does not transform correctly. I can make it larger and rotate it but I can not resize it in only one direction (e.g. increase its height). It always maintains the original aspect ratio. 

The same stage in Chrome allows me to resize the SVG without keeping the aspect ratio. Which is what I want.

I know this is probably a Firefox limitation but I am wondering if there is any solution for this in Konva. Thanks.

**Comment by lavrton** [comment]
Yes. The workaround is simple. Instead of using an SVG image directly on the canvas, draw it into an external canvas instead. Then use that canvas. Like this:

```js
const img = new window.Image();
img.onload = () => {
  const canvas = document.createElement('canvas');
  canvas.width = img.width;
  canvas.height = img.height;
  canvas.getContext('2d').drawImage(img, 0, 0);
  const image = new Konva.Image({ image: canvas });
  layer.add(image);
}
img.src = yourSVGPath;
```

I hope it helps.

**Comment by bollerdominik** [comment]
Thanks for the quick reply. This works but it ends up with the SVG becoming blurry when resizing. I guess because I am resizing a canvas now and not a SVG.

**Comment by lavrton** [comment]
Yes. In that case you can make a bigger canvas upfront, or update it on resize end:

```js
const scale = 2;
const canvas = document.createElement('canvas');
canvas.width = img.width * scale;
canvas.height = img.height * scale;
canvas.getContext('2d').drawImage(img, 0, 0);
const image = new Konva.Image({ image: canvas, width: img.width, height: img.height });
  ```

**Comment by VictorCazanave** [comment]
Another solution, that worked for me, is to add the `preserveAspectRatio="none"` attribute to `<svg>` ([source](https://stackoverflow.com/a/50144772))
