### ISSUE TITLE
Drawing shapes in real time

### ISSUE THREAD

**Issue by roshansachan** [konvajs/konva#1078]
Is there a way to draw shapes in real-time?  Instead of dropping the rectangle with predefined width and height, can we draw a shape as the user drags the mouse on canvas?

https://user-images.githubusercontent.com/4952904/109598012-65bce880-7b3e-11eb-9e05-c07ca6cf66e6.mov

**Comment by tom-richter** [comment]
Why was this issue closed? I would also appreciate a feature like this!

**Comment by lavrton** [comment]
This demo has an example of such behavior: https://konvajs.org/docs/select_and_transform/Basic_demo.html

**Comment by abbeytekmd** [comment]
I also am trying to implement this. The demo you reference has an issue in that if you start to draw the rect but drag out of the bounds of the canvas and release the mouse button, the rect is not completed. Furthermore, if you move the cursor back into the bounds of the canvas, the rectangle is still tracking even though you don't have the mouse button down.

**Comment by lavrton** [comment]
Instead of listening to events on stage, you can listen to them on `window`.

**Comment by abbeytekmd** [comment]
Looking for the mouseup event on the window enables us to complete the rect creation so that's great, thanks for the suggestion and your super quick response.
