### ISSUE TITLE
Blurry text

### ISSUE THREAD

**Issue by baole** [konvajs/konva#1079]
I have an issue with Text element. The text is blurred in compare with HTML's text area (see below screenshot)

![image](https://user-images.githubusercontent.com/1460168/110139119-fc093c80-7dd2-11eb-98b3-53cfa381d2d2.png)

The text drawn with Konva

 ```
       this.textNode = new Text({
            x: x,
            y: y,
            width: w,
            height: h,
            lineHeight: 1.2,
            fontSize: 16,
            text: 'Konva text',
            fill: 'black',
            draggable: false,
        })

```
The HTML's text area counterpart is copy most attributes from Konvas Text (inspiring https://konvajs.org/docs/sandbox/Editable_Text.html)

```
            textarea.value = this.textNode.text();
            textarea.style.position = 'absolute';
            textarea.style.top = areaPosition.y + 'px';
            textarea.style.left = areaPosition.x + 'px';
            textarea.style.width = this.withScale(this.textNode.width() - this.textNode.padding() * 2) + 'px';
            textarea.style.height = this.withScale(this.textNode.height() - this.textNode.padding() * 2) + 'px';
            textarea.style.lineHeight = this.withScale(this.textNode.fontSize() * this.LINE_SPACING) + "px";
            textarea.style.fontSize = this.withScale(this.textNode.fontSize()) + 'px';
            textarea.style.border = 'none';
            textarea.style.padding = '0px';
            textarea.style.margin = '0px';
            textarea.style.overflow = 'hidden';
            textarea.style.backgroundColor = this.config.zone.stickerColor;
            textarea.style.outline = 'none';
            textarea.style.resize = 'none';
            textarea.style.fontFamily = this.textNode.fontFamily();
            textarea.style.transformOrigin = 'left top';
            textarea.style.textAlign = this.textNode.align();
            textarea.style.color = this.textNode.fill();
```

I tried with different fonts/custom fonts and alternative settings from [Text class](https://konvajs.org/api/Konva.Text.html), but it's still not working.

What could be an issue? How can I fix it?

It's tested on Mac OS/ Chrome and Safari browsers.

**Comment by lavrton** [comment]
Did you cache the text? Did you scale the webpage? Did you scale canvas elements with CSS?

**Comment by baole** [comment]
Hi @lavrton I tried with both `this.textNode.cache()` and without it. No scale in any level (i.e. webpage, stage, canvas, css)

**Comment by lavrton** [comment]
Strange. Can you make an online demo? I don't have any blurs here: https://konvajs.org/docs/sandbox/Editable_Text.html#page-title

**Comment by baole** [comment]
I found the issue. Pixel radio was set to fix a drag lagging: 

`Konva.pixelRatio = 1`

When I removed the above line, the text renders are identical.

**Comment by lavrton** [comment]
Yeah, it is better to find another ways to improve the performance.
