### ISSUE TITLE
[Feature Request] - Rect Stroke, StrokeWidth, StrokeEnabled with different values

### ISSUE THREAD

**Issue by Albert-cord** [konvajs/konva#1080]
Hi, I have a feature request.  
Currently only set with or without stroke, but i need change the stroke with different values on each side of the Rect object.  
Can implement an additional object? Just like this:  
stroke?: String | { top: String, left: String, bottom: String, right: String};  
strokeWidth?: number | { top: number, left: number, bottom: number, right: number };  
strokeEnabled?: Boolean| { top: Boolean, left: Boolean, bottom: Boolean, right: Boolean};  
Or set it as shown in the figure below, just like setting CSS Properties:  
![image](https://user-images.githubusercontent.com/31922224/110209935-3275b300-7eca-11eb-87dc-3f11b7d7e4de.png)

**Comment by lavrton** [comment]
Thanks for your request. But I don't want to add such a feature into Konva core. The use case is too rare. And it may reduce the performance and complicate the API.

If you really need it you can:

1. Use several `Konva.Lines` with different strokes and put them into a group
2. Create your own custom shape and draw such strokes manually with direct 2d canvas API.
