### ISSUE TITLE
No 'fontKerning' atrribute in Text class

### ISSUE THREAD

**Issue by xenny** [konvajs/konva#1081]
Hi Anton,

I've come across a weird @font-face issue which causes wrong spacing between certain characters of a font on the web.
As it turns out that one can be fixed by setting 'noKerning' to 'none'. 
Screenshots of a textarea with noKerning set to 'none' and a Konva.Text instance with the same font selected are attached.

Since there's no such attribute in Text class, inconsistent spacing keep occurring
Can you please add '**noKerning**' attribute to Konva.Text?

![Screenshot from 2021-03-08 12-07-13](https://user-images.githubusercontent.com/5171114/110265484-64d8fa80-8007-11eb-8280-b848583fd345.png)
![Screenshot from 2021-03-08 12-07-28](https://user-images.githubusercontent.com/5171114/110265490-66a2be00-8007-11eb-92f4-71df5b4452f0.png)

**Comment by lavrton** [comment]
Try to use the `letterSpacing` property for that. You can set any small non-zero value like `text.letterSpacing(0.000001)`.

**Comment by xenny** [comment]
Thanks very much! It does the trick.
