### ISSUE TITLE
star element wrong formation

### ISSUE THREAD

**Issue by goldenjayr** [konvajs/konva#1082]
Does anyone have any idea what happened to this star? I was using konva-node and replicating that photo in the backend. 

`new Konva.Star(element)`

Output Image
![Screenshot from 2021-03-11 11-16-42](https://user-images.githubusercontent.com/37247707/110730630-bb3e7700-825b-11eb-8fe7-272a92d96718.png)

Expected Image
![Screenshot from 2021-03-11 11-22-15](https://user-images.githubusercontent.com/37247707/110730812-17090000-825c-11eb-8fe2-adea75d2c0a0.png)

**Comment by lavrton** [comment]
Can you make a small script with a demo for `konva-node`?
