### ISSUE TITLE
Scale transform not propagated on draggable group until after drag

### ISSUE THREAD

**Issue by Trinovantes** [konvajs/konva#1083]
https://jsfiddle.net/v4ru37nd/

If I set a global scale factor on my canvas, the scaling doesn't seem to be propagating to the child draggable group until after I drag the group

**Before drag/initial render**
![before-drag](https://user-images.githubusercontent.com/458691/110917827-59781e80-82e8-11eb-9b90-475a86cc0d07.png)

**After drag (expected appearance)**
![after-drag](https://user-images.githubusercontent.com/458691/110917825-58df8800-82e8-11eb-89ce-8545a7a7b6df.png)

---

As a side note, when I change the order of adding layer to stage, the scale no longer applies at all. Is this expected behavior? 

```diff
-stage.add(layer)
layer.add(bg)
layer.add(group)
+stage.add(layer)
```

**Comment by lavrton** [comment]
You should attach the transformer after the node was added to the parent container. So Transformer can know the absolute size of the node.

Or call `transformer.forceUpdate()` to recalculate position when all nodes are in the stage.
