### ISSUE TITLE
toImage() filed with "Global_1.glob.Image is not a constructor"

### ISSUE THREAD

**Issue by spidgorny** [konvajs/konva#1084]
I'm using [konva-node](https://www.npmjs.com/package/konva-node) for rendering image to PNG on the server.
```toImage()``` doesn't work for me with error "Global_1.glob.Image is not a constructor"

Quick workaround: get image URL (base64) and convert it back to the binary image with https://github.com/DiegoZoracKy/image-data-uri.

```
		const base64 = await toDataURL(stage);
		const decode = ImageDataURI.decode(base64);
		const result = decode.dataBuffer;
		const mime = decode.imageType ?? "image/png";

		res.status(200).setHeader("content-type", mime);
		res.send(result);
```

**Comment by spidgorny** [comment]
Maybe it will fix it?
```
		Konva.Util._urlToImage = (url, callback) => {
			const imageObj = Konva.Util.createImageElement();
			imageObj.onload = function () {
				callback(imageObj);
			};
			imageObj.src = url;
		};
```

**Comment by lavrton** [comment]
Yes. it is a correct fix. Do you want to make a Pull Request?
