### ISSUE TITLE
How to detect if a Node (at least some part of it) is truly visible on the screen

### ISSUE THREAD

**Issue by AlexIII** [konvajs/konva#1086]
Hi! 
How can I check if a Node is currently visible on the screen, i.e. it is not completely outside of the boundary of the hosting canvas? It is useful for optimization, such as not drawing the parts that are falling out of user-visible area.

**Upd**
For now I solved it like this
```typescript
const isOnScreen = (testNode: Konva.Node) => {
    if(!testNode.isVisible()) return false;
    type Rect = {[k in 'x'|'y'|'width'|'height']: number};
    const haveIntersection = (r1: Rect, r2: Rect) => !(
        r2.x > r1.x + r1.width ||
        r2.x + r2.width < r1.x ||
        r2.y > r1.y + r1.height ||
        r2.y + r2.height < r1.y
    );
    const stage = testNode.getStage();
    if(!stage) return false;
    const screenRect = {
        x: -stage.x() / stage.scaleX(),
        y: -stage.y() / stage.scaleY(),
        width: stage.width() / stage.scaleX(),
        height: stage.height() / stage.scaleY()
    };
    return haveIntersection(screenRect, testNode.getClientRect({relativeTo: stage as any}));
};     
```

Is it good enough to be added in `Node` as a method? Would you be interested in PR? (Provided, there is no existing solution that I missed.)
Also notice how I had to cast `stage` to `any` in `getClientRect()` call. The typing seems to be not ok...

**Comment by lavrton** [comment]
Yeah, probably it can be a part of the core. But the function has to be a bit more complicated. The most common use case is to use some "padding" in "out of the screen" calculations. So if the object is not visible on the screen, but too close to the edge it still be should be marked as visible. 

Such trick allows much more efficient checks because we need to make them less frequently.

**Comment by AlexIII** [comment]
> The most common use case is to use some "padding" in "out of the screen" calculations.

Ok, that's no problem. The API will be 
```typescript
class Node {
...
isOnScreen(margin: number | {x: number, y: number}) { ... }
...
}
```
What's your minimal checklist for a PR?

**Comment by lavrton** [comment]
Merged.

**Comment by AlexIII** [comment]
Cool, thanks!
