### ISSUE TITLE
Request: Please make the property "clickStartShape" on Stage accessible in some way

### ISSUE THREAD

**Issue by Nairam** [konvajs/konva#1088]
I'm trying to implement a certain behaviour where I have a layer with different shapes as children and only enable dragging the parent layer when dragging a certain children shape. Without identifying/accessing the "click start shape"-property I cannot on which shape the "drag start event" was started. 
Thanks for consideration!

**Comment by lavrton** [comment]
> property I cannot on which shape the "drag start event" was started

You can just fine:

```js
layer.on('dragstart', (e) => {
   const startShape = e.target;
});
```
