### ISSUE TITLE
event parameter missing on DragBoundFunc call

### ISSUE THREAD

**Issue by rfm1201** [konvajs/konva#109]
The Konva.Node.prototype.startDrag is always called with an event parameter but the parameter is missing on the function signature.
It's a shame because it can't internally call _setDragPosition with the event parameter and the user (me) don't receive the event parameter in his DragBoundFunc function.
Can you check that?
Thank you

**Comment by lavrton** [comment]
Why do you need event object in `dragBoundFunc`?

**Comment by rfm1201** [comment]
I have a grid behind what the user draw.
When the user moves an object, It is possible to move the object freely or just on the grid.
The choice is made by the use of the shift key (it's in the specifications I have to code).
So I need to know if shiftKey is true or false. I tried to use a variable set by other way, but I always found cases where the variable was not correctly synchronized.
With the modification I ask (and made in my local version) the only problem is that sometimes the event parameter is the mouse event and sometimes one of your events. I simply need to test "evt.evt"  and set evt to "evt.evt", if needed, before the test of "evt.shiftKey".

**Comment by lavrton** [comment]
I see. Good suggestion.
As workaround you can do this logic inside `dragmove` event:
```javascript
node.on('dragmove', (e) => {
       if (!e.evt.shiftKey) { return; }
        const pos = e.target.getStage().getPointerPosition();
        const x = roundBy(pos.x, gridSize);
        const y = roundBy(pos.y, gridSize);
        e.target.position({x, y});
    });
```

**Comment by rfm1201** [comment]
The workaround is not needed on dragmove because DragBoundFunc get the event in that case.

In my case, the object (a circle that stand for a point of a curve) must stay on the lines of the grid when shift in pressed when you move it.

So what happens when you click on the circle ?
DragBoundFunc is called, but without the event parameter. If I change le position in DragBoundFunc, the point is moved to the new position but the dragstart event is never sent.

I think it's because you need to know if a drag & drop is starting or a click is starting.
You take your decision when the mouse is moved more than dragDistance pixels no matter what DragBoundFunc do.

I think you are right, but should not call DragBoundFunc on the click. You should wait for a drag & drop to start.

So now I test the event parameter of DragBoundFunc and if it's null I don't do anything in DragBoundFunc.
It works as excpected.

**Comment by lavrton** [comment]
Closing the issue for now. Still now sure what is a use case. Also, dragging is slightly changed now.
