### ISSUE TITLE
Build Error in TypeScript

### ISSUE THREAD

**Issue by SamXiao** [konvajs/konva#1090]
I import konva into a ts file
`
import Konva from 'konva';
 this.stage = new Konva.Stage({
            container: container,
            width: width,
            height: height,
        });
`

then I build this file to js
`tsc ./src/CanvasStage.ts`

Got error when I use this js file 
`TypeError: Cannot read property 'Stage' of undefined`

this is my js file builded

`"use strict";
exports.__esModule = true;
var konva_1 = require("konva");
this.stage = new konva_1["default"].Stage({
            container: container,
            width: width,
            height: height
        });`

and this is my tsconfig
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "es6",
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}

**Comment by lavrton** [comment]
Please make a small repository with a reproducible issue.
