### ISSUE TITLE
[Feature request] Provide an esm distribution

### ISSUE THREAD

**Issue by WhoAteDaCake** [konvajs/konva#1091]
If a user wants to use this library with [vitejs](https://vitejs.dev/), an es6 (.mjs) export would be required. It shouldn't be too much work, I could submit a pull request if this is okay to be implemented.

Thank you for your work on this project!

**Comment by lavrton** [comment]
Vitejs supports CommonJS modules, no?

**Comment by WhoAteDaCake** [comment]
It does yes, however, I've had problems with trying to use konva with it. Because the main module in package.json directs to `./lib/index.js`, it kept throwing an error saying `require is not defined`. The only way I've solved it was by changing that main module to `./konva.js`. I was hoping that adding ESM entries would resolve it without requiring a manual fix.

**Comment by stefnotch** [comment]
Same issue. Ideally, modern packages [should drop CommonJS support](https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77), since that's a very outdated solution by now.

**Comment by lavrton** [comment]
Can someone create a small repository with a demonstration of the issue? With the vite or something else. I am going to work on es build. And a reproducible issue will help me a lot.

**Comment by lavrton** [comment]
Done with `konva@8`. Try it. Let me know how it works.
