### ISSUE TITLE
Flipping image flips the transform bounding box anchors

### ISSUE THREAD

**Issue by nicotejera** [konvajs/konva#1092]
When transforming an image (resizing horizontally) I want the image to be flipped if I go shrink it and continue over. This works but then immediately after, when I try to drag the image, or even clicking it, the anchors get flipped vertically too. I noticed in the example the boundBoxFunc is restricted so that it doesn't take negative values, but this prevents the image from flipping. How can I fix this? 

REPL here: https://replit.com/@nicotejera/KonvaIssue

**Comment by lavrton** [comment]
I don't see any good solution for it now.

You may need to manually control rotation of the transformer.

```js
      onTransformEnd={() => {
          const node = shapeRef.current;
          trRef.current.rotation(node.rotation());
          trRef.current.forceUpdate();
          onChange({
            ...shapeProps,
            x: node.x(),
            y: node.y(),
            rotation: node.rotation(),
            scaleX: node.scaleX(),
            scaleY: node.scaleY(),
          });
        }}
```

**Comment by Loukay** [comment]
For anyone who might visit this issue, the simplest fix is to set the transformer's prop "useSingleNodeRotation" to false.

**Comment by prosagar-ggs** [comment]
I am working with konva for quite some weeks now.

I do have an issue while trying to mirror an image. Setting scaleX is working as expected, and it is mirrored on the vertical axis.

Moreover, I do have an issue (either a bug or understanding) with a transformer that I want to attack to the node. I create it after the image, meaning the flipping is already in place. But the rotation anchor is set down of the image, and not top of the image as usual.

Is there a workaround to this?

Here are examples of what I do in my code concerning the transformer:

const transformer = new Konva.Transformer({
    nodes: [image],
    flipEnabled: false,
    rotateEnabled: true,
    enabledAnchors: ["top-left", "top-right", "bottom-left", "bottom-right", "top-center", "middle-left", "middle-right", "bottom-center"],
});

**Comment by moaazbhnas228** [comment]
@abdelmalekkkkk 
> For anyone who may be facing this problem, the simplest fix is to set the transformer's prop "useSingleNodeRotation" to false.

But now if I save the node rotation data somewhere (local storage / database), and then return back to edit, the transformer won't take the node's rotation.
![image](https://github.com/user-attachments/assets/1086ef03-4cc9-44ca-987c-d0d201efeff3)

Actually this will happen if you just toggle the visibility state of the transformer.

**Comment by merunus** [comment]
> [@abdelmalekkkkk](https://github.com/abdelmalekkkkk)
> 
> > For anyone who may be facing this problem, the simplest fix is to set the transformer's prop "useSingleNodeRotation" to false.
> 
> But now if I save the node rotation data somewhere (local storage / database), and then return back to edit, the transformer won't take the node's rotation.
> 
> ![image](https://github.com/user-attachments/assets/1086ef03-4cc9-44ca-987c-d0d201efeff3)
> 
> Actually this will happen if you just toggle the visibility state of the transformer.

Having the same problem, can this issue be reopened?
