### ISSUE TITLE
real time purposes

### ISSUE THREAD

**Issue by yalda-student** [konvajs/konva#1093]
Hi
I have a question about this framework. 
Is this suitable for real time purposes? I want  to use peak.js library that use konva framework but it doesn't support live recording. I try doing this but after some seconds I had problem in scrolling while recording audio. My question is that may it be because of konva (can we use it for real time charts and things like that? )? or the reason is sth else.
 I searched a lot but I didn't find any thing about use this framework for real time charts.

thank you in advance :)

**Comment by lavrton** [comment]
Yes. You can do that with Konva. Konva is just drawing what you asking for. You should care about the performance.
