### ISSUE TITLE
React DoubleClick event propagation can't be stopped in shapes mouse handler

### ISSUE THREAD

**Issue by dgrechka** [konvajs/konva#1094]
The issue is that current implementation of events on `react-konva` does not use React synthetic events but just wraps `konvajs` events.

That does not play well with React synthetic events handling logic.

For instance, we can't stop propagation of *React* onDoubleClick synthetic event in a mouse event handler of konva shape.
See repro bellow.

## Repro

1. Open https://codesandbox.io/s/react-konva-events-l2u2e
2. Do double click on the red rect
3. see the console messages.

**Expected**: Both mouseDown and doubleClick events are handled by konva shape handler. their propagation is stopped. Corresponding handlers in react wrapper are not called.

**Observed**: Only mouseDown event propagation is stopped. doubleClick  event propagation is NOT stopped,  react wrapper is executed.

**Comment by dgrechka** [comment]
Thanks for the quick reply.

Can you give any advice of how can I prevent React (seems to be based on native `dblclick` event) from propagating in the konva shape `onDblClick` event handler?

Thinking of workaround...

Is it possible to get the konva `<Layer />` underlying canvas object reference in React-konva app?


I want to try to attach native `dblclick` handler to the specific canvas and do `stopProppagation()` as a workaround to block the native double clicks for the entire canvas.

**Comment by lavrton** [comment]
Why do you need that?

**Comment by dgrechka** [comment]
I use the https://github.com/rowsncolumns/grid (based on `react-konva`) to render some grid data.
This library uses React `onDoubleClick` event handler (attached to the container which nests the konva stage) to spawn some non-konva control over the konva stage with the proper placement and positioning (similar to the approach adviced in [DOM Portal](https://konvajs.org/docs/react/DOM_Portal.html) section of react-konva docs).
Also this library provides a way to inject arbitrary konva shapes (with possible interactivity enabled).

What I want is to utilize the konva event handling in my custom injected shapes (e.g. handle some clicks), but prevent outer React component to react on already handled double clicks.

**Comment by dgrechka** [comment]
@lavrton , Is there a reason not to use native `dblclick` in konva double clicks implementation?

**Comment by lavrton** [comment]
That is a good question. I don't really remember.

As a workaround you can manually listen to `dblclick` on the parent div of Konva stage, check the intersection with a shape, if it is your custom shape, then stop propagation.

**Comment by lavrton** [comment]
I am going to close the issue for now as not a priority. At the current moment `Konva` is just listening to `mouseup`, `touchend` events to trigger dblclick/dbltap.

**Comment by dgrechka** [comment]
As you decide.

But as for me the issue persists.

It limits the usage of react-konva (I originally created the issue there) as it is impossible right now to stop double click propagation for react in konva shapes. Double clicks are passed further along the React DOM tree.
