### ISSUE TITLE
Issues loading big/large images on the canvas

### ISSUE THREAD

**Issue by RickvanB** [konvajs/konva#1095]
Hi,

After some research we found that Konva suits our needs for annotating images.  After implementing the framework we found out that some images that are really big/large, don't load in the canvas provided by Konva. Example image: https://imgur.com/a/74Eb18Z. 

Because we don't have any influence in what kind of images are loaded from the blob storage from the client, it's important that every image gets loaded correctly.

Is there any way to solve this or is there a workaround available? We would really like to stick to this framework.

**Comment by friksa** [comment]
We do not have this issue with Konva... you may want to post a way to recreate your issue.

**Comment by RickvanB** [comment]
@friksa can you load the image in your canvas? We use base64 strings.
This is our code:
`var konvaElement = document.getElementById('konva').getBoundingClientRect();
                    var layer = new Konva.Layer();
                    stage.add(layer);

                    // main API:
                    var imageObj = new Image();
                    imageObj.src = "data:image/png;base64," + result.asset;

                    imageObj.onload = function () {

                        var width = imageObj.width;
                        var height = imageObj.height;
                        var minusWidth = 0;

                        // Scale asset for the max height of the canvas
                        if (height > konvaElement.height) {
                            height = konvaElement.height;
                            minusWidth = imageObj.width * (konvaElement.height / parseFloat(imageObj.height.toString()));
                            width = minusWidth;
                        }

                        // Rescale asset if the with is now bigger than the with of the canvas
                        // Keep the earlier scaled values in mind :)
                        if (width > konvaElement.width) {
                            width = konvaElement.width - minusWidth;
                            height = height * ((konvaElement.width - minusWidth) / parseFloat(imageObj.width.toString()));
                        }

                        var asset = new Konva.Image({
                            x: 0,
                            y: 0,
                            image: imageObj,
                            width: width,
                            height: height,
                            draggable: true,
                        });
                        asset.cache({ pixelRatio: getCachePixelRatio()})

                        var defaultPos = {
                            x: 0,
                            y: 0,
                        };

                        stage.scale({ x: 1.0, y: 1.0 })
                        stage.position(defaultPos);
                        
                        stage.width(width);
                        stage.height(height);
                        stage.draw();
            
                        // add the shape to the layer
                        layer.add(asset);
                        layer.batchDraw();
                    };`

**Comment by friksa** [comment]
No problem loading the image.  Is there a reason to use Base64?

**Comment by friksa** [comment]
I notice that the image is of type webp and not PNG.  That might be your issue since you specify PNG and not all browsers support webp.

**Comment by RickvanB** [comment]
@friksa 
> No problem loading the image. Is there a reason to use Base64?

That is really strange, I just tried it with a jpg in the root folder of our project and it still doesn't work. It's because it is from a blog storage. We need to handle it via server side instead of local, it was one of our requirements.

**Comment by friksa** [comment]
Try this to convert it to a binary image and using that instead
```
  imageToBin(base64Image: string): Blob {
    const binStr = atob(base64Image.split(',')[1]);
    const len = binStr.length;
    const arr = new Uint8Array(len);

    for (let i = 0; i < len; i++) {
      arr[i] = binStr.charCodeAt(i);
    }

    return new Blob([arr], {type: IMAGE_FORMAT});
  }
```

**Comment by RickvanB** [comment]
@friksa We get a blob from Azure, which we convert to a base64 string, because the .src property expects a string. I also tried downloading the image from Imgurl and put it inside the root of our project, but it appears that still not works.

**Comment by RickvanB** [comment]
@friksa & others reading:
After some further investigation there's something wrong with our scaling calculation. Some images have a negative width and height. If I remove those lines of code the image(s) show up.
