### ISSUE TITLE
Pinch Zoom jumps "randomly"

### ISSUE THREAD

**Issue by Jomik** [konvajs/konva#1096]
I have copied the code from https://konvajs.org/docs/sandbox/Multi-touch_Scale_Stage.html to enable pinch zooming, and panning, on my stage.
But now I experience that my Stage jumps at times, when I pinch. It seems like the center changes.
Removing `draggable` from the Stage fixes the issue, but is not a wanted solution, as dragging with two fingers is a bit wonky, and I would like to use draggable on desktop browsers as well.
My refactored implementation can be seen here: https://github.com/Jomik/Valetudo-UI/blob/6536d4f43adec061525c20ab859849c1a5cb4ff0/src/map/MapStage.tsx#L177
But I have also tried simply copy-pasting your snippet from the example directly, to ensure I did not mess something up.

**Comment by lavrton** [comment]
As I can see you already cancel the drag:
```js
if (stage.isDragging()) {
        stage.stopDrag();
}
```

Doesn't it fix the issue?

**Comment by lavrton** [comment]
Also, you can just disable dragging on the `touchstart`. Just check if there are two fingers.

**Comment by Jomik** [comment]
No, the `stopDrag` did not fix it.
Would I have to disable dragging in `touchstart` and then enable again in `touchend`? 🤔

**Comment by lavrton** [comment]
> Would I have to disable dragging in touchstart and then enable again in touchend

Yes.
