### ISSUE TITLE
fillPatternOffset on an image cause shifting the whole image instead of the pattern image

### ISSUE THREAD

**Issue by hxdev** [konvajs/konva#1097]
I'm trying to fillPatternImage into an image but it seems the fillPatternOffset works not correctly.
I want to shift the lion to fill at the center of the main image but when I use the fillPatternOffsetX, it's shifting all the images to the right (The same login works fine with Rect and fillpatternImage):

![image](https://user-images.githubusercontent.com/1426399/114109770-ea0a4480-9910-11eb-82e4-d7d2e8a8a780.png)

Demo: 
- JS: https://codesandbox.io/s/interesting-bhabha-pnhxw?file=/index.html
- ReactJS: https://codesandbox.io/s/black-darkness-vjmfk?file=/src/index.js

**Comment by lavrton** [comment]
The looks like a bug. As a workaround, you can try to use several shapes or several `Konva.Image` instances.

**Comment by lavrton** [comment]
Look like it is fixed with the next konva version.

Wait for `v8` release and try it. Please reopen if the issue will be still there.
