### ISSUE TITLE
how to change transformer position manually  ?

### ISSUE THREAD

**Issue by Albert-cord** [konvajs/konva#1098]
Hi, I'm try to make a feature, refer to align and adsorpt shape, but when I try to operate transformer component, a absolutePosition API cannot work.

how to change transformer position manually ?  
you can look a demo: [https://codesandbox.io/s/boring-jennings-y9h92?file=/index.html](url)

**Comment by lavrton** [comment]
You can't change the position of a transformer. And you should not. `Transformer` just adapts to the positions of shapes. So just changes the positions of attached shapes.
