### ISSUE TITLE
Multiline emoji line wrap is not correct 

### ISSUE THREAD

**Issue by SergeyMell** [konvajs/konva#1099]
It seems that Konva has issues with multiline emoji rendering in different browsers
1. On Chrome it breaks the emoji in the middle so it becomes two unreadable symbols
![chrome](https://user-images.githubusercontent.com/12133261/115526614-e378b700-a298-11eb-86c3-056e353e644f.gif)

2. On Safari it doesn't add line break unless emoji has some preceding symbol
![safari](https://user-images.githubusercontent.com/12133261/115526601-dfe53000-a298-11eb-9230-1ba561b8dd47.gif)

You can easily reproduce it from this example
https://jsbin.com/zuvivivuhe/edit?html,js,output

Or even in the sandbox https://konvajs.org/docs/sandbox/Editable_Text.html if you insert some long line of emojis

Looking forward to getting some solution

**Comment by denis-mnml** [comment]
I have the same problem. `line.slice(0, mid + 1)` doesn't work well with emoji

**Comment by lavrton** [comment]
It should be fixed in the last version.
