### ISSUE TITLE
add a new event "swipe"

### ISSUE THREAD

**Issue by berryliu** [konvajs/konva#11]
can you add a new event of "swipe"? It's convenient for mobile development.

**Comment by lavrton** [comment]
I have an successful experiment with integration KineticJS and HammerJS v1 (gesture events). 
https://github.com/lavrton/KineticJS-HammerJS-test

So you are able to listen all possible events that HammerJS supports.
Swipe example: http://jsfiddle.net/lavrton/qQeH6/

I am still thinking about better integration.

**Comment by Jberryliu** [comment]
ok, thanks.

**Comment by EugeneSqr** [comment]
Looks like the example with swipe does not work in IE 11. Swipe handler isn't getting called.

**Comment by lavrton** [comment]
Just made an experimental support there: https://konvajs.org/docs/sandbox/Gestures.html
