### ISSUE TITLE
Handling stage dragBoundFunc on scaling

### ISSUE THREAD

**Issue by roshansachan** [konvajs/konva#1104]
I have used dragBoundFunc to limit a user from dragging the stage out of view. It works fine in the default state. But when I scale the stage, the bounding doesn't work for the top and left side of the stage.

        dragBoundFunc={(pos) => {
                  let newY = pos.y;
                  let newX = pos.x;
                  //limit at 10px, when user tries to move the stage out of view
                  if (pos.y > stageResolution.height - 10) {
                    newY = stageResolution.height - 10;
                  }
                  
                  //This doesn't work on scaling. This is the rule for top boundary
                  if (pos.y < -(stageResolution.height - 10)) {
                    newY = -(stageResolution.height - 10);
                  }
                  
                  if (pos.x > stageResolution.width - 10) {
                    newX = stageResolution.width - 10;
                  }
                  
                  //This doesn't work on scaling. This is the rule for left boundry.
                  if (pos.x < -(stageResolution.width - 10)) {
                    newX = -(stageResolution.width - 10);
                  }
                  return {
                    x: newX,
                    y: newY
                  };
          }}
          
Here is a video,

https://user-images.githubusercontent.com/4952904/115464869-59eec800-a24b-11eb-9547-b2b7986ee3b1.mov

[Here is the working example. ](https://codesandbox.io/s/react-konva-basic-demo-forked-zjp5z?file=/index.js:33691-34468)

I tried multiplying the stage width and height with stage stageScale.x and stage stageScale.y respectively but even that didn't 
work.
```
if(pos.y < -(stageResolution.height*stageScale.y -10) ){
    newY = -(stageResolution.height*stageScale.y -10)
}
```

**Comment by lavrton** [comment]
I am closing the issue, because it is a question. There is some better calculations are required on your side.
