### ISSUE TITLE
RFC: canvaskit-wasm rendering backend support. 

### ISSUE THREAD

**Issue by StringKe** [konvajs/konva#1108]
Is it possible to support https://www.npmjs.com/package/canvaskit-wasm to render content, so that the effect of support in nodejs will be very good. At the same time canvaskit-wasm is a package of skia, and skia can support svg output

**Comment by lavrton** [comment]
Konva already can work in NodeJS environment  thanks to https://github.com/Automattic/node-canvas.
You can try to backend it with `canvaskit-wasm` if you want. For reference sii https://github.com/konvajs/konva/blob/38eb854453c8c00215dd3cabe6e1a5c509fa59b9/konva-node/index.js
