### ISSUE TITLE
I can not get child nodes' properties when i drag or zoom or rotate a group.

### ISSUE THREAD

**Issue by mashroom33** [konvajs/konva#1110]
For example, i create two groups, A and B, and then i do: B.add(A).  Then i create a transformer C, do:C.node([A]).  When i drag or zoom or rotate, i find B's properties not change, but it visually moved. And when i do:C.node([A,B]), B will move very strange because as A's child node, B's properties are relative.
So how can i get child nodes' properties when i drag or zoom or rotate a group? I ask this question because when drag or zoom, i can figure it out. However, when rotate, it will be very difficult to calculate.

**Comment by lavrton** [comment]
> B.add(A). Then i create a transformer C, do:C.node([A]). When i drag or zoom or rotate, i find B's properties not change

It is expected. Because the transformer is attached to group A. So it is changing properties of A.

> `C.node([A,B])`

Don't do that. It confuses all the calculations. If you add several nodes into Transformer, they should not be in parent/child relationships.


> So how can i get child nodes' properties when i drag or zoom or rotate a group? I ask this question because when drag or zoom, i can figure it out. However, when rotate, it will be very difficult to calculate.

I am not sure what properties you are looking for here. Please make a small demo of your issue.

**Comment by lavrton** [comment]
> But now B is in group A, when i move or zoom or rotate A, B visually move

In konva coordinates are relative. So group `A` is moving INSIDE group B. Group B is static. Visually you see changes of group A. Group B may also have other groups/shapes that are staying or moving into a different position.
