### ISSUE TITLE
Feature request, add a way to output to Lottie files

### ISSUE THREAD

**Issue by smaznet** [konvajs/konva#1117]
Lottie is very awesome project for animation files
https://lottiefiles.com/

that would be nice to add a feature to output to Lottie

**Comment by lavrton** [comment]
Closing the issue because it is out of Konva scope.

**Comment by hashinclude72** [comment]
Hi any workaround for this?

**Comment by alexrada** [comment]
indeed, lottie seems strong enough to be considered.
