### ISSUE TITLE
Make TypeScript definitions stricter

### ISSUE THREAD

**Issue by CreativeTechGuy** [konvajs/konva#1118]
I see room for the TypeScript definitions to be improved to provide better type safety, compile time errors, and auto completion. One such example would be TagConfig's [pointerDirection](https://github.com/konvajs/konva/blob/b6e8afec6e590001fed57ff9c6a249f2fa83d06a/src/shapes/Label.ts#L179) which is typed as a string but should probably be restricted to just the few strings which are relevant `"up" | "down" | "right" | "left"`. Or another area for improvement would be the [cornerRadius](https://github.com/konvajs/konva/blob/b6e8afec6e590001fed57ff9c6a249f2fa83d06a/src/shapes/Label.ts#L182) for the same element. Instead of any number or array of numbers, there's really only 5 discrete options. Either a number, or an array with 1, 2, 3, or 4 numbers.

This will definitely require a major version bump as it'll likely cause issues with the stricter types. But most of the issues that this update will identify are likely legitimate issues which should be spotted at compile time.

I see that recently you are actually loosening the TypeScript rules which makes me concerned. I'm happy to go through this library and bring it back to a strict usage of TypeScript if this is something you are on board with. Also would probably be a good idea to add ESLint to ensure that we are as strict as possible.

**Comment by lavrton** [comment]
> I see room for the TypeScript definitions to be improved to provide better type safety, compile time errors, and auto completion

YES! YES! YES! AND YES!

Konva was not using strict rules for TS. But that is my goal! It is very time-consuming, so I am doing it super slowly.
I will be very happy to have any help there.
If you can, try to enable any strict rules in tsconfig and fix the errors.

**Comment by CreativeTechGuy** [comment]
Oh that's great to hear! I know a lot of people are very opposed to TypeScript or anything that removes the "freedom" of JavaScript so it's great to know you are on board.

Honestly one of the things I'm the most passionate about is developer experience and tooling so setting up TypeScript/ESLint/etc and refactoring to make it as precise as possible is definitely something I want to do.

What approach would you like me to take in the migration? I definitely don't want to try to rewrite the entire library in one PR. Should we create a `next` branch of some sort to put all of this incremental work and then release it as a new major version when it's all done? Not sure if you have a plan for a v9 yet or if there's a timeline there.

Let me know how you'd like me to go about this and I'll get started!

**Comment by CreativeTechGuy** [comment]
Also, it looks like the types in the other framework wrappers for Konva are depending on the core library's types. But maybe there'll need to be some updates to those also as a result. Probably not though as they seem like thin wrappers. Definitely those packages will need a version bump when this is done.

**Comment by lavrton** [comment]
I don't think we will need major releases for most of TS changes. I know some of them may be "breaking", but it is not a huge deal, because it is "type breaking" and should be fixed very easily. Of course, we should not change any js API or behavior on this road.

I see it as:
1. Turn on any strict rule in `tsconfig`. Probably `noImplicitAny` is the most important one and the simplest one to start with.
2. Fix as many errors as possible
3. If there are still too many errors, turn the rule off (so out TS tests are still working) and make a pull request.
4. Repeat.

If a Pull Request is not too large, it will be simpler to review it.

**Comment by CreativeTechGuy** [comment]
Got it. I definitely don't mind doing large passes like that as long as you are okay with reviewing changes across tons of files. I'll do that!

Are you on-board with ESLint also? I find it easier to write good TypeScript when you have ESLint yelling at you for the use of `any`, implicit type coercions, etc.

How do these phases sound:

1. Add ESLint configuration and agree on the rules. At this point it won't yet be enforced in the build process so this will just be adding the dependencies and configs.
2. Turn on strict in tsconfig and fix any errors as a result. Using ESLint warnings as a guide, but still not enforced.
3. Add ESLint validation to the build process and fix any of the warnings/errors as a result. These would just be the things that aren't already covered by the tsconfig strict mode.

**Comment by CreativeTechGuy** [comment]
For now I'm just going to address the shape interfaces that will most likely have an impact on a user. Let me know if I missed anything or if I misunderstood the docs! :)

**Comment by lavrton** [comment]
> Are you on-board with ESLint also?

Not on this step. Probably MUCH later. For now ts errors is enough work. But you can use eslint locally, if it helps you.

**Comment by lavrton** [comment]
Closing the issue. I hope to do some work for strict typescript. I am happy to apply any related Pull Requests.
