### ISSUE TITLE
`fillPatternOffset` update not working

### ISSUE THREAD

**Issue by y4nnick** [konvajs/konva#1120]
Hi, thanks for the great lib.
I wanna build a magnification tool, where the user can zoom in an image by showing a separate circle with a scaled up version of the current mouse pointer.

I am using angular.

I am creating the circle with: 
```javascript
 this.stage = new Konva.Stage({
      container: 'image-zoom-container',
      width: this.stageSize,
      height: this.stageSize,
    })

this.layer = new Konva.Layer()
this.stage.add(this.layer)

const imageObj = new Image()
imageObj.src = this.image

imageObj.onload = () => {

      this.imageCircle = new Konva.Circle({
        x: this.stageSize / 2,
        y: this.stageSize / 2,
        fillPatternImage: imageObj,
        fillPatternScaleX: this.zoomFactor,
        fillPatternScaleY: this.zoomFactor,
        radius: this.stageSize/2,
      })

      this.layer.add(this.imageCircle)
}
```

Now once the user moves the cursor over the image the following function gets called:
```javascript
 public onDragMove({position}: { position: { x: number, y: number }) {
    // NOT WORKING
    this.imageCircle.fillPatternOffsetY(100);

   // WORKING
  this.imageCircle.fillPatternScaleX(10)
  }
```

The setting of the `fillPatternOffset` does not work here.
However the setting of `fillPatternScaleX` does work (i added this as a test).

Sadly i could not reproduce this behaviour where fillPatternOffset does not work
Here is my test where it works. but i suppose i am doing something different there: https://stackblitz.com/edit/js-dvz5l8

Do u have any plan why this is happening on my local setup with angular and konva v8.0.2?

--------------------
Adding redraws with the following code also does not work
```
    this.layer.draw()
    this.imageCircle.draw()
    this.stage.draw()
```

**Comment by lavrton** [comment]
So the demo works correctly, right? But in your app it doesn't work?

**Comment by y4nnick** [comment]
Yes, exactly.
I am now using an actual `Konva.Image` where it works but i can't do an animation i wanted to do (showing and hidding the maginification tool by changing the radius from a `Konva.Cirlce` from 0 to X).

Since i can't reproduce the issue on stackblitz i suppose we can close this issue.

**Comment by lavrton** [comment]
Ok. When you find a way to reproduce it, just reopen the issue, please.
