### ISSUE TITLE
bug in build process

### ISSUE THREAD

**Issue by flarsi** [konvajs/konva#1121]
file://node_modules/konva/lib/index-node.js line:2
Change from
import * as Canvas from 'canvas';
to
import * as Canvas from './Canvas.js';
becouse fuse box cant understend this import

**Comment by lavrton** [comment]
Can you make a small repo demo with that bundler?

It should be `import * as Canvas from 'canvas';` because it is import from `node_modules`, not local file. It should import it ONLY if you call code from NodeJS env.

**Comment by maloguertin** [comment]
I can confirm the issue, when I run my test I use node as my target and since 8.0.0 I have to transform Konva with babel-jest but it breaks on that line.

**Comment by lavrton** [comment]
If code works from NodeJS you need to install `canvas` package.
I still need a demo repo.

**Comment by starsolaris** [comment]
> If code works from NodeJS you need to install `canvas` package.
I have this error in electron application, in the renderer process. (window.canvas is existed and should not be imported).

**Comment by maloguertin** [comment]
> If code works from NodeJS you need to install `canvas` package.
> I still need a demo repo.

My code including Konva is targeted for browsers but with jest and babel you have to set the target as node which is what caused this issue. 

Installing canvas ended up doing the trick, maybe you could add a small line about test env in the NodeJS section! 

Anyways thanks for the solution!

**Comment by lavrton** [comment]
As far as I know, jest is running its tests from NodeJS env. So extra package is required.

**Comment by maloguertin** [comment]
> As far as I know, jest is running its tests from NodeJS env. So extra package is required.

yeah I'm not exactly sure why I was fine without that before version 8.0.0
