### ISSUE TITLE
Rescale/Resize scale while zooming?

### ISSUE THREAD

**Issue by RickvanB** [konvajs/konva#1123]
Hi,

Over the past few weeks I have been developing an annotation tool. At the moment there is a stage with an image on it, in the first layer. The annotations are placed in the next layer. I am very happy with the zoom option, but I have one more question. Is it possible to resize/rescale the stage based on the zoom position? See for example Photoshop, the plane then becomes larger when you start zooming. At this point with elongated images, when you zoom in, the part you're annotating doesn't get wider. Is that possible in Konva?

Thanks in advance!

**Comment by lavrton** [comment]
Can you provide a visual example?

Konva just drawing what you are asking. If you don't need to change sizes of annotations, then you can:
1. Change sizes of annotations in reverse of stage scale
2. Or apply scale just on image (not whole stage) and reposition annotations into correct places.
