### ISSUE TITLE
Fill pattern image processing works differently in version 7.2.5 and version 8.02. 

### ISSUE THREAD

**Issue by smhcpk** [konvajs/konva#1124]
konva@7.2.5  =>  https://stackblitz.com/edit/konva-pattern-725 
konva@8.0.2  =>  https://stackblitz.com/edit/konva-pattern-802

***** When moving the pattern position by dragging the mouse, it is not applied in version 8.0.2.

**Comment by lavrton** [comment]
Fixed with `konva@8.0.4`. Thanks for the report.
