### ISSUE TITLE
What should transformsEnabled('position') do?

### ISSUE THREAD

**Issue by AlbertBrand** [konvajs/konva#1125]
Here is the fiddle:
https://jsfiddle.net/52zk0qsp/5/

What I would expect (the docs are not that clear) after calling `transformsEnabled('position')` is that the rect does not get any scale transform from the layer. But it seems it does..

**Comment by lavrton** [comment]
It affects only attributes of a node itself.

```js
const rect = new Konva.Rect({
   width: 100, height: 100,
   scaleX: 0.5, // will be ignored because of transformsEnabled
   fill: 'black',
   transformsEnabled: 'position'
});
```

It is used mostly as performance tip. But it doesn't give much boost and I have plans to remove `transformsEnabled`.

**Comment by AlbertBrand** [comment]
Thanks for the clear explanation!
