### ISSUE TITLE
Import konva in NodeJS crashes due to ESM format

### ISSUE THREAD

**Issue by flaviendelangle** [konvajs/konva#1126]
Hi,

I'm trying to import one of our libraries that uses Konva inside a NodeJS environment to import other elements of my library (and later on to use Konva with `node-canvas` which worked almost perfectly on the last version on Konva)

But with Konva 8, your package is only exported in ESM format, causing 

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/flavien/Git/habx/service-render-housing-2d/node_modules/konva/lib/index-node.js
require() of ES modules is not supported.
```

We tried to migrate our application to ESM modules but a lot of dependencies still export CJS only and after hours spent on trying I'm not sure it is the right solution.

Do you have a working example of Konva usage in a codebase both compatible with the browser and with NodeJS ?

In the documentation, the NodeJS installation only tell to install both `konva` et `canvas`
https://konvajs.org/api/#toc8__anchor
Does it mean that not being compatible with NodeJS applications with CommonJS imports` is intended ?

**Comment by lavrton** [comment]
I don't have plans to add CommonJS modules back. If you still need them, use `konva@7` and `konva-node` packages.

> Does it mean that not being compatible with NodeJS applications with CommonJS imports` is intended ?

Yes. You have to migrate your code to ESM. Depending on your app, it may be not very hard task, because ESM can import CommonJS modules. It makes migration simpler.

**Comment by flaviendelangle** [comment]
I did rollback to `konva@7` yesterday, which solves the issue for now

Migrating to ESM does not seem to be that simple unfortunately. It is totally doable of course but would require a lot of time.

**Comment by dariomac** [comment]
Hi! I found the same issue as @flaviendelangle. My typescript backend uses Konva 7 but after bumping to v8, the same happened to me. 

Anton's solution of keep in v7 is not a real solution, because we will lose all the new stuff, but I've tried to migrate my code to ESM, use the `--experimental-specifier-resolution=node`, dynamic load the Konva module, and all of those attempts break other unrelated parts or cause troubles with the rest of the project. This is a big backend so the migration (if can be done) would be costly.

**Comment by lavrton** [comment]
I just released `konva@8.2.0` that has CommonJS modules. Please try to use it https://github.com/konvajs/konva#commonjs-modules

Let me know if it doesn't work.

**Comment by tbo47** [comment]
I had an issue with konva not being esm in my angular project. So I decided to create `konva-es` to fix it.
https://github.com/tbo47/konva-es?tab=readme-ov-file
Maybe it helps

**Comment by ptc-jhirzel** [comment]
In a Lit project we encountered the same issue  as @tbo47 (thanks for sharing your project). Not sure if it's a great idea but maybe the distribution artifacts could provide both, a ES6 and CommonJS compilation?

**Comment by lavrton** [comment]
BTW, konva version 8 has both ES and commonjs compilation. You can try it.

I dropped ES version because there were too many issues.
I am hoping sooner a later, JS ecosystem will finally heal to have ES-only version.
