### ISSUE TITLE
Property 'autoDrawEnabled' does not exist on type 'typeof Konva'

### ISSUE THREAD

**Issue by JasonPierce** [konvajs/konva#1128]
Thank you for creating such an amazing library!

I've been using your library in an Angular 11 project for some time. I recently upgraded to Konva v8.0.4 from v7.x, and noted the new "automatic redraw" feature you added in v8.0.0, with the ability to disable this by setting `Konva.autoDrawEnabled = false`. Unfortunately TypeScript doesn't believe this new setting exits and throws error _"Property 'autoDrawEnabled' does not exist on type 'typeof Konva'"_ in the editor and compiler.

I've reproduced the error here: https://stackblitz.com/edit/angular-ivy-ed2yrp?file=src/app/app.component.ts. You'll note in the demo that the `Konva.pixelRatio` option can be set, but not the `Konva.autoDrawEnabled` option (line 15). 

Is there another way to set the `Konva.autoDrawEnabled` option in TypeScript apps or is this a bug?

**Comment by lavrton** [comment]
I will publish the release later. You can ignore this error for now, or just do `(Konva as any).autoDrawEnabled = false`.

Why do you need to disable it?

**Comment by JasonPierce** [comment]
Thanks for the expedient reply/fix @lavrton! 

Prior to the introduction of automatic redraw that you added in v8.0.0, I was manually redrawing via calls to `layer.draw()` after performing multiple layer updates (e.g., draw a bunch of rectangles, then draw a circle on top of a rectangle). I wanted to disable the automatic redraw to test it's performance -- to make sure automatic redraw is not slower in these use cases
