### ISSUE TITLE
Add a class name to the canvas created by Konva

### ISSUE THREAD

**Issue by rowild** [konvajs/konva#1129]
I learned about the Konva project through peaks.js, an audio annotation library. Peaks.js uses Konva to overlay several canvas elements that each show different this, one the waveform, another one the timeline, a third one the playhead etc.

This is awesome and works very well. However, I miss the possibility of simple css interactions with these canvases, like hiding a particular layer or changing its opacity (as a whole). 

So i wonder if there is any chance to convince the creators of Konva to add the possibility of adding a class name ir a unique id to the created canvas?

I checked the `Canvas` class. There, in `function Canvas(config)`, I added 
`this._canvas.className += 'my-custom-class';`
which works fine. 

However, I did not yet check where the config is coming from (new to Konva). Anyway, it seems to be of not too much effort if I am not totally mistaken. 

Would love to read you feedback!

**Comment by lavrton** [comment]
Usually I don't recommend to change styles of canvas element. It may lead to unexpected behavior on export (as styles are not exported). 


If you are sure what you are doing, using the last `konva@8` you can access native canvas element and change it styles or class as you want it.

```js
const canvas = layer.getNativeCanvasElement();
canvas.classList.add('my-custom-class');
```

**Comment by rowild** [comment]
@lavrton Thank you! (It's for a simple show/hide scenario, no other styling involved.)

**Comment by lavrton** [comment]
For simple hide/show you can use just
```js
layer.visible(false);
// or
layer.hide();
layer.show();
```

**Comment by rowild** [comment]
That's good to know!

(However, Peaks does not expose an API, where I can address a specific layer. They overlay 5 canvases, one for a waveform, one for a playhead, one for a timeline, another one for markers, and the 5th one for segments. In the DOM, none is described in any particular way, and the responsible JS that handles all that, is hidden away. So I simply don't know how to address the proper canvas, except maybe by children[0], children[1]... don't know, if the order is always consistent, though...)
