### ISSUE TITLE
`fillPatternImage` won't auto refresh in React?

### ISSUE THREAD

**Issue by Jayatubi** [konvajs/konva#1130]
I was going to add a image as the `fillPatternImage` to a `Rect` node such as:
```typescript
render() {
    const image = new Image();
    image.src = 'foo.png';
    return (
        <Konva.Rect
                    fillPatternImage={image}
                    fillPatternX=...
                    fillPatternY=...
                    width=...
                    height=...
                />);
}
```

However, I would only get a blank background if I refresh this page. After a few investigation I found that was caused by the `image was not ready`.

For now I have to change this code into such form:
```typescript
// I've to add an `image` into the state
state = {
    image : new Image() 
}

componentDidMount() {
    // This must be a different instance from the above one to make `setState` work
    const image = new Image();
    image.src = 'foo.png';
    // This is the key
    image.onload = () => {
        this.setState({image : image})
    }
}

render() {
    return (
        <Konva.Rect
                    fillPatternImage={this.stage.image}
                    fillPatternX=...
                    fillPatternY=...
                    width=...
                    height=...
                />);
}
```

Basically it works but it looks like to much code here. I want simply such routines since I would have much more nodes with images. Could the `fillPatternImage` be auto refreshed?

**Comment by lavrton** [comment]
Sorry, I don't understand your question. What do you mean by "auto refreshed"? You can use `use-image` hook to simplify code a lot: https://github.com/konvajs/use-image

**Comment by Jayatubi** [comment]
> Sorry, I don't understand your question. What do you mean by "auto refreshed"? You can use `use-image` hook to simplify code a lot: https://github.com/konvajs/use-image

Thanks for reply. The `use-image` did just what I want although I need to change the class components into function components to use the React Hooks.
