### ISSUE TITLE
mouseover Event is unpredictable on Brave browser

### ISSUE THREAD

**Issue by RobinPH** [konvajs/konva#1132]
Each page load produces different results on whether the shape will properly handle mouseover or not.

https://konva-test-mouseover.netlify.app/

I have tested it and it worked fine on Chrome, Firefox, and Edge.
However it is unpredictable on Brave. _Version 1.25.72 Chromium: 91.0.4472.101 (Official Build) (64-bit)_

**Comment by friksa** [comment]
did you try layer.batchDraw(); after the color change?

**Comment by RobinPH** [comment]
> did you try layer.batchDraw(); after the color change?

I just added **layer.batchDraw()** on the link above. But the issue is still there.

**Comment by friksa** [comment]
You should use "mouseenter" vs "mousemove" for performance reasons.  Can you can make it so the source code is editable to try different things?

**Comment by RobinPH** [comment]
Here: https://jsbin.com/moxuvix/edit?html,js,output

**Comment by friksa** [comment]
Thanks!  Not sure why it is not working... Even if you use a single rectangle and simply do a console.out, it does not consistently work in Brave, but it works everywhere else for me.

Maybe a Brave bug?

**Comment by RobinPH** [comment]
It worked fine up until Brave 1.22.29. However it stopped working in Brave 1.22.30

**Comment by lavrton** [comment]
Brave browser is doing extreme things for privacy reasons. One of them is breaking `getImageData()` function. I guess some trackers are using it for fingerprinting.

But Konva is using `getImageData()` for hit detection (for all events). The demo will work just fine when you disable "Brave Shields".

I don't think I want to do anything here from the Konva side. The Brave browser is breaking a very common function.

If you REALLY need to support brave browser, you can monkey-patch `layer.getIntersection()` function to calculate shape under pointer with math calculations and `node.getClientRect()` function.

**Comment by juansalvatore** [comment]
@lavrton I'd suggest adding something like this:
```js
function isCanvasGetImageDataSupported() {
    const canvas = document.createElement('canvas');
    canvas.width = canvas.height = 1;
    const context = canvas.getContext('2d');
    if (!context) {
        return false;
    }
    const imageData = context.getImageData(0, 0, 1, 1);
    return imageData && imageData.width === canvas.width;
}
```
reference: https://github.com/mapbox/mapbox-gl-supported/pull/28/files
Not sure where this logic could be added, but I think maybe doing this to at least not have logic not working silently. 
But otherwise I agree that it's a Brave issue :/

**Comment by Omiod** [comment]
The isCanvasGetImageDataSupported() function returns true on Brave ...

**Comment by pjbakker** [comment]
> @lavrton I'd suggest adding something like this:
> 
> ```js
> function isCanvasGetImageDataSupported() {
>     const canvas = document.createElement('canvas');
>     canvas.width = canvas.height = 1;
>     const context = canvas.getContext('2d');
>     if (!context) {
>         return false;
>     }
>     const imageData = context.getImageData(0, 0, 1, 1);
>     return imageData && imageData.width === canvas.width;
> }
> ```
> 
> reference: https://github.com/mapbox/mapbox-gl-supported/pull/28/files Not sure where this logic could be added, but I think maybe doing this to at least not have logic not working silently. But otherwise I agree that it's a Brave issue :/

This is not enough to detect the event handling changes that Brave starts, so not a good enough solution.

**Comment by edmundmunday** [comment]
@lavrton - Brave implemented some functionality ~12 months ago to make it relatively easy to detect that a site is running in the Brave browser (https://jsbin.com/sexawix/edit?html,js,console).

Would you be open to some kind of automatic check being added to Konva that just displays a warning in the console to users running Brave? If you can point me to an example of something similar in the library today, I'd be open to creating a PR.

I spent ~2 hrs trying to debug this behaviour this morning **cries**

**Comment by lavrton** [comment]
I am open to some automatic check. But it shouldn't be brave check. Instead, we should do "working feature check". We need to draw into external canvas and try to get color of pixel. It should match the color that we trying to draw.

**Comment by jez9999** [comment]
So, I just spent 2 days figuring out that this was a Brave issue.  Gah.  Yes, I think a warning in console should be added upon createLayer or something to warn about this behaviour and its likely culprit (canvas poisoning browsers like Brave, with their default behaviour).

**Comment by lavrton** [comment]
It will be nice if you can make a pull request for that.

**Comment by wiverson** [comment]
Hmm. Why not allocate a 2d array with 3/4 vector data (or just store ref ids there) to the object instead? Then look at that data structure instead of relying on a canvas color array?
