### ISSUE TITLE
Getting SVG data

### ISSUE THREAD

**Issue by PikabobAlex** [konvajs/konva#1134]
Hi, in your documentation you did cover a example of making a text path, but you didn't state that how users can get the path data from. I know I can get the data from SVG in notepad++ or using CODE but it's not really user friendly? What if I want to get the SVG data from the shapes we created in Konva?

**Comment by lavrton** [comment]
Can you give me more information about your use case? I don't understand what you want.

**Comment by PikabobAlex** [comment]
Sorry I didn't explain clearly just then, how to convert shape that I created in Konva like Rect, Circle etc to a path data for TextPath to follow along?

**Comment by lavrton** [comment]
Well, it is up to you. You need to understand the meaning of path data and how to generate it. As soon as you understand it, you can easily generate `data` for any shape.

**Comment by Modi34** [comment]
> Sorry I didn't explain clearly just then, how to convert shape that I created in Konva like Rect, Circle etc to a path data for TextPath to follow along?

Not sure if this will help you. I needed svg / pdf / png export for logo generating service on node.js + konva
Was able to solve it by simply specifying type for node canvas
```javascript
const Konva = require('konva-node');
var canvas = require('canvas');
let fs = require('fs')

let types = ['pdf', 'svg', 'png']
function newExport(json){
  let {width, height} = json.attrs;
  let background = json.children[0].children[0];
  let logo = json.children[1]
  let watermark = json.children[2].children[0];
  logo.children.unshift(background)
  logo.children.push(watermark)
  for(let type of types){
    let canvases = []
    Konva.Util.createCanvasElement = () => {
      const node = new canvas.Canvas(width, height, type);
      node.style = {};
      canvases.push(node)
      return node;
    };

    const stage = new Konva.Stage({width, height})

    stage.add(Konva.Node.create(logo, 'container'))
    let layer = canvases.pop();
    layer = canvases.pop()
    fs.writeFile('out.'+type, layer.toBuffer(), r=>{})
  }
}
newExport(json)
```

feels a bit weird to override Konva.Util.createCanvasElement like this but it works :P

you could also try
* https://github.com/gliffy/canvas2svg - this was my plan b in case canvas failed
* https://github.com/Iwasawafag/node-potrace - this is the last resort solution

not sure how to do this in browser though... 
hope this helps someone - lost some time on this.. 
ps.. also was sad that did't chose fabricjs for this task. Had to write editor that comes out of the box in fabrikjs (called textBox) http://fabricjs.com/subclassing-tutorial  
Learned a lot and had a lot of fun with it but still not cool..

**Comment by PikabobAlex** [comment]
> > Sorry I didn't explain clearly just then, how to convert shape that I created in Konva like Rect, Circle etc to a path data for TextPath to follow along?
> 
> Not sure if this will help you. I needed svg / pdf / png export for logo generating service on node.js + konva
> Was able to solve it by simply specifying type for node canvas
> 
> ```js
> const Konva = require('konva-node');
> const canvas = require('canvas');
> const fs = require('fs')
> 
> let types = ['pdf', 'svg', 'png']
> function newExport(json){
>   let {width, height} = json.attrs;
>   let background = json.children[0].children[0];
>   let logo = json.children[1]
>   let watermark = json.children[2].children[0];
>   logo.children.unshift(background)
>   logo.children.push(watermark)
>   for(let type of types){
>     let canvases = []
>     Konva.Util.createCanvasElement = () => {
>       const node = new canvas.Canvas(width, height, type);
>       node.style = {};
>       canvases.push(node)
>       return node;
>     };
> 
>     const stage = new Konva.Stage({width, height})
> 
>     stage.add(Konva.Node.create(logo, 'container'))
>     let layer = canvases.pop();
>     layer = canvases.pop()
>     fs.writeFile('out.'+type, layer.toBuffer(), r=>{})
>   }
> }
> newExport(json)
> ```
> 
> feels a bit weird to override Konva.Util.createCanvasElement like this but it works :P
> 
> you could also try
> 
> * https://github.com/gliffy/canvas2svg - this was my plan b in case canvas failed
> * https://github.com/Iwasawafag/node-potrace - this is the last resort solution
> 
> not sure how to do this in browser though...
> hope this helps someone - lost some time on this..
> ps.. also I was a bit sad that did't chose fabricjs over konva for this task. Had to write text editor that comes out of the box in fabrikjs (called textBox) http://fabricjs.com/subclassing-tutorial
> Learned a lot and had a lot of fun with it but still not cool..

Thanks mate! I should close the issue, because the initiate idea was using a text path on a circle path, and now luckily the idea was scraped and using a normal text instead. But thanks man, I will give it a try too in case of future use.
