### ISSUE TITLE
keep the position and rotation of the shape in the group, it will offset and randrom happen not visible?

### ISSUE THREAD

**Issue by codcer** [konvajs/konva#1136]
online demo:
https://codesandbox.io/s/zen-colden-6y5n2?file=/src/index.js

How can I get it?

**Comment by lavrton** [comment]
Why do you need a group at all? Konva support resizing several shapes at the same time.

You are mixing `react-konva` and `konva` API. I don't recommend that. If you create nodes with `react-konva`, like `<Rect />`, you probably should not use Konva API like `new Konva.Group()` and use `react-konva` too `<Group />` (you will need to compose your app differently in that case).

**Comment by codcer** [comment]
Thanks, i try write it. 
https://codesandbox.io/s/zen-colden-6y5n2?file=/src/index.js
