### ISSUE TITLE
Applying canvas context to shape or layer

### ISSUE THREAD

**Issue by friedrichkeydel** [konvajs/konva#1137]
Hey there,

is there any possibility to apply a canvas context, e.g. from a canvas inside DOM, directly to a Layer or Shape without rasterizing it to JPEG or PNG?
I'm using an external canvas library to draw a canvas which I then would like to process using Konva. I wan't to be able to resize the image afterwards without having pixelized image data.

**Comment by lavrton** [comment]
Why do you need it? If you have a canvas element, you can just use it for `Konva.Image`.

**Comment by friedrichkeydel** [comment]
Ah, thanks for that info - so how would I do that? Is it as simple as passing the canvas-DOM-Node into the image Parameter of a Konva Image?

**Comment by lavrton** [comment]
Yes.

```js
const image = new Konva.Image({
  image: canvasElement // or context.canvas, if you have access to context
});
```

**Comment by friedrichkeydel** [comment]
That worked, but it does not make a difference to the image output. It seems like the canvas still gets rasterized, so if I try to export the image using a higher pixelRatio, it's still blurry!

`toDataURL({
    pixelRatio: 5.0,
    mimeType: 'image/png',
    quality: 1.0
})`

**Comment by lavrton** [comment]
Well, the canvas element is like a bitmap image. So it is **resterized**. Exporting with higher pixelRatio will not magically increase quality of the canvas data.

You need to find your own way how to increase quality of that canvas drawing. Probably by making bigger canvas.
