### ISSUE TITLE
Feature Request: Shadow Shrink/Grow capability

### ISSUE THREAD

**Issue by 92Eli** [konvajs/konva#1139]
I have a feature idea for objects that goes with the `shadowOffestX`, `shadowBlur`, and other shadow properties: `shadowGrow`.

shadowGrow would be like [CSS's shadow spread radius](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow), the fourth item of the `box-shadow` property.

This could be used to change the size of the shadow as larger or smaller (a negative value would yield an inner shadow).

**Comment by lavrton** [comment]
As far as I know, 2d canvas API doesn't support that. There are some hacks: https://stackoverflow.com/questions/60656468/is-there-something-of-canvas-shadow-properties-like-the-spread-property-of-css, but I don't think we can make a general sulution of all cases.
