### ISSUE TITLE
Konva Transformer lags with "shouldOverdrawWholeArea"

### ISSUE THREAD

**Issue by akkii922** [konvajs/konva#1141]
If i use a transformer with "shouldOverdrawWholeArea" option it lags when drag

here is the demo

https://codesandbox.io/s/react-konva-window-scale-test-forked-qh01h?file=/src/index.js

**Comment by VanquishedWombat** [comment]
Just for info https://codepen.io/JEE42/pen/oNWgdqq?editors=1010 is a demo in Vanilla JS (no react) illustrating that the issue is NOT present outside of react-konva.

**Comment by lavrton** [comment]
I see such behavior on vanilla version too, when I upgrade konva.
