### ISSUE TITLE
Transformer is appling on invisible elements

### ISSUE THREAD

**Issue by Artur93gev** [konvajs/konva#1142]
Hi, thanks for the great effort putten into this library.
I have noticed some strange behavior(maybe a bug). When I'm setting a node to be invisible, it's still possible to attach a transformer and have the transformer visible on the invisible node. Also, I have noticed the same behavior for the groups and transformer. The transformer always respects all children's geometry, no matter whether it is visible or not. 

Here is the repro link: https://codesandbox.io/s/ancient-microservice-yz4ny?file=/src/index.js:659-667

My actual wish is to add a transformer to a group and get it visually bounded only on the group's visible elements. Thanks

**Comment by lavrton** [comment]
Hello. I don't understand the issue on the demo. Can you please make a demo with a group?
