### ISSUE TITLE
Spiked lines after implementing free draw

### ISSUE THREAD

**Issue by Marchiuzzz** [konvajs/konva#1144]
First of all, wonderful project!

However, I'm having a bit of a problem with it. I have implemented a free drawing tool into my app following the official tutorial provided in the docs and noticed that if the movements of mouse are short-ranged, some lines begin spiking out. As you can see in this gif I made
![ezgif-6-291638f42280](https://user-images.githubusercontent.com/73941456/124299379-06abc680-db66-11eb-8cc4-4d7c78d49233.gif)

It doesn't seem like it's a big deal but in my application it is possible to draw on zoomed canvas and when it's zoomed this happens more often

https://codesandbox.io/s/github/konvajs/site/tree/master/react-demos/free-drawing?from-embed

**Comment by lavrton** [comment]
I don't think there is something we should do from Konva side. Too close points produce such result with 2d canvas. Or it is a tension algorithm. I think you should add your own smoothing. There are tons of ways to do that. For example: 

```js
    let lastPoint = {
      x: lastLine.points[lastLine.points.length - 2],
      y: lastLine.points[lastLine.points.length - 1]
    };
    if (dist(lastPoint, point) > 4) {
      lastLine.points = lastLine.points.concat([point.x, point.y]);
      // replace last
      lines.splice(lines.length - 1, 1, lastLine);
      setLines(lines.concat());
    }
```

https://codesandbox.io/s/distracted-hypatia-13080?file=/src/index.js

**Comment by Marchiuzzz** [comment]
Hands down, this project has the best support I have ever seen. Thank you very much Anton
