### ISSUE TITLE
Konva.Image.fillPatternScale is not functional in Konva Nodejs

### ISSUE THREAD

**Issue by wxfred** [konvajs/konva#1145]
konva version: 8.1.1
canvas version: 2.8.0

Change any of `fillPatternScale` `fillPatternScaleX` `fillPatternScaleY` will have the same result in Nodejs env. 
By the way, browser rendering is fine.

**Comment by lavrton** [comment]
Looks like `canvas` library is missing some function to make it work from Konva.

And I found this related Pull Request: https://github.com/Automattic/node-canvas/pull/1623. I guess it will work when they will have transform functions on patterns.

**Comment by lavrton** [comment]
Looks like it is merged. I hope it will work with the new `canvas` version.
