### ISSUE TITLE
how to move point in a rect with angle in dragboundfun fun ?

### ISSUE THREAD

**Issue by fuxiaowo** [konvajs/konva#1146]
![image](https://user-images.githubusercontent.com/57031922/125483568-0d436670-d88a-4ed8-bfc1-df4218a1ed07.png)

green arrow is rotated rect, how to drag red point move in green area

**Comment by lavrton** [comment]
If it is `Konva.Transformer` then `dragBoundFunc` will not work for it. You need to control resizing node attributes for that.
