### ISSUE TITLE
Brave browser mouse weird behavior 

### ISSUE THREAD

**Issue by jrj2211** [konvajs/konva#1149]
I'm currently trying to pick a 2D canvas library and so far I'm liking Konva the best. One thing I've noticed though is when looking at the examples I get weird mouse behavior when using Brave browser (built on chromium). 

I've been looking at the Seat Reservation example. I noticed that some dots when clicking on them toggle the wrong seat. Also clicking some "blue" seats don't do anything or show the "blocked" cursor and some work correctly. In chrome however the example works perfect.

**Brave Browser:** 
![UdL6dpCF9o](https://user-images.githubusercontent.com/6005836/126232514-2be45971-37ec-465c-913c-baac5b76eb82.gif)

**Chrome Browser:**
![4eIKrmY9v5](https://user-images.githubusercontent.com/6005836/126231625-eaa32440-870e-429e-a282-4e6c678e2e2a.gif)

I also noticed this on the Stars example on konvas homepage. In Chrome the example works fine but has issues in Brave. Only one of the scaling handles ever works.

**Brave Browser:** 
![VGPYoqoB4K](https://user-images.githubusercontent.com/6005836/126232012-cb94ff16-c997-4466-94bc-82011ffbaf62.gif)

**Chrome Browser:**
![DwHwE3yR9h](https://user-images.githubusercontent.com/6005836/126232008-9ce45111-4ff2-42bc-9948-8a80182beab3.gif)

I know its hard to support every browser and Brave does break a lot of sites, but that's only typically because of it blocking different origin requests. I feel like this library should just work on Brave considering its built on Chromium so I'm not sure what would cause the difference. Any idea on why this would be happening?

**Comment by lavrton** [comment]
I guess it is the same as https://github.com/konvajs/konva/issues/1132#issuecomment-867339732 and https://github.com/konvajs/konva/issues/1111#issuecomment-836746826
