### ISSUE TITLE
can set existing canvas to konva ? like threejs.

### ISSUE THREAD

**Issue by nxg916** [konvajs/konva#1150]
`<canvas type="webgl" id="webgl" style="width: 100%; height: 450px;"></canvas>`

```
uni.createSelectorQuery()
.select('#webgl')
.node()
.exec((res) => {
    const canvas = res[0].node
    const THREE = createScopedThreejs(canvas)

    //do something
})
```

that can be use in applets and other apps

**Comment by lavrton** [comment]
https://github.com/konvajs/konva/issues/1147#issuecomment-880404210
