### ISSUE TITLE
Mouse events not working properly on chromium v92

### ISSUE THREAD

**Issue by Tomburgs** [konvajs/konva#1151]
Currently some of the mouse events, such as drag & hover, are not working properly on Chromium 92.0.4515.107.
This was tested in both Brave & Google Chrome, latest confirmed working version was Chromium 91.0.4472.164.

This can be tested in many of the demos on Konva website itself, such as the following:
- [Canvas Designer](https://konvajs.org/docs/sandbox/Canvas_Editor.html)
- [Animals on the Beach Game](https://konvajs.org/docs/sandbox/Animals_on_the_Beach_Game.html)
- [Editable text](https://konvajs.org/docs/sandbox/Editable_Text.html) (Partly not working - can't resize or rotate)

**Comment by lavrton** [comment]
I don't see any issues with the last chrome `92.0.4515.107` on MacOS.

But Brave browser may have issues with its strict protection.

**Comment by Tomburgs** [comment]
You're right — apologies.

Seems like the person who was testing with Chrome likely had something else going on.
I Downloaded & tested with Google Chrome myself and it's completely fine.

Disabling Brave Shield also solves it in Brave.
It must be that the Shield isn't active on local, that's why I never noticed those issues before.
