### ISSUE TITLE
Unable to get identifier correctly with multitouch "touchend"

### ISSUE THREAD

**Issue by mbotsu** [konvajs/konva#1152]
Of the two-finger results, touchend only returns one identifier.

https://jsbin.com/covohihuga/1/edit?html,js,console,output

**Comment by lavrton** [comment]
Probably you want to use `changedTouches` instead of `touches`. As far as I know, if will not have that last touch inside `touches`. Because `touchend` is already happened, so there is no finger on the screen.

**Comment by mbotsu** [comment]
Thank you, it works as I expected.
