### ISSUE TITLE
Bug when processing shape events

### ISSUE THREAD

**Issue by citizen55** [konvajs/konva#1153]
Thank you for Konva

I need to select a Bézier curve to work with, but I found that by creating it with a Shape, I get strange behavior

here's an example https://codepen.io/citizen55/pen/OJmZRrL?editors=0110

hover the pointer over the lines
the first line works correctly, the others do not

**Comment by lavrton** [comment]
You need to call `ctx.beginPath();` in your scene function:

```js
const sceneFunc = (ctx, shape) => {
  let x0, y0, cpx, cpy, x1, y1;
  [[x0, y0], [cpx, cpy], [x1, y1]] = this.coords;
  ctx.beginPath();
  ctx.moveTo(x0, y0);
  ctx.quadraticCurveTo(cpx, cpy, x1, y1);
  ctx.fillStrokeShape(shape);
}
```
