### ISSUE TITLE
Probable Memory leak in 8.0.1+

### ISSUE THREAD

**Issue by AlexIII** [konvajs/konva#1154]
Starting around `8.0.1` and to the current version there's a memory leak that seems to be related to children not being properly destroyed (or at all). My current assumption is that `Group.destroyChildren()` is not working. The last version that does NOT have this problem (that I've tried) is `7.2.5`.
I'm sorry for the vague description, I've just found it in one of my projects and it will take some considerate time to isolate the minimal code that can reproduce the problem. But I can do it if the problem is not apparent on your side.

**Comment by lavrton** [comment]
I can't reproduce it. Check your own variables and leaks.
Please make a demo.

**Comment by AlexIII** [comment]
Here's my demo. The crucial part here is to upload an actual `Image`.
With `7.2.5` memory consumption stays roughly the same.

![k7 2 5](https://user-images.githubusercontent.com/10047074/128139299-790e1ce5-2558-4a44-84b9-a81ddeec5342.png)

With `8.1.1` memory consumption grows on every call `ktest.redraw()` without limit.

![k8 1 1](https://user-images.githubusercontent.com/10047074/128139311-5f5cb465-5c2a-41c4-9ad4-6f8b74a4f89b.png)


```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://unpkg.com/konva@8.1.1/konva.min.js"></script>
    <meta charset="utf-8" />
    <title>Konva Demo</title>
  </head>
  <body>
    <div id="container"></div>
    <script>

        class Ktest {
            constructor() {
                this.testLayer = new Konva.Group();
                this.image = (() => {
                    const img = new Image();
                    img.onerror = () => console.error(`Failed to load image`);
                    img.src = "https://www.webkit.org/blog-files/acid3-100.png";
                    return img;
                })();
            }

            redraw() {
                console.log('redraw()');
                for(let n = 0; n < 20; ++n) {
                    const g = this.testLayer;
                    g.destroyChildren();
                    for(let i = 0; i < 100; ++i) {
                        const icon = new Konva.Image({image: this.image});
                        g.add(icon);
                    }
                }
            }
        }

        const ktest = new Ktest();
        setInterval(() => ktest.redraw(), 500);

    </script>
  </body>
</html>
```

**Comment by lavrton** [comment]
You were right. There was a memory leak in such case. I just released a new version with the fix. Please try it.

**Comment by AlexIII** [comment]
Can confirm the fix works. Thank you! 👍
