### ISSUE TITLE
How to draw a line with a single corner radius?

### ISSUE THREAD

**Issue by tangbc** [konvajs/konva#1156]
Just like this：

![image](https://user-images.githubusercontent.com/6846113/128167589-0182a3f9-3a03-4b25-873f-8d082587769e.png)

I see `Rect` is convenient to draw cornerRadius but cannot draw this case because `Rect` is tough to hide another two borders.

Thank you!

**Comment by lavrton** [comment]
For that use case you can use `Konva.Path`. You will have to learn how to generate path data https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths.

```js
const stage = new Konva.Stage({
  container: 'container',
  width: window.innerWidth,
  height: window.innerHeight
});

const layer = new Konva.Layer();
stage.add(layer);

const shape = new Konva.Path({
  x: 50,
  y: 50,
  data: 'M 0, 0 L 0, 50 A 20 20 0 0 0 20 70 L 70 70',
  stroke: 'green'
});
layer.add(shape);
```

https://jsbin.com/fefasurede/2/edit?html,js,output
