### ISSUE TITLE
Konva website is blocked in india

### ISSUE THREAD

**Issue by darcwader** [konvajs/konva#1159]
konvajs.org seems to be blocked in india. 

got this message when i open

```
Your requested URL has been blocked as per the directions received from Department of Telecommunications, Government of India. Please contact administrator for more information.
```
i can't open https://konvajs.org/ , cannot find admin email or account as i cannot open the website. i've read this happens as india DoT blocks cloudflare CDN . 

https://imgur.com/a/RgrYtq1

**Comment by lavrton** [comment]
I have no idea what I can do from my side.

**Comment by darcwader** [comment]
its working now. i'll close.
