### ISSUE TITLE
How to read the pixel-wise information in konva layers

### ISSUE THREAD

**Issue by AnranXu** [konvajs/konva#1160]
I am using konva.js as the basic library to realize a photo editing tool. Now I am working on a brush tool that will add mosaic to part of the image as it moves. 
To make it, I need to get the pixel-wise information of the canvas as I once did it based on original js code. 

That is to use code like 
`data = canvas.getContext('2d').getImageData(x,y,10,10);` to get the pixel information and generate mosaic by `ctx.fillRect(x,y,10,10);` based on the `data`.

However, when I am using konva.js classes like `Image` or `rect` and add them to the `layer`, I do not know how to get the pixel-wise data as the mouse moves. 

I tried the code written as follows:
```
      var width = window.innerWidth;
      var height = window.innerHeight;

      var stage = new Konva.Stage({
        container: 'container',
        width: width,
        height: height,
      });

      var layer = new Konva.Layer();

      var rect1 = new Konva.Rect({
        x: 20,
        y: 20,
        width: 100,
        height: 50,
        fill: 'green'
      });
      layer.add(rect1);

      var imageObj = new Image();
      imageObj.onload = function () {
        var image = new Konva.Image({
          x: 250,
          y: 250,
          image: imageObj,
          width: 100,
          height: 100,
        });

        // add the shape to the layer
        layer.add(image);
      };
      imageObj.src = './path/to/image.jpg';


      // add the layer to the stage
      stage.add(layer);
      // it should be green like (0,255,0) 
      console.log(layer.getCanvas()._canvas.getContext('2d').getImageData(30,30,1,1));
      // another way to get canvas context, it should be a color in the image 
      console.log(layer.getCanvas().getContext().getImageData(300,300,1,1));
```
However, the output shows that it cannot get the proper color of the image or rect in canvas.
The output also shows the colorSpace is 'srgb' (which is not appear in standard fillStyle) with weird data like (0,0,0,0) or (0,128,0,255).

I guess it is because we cannot read raw image data by canvas in the layer. Image elements are not on the canvas.
But if I want to do so, how can I do it? Also for function `ctx.fillRect(x,y,10,10);`
Or is there any way to realize a mosaic brush by konva.js?
Thank you so much.

**Comment by lavrton** [comment]
What is mosaic brush?

How does it look? I don't think Konva is a good framework for such use case. It is not designed for direct pixels manipulations directly on the canvas. The only exception is filters. 

> weird data like (0,0,0,0)

It is `rgba` color space.

**Comment by AnranXu** [comment]
I do not want to filter the whole parts of an image, I want the mosaic only added to the position where my mouse moves.
The function is just like https://konvajs.org/docs/sandbox/Free_Drawing.html shows but I want the brush color to be mosaic.
I have tried to combine native canvas with konva and now it has worked. 
Thank you. If there is another way to realize it, please tell me.
