### ISSUE TITLE
konvajs.org website blocked in India

### ISSUE THREAD

**Issue by iamsaurabhgupt** [konvajs/konva#1161]
Just saw this notice when i tried to access konvajs.org over internet provided by Airtel. 
It says "The website has been blocked as per order of Ministry of Electronics and Information Technology under IT Act, 2000."
Any specific reason why this has happened?
@lavrton 
![image](https://user-images.githubusercontent.com/43205009/128910750-03610d3c-813a-40b5-ac2a-306d783826d6.png)

**Comment by lavrton** [comment]
🤷‍♂️

**Comment by captn3m0** [comment]
👋🏽 2 Simple fixes for this issue:

1. Directly host the website on GitHub Pages, avoiding CloudFlare. Make sure you enable TLS at GitHub End
2. Enable Strict SSL on CloudFlare end. Make sure you enable HTTPS at GitHub side.

The reason this happens is because CloudFlare servers in India get MITMd by the network provider (Airtel) if the upstream is GitHub Pages and configured without end-to-end TLS.

Here's a very similar block story:

- https://forum.internetfreedom.in/t/website-blocking-report-and-wynk-ads-shantanugoel-com/2318

See [this twitter thread for more details](https://twitter.com/captn3m0/status/1468454402956533761)

**Comment by captn3m0** [comment]
Here's a complete curl log to demonstrate that Airtel does indeed MITM HTTPS connections by virtue of being between CloudFlare and Github.

<details><summary>Curl log</summary>
<pre>
curl https://konvajs.org -vvv
* Rebuilt URL to: https://konvajs.org/
*   Trying 172.67.222.159...
* TCP_NODELAY set
* Connected to konvajs.org (172.67.222.159) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Jun 11 00:00:00 2021 GMT
*  expire date: Jun 10 23:59:59 2022 GMT
*  subjectAltName: host "konvajs.org" matched cert's "konvajs.org"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* Using Stream ID: 1 (easy handle 0x563daae91600)
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> GET / HTTP/2
> Host: konvajs.org
> User-Agent: curl/7.58.0
> Accept: */*
>
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/2 200
< date: Fri, 07 Jan 2022 13:52:12 GMT
< content-type: text/html
< pragma: no-cache
< cache-control: no-cache
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=ZbPm9QGS7lrVxh1vhucoU19JGRbJVdH1H2ah4Xo7RXTEWSrqM%2BrWr8P9xtYVC8qF4CYUZmEscRbtdiynZh0ASkTqiYypsXkZiGeMzinNv46hlz0Bd8rR%2Fki5eDVAJg%3D%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 6c9daa4af89926b9-BLR
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400
<
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* Connection #0 to host konvajs.org left intact
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0"/><style>body{margin:0px;padding:0px;}iframe{width:100%;height:100%}</style><iframe src="https://www.airtel.in/dot/" width="100%" height="100%" frameborder=0></iframe>
</pre>
</details>

**Comment by lavrton** [comment]
@captn3m0 thanks a lot for details information.

I tried to change CloudFlare settings. I hope it will resolve the issue.

Can someone try it? Is website opening correctly from India?

**Comment by captn3m0** [comment]
Yes, looks like this is resolved. Thanks a lot!

I wrote a letter to CloudFlare detailing the issue, if you'd like to read more: https://github.com/captn3m0/hello-cloudflare
