### ISSUE TITLE
stage.toDataURL() returns empty string even if there are children of the stage.

### ISSUE THREAD

**Issue by indiubhaya** [konvajs/konva#1165]
stage.toDataURL() returns an empty string even if there are children of the stage.

stageRef.current.getStage().toDataURL({ quality: 1 });

Or

stageRef.current.getStage().toDataURL();
![image](https://user-images.githubusercontent.com/15166145/130379852-e2136f9b-024e-4e13-94ee-0235bdbf24c2.png)
![image](https://user-images.githubusercontent.com/15166145/130379907-bf466656-f635-450d-9a91-201642002f55.png)

![image](https://user-images.githubusercontent.com/15166145/130379881-7adadb8a-ee17-4f55-baa7-0a6aae26947f.png)

**Comment by lavrton** [comment]
Do you have any warnings in the console?
