### ISSUE TITLE
Konva  how to add ID for the Transformerwhen i do  new Transformer()

### ISSUE THREAD

**Issue by OnePsycho** [konvajs/konva#1167]
Konva  how to add ID for the Transformerwhen i do  new Transformer()

**Comment by OnePsycho** [comment]
I need to delete the transformer specified in the layer

**Comment by lavrton** [comment]
The same way as for any other `Konva.Node` instance.

**Comment by OnePsycho** [comment]
i read the doc , but i do not find how to delete the transformer specified in the layer  can you help me . I'm a novice thank you

**Comment by lavrton** [comment]
```js
const tr = new Konva.Transformer({ id: 'my-transformer' });
layer.add(tr);
// later
layer.findOne('#my-transformer').destory();
```

**Comment by OnePsycho** [comment]
thank you !
