### ISSUE TITLE
_transformedRect rounded return value causes inaccuracies 

### ISSUE THREAD

**Issue by hoolymama** [konvajs/konva#117]
Hi, 

The _transformedRect function returns a rectangle with x, y, width, and height values that have been rounded. This can cause inaccuracies in some situations. For example, In my app I have an Image node. I calculate the aspectRatio (A), then set the size to 1X(1/A). 
The image is a added to a group and the group is scaled to fit the canvas. Lets say the original image was 640X480. If I call getClientRect() on the group, the width and height of the result will be 640X640 as the 0.75 was rounded up to 1.

For the moment I override the function. I could also change the way I manage images, but I think really the transform function should not lose precision because there may be many transformations concatenated.

Thanks

**Comment by lavrton** [comment]
In terms of pixels why do you need such accuracy? Or what is your use case of `getClientRect()`?

**Comment by hoolymama** [comment]
Hi, I'm using getClientRect() to because I made a scale manipulator that is used to scale an image from either of the 4 corners of the image. I could calculate it from the original image w/h and its relation to the group, but that would be doing what getClientRect() does. The reason I set the underlying image size to 1 is to make the math easier. The image displays fine. I don't mind changing and have the image width set to the original image pixels - but as I noticed this case I thought I should mention it. As I understand, you want the final result of getClientRect() to be integer values. But If there are many nested groups, It looks like _transformedRect() be called recursively and will round off values many times.

**Comment by lavrton** [comment]
I still do not understand the issue. Why integer values are not working for you? Can you provide example where rounding causes problems?

**Comment by hoolymama** [comment]
Thanks, yes, I'll make an example tonight.

**Comment by hoolymama** [comment]
Hi Anton, 
I made a [plunk here ](http://plnkr.co/edit/cP6p8cQqYh3Bp8z9jfNP?p=preview) 
There is a readme there too. 
Many thanks!!

**Comment by lavrton** [comment]
Good example. I need to think about a way to create unit test for such case.

**Comment by lavrton** [comment]
Fixed in https://github.com/konvajs/konva/commit/3c1e2804deb4785ec64dadf474bf3a110b3989f3.
