### ISSUE TITLE
Jest Unit Test Cannot find module 'canvas' from 'node_modules/konva/lib/index-node.js'

### ISSUE THREAD

**Issue by VincentNewkirk** [konvajs/konva#1175]
Jest: 26.6.3
Konva: 8.0.1

When running a UT with jest on a  file that imports Konva, I receive 
```Cannot find module 'canvas' from 'node_modules/konva/lib/index-node.js'```

This is what my jest.config.json looks like
```
{
  "moduleNameMapper": {
    "\\.(scss)$": "identity-obj-proxy"
  },
  "transformIgnorePatterns": [
    "node_modules/(?!(konva)/)"
  ],
  "modulePaths" : ["<rootDir>/src/"],
  "collectCoverageFrom": [...]
}
```

Any help would be greatly appreciated

**Comment by lavrton** [comment]
Did you try this https://github.com/konvajs/konva#4-nodejs-env ?

**Comment by zarv1k** [comment]
Experiencing the same problem with `create-react-app` setup. I solve that by adding the following in my `package.json`:

```json
"jest": {
    "moduleNameMapper": {
      "^konva": "konva/konva"
    }
}
```

**Comment by mostja01** [comment]
If it is just for testing purposes, the jest configuration can be set up to take jest-canvas-mock instead of the canvas.

Add `canvas: 'jest-canvas-mock` into the `moduleNameMapper` configuration in jest.config.js file.

**Comment by titenis** [comment]
When using vite, vitest, konva: 
@lavrton the problem is that canvas package is not compatible with vitest multithreads and turning off threads, just because of single test is not really an option :/
also aliasing in vite config didnt help, I couldnt force it to use vitest-canvas-mock.
Any ideas how to mock canvas by hand?

**Comment by lavrton** [comment]
@titenis please make a minimal demo to reproduce.

**Comment by drewbobO1** [comment]
> Did you try this https://github.com/konvajs/konva#4-nodejs-env ?

Was running into the same message. Manually installing the canvas package fixed the issue right away. Thanks for the direction.

**Comment by zhouhuiquan** [comment]
> If it is just for testing purposes, the jest configuration can be set up to take jest-canvas-mock instead of the canvas.
> 
> Add `canvas: 'jest-canvas-mock'` into the `moduleNameMapper` configuration in jest.config.js file.

这个有用, 谢谢!

**Comment by mttetc** [comment]
Same issue with vitest, I cannot install canvas manually in node version higher than 14 but vitest is not comptible with this version. Kind of at a loss right now.

**Comment by lavrton** [comment]
>  I cannot install canvas manually in node version higher than 14

Why?

**Comment by russcarver** [comment]
> If it is just for testing purposes, the jest configuration can be set up to take jest-canvas-mock instead of the canvas.
> 
> Add `canvas: 'jest-canvas-mock'` into the `moduleNameMapper` configuration in jest.config.js file.

Don't forget to add 'jest-canvas-mock" into your package.json file.

**Comment by ShinaZin** [comment]
If you still get the error after all these steps, try adding `'^konva': 'konva/konva'` to `moduleNameMapper` in the `jest.config.js` file.
