### ISSUE TITLE
Dash is only visible on Konva.Arrow if pointerAtEnding is true

### ISSUE THREAD

**Issue by Hexalyse** [konvajs/konva#1181]
As the title says, I've noticed a weird behavior:

If I define a `dash` on a `Konva.Arrow`, the dash is only applied if `pointerAtEnding` is true. As soon as I disable the pointer at ending (and even if there is a pointer at the beginning!), the dash effect disappears, independently of the `dashEnabled` property.

Here is a JSBin with the problem showed : https://jsbin.com/hubicivedi/edit?html,css,js,output

**Comment by lavrton** [comment]
That was a bug. Just made a fix. I will make a new release later.

**Comment by lavrton** [comment]
Thanks for the report.

**Comment by Hexalyse** [comment]
Thanks for the very quick fix! Awesome!
