### ISSUE TITLE
Safari in iOS 15 performance issues

### ISSUE THREAD

**Issue by Joebayld** [konvajs/konva#1182]
Hi! 

So I have a konva canvas thats quite large - about 5000x5000. I've found that there's a new feature in iOS that drops the konva performance very significantly. Dragging has almost a second delay. It's called "GPU Process: Canvas Rendering". It's essentially GPU acceleration for the HTML canvas. It's defaulted to being enabled for iOS 15, but this completely breaks my app.

On a iPhone or iPad, you can go to safaris experimental features and disable it, then the performance drastically increases. I'm not sure if this is something that can be fixed but thought I'd bring the issue up. 

Thoughts?

**Comment by lavrton** [comment]
Why do you need such a large canvas? The screen size is smaller. For that case, you can do this: https://konvajs.org/docs/sandbox/Canvas_Scrolling.html#page-title

**Comment by Joebayld** [comment]
My app requires the large canvas for pixel accuracy as well as zooming in/out. There’s still a problem introduced with iOS 15 though. 

I do have an update. It looks like the issue is with large svg images. If I remove all the images the performance increases, but my app requires them. 

I’m going to try the other methods of drawing svg images, but would prefer the image node method would perform better.

**Comment by lavrton** [comment]
For the SVG, you can "rasterize" it before drawing into the canvas. You need to draw SVG into an external canvas element. And then use that canvas element for `Konva.Image`. It may improve performance a lot. And you can control quality of that process by changing the size of the external canvas.

**Comment by Joebayld** [comment]
Okay so draw to a canvas without konva, then use that as a image data source? Any examples of this?

The big thing here is to preserve the same size as like I said I’m doing pixel accurate work. 

It’s kind of odd that this new GPU acceleration broke something very specific. I’ll keep trying for a workaround but seems apple has some fixing to do as well?

**Comment by lavrton** [comment]
```js
const canvas = document.createElement('canvas');
canvas.width = nativeImage.width;
canvas.height = nativeImage.height;
canvas.getContext('2d').drawImage(nativeImage, 0, 0);
const image = new Konva.Image({
  image: canvas
})
layer.add(image);
```
