### ISSUE TITLE
how to add and remove tranform dynamically just by clicking

### ISSUE THREAD

**Issue by ibalaji777** [konvajs/konva#1184]
i want to add and remove Transform just by click in mouse event Left mouse button.

**Comment by lavrton** [comment]
What did you try?

**Comment by ibalaji777** [comment]
> What did you try?

stage.on('click', function (e) {
        // e.target is a clicked Konva.Shape or current stage if you clicked on empty space
        console.log('clicked on', e.target);
        console.log(
          'usual click on ' + JSON.stringify(stage.getPointerPosition())
        );
        console.log(e)
        if(e)
         currentShape = e.target;
        // var shape = stage.find(e.target._id);
        console.log(shape)
                   if(currentShape){
        	 tr.nodes([currentShape]);
             }
      });

**Comment by lavrton** [comment]
Demo?

**Comment by ibalaji777** [comment]
[https://codepen.io/ibalaji777/pen/wveNOeK](https://codepen.io/ibalaji777/pen/wveNOeK)

**Comment by lavrton** [comment]
On mobile you need to use mobile event `tap` in addition to `click`.

```js
stage.on('tap click', () => {});
```

Also if you use Konva version 7 you need to manually update layer on any changes. `layer.draw()`. You don't need to do that with the last Konva version 8.

**Comment by ibalaji777** [comment]
How to remove  transform?

**Comment by ibalaji777** [comment]
i found but it throws error instead of doing togle transform
```

 stage.on('click', function (e) {
        // e.target is a clicked Konva.Shape or current stage if you clicked on empty space
        // console.log('clicked on', e.target);
        // console.log(
        //   'usual click on ' + JSON.stringify(stage.getPointerPosition())
        // );
        // console.log(e)
  if (e.target === stage) {
          // if we are on empty place of the stage we will do nothing
          return;
        }
        if(currentShape){
    const tr_node = layer.find('Transformer').find(tr => tr.nodes()[0] === currentShape);
  //  console.log(tr)
   if(tr_node){
   tr_node.remove();
  layer.draw();

   }
        }
         currentShape = e.target;

        if(currentShape)
        	  tr.nodes([currentShape]);
              layer.draw();
      });

  },
```

**Comment by lavrton** [comment]
Demo? On your code example, I see that you are removing Transformer from the layer, but don't add it back later.

**Comment by SilvaQ** [comment]
I modified your code a little bit, it works as expected now, give it a try

```js
var width = window.innerWidth;
var height = window.innerHeight;
let currentShape;
var stage = new Konva.Stage({
  container: "container",
  width: width,
  height: height,
});

var layer = new Konva.Layer();
tr = new Konva.Transformer({
  keepRatio: true,
  rotationSnaps: [0, 90, 180, 270],
  //  enabledAnchors: [
  //       'top-left',
  //       'top-right',
  //       'bottom-left',
  //       'bottom-right',
  //     ],
});

layer.add(tr);
var rect1 = new Konva.Rect({
  x: 20,
  y: 20,
  width: 100,
  height: 50,
  fill: "green",
  stroke: "black",
  draggable: true,
  strokeWidth: 4,
});
// add the shape to the layer
layer.add(rect1);

// add the layer to the stage
stage.add(layer);

stage.on("click", function (e) {
  currentShape = e.target;
  if (currentShape === stage) {
    tr.nodes([]);
  } else {
    tr.nodes([currentShape]);
  }
  layer.draw();
});


```
