### ISSUE TITLE
how to update shape width and height?

### ISSUE THREAD

**Issue by ibalaji777** [konvajs/konva#1185]
i want to overwite rectangle shape of width and height. i have simple example given in docs  ;

      var stage = new Konva.Stage({
        container: 'container',
        width: width,
        height: height,
		fill: "white",
      });
      var layer = new Konva.Layer();
      stage.add(layer);
	  
	   var bg = new Konva.Rect({
        x: 0,
        y: 0,
        width:width ,
        height:height ,
        fill: 'white',
        draggable: false,
      });
      layer.add(bg);
	
Now want to update above rect dynamically.

**Comment by lavrton** [comment]
`bg.width(newWidth)`
