### ISSUE TITLE
Bug with `mouseenter` event

### ISSUE THREAD

**Issue by lavrton** [konvajs/konva#119]
Need to recheck `stopBubble` condition for nodes with different group nesting level.

Demo: http://jsbin.com/lixeco/edit?js,output

**Comment by lavrton** [comment]
Just found another issues: http://jsbin.com/lixeco/2/edit?js,output

**Comment by DMIAOCHEN** [comment]
so.. does group1 should fire mouseenter?  there are nothing in group1!

**Comment by lavrton** [comment]
@DMIAOCHEN Ah. Right.  Thanks. I made a typo. But bug still exists: http://jsbin.com/lixeco/4/edit?js,output
`mouseenter` from red to green is not working.

**Comment by DMIAOCHEN** [comment]
i see.. that red rect's parent layer is also green rect's Ancestor so bubble stop，Eh.. there maybe a isParentOf test
