### ISSUE TITLE
Hue-rotate using `Filters.HSL` is an imperfect approximation

### ISSUE THREAD

**Issue by WeeJeWel** [konvajs/konva#1193]
When transforming an image using `Konva.Filters.HSL`, and only setting `hue()`, the output is not an exact Hue rotate (as for example Photoshop does). Luckily, it's better than CSS's `hue-rotate` ;)

For example, for an image that's full `#FF0000`:

Rotate by `120`: `#182AFF`, expected: `#0000FF`
Rotate by `240`: `#00BA00`, expected: `#00FF00`

**Comment by lavrton** [comment]
Closing as "wont-fix". Any related Pull Requests are very welcome.
