### ISSUE TITLE
Wierd shape absolutePosition when stage scaled or moved

### ISSUE THREAD

**Issue by aeshakhzod** [konvajs/konva#1201]
Hey there! Loved this library, thank you very much.

While I'm playing with this library, I faced a strange bug, or idk.

Look this: https://jsfiddle.net/jhzefraw/18/ and try zoom stage, do some drag on it.

The drag problem is solved by doing this: https://jsfiddle.net/jhzefraw/19/ (line 66), but the zoom problem still exists.

Can you help solve it?

**Comment by 359126613** [comment]
> If they are not different levels you can use this:
> 
> ```js
> const getRelativePoint(node, absPos) {
>     var transform = node.getAbsoluteTransform().copy();
>     // to detect relative position we need to invert transform
>     transform.invert();
>     // now we can find relative point
>     return transform.point(absPos);
>   }
> ```How do I convert relative coordinates to absolute coordinates?Thank you very much

**Comment by 359126613** [comment]
> If they are not different levels you can use this:
> 
> ```js
> const getRelativePoint(node, absPos) {
>     var transform = node.getAbsoluteTransform().copy();
>     // to detect relative position we need to invert transform
>     transform.invert();
>     // now we can find relative point
>     return transform.point(absPos);
>   }
> ```

@lavrton How do I convert relative coordinates to absolute coordinates?Thank you very much

**Comment by 359126613** [comment]
If they are not different levels you can use this:
   
// this function will return pointer position absolute to the passed node
function getAbsolutePosition(node,pos){
	var transform = node.getTransform().copy();
	// to detect absolute position we need to invert transform
	transform.invert();

	// now we can find absolute point
	return transform.point(pos);
	
}

**Comment by 359126613** [comment]
> 

@lavrton 
If they are not different levels you can use this:

// this function will return pointer position absolute to the passed node
function getAbsolutePosition(node,pos){
var transform = node.getTransform().copy();
// to detect absolute position we need to invert transform
transform.invert();

// now we can find absolute point
return transform.point(pos);
}
