### ISSUE TITLE
feature request: Simple layout systems

### ISSUE THREAD

**Issue by shakhzodkudratov** [konvajs/konva#1204]
Hey there again!

Would be nice to see here some layout systems as Flutter does.
Row: https://api.flutter.dev/flutter/widgets/Row-class.html
Column: https://api.flutter.dev/flutter/widgets/Column-class.html
and so on

I've done some helper classes, but it will be nice if the plugin will have it out of the box.
I can contribute.

Would like to hear your thoughts. Thank you!

**Comment by gautam1168** [comment]
Hey did you guys make a package for this? I want this and if there is already some package Ill start with that before I start writing my own
