### ISSUE TITLE
Suggestion: Add important and frequently asked questions to the document

### ISSUE THREAD

**Issue by SilvaQ** [konvajs/konva#1206]
有没有可能在文档中补充专门讲解坐标，坐标相关常用参数、函数，坐标转换工具的使用和相关原理等内容和对应的例子程序。
比如：
1. 什么是x,y?
2. 什么是 offsetX和offsetY
3. 什么是起始点，如何知道哪个形状的起始点在哪里？
4.  position()函数 position(pos) 做了什么，需要注意什么？
5. relativePosition, absolutePosition是什么，分别如何获取，如何相互转换？什么时候使用哪个？什么时候不能使用哪个？
6. 为什么layer不支持width和height，原因和好处？
7. 为什么group和它的子孙坐标是基于group的，这样设计的目的？group子孙使用坐标需要注意哪些细节？
8. dragBoundFunc 的作用，以及它的坐标注意事项，需要的转换方法和原因？
9. dragBoundFunc 里面获取到的x,y和 dragEnd 事件中获取到的x,y 有啥区别，为什么？

我作为一个初学者，最近一段时间被这些问题折腾了很多，每次都是通过看源码以及相关demo自己去体会并总结的，如果文档中有专门的章节吧这些概念说清楚了，我相信对更多像我这样初学者有非常好的帮助，大家也能更愉快的做出更多更好的应用。

Is it possible to supplement the document with special explanation of coordinates, common parameters and functions related to coordinates, the use of coordinate conversion tools and relevant principles and other content and corresponding example programs?

Such as:

1. What are x and y?

2. What are offsetX and offsetY

3. What is the starting point and how do I know where the starting point of a shape is?

4. What does the position() function position(pos) do and what should I pay attention to?

5. What are relativePosition and absolutePosition? How to obtain them and convert them to each other? When to use which? When can you not use which one?

6. Why does layer not support width and height?

7. Why are coordinates of group and its descendants based on group? What details should be paid attention to when using coordinates for group descendants?

8. What is the function of dragBoundFunc and its coordinate considerations? What conversion methods are required and why?

9. What is the difference between x and y retrieved from dragBoundFunc and dragEnd?

As a beginner, I recently for a period of time was the problem with a lot of, every time is by looking at the source code and related demo to understand and summarize the, if you have any special section in the document these concepts make myself clear, I believe that is very good for beginners like me more help, we can be more happy to make more and better applications.

**Comment by lavrton** [comment]
Closing, as I think there are already answers for most of these questions in docs. I am ok to answering more specific questions.
