### ISSUE TITLE
Blurred svg image in iOS15

### ISSUE THREAD

**Issue by tangbc** [konvajs/konva#1207]
I draw svg icon in this way:
```js
Konva.Image.fromURL('/url.svg', (image) => {
  layer.add(image);
});
```

It works fine in iOS 14:
<img width="44" alt="ios14" src="https://user-images.githubusercontent.com/6846113/139644047-51db03f5-87ed-49d3-810a-12cfc04b93a3.png">

But after I upgrated my iPhone to iOS 15.1, it becomes blurred:
<img width="44" alt="ios15" src="https://user-images.githubusercontent.com/6846113/139644262-0aa426d5-374a-4473-adec-e1b165318c28.png">

Version: 8.2.3

Does anyone have this problem?

**Comment by lavrton** [comment]
Can you make a quick online demo? With jsfiddle or something?

**Comment by tangbc** [comment]
I make a simple demo here:
https://tangbc.github.io/others/konva-test.html

In iOS 15:
![image](https://user-images.githubusercontent.com/6846113/140676934-5ea49b31-33c5-4aa4-8c25-98a2322ea13d.png)

In iOS 14:
![image](https://user-images.githubusercontent.com/6846113/140676993-3b601036-76af-46f7-9924-6fc0b1ace35c.png)

In macOS 12.0.1 Safari:
<img width="459" alt="MacBook Safari" src="https://user-images.githubusercontent.com/6846113/140677110-7a8abdce-dbaf-4d81-8136-d10a0202c78f.png">

In macOS 12.0.1 Chrome:
<img width="500" alt="MacBook Chrome" src="https://user-images.githubusercontent.com/6846113/140677158-3bdf6855-2abb-46ab-8c89-0803469ea67c.png">

Looks like it's the latest version of IOS and MacOS.

**Comment by lavrton** [comment]
To me, that looks like unexpected behavior from Safari. I am not sure if we can do much here from Konva side.

As a workaround, you can render SVG into a bigger external canvas and then use canvas as `image` property for `Konva.Image`.

```js
// img - is loaded svg image

const canvas = document.createElement('canvas')
canvas.width = img.width * 2;
canvas.height = img.height * 2;
canvas.getContext('2d').drawImage(img, 0, 0, canvas.width, canvas.height)

imageNode.image(canvas);
// set original size
iamgeNode.width(img.width);
iamgeNode.height(img.height);
```

**Comment by AidanRRR** [comment]
Same issue here. Indeed, starting from iOS 15. Also on the mac OS monterey. Thanks for your workaround though!

**Comment by domi7777** [comment]
maybe this could help? https://konvajs.org/api/Konva.Canvas.html#pixelRatio__anchor
