### ISSUE TITLE
TypeScript definitions for Konva do not support its 'dragmove' event

### ISSUE THREAD

**Issue by mixaildudin** [konvajs/konva#1210]
Typings for `on` method are based on `GlobalEventHandlersEventMap` from lib.dom.d.ts, and it knows nothing about Konva's `dragmove` event. So I have to write the following code:

```typescript
result.on('dragstart', this.handleDragStart);
result.on('dragend', this.handleDragFinish);
result.on('dragmove' as any /*HERE*/, this.handleDragMove);
```

**Comment by lavrton** [comment]
We are using `GlobalEventHandlersEventMap` incorrectly. I think we should have out own events map.
Are you interested to make a Pull Request with a fix?

**Comment by mixaildudin** [comment]
Yeah, I think I would do it.
Honestly, I am a bit too busy these days, but I don't think this is a very high-priority issue. So if you think it can wait for a couple of weeks at least, I'd love it if you assign this one to me.
