### ISSUE TITLE
Feature Request: Hyphenation of Konva Text

### ISSUE THREAD

**Issue by clselin** [konvajs/konva#1211]
It would be wonderful if there was some kind of hyphenation feature in Konva that could be used in conjunction with wrap={'char'}. I have instances where text needs to fit into a specific shape, but it's dynamic, leading to some clunky readability problems with words cutting off, where the truncated word looks like a whole word. A hyphen would make things clearer and make it so the user can tell the word isn't finished so they don't read something odd like - 

"New advice for me
dical practitioners"  

When it would be great as 

"New advice for me-
dical practitioners" 

Alternately, has anyone worked out any tricky ways to filter the text to make this happen, if the feature doesn't exist in Konva?

**Comment by lavrton** [comment]
Closing as not a priority. Probably you can solve that issue by read `textArr` property of `Konva.Text` instance.
