### ISSUE TITLE
Create Konvajs Shapes and Connections creating dynamically based on button click events.

### ISSUE THREAD

**Issue by Aravinda93** [konvajs/konva#1212]
I would like to create `Rectangle Shapes` and `Connections` using the `Vue-Konva/Konvajs` within my application. I do not want to create load the `Static` values rather I would like to create the `Shapes` when the user clicks on the `Add Node` button and create `Connectors` when the user clicks on the `Add Connector` button and build the connections between `Shapes`.

I looked into a few things and was able to do it using the `mouse events` but was unable to convert it to `button clicks`.

Following is the current code I have: [CodeSandbox][2]

Can someone please guide me on how to create shapes and connectors on click of the button events? Any suggestion or guidance is much appreciated.

I am looking something like this:
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/ZXoVy.png
  [2]: https://codesandbox.io/s/dreamy-merkle-vcmku?file=/nuxt.config.js

**Comment by lavrton** [comment]
Please don't spam with your question everywhere. As I can see, you found a solution.  https://stackoverflow.com/a/69854115/512042
