### ISSUE TITLE
Konvajs/Vue-Konva connect the shapes using the connector dynamically

### ISSUE THREAD

**Issue by Aravinda93** [konvajs/konva#1215]
I am really sorry but unable to find an answer or get any response elsewhere and stuck in this for the last 2-3 days so posting here for some help as a last resort.

I am using `Konvajs/Vue-Konva` within my `Vuejs/Nuxt` application. Using `Konva` I am creating the `Rect` shape dynamically at run time. Now I would like to use some sort of `Connectors` to connect the `Rect Shapes` so that I can have the logic of which is `source Rect` and which is `Target Rect`. 

I am creating the `connectors` using the same approach as `shapes` but for some reason, it is not working as expected. I have added my code sample here in [CodeSandBox][1].

Can someone please let me know how can I add the `Connectors` and build the logic to understand `Rect/Shape` that has been created using `Vue-Konva`? I am trying to do something like this:

![CPT2111081318-1890x906 (1)](https://user-images.githubusercontent.com/29374160/140740896-2e7084af-3522-48ff-8d39-171c2a2c51ad.gif)

  [1]: https://codesandbox.io/s/dreamy-merkle-vcmku?file=/pages/index.vue

**Comment by lavrton** [comment]
https://github.com/konvajs/vue-konva/issues/177
