### ISSUE TITLE
Change anchor position of custom cursor image

### ISSUE THREAD

**Issue by collinsmwade** [konvajs/konva#1216]
Hello, I am using a custom cursor with Konva. It's a breeze to set up, so thank you :)

**I would like to change the anchor position/origin of the custom image.** I am encountering the following problem implementing a drawing tool:

![image](https://user-images.githubusercontent.com/3690795/140781959-f628da2b-9e9e-4ddb-bfdb-41509210221a.png)

Konva interprets the actual cursor position as the top left of the image. I would like to anchor the image to be pinned on the bottom left, so the cursor mousedown point lines up with the "lead" part of the pencil icon.

It might look something like this:
`stage.container().style.cursor = 'url(images/cursor-draw), auto, bottom left'`

Thanks again!

**Comment by lavrton** [comment]
https://stackoverflow.com/questions/19560878/css-change-custom-cursor-image-origin-hotspot-to-center
