### ISSUE TITLE
stage.find('Transformer').destroy() is not work at konva version 8.2.2.

### ISSUE THREAD

**Issue by SophiaLeeXJ** [konvajs/konva#1219]
Thank you for submitting an issue!

Please make sure to check current open and closed issues to see if your question has been asked or answered before.
If you have just a question (not a bug or a feature request) it is better to ask it in [Stackoverflow](http://stackoverflow.com/questions/tagged/konvajs).

If you have a bug, please, try to create a reproducible example with jsfiddle (or any similar service).
You can use [this JSBIN](https://jsbin.com/tekehizuta/1/edit?html,js,output) as a template.

**Comment by SophiaLeeXJ** [comment]
But at version 6.0.0 is ok.

**Comment by lavrton** [comment]
Did you check changelog for breaking changes?

**Comment by SophiaLeeXJ** [comment]
I checked the destroy-related information in the change log and found that the version 6.0.0 fixes the destroy-related bug, so I changed the konva version to 6.0.0 and found that it was available.

**Comment by lavrton** [comment]
See `find()` method changes: https://github.com/konvajs/konva/blob/master/CHANGELOG.md#800

**Comment by SophiaLeeXJ** [comment]
That's it, I got it, Thank you very much!
