### ISSUE TITLE
cancelBubble is not preventing event bubbling

### ISSUE THREAD

**Issue by jonnypcook** [konvajs/konva#123]
This issue could be related to: https://github.com/konvajs/konva/issues/119

Previously I was able to use event.cancelBubble to prevent events firing down the stack.  Now neither event.cancelBubble or event.evt.cancelBubble seem to have any effect meaning that I have to manually check for cancel flag in event methods.

Looks like the issue is at line 4011 where ((evt && !evt.cancelBubble || !evt) should be replaced or combined with: (evt.evt && !evt.evt.cancelBubble || !evt.evt).  Seems to resolve the issue for me.

Note: this behaviour has exhibited itself in mouse move and drag/drop events in our codebase but will probably be an issue on other event types.

**Comment by lavrton** [comment]
Right. I see the bug. Thanks for report.

**Comment by bensquire** [comment]
@lavrton Also encountered this bug, would love to be able to role the new version into production... (P.S: Great work)

**Comment by lavrton** [comment]
You can use last build in repo. New version will be later.
