### ISSUE TITLE
Blurry text issue for small font sizes.

### ISSUE THREAD

**Issue by regenrek** [konvajs/konva#1236]
Hi,

I've struggled with this a lot and went through certain issues on stackoverflow but still no resolution yet.

Here is a quick codepen: https://codepen.io/kkern/pen/NWvJerO?editors=0011

Is there a possibility to disable anti antialiasing or avoid the blurry text on small font sizes? 

I'm working on an app where I need small font sizes with crystal clear fonts (or pixelated). 

Here is a comparison of konvajs/canvas
![image](https://user-images.githubusercontent.com/5182020/142703693-f9831829-2ea1-4c24-97a7-1d1d85ae7897.png)

And here is a native windows app without canvas (usually sharper but screenshot seems also blurry)
![image](https://user-images.githubusercontent.com/5182020/142703733-395b1b29-4246-46c5-8dc9-bde7de535718.png)

I've read also into but probably not related.
https://github.com/konvajs/konva/issues/1079

EDIT: Updated the demo above. On the left is the canvas and on the right HTML.

**Comment by lavrton** [comment]
As far as I know, there is no direct 2D canvas API to draw a text without antialiasing.

As a workaround, you can:
1. Draw text into external canvas
2. Iterate over all pixels in that canvas. Remove antialiased pixels.

**Comment by regenrek** [comment]
Hi,

thank you very much for the answer. Do you have some articles / examples with the given approaches? 
Would like to build a demo with both to see what I can get.

Regards
