### ISSUE TITLE
konva node Emoji not exporitng in its intended icon

### ISSUE THREAD

**Issue by Senthilkite** [konvajs/konva#1237]
While using the below code in konva node and exporting it as a base64 code and rendering it to an image, 
let complexText = new Konva.Text({
    x: 0,
    y: 0,
    text: "🔑 hello World 🤗 ",
    fontSize: 12,
    fill: "#003049",
    padding: 5,
    align: "center",
    fontFamily: "Arial",
  });

the emojis are displaying like a text instead of an emoji. Refer the image below

![Screenshot 2021-11-20 221908](https://user-images.githubusercontent.com/69422235/142756758-c0b91c6a-4937-4e46-beb3-c17159333cd0.png)

**Comment by lavrton** [comment]
There is nothing Konva can do there.

Emoji rendering depends on the operating system, available fonts, etc. Also node renderer may work differently from browser renderer.
