### ISSUE TITLE
Questions about transformer.flipEnabled.

### ISSUE THREAD

**Issue by mashroom33** [konvajs/konva#1239]
When i set transformer.flipenabled(false) and i noticed that when it comes to flipping, node really does not flip,  but the upper-left corner position suddenly changes.

**Comment by lavrton** [comment]
Can you please clarify your issue? What is not expected for you? Can you make a demo?

**Comment by mashroom33** [comment]
Sorry, it's not convenient for me to take a demo. I mean, for example, i create transformer A, and do A.flipenabled(false), and i drag right-bottom anchor quickly, this time i just want to scale node, but it's position also changed strangely.

**Comment by mashroom33** [comment]
It occurs every time when i drag right-bottom anchor lefter than the left-top anchor.
