### ISSUE TITLE
fill and stroke for lines

### ISSUE THREAD

**Issue by jthrilly** [konvajs/konva#124]
Is there a way to have Konva lines include a fill and a stroke? 

In the screenshot below, I want to make the lines running between the circles more visible against the background color. I cannot change the colors involved here as they are user defined. The best solution would be to be able to add a small stroke to the outside of the line. However, lines are built using stroke width already.

Is there a solution?

I have experimented with the width and fill properties of the line to no avail.

![example](https://cloud.githubusercontent.com/assets/1387940/12493037/2d697eea-c07b-11e5-917e-51a269bb6c0a.PNG)

**Comment by lavrton** [comment]
So why you can not increase `strokeWidth`?

**Comment by jthrilly** [comment]
Strokewidth sets the width of the line. I want a stroke (in a different color) on the outside of the current width.

**Comment by jthrilly** [comment]
Like for example:
![92elf](https://cloud.githubusercontent.com/assets/1387940/12497078/79c942c8-c091-11e5-9ec6-904023652c74.png)

**Comment by lavrton** [comment]
As you are already using `stroke` I think there are two good ways to solve it:

1. Draw `closed` line in the path of your stroke. Then you will be able to use fill property.
2. Draw two lines. (Probably this is best way).

Take a look: http://jsbin.com/cecaka/edit?js,output

**Comment by jthrilly** [comment]
Thanks for your help. Those examples work well.

A third option is to use the built in shadow functionality to achieve the effect I desire. I do think this would be good functionality to have for the line object, though.

Thanks again.

**Comment by sebastian-wolfram** [comment]
> I do think this would be good functionality to have for the line object, though.

Samesies, I used the two line approach to simulate the stoke and fill on a line. Would be better if fill actually worked.

**Comment by projektorius96** [comment]
> As you are already using `stroke` I think there are two good ways to solve it:
> 
> 1. Draw `closed` line in the path of your stroke. Then you will be able to use fill property.
> 2. Draw two lines. (Probably this is best way).
> 
> Take a look: http://jsbin.com/cecaka/edit?js,output

Hi, @lavrton , it would be nice to have saying it on [docs](https://konvajs.org/api/Konva.Line.html) that you must met `closed: true` to have a fill working properly i.e. if fill is required make sure `closed` is set to `true` . Thank God Googling worked for me and I found this answer . Personally I do use trigonometry functions to draw universal shapes, starting from periodic functions, ending up with haver circles . Finally I made the fill work to me . Cheers !
