### ISSUE TITLE
Usage in NodeJS context (server-side)?

### ISSUE THREAD

**Issue by antonioandrade** [konvajs/konva#1240]
What's the recommended way to use this library on the server side?
The goal is to **render images from canvas in Node.js context**.

The [README mentions](https://github.com/konvajs/konva#4-nodejs-env) that is possible but is lean on samples...
Looked through the unit tests but it seems they are all executed in DOM context.

When in Node.js context I get the message `Error: Stage has no container. A container is required.` (basic example [here](https://codesandbox.io/s/elegant-parm-lvihp?file=/src/index.ts)).
So, I thought to myself: alright, perhaps it needs something like JSDOM to create some `div` container. In that case, the `dataUrl` is returned empty.

I'm aware of [this answer](https://stackoverflow.com/a/57759816/6183195) too but supposedly `node-konva` is deprecated (as in, merged into the main `konva` package), right?
The `canvas` package is included as a dependency already too on my projects, I believe that isn't the issue.

**Finally**, node samples under https://github.com/konvajs/konva/blob/master/konva-node/index.js are still referring to `node-konva` and `konva@7`... should I simply downgrade to version 7?

**Comment by antonioandrade** [comment]
I also considered updating/reusing the wrapper https://github.com/konvajs/konva/blob/master/konva-node/index.js but so far that's not working for me either... From what I see `canvas` constructor [takes params](https://github.com/Automattic/node-canvas/blob/master/types/index.d.ts#L81) and those are [not being passed in](https://github.com/konvajs/konva/blob/master/konva-node/index.js#L24)?!

**Comment by lavrton** [comment]
I updated the readme: https://github.com/konvajs/konva#4-nodejs-env

**Comment by antonioandrade** [comment]
Thanks @lavrton I suspected that was what you meant... shouldn't `StageConfig` interface be updated to reflect this usage (I mean, either a container OR width-height)?

Anyway, I seem to be on the right track, I'm getting something out of `toDataUrl()` on my stage : )

**Comment by antonioandrade** [comment]
Solved, closing this.
