### ISSUE TITLE
Memory leak in the NodeJS environment on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by severinv42** [konvajs/konva#1247]
**Environment:**
Ubuntu 20.04.3 
NodeJS v12.18.4
konva v8.3.0
canvas v2.8.0

Consider following peace of code:
```javascript
const Konva = require('konva/cmj').default;

console.log('before all', process.memoryUsage().rss);

for (let i = 0; i < 1000; i++) {
  const stage = new Konva.Stage({ width: 1920, height: 1080 });
  stage.destroy();    
}

// give control back to the event loop so GC can do its work
setTimeout(() => console.log('after all', process.memoryUsage().rss), 1000);
```

When I execute it on my server with Ubuntu 20.04.3 installed on it result looks like this:
![image](https://user-images.githubusercontent.com/74194931/144863204-425cc071-677f-4f2e-845e-b0ae836bd6ab.png)

RSS before 45936640 (~43.8 MB)
RSS after 137310208 (~130.9 MB)

As you can see in the code I destroy the stages, so either I'm doing something wrong or there's a memory leak somewhere.

Also, looks like it doesn't occur on Windows 10, at least the memory usage difference is not so big. This is what I get on my local machine:
![image](https://user-images.githubusercontent.com/74194931/144865048-66bbf406-a705-4b65-a7e7-276a63040be1.png)

RSS before 41807872 (~39.8 MB)
RSS after 57458688 (~54.7 MB)

I would be grateful if someone advise me on this issue.

**Comment by lavrton** [comment]
I have no idea how to debug that. Probably it is related to `canvas` library. Are there any ways to check what objects are still in memory?

I know it is possible to do that in Chrome Dev tools. I guess you can check that in NodeJS process too.

**Comment by severinv42** [comment]
We decided that it's not a top priority issue for us right now, so won't we investigate it any further for now.
Besides that, from what I see you're probably right about the canvas library because it's a native module that manages memory manually and it has opened memory leak issues. The issue is also probably related to the way memory management works in UNIX systems since on Windows everything is fine. 

So it's unlikely that the problem is in the KonvaJS code. I'll close the issue.

Thank you for your attention, @lavrton.
