### ISSUE TITLE
Draw 1px line

### ISSUE THREAD

**Issue by Cyral** [konvajs/konva#125]
I'm very impressed with this library and the features it offers. I've moved most of my application over to it but I am wondering if there is a way to draw a 1px line, with no anti-aliasing (I need to create a grid of 1px lines horizontally and vertically). Using x as the `strokeWidth` makes the line about 2 pixels due to what I assume is anti-aliasing.

**Comment by lavrton** [comment]
Just move your shape by 0.5px. See http://stackoverflow.com/questions/9311428/draw-single-pixel-line-in-html5-canvas
