### ISSUE TITLE
RTL language support for toDataURL

### ISSUE THREAD

**Issue by kanaabe** [konvajs/konva#1251]
Hi, thanks for this library. It's been very useful so far! 

One area I am having trouble with is dealing with RTL languages. I'm able to get the canvas to render RTL languages with `dir="rtl"` by directly accessing the canvas element as was suggested [here](https://konvajs.org/docs/sandbox/Native_Context_Access.html#page-title). However, I need to export that canvas as well. From the docs I see: 

> Because Konva has full control over drawing and may reset your manual drawings or lost them on any export such as stage.toDataURL().

Do you have any alternate suggestions if we need to use `stage.toDataURL`? Or is the solve to support more attributes such as `dir` as first-class attributes? I'd be happy to open a PR if that's something you'd be interested in. 

Example of it affecting RTL output: 
https://codesandbox.io/s/musing-ellis-yh005?file=/src/index.js

**Comment by lavrton** [comment]
I don't have any simple solutions in mind. `node.toDataURL()` creates a temporary canvas to make an export.

As workaround you can monkey-patch `Konva.Util.createCanvasElement()` and set `dir` attribute in it.

**Comment by kanaabe** [comment]
Thanks for the response @lavrton, I wanted to follow up.

Do you have any examples of this patching with `node.toDataURL()`? I tried patching and I can see the console.logs applying the `dir="rtl"` but my output canvas from `node.toDataURL()` still applies the incorrect attribute. Do you spot anything wrong with my implementation? https://codesandbox.io/s/relaxed-rumple-hkfpw?file=/src/index.js

Ultimately I want to apply a variety of attributes including CSS styles such as filters to produce the canvas the user wants, then export it. (I tried using the Konva Filters but the performance wasn't great since we are working with large images and a slider UI). My question is, if we go with patching, would we lose control over which layer we want the attributes + styles to apply to? For example, if we had two pieces of text in English and Hebrew and patched `createCanvasElement`, the style would apply to the entire canvas instead of say, the Hebrew text layer only. Is that correct? Do you have any other suggestions on how to approach this?

**Comment by lavrton** [comment]
I don't know why `dir="rtl"` is not working. I'm not very knowledgeable about it, so I don't have any solutions for you. You may need to debug on your own.

> Ultimately I want to apply a variety of attributes including CSS styles such as filters to produce the canvas the user wants

You can do that. I don't think you should patch `Konva.Util.createCanvasElement` for that. Instead, just use external canvas elements, draw something on them (with or without filters). And then use them for `Konva.Image`.

You can use direct 2d canvas API to draw on external canvas, or convert Konva.Nodes into canvas elements.

**Comment by lavrton** [comment]
May be fixed with https://github.com/konvajs/konva/pull/1637
