### ISSUE TITLE
Width doesn't change on resize

### ISSUE THREAD

**Issue by albmon** [konvajs/konva#1252]
Hi,
When I try to resize an element (for example a Rect):
      var rect = new Konva.Rect({
        x: 160,
        y: 60,
        width: 100,
        height: 90,
        fill: 'red',
        name: 'rect',
        stroke: 'black',
        draggable: true,
      });
      layer.add(rect);

      rect.on('transform', function () {
        updateText();
        console.log('transform');
      });

      function updateText() {
        var lines = [
          'x: ' + rect.x(),
          'y: ' + rect.y(),
          'rotation: ' + rect.rotation(),
          'width: ' + rect.width(), **--> HERE THE rect.width() VALUE DOESN'T CHANGE ON RESIZE EVENT **
          'height: ' + rect.height(),
          'scaleX: ' + rect.scaleX(),
          'scaleY: ' + rect.scaleY(),
        ];
        text.text(lines.join('\n'));
      }

Any help is appreciated.
Thank You.

**Comment by lavrton** [comment]
From the docs https://konvajs.org/docs/select_and_transform/Basic_demo.html:

> Note: Transforming tool is not changing width and height properties of nodes when you resize them. Instead it changes scaleX and scaleY properties.
