### ISSUE TITLE
I am using Konva 8.3.1 and this behaviour is still there. In addition, the double-click event is also triggered when I click a shape first with the right mouse button and then quickly with the left or vice versa. I would be very happy if this would be fixed soon.

### ISSUE THREAD

**Issue by J2thearo** [konvajs/konva#1255]
I am using Konva 8.3.1 and this behaviour is still there. In addition, the double-click event is also triggered when I click a shape first with the right mouse button and then quickly with the left or vice versa. I would be very happy if this would be fixed soon.

_Originally posted by @J2thearo in https://github.com/konvajs/konva/issues/917#issuecomment-999510856_

**Comment by lavrton** [comment]
Make a small demo, please.
