### ISSUE TITLE
how to implement the feature like lineStype`s alignment in pixijs

### ISSUE THREAD

**Issue by 1d88** [konvajs/konva#1257]
Thank you for submitting an issue!

Please make sure to check current open and closed issues to see if your question has been asked or answered before.
If you have just a question (not a bug or a feature request) it is better to ask it in [Stackoverflow](http://stackoverflow.com/questions/tagged/konvajs).

If you have a bug, please, try to create a reproducible example with jsfiddle (or any similar service).
You can use [this JSBIN](https://jsbin.com/tekehizuta/1/edit?html,js,output) as a template.

**Comment by lavrton** [comment]
Konva doesn't support such API. As a workaround, you can manually control shape position and size to draw the stroke where you want. For some shapes, in may be simple. This is Pixi example for circle https://jsfiddle.net/bigtimebuddy/zcrub78v/, in Konva you can just draw circles with different radius to make the same effect.
