### ISSUE TITLE
SVG is distortion when using rect fillPatternImage with stage scale

### ISSUE THREAD

**Issue by derekjan1240** [konvajs/konva#1258]
Is there any solution to use fillPatternImage with stage scale without distortion, i'm not sure if this behavior is expected or not? 
But my temporary solution is dynamically changing svg size and fillPatternScale to offset stage scale, I don’t think this is a good way.

sandbox > https://codesandbox.io/s/recursing-fog-fvqos?file=/src/App.vue

![image](https://user-images.githubusercontent.com/24741602/147576218-abcaa572-e5c7-4e0a-93de-8f57befe9b9d.png)

**Comment by lavrton** [comment]
I am not sure it something we can fix from Konva side. I guess this is how pattern caching works for SVG.

I think your workaround is good. If you can't change svg dynamically, you can render it into canvas element with bigger size and use it:
```js
const canvas = document.createElement('canvas');
canvas.width = 50;
canvas.height = 50;
canvas.getContext('2d').drawImage(image1, 0, 0, 50, 50);
this.image = canvas;
```
