### ISSUE TITLE
`add()` should not ignore to add a Shape, if this shape's parent indicate to the target container

### ISSUE THREAD

**Issue by iahu** [konvajs/konva#1259]
[this CodeSandbox](https://codesandbox.io/s/brave-bhaskara-jz4dz?file=/src/composite.ts:486-504) demos this issue

**Comment by lavrton** [comment]
I don't understand the problem.

```js
r2.parent = layer
```

You shouldn't do that in Konva.

**Comment by iahu** [comment]
It is a simplified demo, to directly reproduction the issue.

**Comment by lavrton** [comment]
As I mentioned, I think the code in the example is not correct. You shouldn't mutate `parent` property manually.

**Comment by iahu** [comment]
not manually, just a direct code to example the problem.

**Comment by lavrton** [comment]
> say that Konva sometimes keep node’s parent even if it not still belong to a container

I need a demo of that. The example above doesn't demonstrate anything to me because it has code of incorrect Konva usage.
