### ISSUE TITLE
Reflection Custom filter require

### ISSUE THREAD

**Issue by ganeshpatwaypi** [konvajs/konva#1263]
how can we create mirror or reflection filter in konva

see the example https://drive.google.com/file/d/19c7kKluOCJentzH_iyMGx9kigpeLX5f7/view?usp=sharing

**Comment by lavrton** [comment]
I think the simplest way is to create another shape and apply scale, skew to make a mirror effect. But I am not certain how implement "waves" effect. You can create a custom filter for that, but I don't know how the implementation may look like.

Probably blur will be enough.

<img width="220" alt="Screen Shot 2022-01-03 at 12 18 14" src="https://user-images.githubusercontent.com/1443320/147959871-c55d8773-c895-48ff-a401-2ef4324f3566.png">


```js
const text = new Konva.Text({
  x: 20,
  y: 20,
  text: 'Konva',
  shadowBlur: 10,
  fontSize: 50,
  fill: 'white',
  stroke: 'red',
  strokeWidth: 5,
  fillAfterStrokeEnabled: true
});
layer.add(text);

const mirror = text.clone({
  y: text.y() + text.height(),
  offsetY: text.height(),
  scaleY: -1,
  skewX: 1,
  filters: [Konva.Filters.Blur],
  blurRadius: 10
});
mirror.cache();
layer.add(mirror);
```


https://jsbin.com/qifoqubiku/1/edit?html,js,output

**Comment by ganeshpatwaypi** [comment]
@lavrton Thanks  

Can we skip mirror shape from transformer selection in Konva.Group

**Comment by lavrton** [comment]
Well, you are implementing selection by yourself. So it is up to you to control what is selectable and what is not.
