### ISSUE TITLE
drawImage doesn't work

### ISSUE THREAD

**Issue by yinguangyao** [konvajs/konva#1264]
When I use drawImage for the layer, it will not take effect.

Examples are as follows:

https://codesandbox.io/s/unruffled-rosalind-vnytp?file=/src/index.js

**Comment by lavrton** [comment]
It is not a recommended way to use Konva API. In Konva you have shapes and groups. So, you should add all drawings with them. You can add `canvas` element into layer with `Konva.Image` shape.

You see nothing on the page, because Konva automatically cleared the canvas.
If you don't want that, you can set `Konva.autoDrawEnabled = false`. But again, Konva will clear all previous drawings as soon as you call `layer.draw()` or `stage.draw()`. If you don't want that, you can set `layer.clearBeforeDraw(false);`

**Comment by yinguangyao** [comment]
@lavrton I want to use offscreen rendering for the layer, so I have to use drawImage.
autoDrawEnabled will prevent all layers from being updated. Is it possible to prevent only one layer from being updated?

**Comment by lavrton** [comment]
Make offscreen rendering into external canvas element. Then instead of direct rendering into layer context, just render that canvas as `Konva.Image`.

**Comment by yinguangyao** [comment]
I am optimizing the performance when scrolling, and reduce the loss caused by konva text drawing through offscreen rendering

**Comment by lavrton** [comment]
> Will only one image be rendered at the end?

You can create as many images, as you want.

> This way the event system will fail

What event system? Why does it fail?

**Comment by yinguangyao** [comment]
Do you mean that I create an additional image shape for offscreen rendering and set other shapes to be invisible？

**Comment by lavrton** [comment]
Sorry, I don't understand what are you trying to do.

Why do you need to set other shapes invisible?

**Comment by yinguangyao** [comment]
I am optimizing the performance when scrolling, and reduce the loss caused by konva text drawing through offscreen rendering.

If I draw the offscreen canvas into the image,  I need to prevent the drawing of other shapes in the layer.

I don’t know if this performance loss will increase.

**Comment by lavrton** [comment]
Did you try to just cache a text shape?

> If I draw the offscreen canvas into the image, I need to prevent the drawing of other shapes in the layer.

Why? What is the structure of your scene?

**Comment by yinguangyao** [comment]
I have considered caching the text. There is a lot of text on the page, and it takes a lot of time to calculate the width and height every time I scroll. 
I thought of two methods. When the page is loaded, all the text width and height are calculated in advance and cached, so that there is no need to recalculate when scrolling, but drawing will still take time and memory will increase.
Another is to use offscreen rendering.

**Comment by yinguangyao** [comment]
Cached text shapes will increase the memory overhead. We are an online Excel product. In a scenario of about 100,000 cells, there will be a lot of text.

**Comment by yinguangyao** [comment]
There is a lot of the same text in the page, if I don't use text.cache for the text shape and just want to cache this text, is there any way? text.clone causes _setTextData to execute, but _setTextData takes too much time.

**Comment by lavrton** [comment]
> We are an online Excel product. In a scenario of about 100,000 cells, there will be a lot of text.

Not all of them are visible in the screen, right? Do you don't need to think about most of them. Just work with visible elements.

**Comment by yinguangyao** [comment]
I don't understand what you mean by using Konva.Image instead of drawImage.

**Comment by lavrton** [comment]
You want to use `drawImage`. Use it where? On layer canvas directly? If so, it is not recommended. You should change canvas of the layer directly. Use shapes for that.
Create an external canvas element. Do anything you want with it. Use `drawImage`.
THEN display that canvas on layer via `Konva.Image` shape.

**Comment by yinguangyao** [comment]
Does konva have best practices for offscreen rendering?

**Comment by yinguangyao** [comment]
I mean is this image drawn in a new Layer? Or put it in the original Layer?
If it is placed in a new Layer, will the Shape in the original Layer not be rendered?
If it is placed in the original Layer, how to deal with other Shapes in this Layer? set visible to false?

**Comment by lavrton** [comment]
> Does konva have best practices for offscreen rendering?

I was not doing anything serious with it. Just prototyped this https://konvajs.org/docs/sandbox/Web_Worker.html

> I mean is this image drawn in a new Layer? Or put it in the original Layer?
> If it is placed in a new Layer, will the Shape in the original Layer not be rendered?
> If it is placed in the original Layer, how to deal with other Shapes in this Layer? set visible to false?

I am loosing context on what exactly you want to render in offscren. Just manual drawing on canvas? Konva shape? Groups of shapes? Full layer?

Make a quick and small demo. Show what you tried. Tell what is not working, etc...

**Comment by yinguangyao** [comment]
Is it possible to use the cache method for Group?

**Comment by lavrton** [comment]
Yes
