### ISSUE TITLE
React Konva freezes web app

### ISSUE THREAD

**Issue by Chrischuck** [konvajs/konva#1271]
Hello, I'm having a fairly  similar issue to #827 where react-konva just freezes up the browser. I assume it has something to do w/ webpack but I'm not really sure what it is. 

Originally we were attempting to wrap react-konva in an internal node module for our web application. Using the module in storybook works, but when using it in a real life app, it freezes. After getting this freezing issue, I tried to add react-konva directly to our app. Even after trying to mount a very simple example, it freezes:

```
 <Stage width={100} height={100}>
    <Layer>
      <Text text="Try click on rect" />
    </Layer>
  </Stage>
```

No errors in console, just the instant the component mounts, the cpu usage shoots to 100%. I've tried in both Brave and Chrome, but no errors  in each.

react-konva version: `17.0.2-5`
webpack version: `5.50.0`
react version: `17.0.2`

Some webpack plugins/loaders we're using:

- script-loader
- webpack-dev-server
- webpack-merge
- html-webpack-plugin
- webpack.ProvidePlugin
- webpack.DllReferencePlugin
- webpack.DefinePlugin
- AddAssetHtmlPlugin
- babel-loader
- webpack.HotModuleReplacementPlugin
- CaseSensitivePathsPlugin
- ExtractTextPlugin
- webpack.ContextReplacementPlugin
- webpack.ProvidePlugin

I know it's kind of a long shot and I unfortunately don't have much info to give you, but you have any ideas of what might conflict w/ react-konva, that would be great.

Thanks for the help, it's much appreciated!

**Comment by EasyBreezy97** [comment]
Hi, I have a similar problem. Did you fix it?
