### ISSUE TITLE
Feature Request: RoughJS built in support?

### ISSUE THREAD

**Issue by EddieJn** [konvajs/konva#1272]
with the full abilities such as transform, cache, Serialization etc.

**Comment by lavrton** [comment]
I don't have any plans to add it directly into KonvaJS.

You can make your own implementation using custom shapes: https://konvajs.org/docs/vue/Custom_Shape.html#page-title
Or you can monkey-patch `sceneFunc` of every built-in Konva shape to use RoughJS library.

It should be hard. In scene function, you just need to call RoughJS API to make drawing on the canvas.
