### ISSUE TITLE
Konva captureStream

### ISSUE THREAD

**Issue by mikron123** [konvajs/konva#1273]
Hi, I would like to understand how do I get the stream of the canvas so I can record it?

Is there a Konva.captureStream(30) method like the one a Canvas has?

If not, how do I get the Canvas of Konva to call captureStream?

Thanks

**Comment by lavrton** [comment]
```js
const canvas = layer.getNativeCanvasElement();

const stream = canvas.captureStream(30);
```

If you have several layers, you may try to manually draw them into an external canvas element and capture its stream.
