### ISSUE TITLE
Firefox: shape.fillPatternRepeat('repeat-x') not working

### ISSUE THREAD

**Issue by weareindi** [konvajs/konva#1276]
`shape.fillPatternRepeat('repeat-x')` and `shape.fillPatternRepeat('repeat-y')` broken in Firefox.

The output is the same as if `shape.fillPatternRepeat('repeat')` has been entered.

Pen: https://codepen.io/weareindi/pen/PoOoKqW

**Comment by richardjonlewis** [comment]
I had a similar issue. It is not a Konva issue it is a bug in firefox.  See w3schools's createPattern direct canvas example here which gives the same effect: [https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_canvas_createpattern](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_canvas_createpattern)

'no-repeat' also causes the last pixels to be copied down and across causing very odd background.

I created a separate Konva.Rect of img.height to achieve the same effect OR used fillPatternScaleX and Y to scale Image to Rect.height.

**Comment by richardjonlewis** [comment]
Here is the bug represented on Moz BugZilla that I found when I was originally tackling this issue.  [https://bugzilla.mozilla.org/show_bug.cgi?id=468358](https://bugzilla.mozilla.org/show_bug.cgi?id=468358). It's still outstanding and has been like that for many years. Comments suggest it was put in the not a priority / take too much time pile.

**Comment by weareindi** [comment]
Ah brilliant. Thanks for the info @richardjonlewis .

I changed my code to cater for the issue by setting the height of a container to the height of the tile I wanted to spread horizontally.

I'll close this as it's not a Konva issue.
