### ISSUE TITLE
Some lose/blurry in resolution on saving image

### ISSUE THREAD

**Issue by AhmeeedMostafa** [konvajs/konva#1277]
Hello,
Thanks for such a great plugin!

I have some issue that's shown on saving the image which is the resolution of the image is a little bit decreased (loses some details or making it a bit blurry)

On the example below I have marked some area that might be a bit clear of the issue (you would find some details are abit noisy/blurry),

-Original Image (Open it in new tab to see difference clearly)
![original-image](https://user-images.githubusercontent.com/22754338/151412348-a6ec0038-aecc-42ee-929f-72f0f2183012.jpg)

- Saved image from Konva  (Open it in new tab to see difference clearly)
![downloaded-image](https://user-images.githubusercontent.com/22754338/151412378-085851d1-7398-4516-8c42-ddcf0bfeeefb.jpeg)

[Codesandbox demo](https://codesandbox.io/embed/react-konva-image-demo-forked-4f2vh?fontsize=14&hidenavigation=1&theme=dark)  (just click over the image to download it).

Waiting for the feedback!

**Comment by lavrton** [comment]
Can you try the last Konva version?

I do not see many differences with it. And I am not sure if there is anything from Konva side.
