### ISSUE TITLE
How can I get the x, y, width, height of the group in the case of rotation

### ISSUE THREAD

**Issue by Linkontoask** [konvajs/konva#1278]
If I use `rect`, I can easily get `x/y/width/height` properties, but `group` can't get it at all, I can only get it through `getClientRect`, but after rotation, `width/ height` These are the size of the class in the `x/y` axis.
I hope:
``` javascript
const group = new Konva.Group()
const rect = new Konva.Rect()
group.rotation(30)
rect.rotation(30)
group.x() === rect.x() // true
````

**Comment by Linkontoask** [comment]
![image](https://user-images.githubusercontent.com/26475695/151524128-de2ef09f-f03f-4d31-b2b7-4191e59069ea.png)

As shown in the figure, if it is rect, then I can use
``` javascript
const [x1, y1, width, height] = [
       node.x(),
       node.y(),
       node.width() * node.scaleX(),
       node.height() * node.scaleY()
]
````
The above formula does not work with `group`

**Comment by lavrton** [comment]
Can you clarify why do you need it and what you are trying to do?

Every Konva node has its own x, y, rotation attributes. `x` and `y` attributes are relative.
