### ISSUE TITLE
How to apply konva filters on Video / Animation part

### ISSUE THREAD

**Issue by khanzzirfan** [konvajs/konva#1279]
Hi, Thank you for such detail examples and documentation on Konvajs. 

The  filters for Images works pefectly fine on the Image.  But I'm trying to apply the same Konva filters to Video. 
I have an example code sandbox if you want look at my implementation. but shortcode is here.  
Please let me know what I"m doing wrong here and how could I improve it. 

```
<Image
          x={0}
          y={0}
          width={width}
          height={height}
          image={video}  // video reference
          stroke="red"
          filters={[Konva.Filters.Blur]}
          blurRadius={10}
          ref={this.image} // React.createRef()
        />
        
  ```
  
  Codesandbox link
  https://codesandbox.io/s/react-konva-video-component-forked-x62rh?file=/src/VideoComponent.js

**Comment by lavrton** [comment]
It will not work that way. Applying Konva filters is expensive operation and takes time. It will not work in real time for every video frame.

As a solution, you should render video into an external canvas and apply filters on that canvas. There are several ways to do that. You can try to use https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/filter or do some webgl magic. 

When you render video frame into that canvas you can use the canvas as `image` attribute for `Konva.Image` to display it in the stage.
