### ISSUE TITLE
Centered text is left justified when it exceeds the width of the bounding -box

### ISSUE THREAD

**Issue by ddcovery** [konvajs/konva#128]
Hi,

I'm creating a Text with property 

> align: "center",
> wrap: "none"

When text content width exceeds the bounding box width, text align is internally treated as "left".  In my opinion, this behaviour is contradictory and breaks with the expected one:  alignmen must honor the specified one.

**Comment by lavrton** [comment]
It is the same as css works: https://jsfiddle.net/6rqhmwsx/

**Comment by ddcovery** [comment]
Ok thankyou.
