### ISSUE TITLE
Path scales incorrectly? 

### ISSUE THREAD

**Issue by nabati** [konvajs/konva#1280]
I'm not sure entirely what the issue is here but seems like when you use `Konva.Path` together with scaling, the size of the scaled shape ends up incorrect. 

The path itself is drawn correctly, but the group now has a padding on the lefthand side. 

![image](https://user-images.githubusercontent.com/1499050/152361169-7999f6c7-7405-437a-af8e-622c68a61f40.png)

Repro: 
https://codesandbox.io/s/scaling-todataurl-h9f8r?file=/src/index.js

Have I missed something?

**Comment by nabati** [comment]
Updated the example, 
![image](https://user-images.githubusercontent.com/1499050/152374074-e7de91d1-1847-49a5-b82c-61cd7953d157.png)

**Comment by lavrton** [comment]
Closing, as I am not sure what is the issue about. Please add more details if it is still relevant.
