### ISSUE TITLE
How to programatically rotate a Group around its center like Transformer does?

### ISSUE THREAD

**Issue by wagoid** [konvajs/konva#1281]
Hi @lavrton, thanks for the amazing library!

I have an use case that I need to rotate a group of elements, so I'm using `Group`.

I also need to programatically rotate it. But when I call either `group.rotation` or `group.rotate` it's not rotated around its center.  I also tried using `rotateAroundCenter` logic from [docs](https://konvajs.org/docs/posts/Position_vs_Offset.html) but no luck.

[Here](https://codesandbox.io/s/weathered-thunder-7ohvt) is an example showing the issue.

How can this be achieved?

**Comment by lavrton** [comment]
The group is rotating around its origin. By default, it is its {x,y} point. In your example, it is {0,0} on canvas. 
The simple way to solve the issue, is to put a rectangle into a group "around" its center. 

You just need to learn how relative position are organized. 

```js
<Group
  draggable
  name="test-group"
  ref={(group) => {
    this.group = group;
  }}
  x={150}
  y={150}
>
  <ColoredRect x={-75} y={-75} />
  <ColoredRect x={-25} y={-25} />
</Group>
```

**Comment by wagoid** [comment]
Ah I see! That makes more sense now. Thanks for the help ♥️
