### ISSUE TITLE
One gradient over multiple elements

### ISSUE THREAD

**Issue by lkarcol** [konvajs/konva#1282]
Hi @lavrton,

is possible make something like this ? I have rects on layer and i need one gradient over all elements.

![qr](https://user-images.githubusercontent.com/16167609/152429030-d480d8a6-2634-4956-84d4-7d9b2c09da18.png)

**Comment by lavrton** [comment]
Yes. There are many ways.

I think you can:

1. Create an external canvas element. Draw gradient into it with 2d canvas API
2. change `globalCompositionOperation` to `destination-in` and draw your qr code on top of that canvas. https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation
3. Use resulted canvas for `Konva.Image`

**Comment by pharaok** [comment]
Why is the first solution to directly use what the library was made to abstract?

I'm currently just putting an individual gradient on each element and subtracting the element's position from the gradient start and end points, but I thought there would've been a better way to do this.
