### ISSUE TITLE
image quality 

### ISSUE THREAD

**Issue by larbikhounti** [konvajs/konva#1283]
hello I implemented konva
everything is working super fine

but with images became really low
quality when I resize it
using the code in  docs

is there a way to not effecting image quality on resize the image

**Comment by nabati** [comment]
Do you have a reproducible example?

**Comment by larbikhounti** [comment]
@nabati  
sorry man I switched to some other solutions 

for answering your question : 
just add any image even high quality and scale it will lose quality.

**Comment by deadcoder0904** [comment]
@larbikhounti you have options to use `quality` & `pixelRatio` in **konva** so it comes out high-quality https://konvajs.org/docs/data_and_serialization/High-Quality-Export.html
