### ISSUE TITLE
caching not preserved on cloning

### ISSUE THREAD

**Issue by nabati** [konvajs/konva#1284]
If you clone a group with cached elements, one has to call cache again for the same elements. 

I don't think this was expected on my part, so if this behaviour makes sense to keep, I think we should document it somewhere.

https://codesandbox.io/s/globalcompositeoperation-fiz9f?file=/src/index.js

![image](https://user-images.githubusercontent.com/1499050/153589761-a5ee479c-aa84-4d13-b996-31d43d47d31f.png)

**Comment by lavrton** [comment]
Currently, this is intentional. I am happy to apply any related pull requests for documentation.
