### ISSUE TITLE
Use with frame buffer device in node

### ISSUE THREAD

**Issue by natcl** [konvajs/konva#1287]
Hello,
I'd like to use Konva and output as a frame device as described here:
https://github.com/Automattic/node-canvas/wiki/Using-with-framebuffer-devices

How would I do this from Konva in Node ?

Thanks

**Comment by lavrton** [comment]
```
const buff = canvas.toBuffer("raw");

**Comment by natcl** [comment]
Thanks !
And is it too late at this point to change the pixel format ?
This line seems important to make it compatible with the frame buffer device:
```
const ctx = canvas.getContext("2d", {pixelFormat: "RGB16_565"});	// important: RGB16_565
````

**Comment by lavrton** [comment]
Too late. And there is not API to change `getContext` call in Konva. As workaround:

1. Create konva stage/layer and do all drawings
2. create external canvas element
3. get its context with `getContext()` method. Pass all arguments you need
4. manually draw konva layer into external canvas
5. use bufffer of external canvas

**Comment by natcl** [comment]
Thanks ! I will try that workaround

**Comment by natcl** [comment]
> 4\. manually draw konva layer into external canvas

I'm struggling with this step, could you post an example ?
Thanks !

**Comment by lavrton** [comment]
```js
const canvas = document.createElement('canvas');
canvas.getContext('2d').drawImage(layer.getNativeCanvasElement(), 0, 0);
```

just check correct sizes. canvas element of the layer may be bigger because of pixel ratio.

**Comment by natcl** [comment]
Thanks that seems to work !
one last question: if I want to draw the stage to the canvas how would I do ?
I tried stage.getLayer() but it doesn't seem to work.

**Comment by lavrton** [comment]
```js
const canvas = stage.toCanvas()
```

**Comment by natcl** [comment]
Thanks !! Success
Konva on a tiny screen
![image](https://user-images.githubusercontent.com/77556/167191027-095834de-832b-4301-baf4-d3251ec4a134.jpeg)

**Comment by lavrton** [comment]
Oh, wow.
