### ISSUE TITLE
Hitpoint coordinates when zooming 

### ISSUE THREAD

**Issue by sergiulucaci** [konvajs/konva#1288]
Hello,

after zooming on a page where Konvajs elements are present, hitpoints doesn't correspond to where the shape is. 

While the canvas zooms good, it looks like the hitpoint coordinates don't.

See this demo: https://jsbin.com/puzuvokuhe/2/edit?html,js,output

**Comment by lavrton** [comment]
Do not scale with CSS. Use the built-in scale attribute on stage instead.

Scaling with CSS is breaking hit detector.
