### ISSUE TITLE
Transformer added to a layer getting rendered on nodes of another layer

### ISSUE THREAD

**Issue by Dhwanil-Shah** [konvajs/konva#1293]
Hey,

I have multiple layers, each with a separate node. The transformer is added only to Layer 1 and yet, the objects of the other layer get wrapped in it when I add the node to it. The behavior is more or less what I want i.e. only a single transformer is active on a node at a time. If I click on a node, then any other active node should get disabled. But the way it's working by just adding to one layer is kind of bugging me. Is this how it's intended to be, transformer getting access to nodes of other layers where it wasn't added?

This is another approach I was trying out along with the other issue which I opened regarding events not triggering as expected.
https://github.com/konvajs/konva/issues/1292

The thing I am trying to do is the same but neither of the approaches are working.

https://codepen.io/dhwanil-shah/pen/eYebNZW

Thanks in advance.

**Comment by lavrton** [comment]
So, what is your question or issue?

> Is this how it's intended to be, transformer getting access to nodes of other layers where it wasn't added?

Transformer can adapt to a node, placed on another layer.

**Comment by Dhwanil-Shah** [comment]
I am wondering whether it's the best way to have a layer with just the transformer as a singleton and then based on the click events of a node, add that node to the transformer. Or should I add the transformer to the layer where the node is added as well? Its a bit odd because I have multiple layers, each with its own node, so what's the best way to determine where the transformer should be added.

**Comment by lavrton** [comment]
Well, it is up to you. Do what is most comfortable for you. I prefer to keep just one layer on, most of the cases. Use several layers only when you want to fix performance issues.

**Comment by Dhwanil-Shah** [comment]
Understood, just out of curiosity, what kind of performance issues can layers solve?

**Comment by lavrton** [comment]
https://konvajs.org/docs/performance/Layer_Management.html

**Comment by Dhwanil-Shah** [comment]
Got it, thanks for the help and prompt replies. Appreciate it!
