### ISSUE TITLE
Drawing with react-konva a rectangle WHEN clicking a button

### ISSUE THREAD

**Issue by raphael10-collab** [konvajs/konva#1299]
As explained in `StackOverFlow` here: https://stackoverflow.com/questions/71401068/draw-with-react-konva-a-rectangle-when-clicking-a-button
I'm having difficulties in drawing with `react-konva` a rectangle `when` clicking a button:

This is the code: 

    import * as React from 'react'
    import Konva from 'konva'
    import { Stage, Layer, Line, Text, Rect, Group} from 'react-konva'
    import { Portal, Html } from 'react-konva-utils'

    export default function W(props) {
    
      const toggleShown = () => {
        setShown(!shown)
        console.log("shown: ", shown)
      }
    
      return (
        <Stage
          x={stagePos.x}
          y={stagePos.y}
          width={window.innerWidth}
          height={window.innerHeight}
        >
         <Layer>
            <Html>
    
              <button onClick={toggleShown}>Click</button>
              {
                shown
                &&
                <p>Hello World!!!</p>
                &&
    
                <Stage>
                  <Layer>
                      <Rect width={100} height={100} fill="white" draggable />
                  </Layer>
                </Stage>
              }
            </Html>
         </Layer>
        </Stage>
      )
    }

When clicking on the button during execution I get on the console log:

    shown:  false
    shown:  true

which is fine, but on the dark background I do not get the white rectangle.

Other info:

- node : v16.13.0
- O.S.: Ubuntu 20.04 Desktop
- "konva": "^8.3.3"
- "react": "^17.0.2"
-  "react-konva": "^17.0.2-5",
 "react-konva-utils": "^0.2.0",

What am I doing wrongly? How to make it work?

**Comment by lavrton** [comment]
I don't understand why you need to put another `Stage` inside `Html`. You already have stage. Just draw a rectangle in it.

```js
      <Layer>
        <Html>
          <button onClick={toggleShown}>Click</button>
        </Html>
        {shown && <Rect width={100} height={100} fill="white" draggable />}
     </Layer>
```

In your case, you see nothing because inner stage has no width/height. https://codesandbox.io/s/compassionate-proskuriakova-zymx22?file=/src/index.js

**Comment by raphael10-collab** [comment]
Thank you very much for your kind help.

That was the problem!
