### ISSUE TITLE
textPath does not recalculate character positions on change of fontFamily.

### ISSUE THREAD

**Issue by VanquishedWombat** [konvajs/konva#1300]
As per title, textPath does not recalculate character positions on change of fontFamily.

Here is the line of code where the issue resides. Note that there is no fontFamilyChange,konva event listed.

// update text data for certain attr changes
    this.on(
      'textChange.konva alignChange.konva letterSpacingChange.konva kerningFuncChange.konva fontSizeChange.konva',
      this._setTextData
    );

Proposed fix is:

// update text data for certain attr changes - note inclusion of fontFamilyChange .konva.
    this.on(
      'textChange.konva alignChange.konva letterSpacingChange.konva kerningFuncChange.konva fontSizeChange.konva fontFamilyChange .konva',
      this._setTextData
    ); 

Will create a pull request.

**Comment by lavrton** [comment]
Merged in PR.
