### ISSUE TITLE
Text underline is truncated when converting to canvas

### ISSUE THREAD

**Issue by Keyang** [konvajs/konva#1302]
**Expected**
The toCanvas function of Text class should return a canvas with full underline width.
**Problem**
underline of text from toCanvas is truncated

**Reproduce Steps**
Please see this codepen: https://codesandbox.io/s/konva-playground-forked-buoehg?file=/src/index.js

**Comment by lavrton** [comment]
As workaround, you can set height for exported canvas:

```js
const cvs = text.toCanvas({ pixelRatio: 2, height: text.fontSize() + 5 }); // extra 5 pixels for underline
```

**Comment by lavrton** [comment]
Closing as "wont-fix" for now. Happy to apply any Pull Requests to fix that.
