### ISSUE TITLE
How to delete canvas create by Konva?

### ISSUE THREAD

**Issue by kratosvn** [konvajs/konva#1303]
Hi guys,
I'm trying to debug on ios 15, when I create konva stage and konva layer, konva will create 4 canvas we can see it on  graphics tab from safari inspect tool. I try to use stage destroy and layer destroy but canvas still existed on safari. How i can delete canvas from konva method? thank you

![image](https://user-images.githubusercontent.com/14298385/158254876-c49b084a-5512-4cb0-9e59-76ffcbf74c06.png)

**Comment by kratosvn** [comment]
Hi @lavrton 
Could you take a look to my demo video? the canvas cant delete on safari
video: https://monosnap.com/file/qf4yd1Z4mvkIHSDrFHQkEvR59vznVo
code: https://konvajs.org/docs/sandbox/Drop_DOM_Element.html

thank you

**Comment by lavrton** [comment]
You may need to remove references. Like `stage = null` and `layer = null`.

Also, I noticed that safari may still show canvas in that tab, if even it is no longer in use.
I think you may ignore it and just track memory consumption. If it is too high, then look what object is in used.
