### ISSUE TITLE
Text.toCanvas is cropped

### ISSUE THREAD

**Issue by Keyang** [konvajs/konva#1308]
Description
the width of canvas from Text.toCanvas is smaller than it should be.
Expected
The canvas should contain the full text when no width or height is provided.
Reproduce
https://jsbin.com/faruquyagi/1/edit?js,output

**Comment by lavrton** [comment]
For now, I am not certain why it produces that. As workaround you can manually increase width:

```js
const cvs = text.toCanvas({ width: text.width() + 2 });
```

**Comment by lavrton** [comment]
Closing as I am not sure what to do from konva side.
