### ISSUE TITLE
clipFunc Path2D  Turn black

### ISSUE THREAD

**Issue by 3400442579** [konvajs/konva#1311]
ver：8.3.5

 _layer.clipFunc(function (ctx) {
      //ctx.arc(200, 200, 150, 0, Math.PI * 2, false);   **// Use this code to display normally**
     

**//Use the following code to display only the black circle**
      const path2D = new Path2D();
      path2D.arc(200, 200, 150, 0, Math.PI * 2, false);
      ctx.fill(path2D);

  });

**Comment by lavrton** [comment]
Looks like currently Konva can't support that. We need to adapt Konva API to support that. 
https://github.com/konvajs/konva/blob/master/src/Container.ts#L401 here we should be able to pass generated `Path2d` object. I am not certain how. Return from `clipFunc`? Create another attribute?

Are you interested to think about it and make a Pull Request?
