### ISSUE TITLE
Is there any chance that `sceneFunc` will support async functions? 

### ISSUE THREAD

**Issue by rndm2** [konvajs/konva#1312]
In order to draw some of elements we use external library which is async. 
Is it possible to make `sceneFunc` async-compatible?

**Comment by lavrton** [comment]
What library? What data is async?

There is no way or plans to make sceneFunc async. Just save async data into attributes of a shape, then use it in a sync way.

```js
shape.setAttr('variable', await library.getData());

// then in scene func:
shape.getAttr('variable');
```

**Comment by rndm2** [comment]
It’s private library for text rendering. 
Thanks for the hint. Will try this approach.
