### ISSUE TITLE
tween.reverse()    Onfinish is not triggered?

### ISSUE THREAD

**Issue by 3400442579** [konvajs/konva#1313]
var count=0; 
onFinish: () => {
                    count += 1;
                         if (count % 2 == 1)
                            tween.reverse();
                        else
                            tween.play(); 

                   // It only runs once?????    
//Realize repetitive animation
                }

**Comment by lavrton** [comment]
Possible it is not triggering. Do you want to make a pull request with a fix?

**Comment by lavrton** [comment]
Wait. What I just understand is that only one `onFinish` trigger is correct. Because it is on finish of tween flow.
If you want to trigger an event, when tween is reversed, you can use `onReset` event.

https://jsbin.com/dirulivafo/1/edit?html,js,output
