### ISSUE TITLE
canvas responsive for game

### ISSUE THREAD

**Issue by meghe2000** [konvajs/konva#1314]
Hi, I want to resize the canvas as shown above.

I used the default methods for this but it was not suitable.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/85949855/161116006-b1325e84-3d49-4bcf-a29d-35c5e175da4c.gif)

**Comment by lavrton** [comment]
Did you try to adopt an existing tutorial for your use case?  You may just need to track the height of the container too.

**Comment by meghe2000** [comment]
Hi, I did not find any tutorial on this.
