### ISSUE TITLE
Enable opaque canvas

### ISSUE THREAD

**Issue by kbohm** [konvajs/konva#132]
When you call `canvas.getContext("2d", { alpha: false });`, the canvas will be opaque (no shining through possible of HTML elements below). According to [an article (see headline <q>Opaque canvas</q>)](http://blogs.adobe.com/webplatform/2014/04/01/new-canvas-features/) this results in the browser drawing text with subpixel anti-aliasing (<q>ClearType</q>).

So, could this please be implemented and documented? It will result in better-looking text!

**Comment by lavrton** [comment]
I think this feature may lead unexpected behaviour, because `Konva` allow to use several `Layers` (several canvases). So all canvases under opaque one will be not visible.
