### ISSUE TITLE
Filter Blur on Image

### ISSUE THREAD

**Issue by johanjudai** [konvajs/konva#1323]
Hi,

I have a 1920x1080 scene with an iamge as background. When I try to apply a Filter Blur i get this error :  
"Konva error: Unable to apply filter. Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation"
I has something to do with the clearCache function. Do you know where's the problem ?
Thank you

**Comment by eXponenta** [comment]
this is browser specific bug, need to reproduce on raf Canvas2D and report to browser.

**Comment by lavrton** [comment]
I don't think there is much to do from Konva side. You may try to create smaller cache.

```js
node.cache({ pixelRatio: 0.5 });
```

Just make sure quality is good enough for you.

**Comment by lavrton** [comment]
Also check how much memory your app is using. Probably you need to find places to reduce it.
