### ISSUE TITLE
Drag shape on edge of stage auto scroll

### ISSUE THREAD

**Issue by ganeshpatwaypi** [konvajs/konva#1326]
Hi @lavrton  I want expected functionality please look it
https://codepen.io/GreenSock/pen/YPvdYv

**Comment by lavrton** [comment]
What did you try?

**Comment by ganeshpatwaypi** [comment]
i have tried this but its not work only when width & height increase.
https://jsbin.com/cibabupogo/edit?html,output

**Comment by ganeshpatwaypi** [comment]
@lavrton please help
