### ISSUE TITLE
Transformer Maximum Call Stack Exceeded

### ISSUE THREAD

**Issue by bhamlefty** [konvajs/konva#1327]
I am getting this error when I mouse up after transforming elements. Any idea why I am getting this range error? 

![Screen Shot 2022-04-22 at 10 57 33 AM](https://user-images.githubusercontent.com/29154044/164769350-997fd474-a8da-4de6-a268-ba0c9899325d.png)
![Screen Shot 2022-04-22 at 10 57 11 AM](https://user-images.githubusercontent.com/29154044/164769355-31e5e9e8-04e7-400a-9f69-7f140af9ca40.png)

**Comment by lavrton** [comment]
Demo?

**Comment by bhamlefty** [comment]
Repo Steps:
1. Click this to [auth token ](https://aetauto-staging.web.app/?token=c4725c240e281015aca4af90f42bd50df3d4a08a)
2. Once logged in [click this](https://aetauto-staging.web.app/creative-studio-v3).  
3. Add a background to the stage by dragging from the "backgrounds" section
4. Try and transform the image and see the console error

**Comment by lavrton** [comment]
That is a full app. I am not interested to debug it. Instead, just make a minimal demo with jsbin or codesandbox or something similar. With only code required to reproduce the bug. Nothing else.

**Comment by chbinghu** [comment]
I think I can help.  and I guess you want to draw some rects on a image, and select one rect for resizing. @bhamlefty 

There is a demo from konvajs website. https://konvajs.org/docs/select_and_transform/Basic_demo.html.
in this demo, this line of code is important to prevent Maximum Call Stack Exceeded.

![image](https://github.com/konvajs/konva/assets/5512657/38164892-88a5-4289-946c-e1c93701f403)

when click on the transformer to resize a rect,  we click on one of the rect of a transformer, and then drag.

In my situation, without the line of code in the picture, transformer.nodes contains a rect which is a child of the transformer.
and Maximum Call Stack Exceeded came out.

I add the line of code, it works well.  I hope this will help you.

it is interesting to find out the reason of this problem. and I do not think it is a bug of konva. 
when click and resize a rect, do it carefaully.
