### ISSUE TITLE
plan.children[i].setAttrs is not a function

### ISSUE THREAD

**Issue by AndrewStorci7** [konvajs/konva#1329]
Hi everyone, I've a issue with the function **setAttrs()**.<br>
I'm trying to create a function that on click of a button he check if the images on the canvas have the name "estintore" ... for those who have that name I've to change the color (or at the very least, highlight them).
<br>
Here is my script:
```
$('#vista').click(function(){
      const plan = group.toObject();
      for(let i = 0; i < plan.children.length; i++){
        console.log(plan.children[i]);
        if(plan.children[i].attrs.name == 'estintore'){
          plan.children[i].setAttrs({
            fill: 'red'
          });
        }
      }
});

```
<br>
The console give me this error:<br>

```
dettaglio-anagrafica.php?id_ana=1:391 Uncaught TypeError: plan.children[i].setAttrs is not a function
    at HTMLButtonElement.<anonymous> (dettaglio-anagrafica.php?id_ana=1:391:28)
    at HTMLButtonElement.dispatch (jquery-3.6.0.js:5430:27)
    at HTMLButtonElement.elemData.handle (jquery-3.6.0.js:5234:28)
```

If you wnat to see the full script ... here is [my repository](https://github.com/AndrewStorci7/AlfaTecnica/tree/remote).
The most recent changes are on the remote branch. The script above this is on the file [pages/dettaglio-anagrafica.php](https://github.com/AndrewStorci7/AlfaTecnica/blob/remote/pages/dettaglio-anagrafica.php).<br>
There's also the database called **alfatecnica.sql**.<br>
Thanks in advance for those who will reply.

**Comment by lavrton** [comment]
What is the purpose of this line?

```js
const plan = group.toObject();
```

**Comment by AndrewStorci7** [comment]
There isn't, I've deleted that row and now it works.<br>
