### ISSUE TITLE
Current target vs target in mouseenter and mouseleave events

### ISSUE THREAD

**Issue by js2702** [konvajs/konva#1332]
We've been having an issue with the mouseEnter/Leave events not having the expected currentTarget value.

For this simple demo I would expect currentTarget to be the star and not the layer. Is this a bug or expected behavior?
Other events work correctly.

https://codesandbox.io/s/objective-sutherland-3tj0kv

**Comment by lavrton** [comment]
When even is triggered, the current target is star. You may see layer in `currentTarget` when you log full event because Konva mutate event object when it bubbles.  Codesandbox is showing mutated data. You can log `evt.currentTarget` directly, and you will see Star.

**Comment by js2702** [comment]
Ok, thanks for the information. That's definitely a bit confusing.
