### ISSUE TITLE
Konva warning: Unable to get data URL. Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported

### ISSUE THREAD

**Issue by chiragshah-mb** [konvajs/konva#134]
Konva warning: Unable to get data URL. Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported when trying to use toDataURL on two canvas.

Trying to use on chrome

**Comment by lavrton** [comment]
I guess you have images from other domain.
Take a look: http://stackoverflow.com/questions/20424279/canvas-todataurl-securityerror

**Comment by Nikhil-devloper** [comment]
sir then what is solution for this problem ?
we get why this error happen

How to solve it ?

https://stackoverflow.com/questions/55798090/react-js-need-temporary-buffer-for-image-which-comes-from-api
