### ISSUE TITLE
Version 8.3.8 breaks node imports

### ISSUE THREAD

**Issue by js2702** [konvajs/konva#1342]
Hello, I'm the one who opened https://github.com/konvajs/react-konva/pull/663 and version 8.3.7 was working wonderfully on our Vite app + unit tests. But with the changes in 8.3.8 (the exports property in the package.json was removed) our unit tests stopped working.

Is there any reason for that change? Reverting those changes in the latest version (8.3.9) seems to fix it for us.

Happy to help if I can

**Comment by davidmartos96** [comment]
@lavrton In which bundler environment does v8.3.7 break?

**Comment by lavrton** [comment]
If I remember correctly, `parcel` was importing both CommonJS and ES versions in some cases.

**Comment by pasloc** [comment]
I have the same problem. Im using nuxt3 with vite and cannot import Konva anymore for server/api routes.

**Comment by pasloc** [comment]
I could solve the problem for me with the guide from nuxt3 about "Troubleshooting ESM Issues": https://v3.nuxtjs.org/guide/concepts/esm/#default-exports

Here is what I did:
```typescript
import { interopDefault } from 'mlly'
import Konva from 'konva'

const KonvaFix = interopDefault(Konva)

const textElement: Konva.Text = new KonvaFix.Text({...})
```

There is also a guide for Library authors to fix the problem: https://v3.nuxtjs.org/guide/concepts/esm/#library-author-guide

**Comment by lavrton** [comment]
Probably fixed in the last konva version, as it is cmj only.
