### ISSUE TITLE
How do I use konva in nestjs

### ISSUE THREAD

**Issue by proudpo** [konvajs/konva#1343]

**Comment by lavrton** [comment]
Please be specific. What did you try? What is not working?

**Comment by MRXOneX** [comment]
@lavrton Tried this tip https://github.com/konvajs/konva#4-nodejs-env but didn't work

**Comment by MRXOneX** [comment]
@lavrton
package json
![Снимок экрана от 2022-06-03 20-25-05](https://user-images.githubusercontent.com/74454444/171989648-88684b9b-2122-45bf-a267-e5dc0eddbd44.png)

error
![Снимок экрана от 2022-06-03 20-18-36](https://user-images.githubusercontent.com/74454444/171989658-4a1cc731-01f3-4548-9248-bfaad09ad4c1.png)

**Comment by lavrton** [comment]
It looks like a typescript error. Not a runtime JS error. You may pass `container: ''` to avoid this error.

**Comment by MRXOneX** [comment]
@lavrton I solved my problem. Replacing the import with
`const Konva = require('konva/cmj').default;`

**Comment by nyo** [comment]
bumping because I still have the same error, I can't get this working when importing Konva using `import Konva from "konva";`, i had to use the previous comment method as a fix.

node: v18.12.1
typescript: ^4.9.3
canvas: ^2.10.2
konva: ^8.3.14

**Comment by lavrton** [comment]
Should be fixed in konva@9.
