### ISSUE TITLE
Transformer & Stage.

### ISSUE THREAD

**Issue by zta7** [konvajs/konva#1347]
When the transformer cannot be seen by human eyes: `tr.nodes ([])`,
The visible attribute of transformer should be set to `{ visible: false }` (instead of `{x: -1000000, y: -1000000}`, which is printed when the array is empty), 
Otherwise, it will pollute the getClientRect method of the stage, or I can only manually set tr.visible (false) to ensure that the getClientRect of the stage is correct.

**Comment by lavrton** [comment]
Are you interested in making a pull request with tests and fixes?

I am not certain that it should change `visible: false`. Probably we just should ignore it in `getClientRect` calculations.

**Comment by zta7** [comment]
I'm interested in that but i just fork the code, and i think i should learn about 'mocha chai rollup parcel' first.

Maybe we can directly use `__getNodeRect` as the `getClientRect` of the transformer (because when there is no nodes, it returns `{width: 0, height: 0}` which have the same effect with`  {visible: false} `.

But I think the visible attribute is more intuitive (because the transformer is moved to a place where the screen cannot be seen. In fact, it is {visible: false}).

**Comment by lavrton** [comment]
It may be intuitive. Probably, we can overwrite `isVisible()` method. Without changing `visible` property.

Changing `visible` may add a lot of complexity when:
1. user hide transformer by setting visible = false
2. user set some nodes on transformer

Expected behavior is that transformer is still hidden.

**Comment by zta7** [comment]
Idk, it's seems `isVisible()` is used to detect if there has actual `Shape` in `Container`, and is not directly related to calculation. It seems we need to overwrite all  transformer's under `Rect` and `Shape`   `isVisible()` methods Instead of changing transformer's visible at once.
If i'm wrong and we only need to overwrite transformer's isVisible() method to skip calc in `getClientRect`, and it's will be good.

And I agree with ur worry. My idea is that users cannot manipulate the visible attribute, which depends entirely on whether the length of nodes is 0 or not.

**Comment by zta7** [comment]
Or we can skip the transformer according to its absolute identity.
