### ISSUE TITLE
How draw anchor polygon

### ISSUE THREAD

**Issue by Emily-0616** [konvajs/konva#1348]
I use <Line /> to draw polygons, but need anchors. The anchor uses <Circle />，i know closed，but how to connect using a mouse?

**Comment by lavrton** [comment]
What did you try?

**Comment by Emily-0616** [comment]
> What did you try?
use <Line /> draw polygons，The anchor uses <Circle />，but I don't know how to connect using a mouse？

**Comment by Emily-0616** [comment]
> What did you try?


use `<Line />` draw polygons ，The anchor uses `<Circle />`，But I don't know how the anchors are connected to the anchors using a mouse？

**Comment by Emily-0616** [comment]
Problem solved, but I now have another problem. `<Circle />` is used as an anchor, why does dragEnd not take effect?

**Comment by Emily-0616** [comment]
But I still have a problem, I am now drawing polygons on `<Image />`, but my technical solution makes the page very stuck.

**Comment by lavrton** [comment]
Please describe your specific issue and make a demo.
