### ISSUE TITLE
React : Konva.Rect : onpointerdown attribute not listed using typescript

### ISSUE THREAD

**Issue by berli888** [konvajs/konva#1349]
Konva v8.2.2 :
using React : Konva.Rect : onpointerdown attribute not listed using typescript

**Comment by berli888** [comment]
moreover, when I set  event.cancelBubble = true  to the event of onpointerdown, the event still bubbles up.

**Comment by lavrton** [comment]
`Konva.Rect` doesn't have such attribute. How did you use it?

Also, I can't reproduce the issue with `cancelBubble`. Works good for me: https://jsbin.com/pizadoquyu/edit?html,js,console,output
