### ISSUE TITLE
Add a removeChildren function that only removes the first level children

### ISSUE THREAD

**Issue by Viictor** [konvajs/konva#135]
I'd be great to have a function that only removes the first level children of a group, exactly like the removeChildren but without **if (child.hasChildren()) {child.removeChildren();}**

**Comment by lavrton** [comment]
@Viictor Why do you need this function? What is your use case?

**Comment by Viictor** [comment]
I'm working with a stage that has several Konva groups, that have a Konva image and a rectangle, which constitute an object, and these objects may also have as children other objects with the same strucutre.

This objects can be modified, and when they are I remove their children and redraw.
So when I draw them I follow an order according to which one has to be on top, and sometimes a child object may be on top of its parent, following this order:

1. The child removes its children and adds the new ones, then its positioned and **added to its parent**.
2. Then the parent of that child, does the same thing, which causes that when removing its children also removes its children children.

The problem then is the objects order of drawing and positioning, I can run the code again through the child objects to resolve the issue, but It would be great to be able to not remove all the object hierarchy.
