### ISSUE TITLE
the position information of Rect & Transform

### ISSUE THREAD

**Issue by heD0ng** [konvajs/konva#1351]
Here， there is a situation with the Transform attaching to the Rect. When I drag the Rect or I ratate the Transform, I want to know the position information of the four vertices of  the Rect. So, in Konvajs, there is or not existing an API that can obtain the information  I need.  Can you help me? 
Thank you .

**Comment by lavrton** [comment]
Just use math for that. transform information from node may help you.

```js

function updateCoordinates() {
  const transform = shape.getTransform();
  const tl = transform.point({ x: 0, y: 0 });
  const tr = transform.point({ x: shape.width(), y: 0 });
  const bl = transform.point({ x: 0, y: shape.height() });
  const br = transform.point({ x: shape.width(), y: shape.height() });
  const str = `
${tl.x}, ${tl.y}
${tr.x}, ${tr.y}
${bl.x}, ${bl.y}
${br.x}, ${br.y}
`;
  info.text(str);
}
```

https://jsbin.com/diwojikujo/edit?html,js,console,output
