### ISSUE TITLE
getClientRect is slow

### ISSUE THREAD

**Issue by testerez** [konvajs/konva#1352]
Hello,

In certain cases, `getClientRect` can be slow. In this example, it gets about 1.7s to calculate the rect for a group containing fairly complex paths: https://codesandbox.io/s/happy-waterfall-vhnyns?file=/src/App.js
(tested on Chrome 102 on a M1 macbook air)

Is this duration expected? Is there any chance it could be optimized?

Thanks!

**Comment by lavrton** [comment]
You have a shape with VERY long path with many points. So, it takes a long time to calculate. You can dive in into Konva internals and find ways to optimize calculations. I am uncertain if it is simple.

Probably, you can use SVG DOM API to calculate bounding box of shape. 
Presently, I can't do much from Konva side to make it faster.
