### ISSUE TITLE
What is the most efficient way of dynamically rendering Bitmap characters?

### ISSUE THREAD

**Issue by djrobby** [konvajs/konva#1353]
I have an app that renders dynamic data received over WebSockets (as an array of hex chars) onto a Canvas that is specifically designed for signage applications utilizing LED displays. One of the requirements of the application is that the fonts must maintain a 1:1 pixel-to-led mapping ratio without any anti-aliasing. I am porting a desktop application over to HTML canvas and we already have custom bitmap fonts that can help us achieve this. However, In order to do so, I need to:

1.  Parse the incoming visual data
2.  Lookup byte arrays of corresponding hex characters
3.  Render them into a group onto the canvas with the following attributes (fillColor, fillAnimation, fillAnitmationSpeed)

I have put together a very simple example using native canvas here: https://codepen.io/robbydhillon/pen/PoQvpvP. I was planning on using Konva to help add another layer of abstraction and allow for me to work with Groups. I can then dynamically add/remove character content from those groups easily. What do you suggest is the most efficient/scalable way to do this with Konva along with animating the fillColor and assigning a dynamic color change speed per set of character objects?

![SS_20220620_6](https://user-images.githubusercontent.com/22199/174676483-a51c4379-6e78-4448-8192-dfa344f2a072.jpg)

**Comment by lavrton** [comment]
You can use custom shape for that. https://konvajs.org/docs/shapes/Custom.html

For animations you can use tweens.

**Comment by djrobby** [comment]
Thanks for your prompt response! I put together a demo here: https://codepen.io/robbydhillon/pen/BaYeZWP. However, when I try to apply `node.fill()` to my shape during or after initialization, it doesn't work as expected. I can understand that it might be due to the shape being comprised of `1px` rectangles. As long as I can somehow combine them into a single custom shape, I can preload the app with an array of shapes that I can later clone/destroy passing the updated `x, y, and fill` attributes.

**Comment by lavrton** [comment]
Instead of `ctx.fillRect()` use `ctx.rect()`

**Comment by djrobby** [comment]
That did the trick but for some reason, both shapes are getting applied the same `fill` color even though I'm passing different values dynamically. I updated the same example: https://codepen.io/robbydhillon/pen/BaYeZWP

**Comment by lavrton** [comment]
You need to call `ctx.beginPath();` as in docs example https://konvajs.org/docs/shapes/Custom.html

**Comment by djrobby** [comment]
At any given point in time, I am dynamically adding/removing 20-30 bitmap nodes on every push of data via WebSockets. Some of these nodes need to alternate between 2 different fill colors at either 500 or 1000ms intervals. I am having a hard time trying to do this with the `Konva.Animation` and instead I've setup the following logic globally:
```js
// animation logic
let fastAnimateSpeed = 500
let slowAnimateSpeed = 1000
let objsToAnimateFast = []
let objsToAnimateSlow = []

const setupAnimation = () => {
  window.setTimeout(halfSecEvents, fastAnimateSpeed)
  window.setTimeout(oneSecEvents, slowAnimateSpeed)

}

const halfSecEvents = () => {
  objsToAnimateFast && objsToAnimateFast.map(o => o.fire('click'))
  window.setTimeout(halfSecEvents, fastAnimateSpeed)
}

const oneSecEvents = () => {
  objsToAnimateSlow && objsToAnimateSlow.map(o => o.fire('click'))
  window.setTimeout(oneSecEvents, slowAnimateSpeed)
}
```
I am assigning an `node.on('click', () => {})` listener to nodes that require this capability on creation and then use the above logic to fire the `clicks`. With that in mind, my question to you is whether this is an efficient method of doing so? If not, what do you suggest? Please advise. Thank you in advance!

**Comment by lavrton** [comment]
I don't understand it. Why do you need `click` event there?

You don't have to use `Konva.Animation`. You can use `setTimeout` flow too.

**Comment by djrobby** [comment]
I have all `nodes` that need to alternate their color listening to the `click` event. Then every 500 and 1000ms I am performing `node.fire('click')` event so that each node can handle its own alternating of the `fillColor` accordingly. In a way, it's like a global tick. From what I understand, `Konva.Animation` does offer a global tick but I'm just having a hard time trying to wrap my head around how I would use this tick to trigger events on arbitrary intervals. Also, the documentation lists a subset of events that the `Shape` nodes can listen to...can it be extended to listen to custom events also?
