### ISSUE TITLE
Konva Website API DOCS issue (Layer / Container)

### ISSUE THREAD

**Issue by Tyme-Bleyaert** [konvajs/konva#1358]
Not sure if this is an issue I can post here.

But on the Konva Website under API Docs I found this:

![image](https://user-images.githubusercontent.com/72735570/176189857-0158d6ce-94d3-406b-ab6e-9430aa5db5dc.png)

And it looks to me that the `@params{Object}[config.clip] set clip` should not be there?
Maybe I'm wrong, but wanted to bring this to your attention.

**Comment by lavrton** [comment]
Where do you see it?

**Comment by lavrton** [comment]
I see now. Should be fixed. Thanks for the report.
