### ISSUE TITLE
[BUG] Image cropWidth behaved unexpected way.

### ISSUE THREAD

**Issue by LuoXin-s** [konvajs/konva#1359]
For example, I have codes like this:
```javascript
var imageObj = new Image(200, 200);
imageObj.onload = function () {
  var img = new Konva.Image({
    x: 0,
    y: 0,
    image: imageObj,
    width: 200,
    height: 200,
    crop: {
    x: 0, y:0, 
    width: 200,
    height:200
    }
  });

  // add the shape to the layer
  layer.add(img);
};
imageObj.src = '/image.jpg';
```
assume image.jpg is 400 * 400, I expected the above code will show the full image in 200 * 200 since I created an imageObj with 400 * 400. But what I have got is a half image in 200 * 200.
It seems konva ignored width and height property of Image Object.

**Comment by LuoXin-s** [comment]
> Looks like Konva crop from original image size. And that is expected to me.

Why is this expected? I think the width and height property of Image have their meaning.

**Comment by lavrton** [comment]
I think that is the default browser behavior from `ctx.drawImage()` method. Konva is not adding any extra logic on top of it.
