### ISSUE TITLE
Konva.Text width cannot be less than 22.2461px？

### ISSUE THREAD

**Issue by LonelySunset** [konvajs/konva#1360]
When I create a Text object，and set the width parameter to less than 22.2461px，the stage will not display this text.
I find that all versions seem to have this problem

`const konvaText = new Konva.Text({x:100,y:100,fontSize:40,text:'hello world',width:22.246})`

**Comment by lavrton** [comment]
You have `fontSize: 40`. At some point, there are no characters, then can fit into `22px` width. So, nothing is visible.
