### ISSUE TITLE
How do you cut out a particular area?

### ISSUE THREAD

**Issue by J2thearo** [konvajs/konva#1363]
I would like to select a certain area and cut it out and reposition it. I am mainly interested in the cutting mechanism. I have also uploaded an example to illustrate this. Unfortunately, I couldn't really find anything in the Konva documentation.

Let's say I have the following sketch:
![Shapes](https://user-images.githubusercontent.com/55392372/179454290-404e1db4-3b90-498c-80ff-0c1a8fe6af8f.PNG)

I would like to cut in the following way (actually exactly the same function as in Mircosoft Paint):

![Cutout](https://user-images.githubusercontent.com/55392372/179454569-7e552f9e-6777-47da-a8d5-61764614086a.PNG)

I really hope that this is somehow possible and look forward to an answer.

**Comment by lavrton** [comment]
Konva is not designed for such use cases. I am uncertain if it will be simple to do.

Technically, you can read any part of the canvas (with `ctx.getImageData()`) and copy it into another canvas and then create `Konva.Image` instance with it.

Why do you need this? What tool are you making?

**Comment by J2thearo** [comment]
Yes, I have already researched further and thought of a similar approach. Just wanted to know if Konva has a convenient solution for this, but I'm sure I can make it work.

I am working on a collaborative drawing board. Such a feature in the application would be nice to move drawings from A to B easily and quickly. 

It's definitely not trivial but if I succeed I will post my solution, thank you!
