### ISSUE TITLE
Events don't trigger in production (Svelte + Konva)

### ISSUE THREAD

**Issue by pheianox** [konvajs/konva#1365]
I use Svelte with Konva.js on some project, but something interesting happens...

When I run it locally (dev or preview) it works fine
But when I move it to Heroku 
only always 2/10 of created shapes seems to trigger events (drag/click/...) everything else works ok

I cannot show code, because it's production spaghetti, but is there any known bugs with that?

And also is there any recommendations for using KonvaJS with Svelte?

```ts
  const rect = new Konva.Rect({
    ...
   draggable: true,
  }) 

  rect.on('dragmove', handleDragMove)
```

**Comment by lavrton** [comment]
I saw this https://svelte-konvajs.patwie.com/. But I never tried it.

Try to isolate the bug and make a small online demo.

**Comment by pheianox** [comment]
Most likely it's the error of the universe. Anyways

**Comment by kyleoliveiro** [comment]
I am having the exact same issue. Did anyone ever figure this out?
