### ISSUE TITLE
How to fill the outside area of a shape with color??

### ISSUE THREAD

**Issue by nnha19** [konvajs/konva#1366]
I want to highlight the rectangle by making everything outside of the shape dark. Is there a way to do that? What I came up with is to have another rectangle taking up the entire height and width and fill it with the dark color. But, that color is also filling the smaller shape which I want to highlight. Can you help me with this please??

https://codesandbox.io/s/react-konva-draw-polygon-forked-uhhz0c?file=/src/index.js

**Comment by lavrton** [comment]
I see that you tried to use `globalCompositeOperation`. Does it work as you want now?

**Comment by nnha19** [comment]
Yes, it's working as I want. Thanks
