### ISSUE TITLE
Throwing "Konva error: "setRotationDeg" method is deprecated" when using "rotationDeg"

### ISSUE THREAD

**Issue by fristys** [konvajs/konva#1367]
Any time I pre-set "rotationDeg" on a shape I get the following error thrown in the console:

```
Util.js:611 Konva error: "setRotationDeg" method is deprecated and will be removed soon. Use ""setRotation" instead.
```

Example ([Demo](https://codesandbox.io/s/konva-playground-forked-vg3s1c)):

```typescript
new Konva.Circle({
  x: 150,
  y: 150,
  radius: 70,
  fill: 'red',
  draggable: true,
  rotationDeg: 40
});
```

Is there a way to suppress this error or at least fix it?

**Comment by lavrton** [comment]
Just use `rotation` instead of `rotationDeg`.
