### ISSUE TITLE
Cache when pixel density is less than 1

### ISSUE THREAD

**Issue by falahati** [konvajs/konva#1373]
When pixel density is below 1, and the size of a node results in less than 1 when divided by the pixel density, the whole drawing process fails with the following error:

```
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
```

The source of the problem is the discrepancy between these two lines of code:
https://github.com/konvajs/konva/blob/e88ed2c28cd162ece612c038d0e2aff474846fe9/src/Node.ts#L331
https://github.com/konvajs/konva/blob/e88ed2c28cd162ece612c038d0e2aff474846fe9/src/Node.ts#L526

As you can see, when adding a node to the cache, the library correctly tries to abort the process when the size of the node is equal to `0`, however, the check here is incomplete as it does not considers the effect of the pixel density on the width and height, something that is required on the second call to draw the cached node. It also does not take into account the rounding issue (`drawImage` rounds the value) and checks for zero only. I also don't know about the effect of the previous `ceil` call on the whole process.

This will result in the second call failing when the device's pixel density is low. In my case, it happened when I zoomed out via the browser's zone functionality. The same piece of code works flawlessly on multiple devices and resolutions so for now at least, this seems to be limited to browser zoom's functionality. Altho since this can happen to users without any explicit action from the developer, it would suggest that this issue should be regarded as a bug need fixing on the library level.

**Related:**
https://github.com/konvajs/konva/issues/1106
https://github.com/konvajs/konva/pull/1107
https://github.com/konvajs/konva/issues/392

**Workaround:**
Passing `{pixelRatio: 1}` to the `cache()` call would solve this. I also expect the recently added hit canvas pixel ratio option to fix this as well but I have not tested this myself.

**Comment by sayers** [comment]
I had this issue for IOS devices but not on anything else.
Adding {pixelRatio: 1} got around this issue.
