### ISSUE TITLE
mouseleave event triggered on Rect after dragging quickly

### ISSUE THREAD

**Issue by meteohr** [konvajs/konva#1374]
Hi there.

If I drag a Rect very shortly, almost all the time the mouseleave and mouseout events are triggered on the rect, even though technically the cursor is not leaving the Rect.

Reproducable example (You have to drag very short amount of time, <1 second): https://jsbin.com/kexanafupi/1/edit?html,js,output

This seems to be introduced with 7.1.5, as it doesn't happen with version 7.1.4 and lower.

Thanks for your help

**Comment by lavrton** [comment]
It will be very helpful if someone can reproduce that bug in a test environment, like here: https://github.com/konvajs/konva/blob/master/test/unit/DragAndDropEvents-test.ts#L198

**Comment by meteohr** [comment]
Ok, I tried writing a naive unit test:

```
it('mouseleave should not occur after drag and drop', function (done) {
    var stage = addStage();
    var layer = new Konva.Layer();
    var circle = new Konva.Circle({
      x: 40,
      y: 40,
      radius: 20,
      strokeWidth: 4,
      fill: 'green',
      stroke: 'black',
      draggable: true,
    });
    layer.add(circle);
    stage.add(layer);
    var mouseleave = false;
    var dragend = false;
    circle.on('mouseleave', function () {
      mouseleave = true;
    });
    circle.on('dragend', function () {
      dragend = true;
    });
    simulateMouseDown(stage, {
      x: 40,
      y: 40,
    });
    setTimeout(function () {
      simulateMouseMove(stage, {
        x: 100,
        y: 100,
      });
      simulateMouseUp(stage, {
        x: 100,
        y: 100,
      });
      assert(!mouseleave, 'mouseleave event should not have been fired');
      assert(dragend, 'dragend event should have been fired');
      done();
    }, 20);
  });
```

Unfortunately, this test always succeeds. So I did some debugging and found this:
https://github.com/konvajs/konva/blob/master/src/Stage.ts#L597 here in the `_pointermove` method the `shape` variable is sometimes `null`, thus `differentTarget` is `true` and it executes `_fireAndBubble` with `events.pointerleave` [here](https://github.com/konvajs/konva/blob/master/src/Stage.ts#L606).
For me it seems like the `shape` being `null` could be a performance issue / race condition.

I'm not 100% sure if this is the root cause of the problem and I only have very little knowledge of konvajs, but this is what I was able to find. Maybe you have another idea, especially how to write a test for this problem?

Thanks for your help!

**Comment by meteohr** [comment]
Thank you @lavrton for fixing this !
