### ISSUE TITLE
Does not save the background color of the stage when exporting as an image

### ISSUE THREAD

**Issue by rlidev** [konvajs/konva#1376]
Hello, how can I export the background color added to the stage when I save the canvas as an image?

When viewing if the background color is seen but when clicking save as an image the background is transparent.

The following code is using a colorpicker I change the background color, and visually the color is seen and it works. But when saving as image you don't see the color.

` 
 $("#colorpicker_background").spectrum({
        
        type: "color",
        showPaletteOnly: true,
        hideAfterPaletteSelect: true,
        showAlpha: false,
        showButtons: false,
        allowEmpty: false,
        
        change: function(color) {
            //stage.container().style.backgroundColor = color.toHexString();
            stage.getContainer().style.backgroundColor = color.toHexString();
            layer.draw();
        },
        move: function(color) {
            //stage.container().style.backgroundColor = color.toHexString();
            stage.getContainer().style.backgroundColor = color.toHexString();
            layer.draw();
        },
    });
`
[image example](https://imgur.com/a/uWeZJy0)

Thanks guys

**Comment by lavrton** [comment]
CSS styles are not visible in export. Only canvas content is exported. If you need a background, just a simple rectangle on the bottom of your scene and set its fill color.
