### ISSUE TITLE
Update Tag position after changing "pointerDirection"

### ISSUE THREAD

**Issue by SemiZhang** [konvajs/konva#1380]
Currently, when the Tag is assigned a `pointerDirection` attribute, the position of the Tag is automatically adjusted with the `pointerWidth` and `pointerHeight`, with the end of the pointer pointing to the Center position, also, when the `pointerDirection` is 'Down', the Tag will be displayed above the Center and vice versa.
However, this automatic repositioning behavior only works when creating a `'new Konva.Tag'`. Changing the `pointerDirection` of an existing Tag will change the position of the pointer, but not the entire Tag, causing the pointer to point to the wrong position.

For exemple,
Normal behavior : Creating with `pointerDirection: 'Down', pointerWidth: 10, pointerHeight: 10`
![with direction](https://user-images.githubusercontent.com/26916265/182866832-ea1c30bb-7643-4ca5-b507-e64f52186810.png)

Change `pointerDirection` to 'Up'
![image](https://user-images.githubusercontent.com/26916265/182867074-d561dd48-f1ac-4998-b1cf-6c044096b920.png)

Change `pointerHeight` to 50
![image](https://user-images.githubusercontent.com/26916265/182868024-fb2d73cc-77a5-49f2-b0ad-cbc1296d1283.png)

Or create the Tag without 'pointerDirection' and add it afterwards.
![no direction](https://user-images.githubusercontent.com/26916265/182867289-2d0cf9eb-6ccd-443f-abfa-297133636915.png)

It is hoped that the Tag's position will automatically adjust after the `pointerDirection, Width and Height` are changed so that **the pointer always points to the same position**.

**Comment by lavrton** [comment]
Fixed with https://github.com/konvajs/konva/commit/e06d3b85b9086969cf4d1a6f64af5e0c07ca5edc
