### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event

### ISSUE THREAD

**Issue by geniot** [konvajs/konva#1382]
I'm getting a lot of warnings like this in Chrome. 
Chrome thinks there's a better way to attach event listeners (Stage.js):
```
_bindContentEvents() {
        if (!Konva.isBrowser) {
            return;
        }
        EVENTS.forEach(([event, methodName]) => {
            this.content.addEventListener(event, (evt) => {
                this[methodName](evt);
            });
        });
    }
```
I'm not sure I should pay any attention to this though.

**Comment by suterma** [comment]
This seems to be closely related to https://github.com/konvajs/konva/issues/260

**Comment by lavrton** [comment]
Who can make a Pull Request to fix that? Just need to add { passive: false} in stage listener.
