### ISSUE TITLE
Transformer clientRect always returns 0 size

### ISSUE THREAD

**Issue by cgrabmann** [konvajs/konva#1387]
Hi @lavrton 

In a resent commit for Release 8.3.10 the client-rect calculation for the Transformer was changed. See here: https://github.com/konvajs/konva/commit/ab5c93e6acf77d9ca53981e811696d3858e47582

There was also a test-case with the name `detached transformer should not affect client rect` added.

I do agree that a detached transformer should not affect the client rect, but if it is attached I do disagree.

**My use-case:**    
I have to position a additional element relative to the transformer, under the transformer to be precise. This element contains some buttons that the user can interact with.    
Previous to the change I could ask the transformer for its position and its size and place the other element accordingly. The size would also take all the active anchors into account, which is especially useful for the rotation anchor. Therefore even if the transformer was rotated in a way that the rotation anchor is at the bottom, I would still be able to position the element even beneath that.    
After the change this is no longer possible, since the transformer client rect is always `{ x: 0, y: 0, width: 0, height: 0 }`. If I would get the client rect of the transformers target, I would not be able to take the rotation anchor into account when placing the element.

I would propose to change the implementation so that the transformer has a client rect if it is detached, just like the test name and its implementation suggests. But also use the normal client rect implementation of Group (like it was prior the change), if the transformer is attached. So something like this:

```typescript
getClientRect() {
    if (this.nodes().length > 0) {
        return super.getClientRect();
    } else {
        // if we are detached return zero size
        // so it will be skipped in calculations
        return { x: 0, y: 0, width: 0, height: 0 };
    }
}
```

What do you think about it? Was the initial change meant to always return no size at all or was it an oversight?

If you wish I can also provide a PR for it with a test-case.

**Comment by lavrton** [comment]
That make senses. It will be good to have a Pull Request for that.

Can you make a test for your use case?

**Comment by songoffire** [comment]
Thanks @lavrton!   I have the same problem/use-case (though for now holding @ Konva 8.3.9 is fine for us)  We add a [Modify], [Delete], and [Drag to Move] anchor relative to the transformer like so: https://i.imgur.com/kNiMfuz.png .  In Konva 8.4.0 all of these elements render at position 0,0 relative to the canvas, rather than than rendering around the transformer as you can see in the image.
