### ISSUE TITLE
Center canvas stage to large position

### ISSUE THREAD

**Issue by kamildul** [konvajs/konva#1389]
Hello,
i need help. I try center canvas to large points XY. When i set stage x/y and loaded image x/y ex. 10000/10000 then my canvas lose all :-(

 `					var stage = new Konva.Stage({
						container: 'cad-view',
							x: 10000,
							y: -10000,
						width: width,
						height: height,
						draggable: true,
					});
					var image= new Konva.Image({
						x: 10000,
						y: -10000,
						image: imageObj
					});
`
How i can center canvas view to elements in stage?

**Comment by lavrton** [comment]
Why do you have such strange and large numbers in positions?

If you stage moved by 10000 and image is moved by 10000, then in total images is placed in 20000 position. Is it what you want?

**Comment by kamildul** [comment]
I need to set the scene view, e.g. for x / y coordinates: 100000/10000. Now I set the coordinates, but the / canvas scene is not set. stage is set to 0/0 all the time

**Comment by lavrton** [comment]
Sorry, I don't understand your issue. Please create a very small demo.
