### ISSUE TITLE
Image with RGB filter flickers when resized in Web Worker

### ISSUE THREAD

**Issue by denvolynets** [konvajs/konva#1391]
I need to achieve smooth resizing of the canvas inside the webworker, but I get noticeable flashes on every resize, is there a way around this? video - https://dl.dropboxusercontent.com/s/d71hxi5xrbenal1/8jC0LZD9uY.mp4

https://codesandbox.io/s/angry-jepsen-010fxe?file=/src/worker.js:298-315

**Comment by lavrton** [comment]
https://codesandbox.io/s/distracted-cerf-szt231?file=/src/worker.js

You just need to be careful with order of operations.  Caching image take time, so when you update stage size, it may clear its content, so for a period of time, canvas may be empty.

**Comment by denvolynets** [comment]
> https://codesandbox.io/s/distracted-cerf-szt231?file=/src/worker.js
> 
> You just need to be careful with order of operations. Caching image take time, so when you update stage size, it may clear its content, so for a period of time, canvas may be empty.

Thanks!
