### ISSUE TITLE
Render Errors on iPhone when zooming and moving using touch input

### ISSUE THREAD

**Issue by 11chrisg** [konvajs/konva#1392]
When using Konva on iPhone, occasionally the canvas does not clear and renders on top of a previouse renderings of konva, when zooming and moving using touch input.
see attached screen. 

![ef3f3163-43e8-4702-a28a-64369c059a76](https://user-images.githubusercontent.com/111973899/186393435-62ec2ce5-0ee8-493e-b6ef-b79c0a2ef524.png)

**Comment by lavrton** [comment]
I never saw this on ios. Can you make a reproducible demo?

**Comment by 11chrisg** [comment]
Took us a while to extract code and make it reproducible on an iPhone. 
Attached is a html file with javascript that will crash on an iPhone when using touch zoom

[iphone_bug_konva.zip](https://github.com/konvajs/konva/files/9581835/iphone_bug_konva.zip)

**Comment by lavrton** [comment]
Works ok for me: https://vqz5ub.csb.app/

https://codesandbox.io/s/wonderful-hawking-vqz5ub?file=/index.html

**Comment by 11chrisg** [comment]
It crashed on iPhones SE, 11 and X after zooming around after a couple seconds ~30s (not consistently but we could reproduce it on all iPhones after a few tries)
