### ISSUE TITLE
CPU utilization is too high

### ISSUE THREAD

**Issue by zhugqing** [konvajs/konva#1393]
When I use konva to draw the obstacle points of the robot costmap, when the robot moves at more than 10 times the speed, the CPU utilization will always be close to 100%. (use konva to draw 2000 circles as machine costmap obstacle points, and play the mobile machine at 10+ speed). Is there any way to solve this problem?

![企业微信截图_16615060622370](https://user-images.githubusercontent.com/79390009/186884012-1f8abbf5-2699-4546-bc47-fc1cea06a646.png)
![企业微信截图_16615064779791](https://user-images.githubusercontent.com/79390009/186884052-b7a9a286-3b51-42c3-81e7-99906702ea53.png)

**Comment by lavrton** [comment]
2000 shapes is a lot. So it takes resources to draw them. Looks here for performance optimizations: https://konvajs.org/docs/performance/All_Performance_Tips.html
