### ISSUE TITLE
Broken pointer events delegation on Samsung Internet browser

### ISSUE THREAD

**Issue by maciej-baruch** [konvajs/konva#1398]
Samsung Internet (18) browser's getImageData (https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData) returns inconsistent results - at least one of the values in ImageDate's Uint8ClampedArray is randomly offset by at least 1. It varies with every click. 

This makes it impossible for Konva's hitCanvas to identify the clicked element, and in turn to delegate an event to it, making pointer events defunct.

I am aware this is not a bug within Konva itself, but it is an issue nonetheless, as well as I am aware that making this work on Samsung's browser would require changing the way Konva identifies clicked elements.
(https://forum.developer.samsung.com/t/getimagedata/21205)

**Comment by lavrton** [comment]
That is bad news. I guess the only way it to wait for full patch deploy. I don't have any superfast solutions from Konva side. 

It is possible to monkey-patch hit detection. To just use math and `shape.getClientRect()`. But it may not work for custom shapes.
