### ISSUE TITLE
transformer dragend is working only second time 

### ISSUE THREAD

**Issue by Hayk-Asoyan** [konvajs/konva#1399]
When we are doing dragend the first time nothing is working, but if we do it second time it starts working
shouldOverdrawWholeArea=true

**Comment by Hayk-Asoyan** [comment]
When we are doing dragend the first time nothing is working, but if we do it second time it starts working

**Comment by lavrton** [comment]
Demo? This works ok for me https://jsbin.com/qacacafevu/edit?js,console,output
