### ISSUE TITLE
Swipe does not work in IE11/Edge

### ISSUE THREAD

**Issue by EugeneSqr** [konvajs/konva#140]
In IE11/Edge try swiping the red rectangle in the following jsfiddle https://jsfiddle.net/5xb5azhd/
Actual: nothing happens
Expected: "konva-hammer swipe" in console output

Please note that hammer swipe (without konva) works fine in IE11 (the black rectangle).

I believe the issue is related to pointer events. More specifically "pointerdown" event isn't getting fired.
When the page first loads, the "pointerdown" event handler is attached to the Konva.Rect object. However when one clicks the rectangle, it's the "mousedown" event that is getting fired not the "pointerdown" one.

**Comment by lavrton** [comment]
Hammer support is experiment feature. So I am closing this issue.
