### ISSUE TITLE
Drag/drop events demo is misleading by trying to set type/target

### ISSUE THREAD

**Issue by jez9999** [konvajs/konva#1405]
In the [drag/drop events demo](https://konvajs.org/docs/drag_and_drop/Drop_Events.html), the code in many places fires custom events where it sets `type` and `target` on the event object; for example:

```
            previousShape.fire(
              'dragleave',
              {
                type: 'dragleave',
                target: previousShape,
                evt: evt.evt,
              },
              true
            );
```

This is misleading as it implies the `fire` method can set these properties, which it cannot.  They both get overridden, so the code should not try to set them as it could make you think that they can actually be overridden.  The way to pass extra custom information is to set new, differently-named properties on that event object.

Also, the demo should call `layer.draw();` at the end of its `on('dragstart'` function or the first `dragmove` will incorrectly return the shape being dragged from `layer.getIntersection`.

**Comment by lavrton** [comment]
hello. Thanks for the feedback. Do you want to make a Pull Request for that demo?

**Comment by jez9999** [comment]
Which repo/location is it in?

**Comment by jez9999** [comment]
OK I found it and submitted a PR.

**Comment by lavrton** [comment]
Thanks
