### ISSUE TITLE
Ring Clockwise

### ISSUE THREAD

**Issue by Tyme-Bleyaert** [konvajs/konva#1406]
What does the attribute clockwise in Konva.Ring do?

I cannot find anthing about it in the API docs.

![image](https://user-images.githubusercontent.com/72735570/191442383-9eb44a9a-5ff4-483e-9c22-0ce83e592071.png)
![image](https://user-images.githubusercontent.com/72735570/191442742-b3274e7e-a7ba-4e67-9750-049529de3258.png)

Also if you try to set clockwise by calling a function you get an error.
`ring.clockwise(false);`
![image](https://user-images.githubusercontent.com/72735570/191443553-704d7a94-43c8-437b-9bf4-9c87c2d9a828.png)

I tried this, because I thought it might work the same as Konva.Arc.

So I'm not sure the attribute does anything.
Or maybe I'm missing something?

**Comment by yinguangyao** [comment]
Clockwise only has type definition, no implementation

**Comment by lavrton** [comment]
Thanks for the report. It looks like it is a copy/paste error.

**Comment by Tyme-Bleyaert** [comment]
It also need to be removed from [https://konvajs.org/api/Konva.Ring.html](https://konvajs.org/api/Konva.Ring.html).

**Comment by lavrton** [comment]
Yes, it will be updated with the next release.
