### ISSUE TITLE
[Enhancement] Export zIndex in toObject method

### ISSUE THREAD

**Issue by dendrofen** [konvajs/konva#1407]
To implement recovery functionality, the easiest way according to the documentation is to export Node using toObject method. When restoring, use the exported object in the Node parameters.

One of the important things to consider when exporting is object layers, zIndex. In current konva.js version, toObject doesn't return zIndex, so export/restore zIndex functionality has to be implemented using third-party functionality.

**It would be great** to add export/import index layer (zIndex) functionality to objects

**Comment by lavrton** [comment]
`zIndex` is just an index of the element in its parent `children` attribute. When you export into object, order in array is preserved. So, I am not sure what you're missing here.

**Comment by lavrton** [comment]
`zIndex` is not saved intentionally by the reason I mentioned above.

If you really need it, save in into custom attribute, then load from it.

```js
group.setAttr('myZIndex', group.zIndex());

// then on after import
group.zIndex(group.getAttr('myZIndex'));
```

**Comment by dendrofen** [comment]
### export/import Demo
I have created demo. In demo implemented 2 cases: 
- whole stage toObject import/export
- each node import/export (with exported object array shuffle, to modulate late adding object to stage (like clicking on button etc... ) )

https://codepen.io/dendrofen/pen/WNJEqOG

While click on **recreate** button, you are able to see that imporing each node functional missing zIndex time by time.

### setting zIndex manually
This will cause error also, because can't set zIndex bigger than nodes count on layer...
