### ISSUE TITLE
group export json lose

### ISSUE THREAD

**Issue by lishaoxin123** [konvajs/konva#1409]
Hello, I have a problem. I use a group to make containers. I use clipFunc to cut containers and add an image to the group to achieve circular images. But I find that my effects are lost when exporting. Is there any way to solve this problem

**Comment by lavrton** [comment]
Functions are not serialized into JSON. If you can't use `clip` attribute, then you need to find a way to store the function in the scope of your application.

Also, please read https://konvajs.org/docs/data_and_serialization/Best_Practices.html.
I don't recommend to use Konva export/import methods in any complex scenarios.

**Comment by lishaoxin123** [comment]
> Functions are not serialized into JSON. If you can't use `clip` attribute, then you need to find a way to store the function in the scope of your application.
> 
> Also, please read https://konvajs.org/docs/data_and_serialization/Best_Practices.html. I don't recommend to use Konva export/import methods in any complex scenarios.



> Functions are not serialized into JSON. If you can't use `clip` attribute, then you need to find a way to store the function in the scope of your application.
> 
> Also, please read https://konvajs.org/docs/data_and_serialization/Best_Practices.html. I don't recommend to use Konva export/import methods in any complex scenarios.

Thanks for your reply. I tried to use fillPatternImage, but I don't know whether the size of the image can be modified. I think the image is larger than the outer rectangle to simulate the clipping style
