### ISSUE TITLE
How to set rect partial stroke width to zero?

### ISSUE THREAD

**Issue by heinz-lxy** [konvajs/konva#1410]
In CSS, we can set div border to zero by four different directions: top, bottom, left and right.
So I wonder if there is a way to do so in Konva too. Thanks.

**Comment by lavrton** [comment]
No. Just use lines to draw that.

**Comment by heinz-lxy** [comment]
> No. Just use lines to draw that.

Then is is possible to fill color in shape made of lines, because I want it to cover other shapes.

**Comment by lavrton** [comment]
Use several shapes. You can use one or many for stroke. And another closed line for fill.
