### ISSUE TITLE
When using the cache, modifying the shape attribute will not take effect

### ISSUE THREAD

**Issue by yinguangyao** [konvajs/konva#1413]
If I set the cache for the shape, when I set the new property, I find that there is no re-rendering.

Do we need to invalidate the cache when some properties are modified?

https://codesandbox.io/s/suspicious-hooks-oh0mk3?file=/src/index.js

**Comment by lavrton** [comment]
Currently, this is intentionally. You have to manually re-cache it. 

Caching is a slow process. So automatic invalidate can make the app very slow.
