### ISSUE TITLE
Whether font-weight and font-styles can be split

### ISSUE THREAD

**Issue by tyutjohn** [konvajs/konva#1414]
Thanks for this great library
I want to use both 'font-weight: bold ' and 'font-style: italic，but now it can only take effect for one property, just like 'font-style: bold' or 'font-style: italic'
So how can I use them to work together for me

**Comment by lavrton** [comment]
From docs https://konvajs.org/api/Konva.Text.html#Text

`fontStyle` - an be 'normal', 'bold', 'italic' or even 'italic bold'. Default is 'normal'

**Comment by tyutjohn** [comment]
> 

Thanks Reply! It works for me.
