### ISSUE TITLE
How can I give stroke to my shape when also using globalCompositeOperation =destination-out

### ISSUE THREAD

**Issue by nnha19** [konvajs/konva#1415]
**Please take a look the demo I built below**. 

Essentially, my shape has ``` globalCompositeOperation = destination-out``` and when I gave it stroke, it didn't show up. I need a way to give it stroke when also using  ``` globalCompositeOperation = destination-out```. Is there a way to do that??

[Demo Link](https://codesandbox.io/s/react-konva-draw-polygon-forked-uhhz0c?file=/src/index.js:1654-2073)

**Comment by lavrton** [comment]
Just use two shapes. One for `globalCompositeOperation` another for stroke.

https://codesandbox.io/s/react-konva-draw-polygon-forked-fkuy1s?file=/src/index.js
