### ISSUE TITLE
Shadows not displaying on 90 / 270 degree rotation

### ISSUE THREAD

**Issue by gastromis** [konvajs/konva#142]
Upon rotating a sprite by 90 or 270 degrees, the specified shadow is gone. 0° and 180° rotation however display the shadow just fine.

Example: https://codepen.io/Bobbing/pen/qZoqEX

**Comment by lavrton** [comment]
Hm. Strange. Still no shadow in Chrome. But works in firefox: http://jsbin.com/sojiyaxoqi/edit?html,js,output

As workaround, for now, you can set `stroke` property: http://jsbin.com/runomugiti/1/edit?html,js,output

**Comment by lavrton** [comment]
I will close this issue. I think it is a bug in Chrome and I am not sure what should we do to avoid it in `Konva` source.
Firefox and Safari work ok.
As a workaround, you may set fill `black` for an image. It should help.
