### ISSUE TITLE
Refactor: Replace konvaEvent.cancelBubble with konvaEvent.stopPropagation?

### ISSUE THREAD

**Issue by nabati** [konvajs/konva#1420]
Was wondering, would it make sense to replace konvaEvent.cancelBubble property with a konvaEvent.stopPropagation method?

I guess it was modeled after https://developer.mozilla.org/en-US/docs/Web/API/Event/cancelBubble which is now deprecated, and I guess there is some value in trying to keep the interfaces aligned. 

WDYT, @lavrton ?

**Comment by lavrton** [comment]
I don't think it is important. `evt.cancelBubble` in Konva event system doesn't use real DOM property.
