### ISSUE TITLE
Arc & Wedge issue in group with transformer.

### ISSUE THREAD

**Issue by Tyme-Bleyaert** [konvajs/konva#1421]
1) If you create a arc and put it in a group and add a transformer to the group, you end up with a shape that is off-center.
2) If you create a wedge do the same, you end up with with a lot of empty space when applying the transformer.

Example: [https://codesandbox.io/s/elastic-heyrovsky-j71o8p?file=/src/index.js](https://codesandbox.io/s/elastic-heyrovsky-j71o8p?file=/src/index.js)

I think the problem is probably caused by getSelfRect.

I think in wedge it just works as default.
And in arc it would be better to have some extra top boundary based on the rotation it's in, if the shape is rotated.

**Comment by lavrton** [comment]
For (1), Arc is not so smart about its bounding rect, comparing to wedge. It will be good to have a Pull Request to fix it.

(2) is a side effect of rotated shape + group usage. `Konva.Transformer` do not understand that something inside the group is rotate, so it should rotate itself too. So, I will keep this behavior as is, until someone intelligent will find the best solution for that.
