### ISSUE TITLE
How can I get the position of the node relative to Stage regardless of the scaling or position of the stage ( Video Below )?

### ISSUE THREAD

**Issue by nnha19** [konvajs/konva#1423]
I have a Stage which can be zoomed and panned. I also have a rectangle which can be resized, I am using transformer and attaching that transformer to rectangle. I also have a dragBoundFunc for the transformer which contains the transforming inside the stage. Here is the ```dragBoundFunc``` function

```
boundBoxFunc={(oldBox, newBox) => {
        const stage = stageRef?.current;
        if (!trRef || !stage) return oldBox;
        const box = trRef.getClientRect();

        const subtract = (canvasZoom - 1) * 100;

        const isOut =
          box.x < -22 ||
          box.y < -10 ||
          box.x + box.width - 4 > stage.width() ||
          box.y + box.height - 4 > stage.height();

        if (isOut) {
          return oldBox;
        }
        return newBox;
      }}

```

 Resizing works just fine unless the stage is scaled or position( x,y ) of the stage is 0. But, if the stage is scaled or dragged, resizing no longer works as expected. For the above code, if 

``` box.x  < -22 ```

This means the end and rectangle shouldn't be stretched any further. But, when stage is scaled and panned, that x is not the beginning of the Stage. It's the area that is visible on the screen. How can I get the x position of the rectangle/node which is the beginning of the Stage?

https://user-images.githubusercontent.com/78017969/195272317-d3158933-0e17-42cb-a10c-e8af000d2f8a.mp4

**Comment by raphael-papazikas** [comment]
Not sure if this solves your issue, but you could pass a `relativeTo` option. 
```
trRef.getClientRect({relativeTo: stage});
```
https://konvajs.org/api/Konva.Rect.html#getClientRect__anchor
