### ISSUE TITLE
validateAnchors Transformer API Docs

### ISSUE THREAD

**Issue by Tyme-Bleyaert** [konvajs/konva#1424]
On the transformer API page under validateAnchors : [https://konvajs.org/api/Konva.Transformer.html#validateAnchors__anchor](https://konvajs.org/api/Konva.Transformer.html#validateAnchors__anchor)

The information is correct, but the name should be "anchorSize".

![image](https://user-images.githubusercontent.com/72735570/195280132-6b5df487-0512-4c54-8081-77d9c564a5b1.png)

**Comment by lavrton** [comment]
Fixed
