### ISSUE TITLE
resizeEnabled Transformer API Docs

### ISSUE THREAD

**Issue by Tyme-Bleyaert** [konvajs/konva#1425]
I don't think resizeEnabled of transformer takes an array/ returns an array.

[https://konvajs.org/api/Konva.Transformer.html#resizeEnabled__anchor](https://konvajs.org/api/Konva.Transformer.html#resizeEnabled__anchor)

![image](https://user-images.githubusercontent.com/72735570/195281718-33633bfe-2b05-4815-9217-6a5597032b40.png)

**Comment by lavrton** [comment]
Fixed
