### ISSUE TITLE
borderStrokeWidth Transformer API Docs

### ISSUE THREAD

**Issue by Tyme-Bleyaert** [konvajs/konva#1426]
BorderStrokeWidth should be number instead of boolean.

[https://konvajs.org/api/Konva.Transformer.html#borderStrokeWidth__anchor](https://konvajs.org/api/Konva.Transformer.html#borderStrokeWidth__anchor)

![image](https://user-images.githubusercontent.com/72735570/195282414-716d0081-47d1-4e5a-b803-3dea8ba7642a.png)

**Comment by Tyme-Bleyaert** [comment]
Also the following :
Should be number instead of boolean:
[https://konvajs.org/api/Konva.Transformer.html#anchorCornerRadius__anchor](https://konvajs.org/api/Konva.Transformer.html#anchorCornerRadius__anchor)
[https://konvajs.org/api/Konva.Transformer.html#anchorStrokeWidth__anchor](https://konvajs.org/api/Konva.Transformer.html#anchorStrokeWidth__anchor)
Should be string instead of boolean:
[https://konvajs.org/api/Konva.Transformer.html#anchorStroke__anchor](https://konvajs.org/api/Konva.Transformer.html#anchorStroke__anchor)
[https://konvajs.org/api/Konva.Transformer.html#anchorFill__anchor](https://konvajs.org/api/Konva.Transformer.html#anchorFill__anchor)

**Comment by lavrton** [comment]
That is nice feedback. Are you interested in making a Pull Request to fix it? In all the cases, we just need to fix jsdoc in source files.

**Comment by Tyme-Bleyaert** [comment]
Sure, I'll look into it when I have some spare time.

**Comment by Tyme-Bleyaert** [comment]
#1430
