### ISSUE TITLE
Typescript 4.7+ `NodeNext/Node16` incompatibility

### ISSUE THREAD

**Issue by scott-lc** [konvajs/konva#1432]
TypeScript 4.7 [added full support for ESM Modules](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#ecmascript-module-support-in-node-js) via two new tsconfig `module` settings - `nodenext` and `node16`.

One of the caveats of these new module resolution modes is that:

> Relative import paths need full extensions (we have to write import "./foo.js" instead of import "./foo").

Unfortunately the TypeScript code is missing `.js` import extensions throughout.

**Comment by lavrton** [comment]
May help https://github.com/konvajs/konva/blob/master/rename-imports.mjs

**Comment by scott-lc** [comment]
@lavrton - Thanks.  I see now that none of the `*.d.ts` files have import extensions, not just `index-types.d.ts`

**Comment by lavrton** [comment]
Yeah, that script manually adds extensions into js files only.
But I am not sure `d.ts` should do the same. Because type files should only import other type files, right?

**Comment by scott-lc** [comment]
I see a potential fix to transform both `./lib/*.js` as well as `./lib/*.ts` as well as have `rename-imports` handle the `import(...)` syntax you have in `index-types.d.ts`.   For example:

```
export const Layer: typeof import('./Layer').Layer;
export type Layer = import('./Layer').Layer;
```

**Comment by scott-lc** [comment]
`rename-imports.mjs`
```
...
// Also transform TS files.
const files = FileHound.create().paths('./lib').ext(['js', 'ts']).find();

...
// Handle import("./x/y/z") syntax.
text = text.replace(/(import\s*\(\s*['"])(.*)(?=['"])/g, '$1$2.js');
```

**Comment by rkuhn** [comment]
Does this issue explain why `Konva.Stage` has type `any` and why I can’t use `react-konva`?

```
error TS2322: Type '{ width: number; }' is not assignable to type 'IntrinsicAttributes & StageProps & KonvaNodeEvents & ClassAttributes<any>'.
  Property 'width' does not exist on type 'IntrinsicAttributes & StageProps & KonvaNodeEvents & ClassAttributes<any>'.

130       <Stage width={300}></Stage>
                 ~~~~~
```

If yes, what can I do to work around this issue?

**Comment by lavrton** [comment]
I still don't understand the root of the issue. Can someone create a small repository to reproduce the issue?

**Comment by rkuhn** [comment]
The root of the issue is that the `.d.ts` files distributed with `konva` contain lines like the following (here from `lib/index-types.d.ts`):
```ts
  export type Vector2d = import('./types').Vector2d;
```
In ESM mode, TypeScript fails to read the import and assigns `type Vector2d = any`. You can see this by creating an empty project with `"type": "modules"` in `package.json` and a `tsconfig.json` like the following:
```json
{
  "compilerOptions": {
    "alwaysStrict": true,
    "declaration": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": false,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "lib": ["dom", "es2019"],
    "module": "Node16",
    "moduleResolution": "Node16",
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "outDir": "lib",
    "preserveConstEnums": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "strictBindCallApply": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "stripInternal": true,
    "target": "es2019"
  }
}
```
Then add `react-konva` as a dependency and try using it. You’ll get very confusing error message like the one I showed above, which stems from `any` appearing as `konva` types.

**Comment by rkuhn** [comment]
Works nicely, thanks!
