### ISSUE TITLE
How can I manipulate it by click on the button?

### ISSUE THREAD

**Issue by LuizProject46** [konvajs/konva#1435]
![Captura de Tela 2022-10-20 às 14 01 17](https://user-images.githubusercontent.com/43315377/197012842-a06414ef-53d9-4b51-a6b8-095fbb0232e2.png)

**Comment by lavrton** [comment]
It is a group or just several nodes in transformer? Where is it origin point? If it is in the center, just rotate it. If it is in the top, left. Then use power of math to calculate new `x` and `y`.

**Comment by LuizProject46** [comment]
Thanks !
