### ISSUE TITLE
Calling `fire('mousedown')` on a draggable node causes an error

### ISSUE THREAD

**Issue by HuaiYu-Chao** [konvajs/konva#1436]
When invoking `fire('mousedown')` without providing an event object, `evt.evt` is `undefined`, which I think should be an expected situation since calling `startDrag()` has the same behavior.
However, this makes the checking in line 2482 causes an error (`Cannot read properties of undefined (reading 'button')`).

Prehaps change it to `evt.evt?.['button'] !== undefined` or `evt.evt?.button !== undefined`?

https://github.com/konvajs/konva/blob/578191d5d4755b4b2d1f9490284b32d9953656ac/src/Node.ts#L2478-L2484

I'm happy to try to open a PR, just not sure if it's a proper thing to do without confirming the issue, or if the fix is too trivial to bother merging a PR. (I haven't really joined a discussion on GitHub.)

**Comment by lavrton** [comment]
Why do you call this event manually?
