### ISSUE TITLE
How can Stage.getClientRect take into account clipping?

### ISSUE THREAD

**Issue by jez9999** [konvajs/konva#1437]
I'm using `Stage.getClientRect` to determine the actual height/width of all the content on the stage.  The problem is, some of my content is taller than I want it to be, so I clip it by passing a `clipFunc` into the config object I pass to the `Konva.Group` constructor when creating the group I add to the Stage.  This makes the content look less tall, but `Stage.getClientRect` still reports the height as being the original content height before clipping.  How can I make it take clipping into account?

**Comment by lavrton** [comment]
`node.getClientRect()` ignores clipping. And I don't have any plans to include that into that function. As it will overcomplicate everything.

Solution - calculate bounding box manually.

**Comment by jez9999** [comment]
But I have tons of objects on the stage.  `getClientRect` is doing quite a bit of work for me.  Are you saying my code needs to manually loop round all of my objects manually and figure out the bounding box??

**Comment by lavrton** [comment]
It shouldn't be very hard. You can use existing `node.getClientRect()` for most of your nodes, except clipped one. For them, just adjust returned value by your clipping logic.

**Comment by jez9999** [comment]
Well yeah and while I'm at it I could write an entire graphics library to help me render to canvas.  Kinda thought that was the sort of thing Konva was meant to help with.

**Comment by lavrton** [comment]
Yeah, it is sad that Konva is not so good...

**Comment by yinguangyao** [comment]
@jez9999 I encountered the same problem, so I chose to clone konva, modify its source code and maintain it myself
