### ISSUE TITLE
Transform Width and Height instead of scaleX scaleY

### ISSUE THREAD

**Issue by afdallah** [konvajs/konva#1440]
Hi, I'm trying to make the transformer behave similarly to figma. When we resize the node, I want it to affect the **width** and **height** instead of the **scaleX**, **scaleY**.

Cos currently when we resize the object, the image will be **skewed**, and the border will also change in size due to the scaleX and scaleY change.

image skewed
<img width="215" alt="image" src="https://user-images.githubusercontent.com/11598084/198499316-c822f5ee-74a7-459d-9ce4-885f46dff6e2.png">

4px border looks bigger
<img width="527" alt="image" src="https://user-images.githubusercontent.com/11598084/198499226-d921737d-749b-4a29-bb9d-b11d1505ba19.png">

is there any way to do that?
I couldn't find api to support this in the transformer doc.

Thanks!

**Comment by lavrton** [comment]
You can do that by yourself. Here is sample code.

```js
shape.on('transform', () => {
  shape.setAttr({
     width: shape.width() * shape.scaleX(),
     height: shape.height() * shape.scaleY(),
     scaleX: 1,
     slaleY: 1
  })
});
```

You may need some extra logic to handle stroke resizes. Or you can just ignore stroke in transformer (see docs about it).
