### ISSUE TITLE
How we can increse DPI from 72 to 300 without changing dimensions?

### ISSUE THREAD

**Issue by prataprockerss** [konvajs/konva#1441]
I want to use fixed dimensions eg. Insta Story 1080x1920 but want to increase DPI to the same size.

**Comment by lavrton** [comment]
Why do you need to increase DPI? DPI is a measurement to convert into physical space. Do you plan to print?

**Comment by prataprockerss** [comment]
Yes @lavrton We have plan to print the artwork.

**Comment by lavrton** [comment]
Then it is up to you to control DPI. Konva works in pixels. Or to be more correct in CSS pixels.

If you export stage with the size of 1080x1920, by default you will have a picture with 100% the same size. Same number of pixels. There is no DPI value for image. It is just pixels. 

If you want to increase number of pixels, there are two ways:
(1) increase size of the stage
(2) export with high `pixelRatio` value. E.g. `stage.toDataURL({ pixelRatio: 300 / 72 })`

It will produce bigger/smaller image. Most of the vector shapes (e.g. Rect, Circle, Text) will have higher quality. Quality of images, depends on original size of the images.

**Comment by prataprockerss** [comment]
Thank you for details explanation
