### ISSUE TITLE
How to make the globalCompositeOperation only take effect between two specified shapes

### ISSUE THREAD

**Issue by RexYuan1114** [konvajs/konva#1443]
How to make the globalCompositeOperation(such as source-atop) only take effect between two specified shapes when there are many shapes in one layer?
I tried to implement this by spliting shapes to many layers, but Konva warn me that there were too much layers.

**Comment by lavrton** [comment]
It may be hard in some cases. The simplest solution is to put them into a group and cache that group. A cached group is rendered on its own canvas element.

**Comment by RexYuan1114** [comment]
> It may be hard in some cases. The simplest solution is to put them into a group and cache that group. A cached group is rendered on its own canvas element.

Help a lot. Thank you！
