### ISSUE TITLE
Showing iPad dock breaks touch input on stage

### ISSUE THREAD

**Issue by Joebayld** [konvajs/konva#1446]
I've come across a weird one.. 

I have a fullscreen konva app with plenty of interactions - draggable, selecting nodes, moving nodes, etc. When in the fullscreen browser on iPad and swiping up from the bottom of the display to show the dock, it breaks all touch interactions with Konva. I then have to reload the entire webpage to fix it. The worst part is no errors are reported. 

Let me know how I can assist in demonstrating this issue - but it's going to be tricky I'm sure.

**Comment by lavrton** [comment]
If it is still relevant, make a very small online demo.
