### ISSUE TITLE
How to display "overlay" information?

### ISSUE THREAD

**Issue by jez9999** [konvajs/konva#1447]
I've implemented a Konva setup where I use a stage with several layers, and I use both draggability and scaling on the stage to allow pan and scan.

Now I want to overlay information (usually text) on top of all that.  The trouble is that if I just add it as another layer on top, it gets dragged and scaled with all the other layers.

How can I add a layer on top that doesn't drag and scale with the other layers?

**Comment by jez9999** [comment]
I think what would be useful is the ability to group layers.  Right now, I am making the stage draggable and scaling the stage.  Really, I want to make a layer group draggable and scale that.  Then I could add a layer group on top of that, and it would stay undraggable and unscaled.

**Comment by lavrton** [comment]
Use groups. Don't scale full stage or layer. Instead scale/drag group. Put "static" text outside that group.

**Comment by jez9999** [comment]
> Use groups. Don't scale full stage or layer. Instead scale/drag group. Put "static" text outside that group.

But the thing about making the stage is draggable is that you can click anywhere on the canvas and it will drag.  How can you achieve that same effect with a group?  Won't it only make the group shapes draggable?

**Comment by lavrton** [comment]
You can put a transparent rectangle as a background, to make "empty" space clickable.
Another solution is to keep draggable on stage, but on any stage props change (x, y, scale, rotation) you need to reset position of static text: set absolute position, absolute scale and absolute rotation.
