### ISSUE TITLE
Usage in Electron without "canvas" module

### ISSUE THREAD

**Issue by jonathan-roy** [konvajs/konva#1448]
I'm using Konva v7 in an Electron app and would like to upgrade to Konva v8.

When doing so, I have a `Cannot find module 'canvas'`. I know that Konva now embeds the Node version of Konva but since I am in an Electron app, I would like to use the browser version instead. I guess this is related to the fact that in my case Konva is not directly used in Electron:
- I have a custom NPM package using Konva internally. That package is not related to Electron at all, and is compiled with Webpack using `web` target.
- Then in my Electron app I make use of that compiled package.

I don't know if I missed something? Is it really needed to use the Node version of Konva in that case?

**Comment by lavrton** [comment]
You may need to find why your environment is trying to load NodeJS version of KonvaJS.

**Comment by jonathan-roy** [comment]
I fixed it by adding `konva` to [Webpack's `externals` option](https://webpack.js.org/configuration/externals/).
