### ISSUE TITLE
Let the starting coordinates always be at the center of the canvas.

### ISSUE THREAD

**Issue by SF-Simon** [konvajs/konva#1449]
Hello
We have a requirement that when we adjust the size of the canvas, the center position will remain the same, but the visible range of up, down, left, and right changes with the size of the canvas.

That is, the position of the center of the canvas is always a fixed coordinate(0, 0).

How can this requirement be achieved?

thx.

**Comment by lavrton** [comment]
Stage has `x` and `y` properties. Adjust them according to the canvas area size.
