### ISSUE TITLE
Next.js 13 related ESM/CJS issues with canvas

### ISSUE THREAD

**Issue by stx-chris** [konvajs/konva#1458]
We've recently stumbled upon some ESM/CJS bundling issues with `Konva` in next.js (appDir version), resulting in an error when any of the Konva classes is used:

MInimal example:
```
"use client"; // needed for Next.js 13 to indicate its a client-only component

import Konva from "konva";

export default function Example() {
   const Rect = Konva.Rect;
   return <div>Hello</div>;
}
```

leads to:

```
error - ./node_modules/konva/cmj/index-node.js
Module not found: Can't resolve 'canvas' in '.../node_modules/konva/cmj'
Did you mean './canvas'?
```

Since only this library is affected, we suspect a general bundling issue with Konva.

Find here the [linked next.js issue](https://github.com/vercel/next.js/issues/43567).

**Comment by lavrton** [comment]
Will it resolve the issue if you manually install `canvas` package? `npm install canvas`

**Comment by stx-chris** [comment]
> Will it resolve the issue if you manually install `canvas` package? `npm install canvas`

No, unfortunately not. Tried both as dev and ordinary dependency.

**Comment by stx-chris** [comment]
It doesn't help if I install `canvas` in my project; the error occurs in the compiled `Konva` package when client-side rendered with Next.js 13. It seems that, for some reason, the `canvas` library is not found in the final bundle.

The only workaround that let's me compile my app (but still results in warnings) is when I explicitly tell Webpack to treat `canvas` as an external package:

```
config.externals = {
      canvas: "canvas",
};
```

....which is an indicator that `canvas` is not ideally bundled with `Konva` in the distribution package.

**Comment by davincios** [comment]
I have the same issue with Konva and Next.js 13! Also tried installing canvas before coming here. 

Where can I find this config file for web pack @stx-chris ? Do I need to install webpack to do this?

**Comment by stx-chris** [comment]
Hi @davincios, a warning-free workaround I found comprises the following measures:

**next.config.js:**
```
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    appDir: true,
    esmExternals: "loose", // required to make Konva & react-konva work
  },
  webpack: (config) => {
    config.externals = [...config.externals, { canvas: "canvas" }];  // required to make Konva & react-konva work
    return config;
  },
};
```

It is important to append `canvas` instead of replacing `config.externals` directly, as the array already contains a bunch of exceptions.

**Dynamic import of all components which use `Konva` and `react-konva`, ssr disabled:**
```
import dynamic from "next/dynamic";
const KonvaComponent = dynamic(() => import("./KonvaComponent"), { ssr: false });
```

No need to add `canvas` as a dependency.

**Comment by davincios** [comment]
> Hi @davincios, a warning-free workaround I found comprises the following measures:
> 
> **next.config.js:**
> 
> ```
> const nextConfig = {
>   reactStrictMode: true,
>   experimental: {
>     appDir: true,
>     esmExternals: "loose", // required to make Konva & react-konva work
>   },
>   webpack: (config) => {
>     config.externals = [...config.externals, { canvas: "canvas" }];  // required to make Konva & react-konva work
>     return config;
>   },
> };
> ```
> 
> It is important to append `canvas` instead of replacing `config.externals` directly, as the array already contains a bunch of exceptions.
> 
> **Dynamic import of all components which use `Konva` and `react-konva`, ssr disabled:**
> 
> ```
> import dynamic from "next/dynamic";
> const KonvaComponent = dynamic(() => import("./KonvaComponent"), { ssr: false });
> ```
> 
> No need to add `canvas` as a dependency. The `"use client"` directive is insufficient, the dynamic load is still required as of now (next.js version `13.0.6`)

Thanks a lot for getting back to me on this! 

I attempted your approach and it solved the issue. 🙏 and I hope it will help others too who read it.

**Comment by stx-chris** [comment]
Update on the workaround, as of `next.js 13.0.7`

**Step 1: Update next.config.js:**

```
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    appDir: true,
    esmExternals: "loose", // required to make Konva & react-konva work
  },
  webpack: (config) => {
    config.externals = [...config.externals, { canvas: "canvas" }];  // required to make Konva & react-konva work
    return config;
  },
};
```

**Step 2: Add `canvas` as a dependency**
```
yarn add canvas
```

**Step 3: Use the components as usual**
```
import Konva from "konva";
import { Rect } from "react-konva";
```

**Comment by imranbarbhuiya** [comment]
For me, `konva` and `react-konva` works now without `esmExternals` config and I also don't need to install `canvas`

**Comment by sri-gowda** [comment]
Not working for nextjs `13.4.4`

Getting the below Error

<img width="586" alt="Screenshot 2023-06-16 at 5 26 57 PM" src="https://github.com/konvajs/konva/assets/30023455/0158afc2-0d8c-4e59-8dbc-97d7e7622035">

If i try to install canvas getting below Error
<img width="899" alt="Screenshot 2023-06-16 at 5 28 44 PM" src="https://github.com/konvajs/konva/assets/30023455/88267d31-7c3d-4ffb-946a-4727ddddeb18">

**Comment by lavrton** [comment]
Just tried react-konva with the last nextjs and app dir. Works good for me. Docs: https://github.com/konvajs/react-konva#usage-with-nextjs

**Comment by walrus811** [comment]
> Just tried react-konva with the last nextjs and app dir. Works good for me. Docs: https://github.com/konvajs/react-konva#usage-with-nextjs

This guide works well in`next@13.4.13`. I've missed the part below.

"You need to define your canvas components somewhere in your components folder. It shouldn't be inside pages or app folder (because they are used for server rendering)."

you need to move a component that uses konva with `next/dynamic` from app folder to a component folder.
