### ISSUE TITLE
issue with webpack, require jsdom and canvas 

### ISSUE THREAD

**Issue by microcipcip** [konvajs/konva#146]
It seems that Konva does not work when it is included with webpack. The reason is that in [global.js](https://github.com/konvajs/konva/blob/master/src/Global.js#L223) the check for global window returns false, this may be because webpack runs inside node.js so the global window is not available. 

Because the global window check fails, the library tries to require `jsdom` and `canvas`, which obviously are not needed because Konva library will be ultimately used in the browser. 

The 'dirty fix' I had to perform is the following (in  webpack.config.js):
```
plugins: [
		new webpack.IgnorePlugin(/^(canvas|jsdom)$/)
	],
```

But it would be nice if this could be fixed directly in the global.js file.

**Comment by lavrton** [comment]
I am using `Konva` with `webpack`. It works well.

What exactly is not working? `canvas` and `jsdom` are described in package.json to be skipped in browser env.
How do you install `Konva`? From npm?

**Comment by microcipcip** [comment]
Thanks! I wasn't aware of the browser env. I had installed it manually by downloading the src folder, I didn't look into the package.json file. Indeed, if I add the browser env in the package.json file it works correctly.
```
  "browser": {
    "canvas": false,
    "jsdom": false
  },
```
