### ISSUE TITLE
scale possibly being undefined

### ISSUE THREAD

**Issue by nabati** [konvajs/konva#1461]
1. In https://github.com/konvajs/konva/commit/63d2aceaa7dbedfeaeae6048fd02efa9786feca4#diff-9f5c71cbe2421db7a3b3d6761c0501977bb72c8e1264a6b3454619a815aa9939R2616 `scale()` has changed signature to possibly return undefined. Should this not be a breaking change / warrant a major version change?
2. The documentation doesn't seem to have been updated accordingly (it still says it returns an object) https://konvajs.org/api/Konva.Node.html#scale__anchor
3. When can the scale now return undefined?

**Comment by lavrton** [comment]
1. I don't think type changes should be a breaking change.

2 and 3 - `node.scale()` MUST return an object. Signature changed just for setting. `node.scale(undefined)`. We may change that signature back.

**Comment by nabati** [comment]
1. It depends on the type change. Narrowing a type is a non-breaking change, but widening a type is a breaking change since it..... breaks stuff for existing consumers of the library. I.e. you can't just upgrade and have the build succeed. 
2 and 3. If it can never return undefined then it shouldn't be part of the signature 🤷
