### ISSUE TITLE
Transformer responding randomly to pointer events

### ISSUE THREAD

**Issue by LetsRoleRPG** [konvajs/konva#1463]
Hello,

Konva version: **8.3.14** using TypeScript
Browser: same behavior on Chrome and Firefox

I'm facing a regression with Transformer recently. In my app, I use a `Konva.Group` which is `draggable()`, and inside this group there is a `this.content: Konva.Group`. This `content` property contains various images and texts.

Adding a `Transformer` to the main group, and set the transformer's nodes to `[this.content]`.

And it worked great until about a few weeks ago when my users started complaining about the transformer not being usable. The mouse pointer does not respond to the transformer.

Here is a live demo : 

![demo](https://cdn.discordapp.com/attachments/926147931755642953/1053343745946427432/transformer.webp)

Here is some related code : 

```typescript
        this.transformer = new Konva.Transformer({
            keepRatio: true,
            borderStroke: 'grey',
            anchorStroke: 'grey',
            enabledAnchors: ['top-left', 'top-right', 'bottom-left', 'bottom-right'],
            centeredScaling: false,
            rotationSnaps: [0, 90, 180, 270],
            padding: 5
        });

        this.add(this.transformer);
        this.transformer.hide();
        this.transformer.nodes([this.content]);
```

`this` is an instance of a class that extends `Konva.Group`. This group is `draggable()`. `this.transformer.show()` is called in a `mousedown` event.

I've tried `transformer.moveToTop()`, `shouldOverdrawWholeArea` parameter to `true`, no `padding` parameter, with no luck.

I'm not sure if this is a Konva bug or something on my end, but any help would be greatly appreciated.

**Comment by lavrton** [comment]
Please make a small demo. Will very minimal reproducible code.

**Comment by LetsRoleRPG** [comment]
Alright, found the issue, it was related to `hitCanvas.setPixelRatio()`.

Here is a JSBin where you can try it:
https://jsbin.com/noloyoqalu/edit?html,js,console,output

Maybe this is the expected output, but I would recommend at least a warning in the documentation "transformers won't work with a setPixelRatio too low".

**Comment by lavrton** [comment]
Why did you set such a small pixel ratio? Any events will not work if you see too small value.

I don't think it is something that the library should care about. I don't even sure that `hiCanvas.setPixelRatio()` is documented anywhere.

**Comment by LetsRoleRPG** [comment]
Yeah, I was trying to improve performances, and probably ended up on a post on stackoverflow or here about `setPixelRatio`. From what I tried, lowering `setPixelRatio` actually worked, it improved performances. But yeah, broke some events, so... not so good.
