### ISSUE TITLE
Konva swallowing button 4 and 5 (mouse backward and mouse forwards buttons)

### ISSUE THREAD

**Issue by greenbech** [konvajs/konva#1465]
Hello, and thank you for the great library!

I would like to be able to navigate backward and forwards with an external mouse also over a Konva canvas, but it seems like Konva is swallowing these buttons (e.g. in some way calling `preventDefault()`).

### Reproduce

If you go to any Konva demo and click on the `mouse backward` or `mouse forward` button the browser window will not navigate to the previous or next page. In [this example](https://konvajs.org/docs/sandbox/Free_Drawing.html) specifically, if you click on these buttons over the grey area, it will brush the canvas, just as if you clicked with your primary button.

**Comment by lavrton** [comment]
Do you want to make a pull request with the fix? Probably we should filter buttons...

**Comment by lavrton** [comment]
Closing as not priority for Konva. Happy to apply related Pull Request.
