### ISSUE TITLE
Maximum call stack size exceeded when I click transformer's rects without dragging them

### ISSUE THREAD

**Issue by gyhyfj** [konvajs/konva#1466]
I want to add node into transformer's nodes arrary by click, so my code is like this:
```ts
stage.on('click', e => {
      tr.nodes([e.target])
})
```
It worked well until I just click transformer's rects WITHOUT dragging them ! 
Terminal told me this and then my app turn out to be retard: 
```ts
Uncaught RangeError: Maximum call stack size exceeded 
```
So I have to add more code like this:
```ts
stage.on('click', e => {
    // @ts-ignore
    if (e.target.parent === tr) {
        return
    }
})
```
And I have to use `// @ts-ignore` to skip ts warnnig there ....
Any plan to avoid such condition here?

**Comment by lavrton** [comment]
Well, you may click on transformer. So `e.target` will be transformer. And you are trying to attach transformer into itself. And that is obviously not a good flow. So, you need to check what exactly you are trying to attach. The error may be a bit more informative. But it is still an error.

So no plans to avoid conditions.
