### ISSUE TITLE
How can I detect a node outside or inside a rect-like area？

### ISSUE THREAD

**Issue by xinnai** [konvajs/konva#1467]
Hi, thank you very much for this awsome lib, I want to implement a function like the picture below, but I have some questions for help,
![Snip20221224_19](https://user-images.githubusercontent.com/23135336/209426379-7b30c870-ab77-4227-b348-28dd9e741737.png)
1、I think this gray area is a Stage, but what this white area is , is it a Rect or not?
2、If it's a Rect, how can I know the node is inside it or not? How can I make the part  which inside the Rect highlight and the other part has different css.
3、If I have a preview page of this editor page, how can I make the preview page only display the content in the white Rect，but the content outside the rect hide in the stage?

**Comment by ee99ee** [comment]
I will assume the image is an `Image` and the white box is a `Rect` on the same `Stage`. To identify if the boxes overlap, you could simply read the `x` and `y` of the objects and calculate their size based on `width` and `height`, and then use some simple math to calculate if there is any overlap.

Right?

**Comment by lavrton** [comment]
> I think this gray area is a Stage, but what this white area is , is it a Rect or not?

In the last Polotno version it is line with hole inside. Previous it was (1) grey rectangle + (2) white rectangle + (3) clipped content (so it doesn't go outside of avaialble area).


> If it's a Rect, how can I know the node is inside it or not? How can I make the part which inside the Rect highlight and the other part has different css.

I don't know how to want to highlight it. But it is up to you to calculate if node is inside or not. You have position and sizes of all nodes.

> If I have a preview page of this editor page, how can I make the preview page only display the content in the white Rect，but the content outside the rect hide in the stage?

When you export any node, you can control position and size of exported area.
