### ISSUE TITLE
how to fix yarn add react-konva konva run fail

### ISSUE THREAD

**Issue by markLabel9822** [konvajs/konva#1469]
Server Error
Error: konva tried to access canvas, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: canvas
Required by: konva@npm:8.3.14 (via /Users/nitithorn/Desktop/flow/frontend/.yarn/cache/konva-npm-8.3.14-37d7faf6ad-a14ace4b62.zip/node_modules/konva/cmj/)

Require stack:

/Users/nitithorn/Desktop/flow/frontend/.yarn/cache/konva-npm-8.3.14-37d7faf6ad-a14ace4b62.zip/node_modules/konva/cmj/index-node.js
/Users/nitithorn/Desktop/flow/frontend/.yarn/virtual/react-konva-virtual-0eb93ea69c/0/cache/react-konva-npm-18.2.3-225def8889-b18868527e.zip/node_modules/react-konva/lib/ReactKonva.js
/Users/nitithorn/Desktop/flow/frontend/.next/server/pages/workflow/builder.js
/Users/nitithorn/Desktop/flow/frontend/.yarn/virtual/next-virtual-b7d3d61fcc/0/cache/next-npm-12.1.6-c0598c390e-670d544fd4.zip/node_modules/next/dist/server/require.js
/Users/nitithorn/Desktop/flow/frontend/.yarn/virtual/next-virtual-b7d3d61fcc/0/cache/next-npm-12.1.6-c0598c390e-670d544fd4.zip/node_modules/next/dist/server/next-server.js
/Users/nitithorn/Desktop/flow/frontend/.yarn/virtual/next-virtual-b7d3d61fcc/0/cache/next-npm-12.1.6-c0598c390e-670d544fd4.zip/node_modules/next/dist/server/next.js
/Users/nitithorn/Desktop/flow/frontend/.yarn/virtual/next-virtual-b7d3d61fcc/0/cache/next-npm-12.1.6-c0598c390e-670d544fd4.zip/node_modules/next/dist/server/lib/start-server.js
/Users/nitithorn/Desktop/flow/frontend/.yarn/virtual/next-virtual-b7d3d61fcc/0/cache/next-npm-12.1.6-c0598c390e-670d544fd4.zip/node_modules/next/dist/cli/next-dev.js
/Users/nitithorn/Desktop/flow/frontend/.yarn/virtual/next-virtual-b7d3d61fcc/0/cache/next-npm-12.1.6-c0598c390e-670d544fd4.zip/node_modules/next/dist/bin/next

**Comment by maderesponsively** [comment]
In order to run konva in nodejs environment you also need to install canvas package manually. Konva will use it for 2d canvas API.

yarn add canvas
