### ISSUE TITLE
Automatically handle filters() array

### ISSUE THREAD

**Issue by albertogasparin** [konvajs/konva#147]
I've noticed that in order to use filters you have to first call `filters()`, passing an array of the filters you wish to use, and then call the specific filter setter. Is there any particular reason why the filter setter cannot handle it automatically?

So `blurRadius` could add `Konva.Filters.Blur` to the filters array if `blurRadius > 0` and the filter is not already added, plus it could handle the removal if `blurRadius == 0`.

I'm asking this because when I need to restore a Konva node object, filter values are not handled and I need to keep a map of every filter method / filter name in order to re-enable the correct one.

I'm also happy to contribute.

**Comment by lavrton** [comment]
Setters can do this. Better inner code of `Konva` will be complex in this case. And also, not all filters have special setters in Node. For instance `Invert` http://konvajs.github.io/docs/filters/Invert.html.

**Comment by lavrton** [comment]
And it is very easy to save and restore list of filters;

```javascript
function applyFilter(node, filterName) {
    const oldFilters = node.filters();
    const newFilters = oldFilters.concat(Konva.Filters[filterName]);
    node.filters(newFilters);
    
   const oldFilterNames = node.getAttr('filterNames') || [];
   const newFilterNames = oldFilterNames.concat(filterName);
   node.setAttr('filterNames', newFilterList);
} 


restoreFilters(node) {
    const filterNames = node.getAttr('filterNames') || [];
    const filters = filterNames.map(name => Konva.Filters[name]);
    node.filters(filters);
}
```

**Comment by albertogasparin** [comment]
That is more or less what I'm doing right now. 
I see your point on the `Invert` filter, by handling `filters` manually you can easily add your own even if it does not have a setters on the node. Thanks 😉 

What do you think about improving the `filters` API by adding also an `add` and `remove` methods? On simpler scenarios, instead of manipulating the array externally, we could call `addFilter(Filter)` / `removeFilter(Filter)`, leaving Konva taking care about duplicated filters, removal, concatenation, ...
It would be handy.

**Comment by lavrton** [comment]
Yes. It will be better API.

**Comment by lavrton** [comment]
I am closing this issue. But PR is welcome for some simpler API (with tests).
