### ISSUE TITLE
Make canvas (nodes) optionally opaque/transparent

### ISSUE THREAD

**Issue by flohall** [konvajs/konva#1470]
## Feature request
It would improve performance if (nodes) can be marked as "alpha: false". This might only apply if the node uses a canvas on its own because it's (the stage, a layer, cached, etc.)

In Konva it's not possible to tell the main canvas (either in the layer or stage object) that it should opaque and not render any alpha values. As it might be useful to cache some transparent nodes (which use offscreen canvas for buffering) - its important to explicitly mark only specific nodes as "alpha:false". This should improve drawing performance in the browser and in node-canvas.

### related issues
https://github.com/konvajs/konva/issues/132
https://github.com/konvajs/konva/pull/350

### Browser
> If your application uses canvas and doesn't need a transparent backdrop, set the alpha option to false when creating a drawing context with [HTMLCanvasElement.getContext()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext). This information can be used internally by the browser to optimize rendering.

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas#turn_off_transparency

### node-canvas

> RGB24 Like RGBA32, but the 8 alpha bits are always opaque. This format is always used if the alpha context attribute is set to false (i.e. canvas.getContext('2d', {alpha: false})). This format can be faster than RGBA32 because transparency does not need to be calculated.

https://github.com/Automattic/node-canvas

There was "moz-opaque" attribute in the past, which is deprecated:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/mozOpaque?retiredLocale=de

**Comment by lavrton** [comment]
Are there any performance tests for that online? `{ alpha: false }` vs `{ alpha: true }`. What is the difference? Is it significant?

**Comment by flohall** [comment]
Sadly I don't have any info about the significance. Just different source telling me that it can have a positive effect. (The ones I have linked.)
I could run some tests in the browser, but I am not 100% where I would to do the changes.
Why `canvas.getContext('2d');` is used in `Canvas.js` and in `Context.js` ? Why does `Canvas.js` has a function outside the class?
For me it seems I only would have to do the change in `Context.js` here I could hardcode in node_modules just to see if there are any differences.

**Comment by lavrton** [comment]
I just don't want to apply performance improvements, if they are too minor, and it may complicate code a lot.

You don't need to make a test with Konva. It will be good enough to have a demo with native 2d canvas API.

**Comment by flohall** [comment]
hm.. I have written a small script (without konva), but on my computer in chrome even with 6 * CPU throtteling it can consistently render 165 FPS on my screen. No matter if enable it or disable alpha. So my test doesn't challenge the hardware enough. Any ideas what would be an easy thing to have a better test for this?

    <!DOCTYPE html>
    <html>
    <body>
    
    <p id="res"> </p>
    
    <canvas id="myCanvas" width="960" height="540" style="border:1px solid #000000;">
    Your browser does not support the HTML canvas tag.
    </canvas>
    
    <script>
    var t, previousTime;
    var drawLoad = 1;
    t = previousTime = performance.now();
    
    var c = document.getElementById("myCanvas");
    var ctx = c.getContext("2d", {alpha:false});
    
    let i = 0;
    let base_image = new Image();
    
    function drawFrame() {
    
       let pos = (i % 960); 
       window.requestAnimationFrame(function(){

         ctx.fillStyle = "white";
         ctx.clearRect(0, 0, 960, 540);
         ctx.fillRect(0, 0, 960, 540);
         ctx.drawImage(base_image, pos, 0, 120, 80);
         
         ctx.drawImage(base_image, pos+50, 200, 120, 80);
        
         i++;

         if(i % 50 === 0) {
            t = performance.now();
     	    var elapsed = t - previousTime;
            var FPS = (1000/elapsed) * 50;
            var FPSRounded = Math.round(FPS);
            previousTime = t;
            document.getElementById('res').innerHTML = ("FPS: "+ FPSRounded);
    
         }
         drawFrame();
      
       });
    }
    
    
      base_image.src = 'https://kinsta.com/wp-content/uploads/2020/08/tiger-jpg.jpg';
      base_image.onload = function(){
  	    drawFrame();
      }
        
    </script>
    
    </body>
    </html>

**Comment by lavrton** [comment]
I adapted it to this https://jsbin.com/fogomudoho/1/edit?html,js,output
And I see no differences...
