### ISSUE TITLE
Support backdropFilter

### ISSUE THREAD

**Issue by MrHeer** [konvajs/konva#1474]
Hi, I love `konva` so much, It help me to develop a canvas editor, but I met a problem that I could't apply some filters to the backdrop of element.

I hope Support backdropFilter for `Node` like CSS [property](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter).

API

```
node.backdropFilters(filters)
```

If someone have some idea to help me, I will so happy to PR.

**Comment by MrHeer** [comment]
Yep, I hardly found any way to do that either. But this feature can provide a good design effect. I'm curious how figma implement this feature.

**Comment by lavrton** [comment]
They have their own custom WebGL renderer. Closing the issue for now, as I don't see any simple solutions with the current approach.
