### ISSUE TITLE
 How to make the border of the clipping function as the clipping edge?

### ISSUE THREAD

**Issue by miterwan** [konvajs/konva#1475]
Hello,i want to be a manga editor,I used the clipping function to make the comic border,but the canvas is centered and stroked,
The result is clipping in the bounding box，As shown below

![企业微信截图_e99e39f5-d4cf-493a-9f55-609b756d20e4](https://user-images.githubusercontent.com/29746948/211511341-159c9949-0d10-471d-a073-d6a852c81be9.png)

**Comment by miterwan** [comment]
Is there any way to do this cropping？
![企业微信截图_9d39dbe0-1895-47c4-8e3d-dd7a2fe6194d](https://user-images.githubusercontent.com/29746948/211511725-541ffa03-b40a-4e95-8bec-57787740839d.png)

**Comment by miterwan** [comment]
so...

**Comment by lavrton** [comment]
Can you make a minimal demo of what you are trying? Can you draw that black stroke on top?

**Comment by miterwan** [comment]
@lavrton Here is a demo:https://jsbin.com/kuyecovajo/edit?html,js,console,output

I hope the clipping area is within the border

**Comment by lavrton** [comment]
I think the only way is to calculate inner points by yourself with some math. I can't help here.
