### ISSUE TITLE
Add Property to Text When Text Being Cut Off / Wrapping Beyond Height

### ISSUE THREAD

**Issue by zschneider** [konvajs/konva#1479]
Hi there,

I'd like to dynamically resize text based on whether the text is wrapping beyond the height of the text, e.g., once the user types more text than can fit, the font size decreases.

To do this I need some sort of event to fire or attribute to check on the Text object. I found `_shouldHandleEllipsis()`, but that's always going to be false by the time I've gotten to it.  Is there an easier way to do this sort of thing?

Thanks!

**Comment by lavrton** [comment]
You can use `text.height('auto')` to set height automatically based on wrapping. You can use `text.height()` to get height value. Then adjust font size based on value. Possible solution:

```js

function fitTextToHeight() {
  // Set the initial font size
  var fontSize = 1;
  // set auto height for realtime adjustment
  text.height('auto');
  // Update the font size until the text fits within the maximum height
  text.fontSize(fontSize);
  while (text.height() < height) {
    fontSize += 1;
    text.fontSize(fontSize);

  }
  // set last good value
  text.fontSize(fontSize - 1);
  // restore height
  text.height(height);
}
```

https://jsbin.com/xetuzoyana/edit?js,output

**Comment by zschneider** [comment]
Thanks! Very cool. That worked for me.
