### ISSUE TITLE
pinch zoom and rotate ?

### ISSUE THREAD

**Issue by seekwe** [konvajs/konva#148]
Can be achieved

**Comment by psivanov** [comment]
What are the plans for implementing this - can we expect it sooner rather than later?

**Comment by lavrton** [comment]
@psivanov personally, I don't have any use cases of gesture events. And probably if I will - I will use something on top of `Konva` stage (like http://hammerjs.github.io/). Gestures are complex, and currently, I don't see simple implementations inside `Konva`.

**Comment by EugeneSqr** [comment]
Could you guys explain why Konvajs prevents default browser behavior on pinch? 

I can zoom in and out by pinching [an ordinary canvas](https://jsfiddle.net/broux00/n2EYw/), however [with Konvajs](http://jsfiddle.net/br1g5knj/5/) nothing happens.

**Comment by lavrton** [comment]
@EugeneSqr Probably this link will explain: http://konvajs.github.io/docs/events/Mobile_Scrolling.html

**Comment by EugeneSqr** [comment]
@lavrton Thanks! That's exactly what I was looking for.

**Comment by lavrton** [comment]
Just made experimental support here: https://konvajs.org/docs/sandbox/Gestures.html
