### ISSUE TITLE
How to make the Group rotate around the center

### ISSUE THREAD

**Issue by EmilyHOC** [konvajs/konva#1481]
I put the basic graphics into the group, and I want them to rotate around the center of the group, and see all the elements as a whole,group is just like a rect paper

**Comment by lavrton** [comment]
What did you try?

**Comment by EmilyHOC** [comment]
I want to put a lot of basic graphics together, and then the overall rotation and scaling into an area of ​​a specified size, pay attention to the overall rotation and scaling

**Comment by LisovJC** [comment]
faced with the same problem, has there been a solution?

**Comment by lavrton** [comment]
Provide a demo with your example. The group has its own position and origin. Depending on the structure of your group, you may need to change position too, to rotate the group around its "center".  You may read this post: https://konvajs.org/docs/posts/Position_vs_Offset.html#sidebar It may help a bit to understand it.

Also remember that group (and any other shape) rotates around its origin. It is x, y position. You can use it as its visual center.
