### ISSUE TITLE
Is there a way to customize the mouse button used to drag shapes/stage?

### ISSUE THREAD

**Issue by leonardoraele** [konvajs/konva#1483]
I want to replicate the behavior of apps like Miro, where the user can drag individual objects with one mouse button but can also drag the entire canvas with another mouse button.

I was able to replicate this behavior by re-implementing the drag and drop feature using only mouse events, (i.e. detecting `mousedown` and  `mouseup`, checking `mouseEvent.evt.button` to identify the button being used, and updating the shape position on `mousemove`, if the right button button is used for the event target) but now I'm wondering if it could have been done with Konva's `draggable` property.

Is it possible to customize Konva's default behavior so that a `draggable` shapes or stage are only draggable when the correct button is used?

I want something similar to this:
```js
new Konva.Rect({ draggable: event => event.button === 1 }) // Rect is only draggable if the event was initiated with the correct button
```

**Comment by lavrton** [comment]
Something like this may work:

```js
Konva.dragButtons = [0, 2];

stage.on('dragstart', (e) => {
  // if user is trying to drag not a stage
  // and not the left button is used
  if (e.evt.button === 2 && e.target !== stage) {
    // then stop that drag
    e.target.stopDrag();
    // and instead start stage dragging
    stage.starDrag();
  }
})
```
