### ISSUE TITLE
Layer's hitCanvas slightly 'tinted' in Brave; breaks getIntersection()

### ISSUE THREAD

**Issue by jez9999** [konvajs/konva#1484]
**UPDATE: you don't even need my repro for this, it seems.  Just visit the Konva website and most of its demos will get randomly broken unless Brave shields are turned off for the site.**

I've come across a very weird bug, and I think I've tracked it down to the fact that Brave is reporting pixel colours *slightly* different from what Konva expects for the hitCanvas layer.  Because of this, getIntersection on the layer doesn't match the shape.  I'm pretty sure this is because of Brave's 'block fingerprinting' "feature" which is turned on by default.  The reproduction is at:

https://mystikazetest.gooeysoftware.com/play

Open the console and note the verbose output (you need to click/drag the green circle in the top/right over the top-right hex):

![konvabug](https://user-images.githubusercontent.com/793830/213177437-94e348f1-1792-453f-a6dc-10c19790ed17.gif)

Firstly, my code is outputting the result of `layerBg.hitCanvas.context.getImageData(pos.x, pos.y, 1, 1).data` and you can see that the RGBA is 0,1,1,0 - I think this should be 0,0,0,0 for areas of the hitCanvas that are empty of shapes.  Brave appears to be slightly "tinting" the colour (possibly some kind of watermarking??)

Then, when it is dragged over the hex (this bug doesn't always reproduce, you may need to reload the page a few times), the code outputs `shp [unspecified]` when `getIntersection` should be matching a shape at that point.  This seems to be because the hitCanvas pixels are *slightly* different from what Konva is expecting.  In the example, Konva expected `#91c575` for the hex shape in the top-right corner (that's what it was keyed against in the `shapes` object), but the colour code it got back for that pixel on hitCanvas was `#90c475` - slightly different.  This totally breaks shape detection with getIntersection.

After some further investigation I think this happens in Brave, sadly with its default settings, which include "Block fingerprinting" as standard by default.  When that's disabled, this appears to be fixed.  Still, Brave (and perhaps some other browsers that do similar things) is going to break all Konva sites by default (this isn't a setting you turn on), and it's a relatively widely-used browser.  I admit that I think Brave should turn this off by default, but given that they don't perhaps there's a way to make Konva's hit detection slightly more "loose" in terms of colour matching so that the Brave anti-fingerprinting stuff doesn't totally break it?

Another idea: perhaps when creating a layer, Konva should do `layer.hitCanvas.context.getImageData(0, 0, 1, 1).data` and if the value is anything but 0,0,0,0, it should give a big red warning in the console that you're probably using an "anti-fingerprinting" browser like Brave that will probably break this Konva site, and that for Brave, you need to "turn off shields"?  I mean, this took me 2 days to figure out so average users might never discover why stuff is broken.

**Comment by jez9999** [comment]
Now that I know it's Brave screwing things up (grr), I see that the issue has already been [addressed](https://github.com/konvajs/konva/issues/1132#issuecomment-1273565082).  As I didn't see a warning in the console, I'm assuming it hasn't been added yet.  I suggest it be added to avoid people in future having to waste time figuring out what the problem is.

**Comment by lavrton** [comment]
From konva version 10.0.10 it should work better. It will use a bit different hit color logic to handle canvas farbling.
