### ISSUE TITLE
Drag and drop not working with Firefox

### ISSUE THREAD

**Issue by BluByte** [konvajs/konva#1486]
I am experiencing an odd bug with Firefox Ver 109.0 (Win 64 bit). Drag and drop does not work anymore, any interaction with the canvas is extremely slow.
I rememeber it was working a few months ago, I wonder if this is a Firefox or a Konva JS issue.

I see that also click events are not detected with Firefox.

Everything works smoothly with Chrome or Safari.

I have tested with https://konvajs.org/docs/drag_and_drop/Drag_Events.html

Also I have checked Polotno demo and it is inusable.

**Comment by BluByte** [comment]
I add one more detial: Firefox Developer 110.0b3 (Win 64 bit) works smoothly.

**Comment by lavrton** [comment]
Most likely, Firefox broke `context.getImageData()` function. That function should return pixel at specific space and canvas. And it should be 100% the same as what used to fill that area.

The only hope from konva side is that fixed version from Firefox Developer will be moved to the main version.

**Comment by BluByte** [comment]
I found that choosing "Refresh Firefox" in the uninstall procedure of FireFox fixed the issue. I really don't know where is the magic there. At least the issue seems solved now! 

I guess ticket can be closed.
