### ISSUE TITLE
Correctly mirror the group and all the elements inside it

### ISSUE THREAD

**Issue by LisovJC** [konvajs/konva#1487]
When rotating a group by 90 or 270 degrees and mirroring it with scaleX or scaleY, the elements inside it and it itself move out and are not displayed correctly. If you set offsetx and offsetY for a group, then only the main rectangle is normally displayed, the text or other elements inside the group still break.
![image](https://user-images.githubusercontent.com/93536115/214765011-24fbda6d-d878-4be2-8999-ba08ea6050fa.png)

**Comment by lavrton** [comment]
Can you make a demo?

**Comment by LisovJC** [comment]
> Можете ли вы сделать демо-версию?
Unfortunately not :с
