### ISSUE TITLE
the cornerRadius of the image component have no effect in "react-konva": "17.0.2-6"

### ISSUE THREAD

**Issue by AnnaHuangPro** [konvajs/konva#1489]
the version is

```
"react": "^17.0.2",
"react-dom": "^17.0.2",
"konva": "^7.2.5",
"react-konva": "17.0.2-6"
```

Looks like it's not implemented, is there another way to solve it ?
(Because of the react version we cannot upgrade, so the latest version of konva we can use is  ^7.2.5 )

there is a demo you can try
https://codesandbox.io/s/small-violet-e8qldp?file=/src/index.js

thanks for your apply~~

**Comment by lavrton** [comment]
https://stackoverflow.com/a/75278601/512042
