### ISSUE TITLE
Konva doesn't update hit graph in time when destroying dragged object

### ISSUE THREAD

**Issue by jez9999** [konvajs/konva#1490]
Repro (slightly modified version of the konva website's circle stress test with extra logging): https://game-point.net/misc/konvatest/
Capture of bug:
![firefox-perf](https://user-images.githubusercontent.com/793830/215344837-b08df3cc-2d10-4f2c-89e9-30f22b307357.gif)

When you set up draggable objects on Konva of a reasonable size, and you setup a `dragend` event on the stage containing the layer for the objects, where the target object gets destroyed in the `dragend` event, it can cause Konva to process methods like `_pointermove` (in Stage.js) before the layer's hit graph has been updated.  In the example given above, it tends to happen if you click, drag, then let go of the mouse button while the mouse cursor is still moving.

Because the shape has been destroyed, `_pointermove`'s call to `getIntersection` causes a full spiral search to happen on the hit graph until it reaches the pixel outside of the destroyed shape, because the shape's colour has been removed from `shapes[HASH + colorKey];`.

In Chrome, this is not noticeable because `this.hitCanvas.context.getImageData()` is almost instant but for some reason, this function runs *extremely* slowly in Firefox by comparison, taking about 10ms to run each time.  This means that, in Firefox, this full spiral search can cause the UI to hang for seconds - the larger the destroyed shape, the bigger a search it needs.  See how long the purple circle takes to disappear in the above example.

I've even tried doing an explicit layer `draw()` after the `destroy()` but the problem seems to persist; presumably this is a race condition.

**Comment by jez9999** [comment]
As an aside, Konva seems to just call `getImageData` a lot in general which, as I mentioned, is very very very slow in Firefox.  No idea why, but it is.  Perhaps [this](https://github.com/konvajs/konva/issues/293) idea of caching should be revisited.

**Comment by lavrton** [comment]
Can you make a real demo that shows incorrect behavior? I don't understand how it affects real events flow. 

I assume data in the next `mousemove` event will be not correct, but I am not sure.

**Comment by jez9999** [comment]
What's wrong the demo I linked?

In terms of the data being correct, it usually happens to be correct at the moment, it just causes a big delay in Firefox because `getIntersection` is doing a spiral search for a deleted shape on the hit canvas until it reaches the edge of that deleted shape, and thus a transparent pixel.  If the hit canvas had been updated at the right time, it wouldn't have that deleted shape there and would immediately get a transparent pixel.

**Comment by lavrton** [comment]
I just don't understand how to reproduce the issue on your demo. There are too many logs on it.

**Comment by jez9999** [comment]
The screenshot shows it being produced.  In firefox, open the console, then drag a circle and release the mouse cursor while the mouse is moving along.  Often, the bug will happen and there will be a big delay, with a high value for `getIntersection` like `getIntersection WHILE 40` or something.  That means the spiral search is going out 40 pixels to find a transparent pixel on the hit canvas, because it find the deleted shape's pixel on the hit canvas but it's been deleted from `shapes[]`.  Firefox is so slow to return `getImageData` that, on my reasonable laptop, it causes a delay of maybe 2 seconds.
