### ISSUE TITLE
react-konva throws the following error on console > setRotationDeg is deprecated

### ISSUE THREAD

**Issue by nakulsolanki** [konvajs/konva#1491]
I followed a simple example to rotate a rectangle using react-konva and received the following message on browser console.
Konva error: "setRotationDeg" method is deprecated and will be removed soon. Use ""setRotation" instead. 

Are there plans to update the react-konva library?

**Comment by lavrton** [comment]
`react-konva` is just a wrapper on top of `konva`. Instead of `rotationDeg` property, you may need to use `rotation` instead.

IF you still have an issue, make a small demo.
