### ISSUE TITLE
Help , How to achieve the inner shadow of a line ？just like this

### ISSUE THREAD

**Issue by lence-wl** [konvajs/konva#1492]
<!DOCTYPE html>
<html>
    <style type="text/css">
        canvas {
            border: dashed 2px #ccc;
        }
    </style>
    <script type="text/javascript">
        function $$(id) {
            return document.getElementById(id)
        }
        function pageLoad() {
            var can = $$("can")
            var ctx = can.getContext("2d")
            ctx.globalCompositeOperation = "source-out"
            ctx.beginPath()
            ctx.beginPath()
            ctx.moveTo(300, 300)
            ctx.lineTo(750, 300)
            ctx.quadraticCurveTo(800, 300, 800, 350)
            ctx.lineTo(800, 450)
            ctx.quadraticCurveTo(800, 500, 750, 500)
            ctx.lineTo(300, 500)
            ctx.lineCap = "round"
            ctx.shadowBlur = 12
            ctx.lineWidth = 20
            ctx.shadowColor = "#fff"
            ctx.fillStyle = "#CCC"
            ctx.strokeStyle = "#CCC"
            ctx.stroke()
        }
        window.onload = function () {
            pageLoad()
        }
    </script>
    <body>
        <canvas id="can" width="1000px" height="1000px"></canvas>
    </body>
</html>

**Comment by lavrton** [comment]
Can you make a clear online demo and image sample?
