### ISSUE TITLE
Adjust objectPosition on react-konva Image

### ISSUE THREAD

**Issue by jonrrivera** [konvajs/konva#1496]
Hey!

Thanks for the great library. I is there anyway to set the `objectPosition` property of the Image component in react-konva?

I am looking to set an image inside a square like so, but the image continued to render stretched:

`
		<Group>
			<Image
				ref={ref}
				objectFit='cover'
				image={image}
				height={180}
				width={180}
				x={posX}
				y={posY}
			/>
		</Group>
`

please help, thank you!!

**Comment by lavrton** [comment]
Hello. It is not supported as part of the library. And for now, I don't have plans to do that.

But you can do that by yourself using `cropX`, `cropY`, `cropWidth` and `cropHeight` attributes. You just need calculate them based on original image size and shape size. For demo: https://konvajs.org/docs/sandbox/Scale_Image_To_Fit.html
