### ISSUE TITLE
Feature Request: Konva DevTool

### ISSUE THREAD

**Issue by yinguangyao** [konvajs/konva#1498]
Canvas debugging is very troublesome. Konva already supports bounding boxes, which can easily implement debugging DevTool.

I have implemented a devtool, if the community needs it, I can optimize the code and open source it.

It supports mouse hover to preview shape information, supports modification of shape information and real-time rendering.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/16210045/216822322-b4179efd-9118-4edd-b029-d256cb82aad6.png">

**Comment by lavrton** [comment]
That looks really awesome. Please share your work.

**Comment by yinguangyao** [comment]
@lavrton I'm thinking, is this devtool integrated in the konva project? Or create a new project?

**Comment by yinguangyao** [comment]
@lavrton I created a project.
https://github.com/yinguangyao/konva-devtool

**Comment by lavrton** [comment]
Can you add full installation steps? Is it like Chrome extension?

**Comment by yinguangyao** [comment]
@lavrton It's a Chrome extension, and I've supplemented the installation and usage docs.

Also released the Chrome Web Store, waiting for approval.

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/16210045/217722540-21d5900c-162f-432e-841d-d4635a76196a.png">

**Comment by yinguangyao** [comment]
Now it has been released to the chrome app store.

https://chrome.google.com/webstore/detail/konva-dev-tool/liddfplammjmpepmjkokfmgemohhhnnm?hl=zh-CN

**Comment by lavrton** [comment]
Instead of reading `__canvas_instances__`. Can you instead just read global `Konva.stages` object? It has all current stages on the page and all its children. So the extension will work without any user changes in the code.

**Comment by yinguangyao** [comment]
Well, this does make it easier to use. I've changed to reading `Konva.stages` directly.

**Comment by lavrton** [comment]
I tried to install it. But I don't understand how to use it. I don't see any additional panels.

**Comment by yinguangyao** [comment]
Did you install from the git repository? Is there a `Konva` variable globally?

**Comment by lavrton** [comment]
I tried it from Chrome App store. `Konva` is available globally.

**Comment by yinguangyao** [comment]
Since the plugin of the chrome store has not been updated, it has been under review. You can use the github repository.

**Comment by lavrton** [comment]
@yinguangyao hello. I just tried the dev tools. Looks like it was updated in Chrome. And I really like how it works. Are you interested in moving your repo into `konvajs` organization? Do you plan to improve the extension and continue development?

**Comment by yinguangyao** [comment]
@lavrton Yes, I am very interested and plan to continue to improve the extension, how to migrate to the organization?

**Comment by lavrton** [comment]
I added you to org. Please let me know if you can migrate it.

**Comment by yinguangyao** [comment]
Thanks, I've migrated it
