### ISSUE TITLE
Feature: allow layers to specify events to listen to

### ISSUE THREAD

**Issue by jez9999** [konvajs/konva#1499]
Right now, Konva adopts an all-or-nothing approach to layers listening for events, passing in a `listening` config setting when being created.  So if you need to listen on a layer at all, all the events are generated.  This includes all the mousemove/pointermove events, which call `getIntersection` and therefore `getImageData` on each mousemove.  Because Firefox's `getImageData` is very slow, this makes the UI seem rather sluggish in Firefox and increases CPU usage a lot.

It would be nice if `listening` could take a list of events to which the layer would subscribe.  If that didn't include mousemove/pointermove, Konva would not try to call `getIntersection` on each mousemove and the UI could be sped up significantly, whilst still allowing the layer to listen to events it may need such as pointerdown or click.

**Comment by yinguangyao** [comment]
I also encountered the same problem. Here I share my solution.
The events can be disabled when the mousemove is triggered, and the event can be enabled after the mousemove trigger stops.

```js
private mousemove() {
  this.disableEventListening();
  // your code
}

private disableEventListening() {
    this.layer.listening(false);
    this.resetListenAfterScroll();
  }

  @debounce(50)
  private resetListenAfterScroll() {
    this.layer.listening(true);
  }
```

**Comment by lavrton** [comment]
I don't see how to make a good API design for that.

**Comment by jez9999** [comment]
Couldn't `new Konva.Layer( { listening: ... } )` be able to take an array of strings instead of a boolean, specifying the names of the events to subscribe to?

**Comment by MNeverOff** [comment]
This here, when using `react-konva` especially, would be a wonderful convenience feature. From API design standpoint I get your reservations, @lavrton, looking at the source, listening is a very foundational property and changing it's behaviour would be a massive pain.

Having said that, being able to set `listening` not only to `boolean` but also to an object `ListeningConfig` with properties defining which of the events to listen to / raise, could be beneficial, as opposed to manually going through them with `e.preventDefault()` except for the one that would be of interest. But I realise that it's not a popular or frequent ask.
