### ISSUE TITLE
About performance optimization

### ISSUE THREAD

**Issue by bhabgs** [konvajs/konva#1500]
> I'm using konva as a configuration tool, It's a very good tool. there are still some problems in my use.

## problem
>The function I implemented was，As the main Stagemoves, let 'scale Stage''s canvas move as well. `setAttrs{x,y}`
* cache code
![image](https://user-images.githubusercontent.com/19221378/216882606-d3173f8a-5ea6-4b31-9a60-6efe066dd044.png)

* fps low
![image](https://user-images.githubusercontent.com/19221378/216882388-07cee5e3-fc05-48b0-a70b-e03ced31a954.png)

## information
1. cpu : Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz   3.79 GHz
2. ram : 32.0 GB
3. system type :  64
4. cpu : RTX 3060ti

##  hope
How can I improve the performance of 'scale Stage'

**Comment by yinguangyao** [comment]
I recommend against using clone to create new shapes, clone brings some performance loss.

You can create it like this:
```js
const clConfig = {
  points: [],
 // ...
};

const cloneLine = new Line({ ...clConfig, { points: [x, 2, x, thickness ] }});
```

**Comment by bhabgs** [comment]
> I recommend against using clone to create new shapes, clone brings some performance loss.
> 
> You can create it like this:
> 
> ```js
> const clConfig = {
>   points: [],
>  // ...
> };
> 
> const cloneLine = new Line({ ...clConfig, { points: [x, 2, x, thickness ] }});
> ```

第一个版本是没有使用克隆的，性能对比差不多。

**Comment by yinguangyao** [comment]
> > I recommend against using clone to create new shapes, clone brings some performance loss.
> > You can create it like this:
> > ```js
> > const clConfig = {
> >   points: [],
> >  // ...
> > };
> > 
> > const cloneLine = new Line({ ...clConfig, { points: [x, 2, x, thickness ] }});
> > ```
> 
> 第一个版本是没有使用克隆的，性能对比差不多。

其实没太理解性能问题是什么场景下的？滚动的时候？还是？

**Comment by bhabgs** [comment]
> 

需求是: 主舞台移动后，刻度也会随之变化。
我实现的思路是：
``` js
const moveStageByCanvasOffset = () => {
  const { x, y } = mainStage.position();
   scaleX.setAttrs({ x });
    scaleY.setAttrs({ y });
}
mainStage.on("dragmove", (e) => {
      if (e.target === stage) {
        n ? clearTimeout(n) : null;
        n = setTimeout(() => {
          moveStageByCanvasOffset();
        }, 1);
      }
    });
```

**Comment by bhabgs** [comment]
是屏幕刷新率影响了 我的使用体验，并不是性能问题。因为用我的mac就完全没有问题。问题只出现在pc端。
