### ISSUE TITLE
Help aligning objects rendered using KONVA

### ISSUE THREAD

**Issue by davesargrad** [konvajs/konva#1501]
I'm a bit new to Konva. Currently I have a canvas that I'm rendering rectangles on. 

The  two rectangles that you see in the following should overlap exactly (they have the same width/height/x/y). I use the pink rectangle to drag and drop the overall structure. I then maintain the object detail (that allows me to render the handles and the rectangles) in a backing redux store. Basically I render the two rectangles and the four green handles everytime I compute a change of the position (of the pink rectangle), or a change of size (when I drag the green handles). For some reason the rendered pink rectangle "leads" the rest of the objects, (and hence they dont catch up, with every drag, though if I drag slow they stay largely aligned). 

![image](https://user-images.githubusercontent.com/48793689/217052934-37bab9b6-c4e7-4b0e-9956-84ac44b0e339.png)

I also have a means to bound the rectangles (when the dragged shape reaches the edge), but the pink rectangle doesnt respect those boundaries.

![image](https://user-images.githubusercontent.com/48793689/217053326-f16a5960-a79a-4b71-b202-e621249bf6ab.png)

This is how it pretty much should always look (though even here you will see that the second rectangle is shifted slightly):
![image](https://user-images.githubusercontent.com/48793689/217053420-cbe2f644-4ec3-4611-8de9-c65fee7db63c.png)

I'll post code if it helps, but currently its in a form that will not be easy to post. I thought the description might trigger an idea for me to try.

Thanks in advance for any thoughts on this.

**Comment by lavrton** [comment]
https://github.com/konvajs/react-konva/issues/730
