### ISSUE TITLE
bug: drag is ended prematurely. example included

### ISSUE THREAD

**Issue by nabati** [konvajs/konva#1509]
In this [Codesandbox](https://codesandbox.io/s/startdrag-automatically-stops-forked-z226df), I am explicitly calling startDrag on mousedown to start panning the stage. 

If I, 
- mousedown, move the mouse around, and mouseup, then the stage seems to stop dragging on mouseup.
- mousedown, mouseup, then move the mouse around, then the stage seems to keep dragging until you press mousedown again. 

I haven't called stopDrag at any point here explicitly, so I would expect the stage to keep dragging until I do. 

This seems like a bug to me. Please advise :)

**Comment by lavrton** [comment]
What exactly is not expected to you? I don't get it.

To me, the second case looks like a bug. Because mouseup should stop dragging.

**Comment by nabati** [comment]
For the first case; 

> mousedown, move the mouse around, and mouseup, then the stage seems to stop dragging on mouseup.

Here, I am triggering startDrag programmatically, but I am never triggering stopDrag, so I would not expect konva to disable dragging on mouseup.

**Comment by lavrton** [comment]
This is intentional. Pointer up will stop dragging.

**Comment by mageprashant** [comment]
Hi @lavrton 

Do I need to drag and drop in specific areas? so is it possible?

https://jsfiddle.net/0cdw3ya7/21/

**Comment by lavrton** [comment]
@mageprashant I don't understand your question.
