### ISSUE TITLE
mousemove is not fired while stage is dragging

### ISSUE THREAD

**Issue by nabati** [konvajs/konva#1510]
As a user, I expect mousemove to fire when the mouse is moving. 

If you move the cursor around the stage here, the `mousemove` event is firing, but if you start dragging the stage, then the `mousemove` event stops firing. 

Also, when you move the circle, the `mousemove` event stops firing. 

I think there are two cases here; 
1. When the stage is being dragged. It might be the case that since the relative position is not being changed, you think `mousemove` should not be fired. This might be the case, but it's not immediately obvious that that's how it would work.
2. When a node within the stage is being dragged. This seems like a bug - I would expect `mousemove` to be fired. 

https://codesandbox.io/s/mousemove-while-dragging-8w9lec?file=/src/index.js

![Recording 2023-02-14 at 07 56 36](https://user-images.githubusercontent.com/1499050/218662090-6e272a1a-ed13-4793-9138-9fc5b17fbf2a.gif)

![Recording 2023-02-14 at 08 06 48](https://user-images.githubusercontent.com/1499050/218664006-90f77846-3916-4a85-9a3e-1a2099b47a0b.gif)

**Comment by lavrton** [comment]
It is done for performance reasons. If you want to enable full events on drag you can use this:

```js
Konva.hitOnDragEnabled = true;
```
