### ISSUE TITLE
How do I put rotation in the "bottom-right" in react?

### ISSUE THREAD

**Issue by linxianxi** [konvajs/konva#1512]
@lavrton  like this, I looked at the documentation and Googled it to no avail. This is easy to do if I use fabricjs.
<img width="301" alt="WeChat1786004855aa21e45bd1a8cbc85f5bf9" src="https://user-images.githubusercontent.com/47104575/218942964-4be46045-bcec-4cbf-972e-32b82ebe242c.png">

**Comment by lavrton** [comment]
Currently, there is no API for that for `Konva.Transformer` object. Instead, I suggest implementing that by yourself with several shapes.

**Comment by linxianxi** [comment]
can you show me a example?
