### ISSUE TITLE
Konva `Join Discord` link is expired

### ISSUE THREAD

**Issue by sohamsshah** [konvajs/konva#1516]
I would like to join discord, like thousand other developers to ask questions related to Konva. Please share the Discord Invite link, I can raise a PR for it.
<img width="773" alt="image" src="https://user-images.githubusercontent.com/47717492/219556816-f469582f-ad9f-4be7-acb6-64b20ac305c3.png">

**Comment by lavrton** [comment]
Hmmm... Just tested it and it works ok...
