### ISSUE TITLE
In konva why the color is uneven when use fillLinearGradientColorStops api to draw a diagonal line in rect

### ISSUE THREAD

**Issue by huyong007** [konvajs/konva#1517]
*The Scenes:*

I use konva to draw a diagonal line in a rect, the rect api fillLinearGradientColorStops meet my need , when the value of fillLinearGradientColorStops Array length is smaller 200,the line is normal , but when length become bigger than 200, the lines become different color ,some lines is dark red some other is light red;

how to fix this error to make when length is 1000 the diagonal line color is same

```js
const colors = [];
const length = 500;
Array(length).fill(0).map((_, index) => {
    const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    colors.push(index * 0.002, arr.includes((index * 0.02)) ? "red" : '#fff')
})

const layer = new Konva.Layer();
const rect1 = new Konva.Rect({
    x: 120,
    y: 20,
    width: 100,
    height: 200,
    fillLinearGradientStartPoint: {
        x: 0,
        y: 0
    },
    fillLinearGradientEndPoint: {
        x: 100,
        y: 200
    },
    fillLinearGradientColorStops: colors,
    stroke: "black"
});

```
![image](https://user-images.githubusercontent.com/30817245/219583785-d3bd343a-f130-4d2e-95b3-e29b64e88a90.png)

[stackoverflow](https://stackoverflow.com/questions/75459021/in-konva-why-the-color-is-uneven-when-use-filllineargradientcolorstops-api-to-dr)
 [this is a sample with detailed code](https://codesandbox.io/s/heuristic-chatelet-x6pzd4?file=/src/index.js)

**Comment by lavrton** [comment]
There is nothing much we can do from the Konva side. This is how the browser renders it. You can compare results in Firefox and Safari. You will see it is different from Chrome.

I think some of your lines get lighter because their size is too small.

**Comment by huyong007** [comment]
> There is nothing much we can do from the Konva side. This is how the browser renders it. You can compare results in Firefox and Safari. You will see it is different from Chrome.
> 
> I think some of your lines get lighter because their size is too small.

ok ,thank you for you reply
