### ISSUE TITLE
can you add a interface to set layer's INTERSECTION_OFFSETS

### ISSUE THREAD

**Issue by DMIAOCHEN** [konvajs/konva#152]
when in mobile, i draw a line that with 2px stroke width, and set draggable to true, then when i drag it, it always very hard to trigger the drag event, i think if there has any interface to set INTERSECTION_OFFSETS, and increase the rang, it will be better.

**Comment by lavrton** [comment]
I don't think it will help. You touch a screen at some `{x,y}` point. If there is no shape in {x,y} position - no dragging.

To fix the issue you can define custom `hitFunc` with higher strokeWidth. Or you can create draggable group with visual line inside and transparent bold hit line: http://jsbin.com/xowiba/edit?js,output

**Comment by DMIAOCHEN** [comment]
thanks, lavrton! you are right!
