### ISSUE TITLE
Support css zoom property

### ISSUE THREAD

**Issue by yinguangyao** [konvajs/konva#1520]
When I set the `zoom` property, the page will zoom accordingly. But th size obtained through `getBoundingClientRect` has not changed.

for example：
```js
.konvajs-content {
  zoom: 1.5;
}
```
 
`this.content.getBoundingClientRect().width / this.content.clientWidth` result is always 1。

Is it possible to support passing configuration items in the form of `Konva.scaleX` and `Konva.sclaeY`?

**Comment by lavrton** [comment]
Hello. I need more info about the issue. I don't understand it.
