### ISSUE TITLE
Dragging triggers bugs when pages have zoom properties

### ISSUE THREAD

**Issue by fhao07** [konvajs/konva#1521]
recurrence step：
![image](https://user-images.githubusercontent.com/63383235/220863697-381c1af0-8f14-4b38-b75b-68adc4be7e65.png)
![image](https://user-images.githubusercontent.com/63383235/220866039-7c9d04dd-354a-4475-a0d3-2dfc33f36eb4.png)
Then the elements on the page cannot be dragged

**Comment by lavrton** [comment]
Zooming/transforming canvas is not supported by Konva.
