### ISSUE TITLE
bug: when i mirror shape horizontally,the attrs get through transform is wrong, and the transformer rotated 180 degrees by mistake

### ISSUE THREAD

**Issue by wyyx50** [konvajs/konva#1522]
I refer to this link to mirror shape horizontally:
https://konvajs.org/docs/sandbox/Mirror_Canvas_Shape.html#Is-it-possible-mirror-shapes-vertically-or-horizontally
I don't need animation effects, so I don't use the to method, I use the setAttrs method.
I have initially implemented this function ，But I found that the transformer rotated 180 degrees by mistake，And the attribute obtained through getTransform().decompose() is also wrong. This leads to the fact that when I open the canvas for the second time, the horizontal mirror elements based on these attributes cannot achieve the expected effect.
The following is a code example.
```
var width = window.innerWidth;
var height = window.innerHeight;

var stage = new Konva.Stage({
  container: 'container',
  width: width,
  height: height,
});

var layer = new Konva.Layer();
stage.add(layer);

var text = new Konva.Text({
  text: 'Text with the origin in its center',
  width: 200,
  align: 'center',
  y: 100,
  x: 270,
  fontSize: 30
});
layer.add(text);
// set horizontal origin in the center of the text
text.offsetX(text.width() / 2);

let transformer = new Konva.Transformer({
  type: "transformer",
  rotationSnaps: [0, 90, 180, 270],
  flipEnabled: false,
  enabledAnchors: ['top-left', 'top-right', 'bottom-left', 'bottom-right'],
  nodes: [text]
});
layer.add(transformer)

document.querySelector('#flip').addEventListener('click', () => {
  text.setAttrs({
	  scaleX: -text.scaleX()
  });
  
  console.log(text.getAttrs());
  let newAttrs = text.getTransform().decompose();
  console.log(newAttrs)
});
```
This is the initial state
![1677143934871](https://user-images.githubusercontent.com/35246460/220866308-eec31da1-06cc-4b17-b9ab-fef7e242fa10.png)

This is the changed state
![1677144034875](https://user-images.githubusercontent.com/35246460/220866633-5679ce4d-212a-4012-a2b1-facdb4c83ab3.png)

I just mirror the shape horizontally. Why does the transformer rotate 180 degrees

![1677144249745](https://user-images.githubusercontent.com/35246460/220867498-19611490-8f83-4702-9dc8-df6a904d25b8.png)

From the print information on the console, we can see that the scaleX value of text is - 1, but in the attributes obtained through text. getTransform().decompose(), the scaleX value is 1, scaleY is - 1, and rotation is - 180,Why is this!
After reading the source code of konva, I found that the rotation angle of transformer is also obtained through getTransform(). decompose() 
I need help

**Comment by wyyx50** [comment]
@lavrton  I need your help

**Comment by lavrton** [comment]
This is how transformer works. The workaround:

```js
const tr = new Konva.Transformer({
  nodes: [shape],
  useSingleNodeRotation: false
});
layer.add(tr);
tr.rotation(0);
tr.forceUpdate();
```
