### ISSUE TITLE
Poor performance with many Text that have width

### ISSUE THREAD

**Issue by Heymancn** [konvajs/konva#1524]
I'm testing the performance of text. In the case of text with width, too much text will cause performance problems.My code is as follows
code run finish cost long time
How can I optimize performance

`

    var width = window.innerWidth;
    var height = window.innerHeight;
    var stage = new Konva.Stage({
      container: 'container',
      width: width,
      height: height,
    });

    var layer = new Konva.Layer();
    stage.add(layer);
    var xCount = Math.floor(width / 50);
    var yCount = 265;
    var startTime = Date.now()
    var rect1;
    var textContent = "create a group which will be used to combine multiple simple shapes.  Transforming the group will transform all of the simple shapes together as  one unit" 
    let complexText2 = new Konva.Text({
      text: '',
      fontSize: 16,
      fontFamily: 'Calibri',
      padding: 0,
      align: 'center',
      shadowForStrokeEnabled: false,
    });
    layer.add(complexText2)
    stage.add(layer)
    complexText2.cache()
    for (let yIndex = 0; yIndex <= yCount; yIndex++) {
      for (let index = 0; index <= xCount; index++) {
        
        let clone = complexText2.clone({
          x: index * 30,
          y: yIndex * 30,
          text: textContent,
        });
        clone.cache();
        layer.add(clone)

      }
    }
    var tim1 = Date.now()
    console.log("code run finsh", (tim1 - startTime) / 1000, "s")
    layer.batchDraw();
    var tim2 = Date.now()
    console.log("konva draw finsh", (tim2 - tim1) / 1000, "s")

`

**Comment by D31T4** [comment]
Not caching the text will significantly reduce render time in this case. But you may still want to cache them if your layer is re-drawn frequently.
```javascript
var width = window.innerWidth;
var height = window.innerHeight;
var stage = new Konva.Stage({
  container: 'app',
  width: width,
  height: height,
});

var layer = new Konva.Layer();
stage.add(layer);
var xCount = Math.floor(width / 50);
var yCount = 265;
console.log(xCount, yCount)
var startTime = Date.now()
var rect1;
var textContent = "create a group which will be used to combine multiple simple shapes.  Transforming the group will transform all of the simple shapes together as  one unit" 
let complexText2 = new Konva.Text({
  text: '',
  fontSize: 16,
  fontFamily: 'Calibri',
  padding: 0,
  align: 'center',
  shadowForStrokeEnabled: false,
});
layer.add(complexText2)
stage.add(layer)
complexText2.cache()
for (let yIndex = 0; yIndex <= yCount; yIndex++) {
  for (let index = 0; index <= xCount; index++) {
    
    let clone = complexText2.clone({
      x: index * 30,
      y: yIndex * 30,
      text: textContent,
    });

    layer.add(clone)
  }
}
var tim1 = Date.now()
console.log("code run finsh", (tim1 - startTime) / 1000, "s")
layer.batchDraw();
var tim2 = Date.now()
console.log("konva draw finsh", (tim2 - tim1) / 1000, "s")
```

**Comment by Heymancn** [comment]
Even if `cache `is not used， it has consumed more than 30 seconds When the code runs to `console.log("code run finsh ", 1000, "s")`

**Comment by D31T4** [comment]
Create an example to reproduce your issue. Took <500 ms for me in this [sandbox](https://codesandbox.io/s/konva-issue-1524-n825nm?file=/src/index.js).

**Comment by yinguangyao** [comment]
Because it takes a lot of time to calculate text line breaks, it would be better if you could segment the text and cache the width of each word.

**Comment by lavrton** [comment]
Caching is a slow operation and consumer a lot of memory. You should not do it frequently for too many nodes. Instead, you can create one text node, convert it into an image (or canvas) and use images instead.

```js
const canvas = complexText2.toCanvas();

for (let yIndex = 0; yIndex <= yCount; yIndex++) {
  for (let index = 0; index <= xCount; index++) {
    let clone = new Konva.Image({
      image: canvas,
      x: index * 30,
      y: yIndex * 30,
    });
    layer.add(clone);
  }
}
```


I don't think there is much to do to optimize a lot of text nodes. Try to reduce the number of visible shapes on the stage.

**Comment by Heymancn** [comment]
> Caching is a slow operation and consumer a lot of memory. You should not do it frequently for too many nodes. Instead, you can create one text node, convert it into an image (or canvas) and use images instead.
> 
> ```js
> const canvas = complexText2.toCanvas();
> 
> for (let yIndex = 0; yIndex <= yCount; yIndex++) {
>   for (let index = 0; index <= xCount; index++) {
>     let clone = new Konva.Image({
>       image: canvas,
>       x: index * 30,
>       y: yIndex * 30,
>     });
>     layer.add(clone);
>   }
> }
> ```
> 
> https://codesandbox.io/s/konva-issue-1524-forked-prscd5?file=/src/index.js
> 
> I don't think there is much to do to optimize a lot of text nodes. Try to reduce the number of visible shapes on the stage.

Converting to image solved my problem.Thanks

**Comment by Heymancn** [comment]
Converting to images has greatly improved performance.Thanks. @lavrton
