### ISSUE TITLE
feat: canvas as Konva.Stage input argument

### ISSUE THREAD

**Issue by MentalGear** [konvajs/konva#1530]
## Use Case
As a developer, I would like to have a Konva-managed canvas (offscreenCanvas if available) that is only used for rendering.

## Suggestion
Since Konva doesn't yet support spawning an offscreenCanvas, I'd like to suggest an additional stage constructor argument which allows to provide an existing (offscreen) canvas to be used as the stage instead of spawning a new one.

Example:
```js
var stage = new Konva.Stage({
  canvas: canvasElement
});
```

**Comment by lavrton** [comment]
The problem is that the stage has no canvas. Only layers have canvas. Stage is just a div wrapper around layers. 

For offscreen, I had some experiments here: https://konvajs.org/docs/sandbox/Web_Worker.html#page-title

**Comment by MentalGear** [comment]
Thx, great experiment! Would be possible then to have new Layer({ offscreen: true }) ?
