### ISSUE TITLE
getting 504 error to get konva min js package library - https://unpkg.com/konva@7.0.0/konva.min.js

### ISSUE THREAD

**Issue by nikheelneelay** [konvajs/konva#1531]
We are using konva js version 7.0.0 in our angular project and referred in index html file 
`<script src="https://unpkg.com/konva@7.0.0/konva.min.js"></script>`
recently we started getting 504 gateway time out error in edge and chrome for this package-
![image](https://user-images.githubusercontent.com/16623762/223656026-8b123add-35e3-4ca0-8f3f-f44ed56cd645.png)
I believe the certificate has expired causing this error , can you please renew or advise otherwise?
![image](https://user-images.githubusercontent.com/16623762/223656371-3dfa99c0-6da3-4bef-bba4-01a1259c84f4.png)

**Comment by lavrton** [comment]
Maybe it is working ok now. It is CDN issue and out of my control.
