### ISSUE TITLE
After modifying Konvajs's stage.attrs.scaleX and scaleY, how can the canvas be updated in real time?

### ISSUE THREAD

**Issue by wenlongFam** [konvajs/konva#1537]
After modifying Konvajs's stage.attrs.scaleX and scaleY, how can the canvas be updated in real time?

Want to zoom in and out on the canvas.

`//zoomIn
    zoomIn() {
      stage.attrs.scaleX += 0.1
      stage.attrs.scaleY += 0.1
    },
    // zoomOut
    zoomOut() {
      stage.attrs.scaleX -= 0.1
      stage.attrs.scaleY -= 0.1
    },`

**Comment by lavrton** [comment]
Do not touch `node.attrs` property. It is not documented. Changing it directly may not work. Use methods instead:

```js
stage.scaleX(stage.scaleX() - 0.1);
stage.scaleY(stage.scaleY() - 0.1);
```
