### ISSUE TITLE
showing tooltip only if text overflows the node

### ISSUE THREAD

**Issue by skyboyer** [konvajs/konva#1538]
So I'm trying to display tooltip only for long text values which does not fit. 

Looked into https://github.com/konvajs/konva/blob/0a908286334c40bdad9c7926bbe3eb394ffb41cb/src/shapes/Text.ts#L413 but it does not seem to have any callback to be called or any even is triggered if/when text does not fit boundaries.

Neither have found a demo for that case. May I miss something obvious?

**Comment by lavrton** [comment]
Konva doesn't have API for that. But you can manually check `text.textArr` property. And compare it with `text` attribute.
