### ISSUE TITLE
when custom shape with class, how to extends property

### ISSUE THREAD

**Issue by SummerZYQ** [konvajs/konva#1540]
I demo it like src\shapes\Rect.ts, but  Factory.addGetterSetter is invalid.
 
https://codesandbox.io/s/konva-extend-test-forked-4587c7?file=/src/index.js

``` javascript

class CustomRect extends Konva.Rect {
  constructor(props) {
    super(props);
    console.log("creating...");
  }

  isSelected;
}
CustomRect.prototype.className = "CustomRect";

_registerNode(CustomRect);
Factory.addGetterSetter(CustomRect, "isSelected", false);

const rect = new CustomRect({});
console.log("rect.isSelected", rect.isSelected);
// rect.isSelected undefined, but should be function

```

**Comment by lavrton** [comment]
```js
import Konva from "konva";
import { _registerNode } from "konva/lib/Global";
// import { GetSet } from "konva/lib/types";
import { Factory } from "konva/lib/Factory";

class CustomRect extends Konva.Rect {
  constructor(props) {
    super(props);
    console.log("creating...");
  }
}
CustomRect.prototype.className = "CustomRect";

_registerNode(CustomRect);
Factory.addGetterSetter(CustomRect, "isSelected", false);

const rect = new CustomRect({});
console.log("rect.isSelected", rect.isSelected);
```

https://codesandbox.io/s/konva-extend-test-forked-ss4r4l?file=/src/index.js

**Comment by SummerZYQ** [comment]
for /Factory.ts#L17, it's can't define property in class.
https://github.com/konvajs/konva/blob/07df75606631b1213a8283fac77775357c6b6ede/src/Factory.ts#L17

why  Rect.ts is ok?
https://github.com/konvajs/konva/blob/07df75606631b1213a8283fac77775357c6b6ede/src/shapes/Rect.ts#L50

**Comment by Zonciu** [comment]
Use `declare isSelected: GetSet<boolean, this>;` instead of `isSelected: GetSet<boolean, this>;`
Because the instance member will override prototype member.
