### ISSUE TITLE
 RegularPoly   fill pattern image  can't fill.  only part of shap fill image

### ISSUE THREAD

**Issue by RobinYang11** [konvajs/konva#1541]
![image](https://user-images.githubusercontent.com/20513480/227128571-865c0ab6-afbd-4c90-85f5-818c842731f4.png)

**Comment by lavrton** [comment]
The origin of the Regular polygon is its center. So, by default, Konva starts to draw the pattern from the center.
You can move pattern with `fillPatternOffsetX` and `fillPatternOffsetY`
