### ISSUE TITLE
Drawing delay on mobile device

### ISSUE THREAD

**Issue by VegetaWithoutBle** [konvajs/konva#1542]
When drawing quickly on a mobile device, there will be a significant sense of delay, and some pixels appear to pop up suddenly. Is there any way to optimize this situation？

**Comment by VegetaWithoutBle** [comment]
https://konvajs.org/docs/sandbox/Free_Drawing.html

**Comment by lavrton** [comment]
For me, it works ok. You may have delays if you draw too many lines. For that case you need to think about caching.
