### ISSUE TITLE
features : Add text directly in form

### ISSUE THREAD

**Issue by Pierre-Portfolio** [konvajs/konva#1543]
I create a project or i need to add a text hover rectangle, circle or polygon.
it would have been much easier if we could directly add the text in the shape.

---------------------------------------
For exemple :

// Création d'une scène
var stage = new Konva.Stage({
  container: 'container',
  width: 500,
  height: 500
});

// Création d'une couche
var layer = new Konva.Layer();

// Création d'un rectangle
var rect = new Konva.Rect({
  x: 100,
  y: 100,
  width: 200,
  height: 100,
  fill: 'red',
  stroke: 'black',
  strokeWidth: 2
});

// Création d'un texte
var text = new Konva.Text({
  x: 0,
  y: 0,
  text: 'Mon texte',
  fontSize: 20,
  fontFamily: 'Calibri',
  fill: 'white'
});

// Ajout du texte au rectangle
rect.add(text);

// Ajout du rectangle à la couche
layer.add(rect);

// Ajout de la couche à la scène
stage.add(layer);
------------------------------------------------------

Thank you for this amazing project and for have taking the time to read my idea :)

**Comment by lavrton** [comment]
Thanks for the idea. That is out of Konva architecture. For that use case you can use groups. But rect into group and then text on top in the same group.

Also you can use labels.
