### ISSUE TITLE
bug: drop and dropover invalid

### ISSUE THREAD

**Issue by MarTuPoke** [konvajs/konva#1544]
"konva": "^8.4.3",
"vue-konva": "^3.0.2"

@drop and @dropover invalid
codesandbox: https://codesandbox.io/s/affectionate-cannon-uqu37t?file=/src/App.vue

Copy this example to vuejs to find the problem
https://konvajs.org/docs/sandbox/Drop_DOM_Element.html

**Comment by MarTuPoke** [comment]
https://github.com/konvajs/vue-konva/issues/55

**Comment by lavrton** [comment]
Konva doesn't have built-in support for drop or dragover. There is only `dragstart`, `dragmove` and `dragend`.
