### ISSUE TITLE
When drawing a high-resolution canvas, konva consumes too much memory

### ISSUE THREAD

**Issue by wyyx50** [konvajs/konva#1545]
Our application is a program for designing an album based on Electron implementation. Designing an album requires drawing multiple high-resolution canvases, and then exporting the canvases to high-definition images. Konva meets our needs well. However, during the export process, it was found that the memory occupied by the program was very high, reaching more than 3 gigabytes. Even when the destroy method provided by Konva was called after each drawing and export, the memory occupied was still very high.
Later, analysis found that even if you initialize an empty canvas without drawing any content, Konva still consumes a high amount of memory. We did an experiment using Konva to draw 10 5000 * 4000 resolution canvases, only writing a "hello word" on the canvas, and using Chrome to open the demo. In the C task manager, Chrome uses nearly 6GB of memory, while using native canvas to achieve the same effect, Chrome only uses over 200 MB of memory. Why does Konva occupy such a large amount of memory? Is there any good solution?
Here is the demo code

```
//Parent Component
<template>
	<div>
		<KonvaRender v-for="(item,index) in 10" :key="index"></KonvaRender>
		<!-- <NativeRender v-for="(item,index) in 10" :key="index"></NativeRender> -->
	</div>
</template>
<script setup>
	import KonvaRender from './components/konva-render.vue'
	import NativeRender from './components/native-render.vue'
</script>

//Konva Canvas Component
<template>
	<div class="konva-render">
		<div ref="wrap"></div>
	</div>
</template>
<script setup>
	import {ref,onMounted,} from "vue"
	import Konva from 'konva';
	
	onMounted(()=>{
		initCanvas()
	})
	
	let wrap = ref();
	let container;
	function initCanvas(width,height) {
		container = wrap.value;
		
		let stage = new Konva.Stage({
			container: container,
			width: 5000,
			height: 4000
		});
		
		let layer = new Konva.Layer()
		stage.add(layer);
		
		var text = new Konva.Text({
			fontSize: 80,
			font: "sans-serif",
			text: "hello word",
		});
		layer.add(text)
	}
</script>
<style scoped>
	.konva-render{
		width: 400px;
		height: 300px;
		overflow: hidden;
		border:1px solid #aaa;
		float:left;
	}
</style>

//Native Canvas Component
<template>
	<div class="native-render">
		<canvas ref="mainCanvasRef"></canvas>
	</div>
</template>
<script setup>
	import {ref,onMounted,} from "vue"
	
	onMounted(()=>{
		initCanvas()
	})
	
	let mainCanvasRef = ref();
	let mainCanvas;
	function initCanvas(){
		mainCanvas = mainCanvasRef.value;
		mainCanvas.width =5000;
		mainCanvas.height = 4000;
		let ctx = mainCanvas.getContext("2d");
		ctx.font = "80px sans-serif";
		ctx.textBaseline="top";
		ctx.fillText("hello word",0,0);
	}
</script>
<style scoped>
	.native-render{
		width: 400px;
		height: 300px;
		overflow: hidden;
		border:1px solid #aaa;
		float:left;
	}
</style>
```
Effects like this:
![f45cb6d4c79a724b9f1d4081bf3da58](https://user-images.githubusercontent.com/35246460/228118029-777dcaca-17a0-461a-9270-0257693ab61a.png)

Memory usage comparison:
Native Canvas:
![3adfd24185b208f998982695d41a1b3](https://user-images.githubusercontent.com/35246460/228118224-caa1fe36-aaa2-4d3f-8e04-968212674d02.png)

Konva:
![bbfff7d9a5a144de48e8ac037eaa7e1](https://user-images.githubusercontent.com/35246460/228118257-0020f9c2-b0d8-4dd5-92ea-7300dcae84f4.png)

**Comment by lavrton** [comment]
The canvas is consuming all that memory. Konva creates many canvases on the runtime.

1. Konva automatically handles HDI devices (like retina display). So it may create 4x bigger canvas.
2. When you create a simple layer with one text it will create at least 3 canvas elements. One buffer canvas of stage, one scene canvas of layer and another hit canvas of layer.

I don't think you should create 10 5000 * 4000 stage. The screen is smaller. Try to keep the stage size as small as possible. 

But you can export once into a very large canvas. You can use `pixelRatio` property for `toDataURL()`
