### ISSUE TITLE
should clear context in the begin of sceneFunc? 

### ISSUE THREAD

**Issue by polokobe** [konvajs/konva#155]
Hi, when I setAttrs() a shape,  the new style of context does not display in the right way. should clear context in the begin of sceneFunc?

**Comment by lavrton** [comment]
@polokobe can you provide any examples?
You may take a look into this example: http://konvajs.github.io/docs/shapes/Custom.html
Also, are you calling `layer.draw()` after setting attrs?

**Comment by polokobe** [comment]
My code is :
```javascript
shape.sceneFunc(function(context) {
    // I do this to clear canvas
    context.clearRect(0, 0, context.canvas.width, context.canvas.height);
    context.beginPath();
    ........
}
```

when I use setAttrs(), I must do that to clear the canvas. And in the source code of konvajs,
```javascript
 drawScene: function(can, top, caching, skipBuffer) {
     ....
}  
```
It seems that there is no code to do that.
Thanks!

**Comment by lavrton** [comment]
@polokobe you do not need to clear canvas. `Konva` will do it for you.

**Comment by lavrton** [comment]
I will close this issue. You can reopen it if you still have questions.
