### ISSUE TITLE
will Konva consider to add a ES5 build version

### ISSUE THREAD

**Issue by timeless15** [konvajs/konva#1550]
Hi, I'm a deeper user of Konva, and currently I'm using class extends to realize custom Group.
I write like: 
```tsx
class CustomGroup extends Group {};
const test = new CustomGroup();
```
But my project is build into es5, will be build into like:
```js
var RectControlGroup = /*#__PURE__*/function (_Konva$Group) {
  _inheritsLoose(RectControlGroup, _Konva$Group);

  function RectControlGroup(props) {
    var _this;
    _this = _Konva$Group.call(this, props) || this;
  }
}
```
However, _Konva$Group is still in ES6 class syntax, so browser will throw Error: 

![image](https://user-images.githubusercontent.com/25543532/230284883-8345426d-a76d-4a62-a8cb-f27d021dd26f.png)

I understand that because Konva's support browser that run ES2015. But it's hard for some big project to change the build target, although all pages are run in modern browser.

So will your team consider to add a ES5 build version?

**Comment by lavrton** [comment]
I don't plan to support es5 from Konva side. If you need it, you can transpile to ES5 code by yourself with some tools.
