### ISSUE TITLE
Performance issue with _getProtoListeners  

### ISSUE THREAD

**Issue by aiiak** [konvajs/konva#1551]
Problem:  _getProtoListeners  calls takes up to 50% of layer upadtes time. 

I have a layer with ~ 5000  Konva.Lines with listening = false  

When layer is updates,  i see folowing picture in profiler

![image](https://user-images.githubusercontent.com/14100012/230394959-dcaff1be-3d44-4980-89be-28f5f4bf1b36.png)

 and 

![image](https://user-images.githubusercontent.com/14100012/230397662-0fe4e338-4f0f-4e3a-a598-2aca2f9c24a6.png)

Creating events cache takes a lot of time in mycase. 

**Is it possible to replace array.concat here with faster sorution ?**  

Another reason, that case this, is that Shape prototype by default subscribes  for shadows and gradients updates.  It happens  even if there is no shadow or any type of gradient are used in shapes. 
```
Shape.prototype.on.call(
  Shape.prototype, 
  'shadowColorChange.konva shadowBlurChange.konva shadowOffsetChange.konva shadowOpacityChange.konva shadowEnabledChange.konva',
  _clearHasShadowCache
);

Shape.prototype.on.call(
  Shape.prototype,
  'shadowColorChange.konva shadowOpacityChange.konva shadowEnabledChange.konva',
  _clearGetShadowRGBACache
);
...
```
**Is it possible to make this subscription optional, and apply them only when shadow / gradient are actually used in shapes ?** 

Thanks

**Comment by lavrton** [comment]
> Is it possible to replace array.concat here with faster sorution ?

Probably, but I am not sure it will help much.

> Is it possible to make this subscription optional, and apply them only when shadow / gradient are actually used in shapes ?

I don't think it will be simple to do, and I don't think it will help to improve the performance.

Can you make a demo? Why do you need 5000 lines? Are they all visible at the same time?

**Comment by aiiak** [comment]
Lines with closed=true are used to draw a phisical location in storage,  layer show literally heatmap, can be swithed by different KPI. 

Is it required to calculate ALL_LISTENERS cache for all event types simulataneously ?  
What if calculate and cache proto events listenerts on a first time when event was fired? 

Here is example  of implementation
```
  _getProtoListeners(eventType) {
    const allListeners = this._cache.get(ALL_LISTENERS) ?? {};
    let events = allListeners?.[eventType];
    if (events === undefined) {
      //recalculate cache
      events = [];
      let obj = Object.getPrototypeOf(this);
      while (obj) {
        const hierarchyEvents = obj.eventListeners?.[eventType] ?? [];
        events.push(...hierarchyEvents);
        obj = Object.getPrototypeOf(obj);
      }
      // update cache
      allListeners[eventType] = events;
      this._cache.set(ALL_LISTENERS, allListeners);
    }

    return events;
  }
```
i completle remove _getProtoListeners from heavy tasks 

![image](https://user-images.githubusercontent.com/14100012/230601108-2a07797e-507d-447c-96f9-f3660e5c8fab.png)

@lavrton , do u see any problem with this approach ? 

This changes doen't  affect any new test failures ^) . I got one called **"  1) Text text multi line with shadows: "** falling wen run test locally even on repository whithout changes. Is it flacky one and depend on enviroment ?

**Comment by lavrton** [comment]
I don't see any problems right now. It looks like it works excellent. I merged your changes and released a version. Take a look. Does it work better for you?

**Comment by aiiak** [comment]
@lavrton , it works exellent. Thanks!
