### ISSUE TITLE
Allow namespaced listeners to remain after a plain 'off' is called.

### ISSUE THREAD

**Issue by VanquishedWombat** [konvajs/konva#1553]
This relates to event listeners.

Say I have a rect, and the following code 

```js
rect.on('click.vw', function(){
  console.log('this is the click.foo listener')
})
       
 listListeners('Before off is called', rect, 'click')

  rect.off('click')

 listListeners('After off is called', rect, 'click')

function listListeners(msg, shape, list){

  console.log(msg)
  
  for (let type of list.split(' ')){

    const evtListeners = shape.eventListeners[type]

    if (evtListeners){
      for (let i = 0; i < evtListeners.length; i++) { 
        const evtName = evtListeners[i].name; 
        console.log(' - ' + type + ' has a listener [' + evtName + ']')
      }
    }
    else {
      console.log(' - ' + type + ' no listener')
    }
  }

}
```

Then what I see in the console is 

```
"Before off is called"
" - click has a listener [foo]" 
"After off is called"
" - click no listener"
```

Conclusion: the plain 'rect.off()' call has removed my namespaced click.vw  listener. 

Issue: the issue comes when we are writing custom shape bahaviors intended to be provided as libraries.  Konva is excellent and the custom-shape allows for this approach. However, in writing a lib we need to be sure that the developer using it later does not wipe out the listeners coded for the internal of the lib.  Konva, in its code, protects it's own listeners from this issue.

Proposed mod: Modify the shape.off() code to leave namespaced listeners in place unless specifically named (click.foo) or targeted via wild-card approach (.foo).

Complication: This could be considered a potential breaking change.  To avoid that perhaps we confine this change to namespaces of a specific form. For example '*.-foo', so 'click.-foo' would not be cleared by 'off()' whilst 'click.foo' would be cleared as current behavior.

I submit this change request to the good community of Konva maisters for consideration.

**Comment by lavrton** [comment]
That is an interesting issue, but I am not sure what will be the beautiful solution for that.

> Modify the shape.off() code to leave namespaced listeners in place unless specifically named (click.foo) or targeted via wild-card approach (.foo).

I don't know to do that, as it is breaking solution.

Your use case is VERY rare. So, I think we can just add another special hidden and protected name space. E.g. "hidden_lib"
