### ISSUE TITLE
Text position differs on safari

### ISSUE THREAD

**Issue by jonathanelmgren** [konvajs/konva#1555]
I am creating a stage in a admin page to then be seen on the front. I save my stage with toJSON and recreate it with Node.create()

No matter how simplified I make the canvas, it renders different on Safari compared to all other browsers.

I have tried Chrome, Edge, Opera, Firefox and Safari. Only safari differs.

This makes a significant difference since I need to scale this up to a poster size (50x70cm) so the text differs about 2-5cm depending on font size and this is not good if it's supposed to stay on a line :)

Please see my codesandbox https://codesandbox.io/s/vigilant-pond-lb1zxt 

EDIT: I added a border to the shape and it doesn't seem to be aligning the same way

![Screenshot 2023-04-20 at 22 59 29](https://user-images.githubusercontent.com/81702447/233486648-7238a493-3c77-444e-83e9-b2af705889a1.png)

![Screenshot 2023-04-20 at 22 59 11](https://user-images.githubusercontent.com/81702447/233486687-74bde869-9f53-4b1e-9128-2ee9c1a06d5a.png)

EDIT2: I noticed it is not only when recreating the stage. See this link: https://codesandbox.io/s/determined-glade-go1uu7?file=/src/index.js

EDIT3: Did some more digging and noticing this https://stackoverflow.com/questions/6692565/webkit-vs-mozilla-vertical-alignment-of-font-glyphs-in-box looks like it's a webkit/mozilla issue. Maybe you can find a workaround for this?

**Comment by peter-tell** [comment]
+1

Also seeing the same issue. It also happens in Chrome on iOS, but definitely seems like an Apple thing

**Comment by jonathanelmgren** [comment]
I ended up finding the core issue. It is the difference in line heights between fonts and browsers. I tried doing my best creating converters for each font but got out of hand when adding more fonts and the precision had to be 100% working with big size prints like 500x700 prints.

I ended up changing canvas library

**Comment by lavrton** [comment]
@jonathanelmgren what do you use instead? I want to learn more on how to fix that, if possible at all.

**Comment by jonathanelmgren** [comment]
@lavrton I'm testing out fabric.js at the moment. I've yet to try the issue I had above, but I chose this because of the SVG export method

**Comment by braity** [comment]
_Posting a comment as I had the same problem and found a workaround._

Safari rounds font sizes when rendering text. For example, a font size of 15.2442 pixels will be rounded down to 15 pixels. To calculate the dimensions of a text wrapper precisely, you need to account for this rounding behavior.

**1. Define Font Size Variables**
First, compute the scaled font size based on the canvas scale factor and then calculate the fixed (rounded) font size. The offset (difference between the precise scaled size and its rounded value) is used to adjust the text placement:

```javascript
const scaledFontSize = fontSizeInPx * scale;             // Apply canvas scale factor to the font size
const fixedFontSize = Math.round(scaledFontSize); // Round the scaled font size
const offsetY = scaledFontSize - fixedFontSize;       // Calculate the vertical offset for precise positioning
```


**2. Create a Function to Measure Text Size**
Next, define a function that measures the text dimensions using the canvas context. Note that we adjust the width by an extra 5 pixels to avoid clipping issues:

```javascript
function measureText(canvas, fontSize, fontFamily, text) {
  const ctx = canvas?.getContext('2d');

  // Set canvas text properties
  ctx.font = `${fontSize}px ${fontFamily}`;
  ctx.fontKerning = 'normal';
  ctx.textBaseline = 'alphabetic'; // someone 

  const metrics = ctx.measureText(text);

  // Calculate the width and height. A small buffer is added to the width to prevent text clipping.
  // I belive there is better solution for doing that.
  const width = Math.abs(metrics.actualBoundingBoxLeft) + Math.abs(metrics.actualBoundingBoxRight) + 5;
  const height = metrics.actualBoundingBoxAscent; // Use ascent as the text height

  return { width, height };
}
```
**3. Define the Wrapper and Text Sizes**
Finally, use the measured text size to define the wrapper and adjust the text’s Y-position by subtracting the offset. This ensures proper alignment, especially when working with frameworks like Konva:

```javascript
// Set a temporary flag to handle Konva text rendering issues
Konva._fixTextRendering = true;

const wrapperPosition = { x: 50, y: 50 };
const wrapperSize = measureText(konvaCanvas, fontSize, fontFamily, text);
const wrapperRect = new Konva.Rect({
  ...wrapperSize,
  ...wrapperPosition
});

const textInstance = new Konva.Text({
  ...wrapperSize,
  x: wrapperPosition.x, 
  y: wrapperPosition.y - offsetY, // Adjust Y-position based on the offset
  align: 'center',
  verticalAlign: 'middle',
});
```

**Related issues:**
- https://github.com/konvajs/konva/issues/559
