### ISSUE TITLE
Rendering error when the coordinates of the point are a huge value

### ISSUE THREAD

**Issue by Kiku-CN** [konvajs/konva#1557]
I have drawn two polygons with points [20, 20,  20, 160, 530000, 900000] and [20, 20,  20, 160, 5300000, 900000].
poly1 is normal, but poly2 is abnormal and don't like a triangle.

<img width="635" alt="Snipaste_2023-04-25_11-25-25" src="https://user-images.githubusercontent.com/27356487/234167370-6f80818c-b0d1-42a5-a25b-7a333f8009cd.png">

Is it because the coordinate value of poly2 is too large?

There is an exception in the rendering in Edge or Chrome, but it is normal in the Firefox.

There is a [reproducible example](https://codepen.io/kiku-cn/pen/rNqyOey).

**Comment by lavrton** [comment]
I don't think there is anything we can do from Konva side. This is behavior from the browser.
