### ISSUE TITLE
this.tapStartShape is undefined in stage's _toouchend

### ISSUE THREAD

**Issue by DMIAOCHEN** [konvajs/konva#156]
Hi lavrton!
I draw two ellipse, the first ellipse is OK, when the second ellipse's end point **on** first ellipse, start point **not on** first ellipse, then it cause the error.
I debug it, find that first ellipse triggered touchend event, but **not trigger touchstart event**. so there have no tapStartShape.

**Comment by lavrton** [comment]
@DMIAOCHEN can you provide code example?

**Comment by DMIAOCHEN** [comment]
sorry, i try to write a demo but i can't Simulate touchstart and touchend :sob::sob:,  just for example :
there are one Stage:
```javascript
{
  x: 0,
  y: 0,
  width: 600,
  height: 800,
}
```
and one Rect:
```javascript
{
  x: 0,
  y: 0,
  width: 100,
  height: 100,
  fill: 'blue',
}
```
the step is:
1. touchstart in position` {x:150, y: 150 }` trigger one touchstart event
2. **not released**, just move to `position {x: 50, y: 50}`
3. release you touch, it will trigger one touchend event.

**attention: 
It's touch event not mouse event, mouse event can not cause this error.**

**Comment by DMIAOCHEN** [comment]
![image](https://cdn.rawgit.com/DMIAOCHEN/RawGit/master/Images/Konva%23156.gif)

**Comment by lavrton** [comment]
@DMIAOCHEN Thank you very much! Fixed!

**Comment by lavrton** [comment]
I will publish soon.

**Comment by DMIAOCHEN** [comment]
Thanks！:+1:
