### ISSUE TITLE
Support for border gradient

### ISSUE THREAD

**Issue by lukedukeus** [konvajs/konva#1561]
Is it possible to create a line with a linear gradient stroke like this?
![image](https://user-images.githubusercontent.com/23089287/235464086-9272b747-cf19-4a6d-bb80-45e4d12e3d14.png)

**Comment by lavrton** [comment]
Stroke linear gradient.

```js
var linearGradPentagon = new Konva.RegularPolygon({
  x: 360,
  y: stage.height() / 2,
  sides: 5,
  radius: 70,
  fillLinearGradientStartPoint: { x: -50, y: -50 },
  fillLinearGradientEndPoint: { x: 50, y: 50 },
  fillLinearGradientColorStops: [0, 'green', 1, 'blue'],
  strokeLinearGradientStartPoint: { x: -50, y: -50 },
  strokeLinearGradientEndPoint: { x: 50, y: 50 },
  strokeLinearGradientColorStops: [0, 'red', 1, 'yellow'],
  strokeWidth: 4,
  draggable: true,
});
layer.add(linearGradPentagon);
```

https://jsbin.com/xituyiheki/1/edit?html,js,output

**Comment by lukedukeus** [comment]
@lavrton, Thanks, but I can only figure out how to use this with regular polygons, like you have in the demo. Is it possible to use this with Shape or Line, so I can create a custom shape like the one above?

**Comment by lavrton** [comment]
Did you try anything?

**Comment by lukedukeus** [comment]
@lavrton, my bad, I see it wasn't working because I was using the react wrapper which doesn't have the changes yet. Any clue when you plan to update the npm package?

Thanks!
