### ISSUE TITLE
node-canvas fillPatternImage with opacity<1,strokeWidth=0,fillPatternScale>1, output a incorrect image

### ISSUE THREAD

**Issue by liudexiang3218** [konvajs/konva#1564]
var stage = new Konva.Stage({
        width: 500,
        height: 500
      });
      var imageObj =  new Canvas.Image;
            imageObj.onload = function () {
                var layer = new Konva.Layer();
      var shape=new Konva.Rect({
      fillPatternImage:imageObj,
      strokeWidth:0,
      fillPriority: "pattern",
      height: 500,
     width: 500,
      fillPatternScaleY: 1.3,
      fillPatternScaleX: 1.3,
      x: 0,
      y: 0,
      fillPatternRepeat: "no-repeat",
      opacity: 0.75
      });
      layer.add(shape);
           stage.add(layer);
           res.setHeader('Content-Type', 'plain/text')
           res.end(stage.toDataURL({mimeType:'image/png'}))
            };
            imageObj.src = 'https://camo.githubusercontent.com/8ee88dda37d12638ee55035971e01ce818f0564584264cd9a688188846ce7e34/68747470733a2f2f6b6f6e76616a732e6f72672f616e64726f69642d6368726f6d652d313932783139322e706e67';

### I run this code by server side node-canvas "canvas": "2.11.2", "konva": "9.0.1".

incorrect image
![incorrect](https://github.com/konvajs/konva/assets/47103998/a45a9f8f-3a50-42b7-81c6-96445d8ffc67)
### change opacity to 1, output a correct image
correct image
![correct](https://github.com/konvajs/konva/assets/47103998/3dc55cbc-3b0a-41ed-b7a8-ed5f25ab5c3d)

**Comment by faizulhaque** [comment]
Just a thought, instead of using `Rect`, why not just use `Image`

e.g. Instead of 
```shell
var shape=new Konva.Rect({
fillPatternImage:imageObj,
strokeWidth:0,
fillPriority: "pattern",
height: 500,
width: 500,
fillPatternScaleY: 1.3,
fillPatternScaleX: 1.3,
x: 0,
y: 0,
fillPatternRepeat: "no-repeat",
opacity: 0.75
});
```

Use  

```shell
let shape = new Konva.Image({
        image: imageObj,
        strokeWidth: 0,
        height: 500,
        width: 500,
        x: 0,
        y: 0,
        opacity: 0.75
      });  
```

Output:
![image](https://github.com/konvajs/konva/assets/836298/e4045132-df49-492e-9000-8ff3c45b09c8)

**Comment by lavrton** [comment]
That looks like a bug in `canvas` library. Can you please report it there?
