### ISSUE TITLE
Displaying an image in custom shape and drag effect

### ISSUE THREAD

**Issue by faizulhaque** [konvajs/konva#1565]
There is an example posted by [Vanquished Wombat](https://stackoverflow.com/users/7073944/vanquished-wombat) on the post [here](https://stackoverflow.com/questions/71479508/how-to-handle-with-images-overflow-draggable-area-etc-on-konva-js-stage/76223478#76223478)

The example uses the Konva Rect and Konva Image in Konva Group. Is it possible to achieve the same effect using Konva Line (having Points) to draw a custom shape and use fillPatternImage to draw the Image inside it.

**Comment by lavrton** [comment]
It should be possible. Did you try anything?

**Comment by lavrton** [comment]
You just need to set offset relative to image position.

```js
rect.fillPatternOffset({
    x: -imagePos.x,
    y: -imagePos.y,
  });
  ```
