### ISSUE TITLE
The new version sets the graphics image incorrectly

### ISSUE THREAD

**Issue by zhoulingz** [konvajs/konva#1566]
In the new version, only the graphics are flipped when you set up the graphics image. For example, set x:-1 mirroring y or set y:-1 mirroring x in transformer. In lower versions, such as 4.0, this problem does not exist

[demo](https://jsbin.com/zusuqomifi/3/edit?html,js,output)

**Comment by zhoulingz** [comment]
When you click on this pentagon, the pentagon flips down and transformer does not flip

**Comment by lavrton** [comment]
In one of the konva versions, there were major refactor of how transformer works. Current behavior is consistent and the pentagon works the same as rect in the demo. If you have any particular example what is not correct in the current demo, please make a demo and explain.

**Comment by zhoulingz** [comment]
I'm not sure if my previous example description was not clear enough?
The following are the results of two versions of the same code. In version 4.0.18, x and y flipping were set, and the transformer was transformed along with the graph. In version 9.0.2, when flipping x and y, the graphics transformation is normal, but the transformer is in the opposite direction.

[version 9.0.2](https://jsbin.com/coninibeqi/1/edit?html,js,output)

[version 4.0.18](https://jsbin.com/newakopala/1/edit?html,js,output)

**Comment by lavrton** [comment]
Well, this is how it works now. Flipping x is the same transform as flipping y + rotating by 180 deg.
It was working a bit differently previously, but it is how it works now. If you don't like it, you can use `useSingleNodeRotation = false` property: https://konvajs.org/api/Konva.Transformer.html#useSingleNodeRotation__anchor
