### ISSUE TITLE
Spikey line point

### ISSUE THREAD

**Issue by witchpiggie** [konvajs/konva#1567]
Not sure if this is a konva or react-konva specific issue as I am using react-konva..
When free drawing I get these spikey points on lines. Checking the points,
there's none that lie that far out. Eventually, I figured out that if I add the
lineCap: "round" property, it appears to be fixed. However, that particular
property is listed as optional in the docs. I've included an image showing
the pointy line, and the array of points.

![spikey](https://github.com/konvajs/konva/assets/47288884/e3fa82b0-09f1-42bb-b406-2e8a45b35631)

Edit - Adding image showing the same points, but with linecap added.

![notspikey](https://github.com/konvajs/konva/assets/47288884/8ccb303b-2e7c-4112-99d7-e8d797ea829c)

**Comment by lavrton** [comment]
So what is the issue about? If you don't want the default behavior (that uses lineCap = "butt" i think), use lineCap = "round"

**Comment by witchpiggie** [comment]
I wasn't sure if this behavior was intentional. If this is expected behavior then I guess you can just close this.
Since the lineCap property is marked as optional and (at least to me) this seemed like a bug (since it's drawing where there are no points), I submitted this report.

**Comment by lavrton** [comment]
This is canvas 2d API default. I don't want to overwrite this default behaviour for now.
