### ISSUE TITLE
toObject serialization

### ISSUE THREAD

**Issue by ada99** [konvajs/konva#157]
I'm not sure, but looks like:
// line 3430 in kanva.js
// serialize only attributes that are not function, image, DOM, or objects with methods
if (Konva.Util._isFunction(val) || Konva.Util._isElement(val) ||
    (Konva.Util._isObject(val) || Konva.Util._hasMethods(val))) {
    continue;
}

should be:

// serialize only attributes that are not function, image, DOM, or objects with methods
if (Konva.Util._isFunction(val) || Konva.Util._isElement(val) ||
    (Konva.Util._isObject(val) && Konva.Util._hasMethods(val))) {
    continue;
}

|| replaced with &&

**Comment by lavrton** [comment]
@ada99 probably. Do you want to create a pull request with tests?

**Comment by ada99** [comment]
Unfortunately on unchanged project I got:
   434 passing (12s)
  12 pending
  1 failing

  1) Caching cache group with rectangle and text:
     Result from Konva is different with canvas result: expected false to equal true

**Comment by lavrton** [comment]
Strange. In my machine and in Travis builds all ok. But in fact, it is possible. As some tests depends on browser and system. So some of them may fail. You can ignore that tests.

**Comment by ada99** [comment]
#158
