### ISSUE TITLE
Image transformer z-index problem

### ISSUE THREAD

**Issue by monumatik** [konvajs/konva#1571]
Hi,
konva 9.0.2

i have created one stage, add one layer, one transformer and two draggable images to layer.
Second photo (on top) is on top but transformer not.
![Zrzut ekranu 2023-06-1 o 15 08 44](https://github.com/konvajs/konva/assets/40207400/56272d28-f663-40fa-b8f4-35285b7b71bf)

There is how i detach transformer from first to second image
![Zrzut ekranu 2023-06-1 o 15 44 33](https://github.com/konvajs/konva/assets/40207400/72bbdcfa-5efc-4bcb-bd64-34b8f375bfab)

**Comment by lavrton** [comment]
The Transformer works similar to other nodes. It has its own zIndex. So, you may want to move it to the top too, after the image:

```js
image.moveToTop();
konvaTransformer.moveToTop();
```
