### ISSUE TITLE
The konvajs click event is executed before the window mouseup event

### ISSUE THREAD

**Issue by LonelySunset** [konvajs/konva#1572]
I found that konvajs click event was executed before DOM mouseup event.

Is this a bug or is this how konvajs is designed

konvajs version: 9.0.2
chrome version: 114.0.5735.91

**Comment by lavrton** [comment]
This is how Konva events are designed. Konva is not listening to native `click` event. Instead it is listening to `mousedown`/`mouseup` events and making clicks from them.
