### ISSUE TITLE
esbuild  not minify   konva error

### ISSUE THREAD

**Issue by 3400442579** [konvajs/konva#1575]
Thank you for submitting an issue!
![image](https://github.com/konvajs/konva/assets/34226979/f645bf73-4385-455d-ba10-da2f7c252231)

![image](https://github.com/konvajs/konva/assets/34226979/c5ba088c-7d56-47e6-8c5c-f9d81e5e0594)

**Comment by ThangLe3111996** [comment]
If you assign ref for node konva, you should use node.current.addEventlistener (not node.addEventlistener)

**Comment by lavrton** [comment]
@3400442579 please make a demo. Like a very minimal repo to reproduce the issue. May it be the error with esbuild and not konva?

**Comment by 3400442579** [comment]
html
`<html>
<head>
</head>

<body>
  <div id="test"></div>
  <script src="js/test.js"></script>
</body>
</html>`

js
`import { render } from "solid-js/web";
import Konva from 'konva/lib/Core';
import { Rect } from 'konva/lib/shapes/Rect';

function App() {
  
  var stage = new Konva.Stage({
    container: '#container',
    width: 300,
    height: 300
  });
  var layer = new Konva.Layer();

  var rect = new Rect({
    x: 20,
    y: 20,
    width: 100,
    height: 50,
    fill: 'green',
    stroke: 'black',
    strokeWidth: 4,
  });
  layer.add(rect);

  stage.add(layer);

  return (
    <div id="container">test</div>
  )
}


render( () =>  <App /> , document.getElementById("test"));`

**minify=false ,  Generate code cannot run**
`// vite.config.ts
import { resolve } from 'path'
import { defineConfig } from 'vite';
import solidPlugin from 'vite-plugin-solid';

export default defineConfig({
    plugins: [solidPlugin()],

    build: {
        emptyOutDir:false,
        manifest: true,
        outDir: "wwwroot",
        minify:false, // minify=false ,  Generate code cannot run
        watch:true,
        rollupOptions: {
            input: {
                test: resolve(__dirname, 'dev/pages/test.jsx'),
            },
            output: {
                entryFileNames: "js/[name].js",
                 assetFileNames:"css/[name][extname]"//[hash]
            }
        },
    },
});`
