### ISSUE TITLE
Calculate angle between two lines

### ISSUE THREAD

**Issue by ThangLe3111996** [konvajs/konva#1576]
Hi, i love library Konva.

So today, i have problem about calculating angle between two lines. I create group component have two lines. Its perpendicular to each other. But when i drawing groung by using mousemove, i don't know how to work to keep angle between two lines still perpendicular. Can you give advice or solution for me? Thank you. If you don't understand with my question. I try to create codesandbox to send for you soon.

**Comment by lavrton** [comment]
Yes, make a demo.

**Comment by ThangLe3111996** [comment]
https://codesandbox.io/s/distracted-snowflake-k6z7w8?file=/src/App.js

I have group include two lines inside. So, i want to mousemove that two lines still keep perpendicular together. Can you help me calculate position x, y for two lines?

**Comment by lavrton** [comment]
This?

```js
    const position = e.target.getStage().getPointerPosition();
    const { x, y } = position;
    const dx = x - pointsLine.x;
    const dy = y - pointsLine.y;
    const length = Math.sqrt(dx * dx + dy * dy); // Length of the original second line

    const angle = Math.atan2(dy, dx); // Angle of the second line
    const rotatedAngle = angle + Math.PI / 2; // Angle rotated by 90 degrees

    const rotatedX = pointsLine.x + length * Math.cos(rotatedAngle);
    const rotatedY = pointsLine.y + length * Math.sin(rotatedAngle);
    setNewShape([
      {
        points: [pointsLine.x, pointsLine.y, rotatedX, rotatedY]
      },
      { points: [pointsLine.x, pointsLine.y, x, y] }
    ]);
```

https://codesandbox.io/s/purple-voice-k6v9ms?file=/src/App.js

**Comment by ThangLe3111996** [comment]
Yes, it's exactly what i need to do now. Thank you so much <3
