### ISSUE TITLE
Rasterization anti-aliasing

### ISSUE THREAD

**Issue by xReav3r** [konvajs/konva#1577]
Hello,
methods `toDataURL` and `toBlob` are creating anti-aliased output. According to documentation this behavior can be turned off:
https://konvajs.org/api/Konva.Node.html#toBlob
but `imageSmoothingEnabled` parameter makes no difference and is not typed in `konva/lib/Node.d.ts`.

In my application I am using `toBlob` which outputs the created Blob to canvas with `imageSmoothingEnabled` also set to false.
I created a sandbox with `toDataURL`. Even downloaded image is anti-aliased.
https://codesandbox.io/s/ancient-thunder-dr4jmn?file=/src/App.js

**Comment by lavrton** [comment]
I don't think `imageSmoothingEnabled` is useful in that case. As I understand, it is actually just for IMAGE smoothing. Not for shapes rendering: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled
