### ISSUE TITLE
Resize shape stroke updates only on mouse up

### ISSUE THREAD

**Issue by chriscouts** [konvajs/konva#1579]
When resizing a shape with a stroke on that shape, the stroke changes size visually and only updates back to the specified stroke on mouse up. 

I used the transformer [example](https://konvajs.org/docs/react/Transformer.html) and added a stroke to a shape and played around with the resize.

**Comment by lavrton** [comment]
This is by design of this demo. The demo resets scaling of rectangle on transformend. You can change that behaviour, if you don't like it. You can reset scale on every `transform` event or just keep using scale in the state of the app.
