### ISSUE TITLE
Use filter，Drawing a polygon, there is a 2-3px offset in different resolutions

### ISSUE THREAD

**Issue by zhangjunpingping** [konvajs/konva#1580]
![image](https://github.com/konvajs/konva/assets/40229043/ad79ce4d-1460-4b7a-bfad-04bba00abcca)

**Comment by lavrton** [comment]
Demo?

**Comment by zhangjunpingping** [comment]
> Demo?
![image](https://github.com/konvajs/konva/assets/40229043/1dc8dcd3-14d4-43ed-9c6e-1db383d92443)

Locate the reason, the konva.js filter function used caused。 data.length!=image.width*image.height*4
