### ISSUE TITLE
.height() on group returns 0 even if there is a rectangle inside

### ISSUE THREAD

**Issue by petervavro** [konvajs/konva#1581]
Even if there is a rectangle 20x20 inside the group, calling .height() on the group returns 0.

```
import Konva from 'konva-node'

var stage = new Konva.Stage({
    width: 100,
    height: 100,
});

var layer = new Konva.Layer();
stage.add(layer);

const group = new Konva.Group({
    x: 10,
});

const box = new Konva.Rect({
    x: 0,
    y: 0,
    width: 20,
    height: 20,
    fill: "red",
});

group.add(box);

console.log(group.height()) // Returns 0

layer.add(group);
```

**Comment by lavrton** [comment]
This is currently semi-intentionally. All Konva nodes have their own `width` and `height` attributes.  By default, they are equal to 0. For now, I don't have plans to fix that.
You can use `group.getClientRect()` to get the size of children elements.
