### ISSUE TITLE
I would like to share my Konva Node.js wrapper for server-side generation in Next.js.

### ISSUE THREAD

**Issue by petervavro** [konvajs/konva#1582]
This is my Konva Node.js wrapper for server-side generation in Next.js: [konva-node.ts](https://gist.github.com/petervavro/6fa3f2fbe14e5245c08600565144db62)

Q: What is the best place to share this, please?

**Comment by lavrton** [comment]
You can add missing functions to https://github.com/konvajs/konva/blob/master/src/index-node.ts and make a Pull Request.
