### ISSUE TITLE
How to check Konva Stage is loaded or not in browser js

### ISSUE THREAD

**Issue by mageprashant** [konvajs/konva#1584]
Thank you for submitting an issue!

Please make sure to check current open and closed issues to see if your question has been asked or answered before.
If you have just a question (not a bug or a feature request) it is better to ask it in [Stackoverflow](http://stackoverflow.com/questions/tagged/konvajs).

If you have a bug, please, try to create a reproducible example with jsfiddle (or any similar service).
You can use [this JSBIN](https://jsbin.com/tekehizuta/1/edit?html,js,output) as a template.

**Comment by lavrton** [comment]
Can you provide any details?

**Comment by mageprashant** [comment]
@lavrton here is an example.

1. editor.js

```
var stage = new Konva.Stage({
    container: 'container',
    width: 420,
    height: 600,
});
```

2. initText.js

```
var textArray = ['Text 1', 'Text 3', 'Text 3', 'Text 4'];

var layer = new Konva.Layer();
stage.add(layer);
for(i=0; i < n; i++) {
    var textNode = new Konva.Text({
        text : textArray[i],
        fontSize : 20,
        fill : '#000',
        fontFamily : 'default',
        x: 100,
        y: 50,
        align: 'center',
    });
    layer.add(textNode);
}
```

I have 2 files we defined the **stage** on the first file and the **layer** is on the second file so is it possible to get **stage** in the second file?

**Comment by lavrton** [comment]
I am closing it, as it is not really konva-related question. It is js basics. There are many solutions. You can try moder module solutions or simply put stage into global variable.

```
// editor.js
window.stage = new Konva.Stage({...});

// initText.js
window.stage.add(layer);
````
Make sure `initText.js` is added after `editor.js` on the page.
