### ISSUE TITLE
Developer tool

### ISSUE THREAD

**Issue by maitrungduc1410** [konvajs/konva#1585]
Hi @lavrton,

Konva is great library with feature rich and the ease of use, and to make the developer experience better, I created Konva devtool used to inspect Konva app: https://github.com/maitrungduc1410/konva-inspector

My extension is born to bring developer better experience like other devtools (React, Vue, browser native devtool), supports all Konva objects, cross browser (Chrome, Firefox, Edge), live editing, multi stages, dark theme,...

You can have a try with my extension and give feedback if it's good or not.

I'm wonder if can have this extension officially some where in Konva ecosystem that'll help Developer who's using Konva during development. Understand that there's already [konva-devtool](https://github.com/konvajs/konva-devtool) under your org. But still whether you can put my ext in some recommended list, Eg: https://konvajs.org/docs/tools.html.

Thanks

<img width="1200" alt="1" src="https://github.com/konvajs/konva/assets/16630193/dbad3f26-0bf9-4568-b82b-1a89d287a476">
<img width="1200" alt="2" src="https://github.com/konvajs/konva/assets/16630193/f85ea238-96bc-48b3-89af-bcb59ccc9475">
<img width="1200" alt="3" src="https://github.com/konvajs/konva/assets/16630193/1ffbd71f-21e4-4f34-9327-839c0b38661c">
<img width="1200" alt="4" src="https://github.com/konvajs/konva/assets/16630193/73c67fd3-6e5e-4866-9ac3-c11c4e643415">
<img width="1200" alt="5" src="https://github.com/konvajs/konva/assets/16630193/158d855b-dde4-4644-a2ed-ee21699f0495">

**Comment by lavrton** [comment]
That is really great work! I really like how it works!

Also, I think there are several ways to improve it. The first suggestion I have in mind is to add a bit more info into tree view. Probably add `id` and `name` of a node. And I suggest to hide internal id, as it is not really useful for a developer.

**Comment by maitrungduc1410** [comment]
i was really wondering whether to add `id` and `name` directly to node, but then I think should keep it in the inspected attributes from right side, since they're optional attributes like other attrs, 

also during inspecting a tree, many times many nodes won't have any `id` or `name`.

regarding the internal `_id`, I consider it like `key` in React/Vue

displaying them next to Node name will help user on navigation around, or searching. It's hard for developer to inspect if there's 100 Text nodes with no additional info to distinguish one from others

**Comment by lavrton** [comment]
Personally, I use `name` attribute frequently to identify nodes on the canvas. I think some attributes can be added into tree view to better understand structure and find nodes. Like `id`, `name`. If they are empty, just show `_id`. Also you can show some essential attributes. E.g. show `text` attribute for `Text` nodes, probably `fill` for some shapes.
That is just a suggestion to experiment. 

That is up to you to decide what will work better.

**Comment by maitrungduc1410** [comment]
> Personally, I use `name` attribute frequently to identify nodes on the canvas. I think some attributes can be added into tree view to better understand structure and find nodes. Like `id`, `name`. If they are empty, just show `_id`. Also you can show some essential attributes. E.g. show `text` attribute for `Text` nodes, probably `fill` for some shapes.
> 
> That is just a suggestion to experiment. 
> 
> 
> 
> That is up to you to decide what will work better.

I see, that's good points. I'll consider it for future releases
