### ISSUE TITLE
How to correct extend type 

### ISSUE THREAD

**Issue by borm** [konvajs/konva#1586]
hello there, im trying to extend type but im new with extending namespaces, 
what did i try already

```typescript
import { NodeConfig } from 'konva/lib/Node';

declare module 'konva/lib/Node' {
  export declare class Node<T, Config extends NodeConfig = NodeConfig> {
    protected constructor(config?: Config);
    attrs: T;
  }
}

```

but it doesnt works

**Comment by lavrton** [comment]
Why do you need it?

**Comment by borm** [comment]
i need to pass generic `attrs` to my `Node` and get correct types from there then

**Comment by lavrton** [comment]
I still don't understand why you may need that. Using `attrs` directly is antipattern in Konva. You should use public getters, like `node.x()` instead of `node.attrs.x`.

**Comment by borm** [comment]
I need to access my custom props, not predefined like x or y, I had pass custom attribute to my node and need to have access to that, like 
```
<Group 
  foo="bar"
/>
```

then get this attr 
node.attrs.foo

**Comment by lavrton** [comment]
I am not sure what will be the correct solution. I still would prefer public and documented API, instead of `attrs` property.

```js
node.getAttr('foo');
// or
(node.getAttrs() as MyInterface).foo;
```
