### ISSUE TITLE
How to implement custom brushes

### ISSUE THREAD

**Issue by CodingEnding** [konvajs/konva#1588]
Hi,
I hope to support more types of brushes in freehand drawing mode, such as pen style and pencil style. However, there seems to be no concept of Brush in the document, so I don't know how to implement it. 

In another Canvas library, Fabric.js, there is an independent concept of Brush and built-in brushes such as SprayBrush. So I want to ask if I misunderstood any concept.

**Comment by lavrton** [comment]
Konva doesn't have brushes. You can do some them with simple Konva.Line or Custom shape.
