### ISSUE TITLE
Drawing ellipse 

### ISSUE THREAD

**Issue by ThangLe3111996** [konvajs/konva#1589]
Hi admin, i want to draw free ellipse like video below

https://github.com/konvajs/konva/assets/65648064/40d68fe6-5877-4a78-a651-439de8633b5d

It's my demo. I try to calculate RadiusX and RadiusY (width and height) of Ellipse but it not work like i want. Can you help me by fixing my demo? Thank you so much. 

https://codesandbox.io/s/goofy-gianmarco-y3lznh?file=/src/App.js

**Comment by lavrton** [comment]
I would do this:

```js
 const startPos = useRef();

  const handleMouseDown = (e) => {
    const position = e.target.getStage().getPointerPosition();
    const { x, y } = position;
    setNewShape({ x, y });
    startPos.current = position;
  };

  const handleMouseMove = (e) => {
    if (!newShape.x && !newShape.y) {
      return;
    }
    const { x, y} = e.target.getStage().getPointerPosition();
    const start = startPos.current;
    
    const item = {
      x: (x + start.x) / 2,
      y: (y + start.y) / 2,
      radiusX: Math.abs(x - start.x) / 2,
      radiusY: Math.abs(y - start.y) / 2
    }
    setNewShape(item);
  };

  const handleMouseUp = (e) => {
    setListShape(prev => [...prev, newShape]);
    setNewShape({})
  };
```

https://codesandbox.io/s/festive-dew-tkffwl?file=/src/App.js

**Comment by ThangLe3111996** [comment]
Thank you so much

I have one more question about this problem. When i keep shift to draw ellipse become circle, i set radius X = radius Y. But it not work like i hope. I try to check with dx, dy but still so. Can you help me about this :(  I hope it work like video below 

https://codesandbox.io/s/mystifying-murdock-23vcdg?file=/src/App.js

https://github.com/konvajs/konva/assets/65648064/7cb792cb-ace1-432b-83e1-a7116b1a52db
