### ISSUE TITLE
Group and Node documentation

### ISSUE THREAD

**Issue by ada99** [konvajs/konva#159]
Group and Node don't have getSelfRect method. It appears only in Shape. Group has nested method from Container -  getClientRect, so getSelfRect could be realized in the same way in Container.

**Comment by lavrton** [comment]
@ada99 So what is your question or issue?

**Comment by lavrton** [comment]
@ada99 do you mean remove `getSelfRect` from documentation?

**Comment by lavrton** [comment]
It was typo in documentation.
Fixed by https://github.com/konvajs/konva/commit/c7de29389faf9b706a1a733f07b7a2ae7656fed9

**Comment by ada99** [comment]
How about something like this:
https://github.com/ada99/konva/commit/b78a7db074c9df18d6b64e29de75bcbd34542e45
?

**Comment by lavrton** [comment]
What is a use case of this function? Any difference from `getClientRect()`?

**Comment by ada99** [comment]
It does not take in consideration shape styles (like shadow), and it should be faster a bit
