### ISSUE TITLE
[Feature request] Possibility to customize transformer rotate cursor

### ISSUE THREAD

**Issue by iloabn** [konvajs/konva#1590]
First of all. Thank you (and all other contributors). Konva is **very** useful.

I'd be willing to implement this and create a PR, but I first wanted to ensure that it could be valuable and isn't some other way that it should've rather be done.

# The issue
We have through user testing discovered that a significant amount of our users get a little confused with the crosshair cursor when hovering over the rotate anchor for the transformer and are unable to figure out that they need to drag it to rotate.
We have tried a bit ourselves to fix it, but feel as if we are unable to override the crosshair with something else without doing any changes to Konva itself.

# The proposal
My proposal is that a new property is added to `TransformerConfig` that has a name similar to `rotateAnchorCursor?: string;` that is a string which would be used on line [98](https://github.com/konvajs/konva/blob/a8959e1b40eeeda01415a8131794291f76269e7e/src/shapes/Transformer.ts#L98) to enable a different cursor to be used. The crosshair would still be the default if no item was specified. Could be looking something like this:

```javascript
/**
 * get/set rotation anchor cursor
 * @name Konva.Transformer#rotateAnchorCursor
 * @method
 * @param {String} cursorName
 * @returns {String}
 * @example
 * // get
 * var currentRotationAnchorCursor = transformer.rotateAnchorCursor();
 *
 * // set
 * transformer.rotateAnchorCursor('grab');
 */
Factory.addGetterSetter(Transformer, 'rotateAnchorCursor', 'crosshair');
```

# The question
Does this make sense and should we implement a PR adding this new config? Or is there a better way that we should be using instead to change the cursor for the rotate anchor on the transformer.

Thanks for reading ❤️ Hope I managed to format this request in a usable and understandable way.

**Comment by lavrton** [comment]
That may be useful. But what cursor will you use instead?

**Comment by iloabn** [comment]
@lavrton we would probably use `grab` to indicate that the anchor can be dragged around. 
It might also change depending on future user research we do. Which is why I wanted my suggestion to be as configurable as possible instead of simply request the default to be changed or a boolean to change between two values.

**Comment by lavrton** [comment]
That will be ok. I am just thinking about the case, where we may want to set the cursor dynamically based on some attributes. Like this:

![Kapture 2023-07-04 at 12 24 26](https://github.com/konvajs/konva/assets/1443320/50c217c5-aae4-4238-9359-3c2831d4590c)

But probably we will be able to do that even with your suggested API:

```js
tr.on('transform', () => {
   const rotation = node.rotation();
   const cursor = generateCSSCursor(rotation); // a functio that will return base64 svg.
   tr.rotateAnchorCursor(cursor);
})
```

**Comment by bsibar-striveworks** [comment]
Hi, 
Is there maybe example of your generateCSSCursor function. Same one you used in example on .gif file. 

Thanks in advance.
