### ISSUE TITLE
Pixelate Filter Does Not Render Using Specified Pixel Size and Creates Dark Lines

### ISSUE THREAD

**Issue by dlamprey** [konvajs/konva#1591]
When applying the pixelate filter to an image (a cropped section of a specified image in my case), I found there are two problems: 1. the size of the pixels in the filtered image are not the size specified in the pixelSize value. 2. dark edges will sometimes appear on the bottom and right sides of the filtered image (potentially caused by 1.).

![Screenshot 2023-06-27 152556](https://github.com/konvajs/konva/assets/48389685/532d7a8a-a77a-4d5d-81c1-699a71918042)

Before I created the code example provided here, I assumed the pixel size of the filter was as specified. Based on that, I tried forcing the size of the cropped image that was filtered using pixelation to be a multiple of the pixel size and also tried factoring in the scale, but in all cases, a dark line would appear, though it was not as pronounced with a larger pixel size.

See the code sample to reproduce the problem. Note that the appearance of the dark line may appear differently depending on the resolution and color settings of your monitor. Also, the code uses a scale of 1, but changing it to a higher value should make the problem more visible and also show what the pixelate filter does when scaled, which may also be an issue that needs attention.

`<!DOCTYPE html>
<html>
  <head>
    <script src="https://unpkg.com/konva@9.2.0/konva.min.js"></script>
    <meta charset="utf-8" />
    <title>Konva Image Demo</title>
    <style>
      body {
        overflow: hidden;
      }
    </style>
  </head>
  <body>
    <div id="container"></div>
    <script>
      const config = {
        canvas: { width: window.innerWidth, height: window.innerHeight },
        filter: { pixelSize: 5 },
        image: { naturalWidth: 500, naturalHeight: 500, scale: 1 },
        imageCropped: { width: 100, height: 100 },
        shapeReference: { colorOdd: "white", colorEven: "black" },
      };

      const image = document.createElement("img");
      image.crossOrigin = "anonymous";
      image.src = `https://placekitten.com/${config.image.naturalWidth}/${config.image.naturalHeight}`;

      var stage = new Konva.Stage({
        container: "container",
        width: config.canvas.width,
        height: config.canvas.height,
      });

      var layer = new Konva.Layer();
      stage.add(layer);

      image.onload = async function () {
        // await image.decode(); // used to dynamically determine natural dimensions - not needed, in config

        var imageOriginal = new Konva.Image({
          x: 0,
          y: 0,
          scaleX: config.image.scale,
          scaleY: config.image.scale,
          image,
          width: config.image.naturalWidth,
          height: config.image.naturalHeight,
        });

        var imageFiltered = new Konva.Image({
          cropX: 0,
          cropY: 0,
          cropWidth: config.imageCropped.width,
          cropHeight: config.imageCropped.height,
          x: 0,
          y: 0,
          scaleX: config.image.scale,
          scaleY: config.image.scale,
          image,
          width: config.imageCropped.width,
          height: config.imageCropped.height,
          pixelSize: config.filter.pixelSize,
        });

        imageFiltered.cache();

        imageFiltered.filters([Konva.Filters.Pixelate]);

        const addShapeReference = () => {
          let isOdd = false;
          let x = 0;
          do {
            var rect = new Konva.Shape({
              x: 0,
              y: 0,
              fill: config.shapeReference.colorEven,
              width: config.filter.pixelSize * config.image.scale,
              height: config.filter.pixelSize * config.image.scale,
              sceneFunc: function (context, shape) {
                context.beginPath();
                // don't need to set position of rect, Konva will handle it
                context.rect(
                  0,
                  0,
                  shape.getAttr("width"),
                  shape.getAttr("height")
                );
                // (!) Konva specific method, it is very important
                // it will apply are required styles
                context.fillStrokeShape(shape);
              },
            });

            rect.setAttr("x", x);
            isOdd && rect.setAttr("fill", config.shapeReference.colorOdd);
            layer.add(rect);
            x += config.filter.pixelSize * config.image.scale;
            isOdd = !isOdd;
          } while (x < config.imageCropped.width * config.image.scale);
        };

        // add the shapes to the layer
        layer.add(imageOriginal, imageFiltered);
        addShapeReference();
      };
    </script>
  </body>
</html>`

**Comment by lavrton** [comment]
I was trying to find something in the Pixelate filter, but I don't see why it is not working correctly for such case...

**Comment by dlamprey** [comment]
thanks very much for looking into this. i have done some more testing with my code and found some things that may help figure out the cause:

1. Windows display scaling is a factor. When i change it to 100%, there are no dark lines / or fractional filter pixels. (Changing the display resolution has no effect on the problem.) This is when I was seeing the problem:
![image](https://github.com/konvajs/konva/assets/48389685/e825959a-ff7d-45ea-bd02-afbf55ba52e0)
2. When setting the display scaling to 100%, I found that the pixelated filter always creates 5 pixels per pixelSize - if you specify a pixelSize of 20, the rendered filter shows 5 pixels:
![image](https://github.com/konvajs/konva/assets/48389685/f7734f14-a7c2-4beb-88cd-73952199b58b)

Do you know of an easy way to add the code for the pixelate filter directly into the code example so I can more easily analyze it to see why it is generating 5x the number of pixels and see if there is a way to have it ignore Windows display scaling?

https://github.com/konvajs/konva/blob/c1ba9740b3af9d7d783b1256218ac9c279df3611/src/filters/Pixelate.ts#L21

**Comment by dlamprey** [comment]
i should have kept better track of the variables before submitting my last comment. disregard item 2. i am confident that the cause of the problem is when either the Windows display scaling is not 100% *or* the browser zoom is not 100% (or both). it seems that a solution would be to test for both of those and set the pixelSize or cropped image size accordingly in code. assuming you confirm the same, it would be good to note this in your documentation somewhere to help others that encounter the same problem. and any suggestions on how to test for browser zoom and OS display scaling would be appreciated. thanks again.

this screenshot shows what it looks like with Windows display scaling set to 250% and browser zoom 100% - 2 1/2 pixels per pixelSize:
![image](https://github.com/konvajs/konva/assets/48389685/d0da991c-3a59-4902-bc97-e412d43673f0)

**Comment by dlamprey** [comment]
ok, so i found that this gives me what i need to fix the problem: window.devicePixelRatio. it accounts for both the Windows display scaling along with browser zoom. would it make sense to incorporate this into the Konva codebase? maybe it affects other features? for now, i'll add code that factors this into the pixelSize used for the filter.

**Comment by lavrton** [comment]
You can try caching with lower pixel ratio: `node.cache({ pixelRatio: 1 })`

**Comment by dlamprey** [comment]
that did it!!! thanks so much.
