### ISSUE TITLE
Watching for node changes

### ISSUE THREAD

**Issue by maitrungduc1410** [konvajs/konva#1593]
Hi @lavrton,

is there any way to watch for changes related to a Konva node (children change, attributes change,....)?

**Comment by lavrton** [comment]
Not much. Containers (Stage, Layer, Group) have `add` event. All nodes has change events for all attributes. Like `node.on('xChange fillChange', callback)`. But I think using them is antipattern. Why do you need it?

**Comment by maitrungduc1410** [comment]
In my case, whenever a node is changed (added, attributes updated,...), at any level, I need to trigger an API.

I was asking if something similar to MutationObserver (for DOM) that I can use for this purpose

**Comment by lavrton** [comment]
Konva doesn't have that. A possible solution is to listen to `draw` event on the layer. It will be triggered on any changes.

```js
layer.on('draw', () => {
   debounceCallAPI();
});
```

**Comment by maitrungduc1410** [comment]
got it, thanks
