### ISSUE TITLE
Error on Transformer with Group-Node

### ISSUE THREAD

**Issue by CaptAhab30** [konvajs/konva#1595]
When I put a Group in a Transformer, it causes an error in the current version of Konja. In version 9.0.0 it still works. From version 9.0.1 on it does not work anymore.
Example: http://jsbin.com/lurakakuva/2/edit?js,output
In the HTML you can set the version. The JS file must then be adapted (node -> nodes).

**Comment by lavrton** [comment]
Works just fine: https://jsbin.com/sozaburozu/edit?html,js,output
