### ISSUE TITLE
Get Node Global Position

### ISSUE THREAD

**Issue by maitrungduc1410** [konvajs/konva#1598]
I'm not really clear on how to get global position of a node.

I see there're 2 methods: `getClientRect` and `getAbsolutePosition`.

Which one should give me global position can you please help and what are differences between them? @lavrton 

Thanks

**Comment by lavrton** [comment]
It depends on your definition of `global position`. `node.getAbsolutePosition()` will return `x, y` of a node relative to top left corner of the canvas. `node.getClientRect()` return's bounding box of a shape.
