### ISSUE TITLE
Adding re sizable Logo to existing wallpaper Generator

### ISSUE THREAD

**Issue by devbikshu** [konvajs/konva#160]
Hi,

I have a requirement that i need to add re sizable logo to my existing wallpaper generator before it gets Cropped.

My Site Url : http://cricmovie.com/bb-imagecrop/

My target is to build site like : http://apps.warnerbros.com/pacificrim/wallpapergenerator/

The main difference in both is adding logo before wallpaper gets cropped. i need to add logo to this.

I am very new to programming. Any Help will be grateful.

**Comment by lavrton** [comment]
Close as not directly related to `Konva`.
