### ISSUE TITLE
Rect default strokeWidth - 2px?? Bug or feature?

### ISSUE THREAD

**Issue by dendrofen** [konvajs/konva#1604]
Why by **default**, if I don't set **strokeWidth** of Rect, this value **is equal to 2?** Is it a bug? 🧙

Is it not specified in the documentation?

**Comment by lavrton** [comment]
It is not a bug. It is just the default value. A long time ago, stroke width 2 worked better on non-hdpi devices. So, it was used as a default.

**Comment by dendrofen** [comment]
Cool, let's add strokeWidth default value to project docs. 
This takes me a lot of time to understand why my stage is wrong size after adding nodes with precise dimensions.
