### ISSUE TITLE
Can't transform shape less than in 1px (h/w)

### ISSUE THREAD

**Issue by MatteoGauthier** [konvajs/konva#1605]
Hi, I hope everyone is doing well! I have a question about transforms, I'd like to resize a Rectangle with a height of less than 1px because it doesn't work, here's a reproduction (with react-konva) : https://codesandbox.io/s/vibrant-gagarin-qyypzp?file=/src/index.js

I tried to increase the hit box with hitFunc and using the hitStrokeWidth props, but this doesn't fix the issue...

Can anyone help me? Have a nice day!

**Comment by lavrton** [comment]
Konva has internal check for 1px size. What is your use case for such a rect? How do you want to resize it?

**Comment by MatteoGauthier** [comment]
Hey @lavrton, I want to create an Horizontal Line shape that can be used in an editor. I already have Text, Rectangle, Images, and now I'd like to create a horizontal line component with a height of less than 1px. This shape name is also known as divider or separator
