### ISSUE TITLE
the Transformer Property anchor  can add diffrent image or icon 

### ISSUE THREAD

**Issue by sweetsmile888** [konvajs/konva#1606]
the Transformer Property  anchor can add diffrent image or icon？ like blow:

![111](https://github.com/konvajs/konva/assets/23272503/82e65e63-5600-45c0-b34a-00bcd5963fae)

**Comment by lavrton** [comment]
You can use https://konvajs.org/api/Konva.Transformer.html#anchorStyleFunc for that. Inside the function you can set background image.

**Comment by sweetsmile888** [comment]
seems Transformer has no Properties can  set background image,whuch Properties  below can do?
![1](https://github.com/konvajs/konva/assets/23272503/ace98e11-bc78-40e6-9e42-b321b81cdccb)
![2](https://github.com/konvajs/konva/assets/23272503/bc0d439b-48f3-4745-9b61-e4ea5acfd32c)

**Comment by lavrton** [comment]
Every anchor in Transformer is a simple instance of `Konva.Rect` shape. So in `anchorStyleFunc` you can change properties of such rectangle.

**Comment by wuwentao-web** [comment]
const tr = new Konva.Transformer({
                rotateLineVisible: false,
                rotateAnchorOffset: 13,
                anchorSize: 7,
                rotationSnaps: [0, 90, 180, 270],
                enabledAnchors: ['top-left', 'top-right', 'bottom-left', 'bottom-right'],
                flipEnabled: false,
                anchorStyleFunc: (anchor) => {
                    if (anchor.getAttrs().name === 'rotater _anchor') {
                        // 通过设置锚点为图片来自定义旋转图标
                        const rotateIcon = new Image();
                        rotateIcon.src = instructionsDraw; // 这里是你自定义旋转图标的路径
                        anchor.fillPatternImage(rotateIcon);
                    }
                }
            })
此方法更改为自定义图标没有生效
