### ISSUE TITLE
Performance issue for _clearCache

### ISSUE THREAD

**Issue by yinguangyao** [konvajs/konva#1608]
This is an example given by Leaferjs, comparing the time required to create 1 million rectangles.
Konva takes the longest time to create 1 million rectangles, approximately over 40 seconds
Here is a Flame Graph created by Konva with 330000 rectangles, it can be seen that `_getProtoListeners` is called frequently

<img width="1722" alt="image" src="https://github.com/konvajs/konva/assets/16210045/7a39812a-2b16-4804-b787-b9d57e66bcc1">

The culprit is that the `absoluteTransformChange` event is sent, because `fire` calls `_getProtoListeners`

```js
  _clearSelfAndDescendantCache(attr?: string) {
    this._clearCache(attr);
    // trigger clear cache, so transformer can use it
    if (attr === ABSOLUTE_TRANSFORM) {
      this.fire('absoluteTransformChange');
    }
  }
```

Is it possible to judge that if there is no Transformer, do not fire?

**Comment by lavrton** [comment]
I am not sure if it will help much. Need to verify that first.
