### ISSUE TITLE
Cache and scale

### ISSUE THREAD

**Issue by iskiselev** [konvajs/konva#161]
I need to scale whole canvas, and at the same time preserve clarity of object that was drawn.
Some of this objects are cached (I've called `.cache()` method on them).

Is there any way to cache them with appropriate scale? (Earlier, before 0.9.0, I was able to pass scale parameter inside cache() method).

**Comment by lavrton** [comment]
@iskiselev In my opinion, that best way for that is to wrap a component into a group, scale the component and then cache the group: http://jsbin.com/tihojehivo/edit?html,js,output

Or we can add new parameter `pixelRatio` for cache function to save it with higher resolution. PR is welcome.

**Comment by lavrton** [comment]
So we have `pixelRatio` in cache function now.

It will be nice to have a demo on site.
