### ISSUE TITLE
how can i scale the group of Text(text-size) and Path 

### ISSUE THREAD

**Issue by heyhaiderhere** [konvajs/konva#1611]
how can i scale the group of Text(text-size) and Path but if middle-right or middle-left anchors are triggered i want to change the width of group and the text inside

`<Group ref={grpRef} draggable={false} disableCondition={true}>
          {rows.map((item, rowsIndex) => {
            return item.elements.map((element, elementIndex) => {
              return (
                <>
                  {element?.props?.type === "icon" ? (
                    <KonvaImage
                      {...element.props}
                      draggable={false}
                      ref={imageRef}
                    />
                  ) : (
                    <>
                      <TextElement
                        ref={textRef}
                        key={`rows-${elementIndex}`}
                        width={groupWidth}
                        {...element.props}
                        draggable={false}
                        id={`${element?.props?.id}`}
                        type={"menu"}
                      />
                    </>
                  )}
                </>
              );
            });
          })}
        </Group>
      </Group>
      <Transformer
        onTransform={handleTransform}
        rotateEnabled={false}
        ref={trRef}
      />`

**Comment by lavrton** [comment]
I don't understand what you want. Can you clarify and make a small demo?

**Comment by heyhaiderhere** [comment]
> 

https://we.tl/t-2ph81E7mRu
here is the video of problem i am facing right now, when the zoom scale is on 85 it works just Fine but other than 85 it messes up the width

**Comment by lavrton** [comment]
Hard to say from the video what is wrong. Make a very small demo.
