### ISSUE TITLE
Add releases to GitHub

### ISSUE THREAD

**Issue by Andrioden** [konvajs/konva#1613]
I would like to suggest that releases with changelog are added as a GitHub release, this makes it easier to follow your project. 

A few perspectives:
- When considering a lib, I always check for last commit date and last releases date to determine viability of project. Right now Konva is misrepresented as last release in 2018.
- I have pinned versions on most important libaries i use, inkluding Konva, and need to manually detect and apply updates. I do use npm to apply the updates thou, not the GitHub releases themselves.
- I use GitHub dashboard to pay attention to new releases for libaries i use, its a great way to do so!

**Comment by lavrton** [comment]
https://github.com/konvajs/konva/releases
