### ISSUE TITLE
Change zindex with multi shapes

### ISSUE THREAD

**Issue by ThangLe3111996** [konvajs/konva#1615]
I hvave a question about zindex

I have an array includes shapes. When i click button set zindex, i want to run for loop to moveup each item but only first item action. I know when i moveup firsttime in for loop, layer children change. Can you help me to change zindex with multi shapes?

https://codesandbox.io/s/nice-sea-4qs3f3

**Comment by dendrofen** [comment]
try to handle items's zIndex inside state

**Comment by lavrton** [comment]
First, it is better to do that in "react" way. Do not move nodes manually. Do not access them via `ref`, instead just update z index in the state, as @dendrofen mentioned. Remember to use `key` property for your circle render.

Now, what do you want to do on button click? I don't understand from the code. What does it mean to move every child up? How will it look after operation?

**Comment by ThangLe3111996** [comment]
I have a problem. I have 10 circle with zindex. When i select randome two circle, then i click button set zindex, i want to two selected circles change zindex up or down. So i use for loop for it. 

Example: I selected circle have zindex 4 and 8. When i click button set zindex, zindex of two circles will become 3 and 7. Now, create new array with zindex of circles was changed.

**Comment by lavrton** [comment]
Then make a demo when you are trying to do that with just two shapes.

**Comment by ThangLe3111996** [comment]
But, i want to do that with multi shapes not two shapes :(

**Comment by ThangLe3111996** [comment]
Thanks you for support from you. I try to do this and this is result which i want
https://codesandbox.io/s/nice-sea-4qs3f3?file=/src/index.js
