### ISSUE TITLE
How to drag the stage to complete other events

### ISSUE THREAD

**Issue by SF-Simon** [konvajs/konva#1616]
We need to use drag and drop events on the stage, but we do not want any movement on the stage to complete functions such as batch selection of areas.

We tried using _mousemove touchmove_ to complete the region calculation, but found that after leaving the canvas, this region became invalid, which is not what we wanted.

So we want to use the drag function of the stage to complete it, but we don't know how to prevent the stage from being offset.

**Comment by lavrton** [comment]
Do not use drag for such functions. Instead, listen to `mousedown touchstart` on stage. Then listen to `mousemove touchmove` and `mouseup touchend` on window object. So it will still trigger, even if you go out of the canvas.

**Comment by SF-Simon** [comment]
> Do not use drag for such functions. Instead, listen to `mousedown touchstart` on stage. Then listen to `mousemove touchmove` and `mouseup touchend` on window object. So it will still trigger, even if you go out of the canvas.

But it cannot be triggered like dragging, even if it leaves the browser range.

**Comment by lavrton** [comment]
Can you make a little demo?
