### ISSUE TITLE
Большое количество элементов

### ISSUE THREAD

**Issue by aportx** [konvajs/konva#162]
Привет!
Делаю интерактивную карту галактики для игры. на карте планируется около 50-100 тысяч элементов(планеты, астероиды, летящий флот) - шейпы, картинки итп.  Карту можно двигать и изменять масштаб. на каждый элемен нужно повешать несколько событий, к примеру открытие меню, построение путей по клику итд.. в общем много чего.
Вопрос в том, получится ли сделать такую карту на этом фреймворке, взять какой то другой или стоит писать самому на нативном js?

**Comment by lavrton** [comment]
А сколько элементов планируется отображать в один момент на экране? Логично будет не рисовать элементы, которые не входят на экран или слишком маленький (при изменении масштаба).

Для игр рекомендую http://www.pixijs.com/ или http://phaser.io/. Они умеют рисовать через webgl. Это может сначительно повысить производительность (в зависимости от самого приложения).

На нативном писaть не рекомендую. Лучше сначала попробовать какой-либо фреймворк и получить работающий результат как можно раньше и уже потом оптимизировать.

**Comment by aportx** [comment]
@lavrton ну все планировал отображать. это же игровая карта, игроку надо видеть общую ситуацию в игровом мире. 
webgl нельзя использовать по заданию. только канвас.

**Comment by lavrton** [comment]
50-100 тыс одновременно? Как будет тогда выглядеть каждый элемент? Один пиксель?

**Comment by GitHubKonva** [comment]
For the benefit of others can the above please be translated to the English language?

**Comment by aportx** [comment]
@lavrton ну да. не в один пиксель. 
вариант первый: 
размер планет и галактик в нормальном виде. при изменении масштаба мелкие элементы скрываются, ана их месте появляются другие, которые отображают менее детальную информацию.
вариат второй:
не делать большое уменьшение масштаба и не подменять элементы. но тогда придется отображать все элементы, либо с подгрузкой динамической. правда это плохой вариант, потому что большая нагрузка на сервер будет. карта хранится в базе.
-------------------------------
@GitHubKonva I'm sorry , I do not know English . you have to use Google translator .

**Comment by aportx** [comment]
вот пример того что хочу получить
http://www.pcinvasion.com/wp-content/uploads/2016/05/stellaris-2D-Galaxy.jpg
каждая вершина это галактика в которой от 1 до 9 планет
на картинке немного галактик. у меня 5 тысяч. соответственно 45 000 планет примерно.
только вот я не хотел бы делать подмену. хотел бы отображать все планеты. просто при изменении масштаба они становятся точками, и сливаясь вместе визуально выглядят как одна вершина.
есть только одна проблема - firefox дико тормодит даже при 1000 планетах.

**Comment by aportx** [comment]
вот скрин рабочего прототипа галактики
http://s8.hostingkartinok.com/uploads/images/2016/08/582d5ef6e0cd699802e5d2c4d37eecbd.png
это максимальное приближение до просмотра галактики. карту можно двигать, рядом другие находятся.
а вот скрин максимального отдаления:
http://s8.hostingkartinok.com/uploads/images/2016/08/4f79ad1ef30710e04c84d0962e10090d.png
зеленые точки это как раз галактики с кругами

**Comment by lavrton** [comment]
> только вот я не хотел бы делать подмену. хотел бы отображать все планеты. просто при изменении масштаба они становятся точками, и сливаясь вместе визуально выглядят как одна вершина.

Я думаю такой вариант будет плохо работать. Слишком много элеменов. Лучше делать подмену. Иначе - пробовать webgl с частицами.

Всё что плохо видно, или не видно вообще на экране лучше удалять.

Для лучшего результата лучше взять несколько фреймворков и подходов и сделать прототип на каждом и сравнить производительность.

> ПС: зачем закрыли мой вопрос?

Потому что на первоночальный вопрос я ответил. Остальное не имеет прямого отношения к `Konva`.

**Comment by aportx** [comment]
понятно. ну у меня те же мысли были примерно.
а на Konva реально написать подмену?
к примеру при скроле сделать переключение по щелчку, которое будет "переключать" и соответственно подменять контент.
если да то можете набросать пример простейший с подменой круга на квадрат по щелчку..
я не особо силен пока в js. мне бы кусок кода простой, а дальше разберусь..
