### ISSUE TITLE
Snap rect on resize to grid

### ISSUE THREAD

**Issue by zkobrinsky** [konvajs/konva#1622]
Hello!

I'm trying to snap a rect to grid lines drawn on a separate layer and I'm having some difficulty. My solutions work, but only if the rectangle is already snapped to the grid. If it's in between grid lines, though, I'm having trouble compensating to find the nearest grid line. For now, I'm just using this function for development that only deals with moving the right anchor to the right:
```

case activeAnchor === "middle-right" &&
            newBox.width % gridSize > gridSize - snappingThreshold: {
            // Calculate the new width and adjust it to snap to the nearest grid line
            const newWidth = Math.round(newBox.width / gridSize) * gridSize

            // Adjust the new width to snap to the nearest grid line
            newBox.width = newWidth

            // Return the adjusted bounding box
            return newBox
          }
```

**Comment by zkobrinsky** [comment]
I should add: the gridSize values I'm using are not in absolute coordinates. I wonder if that's part of the issue trying to create an offset?

**Comment by zkobrinsky** [comment]
Basically I'm having a hard time getting the offset between newBox.x and its nearest gridLine.

**Comment by lavrton** [comment]
Please make a small demo.

**Comment by zkobrinsky** [comment]
I'm unable, as it's proprietary work. Any idea how one might get the coordinates of the nearest gridLine?

**Comment by lavrton** [comment]
You don't need to replicate the full app. Just a tiny part of snapping for demo.

**Comment by zkobrinsky** [comment]
I think I figured it out. Needed to get the stageX in absolute coordinates to be able to calculate where the nearest grid line is:

`const newWidth = Math.round(newBox.width / gridSize) * gridSize

            const gridsToLeftX =
              (newBox.x - stageNode.value.getAbsolutePosition().x) / gridSize

            const offsetX = (Math.round(gridsToLeftX) - gridsToLeftX) * gridSize

            newBox.width = newWidth + offsetX

            // Return the adjusted bounding box
            return newBox`
