### ISSUE TITLE
Can I add a filter method to the context class?

### ISSUE THREAD

**Issue by mrskiro** [konvajs/konva#1623]
Hi. Thank you for always doing maintenance.

Do you plan to add `filter` method to the Context class? Can i add?

Currently, we need to go through `setAttr`. I spent a little time realizing this.

example
```
const layer = new Layer()
layer.getContext().setAttr("filter", "blur(10px)")

// want...
layer.getContext().filter("blur(10px)")
```

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/filter

Thanks.

**Comment by lavrton** [comment]
I am not sure if it will give desired result for most of konva use cases. Did you try to use it?
