### ISSUE TITLE
haveIntersect function - any similar functions that takes into account rotation? 

### ISSUE THREAD

**Issue by hnnhmd** [konvajs/konva#1627]
Hi @lavrton, 

Given that the haveIntersection function of Konva is the following: 
```
function haveIntersection(r1, r2) {
   return !(
//condition1
      r2.x > r1.x + r1.width ||
//condition2
      r2.x + r2.width < r1.x ||
//condition3
      r2.y > r1.y + r1.height ||
//condition4
      r2.y + r2.height < r1.y 
   );
} 
```

Is there any functions that account for the rotation of the shapes r1 and r2? The function above assumes that both the shapes are not rotated at all. 

For example, if I had a rectangle r1, with a height of 1, and a width of 100, at (0,0), and another rectangle r2, at (10,10) - 
the formula above would not flag out them as intersecting, due to condition 3. Even though r1 might be at a 45 degree angle or so
and would be intersecting with r2. 

Thanks much! 

Adding @maitrungduc1410 to the thread as well.

**Comment by lavrton** [comment]
`haveIntersection()` check only client rectangle intersections as described in docs:

> const overlapping = Konva.Util.haveIntersection(shape1.getClientRect(), shape2.getClientRect());

If you have rotated rectangles, you need to use your own math. This may help: https://stackoverflow.com/questions/10962379/how-to-check-intersection-between-2-rotated-rectangles
