### ISSUE TITLE
Add font-weight support

### ISSUE THREAD

**Issue by JorisAerts** [konvajs/konva#1629]
Add font-weight support to TextConfig.

(https://www.w3schools.com/jsref/playcanvas.php?filename=playcanvas_fontweight)

**Comment by lavrton** [comment]
We have `fontStyle` for that. `new Konva.Text({ fontStyle: 'bold' })`

**Comment by lavrton** [comment]
I think numerical value will work too.

**Comment by lavrton** [comment]
We just need to update the docs.
