### ISSUE TITLE
`getIntersection` has incorrect TypeScript result type

### ISSUE THREAD

**Issue by fxOne** [konvajs/konva#1630]
TypeScript version 5.1.6

The result of the ´getIntersection´ method should be `Shape<import("./Shape.js").ShapeConfig> | null` and not just `Shape<import("./Shape.js").ShapeConfig>` as be defined in Stage.d.ts.

I have also noticed incorrect return types in a few other places. Maybe consider using something like [explicit-function-return-type](https://typescript-eslint.io/rules/explicit-function-return-type/) to avoid these problems in the future.

If you are interested I can try to create a pull request.

**Comment by lavrton** [comment]
Yeah, that is not correct.

I would avoid writing explicit return type and instead apply strict mode for typescript, so types are automatically and correctly returned from the functions.

**Comment by lavrton** [comment]
Fixed
