### ISSUE TITLE
Blur Filter makes the right edge white

### ISSUE THREAD

**Issue by mrskiro** [konvajs/konva#1631]
Hi, thanks for everything.

I am currently trying to implement the ability to Blur a portion of an image.
I am trying to copy part of the background and make it Blur, but the right edge is white.
Is there any way to work around this?

demo https://stackblitz.com/edit/stackblitz-starters-mpckua?file=src%2FApp.tsx

**Comment by lavrton** [comment]
I don't see while edge. Can you specify steps to reproduce or show how does it look to you?
