### ISSUE TITLE
How to rotate a shape from a different origin point outside of shape and fill various patterns in shapes

### ISSUE THREAD

**Issue by vikkyjain2013** [konvajs/konva#1638]
Hi Team,

Thanks for this wonderful library. I have started exploring this library to check if it fits into some of my project requirements. I am currently looking for two answers here:

1. How can i rotate a object through a point which is not inside that shape ? Assume i have a shape drawn at (10,10) and (200,100). Now i want to rotate this shape assuming its center point is located at (15,5). This point is outside of this shape. How can we achieve that ?

2. I want to fill any kind of shapes with various patterns like horizontal lines, vertical lines, diagonal lines. When user zoom-into those shapes, gap between pattern should remain constant. It should not increase or decrease. Intensity of stroke should also be consistent. If require, i can provide a gif for this as well.

Thanks,
Vj

**Comment by vikkyjain2013** [comment]
![recordings](https://github.com/konvajs/konva/assets/131866319/524522c9-a699-4a37-b923-de7549c3bf1a)

**Comment by lavrton** [comment]
> How can i rotate a object through a point which is not inside that shape ?

There are two ways.

1. You can use the `offset` property to set the "origin" of the shape. It will be rotated around its origin. But also its `x` and `y` will point to the origin, so you may need update them. For more info: https://konvajs.org/docs/posts/Position_vs_Offset.html#sidebar

2. Use pure math for that. Calculate where should be the new {x,y} (top-left for a rectangle) position.

> When user zoom-into those shapes, gap between pattern should remain constant.

I think I would use `fillPatternImage` + `fillPatternScale`. `fillPatternScale` should be reversed to global zoom. So if you zoom in twice, you should "zoom out" pattern twice.

```js
container.scale({x : 2, y: 2 });
rect.fillPatternScale({ x: 0.5, y: 0.5 }):
```

**Comment by vikkyjain2013** [comment]
@lavrton 
I created this stackblitz for rotation functionality. 
I have one group with rectangle shapes. I want to rotate the group from a point(10,10), but seems like it is not taking that as origin point after setting offset. Can you please take a look ?
https://stackblitz.com/edit/konva-6gc5mq?file=index.ts

**Comment by lavrton** [comment]
Once you set offset, you may have to set position differently. `square.position(circle.position());`

https://stackblitz.com/edit/konva-mxupdd?file=index.ts

**Comment by vikkyjain2013** [comment]
Hi @lavrton,

thanks for your update. If we set the position and then rotate, it is rotated as per new coordinates. 
My main requirement here is assume a shape at (10,10) lower left and (100,50) upper right, and i want to rotate this at 90 degree from origin point of (0,0). Once we rotate the shape, the nearest corner of rectangle to origin will stay at same length. 

For a reference, i created this stackblitz using threeJS: https://stackblitz.com/edit/three-js-start-3y7zhd?file=index.ts
I need something similar. 

In your stackblitz, i updated the coordinates: https://stackblitz.com/edit/konva-wquppy?file=index.ts
Now the shape group was at (10,10), and my origin point is (0,0), when i set the offset and set the position, group actually moved to that position, and then rotated.  but it rotated as per new position.  

I hope i am able to explain the problem statement.

**Comment by vikkyjain2013** [comment]
Hi @lavrton 

I implemented rotation from different origin point the method based on pure maths. Let me know if konva support this as functionality or we can use this method implementation in future. 

https://stackblitz.com/edit/konva-ztmtjn?file=index.ts

**Comment by lavrton** [comment]
I think having your own based is a very valid approach.

**Comment by vikkyjain2013** [comment]
I am following this approach now:

1. Rotate the Group object first irrespective of its origin.
2. After rotation, calculate the new position for group object. And this new position is calculated based on given function at the end.
3. Set the new position for the group.

```
function rotatePoint(x: number, y: number, originX: number, originY: number, angleInRadians: number): { x: number, y: number } {
    
  const cosAngle = Math.cos(angleInRadians);
  const sinAngle = Math.sin(angleInRadians);
  const newX = ((x - originX) * cosAngle) - ((y - originY) * sinAngle) + originX;
  const newY = ((x - originX) * sinAngle) + ((y - originY) * cosAngle) + originY;
  return { x: newX, y: newY };
}

```
