### ISSUE TITLE
Stage toDataURL vs the actual rendering on the stage is different

### ISSUE THREAD

**Issue by kishoreknowapp** [konvajs/konva#1641]
<img width="731" alt="image" src="https://github.com/konvajs/konva/assets/43332112/cfeeef4a-26e4-46b0-9527-75cf0a7989ea">

in the above image, left is what the toDataURL image is looking like and right is what Konva Stage is. Why both are not matching. See especially text look bolder in image.

**Comment by lavrton** [comment]
It looks like an effect of pixel antialiasing. By default `stage.toDataURL()` export with `pixel ratio = 1`. But on the screen it can be much higher (with much better quality). https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

You can export into data url with better quality: `stage.toDataURL({ pixelRatio: 2 })`. But it will give image with the bigger size.

**Comment by kishoreknowapp** [comment]
If I right click and choose copy image then I am getting proper image but only with toDataURL it is not giving as it is being shown.

![image](https://github.com/konvajs/konva/assets/43332112/8c2f0d37-9284-4ee5-ba1c-d57f0d3b0e52)

**Comment by kishoreknowapp** [comment]
![image](https://github.com/konvajs/konva/assets/43332112/f827df52-c9c3-46b6-b168-0b93de7b2428)

this is how it is showing if I choose browser right click and choose copy image of the canvas.
