### ISSUE TITLE
Emojis with letterSpacing don't display correctly.

### ISSUE THREAD

**Issue by xkxx** [konvajs/konva#1642]
`Konva.Text` doesn't handle compound emojis such as skin-tone faces. When displayed, it breaks them up into component pieces.

Repro in v9.2.1: https://codesandbox.io/s/konva-playground-forked-mnw476

I have tested these kinds of emojis:
- Fitzpatrick types: 👧👧🏻👧🏼👧🏽👧🏾👧🏿
- ZWJ: 👨‍👩‍👧

Related to https://github.com/konvajs/konva/issues/1099

**Comment by lavrton** [comment]
Hmm. I thought that was fixed. Then we have to find a way to handle it correctly.

**Comment by nickells** [comment]
I'm seeing similar issue with text ligatures ie a "tt" gets broken up when we add letter spacing where normally you'd see connected crossbars

**Comment by lavrton** [comment]
@nickells with what font?

**Comment by nickells** [comment]
hey @lavrton , i was sitting with this for a while and realized CSS does the same thing, so it is expected. https://stackoverflow.com/questions/77380337/keep-font-ligatures-and-have-tighter-letter-spacing
