### ISSUE TITLE
Image Resizing issue on removed background image

### ISSUE THREAD

**Issue by JPNXT6** [konvajs/konva#1644]
Hi,
 
  I am facing an issue with image resizing on overlay image with background image. I want to set the resizing only on image, not for entire image size. Please find the attached screenshot. That will help you to understand easily. I need you help to resolve the issue.

Thanks,
[Parivallal[](url)](![ImageResizeIssue](https://github.com/konvajs/konva/assets/119647899/d7c782d8-910a-4c8c-952b-3f96b3e08749))

**Comment by JPNXT6** [comment]
I am expecting the result looks like this
![ImageResizeFix](https://github.com/konvajs/konva/assets/119647899/a6afd1fa-65a0-439b-a327-1b98f117f021)

**Comment by lavrton** [comment]
The solution is:

1. Draw image into external canvas
2. Read raw pixel information (image data) from that canvas
3. Calculate the bounding box of an image. It shouldn't be hard, just iterate over all pixels, detect min/max area.
4. Create another canvas with the size of the bounding box. Draw image into that canvas with required offset.

Something like this:

```js
const canvas1 = document.getElementById('canvas1');
const ctx = canvas1.getContext('2d');

// Load image
const img = new Image();
img.src = '/path/to/image.jpg';
img.onload = function() {
    // Draw on canvas 1
    ctx.drawImage(img, 0, 0, img.width, img.height);
  
    // Get image data
    const imageData = ctx.getImageData(0, 0, canvas1.width, canvas1.height);
    const data = imageData.data;

    // Create variables for bounding box
    let minx = Infinity;
    let miny = Infinity;
    let maxx = -Infinity;
    let maxy = -Infinity;

    // Iterate over all pixels
    for(let i = 0; i < data.length; i += 4) {
        let r = data[i];
        let g = data[i+1];
        let b = data[i+2];
        let a = data[i+3];

        // If pixel is not transparent
        if(a > 0) {
            let x = (i / 4) % canvas1.width;
            let y = Math.floor((i / 4) / canvas1.width);
      
            if(x < minx) minx = x;
            if(y < miny) miny = y;
            if(x > maxx) maxx = x;
            if(y > maxy) maxy = y;
        }
    }

    // Create and setup canvas 2
    const canvas2 = document.createElement('canvas');
    canvas2.width = maxx - minx;
    canvas2.height = maxy - miny;
    const ctx2 = canvas2.getContext('2d');

    // Draw image on canvas 2
    ctx2.drawImage(canvas1, -minx, -miny);
};
```
