### ISSUE TITLE
Possible to fix blurry text without changing pixelRatio?

### ISSUE THREAD

**Issue by dasveloper** [konvajs/konva#1645]
I'm trying to work on a Canva style app where users can add text/shapes to a canvas and export it in various preset sizes (i.e. Instagram Post 1080x1080px). The text that's rendered on my canvas looks crisp, but when exported with toDataURL it comes out blurry looking, see below:

![imgonline-com-ua-twotoone-j3EHBTOINZT2TR](https://github.com/konvajs/konva/assets/28981975/b1e75d77-59a3-4882-81c8-db8fdb04c017)
(pretty hard to see in screenshots, but the right one has antialiasing blur around the text, more or less on different font sizes).

I've seen a few other issues around this and the answer is usually to increase the pixelRatio for the exported image. However, I don't want to do that because then the ex. Instagram Post 1080x1080px would now be 2160x2160px. I want to respect the canvas size the users set.

Is there any way to fix this or is it just a limitation of canvases?

Here is my code if it helps:

```
import { useRef } from "react";
import { Stage, Layer, Text, Rect } from "react-konva";

export default function App() {
  const stageRef = useRef(null);
  const handleExport = () => {
    const uri = stageRef.current.toDataURL();
    navigator.clipboard.writeText(uri);
  };
  return (
    <div className="min-h-screen bg-blue-100 p-12">
      <button className="mb-2" onClick={handleExport}>
        Copy data URL
      </button>
      <Stage width={800} height={400} ref={stageRef}>
        <Layer>
          <Rect width={800} height={600} x={0} y={0} fill="#ffffff" />
          <Text fontSize={32} text="This is some test text" x={20} y={20} />
        </Layer>
      </Stage>
    </div>
  );
}
```

**Comment by lavrton** [comment]
When you see canvas on most of modern devices (like a retina screen from Apple), the canvas has more pixels than you provide in the stage size. https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

There are just not enough pixels with default pixel ratio = 1 to keep the same quality.

Why do you care about that? 1080x1080 is still a large image. In you, can I see that you have a stage size of 800x400, so you can use a higher pixel ratio to match the 1080x1080 size.
