### ISSUE TITLE
Export picture The picture is not completely displayed

### ISSUE THREAD

**Issue by 1577100475** [konvajs/konva#1650]
While using konva, I exported images to the Group component and found that only a part of the image was exported and the rest was white. I used the attribute pixelRatio to enlarge the image, but it didn't work well
![1696996255234](https://github.com/konvajs/konva/assets/58699391/cc8a0b02-afbe-493b-9167-b7b9719693c6)

**Comment by lavrton** [comment]
Make a demo, please.
