### ISSUE TITLE
Polygon width big strokeWidth is spill out from transformer

### ISSUE THREAD

**Issue by ThangLe3111996** [konvajs/konva#1651]
Hi Anton,

I have a question and need your help
I draw a polygon and set attribute strokeWidth for this polygon is 30px. So it spill out from transformer. I want to fix that to polygon can fit with transformer

![image](https://github.com/konvajs/konva/assets/65648064/a78f9275-2372-409a-9851-93be96febe86)

**Comment by lavrton** [comment]
I don't think Konva has a simple solution for such a use case. The workaround is to use `padding` property for Transformer. But it will make it bigger in all directions.
