### ISSUE TITLE
After export getting corrupted image in konva react

### ISSUE THREAD

**Issue by Thamaraiselvam578** [konvajs/konva#1652]
Hello there, 
I'm facing an issue, 

I created a Stage with 3 Layers after I add 4 to 5 images for each layer and resized them with transformer and export the stage using dataURI but the half bottom image gets hidden. But image doesn't overflow out of the stage.

**Comment by lavrton** [comment]
Make a small demo.

**Comment by Thamaraiselvam578** [comment]
![n2xhujb5zeikb7g66jgcgkfykx](https://github.com/konvajs/konva/assets/113535041/78f88549-393c-48ea-b716-3d24c1ce7fb9)
I'm getting stage image like above after exporting

**Comment by lavrton** [comment]
Code demo?

**Comment by thamaraiSD060** [comment]
const UseImageLoader = (src, canvasDimension) => {
	const [image, setImage] = useState(null);
	const imageRef = useRef(null);
	const [ratio, setRatio] = useState({ width: 0, height: 0, newWidth: 0, newHeight: 0, imageX: 0, imageY: 0 });

	useEffect(() => {
		const img = new window.Image();
		img.onload = () => {
			const width = img.width
			const height = img.height
			const aspectRatio = width / height;

			let newWidth = canvasDimension.height;
			let newHeight = (height / width) * newWidth;

			if (newHeight > canvasDimension.height) {
				newHeight = canvasDimension.height;
				newWidth = newHeight * aspectRatio;
			}
			const imageX = (canvasDimension.width - newWidth) / 2;
			const imageY = (canvasDimension.height - newHeight) / 2;

			setRatio({ width: width, height: height, newWidth: newWidth, newHeight: newHeight, imageX: imageX, imageY: imageY, });
			setImage(img);
		};

		img.crossOrigin = "anonymous";
		img.src = src;
		imageRef.current = img


		return () => {
			img.onload = null;
		}
	}, [src])

	return { image, ratio };
};

const BackgroundImge = ({ currentImage, canvasWidth, canvasHeight }) => {
	const { image, ratio } = UseImageLoader(currentImage, { width: canvasWidth, height: canvasHeight });
	return (
		<Image
			x={ratio.imageX}
			y={ratio.imageY}
			width={ratio.newWidth}
			height={ratio.newHeight}
			image={image}
		/>
	);
};

const DraggedImages = ({ currentImage, canvasWidth, canvasHeight, isSelected, onSelect, onChange, draggable }) => {

	const { image, ratio } = UseImageLoader(currentImage.src, { width: canvasWidth, height: canvasHeight });
	const imageRef = useRef(null);
	const trRef = useRef(null);

	useEffect(() => {
		if (isSelected) {
			trRef.current.nodes([imageRef.current]);
			trRef.current.getLayer().batchDraw();
		}
	}, [isSelected]);

	return (
		<>
			<Image
				x={currentImage.x}
				y={currentImage.y}
				width={ratio.newWidth / 3}
				height={ratio.newHeight / 3}
				ref={imageRef}
				image={image}
				_id={currentImage._id}
				draggable={draggable}
				onDragStart={(e) => { onSelect(e.target) }}
				onDragEnd={(e) => { onChange(e.target) }}
				onDragMove={(e) => { }}
				onTransformEnd={(e) => { onChange(e.target) }}
			/>
			{isSelected && (
				<Transformer
					ref={trRef}
					boundBoxFunc={(oldBox, newBox) => {
						if (newBox.width < 5 || newBox.height < 5) {
							return oldBox;
						}
						return newBox;
					}}
				/>
			)}
		</>
	);
};

//Main Function

<Box
	onDrop={(e) => {
		e.preventDefault();
		if (!isDrawingMode) {
			stageRef.current.setPointersPositions(e);
			const droped = {
				...stageRef.current.getPointerPosition(),
				src: dragUrl.current,
				_id: keyGenerator(),
			}
			setDraggedImages(draggedImages.concat([{ ...droped, dropped: true }]));
		}
	}}
	onDragOver={(e) => e.preventDefault()}
	sx={{ height: 600, width: 800, background: "#fff", borderRadius: 2 }}
>
	<Stage
		ref={stageRef}
		width={800}
		height={600}
		onMouseDown={handleMouseDown}
		onMousemove={handleMouseMove}
		onMouseup={handleMouseUp}
		onClick={() => { setSelectedId(null) }}
	>
		<Layer>
			<BackgroundImge
				currentImage={"https://images.pexels.com/photos/6180667/pexels-photo-6180667.jpeg"}
				canvasWidth={800}
				canvasHeight={600}
			/>
		</Layer>
		<Layer>
			{draggedImages.length > 0 && draggedImages.map((img, index) => {
				return <DraggedImages
					key={index}
					currentImage={img}
					canvasHeight={600}
					canvasWidth={800}
					draggedImages={draggedImages}
					draggable={!isDrawingMode}
					isSelected={img._id === selectedId}
					onSelect={() => setSelectedId(img._id)}
					onChange={handleChange}
				/>
			})
			}
		</Layer>
		<Layer>
			{lines.length > 0 && lines.map((line, i) => (
				<Line
					key={i}
					points={line.points}
					stroke="red"
					strokeWidth={line.tool === 'eraser' ? 10 : 5}
					tension={0.5}
					lineCap="round"
					lineJoin="round"
					globalCompositeOperation={
						line.tool === 'eraser' ? 'destination-out' : 'source-over'
					}
				/>
			))}
		</Layer>
	</Stage>
</Box>

**Comment by thamaraiSD060** [comment]
function getDataURI() {
		const uri = stageRef.current.toDataURL({quality:2});
		console.log(uri)
	}

**Comment by thamaraiSD060** [comment]
@lavrton 

Did you got ?

**Comment by thamaraiSD060** [comment]
Actually when I copy and paste the DataURI its hided but after downloaded it works perfectly
