### ISSUE TITLE
Drag event not working after resizing event

### ISSUE THREAD

**Issue by JonathanGafar** [konvajs/konva#1653]
I first noticed this issue when looking at this demo here: https://konvajs.org/docs/sandbox/Multi-touch_Scale_Stage.html

I left a comment in the comment section of that page, but I'm not sure if it'll be seen because of how old the demo is. Copying and pasting that comment:

I noticed that on my phone, if I press (and hold) on one of the shapes and start dragging it around, then I place a second finger on the screen and start pinching to resize, if I lift the second finger back up but keep the original finger still pressed down, it no longer drags. I have to lift all fingers off the phone in order for it to drag.

Is there a way to fix this?

**Comment by lavrton** [comment]
That is not actually part of the Konva itself. I fixed that behavior as part of the demo.
