### ISSUE TITLE
Event can't response in right way when set with css zoom propery.

### ISSUE THREAD

**Issue by tangbc** [konvajs/konva#1655]
Hello there, I'm facing an issue with css `zoom` propery.

That's my reproducible example: https://jsfiddle.net/7qvjg6ko/11/

Simply put, I implemented a 'hover-change-background' function using konvajs.

When root container or document.body set `zoom` property greater than 1, I find that the event still response in origin position. That is to say it seems like event is still happening in `zoom: 1` position.

Is there any way to fix this? 
Thanks.

**Comment by tangbc** [comment]
#1520 is the same feedback.

**Comment by lavrton** [comment]
Konva doesn't support zooming with CSS. I don't see any simple ways to fix that from Konva side. As workaround zoom with Konva scaling.
