### ISSUE TITLE
Maybe globalCompositeOperation='destination-out' setting is not working as expected.

### ISSUE THREAD

**Issue by davesierra** [konvajs/konva#1656]
Hello, thanks first of all for this library. Apologies in advanced, I'm not the most familiar with canvas and drawing, and I might be misunderstanding a few things about canvas and konva. Regardless, I was giving it a try because I have a unique case where I need to erase some parts of an image. I've searched around and found a few interesting demos, and [this initial question on SO that led me to konva](https://stackoverflow.com/questions/28438034/erasing-parts-of-an-image-on-html5-canvas), but I think there might be an underlying problem with them.

Lets start with the official konva drawing where there is a pen and erase tool: https://konvajs.org/docs/react/Free_Drawing.html

Looks good so far, but I need to erase an image instead of a line. I come across this demo which looks promising also: https://jsfiddle.net/u0vjL4d4/

Great, but I think I noticed something. The "erase" is not really erasing anything. Check out this demo that I threw together using konva's demo of drawing, along with the [transformer](https://konvajs.org/docs/react/Transformer.html): 

Sandbox Demo:
https://codesandbox.io/s/blissful-wing-pxfkl9?file=/src/index.js

Video:
https://github.com/konvajs/konva/assets/867047/f0e46c02-e36d-4f3e-b3dc-514d83d97b0e

As you can see in the video, the eraser is not actually erasing the red pixels, it's just drawing a white color on top of the red, only making it look like it destroyed the red, because the background is white also. 

Re-reading the Free Drawing demo, I realize it states: "Such an implementation should work ok for many whiteboard apps." which is true, so it may be my fault for misinterpreting the "erase" or the option `compositeOperation='destination-out'` which seemed like it removed one paint data from the other.

Regardless, is it possible to erase an image, in such a way that if I have two images, and I erase part of the top one, it will show the bottom one through the erased region (in the way that Photoshop works)? Or is this just a limitation of HTML canvas?

Thanks.

**Comment by davesierra** [comment]
Thanks so much for the info, I will try it. Cheers!

**Comment by bossikill** [comment]
`import URLImage from '@/components/URLImage'
import Konva from 'konva'
import { useEffect, useRef, useState } from 'react'
import { Group, Layer, Line, Stage, Text } from 'react-konva'

export default function View() {
  const [tool, setTool] = useState('pen')
  const [lines, setLines] = useState([])
  const isDrawing = useRef(false)
  const groupRef2 = useRef<Konva.Group>(null)

  const handleMouseDown = e => {
    isDrawing.current = true
    const pos = e.target.getStage().getPointerPosition()
    setLines([...lines, { tool, points: [pos.x, pos.y] }])
  }

  const handleMouseMove = e => {
    // no drawing - skipping
    if (!isDrawing.current) {
      return
    }
    const stage = e.target.getStage()
    const point = stage.getPointerPosition()
    const lastLine = lines[lines.length - 1]
    // add point
    lastLine.points = lastLine.points.concat([point.x, point.y])

    // replace last
    lines.splice(lines.length - 1, 1, lastLine)
    setLines(lines.concat())
  }

  const handleMouseUp = () => {
    isDrawing.current = false
  }

  // const LionImage = () => {
  //   const [image] = useImage('https://konvajs.org/assets/lion.png')
  //   return <Image image={image} />
  // }

  useEffect(() => {
    groupRef2.current.cache()
  }, [lines])

  return (
    <div>
      <select
        value={tool}
        onChange={e => {
          setTool(e.target.value)
        }}
      >
        <option value='pen'>Pen</option>
        <option value='eraser'>Eraser</option>
      </select>
      <Stage
        width={window.innerWidth}
        height={window.innerHeight}
        onMouseDown={handleMouseDown}
        onMousemove={handleMouseMove}
        onMouseup={handleMouseUp}
      >
        {/* <Layer>
          <URLImage src='https://konvajs.org/assets/yoda.jpg' x={150} y={150} />
          <LionImage />
        </Layer> */}
        <Layer>
          <Text text='Just start drawing' x={5} y={30} />
          <URLImage src='https://konvajs.org/assets/yoda.jpg' x={150} y={150} />
          <Group ref={groupRef2}>
            <URLImage src='https://konvajs.org/assets/yoda.jpg' x={350} y={350} />
            {/* <LionImage /> */}
            {lines.map((line, i) => (
              <Line
                key={i}
                points={line.points}
                stroke='#df4b26'
                strokeWidth={5}
                tension={0.5}
                lineCap='round'
                lineJoin='round'
                globalCompositeOperation={line.tool === 'eraser' ? 'destination-out' : 'source-over'}
              />
            ))}
          </Group>
        </Layer>
      </Stage>
    </div>
  )
}
`
