### ISSUE TITLE
`Stage.getLayer()` does not return `Konva.Layer` as documented

### ISSUE THREAD

**Issue by wlcharlie** [konvajs/konva#1657]
As title say, the method `Stage.getLayer()` does not return `Konva.Layer` but `null`

If there are multiple layers, might be better to use `getLayers()` instead of `getLayer()`?

![image (1)](https://github.com/konvajs/konva/assets/77925413/1760b0b5-72e1-4940-b371-88f50981c35c)

versions: 
```
macOS 13.0
node 16.18.1
konva 9.2.2
react-konva 18.2.10
```

**Comment by lavrton** [comment]
I don't understand your question. Where is it better to use `getLayers()`?

> does not return Konva.Layer but null

That is just jsdoc is not ideal. `node.getLayer()` may return null. We may need to update the docs.

**Comment by wlcharlie** [comment]
Sorry, I think i posted two questions at a time 😅  
Let's focus on what will `Stage.getLayer()` return...

> That is just jsdoc is not ideal. node.getLayer() may return null. We may need to update the docs.

I was trying to use `getLayer` from stage but it seems always return null. Is there any circumstances that might return `Layer` or something not null?

**Comment by lavrton** [comment]
I don't think so. `stage.getLayer()` is an artifact of extending from `Konva.Node` class. We all love Object-Oriented programming.

It is very useful to have a method on a node/shape to get the layer (as a parent or an ancestor). So this method exists in Konva.Node. But for `Konva.Stage` this method is useless, as it doesn't have any parents. It is a top element. So the function is explicity return null.
If you want to have `getLayers()` you can just use `stage.children` or `stage.getChildren()`

**Comment by wlcharlie** [comment]
Ah!  I was misunderstanding the relationship between `Layer` and `Stage`. 
Thanks for explain. It makes sense now.
