### ISSUE TITLE
How to prevent the overlapping part from darkening when transparent lines overlap?

### ISSUE THREAD

**Issue by JohnHuang-CT** [konvajs/konva#1662]
Hello, can you give some advice? Below are the effects and demos. 

![image](https://github.com/konvajs/konva/assets/65998703/7c336346-00f7-448c-80d9-fd2aa9340013)
[demo](https://codesandbox.io/s/drawing-pencil-test-forked-vkdwsz)

**Comment by lavrton** [comment]
I don't know any simple ways.
First, you can just disable opacity.
Second, you can combine several overlapping lines into a single `Konva.Path` objects.
Third, you can render these lines without opacity into a group. Then cache the group, then apply opacity to the group.

**Comment by JohnHuang-CT** [comment]
Thanks !
