### ISSUE TITLE
typescript error for Konva.getAngle

### ISSUE THREAD

**Issue by bonnie57** [konvajs/konva#1663]
I find there is `ts` error for ` Konva.getAngle`. Because I use `(Konva as any).getAngle` and I can access this method. But I cannot directly access this method, it will throw `Property  getAngle  does not exist on type  typeof Konva`

**Comment by bonnie57** [comment]
Sure, This is [Code](https://codesandbox.io/p/sandbox/demo-konva-lt96f7?file=%2Fsrc%2Findex.ts%3A3%2C31).
The reason is that I want to implement to rotating shape around the center.
This is official [Demo](https://konvajs.org/docs/posts/Position_vs_Offset.html#Why-do-we-need-an-offset-property).

**Comment by lavrton** [comment]
I see now. Thanks for the demo. I will release it later.
