### ISSUE TITLE
Simulate adaptability text + container

### ISSUE THREAD

**Issue by TessDevAcc8** [konvajs/konva#1664]
Hi, Help me please. How can I make the text have a background (e.g., displayed on a shape), and when the number of letters increases and the text wraps to a new line, the shape also increases in size?
Or find out after how many characters the line will break with a known container length?

like this:
![image](https://github.com/konvajs/konva/assets/149373545/784df4a4-7057-4db5-89f9-31661218260a)

**Comment by lavrton** [comment]
1. You can use https://konvajs.org/docs/shapes/Label.html for that.

2. Or just manually update rectangle height based on text height `rect.height(text.height())`
