### ISSUE TITLE
The row with the right alignment is displayed incorrectly

### ISSUE THREAD

**Issue by koliane** [konvajs/konva#1669]
For configuration ```
{
    "x": 150,
    "y": 100,
    "text": "hello world",
    "fontSize": 16,
    "width": 100,
    "lineHeight": 2,
    "align": "right",
    "letterSpacing": 12,
    "fill": "#FF0000",
    "fontFamily": "Ubuntu",
    "fontStyle": "normal 400"
}
```
Since the string does not fit on one line, it is transferred to another. But in this case, the top line (after the word hello) should end with a space (this behavior is expected and has text in figma/pixso), but in fact there is no space.
Here's what it looks like in konva: 
![Снимок](https://github.com/konvajs/konva/assets/14872877/edb72399-43c5-4f9e-b103-c1ec5383f427)

Here's what it looks like in figma: 
![Снимок](https://github.com/konvajs/konva/assets/14872877/8bbef474-b0af-4d73-b742-e4e5377bb7dc)

**Comment by lavrton** [comment]
I consider HTML rendering as canonical. And looks like konva renders similar result.

https://jsbin.com/nadudufuca/edit?html,css,js,output
