### ISSUE TITLE
Rotation with offset results in strange behavior

### ISSUE THREAD

**Issue by SteveGZr** [konvajs/konva#167]
When I use rotation and offset I'm experiencing a very strange behavior, that looks like a bug to me. Maybe it is no bug, but I just don't understand how the values are calculated.
I have a Stage like the following with 4 Images on it.
The Images have a `width` of `672` and a `height` of `504`, and I want them to be placed symmetrical. The Images at the top, are rotated by 180 degrees and have their center as a rotation point.
When I now set `x` of the Image in the left bottom corner to `74` I expect that I need to set the `x` of the Image in the top left corner to `410` which is the half of the `width` plus the distance of `74` which I want of the left side of the Image.
But when I set it to that value, the Image at the top has a much larger distance to the left edge of the stage than the Image at the bottom.
If I set the `x` of the Image at the bottom to `74` and the `x` of the Image at the top to `150` it works, but this makes no sense to me.

![2016-09-01-151425_1270x766_scrot](https://cloud.githubusercontent.com/assets/12197139/18168954/779a84ae-7058-11e6-9e1c-4c01562b7e1c.png)

**Comment by lavrton** [comment]
I am closing this issue. It is better to use StackOverflow or gitter for questions.

Please reopen if this question is still very important.
