### ISSUE TITLE
Konva.Line strokeWidth:1 and draggable:true Mouse Event Issue

### ISSUE THREAD

**Issue by ViOLeT-GiT** [konvajs/konva#1670]
Used konvajs 9.2.3

Konva.Line strokeWidth: 1 and draggable: true are set,
mouse movement or mouse events will not work.

It has been checked that it works at a minimum strokeWidth of 2 or higher.

Can you solve this problem?

**Comment by lavrton** [comment]
Use `hitStrokeWidth` property to control hit size of a line. Demo: https://konvajs.org/docs/events/Custom_Hit_Region.html
