### ISSUE TITLE
Can Text achieve first line indentation?

### ISSUE THREAD

**Issue by SF-Simon** [konvajs/konva#1677]
We tried using space characters as placeholders, but due to different fonts, the effect was not very good. We also tried using html2canvas, but it can only capture the displayed elements.

I don't know if there is any way to achieve indentation of the first line of text? For example, CSS support?

**Comment by lavrton** [comment]
Can you give more context about your issue? What is your use case?

**Comment by lavrton** [comment]
Probably you can try to use other Unicode characters similar to regular space. Such as `Non-Breaking Space` or `Em Space`
