### ISSUE TITLE
Mouse click on shape is ignored when mousedown detected on stage

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [konvajs/konva#1678]
Hi,
I found this strange behaviour when registering a mousedown listener on stage and a click listener on a shape: the first is triggered but not the second, is this behaviour by design? Is there anything we can do to avoid this?

Here you can see an example:

https://codesandbox.io/p/sandbox/konva-click-bug-zfp9w6

**Comment by lavrton** [comment]
Click on the shape is not triggered because it is interrupted by the alert message. So is no "mouseup" on it to trigger click. If you do simple `console.log` instead of `alert` you will see both messages.
