### ISSUE TITLE
Blurry text and graphic when zooming

### ISSUE THREAD

**Issue by BearTi** [konvajs/konva#168]
Hey,

I am using Konva for a little project and have a problem:

I´m using this example https://coderwall.com/p/dy_dla/scale-your-kineticjs-game-dynamically to dynamically zoom into my konva graphic. Problem: When I make my browser window smaller (so according to the example above, konva is zooming in), the text and also the graphics (rects) is getting blurry.

Is there any solution to prevent this?

**Comment by lavrton** [comment]
As I see, when you make a browser window smaller, a stage should be zoomed out (all shapes should be smaller).

1. Do you use caching?
2. Can you provide jsfiddle (or similar) example?

**Comment by BearTi** [comment]
No, I think don´t use caching... I can make a jsfiddle example later...

Thanks

**Comment by BearTi** [comment]
Hmm, it´s not so easy to make a jsfiddle example, so i made 2 screenshots. I hope you can see the blur effect:

![1](https://cloud.githubusercontent.com/assets/3652708/18311161/1e425bb6-7503-11e6-866c-4f0d25bd83f2.png)

![2](https://cloud.githubusercontent.com/assets/3652708/18311163/20578a20-7503-11e6-8d3e-78668fe5db0b.png)

**Comment by lavrton** [comment]
I don't see blur effect... Probably your text is just too small.
