### ISSUE TITLE
how to make toDataURL render entire virtual canvas, regardless of which part of the stage is showing

### ISSUE THREAD

**Issue by zzoneblue** [konvajs/konva#1683]
I am having a pretty happy time with toDataURL, with one exception. Even with the config bounds provided, the rendered image seems to only be capable of capturing the part of the stage that is visible on the canvas. I am talking about when a stage is set to draggable, and thus the virtual canvas is a superset of the actual on screen canvas, the latter of which has finite dimensions, where as the former does not ( can even go negative coords). Is the only way around this to copy the contents to a second larger canvas, and render from that?

**Comment by zzoneblue** [comment]
Actually after playing some more with this its very unpredictable, sometimes it will show negative coord areas. It also seems to depend on where the stage is currently scrolled to, which im not understanding. I set the bounding box to that of my content. My stage is configured so:
				// Create a konva stage and layer
				var width = window.innerWidth;
				var height = window.innerHeight;
				stage = new Konva.Stage({
					container: 'container',
					width: width,
					height: height,
					draggable: true,
				});
				layer = new Konva.Layer();
				stage.add(layer);
Which is some 1000 x 500 px. When groups are dragged outside that area they seem to exist just fine, until i try to render a png from it.

**Comment by zzoneblue** [comment]
And for completeness:
var bounds = mindmap.getbounds(); 
				var dataURL = mindmap.stage.toDataURL({
					x: bounds.x,
					y: bounds.y,
					width: bounds.width,
					height: bounds.height
				});

**Comment by lavrton** [comment]
Please make a demo.

**Comment by zzoneblue** [comment]
Ok, i have reduced the code to the minimum viable reproduceable,  here:
https://thebighouseproject.nz/mindmapper/thumbproblem.html

Step 1: Load the page, then Click the save button, and note the image contains the expected bounds.
Step 2: Now drag the stage so that you can see the square labelled -500,-500. (or anywhere really). Click save, and notice the image does not contain the same image as found in step 1. 

Where the stage is dragged to influences the bounds of the image regardless of what config object you send.

Cheers for looking at this man.

**Comment by lavrton** [comment]
Position of stage affects `stage.toDataURL()`. So different output before/after drag is expected to me.

Passing `x` and `y` to `stage.toDataURL()` work like an "offset" from its defined position.

Resetting position to `{0, 0}` -> exporting -> restoring position back is very valid approach. You can use it if it makes things simpler.

**Comment by zzoneblue** [comment]
Do i get your right, that this would work?

```
	var originalPosition = {
		x: mindmap.stage.x(),
		y: mindmap.stage.y(),
	};
	var bounds = mindmap.getbounds(); 
	var dataURL = mindmap.stage.toDataURL({
		x: originalPosition.x,
		y: originalPosition.y,
	});
```

**Comment by lavrton** [comment]
I am not sure about negativing it, but it should work.

**Comment by zzoneblue** [comment]
Ok here is another work around:

```
				var dataURL = stage.toDataURL({
					x: stage.x() + min.x,
					y: stage.y() + min.y,
					width:  (max.x - min.x),
					height: (max.y - min.y),
				});
				downloadURI(dataURL, 'stage.png');

```

I hope you dont mind me saying, but this is not really intuitive. What does the stage position have to do with image export?
