### ISSUE TITLE
Transformer.flipEnabled(false) doesn't work

### ISSUE THREAD

**Issue by denis-mnml** [konvajs/konva#1684]
Hi there. Transformer.flipEnabled(false) doesn't work.
You can check it there [https://jsbin.com/rihurob/edit?html,js,output](https://jsbin.com/rihurob/edit?html,js,output)
If i do something wrong, tell me please

**Comment by denis-mnml** [comment]
I think I understand how it works. But I thought it worked differently.

**Comment by entermask** [comment]
i have same issue, any update?
