### ISSUE TITLE
Mirror a shape with respect to custom axis

### ISSUE THREAD

**Issue by vikkyjain2013** [konvajs/konva#1689]
I went through the konva documentation regarding mirror a shape. 
Currently i believe we can mirror a shape on x-axis or y-axis. In that case, it is mirrored with respect to 0,0 origin point.
Then i can use offset to mirror a shape from a custom origin point.

My requirement is bit different. Assume, there are n number of axis in 2d model. lets say one axis at every 5 degree angle from origin point. I want to mirror a shape from those axis. My mirror functionality should not be limited to x or y axis. if i can pass a angle, offset and shape, it should mirror the shape through that axis which will be drawn on that angle from origin. 

Please see below image created, where i want to rotate the rectangle shape through purple axis.

![axis](https://github.com/konvajs/konva/assets/131866319/0808c846-6080-4a60-9c8a-60c51034393c)

**Comment by lavrton** [comment]
Did you try anything? I don't think there is anything specific to the Konva. Just some math calculations.

**Comment by vikkyjain2013** [comment]
I was thinking if konva have inbuilt method for this just like scaleX or scaleY. If not, then i need to search for math calculations.

**Comment by bliepp** [comment]
A mirror operation is basically a simple trabsformation matrix operation, which can be decomposed into a set of scale, rotation and translation function calls. So in general, mirroring around an arbitrary axis can be achieved with one mirror operation around the y axis (i.e. scaling in x with -1 as the factor), a rotation of half the angle of the arbitrary axis and a translation to the mirrored position (basically moving the object twice its distance to the axis in the direction of the normal vector of the axis).

As you can see it's not that hard and Konva comes with all the tools you need. I don't think mirroring around an arbitrary axis is something a general purpose graphics library should be capable of, as the use cases are very niche.
