### ISSUE TITLE
Dragging Group on mobile view throws "missing preventDefault" error

### ISSUE THREAD

**Issue by georglind** [konvajs/konva#169]
When dragging a `Konva.Group` in mobile view of chrome's developer tools, it throws the error: 

`Konva.DD.node.preventDefault is not a function [konva.js: 9328]`

As far as I can see the problem is that `preventDefault` is not correctly defined for `Konva.Group`. I can eliminate the error by by adding a getterSetter to `Konva Group [konva.js: 10133]`:

`Konva.Factory.addGetterSetter(Konva.Group, 'preventDefault', true);`

But I don't know if that produces the desired behaviour for the `preventDefault` property.

No errors are thrown in desktop view.

**Comment by DMIAOCHEN** [comment]
+1

**Comment by lavrton** [comment]
I published new version with the fix.
