### ISSUE TITLE
Font weight 500 not working

### ISSUE THREAD

**Issue by aman-webdev** [konvajs/konva#1696]
I am trying to load and use Montserrat font with normal, bold , medium , bolditalic and italic versions, i load all the fonts in my browser.

This is how i set the font style

 const fontStyle =
    fontWeight === 700 && isItalic
      ? "italic bold"
      : fontWeight === 400 && isItalic
        ? "italic"
        : fontWeight === 700 && !isItalic
          ? "bold"
          : fontWeight===500 && !isItalic ? "500" : "normal";

current output
<img width="170" alt="image" src="https://github.com/konvajs/konva/assets/78081991/b11bc7f0-2c25-46ac-9594-49f6f7ee1912">

expected output
<img width="245" alt="image" src="https://github.com/konvajs/konva/assets/78081991/42e63936-4714-49b7-9cf9-16e752ccba95">

**Comment by lavrton** [comment]
Please make a demo.
Also, make sure all variations of that font are loaded.

**Comment by aman-webdev** [comment]
https://jsfiddle.net/b6qkuhs8/1/
Here is the demo , pls check, thanks

**Comment by lavrton** [comment]
I see the issue in the demo. But I don't know what I can do here from Konva side. As I can see, konva is setting font style on 2d canvas API correctly.
