### ISSUE TITLE
Pixelate filter adds bottom and right borders since v8.3.4

### ISSUE THREAD

**Issue by Piliuta** [konvajs/konva#1697]
## Problem

The Pixelate filter started adding extra borders in most cases making it look not great.
This is easy to reproduce trying to pixelate images with a lot of white area, or simply white image.

Example: https://codepen.io/piliuta/pen/NWJxxXM

Konva v8.3.3
<img width="222" alt="image" src="https://github.com/konvajs/konva/assets/1575198/aeb0ed94-6f17-4a72-bc2e-2d8705ef233c">

Konva v8.3.4
<img width="233" alt="image" src="https://github.com/konvajs/konva/assets/1575198/9797a0a1-f8ce-454f-9af9-3495f30d8d84">

I suspect this might be caused by the extra pixel added here, although not sure https://github.com/konvajs/konva/compare/8.3.3...8.3.4#diff-2b0510beac1d8e3349bfde981667cea06e65f59e40cfa7be46db06288856a5fcR2607-R2610

**Comment by lavrton** [comment]
That for the details report. Should be fixed now. I will make a release later.
