### ISSUE TITLE
"Konva.DD.node.preventDefault is not a function" in _touchmove

### ISSUE THREAD

**Issue by psivanov** [konvajs/konva#170]
I am getting "Uncaught TypeError: Konva.DD.node.preventDefault is not a function" from _touchmove in chrome:

![image](https://cloud.githubusercontent.com/assets/526422/18493919/e9b1b1b6-79c7-11e6-88d1-40a892b1521f.png)

**Comment by lavrton** [comment]
@psivanov This issue should be resolved in last version. Can you try it?

**Comment by psivanov** [comment]
Yeah, I don't see this error anymore. Thanks!
