### ISSUE TITLE
v-circle dragmove with v-line error

### ISSUE THREAD

**Issue by Mt-Youya** [konvajs/konva#1701]
Sry, my English is bad!
I have a issue with drag cirle with vertical line & horizontal line. 
I use dragBoundFunc in v-line, the v-line follow cirle dragmoving, but i get a wrong position.

At first time , i drag cirle and get right position in line , but after i drag line , i got a wrong positon in line.

[code here](https://codesandbox.io/p/devbox/vue-konva-circledragwithline-demo-yz3522?file=%2Fsrc%2FApp.vue%3A45%2C42)

@lavrton

**Comment by lavrton** [comment]
What are you trying to do in the application? What is the UX?

**Comment by Mt-Youya** [comment]
step1: dragmove vertical line anywhere 
step2: dragmove horizontal line anywhere
step3: dragmove circle anywhere 
expect: Two straight lines always intersect at the circle
result: lines intersect not at the circle
