### ISSUE TITLE
getClientRect() for custom shapes returns wrong IRect

### ISSUE THREAD

**Issue by AlexandrDiakov** [konvajs/konva#1706]
Hi.
I've encountered weird behaviour, but I'm not sure is it a bug or intended.

When `getClientRect()` is called on a custom shape made with the `sceneFunc` the size of the actual shape is not considered.
Example:
https://codesandbox.io/p/sandbox/hardcore-rumple-j9njwp

Is there any other way I can get the position and size of the custom shape itself?

**Comment by lavrton** [comment]
For now, Konva can't automatically detect the bounding box of a shape from `sceneFunc`. I recommend defining `width` and `height` attributes and rendering only inside the bounding box of size values.

```js
<Shape
  y={50}
  width={260}
  height={120}
  sceneFunc={function (context, shape) {
    const width = shape.width();
    const height = shape.height();
    context.beginPath();
    context.moveTo(0, 0);
    context.lineTo(width - 40, height - 90);
    context.quadraticCurveTo(width - 110, height - 70, width, height);
    context.closePath();

    // (!) Konva specific method, it is very important
    context.fillStrokeShape(shape);
  }}
  fill="#00D2FF"
  stroke="black"
  strokeWidth={4}
/>
```
