### ISSUE TITLE
Event was not triggered

### ISSUE THREAD

**Issue by zhanghibi** [konvajs/konva#1708]
https://konvajs.org/docs/sandbox/Web_Worker.html

For the above example, add the following styles:
```
#canvas {
        position: absolute;
        left: 20px;
        top: 20px;
}
```

A native event is triggered:
```
EVENTS.forEach((eventName) => {
        htmlCanvas.addEventListener(eventName, (e) => {
            console.log(''triggered")
            w.postMessage({
              eventName,
              event: {
                clientX: e.clientX,
                clientY: e.clientY,
                type: e.type,
              },
            });
          });
  });
```

 Konva Event was not triggered：
```
  button.on('mousedown', function () {
  console.log(''not  triggered")
    isAdding = true;
  });
```

**Comment by lavrton** [comment]
Can you make a final demo to reproduce?

**Comment by zhanghibi** [comment]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Konva Offscreen Canvas Demo</title>
    <style>
      body {
        position: relative;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #f0f0f0;
        width: 1920px;
        height: 1070px;
      }
      #canvas {
        position: fixed;
        left: 20px;
        top: 20px;
      }
    </style>
  </head>

  <body>
      <canvas id="canvas"></canvas>

    <script>
      var htmlCanvas = document.getElementById('canvas');
      htmlCanvas.width = window.innerWidth;
      htmlCanvas.height = window.innerHeight;

      var hasOffscreenSupport = !!htmlCanvas.transferControlToOffscreen;
      if (hasOffscreenSupport) {
        var offscreen = htmlCanvas.transferControlToOffscreen();

        var w = new Worker('./web_worker2.js');
        // pass canvas into webworker, so we can do all rendering inside it
        w.postMessage({ canvas: offscreen }, [offscreen]);

        // "proxy" all DOM events from canvas into Konva engine
        var EVENTS = [
          'mouseenter',
          'mousedown',
          'mousemove',
          'mouseup',
          'mouseout',
          'wheel',
          'contextmenu',
          'pointerdown',
          'pointermove',
          'pointerup',
          'pointercancel',
          'lostpointercapture',
        ];
        EVENTS.forEach((eventName) => {
          htmlCanvas.addEventListener(eventName, (e) => {
            w.postMessage({
              eventName,
              event: {
                clientX: e.clientX,
                clientY: e.clientY,
                type: e.type,
              },
            });
          });
        });
      } else {
        htmlCanvas
          .getContext('2d')
          .fillText(
            '🛑 Sorry, your browser does not support Offscreen rendering...',
            20,
            20
          );
      }
    </script>
  </body>
</html>

**Comment by zhanghibi** [comment]
Sorry, it's me code issue
