### ISSUE TITLE
Events after drag stage

### ISSUE THREAD

**Issue by slidm** [konvajs/konva#171]
Layers and shapes not receive mouse events after stage move by dragging.
stage.batchDraw on dragend solve issue.

**Comment by lavrton** [comment]
@slidm can you be more specific? Demo?

This works fine: http://jsbin.com/geconigeyu/1/edit?js,console,output

**Comment by slidm** [comment]
https://jsfiddle.net/bewvLbzj/1/

**Comment by lavrton** [comment]
Thanks for the report.

The issue is fixed and I published the new version `1.2.2`.  Fixed demo: https://jsfiddle.net/bewvLbzj/3/
