### ISSUE TITLE
The konva.Arrow functionality does not work properly in Chrome version 122.

### ISSUE THREAD

**Issue by bear109** [konvajs/konva#1714]
Hello:) I am a user currently using your library. 
There is an issue when trying to draw an arrow using the Konva.Arrow object in Chrome version 122.
When I tested the code provided in the documentation in both Chrome version 121 and 122, I noticed that the results were different. 
I would appreciate a prompt response to this issue. Thank you

**Comment by Davidiusdadi** [comment]
can u show the difference with an image ? what is the issue in detail?

**Comment by bear109** [comment]
in chrome 121
<img width="1251" alt="스크린샷 2024-02-02 오후 10 49 29" src="https://github.com/konvajs/konva/assets/76770612/7f15fac1-459e-4f99-a409-1c6669a30d8e">

in chrome 122
<img width="1258" alt="스크린샷 2024-02-02 오후 10 49 46" src="https://github.com/konvajs/konva/assets/76770612/9683a7c9-8647-488a-915d-4467884134ce">

Thank you for using the library and for your interest as a user in addressing this issue:)
The issue is that when using the Konva.Arrow object, the arrowhead part does not appear correctly. 
Additionally, there is a problem where during the process of drawing arrows in the service I am currently configuring (while the mouse is downed), the arrowhead part does not display correctly and appears as a straight line. Is there a solution to the above problem?

**Comment by lavrton** [comment]
Can you still reproduce that? I am on Chrome 122 and I can't reproduce the issue.

**Comment by bear109** [comment]
> Can you still reproduce that? I am on Chrome 122 and I can't reproduce the issue.

At the moment, it seems that the issue you presented has been resolved. I think there was a issue with the Chrome beta version and it seems to have been resolved with the minor version of the Chrome beta being upgraded. Thank you for your interest in this issue.
