### ISSUE TITLE
Compatibility issue with chrome 51

### ISSUE THREAD

**Issue by uditvishnoi2** [konvajs/konva#1716]
I have a peculiar request; we are attempting to run Konva.js on an Android device with Chrome version 51.0.2704.91, which is quite outdated. We are encountering the following error with spread operator : 'Uncaught SyntaxError: Unexpected token ...' specifically related to the code snippet
```
    setAbsolutePosition(pos) {
        const { x, y, ...origTrans } = this._clearTransform();
```
        
Is it possible to address this issue, or any suggestions would be greatly appreciated

**Comment by Davidiusdadi** [comment]
- chrome 51 apparently supports spread operator https://caniuse.com/?search=spread%20operator
- this is therefore **very** unlikely to be a konvajs issue 
- 
Supporting fancy new syntax in old browsers is often tackled through the build process and not through the libraries themselves 
 - e.g. through stuff like babeljs.  vite's  `build.target` serves the same purpose

**Comment by uditvishnoi2** [comment]
Hi @Davidiusdadi you are right spread operator are supported in chrome 51, but Object initializer: Spread properties are available with chrome 60 only.
 
 About the build process , i don't think it is advisable to process already compiled JavaScript . But i will give it a try.
 Thanks

**Comment by lavrton** [comment]
I don't have plans to support old browsers from Konva side. But as mentioned @Davidiusdadi, you can transpile dependencies with any available tool.
