### ISSUE TITLE
Overlapping shape fill got "removed". Evenodd issue?

### ISSUE THREAD

**Issue by CPatchane** [konvajs/konva#1717]
Hello here 👋 

It's more a question than a bug but I would like to know if it was possible to avoid that the fill of the shape is being removed when it's overlapping itself.

Here is the [sandbox](https://stackblitz.com/edit/af-react-sandbox-7klok7?file=index.js) that I used for this issue.

My need is to draw a contour of this line:
<img width="254" alt="Screenshot 2024-02-02 at 16 48 09" src="https://github.com/konvajs/konva/assets/10224453/ff1931c0-c1f1-4474-9e8e-56937e172cec">

But in the sandbox you can see that I got this:
<img width="249" alt="Screenshot 2024-02-02 at 16 48 44" src="https://github.com/konvajs/konva/assets/10224453/068d2212-5669-442f-a76e-e9de4d6e21e0">

The contour points are not perfect compared to the original shape but it's correct except that the fill seems to be removed at some places where the shape is overlapping on itself. I expect something similar when you draw a classical line, when I have "painted" a place, it shouldn't be removed when I pass again on it.

Is it possible to fix that using konva or the Canvas API?

Note: I need to draw a contour to then apply that to a clipFunc, so I can't rely on the stroke + strokeWidth anymore.

Thanks a lot by advance!

**Comment by lavrton** [comment]
Are you sure your `computeContour` is correct?

**Comment by CPatchane** [comment]
I think, it's not perfect but I was expecting to not see those empty filling, here is what I am when keeping only the borders:
<img width="263" alt="Screenshot 2024-02-06 at 14 22 53" src="https://github.com/konvajs/konva/assets/10224453/58b9b1e9-709a-463d-b4da-47120e3124e0">

But maybe I'm wrongly thinking this as a brush (when you pass at a point, it should always be painted like in Photoshop) instead of a shape filling after being computed (filling the shape above seems to make sense here) 🤔

**Comment by CPatchane** [comment]
Oh, after thinking again about this contour function, I get a better result by making sure to close the shape when the vector directions change. 
<img width="233" alt="Screenshot 2024-02-06 at 14 37 38" src="https://github.com/konvajs/konva/assets/10224453/d9050034-52d5-41d8-a6f4-2daea8c1c214">
<img width="266" alt="Screenshot 2024-02-06 at 14 37 45" src="https://github.com/konvajs/konva/assets/10224453/d5d161de-2f95-4cca-80e6-449b48379f2e">

[The result](https://stackblitz.com/edit/af-react-sandbox-7klok7?file=index.js) is much better and it solves this problem at least. Thank you very much for this little help :)
