### ISSUE TITLE
pixelized free draw

### ISSUE THREAD

**Issue by fabienwnklr** [konvajs/konva#1719]
Hi, first i'm not sure it's an issue, but didn't find any solutions/response for this..

I make a free hand tool, my goal is to draw "smooth" line like this example :
![image](https://github.com/konvajs/konva/assets/49644785/d898a479-692d-4179-90c3-930e306c9868)

But my result is like this : 
![image](https://github.com/konvajs/konva/assets/49644785/37a6cd01-e421-4937-9be8-da05bb7abad2)
https://mourner.github.io/simplify-js/
I'll already try to upgrade line points with `simplify` example here https://mourner.github.io/simplify-js/ and here https://codepen.io/kristofer-Borg/pen/bGZvgYx?editors=0011

detail: with simplify, if i up `tolerence` it's perf lacking

Thanks for response and thanks for this pretty library :)

**Comment by lavrton** [comment]
Try this one - https://github.com/steveruizok/perfect-freehand

**Comment by fabienwnklr** [comment]
> Try this one - https://github.com/steveruizok/perfect-freehand

Look good, im going testing it. So, there’s nothing in Konva to do that?

**Comment by lavrton** [comment]
`Konva.Line` has `tension` property to make line smooth.
`perfect-freehand` can be used together with Konva. `perfect-freehand` for math, Konva for drawing.

**Comment by fabienwnklr** [comment]
> `Konva.Line` has `tension` property to make line smooth. `perfect-freehand` can be used together with Konva. `perfect-freehand` for math, Konva for drawing.

ok, thanks for reply !
