### ISSUE TITLE
Stage disappears when detaching tab in Chrome

### ISSUE THREAD

**Issue by bloodbank** [konvajs/konva#172]
When you detach a tab with a stage drawn on it out of the parent chrome window, the stage appears blank/images are gone. But when you attach it back to the same parent chrome window, the images/stages are showing again.

Tested on Chrome Version 52.0.2743.116 m.

**Comment by lavrton** [comment]
Can not reproduce.
Please reopen if it is still actual and you can provide steps to reproduce.
