### ISSUE TITLE
loading json problems

### ISSUE THREAD

**Issue by fredalva** [konvajs/konva#1722]
Hi, i am new using konva.js , i use prompt to add text which will be displayed in center rectangle.This works well, when i click on rectangle i get alert with shape id. When i click on save , i get text.json file on my download folder. i checked file and all seems good. Problem i coming after upload file, i can see rectangle and move it but no click detected on rectangle, stage also. if i try to add new rectangle  on stage nothing happens after prompt submit. 
[test.json](https://github.com/konvajs/konva/files/14312608/test.json)
This is sample code page to test:
`<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <title>Plan Interactif avec Konva.js</title>
    <script src="https://unpkg.com/konva@9/konva.min.js"></script>
    <style>
      body {
        margin: 0;
        padding: 20px;
      }
      #container {
        width: 800px;
        height: 600px;
        background-color: #d9d6d6;
        overflow: hidden; /* Empêche le conteneur de scroller */
      }

      #addRectangleBtn {
        width: 20px; /* Largeur fixe */
        height: 30px; /* Hauteur fixe */
      }
    </style>
  </head>
  <body>
    <div id="container"></div>
    <button id="toggleEdit">Mode Édition</button>
    <button id="addRectangle">Rectangle</button>
  
    <button id="save">Sauvegarder</button>
    <input type="file" id="load" accept=".json" />
    <script>
            // Création stage
            var stage = new Konva.Stage({
              container: "container",
              width: 800,
              height: 600,
              draggable: true,
            });

            // Création layer
            var layer = new Konva.Layer();
            stage.add(layer);

            // Création arrière plan
            var background = new Konva.Rect({
              x: 0,
              y: 0,
              width: stage.width(),
              height: stage.height(),
              fill: "lightgrey",
            });

            // Ajout arrière plan au layer
            layer.add(background);
            layer.draw();

            var editMode = false;
            var idCounter = 1;
            var isDragging = false;
            var startPoint = { x: 0, y: 0 };
            var currentRect = null;

            // Mode édition
            function updateEditMode() {
              console.log("Mode d'édition : " + editMode);
              document.getElementById("toggleEdit").textContent = editMode
                ? "ON"
                : "OFF";
              // Actualiser le draggable pour tous les éléments
              layer.getChildren().forEach(function (group) {
                if (group !== background) {
                  // Ignorer le fond pour le panning
                  group.draggable(editMode);
                }
              });
              // Activer ou désactiver le panning du stage
              if (!editMode) {
                stage.draggable(true);
              } else {
                stage.draggable(false);
                stage.position({ x: 0, y: 0 }); // Réinitialiser la position du stage en mode édition
                stage.draw();
              }
            }

            // Ecouteur mode edition true ou false
            document
              .getElementById("toggleEdit")
              .addEventListener("click", function () {
                editMode = !editMode;
                updateEditMode();
              });

            // création d'un rectangle avec texte au centre
            function addRectangle() {
              if (!editMode) {
                console.log(
                  "La création de rectangles est désactivée hors du mode d'édition."
                );
                return;
              }
              var reference = prompt("Entrez la référence du rectangle :");
              if (!reference) return;

              var rect = new Konva.Rect({
                x: 100,
                y: 100,
                width: 20,
                height: 40,
                fill: "white",
                stroke: "black",
                strokeWidth: 1,
              });

              var text = new Konva.Text({
                text: reference,
                fontSize: 12,
                fontFamily: "Arial",
                fill: "black",
              });
              text.position({
                x: rect.x() + rect.width() / 2 - text.width() / 2,
                y: rect.y() + rect.height() / 2 - text.height() / 2,
              });

              var group = new Konva.Group({
                id: "rect" + idCounter++,
                draggable: editMode,
              });
              group.add(rect);
              group.add(text);

              group.on("click", function (e) {
                if (!editMode) {
                  alert("ID du rectangle : " + this.id());
                  e.cancelBubble = true;
                }
              });

              layer.add(group);
              layer.draw();
            }

          

            document
              .getElementById("addRectangle")
              .addEventListener("click", addRectangle);

            updateEditMode(); // Important pour appliquer les changements

           

            // Save stage
            document.getElementById("save").addEventListener("click", function () {
              var data = stage.toJSON();
              var json = data;

              // Créer un objet Blob à partir des données JSON
              var blob = new Blob([json], { type: "application/json" });

              // Créer un objet URL à partir du Blob
              var url = URL.createObjectURL(blob);

              // Créer un élément <a> pour le téléchargement
              var a = document.createElement("a");
              a.href = url;
              a.download = "test.json"; // Nom du fichier à télécharger

              // Ajouter l'élément <a> au DOM
              document.body.appendChild(a);

              // Simuler un clic sur l'élément <a> pour déclencher le téléchargement
              a.click();

              // Nettoyer après le téléchargement
              window.URL.revokeObjectURL(url);

              // Supprimer l'élément <a> du DOM après utilisation, s'il existe
              if (a.parentNode) {
                a.parentNode.removeChild(a);
              }
            });

            document.getElementById("load").addEventListener("change", function () {
    var file = this.files[0]; // Récupérer le premier fichier sélectionné
    var reader = new FileReader();

    reader.onload = function (event) {
        try {
            var jsonString = event.target.result;
            var data = JSON.parse(jsonString);

            // Effacer les éléments actuels sur la scène
            stage.destroyChildren();

            // Créer les éléments Konva.js à partir des données JSON
            Konva.Node.create(data, "container") ;

        } catch (error) {
            console.error(
                "Une erreur est survenue lors du chargement des données JSON:",
                error
            );
        }
    };

    // Lire le contenu du fichier en tant que texte
    reader.readAsText(file);
});

    document.getElementById("load").addEventListener("change", function () {
    var file = this.files[0]; // Récupérer le premier fichier sélectionné
    var reader = new FileReader();

    reader.onload = function (event) {
        try {
            var jsonString = event.target.result;
            var data = JSON.parse(jsonString);

            // Effacer les éléments actuels sur la scène
            stage.destroyChildren();

            // Créer les éléments Konva.js à partir des données JSON
            Konva.Node.create(data, "container") ;

        } catch (error) {
            console.error(
                "Une erreur est survenue lors du chargement des données JSON:",
                error
            );
        }
    };

    // Lire le contenu du fichier en tant que texte
    reader.readAsText(file);
});

    </script>
  </body>
</html>
`

**Comment by lavrton** [comment]
JSON serialization has no information about any event handlers. So after you load from JSON, you have to reattach all listeners for events again.
