### ISSUE TITLE
Container ignores canvas width

### ISSUE THREAD

**Issue by Mikilll94** [konvajs/konva#1729]
https://jsbin.com/kiveruqoxa/2/edit?html,js,output

![image](https://github.com/konvajs/konva/assets/17653648/121eb45a-b31f-4728-9b09-6a00fc49e3be)

As you can see I have set the canvas width and height to `100`. But the `container` spans the entire width. Why? It should have the same width as canvas.

**Comment by lavrton** [comment]
`width` defines canvas size. 
If you want to have a container with the same size, just put `display: inline-block` on it.
