### ISSUE TITLE
Label: Tag width/height does not change dynamically

### ISSUE THREAD

**Issue by evktalo** [konvajs/konva#173]
Tag part of the Label no longer adjusts its width and height when Text's and Label's width and height change. This happens between 0.10->0.11.

Here's a speech bubble from our game in 0.10:

![kiigame_speechbubble_010](https://cloud.githubusercontent.com/assets/1465067/18628980/789972a4-7e6b-11e6-8574-7b87256d3b0d.png)

Here's the same in 0.11:

![kiigame_speechbubble_011](https://cloud.githubusercontent.com/assets/1465067/18628981/789a122c-7e6b-11e6-98db-160602be16f7.png)

What it does it loads the text up in the Label's text (which at this point has "auto" width), checks if its width goes above 524 and then sets it to 524 and reloads the text. I put some console.logs in and in 0.1.0, the widths/heights of Label and Tag are also changed, but in 0.1.1 the Tag's width/height stays at the original values. Might be related to 3616d38

**Comment by lavrton** [comment]
Can you please create jsfiddle demo?

I created this example: http://jsbin.com/rifuzolosa/1/edit?html,js,console,output. Works ok.

**Comment by evktalo** [comment]
I'll do that, it'll probably take me some time to get to that though. Thanks for the response!

**Comment by evktalo** [comment]
I added some printouts of the tag's width in your example, and it *does* work there (http://jsbin.com/nogoxurovu/edit?html,js,console,output). I'll have to dig in to see what's happening in our code.

**Comment by evktalo** [comment]
Here's an example that breaks it:

http://jsbin.com/wonijewuye/edit?html,js,console,output

The thing that seems to break it is when the text.width is set manually. Tag width doesn't change automatically to match, it used to in 0.10.

**Comment by lavrton** [comment]
Fixed. Thanks for report.
