### ISSUE TITLE
Transformer handle drag issue: losing control after dragging and clicking on stage

### ISSUE THREAD

**Issue by karl20888** [konvajs/konva#1730]
When dragging a Transformer's handle, it is not possible to continue dragging without first clicking on the stage. This behavior causes loss of control over the Transformer. Upon investigation, it appears that the click event on the stage is being triggered instead of the desired handle drag event.

**Comment by lavrton** [comment]
@bliepp oh, that is a bad bug. Thanks for the report.

@karl20888 can you make a demo of your issue?

**Comment by lavrton** [comment]
@bliepp fixed in the lst version 9.3.6. Please confirm.

**Comment by karl20888** [comment]
@lavrton same as bliepp's
Thank you so much for fixing this bug! I have confirmed that version 9.3.6 addresses the issue. Your contribution is greatly appreciated!

**Comment by bliepp** [comment]
@lavrton Thanks, I appreciate your fast paced bug fixes. I can confirm the bug's now gone with 9.3.6, too.

**Comment by giovanni-bertoncelli** [comment]
Hello guys, I've lately upgraded to latest Konva version (9.3.6) and I get this error:

```
ERROR TypeError: Cannot read properties of undefined (reading 'isDragging')
    at Object.isDragging (Global.js:46:36)
    at Stage._pointerleave (Stage.js:349:46)
    at content.addEventListener.passive (Stage.js:308:33)
    at _ZoneDelegate.invokeTask (zone.umd.js:445:35)
    at core.mjs:10757:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:10757:36)
    at _ZoneDelegate.invokeTask (zone.umd.js:444:64)
    at Object.onInvokeTask (core.mjs:11070:33)
    at _ZoneDelegate.invokeTask (zone.umd.js:444:64)
    at Zone.runTask (zone.umd.js:210:51)
```

Maybe it's related to this issue?

**Comment by bliepp** [comment]
@giovanni-bertoncelli It might be related, but my demo does not throw that error. Does this error show up with any of the other latest realeases (ie. 9.3.5 or 9.3.4)?

**Comment by bliepp** [comment]
No, I have not. My test project can be found in the discussion thread mentioned above. It's basically a minimal HTML file with a single layer with a single rectangle and a transformer attached to it. That's it.

**Comment by giovanni-bertoncelli** [comment]
Ok, if you can put your project on something like StackBlitz or CodeSandBox I can try to reproduce my issue

**Comment by bliepp** [comment]
> Ok, if you can put your project on something like StackBlitz or CodeSandBox I can try to reproduce my issue

Just have a look at #1727. You can find my code there.

**Comment by lavrton** [comment]
@giovanni-bertoncelli about this issue "Cannot read properties of undefined (reading 'isDragging')". Do you use some kind of minimal bundle of konva library? How do you import it?

**Comment by giovanni-bertoncelli** [comment]
HI @lavrton , I'm the maintainer of [ngx-konva](https://github.com/ctinnovation/ngx-konva). As you can see here: https://github.com/ctinnovation/ngx-konva/blob/main/projects/ngx-konva/package.json and here https://github.com/ctinnovation/ngx-konva/blob/main/projects/ngx-konva/src/lib/components/ko-shape.component.ts I'm using Konva with NPM as ESModule.

**Comment by giovanni-bertoncelli** [comment]
Oh ok, I didn't know that... I'll give it a try, thank you!
