### ISSUE TITLE
Rotating the object image using the rotate function

### ISSUE THREAD

**Issue by webmaxpro** [konvajs/konva#1731]
When I rotate an image object through the rotate function, its transformer does not rotate. If I change the object to a shape or an text, the transformer is also rotated. Image does not. If I change konvajs to version 7, the image is rotated correctly. In version 8 and 9 it does not.
![image-rotate](https://github.com/konvajs/konva/assets/8004801/8bf9ee6c-f5fb-46e9-a186-8e5b5f24c03c)

**Comment by lavrton** [comment]
Please make a little demo of the issue.

**Comment by webmaxpro** [comment]
I'm sorry. I realized the problem. 
I used useSingleNodeRotation: false for some reason. ¯\_(ツ)_/¯
