### ISSUE TITLE
Documentation for old releases and migration guide

### ISSUE THREAD

**Issue by kscc25** [konvajs/konva#1732]
Hello,

Thanks for making this awesome library. I'm using Konva for a project, the version I'm using is quite old (7.2.5) so I'm wondering where I can find the documentation for the old releases and migration guide in case I want to migrate to the latest major version. 

I found the [changelog](https://github.com/konvajs/konva/blob/master/CHANGELOG.md#800) indicating some breaking changes in version 8 but not sure if there are anything else I need to pay attention to. It would be nice if there is a migration guide to upgrade from version 7 to 8 and 8 to 9, etc.

Thank you and have a great day!

**Comment by lavrton** [comment]
All migrations tips are in changelog itself. Just looks for a major releases. There are not many of them.
If version 8 works for you, then most likely you will be able to upgrade to 9 without any modifications.
