### ISSUE TITLE
Event when you mousedown and move outside canvas.

### ISSUE THREAD

**Issue by bogdan-nourescu** [konvajs/konva#1744]
Starting from this code:
https://konvajs.org/downloads/code/select_and_transform/Basic_demo.html

I just added a console.log("eventName") on each of the event listeners: mouseup, click, mousedown.
If you start a selection and finish it, with will only print "mousedown mouseup"
If you start a selection, and don't release the mouse until you exit the canvas, the events start behaving differently. If you do the same thing as before, it will print "mousedown mouseup click"
![Animation](https://github.com/konvajs/konva/assets/4696503/c0ed852a-fd0e-4924-bb40-a562f73a4c2e)

**Comment by lavrton** [comment]
I changed a demo bit. The selection rectangle hit area is affecting events flow. Disabling events for it with `listening: false` works better.
