### ISSUE TITLE
Can we draw an un-closed ellipse like below?

### ISSUE THREAD

**Issue by nyi-ailytics** [konvajs/konva#1745]
Is it possible to draw something like this? The ellipse that doesn't connect?

![image](https://github.com/konvajs/konva/assets/150506615/5a20f093-a4a8-42fa-8a4e-acd2aea523fd)

**Comment by lavrton** [comment]
I think the simplest is to use `Konva.Path`

```js
var ellipseCutPath = new Konva.Path({
  x: stage.width() / 2,
  y: stage.height() / 2,
  offsetX: 100,
  offsetY: 50,
  data: 'M 50,50 a 100,50 0 1,0 100,0', // This draws an arc of an ellipse
  stroke: 'red',
  strokeWidth: 5,
  draggable: true
});
```

https://jsbin.com/cuxedofasi/1/edit?html,js,output
