### ISSUE TITLE
Text wrong line break if have Chinese and english word

### ISSUE THREAD

**Issue by david43** [konvajs/konva#1746]
demo:
https://codepen.io/david43/pen/rNbZwjb
if text mixed Chinese and Eng,the line break will wrong.
![未命名](https://github.com/konvajs/konva/assets/3192233/999b0705-aa09-42fd-865a-4112eb6c20cc)
set text wrap:"char" can fix this issue,
but eng word also broken.

**Comment by lavrton** [comment]
I think I will mark it as "won't fix" for now.  Konva breaks by space character ` `. I am not sure what will be the fast implementation from Konva side to automatically handle different languages.

**Comment by luin** [comment]
A quick solution would be checking if the language of a char uses spaces as word boundaries. (e.g. `/[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Hangul}]/gu`) and split by chars for those languages.

**Comment by lavrton** [comment]
Interested in making a pull request with a test?
