### ISSUE TITLE
Broken shadow after crop in safari

### ISSUE THREAD

**Issue by danarosca** [konvajs/konva#1747]
<img width="473" alt="Screenshot 2024-04-16 at 13 09 01" src="https://github.com/konvajs/konva/assets/22631028/fba5c3e7-fefa-47f6-a25b-b4f18830b89d">
<img width="321" alt="Screenshot 2024-04-16 at 13 08 30" src="https://github.com/konvajs/konva/assets/22631028/56bec7b6-5282-4555-9780-0f4261cc80c1">
If there are some crop properties, shadow effect is unable to go outside of image size. I am using only konva library. Any ideea what can cause this issue? it work on chrome and FireFox, but not in safari :( 
I've attached an example from Chrome ( expected result) and one from Safari.

**Comment by danarosca** [comment]
<img width="387" alt="Screenshot 2024-04-16 at 19 35 31" src="https://github.com/konvajs/konva/assets/22631028/821c1b41-f7c3-4ad7-a065-bb3e2799c3c9">
<img width="360" alt="Screenshot 2024-04-16 at 19 35 46" src="https://github.com/konvajs/konva/assets/22631028/85a0d69e-b090-4154-892a-81ac0045f9b7">
Also, here are image props in for both browsers

**Comment by lavrton** [comment]
Can you make online demo?

**Comment by danarosca** [comment]
unfortunately it's very hard for me since this is only a small part. But the idea is that after having the crop props, I make sure they are relative to original image size and than I set them as props for Image node ( basically this is the only change I made and after this change, shadow is gone). And it's strange that it works in other browsers :(
