### ISSUE TITLE
Vertical text position is different between Safari and other browsers

### ISSUE THREAD

**Issue by kiguri** [konvajs/konva#1751]
As shown below, on the left is Safari, on the right is Edge, the word "Grandma" has a different vertical position. This leads to all browsers on IOS (using the Safari kernel) being different from Android
<img width="1592" alt="Screenshot 2024-04-29 at 10 22 41" src="https://github.com/konvajs/konva/assets/35722061/8ba2a436-53b1-41fa-8042-efb22e7f55ec">

**Comment by lavrton** [comment]
Please provide a minimal online demo. What font you used?

**Comment by Adam-Greenan** [comment]
I'd like to bump this, we have the exact same problem.

Each browser chrome, edge, firefox and safari all render text slightly differently on the y-offset. 

We haven't found a possible solution to this issue yet that viable without manually creating an offset for each browser, on each font - even that is primitive, hardcoded and is never perfect. 

My issue raised similar questions when using konva-node, but the same issue is present in konva react on a regular frontend.

https://github.com/konvajs/konva/issues/1694

**Comment by Adam-Greenan** [comment]
https://codesandbox.io/p/devbox/konva-konva-react-text-location-rendering-on-different-browser-devices-issue-https-github-com-konvajs-konva-issues-1751-z2kkpw?file=%2Fsrc%2FApp.jsx%3A43%2C44

I've prepared a brief demonstration of the problem in CodeSandbox.

Moreover, I've included several screenshots showcasing how the text rendering varies vertically across different browsers and devices. This inconsistency persists regardless of the font used—whether native to the browser, downloaded directly from the web, or from Google Fonts.

**Here's a screenshot taken on Google Chrome for macOS, the platform where the demo was developed:**
![Screenshot 2024-05-08 at 13 52 23](https://github.com/konvajs/konva/assets/71382714/5c732ab4-2462-4b4b-bbf8-743fe640b03b)

**Similarly, here's another screenshot from the same macOS device, but this time using Safari:**
![Uploading Screenshot 2024-05-08 at 13.53.18.png…]()

This inconsistency persists across various browsers and devices.

I trust these visuals effectively illustrate the issue.

**Comment by Adam-Greenan** [comment]
Bump

**Comment by lavrton** [comment]
Please take a look into this comment: https://github.com/konvajs/konva/issues/559#issuecomment-2113766161
I need a help with testing. I hope that will fix the issue.

**Comment by lavrton** [comment]
Closing the issue for now. I am not sure yet when and how the fix defined in https://github.com/konvajs/konva/issues/559#issuecomment-2113766161 will be a default behavior. Looking for a more feedback.
