### ISSUE TITLE
Mouseup triggered the click event for the image, and I hope he doesn't trigger it，It's not as simple as imagined

### ISSUE THREAD

**Issue by hero8080** [konvajs/konva#1755]
[click to codesandbox](https://codesandbox.io/p/devbox/test-konva-event-w9h4n7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvvxhyaf00073z6f0jlzweov%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvvxhyaf00023z6fcrjf7bxx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvvxhyaf00043z6f3zkg1qk6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvvxhyaf00063z6fb45rorlk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B54.96516054881115%252C45.03483945118885%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvvxhyaf00023z6fcrjf7bxx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvvxhyaf00013z6fp8djh1sg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvvxhyaf00023z6fcrjf7bxx%2522%252C%2522activeTabId%2522%253A%2522clvvxhyaf00013z6fp8djh1sg%2522%257D%252C%2522clvvxhyaf00063z6fb45rorlk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvvxhyaf00053z6fyot438rt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvvxhyaf00063z6fb45rorlk%2522%252C%2522activeTabId%2522%253A%2522clvvxhyaf00053z6fyot438rt%2522%257D%252C%2522clvvxhyaf00043z6f3zkg1qk6%2522%253A%257B%2522id%2522%253A%2522clvvxhyaf00043z6f3zkg1qk6%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvvxhyaf00033z6fqd8zb4sh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clvvxhyaf00033z6fqd8zb4sh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D "click to codesandbox")

![test-konva-event](https://github.com/konvajs/konva/assets/52777521/656ff93a-899e-4671-a902-8a599461edd5)

### 以下是简体中文：
# 请先看动态录屏

**Comment by lavrton** [comment]
Thanks for the detailed message. Fixed. It will be released later.
