### ISSUE TITLE
Strange behavior when fillingPatternImage and clone update

### ISSUE THREAD

**Issue by webmaxpro** [konvajs/konva#1760]
Good day. I have created an example for you here: https://jsbin.com/dobives/edit?js,output

I need to place an icon in the rotation anchor. And I have implemented it successfully. I also need to make the object copyable. And now on the copied object the rotation icon behaves strangely. 

How to test: 
1. Click on the green circle - it becomes active.
2. Click on the copy button - the red copied item appears
3. Click on the green (original) - it becomes active. You can move it, rotate it, resize it all right.
4. Click red (copy) - it becomes active. If you rotate it or resize it, everything is fine. But as soon as you move the red one, the rotation icon above the green one becomes active. That's the problem.  I can't understand why it becomes active and how to fix it. Why does moving the copy affect the original? It feels like there is some kind of bug....

![er1](https://github.com/konvajs/konva/assets/8004801/5cb895ba-3cb2-4717-b077-2474bed3d16c)
![er2](https://github.com/konvajs/konva/assets/8004801/6c190213-e1eb-4e72-9ebf-9fcdfe1b20ec)

**Comment by lavrton** [comment]
Looke like this issue my be here:

```js
var cloneTrans = trans.clone({
    id: 'trans' + id,
});
```
  
  It may be better to create a new transformer to not mess things.

**Comment by webmaxpro** [comment]
A new transformer can certainly help. The problem is that in the original code I have a lot of eventListenetrs and other functions on the transformer. And all this will have to be repeated for the new transformer. In the clone they were all copied. 

And there is obviously some bug, because resizing or rotating does not produce an error, but moving does.....
