### ISSUE TITLE
Cannot read 'isDragging' even though importing (unused) Core

### ISSUE THREAD

**Issue by rienheuver** [konvajs/konva#1763]
I'm (also) running into the below error, as was mentioned in #1730
```js
Uncaught TypeError: Cannot read properties of undefined (reading 'isDragging')
    at Object.isDragging (Global.js:46:36)
    at Stage._pointerleave (Stage.js:349:46)
    at content.addEventListener.passive (Stage.js:308:32)
```
However, if I import the following line it doesn't fix it, the problem persists.
```js
import Konva from 'konva/lib/Core';
```
And there's another problem with that: vscode sees it as an unused import since I import all other Konva-object directly as below. So therefore it will want to remove that import. (I can prevent that from happening with a hack of course, but it doesn't fix the `isDragging` either way.)
```js
import { Layer } from "konva/lib/Layer";
import { KonvaEventObject } from "konva/lib/Node";
import { Stage } from "konva/lib/Stage";
import { Tween } from "konva/lib/Tween";
import { Line } from "konva/lib/shapes/Line";
```

**Comment by rienheuver** [comment]
I'm currently using a workaround that fixes both problem:
<strike>
```js
import { Stage } from "konva/lib/Stage";
```
</strike>

```js
const stage = new Konva.Stage();
```

Now the Konva core import is used and the error is gone. But it's not the best fix of course, since I'd rather import Stage directly just as all other classes.

**Comment by lavrton** [comment]
Please make a small demo. I can't reproduce.

**Comment by rienheuver** [comment]
Sure thing!
https://github.com/rienheuver/konva-repro

**Comment by rienheuver** [comment]
Sorry for the late reply. I'll use the `new Konva.Stage()` for now as a fix. Maybe it's a good idea to document this somewhere in case others use a similar setup?
