### ISSUE TITLE
HTML canvas disappears in Chrome after browser window/tab becomes inactive

### ISSUE THREAD

**Issue by thuatnv** [konvajs/konva#1764]
My KonvaJS or Canvas element works perfectly fine except when paint in **Chrome 125.0.6422.61** on a Mac running **MacOS 14.4.1**, where the canvas content gets completely wiped out when I

1. open tab multiple in chrome
2. minimize Chrome. 
3. switch to a different tab
4. swipe to another screen

****Update info Issue from chrome: https://issues.chromium.org/issues/341803761 ****
Pls plus +1 on this issue. :D

**Comment by astronomyf** [comment]
+1 having the same issue here. Running on **Chronium  125.0.6422.60** and **MacOS 14.4.1**

**Comment by thuatnv** [comment]
> +1 having the same issue here. Running on **Chronium 125.0.6422.60** and **MacOS 14.4.1**.
> 
> Edit: Seems to be an issue related to Chrome and experimental features: https://stackoverflow.com/questions/71201403/html-canvas-disappears-in-chrome-after-browser-window-tab-becomes-inactive
> 
> I have the flag off so I'm not sure this explains why is happening to me - but there seems to be a workaround at least

Yep. I found this.  But only outside of incognito mode. I'd appreciate it if the Konva Team could provide a solution that functions in both regular and incognito modes.

**Comment by lavrton** [comment]
Just updated chrome to this version on macOS and I can't reproduce the issue. Can you help me with that?

**Comment by thuatnv** [comment]
> Just updated chrome to this version on macOS and I can't reproduce the issue. Can you help me with that?

To reproduce the issue, follow these steps:

Step 1: Open multiple Chrome tabs (more than 10) and load the KonvaJS demo in each tab.
Step 2: Switch to a different tab and then return to the KonvaJS tab after 30 seconds.

**Comment by alessiocancian** [comment]
Same problem with Chrome 124.0.6367.209 and MacOS 14.3.1

**Comment by chucklazaza** [comment]
Same problem with Chrome 124.0.6367.208 and MacOS Sonoma 14.1

**Comment by lavrton** [comment]
I think I fixed that with `konva@9.3.11`. But to be honest, I am still not sure if this is something that Konva must do.
The solution is simple - redraw layers when tab is active.
So I added that from Konva side a temporary solution, probably it will be better to remove it if Chrome resolves that issue.
