### ISSUE TITLE
The Konva Transformer is unable to change the width and height of the rect

### ISSUE THREAD

**Issue by 929496959** [konvajs/konva#1765]
using js url (https://unpkg.com/konva@9/konva.min.js)

err code 
`
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <script src="https://unpkg.com/konva@9/konva.min.js"></script>
</head>
<body>
    <div id="container"></div>
    <div>
        <input id="X" type="number" value="50">
        
        <input id="Y" type="number" value="50">
        
        <input id="W" type="number" value="50">
        
        <input id="H" type="number" value="50">
        <button onclick="rectchange()" >更新数据</button>
    </div>
    <script>
        // 创建舞台
        var stage = new Konva.Stage({
            container: 'container',
            width: window.innerWidth,
            height: window.innerHeight,
        });

        // 创建层
        var layer = new Konva.Layer();
        stage.add(layer);

        // 创建一个可拖动的矩形
        var rect_test = new Konva.Rect({
            x: 100,
            y: 100,
            width: 100,
            height: 100,
            fill: 'red',
            stroke: 'black',
            strokeWidth: 4,
            draggable: true, // 设置矩形可拖动
        });

        // 创建 Transformer 组件以允许用户更改矩形的大小
        const transformer = new Konva.Transformer({
            nodes: [rect_test],
            keepRatio: false, // 如果你想独立缩放宽度和高度，设置为 false
            resizeEnabled: true, // 启用调整大小的功能
            rotateEnabled: false, // 启用旋转功能（如果需要）
            // ...其他配置
            });
        transformer.rotateEnabled(false); // 禁止旋转
        // 加载图片作为背景
        var imageObj = new Image();
        imageObj.onload = function() {
            var background = new Konva.Image({
                x: 0,
                y: 0,
                image: imageObj,
                width: imageObj.width,
                height: imageObj.height,
            });

            // 设置舞台大小为图片大小
            stage.width(imageObj.width);
            stage.height(imageObj.height);
            stage.draw(); // 重新绘制舞台以反映大小变化

            // 添加背景图片到层中
            layer.add(background);
            layer.draw(); // 重新绘制层以显示背景图片

            layer.add(rect_test);
            layer.add(transformer);
            transformer.attachTo(rect_test);
            
            layer.draw();
            
        };
        imageObj.src = "http://gips3.baidu.com/it/u=3886271102,3123389489&fm=3028&app=3028&f=JPEG&fmt=auto?w=1280&h=960"
        // 限制矩形使其不能超出绘画区域
        rect_test.on('dragmove', function() {
            var pos = rect_test.position();
            var width = rect_test.width() * transformer.getAttrs().scaleX;
            var height = rect_test.height() * transformer.getAttrs().scaleY;
            var maxX = stage.width() - width;
            var maxY = stage.height() - height;

            if (pos.x < 0) {
                pos.x = 0;
            } else if (pos.x > maxX) {
                pos.x = maxX;
            }

            if (pos.y < 0) {
                pos.y = 0;
            } else if (pos.y > maxY) {
                pos.y = maxY;
            }

            rect_test.position(pos);
        });
        // 获取矩形的位置和大小
        function getRectPositionAndSize() {
            var pos = rect_test.position();
            // 使用 Transformer 的 getAttrs 方法获取变换后的宽度和高度
            var attrs = transformer.getAttrs();
            console.log(attrs);
            console.log('Rectangle Position: x=' + pos.x + ', y=' + pos.y);
            var width=transformer.width();
            var height=transformer.height();
            console.log('transformer Rectangle Size: width=' +(width-rect_test.strokeWidth())+ ', height=' + (height-rect_test.strokeWidth()));
            
        }

        // 监听矩形拖动结束事件来获取位置和大小
        rect_test.on('dragend', function() {
            getRectPositionAndSize();
            const x = rect_test.x();
            const y = rect_test.y();
            const width = rect_test.width();
            const height = rect_test.height();
            console.log('x:', x, 'y:', y, 'width:', width, 'height:', height);
        });

        // 监听 transformer 的变换事件来获取位置和大小
        transformer.on('transform', function(e) {
            console.log(e)
            
            getRectPositionAndSize();
        });

        // 监听变换结束事件 
        transformer.on('transformend', function(e) {
            const x = rect_test.x();
            const y = rect_test.y();
            const width = rect_test.width();
            const height = rect_test.height();
            console.log('x:', x, 'y:', y, 'width:', width, 'height:', height);
            //     console.log(e)
            //     console.log(e.currentTarget)
            //     console.log('x:',e.currentTarget.x(), 'y:', e.currentTarget.y(), 'width:', e.currentTarget.width(), 'height:', e.currentTarget.height());
            //    // 获取变换后的节点（这里假设只有一个节点）
            //     rect.x(e.currentTarget.x());
            //     rect.y(e.currentTarget.y());
            //     rect.width(e.currentTarget.width());
            //     rect.height(e.currentTarget.height());
            //     rect.scaleX(1);
            //     rect.scaleY(1);
            //     transformer.scaleX(1);
            //     transformer.scaleY(1);
            //     transformer.cos=(1);
            //     transformer.sin=(1);
            });

        function rectchange(){
            console.log(111)
            var x=document.getElementById('X').value;
            var y=document.getElementById('Y').value;
            var w=document.getElementById('W').value;
            var h=document.getElementById('H').value;
            console.log(x,y,w,h)
            rect_test.x(x);
            rect_test.y(y);
            var tw=Number(w)+Number(rect_test.strokeWidth());
            var th=Number(h)+Number(rect_test.strokeWidth());
            console.log(tw,th)
            // transformer.width(tw)
            // transformer.height(th)
            // rect_test.width(w);
            // rect_test.height(h);
            layer.draw();
        }
        // 添加按钮来获取信息
        document.body.insertAdjacentHTML('beforeend', '<button id="getInfo">Get Rectangle Info</button>');
        document.getElementById('getInfo').addEventListener('click', getRectPositionAndSize);
    </script>
</body>
</html>

`

**Comment by 929496959** [comment]
this code is demo

**Comment by lavrton** [comment]
Use non-minified version to see what is wrong. https://unpkg.com/konva@9/konva.js
Hint: convert strings from inputs into numbers when you pass values into konva.
