### ISSUE TITLE
Transformer blocks konva after using multitouch

### ISSUE THREAD

**Issue by kamil-zak** [konvajs/konva#1767]
Using Transformer on the touch screen, everything works fine until I touch two corners at the same time and then move it, everything freezes. Nothing can be moved or transformed. When touching with two fingers there are two onTransformStart events, but when released there is only one onTransformEnd event.
In console there are no any errors.
The problem appeared in version 9.3.5, in version 9.3.4 everything works fine.

This issue also exists on demo page of Transformer:
https://konvajs.org/docs/select_and_transform/Transform_Events.html

Problem occurs on both chrome and firefox.

**Comment by lavrton** [comment]
I can't reproduce that on the iPad and iPhone.

**Comment by kamil-zak** [comment]
I reproduced this on my iPhone. I noticed new condition. You need to touch one corner, and without making any move touch second corner. (two touchstart events, no touchmove). After that if you make any move everything will freeze. If you start moving before second touch start this problem not occur

https://github.com/konvajs/konva/assets/85481234/e0e92953-2a7f-4cd8-ab05-10d21ae8a717

**Comment by lavrton** [comment]
Thanks for the report. Release with a fix is published.
