### ISSUE TITLE
Demo not working on konvajs.org homepage

### ISSUE THREAD

**Issue by JeffreyArts** [konvajs/konva#1769]
Hi,

I wanted to let you know that this library is not working on Brave [Version 1.65.126 Chromium: 124.0.6367.118 (Official Build) (arm64)](https://brave.com/latest/). Only one star can be dragged, and after is has been isolated, only the top and top-right scale boxes work.

**Comment by lavrton** [comment]
https://github.com/konvajs/konva/issues/1132#issuecomment-867339732
