### ISSUE TITLE
Konva@9.3.9 + Animation，The page crashes after running for a while

### ISSUE THREAD

**Issue by xue1992115** [konvajs/konva#1773]
Environment:
Window System
Chrome Browser

Konva9.3.9

Problem Description:
Add animation effects to the text node, and the page will crash after running for about an hour.  [This is the link to reproduce](https://jsfiddle.net/8xw3fgdy/1/).

**Comment by ZoeLeee** [comment]
#1796  It could be the same issue.

**Comment by lavrton** [comment]
Closing for now. Just tested in the last chrome. I dont' see any leaks.
