### ISSUE TITLE
bug: Text stroke is buggy in android webview

### ISSUE THREAD

**Issue by EinfachHans** [konvajs/konva#1774]
## Description

I use this awesome library in an ionic angular application. I encountered a problem, which seems to be only available in android webview.

The stroke of a text seems to be visible inline.

|iOS|Android|
|----|----|
|![WhatsApp Image 2024-06-07 at 15 01 23](https://github.com/konvajs/konva/assets/20899975/03cfa739-08c3-4e4b-a872-9bc27a0b6945)|![WhatsApp Image 2024-06-07 at 15 01 48](https://github.com/konvajs/konva/assets/20899975/483e186e-34c2-4152-b2ed-8b1eb5fbfe4b)|

## Reproduction 
https://jsbin.com/gazusafuta/edit?html,js,output

**Comment by lavrton** [comment]
I don't think we can do much here from Konva side.

**Comment by EinfachHans** [comment]
@lavrton Why not? Can you give me more input about the root cause of this issue?

**Comment by lavrton** [comment]
I guess this is just how android webview rendering words for stroked text.

You can try to experiment with native 2d canvas API to see if you can have any other results.

A possible and ugly workaround is to still draw white text on top of stroked text to "erase" these internal stroke parts.

**Comment by EinfachHans** [comment]
I continue with the ugly workaround for now...

@lavrton Do you have experience in submitting bugs to the android webview engine? As an expert of this, maybe you can create a issue?
