### ISSUE TITLE
Transformer issue with Brave Browser

### ISSUE THREAD

**Issue by fegauthier** [konvajs/konva#1775]
Hi guys!

I have some issue with the resize transformer on Brave Browser. Not every anchors are clickable. The issue doesn't happen in Dev. Only in production environment. I have the same issue with the Transformer Doc on KonvaJS website.

https://konvajs.org/docs/select_and_transform/Transform_Events.html

I attached a video of the issue. Some anchors as usable and others not.

https://youtu.be/0d0V4ZMrzAg

Is there any solution to that?

I tested with Firefox and It's working.

My brave version is

![image](https://github.com/konvajs/konva/assets/12112673/86ba6c3d-1f7b-47ec-837a-3a087604e255)

I'm on Linux

Thanks!

**Comment by fegauthier** [comment]
Set Shield down fix the issue. Thanks!

**Comment by lavrton** [comment]
From konva version 10.0.10 it should work better. It will use a bit different hit color logic to handle canvas farbling.
