### ISSUE TITLE
Warning regarding CommonJS or AMD dependencies can cause optimization bailouts

### ISSUE THREAD

**Issue by pixobe** [konvajs/konva#1778]
Dear Team,
 I am trying to using konva in Angular project, am getting the following error.
However app works fine am able to render the components and also I do not noticed any optimization issues as such, however this warning is little concerning.

```
▲ [WARNING] Module 'konva' used by 'src/app/app.component.ts' is not ESM

  CommonJS or AMD dependencies can cause optimization bailouts.
  For more information see: https://angular.dev/tools/cli/build#configuring-commonjs-dependencies
```
This is how am importing , 
```
import Konva from 'konva';
```
Usage in app,
```
const stage = new Konva.Stage({
      container: 'container',
      width: window.innerWidth,
      height: window.innerHeight,
    });
```
Any idea if am importing it wrongly or trying not to do recommended way?

Thank you in advance.

**Comment by lavrton** [comment]
Just mark `konva` as ok to be loaded via cmj, something like this (see linked angular docs):

```js
"build": {
  "builder": "@angular-devkit/build-angular:browser",
  "options": {
     "allowedCommonJsDependencies": [
        "konva"
     ]
     …
   }
   …
},
```

**Comment by tbo47** [comment]
@pixobe I published a es version of konva here https://github.com/tbo47/konva-es
