### ISSUE TITLE
Errors when running tests in node

### ISSUE THREAD

**Issue by leahsteinberg** [konvajs/konva#178]
Hi! I'm having an issue with Konva when I run it in node for tests. Before the tests actually run, when it imports Konva, I get this error:

```
/Users/leahsteinberg/src/project/node_modules/konva/konva.js:284
    Konva.Collection = function() {
    ^
ReferenceError: Konva is not defined
```

This doesn't stop me from running Konva in the browser, I think this has to do with running it in node (for tests). I have tried adding canvas and jsdom, but that doesn't seem to have helped.
Thank you!

**Comment by lavrton** [comment]
Hi. Sorry for late response. Please create a reproducible example.

**Comment by leahsteinberg** [comment]
Hey! I ended up getting around this by only importing konva when it isn't being run in node.

**Comment by arusantimo** [comment]
@lavrton @leahsteinberg  I don't think not-importing konva is a right solution...
I'm working on a server-side rendering with react-konva and this is messing stuff up
