### ISSUE TITLE
How to bypass onclick events between layers?

### ISSUE THREAD

**Issue by teddybee** [konvajs/konva#1780]
I have two layers. On the back layer there are shapes that I can select by mouse click. On the front layer I can draw transparent rectangles. 
I need the front layer functions only as an information holder/GUI. My problem is the rectangles are preventing onclick events on the shapes behind them.

Are there any method to disable/prevent the layer onclick handling or pipe over them to the back layer?

**Comment by kamil-zak** [comment]
You can disable listening on front nodes

https://konvajs.org/docs/events/Listen_for_Events.html

**Comment by teddybee** [comment]
Thank you, it's working.
