### ISSUE TITLE
Would it be right if I try to integrate dxf file decoder as a shape into Knova?

### ISSUE THREAD

**Issue by jeff1992** [konvajs/konva#1781]
I'm use Konva in my project which display biulding map and it's device symbles. The backgound map always given as a dxf file(converted from dwg), and I need to display it in Knova. I found a npm package "dxf" a nice solution that decode dxf objects into several polylines. 

see dxf: https://github.com/skymakerolof/dxf

**Comment by lavrton** [comment]
It can be done as a separate package/plugin. If you are interested, feel free to publish it.
