### ISSUE TITLE
How Polotno resizes the stage 

### ISSUE THREAD

**Issue by liganghui** [konvajs/konva#1782]
I tried Polotno, it's really great!
I found that it can resize the canvas, but the width and height of the konvajs-content canvas element are not changed. This is different from konva .  How is this done ?
Can you make a demo? Or explain the principle? Thanks !!

**Comment by lavrton** [comment]
It is just a simple scaling of a content. `group.scaleX(scalingFactor)`, where `scalingFactor` is calculated from available size.

It is very similar to https://konvajs.org/docs/sandbox/Responsive_Canvas.html.

"Resize canvas" in that context should be worded as "resize page" and "resize page" is not equal to "resize canvas element".
