### ISSUE TITLE
Exporting images using stage.toDataURL() ios devices will have black edges

### ISSUE THREAD

**Issue by Jonas949** [konvajs/konva#1783]
When pixelRatio: window.devicePixelRatio is set using the stage.toDataURL() method, a black edge appears when the ios device exports images

<img width="95" alt="1719565252288" src="https://github.com/konvajs/konva/assets/54925213/45bc0182-8159-4249-9508-76d643d5b4a5">

If I don't set pixelRatio, there will be no black edges.

Android devices do not appear similar situation, please tell me how I should adapt.

**Comment by Jonas949** [comment]
![Uploading 1719565794266.png…]()
My export Settings

**Comment by lavrton** [comment]
Please make a small online demo.
