### ISSUE TITLE
Handling drop, dragenter, and dragleave events on Konva.Group from html list with draggable elements

### ISSUE THREAD

**Issue by carlos-v278** [konvajs/konva#1784]
I'm currently working on a new version of a restaurant seating plan, and this version needs to be implemented using Konva. The old version was developed with HTML, CSS, and SVG. However, I'm facing an issue with attaching certain events (such as drop, dragenter, dragleave) to a table, which is represented as a Konva.Group.

My question is: how can I attach these same events to a Konva.Group? Additionally, the draggable element starts from an HTML list and needs to be dropped into a Konva.Group within the canvas layer.

Thank you for your assistance!
![issue-konva](https://github.com/konvajs/konva/assets/89321299/cb893d11-ea77-42c8-a5fe-2ddcafed52b9)

**Comment by lavrton** [comment]
Konva doesn't support drop even directly (such as `dragenter` or `dragleave`).  You can add them by yourself with a little extra code: https://konvajs.org/docs/drag_and_drop/Drop_Events.htm

Here is an example of dropping html element into a canvas: https://konvajs.org/docs/sandbox/Drop_DOM_Element.html
