### ISSUE TITLE
How can we pass event object to fire() function?

### ISSUE THREAD

**Issue by progfargo** [konvajs/konva#1786]
I want to fire a click event for a layer which has another layer on top of it. When top layer receives an 'click' event, how can we pass this event to lower layer?

**Comment by progfargo** [comment]
Ok. I understand by console.log(layer.fire)

Now how can i write a handler function for all events. Is there a glob event name?

**Comment by lavrton** [comment]
What is your use case? Why do you need a global listener and why do you trigger events manually?

**Comment by progfargo** [comment]
Hi Anton,

I wanted to put a filter on the stage. This is a layer, colored (red) and
opacity 0.3. To make the entire stage appear under a red filter. In this
case, events are captured in the upper layer. I wanted to direct all of
these events to the layer below.

My second scenario: I want to place a viewfinder on the stage, indicating
the boundaries of the drawing, for example, a viewfinder is a frame with a
square in the middle. I wanted to direct the events coming to this frame to
the layer below.

I'm just learning Konva, sorry if I asked a meaningless question.

Best,
Erdem Eker

**Comment by lavrton** [comment]
I don't recommend firing any events manually. You can listen to all events on the top container, such as the stage and then filter them, if you need that.
Or you can set `listening: false` on some of the nodes to remove them from hit testing, so they don't trigger any events.

**Comment by progfargo** [comment]
Thank you.
