### ISSUE TITLE
hitFunc 'fillRule' is invalid

### ISSUE THREAD

**Issue by 1514599514** [konvajs/konva#1787]
![image](https://github.com/user-attachments/assets/5d94e703-24e2-428e-80d3-2910a8db6814)
![image](https://github.com/user-attachments/assets/aa5f8e82-126d-4de1-a125-0c37ad08cdd3)

空白区域也接受了点击事件
The blank area also accepted click events

复现错误的项目地址
Reproduce the incorrect project address
[https://github.com/1514599514/konva-test](url)

抱歉, 我没有能力提供PR
Sorry, I am not capable of providing PR

**Comment by lavrton** [comment]
Thanks for the sample. Fixed. I will release later.
