### ISSUE TITLE
Customize the rotation icon and the position of the rotation axis.

### ISSUE THREAD

**Issue by cheerylong** [konvajs/konva#1788]
Hello, I would like to implement this feature in the diagram using Konva. I have been searching for a long time but have not found a suitable solution. Is it possible to achieve this style in Konva? If there is a method, please provide me with some guidance. Thank you.
<img width="204" alt="image" src="https://github.com/user-attachments/assets/b24c9dd6-776d-4f36-8c12-44837edad1fd">

**Comment by lavrton** [comment]
I think the best way is to make your own implementations of such buttons. The UI is just far from `Konva.Transformer` behaviour.

Just create a rectangle on top of the image, and put circles + icons for anchors. Then implement the logic of every anchor click/drag.

**Comment by cheerylong** [comment]
> I think the best way is to make your own implementations of such buttons. The UI is just far from `Konva.Transformer` behaviour.
> 
> Just create a rectangle on top of the image, and put circles + icons for anchors. Then implement the logic of every anchor click/drag.

Thank you for your reply. Are you saying that all the functions of rotation, scaling, and moving need to be manually implemented, and does Konva provide any auxiliary methods for this? Thank you.

**Comment by lavrton** [comment]
> does Konva provide any auxiliary methods for this?

What methods you want? Just a regular `node.x(val)`, `node.width(val)`, `node.rotation(val)` to control attributes. Do that on drag of the anchor, calculated needed values.

**Comment by wuwentao-web** [comment]
`const tr = new Konva.Transformer({
                rotateLineVisible: false,
                rotateAnchorOffset: 13,
                anchorSize: 7,
                rotationSnaps: [0, 90, 180, 270],
                enabledAnchors: ['top-left', 'top-right', 'bottom-left', 'bottom-right'],
                flipEnabled: false,
                anchorStyleFunc: (anchor) => {
                    if (anchor.getAttrs().name === 'rotater _anchor') {
                        // 通过设置锚点为图片来自定义旋转图标
                        const rotateIcon = new Image();
                        rotateIcon.src = instructionsDraw; // 这里是你自定义旋转图标的路径
                        anchor.fillPatternImage(rotateIcon);
                    }
                }
            })
            this.transformerLayer.add(tr);
            tr.nodes([image])`自定义旋转图标不生效
