### ISSUE TITLE
Image from imageData?

### ISSUE THREAD

**Issue by macrozone** [konvajs/konva#179]
Hi konva Team,

Currently an Image needs a dom-element image. Is it possible to use directly imageData to create a Konva-image? So we do not need to use this workaround: http://stackoverflow.com/questions/13416800/how-to-generate-an-image-from-imagedata-in-javascript

**Comment by lavrton** [comment]
@macrozone Hi. You don't need this workaround for creating an image, as you can use canvas directly for `Konva.Image`. Just need to create canvas element for your `imageData`.

**Comment by macrozone** [comment]
Ok, but how do i create a konva.image with a canvas?

**Comment by lavrton** [comment]
```javascript
const canvas = document.createElement('canvas');
// .... draw your imageData into canvas
const image = new Konva.Image({ image: canvas });
```

**Comment by macrozone** [comment]
aah, awesome, thx!

Anton Lavrenov <notifications@github.com> schrieb am Mo., 10. Okt. 2016 um
14:34 Uhr:
