### ISSUE TITLE
Does It support controlled mode?

### ISSUE THREAD

**Issue by vaynevayne** [konvajs/konva#1790]
I don't see any apis or demos for controlled use. Do you support them?

**Comment by lavrton** [comment]
What do you mean by "controlled use"?

**Comment by vaynevayne** [comment]
yes
 https://zh-hans.legacy.reactjs.org/docs/forms.html#controlled-components

**Comment by lavrton** [comment]
It is partially supported with the strict mode: https://github.com/konvajs/react-konva?tab=readme-ov-file#strict-mode
