### ISSUE TITLE
Event `currentTarget` always typed as `Node`

### ISSUE THREAD

**Issue by daformat** [konvajs/konva#1794]
I'm using Konva with React. I'm noticing the type of `KonvaEventObject` is:

```ts
export interface KonvaEventObject<EventType> {
    type: string;
    target: Shape | Stage;
    evt: EventType;
    pointerId: number;
    currentTarget: Node;
    cancelBubble: boolean;
    child?: Node;
}
```

Hence, the `currentTarget` is always a `Node`. Wouldn't it make sense to add another generic argument so that we can specify the exact type of the `currentTarget` (for example a `Rect` or any other)?

Something like:

```ts
export interface KonvaEventObject<EventType, EventTarget = Node> {
    type: string;
    target: Shape | Stage;
    evt: EventType;
    pointerId: number;
    currentTarget: EventTarget;
    cancelBubble: boolean;
    child?: Node;
}
```

I was hoping that the type `KonvaEventListener` would provide me with a way to do that, but the current type is:

```ts
export type KonvaEventListener<This, EventType> = (this: This, ev: KonvaEventObject<EventType>) => void;
```

So this includes a first argument which is `this` and it doesn't actually enforece the type of `currentTarget`.
What I would need would be (with the previous modification of the `KonvaEventObject` type) would be:

```ts
export type KonvaEventListener<EventTarget, EventType> = (ev: KonvaEventObject<EventType, EventTarget>) => void;
```

The reason for that is that:
- right now I can't specify the type of the currentTarget, and have to resort to check the type in each listener
- when declaring an event listener function, I'd like a generic type to describe it instead of always having to write the same `(event: KonvaEventObject) => void` thing.

Maybe I'm missing something though, thoughts and comments welcome 🙏

**Comment by daformat** [comment]
FIY the current solution I'm using is to define my own `KonvaEventListener`:

```ts
export type KonvaEventListener<EventTarget, EventType> = (
  event: KonvaEventObject<EventType> & {
    currentTarget: EventTarget;
  }
) => void;
```

**Comment by lavrton** [comment]
Fixed. Will release later.
