### ISSUE TITLE
[Out of Memory]Memory overflow due to heavy text rendering

### ISSUE THREAD

**Issue by ZoeLeee** [konvajs/konva#1796]
When Konva renders a large amount of text, it causes memory to continuously grow until it results in an "out of memory" error.

https://codepen.io/zoeleee/pen/vYqKYPB

This is preview page
https://cdpn.io/zoeleee/fullpage/vYqKYPB?anon=true&view=  

userAgent:
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

![Uploading image.png…]()

**Comment by lavrton** [comment]
Closing for now. Just tested in the last chrome. I dont' see any leaks.
