### ISSUE TITLE
Stage.d.ts make StageConfig container optional for use in node environment

### ISSUE THREAD

**Issue by daniatic** [konvajs/konva#1797]
The readme states that the container property in StageConfig can be omitted for use in a Node environment. However, the type definition still requires the container property, causing a conflict. I can simply ignore this conflict, but would it be possible to make the property optional?

**Comment by lavrton** [comment]
Interested in making a pull request?

**Comment by daniatic** [comment]
https://github.com/konvajs/konva/pull/1801

**Comment by lavrton** [comment]
Thanks

**Comment by daniatic** [comment]
No, thank you!
