### ISSUE TITLE
Blur filter is distorting shapes and colors

### ISSUE THREAD

**Issue by tomaszwaraksa** [konvajs/konva#1799]
Blur filter applied to a simple shape (green circle) results in a distorted shape and weird yellow colors added on the borders. 

Another circle, implemented as custom shape using HTML5 canvas wrapped in Konva.Image and with blur filter applies, is rendered correctly.

Code to reproduce the issue:
https://jsbin.com/ladixireqi/1/edit?html,js,output

![image](https://github.com/user-attachments/assets/7eb49e11-c744-43b0-b56f-dd0f0aea757e)

**Comment by lavrton** [comment]
It looks like this is the side effect of the algorithm that is used for blur. For performance reasons, I don't want to change to full Gaussian Blur.

As the workaround, you can use your own implementation of blur filter.
