### ISSUE TITLE
Demos?

### ISSUE THREAD

**Issue by gingerbeardman** [konvajs/konva#18]
Wondering where are the demos for this rebirth fork? 

I get 404 for each item in the Sandbox section.

**Comment by jovination** [comment]
Its being worked on, but right now most of them still carry the Kinetic naming structure.  

https://github.com/konvajs/site is where the work is being done to update them.

**Comment by lavrton** [comment]
Links are repaired. But demos for old `Kinetic` namespace. Updates for `Konva` namespace will be soon.

**Comment by gingerbeardman** [comment]
Thanks!
