### ISSUE TITLE
Add different kinds of shapes/text to a Label

### ISSUE THREAD

**Issue by BearTi** [konvajs/konva#180]
Hi,

how can I add different kind of Text (for example one text is bold, the other one not) to a Konva.Label (https://konvajs.github.io/docs/shapes/Label.html) or is it even possbile?

Also I would need a button inside this label.

Thanks a lot!

**Comment by lavrton** [comment]
@BearTi, unfortunately, it is not possible right now, you have do draw such text separately. You can use `Konva.Rect` + `Konva.Text` for better control.

**Comment by BearTi** [comment]
Ok, thanks.

Maybe you help me to draw such a Label (with an arrow pointing down, see https://konvajs.github.io/docs/shapes/Label.html) with Konva.Line() respectively a Polynom?

I not really understand how I can draw a polynom (https://konvajs.github.io/docs/shapes/Line_-_Polygon.html). I donßt understand how I must place the "points".

Thanks

**Comment by lavrton** [comment]
I will close the issue. For questions please use gitter or stackoverflow.
