### ISSUE TITLE
Find image by id and then replace

### ISSUE THREAD

**Issue by along7455** [konvajs/konva#1800]
Need help,I want to find a certain image based on the ID, click the button and replace the image.

 const layerDevice = new Konva.Layer(); 
 stage.add(layerDevice);  
images.forEach((item:any) => { 
        Konva.Image.fromURL(item.imgUlr, function(deviceImg) {
          deviceImg.setAttrs({
          x: item.drawX,
          y: item.drawY,
          scaleX: 0.3,
          scaleY: 0.3,
          id: item.id
        });
        layerDevice.add(deviceImg);    
        layerDevice.batchDraw();
      }); 
    }) 

function updateTheImage(){
	var objImg= stage.find('#'+mapEsd.id)[0];
	//how I update the image with another image?
}

**Comment by lavrton** [comment]
```js
function updateTheImage(newImageUrl, imageId){
  // Find the image object by its ID
  var objImg = stage.findOne('#' + imageId);

  // Load the new image
  var newImageObj = new Image();
  newImageObj.src = newImageUrl;

  // When the new image is loaded, update the Konva.Image node
  newImageObj.onload = function() {
    objImg.image(newImageObj);
  };
}
```

**Comment by along7455** [comment]
> ```js
>   var objImg = stage.findOne('#' + imageId);
> 
>   // Load the new image
>   var newImageObj = new Image();
>   newImageObj.src = newImageUrl;
> 
>   // When the new image is loaded, update the Konva.Image node
>   newImageObj.onload = function() {
>     objImg.image(newImageObj);
>   };
> ```

Great work,thanks for the feedback! thank you very much!
