### ISSUE TITLE
Setting stroke and shadowColor attributes at the same time causes node lag

### ISSUE THREAD

**Issue by ysl-ccc** [konvajs/konva#1802]
[https://codesandbox.io/p/sandbox/konva-stroke-shadow-4qpq6r](url)

![image](https://github.com/user-attachments/assets/d73509da-1bc0-4c3b-bd48-9d3b6f019a94)

Comment out the shaowColor in the red box, and you will no longer be stuck when dragging the rectangle. If you add shaowColor, it will be very stuck.

**Comment by lavrton** [comment]
That is the effect of a special mode to fix rendering inconsistencies. You can disable it `perfectDrawEnabled: false,`.

For more info: https://konvajs.org/docs/performance/Disable_Perfect_Draw.html

**Comment by ysl-ccc** [comment]
Ok
