### ISSUE TITLE
`stage.startDrag()` is much slower than vanilla `dragButtons`' drag

### ISSUE THREAD

**Issue by monoglo** [konvajs/konva#1808]
It seems that `startDrag()` causes redrawing instead drag with `Konva.dragButtons` doesn't, which causes perfomance issue.

Like #1039, I want to drag elements with left mouse button, and to drag global stage with middle mouse button, so I only set
```js
Konva.dragButtons = [0]
```
to prevent middle mouse button dragging elements, typically when mouse hover on a huge element.
then by following guides, 
```js
stage.on('mousedown', (e) => {
    if (e.evt.button === 1) {
        if (!this.stage.isDragging()) {
            this.stage.startDrag()
        }
    }
})
stage.on('mouseup', (e) => {
    if (e.evt.button === 1) {
        if (this.stage.isDragging()) {
            this.stage.stopDrag()
        }
    }
})
```

Soon I feel bad performance(20-30 fps) dragging with middle mouse, but with left mouse everything is good(60 fps).
I have hundreds of elements, so that I think this is a performance issue.

**Comment by lavrton** [comment]
Please make a small online demo.

**Comment by monoglo** [comment]
> Please make a small online demo.

For some reason it‘s hard to reproduct the issue, but when I made the amount of elment larger, both cause performance issue.
So I fix it with caching whole stage.

**Comment by monoglo** [comment]
I finally find the key, it's the Proxy of vue.
For a long time, I accessed my konva instance by vue's Proxy which my every access through.
After I get my real konva by toRaw() of vue, it's up to 60fps instantly!
