### ISSUE TITLE
 Implementing Drag Bound and Zoom Functionality in a Drawing Board

### ISSUE THREAD

**Issue by jonas2024181** [konvajs/konva#1816]
I am currently developing a simple drawing board with the following stage properties: the position x, y  set at (100, 100), and its width and height are 600, 600. I need assistance with implementing two features:

Drag Bound Function: I want to ensure that the drawing board remains within the viewport when dragged. The board should not be allowed to move outside of its defined boundaries.

Zoom Functionality: I need to implement zooming capability, which should allow users to zoom in and out on the drawing board, adjusting the view while maintaining the ability to drag the board within its bounds.

Could you provide guidance on how to implement these features effectively?

**Comment by lavrton** [comment]
Did you try anything? 

Did you look here https://konvajs.org/docs/drag_and_drop/Complex_Drag_and_Drop.html and here https://konvajs.org/docs/sandbox/Zooming_Relative_To_Pointer.html
