### ISSUE TITLE
I hope to add new draggable functions to the existing ones.

### ISSUE THREAD

**Issue by maxfrees** [konvajs/konva#1818]
ref https://konvajs.org/docs/sandbox/Resizing_Stress_Test.html

Now we can only multi-select. We hope to add multi-selection. After dragging, we can modify the size and change the position.

**Comment by lavrton** [comment]
What is your question?

**Comment by maxfrees** [comment]
In the demo of this performance test, you can only make multiple selections, but there is no way to drag the position. I hope the example can be improved.   @lavrton

**Comment by lavrton** [comment]
Updated.

**Comment by maxfrees** [comment]
好的，感谢你，期待您跟踪下，https://github.com/konvajs/konva/issues/1820    https://github.com/konvajs/konva/issues/1819   


@lavrton
