### ISSUE TITLE
Add a straight line demo to create this effect to the official website document

### ISSUE THREAD

**Issue by maxfrees** [konvajs/konva#1819]
Add a straight line demo to create this effect to the official website document

And support for wsad adjustment position

https://github.com/user-attachments/assets/8304ce79-60b8-4d0d-8088-14fcf39149bb

**Comment by lavrton** [comment]
Thanks for the request. It may be added later or not.

**Comment by maxfrees** [comment]
Expect to add it, complete more usage examples, it should be simple for you
