### ISSUE TITLE
Typescript: Property 'Arrow' does not exist on type 'typeof Konva'.

### ISSUE THREAD

**Issue by newmediamonkey** [konvajs/konva#182]
When I install Konva@1.2.2 through npm for an Angular 2 app, I receive this error:

Property 'Arrow' does not exist on type 'typeof Konva'.

All other shapes work for me, but the Arrow looks to be missing the typescript declaration.

Thanks, and keep up the great work!

**Comment by lavrton** [comment]
Ah. Yeah. This one is missed. You can send Pull Request if you want.

**Comment by lavrton** [comment]
Close by https://github.com/konvajs/konva/pull/183
