### ISSUE TITLE
Capturing what the what is rendered to a layer within a region of interest using the _context?

### ISSUE THREAD

**Issue by ArEnSc** [konvajs/konva#1822]
I was using this where  # captureCanvas: Konva.Rect;

  const dataURL = this.videoLayer.toDataURL({
          x: this.captureCanvas.x(),
          y: this.captureCanvas.y(),
          width: this.captureCanvas.width(),
          height: this.captureCanvas.height(),
        });
        
to capture what was in the a konva ImageRect (this.captureCanvas)
It works however is super slow.

I need to get direct access to the data in that region in the layer.
But using the offScreenCanvas and grabbing the 2D context.

So I was able to set that up, however... 
when performing this operation

```
 this.offScreenCanvas.width = this.width;
        this.offScreenCanvas.height = this.height;
        this.context.drawImage(
          this.videoLayer.canvas._canvas,
          this.positionX,
          this.positionY,
          this.captureCanvas.width(),
          this.captureCanvas.height(),
          0,
          0,
          this.width,
          this.height,
        );
```

It doesn't seem grab the region correctly either due to scaling issues? when I zoom in and out of the browser a bit, it seems to work but then on different displays it doesn't capture it correctly.
I suspect this has to do with pixel ratio?
I need it to be rendered on the offScreen Canvas so I can send this off to a web worker to process
@lavrton lmk if if you have any other ideas of how to achieve this.

**Comment by lavrton** [comment]
Make a small demo. I don't understand what you are trying to do.

**Comment by ArEnSc** [comment]
@lavrton thanks for responding!

**Comment by lavrton** [comment]
I still don't get it.

Why don't you use regular toDataURL() or toCanvas() exports? If it is slow for you, can you give a context when/how you call it?

You may have scale issues, because of pixelRatio. Canvas size of the layer may be bigger than css size, to have sharp images on HDPI devices like retina.

**Comment by ArEnSc** [comment]
> to

Yeah it was the scale issues, I dug into the code and created something that would allow me do what u wanted by subclassing then draw scene
