### ISSUE TITLE
Why the rect is overlaid to the Transformer

### ISSUE THREAD

**Issue by maxfrees** [konvajs/konva#1823]
Why the rect is overlaid to the Transformer

When I first create Transformer and then add a rect to the layer, I find that Transformer does not display completely

I tried to move Transformer to top, but this also caused stage.on('click tap') to not work properly, because now the click selects Transformer instead of rect

```
  if (selectionRectangle.visible()) return;
  if (e.target.parent === transformer) return;
  if (e.target === stage) {
    transformer.nodes([]);
    return;
  }
```

**Comment by lavrton** [comment]
What is your question?

> Why the rect is overlaid to the Transformer

Because it was on top?

**Comment by maxfrees** [comment]
I'm not sure exactly why, I'm just adding the rectangle after creating the transformer, and if checked, it looks like it's on top of the transformer
