### ISSUE TITLE
Leaferjs claims to be ten times more performant than Konva, is than true? 

### ISSUE THREAD

**Issue by xachary** [konvajs/konva#1825]
Someone commented in a issue on this [project sample](https://xachary.github.io/konva-designer-sample/) about the
[leaferjs](https://www.leaferjs.com/engine/konva/) claims to be ten times more performant than Konva, is than true? 

<img width="574" alt="image" src="https://github.com/user-attachments/assets/e4a08008-0e50-4f44-8986-db9ee954462c">

<img width="565" alt="image" src="https://github.com/user-attachments/assets/4d73f50a-07b1-48cd-a58c-f37582ee5150">

![image](https://github.com/user-attachments/assets/aa93ff19-3f40-4f36-bd47-d54d18d5f194)

**Comment by lavrton** [comment]
Cool project! Thanks for sharing.

It may be true, depending on the use case. Konva is not designed for the maximum possible performance by default. Instead, it is designed for better API and smooth experience with 2d canvas usage, covering tons of graphical edge cases by default.

Better compare framework on some real use cases. Like if you want to render 1 million rectangles in your app, then a test in the link is a good demo. But probably you do something different.

**Comment by xachary** [comment]
@lavrton Thanks~
