### ISSUE TITLE
konva esm

### ISSUE THREAD

**Issue by tbo47** [konvajs/konva#1829]
I had issues with konva not being esm for my angular project.

I created https://github.com/tbo47/konva-es?tab=readme-ov-file

I would be happy if that was part of the konva project. It seems to have been discussed before. I'm not sure what is the best path forward.

**Comment by lavrton** [comment]
I tried very hard to have ES version of Konva. But there was ALWAYS someone who is failing. No mater how hard I tried, next.js, jest, some another bundler.

It should be possible to configure angular project to accept CommonJS module.

I will revisit full ES support later. I think at a time when Node.js will have a very wide support for importing es modules from commonjs.

**Comment by tbo47** [comment]
okay, I'm happy to help if you want me to.

Here is the package I published using es format https://www.npmjs.com/package/konva-es

It works for my needs. Angular 18 app.
