### ISSUE TITLE
Transformer/Text width is not being update on font size chanfe

### ISSUE THREAD

**Issue by michalgrzyska** [konvajs/konva#1833]
Hi,

I noticed that I cannot resize Transformer (not Text) after I change the fontSize property. If I make my text bigger with the font size, it's being "cut" due to invalid Text's size. Here is my update style code:

```
    const id = this.selectedText._id;
    const text = this.editor.textLayer.children.find((x) => x._id === id)! as Konva.Text;

    const newFontSize = this.calculateFontSize(options.fontSize!);

    text.setAttrs(options);
    text.fontSize(newFontSize);

    this.editor.transformer?.nodes([text]);
    this.editor.transformer?.forceUpdate();

    setTimeout(() => {
      this.editor.textLayer.draw();
    }, 50);

```

Nothing is null: `text` is an object, `transformer` is an object (there is only one transformer at the moment), `editor` is an object. Everything work but this.

![konva](https://github.com/user-attachments/assets/40e21110-1ab0-4530-9a33-4476005e3d02)

**Comment by michalgrzyska** [comment]
I found one of possible solutions: I am making a deep copy of the text with new fontSize value on init, and replace old text with the new one. But I don't think this is the proper solution.

**Comment by lavrton** [comment]
What konva version do you use? I can't reproduce it with the last version. https://jsbin.com/zagifudoni/1/edit?html,js,output

**Comment by marceloarc** [comment]
this is happening to me in android chrome, in desktop is working fine
