### ISSUE TITLE
Unable to Drag Line When Inside Polygon 

### ISSUE THREAD

**Issue by sangeetha321** [konvajs/konva#1835]
I'm experiencing an issue with my React-Conva components. I have two components: one for drawing lines and another for polygons. The problem occurs when I draw a line first and then a polygon. If the line is inside the polygon, I'm unable to drag the line without first moving the polygon.

Steps to Reproduce:

- Draw a line using the line component.
- Draw a polygon using the polygon component, ensuring the line is inside the polygon.
- Attempt to drag the line.
- Expected Behavior: I should be able to drag the line freely, regardless of its position relative to the polygon.

Actual Behavior: The line cannot be dragged if it's inside the polygon. I must first move the polygon to be able to drag the line.

I am using "react-konva": "^18.2.10"

This issue seems similar to https://github.com/konvajs/konva/issues/238. 
Is this issue resolved in the latest packages?

**Comment by lavrton** [comment]
Make a demo. Probably you need to disable fill part of the polygon: `fillEnabled={false}`
