### ISSUE TITLE
Dragmove delay of Macbook screen

### ISSUE THREAD

**Issue by lk125454242** [konvajs/konva#1839]
hi，I have encountered a problem, please help me take a look. Thank you-all

Dragging on the built-in display of MacBook may cause delay，**but it is very smooth when using an external display.**

I have configured it: 
```
Konva.pixelRatio = 1;
```
The situation has improved somewhat, but it still appears to be delayed by at least 100ms. why?

**Comment by lavrton** [comment]
Please make a small demo. I can't reproduce.
