### ISSUE TITLE
Introducing projects directly into the development environment is problematic

### ISSUE THREAD

**Issue by 2531800823** [konvajs/konva#1840]
I introduce projects directly into the development environment, install vite + swc To compile ts want to use the project directly for debugging, but this error occurs.
![image](https://github.com/user-attachments/assets/62deba16-3a5b-47e7-8be6-db3dd7d339d2)
![image](https://github.com/user-attachments/assets/50ea396a-6bf2-4088-a1e3-32a55462b3ea)

**Comment by forever-2627** [comment]
I think it is good for you to use react-konva.
Or I hope you send me your project and let me debug it.
Thank you

**Comment by 2531800823** [comment]
Thank you for your answer. but I want to debug the source code directly,  So I directly imported ts from the konva repository (without compiling the code). Since vite supports ts, I encountered this problem.

**Comment by forever-2627** [comment]
Is it possible for you to source code.

**Comment by 2531800823** [comment]
https://github.com/2531800823/konva , I use pnpm as the package management tool and added vite. Then I directly run "pnpm dev". It should be able to build ts and then debug. However, it directly reports an error.

**Comment by forever-2627** [comment]
ok, let me check it
