### ISSUE TITLE
Iframe Unable to drag due to outer call

### ISSUE THREAD

**Issue by 948764321** [konvajs/konva#1844]
The project structure is the outer main page + the inner iframe, and the main page introduces konva.js.

When `Konva.Stage` was created on the main page, the elements in iframe were passed into the container, Such as:

![image](https://github.com/user-attachments/assets/e59f66d3-78c0-450b-a26b-30b5990fb7c2)

so the created `Konva.Node` could not be dragged. After investigation, it was because of `mouseup`, `mousemove`... The event is bound to the window.

![image](https://github.com/user-attachments/assets/55acaeb4-b871-43be-8f05-187cfdf6ac49)

My suggestion is to use `Node.ownerDocument` and bind events to the document object at the top of the container.
MDN https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument

**Comment by lavrton** [comment]
konva.js is not designed for such use case. And I don't think it should. Just create all konva objects inside iframe context and render from it. Communication between parent context and child iframe is out of konva scope.
