### ISSUE TITLE
Setting font style (font weight) Konva Text

### ISSUE THREAD

**Issue by TamLa21297** [konvajs/konva#1845]
I'm trying to set font weight for Text by set fontStyle with values [300, 400, 500, 600, 700, 800]
but the result not really good
![image](https://github.com/user-attachments/assets/0f0b7b2f-3703-4ada-aef7-1a5156603014)

It have to be looked difference like this
![image](https://github.com/user-attachments/assets/bc14596c-5a58-4591-a180-c4581cf4fce1)

How to do it?

**Comment by lavrton** [comment]
Please make a demo.
Also make sure font is loaded: https://konvajs.org/docs/sandbox/Custom_Font.html
