### ISSUE TITLE
Arrow pointer is taking extra space

### ISSUE THREAD

**Issue by mahbubabbas** [konvajs/konva#1851]
Arrow pointer is taking extra space. Both the parameters `pointerLength` and `pointerWidth` affect the final length of the arrow. The final arrow length increases a bit based on values of `pointerLength` and `pointerWidth` whereas the final length should never change.

**Comment by nlukyaniuk** [comment]
@lavrton  I'm experiencing the same issue. Here's a demo
https://stackblitz.com/edit/angular-konva-jfpugr?file=src%2Fapp%2Fapp.component.ts

**Comment by lavrton** [comment]
Thanks for the report.
