### ISSUE TITLE
Text bounding box is off

### ISSUE THREAD

**Issue by ozziexsh** [konvajs/konva#1852]
Hello! We are in the process of porting our canvas application to Konva but are running into an issue with the text placement

I've created a sandbox here to compare:

https://codesandbox.io/p/sandbox/6c3wlv

With the raw js canvas api we can write some text and then draw a perfect rectangle around it using the dimensions returned from `ctx.measureText`:

![Screenshot 2024-11-18 at 2 16 57 pm](https://github.com/user-attachments/assets/fc8a35a2-9f44-4af1-8d75-cea11f430d1f)

However with Konva we can't seem to get anything consistent between fonts when drawn at the same coordinates/font size:

![Screenshot 2024-11-18 at 2 17 53 pm](https://github.com/user-attachments/assets/107f93fc-2865-4237-8a44-e30e9f440bab)

I found issue #559 which says setting the `Konva._fixTextRendering = true` flag helps a bit (making it closer to the default context baseline), but still not perfect:

![Screenshot 2024-11-18 at 2 18 56 pm](https://github.com/user-attachments/assets/fe1a5faf-1b59-4789-9e9f-189d4f6ea0ca)

With `.getWidth()` and `.getHeight()` we can get a proper rectangle but there is a ton of extra space:

![Screenshot 2024-11-18 at 3 13 54 pm](https://github.com/user-attachments/assets/52bf8305-a550-4ce6-aabe-1111e9b56f34)

How can we get a perfect outline of the text using Konva? Surely there must be a formula we can undo to offset the text. I've tried playing around with the values being set in `Text.ts` but it seems that it comes down to this translate step here which i'm sure is required for other apis

https://github.com/konvajs/konva/blob/master/src/shapes/Text.ts#L352

Thanks in advance

**Comment by lavrton** [comment]
Bounding boxes of `Konva.Text` is not using text measurements much (only for width in some cases).
For height, Konva uses font size and line height.

So I guess you have to use `ctx.measureText` by yourself to calculate very precise measurements.
