### ISSUE TITLE
Context menu triggers a click event, can I prevent it?

### ISSUE THREAD

**Issue by lzd358194530** [konvajs/konva#1854]
Thank you for submitting an issue!

Please make sure to check current open and closed issues to see if your question has been asked or answered before.
If you have just a question (not a bug or a feature request) it is better to ask it in [Stackoverflow](http://stackoverflow.com/questions/tagged/konvajs).

If you have a bug, please, try to create a reproducible example with jsfiddle (or any similar service).
You can use [this JSBIN](https://jsbin.com/tekehizuta/1/edit?html,js,output) as a template.

**Comment by lavrton** [comment]
Demo?

**Comment by lzd358194530** [comment]
https://konvajs.org/docs/events/Pointer_Events.html

**Comment by lzd358194530** [comment]
https://konvajs.org/docs/events/Pointer_Events.html
Click on the red circle on this page. Clicking the right and left mouse buttons will trigger the event. If I only want the left button to trigger and the right button not to trigger, can this be done?

**Comment by lavrton** [comment]
You can just filter by `evt.evt.button`
```js
circle.on('pointerdown', function (evt) {
    if (evt.evt.button === 0) { // 0 indicates the left mouse button
        writeMessage('pointerdown circle');
    }
});
```

**Comment by lzd358194530** [comment]
ok think you i will try
