### ISSUE TITLE
Line Hops or Jumps?

### ISSUE THREAD

**Issue by imdaveho** [konvajs/konva#1856]
I am trying to implement something called a line hop or line jump when two lines/arrows intersect: 
https://community.miro.com/ideas/connection-lines-add-a-jump-for-lines-that-cross-8223

I looked around existing issues, docs, demos, and searched but could not find anything that specifically made this a straightforward process. Is the only way to achieve this to render 3 shapes? 1 arrow, 1 line, and 1 curve and somehow group them together so that they can be draggable and movable as "one" line?

Or is it more like 1 path + an arrow shape associated with the endpoint of the path? Is there no built-ins to "merge" lines into one or provide a path with an endpoint shape?

**Comment by lavrton** [comment]
There are many ways. You can put arrow + arc + arrow into a draggable group.
Or you can draw just one `Konva.Path`.
In any case, you may have to do math homework to calculate all the coordinates by yourself.

**Comment by imdaveho** [comment]
Thanks for the suggestions. I had little time to close the issue myself.
