### ISSUE TITLE
Use Konva in webworker

### ISSUE THREAD

**Issue by kudlajz** [konvajs/konva#186]
Is it possible to use Konva in browser's web worker? I've ran into issue, because per documentation, the `window` and `document` object is not available in web worker itself, thus Konva thinks it is being run in nodejs environment and tries to include `jsdom`, `fs` and such.

I am using webpack's worker loader as such:

    import RenderWorker from 'worker!./render/worker

but it fails on

    Uncaught TypeError: jsdom is not a function

When I expose the `jsdom` in worker, before I import the Konva, it fails on requiring node's `fs`.

We have a use case, where we render images on canvas in browser, and we'd like to move this functionality into a web worker to prevent blocking UI.

**Comment by lavrton** [comment]
@kudlajz but `<canvas>` element is not available in a web worker. So it is not possible to render images here.
To prevent UI blocking you can try to split huge tasks into small chunks.

**Comment by kudlajz** [comment]
@lavrton Is there a way to pass `document` or `window` into a web worker? And could that work?

**Comment by lavrton** [comment]
As I know - No. This is how a web worker works - in isolated scope. You can pass only simple objects into it.

**Comment by greengiraffe** [comment]
Now that there is [Offscreen Canvas](https://developers.google.com/web/updates/2018/08/offscreen-canvas) this issue could be reopened.

**Comment by lavrton** [comment]
@greengiraffe you are right!

**Comment by rndD** [comment]
related https://github.com/konvajs/konva/issues/446

**Comment by lavrton** [comment]
I have a progress on this issue. Here is a demo: https://konvajs.org/docs/sandbox/Web_Worker.html

For any feedback please use this thread: https://github.com/konvajs/konva/issues/446
