### ISSUE TITLE
Fix Memory issue: Only Batch Draw when it's visible again.

### ISSUE THREAD

**Issue by railsonsousa106** [konvajs/konva#1860]
https://github.com/konvajs/konva/blob/4009e6bd11334d570cc645bd8087363d52dd46c5/src/Stage.ts#L974-L980

Why we need change here:
Because it'll cause memory issue.

When the app is in active tab, app uses about 1 GB memory:
<img width="428" alt="Screenshot 2024-12-04 at 12 20 05 PM" src="https://github.com/user-attachments/assets/b2b62dc6-f75a-4c48-b782-ae01cedeac77">

But when it's in inactive tab, app uses about 1.9 GB memory:
<img width="428" alt="Screenshot 2024-12-04 at 12 21 20 PM" src="https://github.com/user-attachments/assets/eae433df-4e5e-4e5f-9fc4-c0faa7d1959a">

Because it tries to batchDraw on visibilitychange, it uses double memory at that time, but it doesn't really draw in inactive tab. It just takes memory.
So we just need to make it batchDraw when it's visible again.

The code should look like this:
```
if (Konva.isBrowser) {
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible') {
      stages.forEach((stage) => {
        stage.batchDraw();
      });
    }
  });
}
```

**Comment by lavrton** [comment]
The draw should not increase memory at all. Did you try to debug and profile the memory to see what consumes the memory?

**Comment by railsonsousa106** [comment]
Profiling Memory?
Well, just tried and it shows 60MB usage there.
But, when I watch memory usage by Chrome Task Manager, it shows 1 GB.

**Comment by railsonsousa106** [comment]
Anyway, As I showed on the above screenshots, the memory is increasing with that visibilitychange.
I tried to debug this whole day, checking code line by line, and reached this.
And, it makes sense to batchDraw only when it's visible, doesn't it?

**Comment by railsonsousa106** [comment]
Sorry, Looks like it's not the problem with this.
