### ISSUE TITLE
Dashes on ellipses may render incorrectly on Firefox

### ISSUE THREAD

**Issue by joelspadin** [konvajs/konva#1864]
When enabling stroke dashes on ellipses, very specific values of radiusX, radiusY, and strokeWidth cause the dashes to render incorrectly on Firefox v132.0 on Windows. This does not occur on Chromium-based browsers. I am unsure whether this is a bug in Konva or Firefox. 

If I draw an ellipse with `radiusX == radiusY` and `strokeWidth = 1`, then it draws a very thick, solid arc instead of a dashed outline. Adjusting it so it is slightly elliptical makes it render correctly. Increasing the `strokeWidth` also makes it render correctly, but even more strangely, doing this causes any further ellipses with the original parameters to render correctly again.

https://jsbin.com/zidilowiyu/1/edit?js,output

On Firefox, I see this:
![image](https://github.com/user-attachments/assets/60014ddb-0448-4c78-b2bf-198b809d0181)

On Edge, it looks like this:
![image](https://github.com/user-attachments/assets/e72e799e-5719-43b8-9678-9c0c5c65f11f)

**Comment by lavrton** [comment]
I am not sure if we should do much here from Konva side. Looks like a firefox bug.

**Comment by joelspadin** [comment]
Can you point me to the part of Konva that handles this so I can file a bug with Firefox (or look for existing bug reports)?

**Comment by lavrton** [comment]
This is pure js sample similar to konva code:

```js
// Select the canvas and set up its dimensions
const canvas = document.getElementById("container");
canvas.width = window.innerWidth;
canvas.height = window.innerHeight;

// Get the 2D rendering context
const ctx = canvas.getContext("2d");

// Draw an ellipse with a dashed stroke
function drawEllipse(x, y, radius, strokeColor = "black", lineWidth = 1, dashArray = [5, 5]) {
  ctx.save(); // Save the context state

  // Move to the center of the ellipse
  ctx.translate(x, y);

  // Set stroke style
  ctx.strokeStyle = strokeColor;
  ctx.lineWidth = lineWidth;
  ctx.setLineDash(dashArray);

  // Draw a circle (which becomes an ellipse due to scaling)
  ctx.beginPath();
  ctx.arc(0, 0, radius, 0, Math.PI * 2, false);
  ctx.closePath();

  // Apply stroke
  ctx.stroke();

  ctx.restore(); // Restore the context to its original state
}

// Call the function to draw the ellipse
drawEllipse(100, 100, 21, "black", 1, [5, 5]);
```

https://jsbin.com/levibaseyi/2/edit?js,output

**Comment by joelspadin** [comment]
Thanks. I can confirm that code also shows the issue on Firefox.

**Comment by joelspadin** [comment]
Firefox bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1937929

**Comment by joelspadin** [comment]
Confirmed that this is a Firefox bug.
