### ISSUE TITLE
Missing empty string in .d.ts parameters for non-string types in attributes

### ISSUE THREAD

**Issue by BalagePMI** [konvajs/konva#1866]
### **The problem**

The .d.ts (typescript mapper) for Shape and many other data types are not supporting string (or at least empty string constant) as input.

For example, the following declaration 

```ts
 fillPatternImage: GetSet<HTMLImageElement | HTMLCanvasElement, this>;
 ```
 
 only allows Image and Canvas types as input.
Clearing a pattern fill could be by passing the `fillPatternImage` an empty string (it could be undefined, but it may be some design decision), which is marked as uncompatible value. So using this one hase to add a `@ts-ignore` which is an antipattern and also may generates a warning itself in strict mode.

The same goes on any other field, so the code is polluted with `@ts-ignore`:

```ts
 // @ts-ignore
 this._node.fill('')
 // @ts-ignore
 this._node.fillPatternImage('')
 // @ts-ignore
 this._node.fillLinearGradientColorStops('')
 // @ts-ignore
 this._node.fillRadialGradientColorStops('')
```

### **The suggestion**

The values which receives non string values should be extended with empty string pattern as input.

```ts
 fillPatternImage: GetSet<HTMLImageElement | HTMLCanvasElement | '', this>;
 ```

This solution has only impact on the `.d.ts` files.
Accepting `undefined` and/or `null` may be even cleaner. However, it has a great impact on the base JS code.

**Comment by lavrton** [comment]
I dont think empty string is a good value. While it is working in runtime because it is falsy, I think the more consistent value should be `null`
