### ISSUE TITLE
Trigger child xChange on parent move

### ISSUE THREAD

**Issue by mrasoahaingo** [konvajs/konva#188]
Hi,

I need to listen for child position changes when his parent position changes.
Actually dragging itself triggers correctly the on('xChange') event with old/new values.

```
node.on('xChange', function(evt) {
  var oldVal = evt.oldVal;
  var newVal = evt.newVal;
});
```

Moving his parent also changes x position without triggering the event :(
How can I deal with it? 
Thanks :)

**Comment by lavrton** [comment]
@mrasoahaingo dragging parent node will not change `x` position (relative position) of a child node. But it will change absolute position. `xChange` and `yChange` only for relative positions.

You can listen `xChange` of parent and apply your operations here, right?

**Comment by mrasoahaingo** [comment]
@lavrton it's confusing because, x/y position of a child is relative to the parent. But, the drag and drop bound function return the absolute x/y. So, if I want to store the x/y into a db I must take the parent pos into account like this:

with react-konva:

```
<Group x={100} y={100}>
    <Circle x={50} y={50} dragBoundFunc={dragBound}/>
</Group>

dragBound = ({ x, y }) => console.log(x, y) 
```

This will print 150, 150. So, before saving into db I must remove the 100,100  offset parent position :(

**Comment by lavrton** [comment]
@mrasoahaingo this is just a special behavior of `dragBoundFunc`. I think it is better to avoid it for side effects. You can use "dragmove" event.

```
<Group x={100} y={100}>
    <Circle x={50} y={50} onDragMove={handleDragMove}/>
</Group>

handleDragMove = (e) => {
    db.save(e.target.position());
}
``

**Comment by mrasoahaingo** [comment]
@lavrton oh okay I didn't notice the target.position()
Thanks!

**Comment by daaain** [comment]
@lavrton would you mind documenting this quirk of `dragBoundFunc`? Also, what's the reason for this behaviour? It took me ages to realise that it's not honouring the layer position and was just about to write a bug report, but found this issue...
