### ISSUE TITLE
Incorrect type for Stage.add in Typescript declaration file, should support multiple layer arguments

### ISSUE THREAD

**Issue by sgronblo** [konvajs/konva#195]
Judging by the docs for Stage.add on https://konvajs.github.io/api/Konva.Stage.html it seems that it should support adding multiple layers at once, as variadic arguments or "Rest parameters" https://www.typescriptlang.org/docs/handbook/functions.html

I think the fix should be as simple as changing:
`add(layer: Layer): Stage;`
`add(...layers: Layer[]): Stage;`

**Comment by lavrton** [comment]
You are right. Are you interested in Pull Request?
