### ISSUE TITLE
Performance is more like SVG not CANVAS

### ISSUE THREAD

**Issue by aeauseth** [konvajs/konva#196]
I was expecting Canvas like performance with SVG like elements.  However the performance is more like standard SVG rather than Canvas.  I created three jsfiddle examples.  One for [KONVA](https://jsfiddle.net/aeauseth/ngdvhe8s/), one for [CANVAS](https://jsfiddle.net/aeauseth/t5mjhmhw/), and one for [SVG](https://jsfiddle.net/aeauseth/4ydfe6zn/).  Notice that Canvas is about 8x faster.  I realize this is a naive test, however my experimental results with pan/zooming 1000+ elements with KONVA seem to match my SVG based experiments.

**Comment by lavrton** [comment]
@aeauseth and?

**Comment by aeauseth** [comment]
Why use KONVA instead of SVG (given their rendering performance seem roughly equal)?  I suppose there are platforms that don't support SVG, but for traditional computers there doesn't seem to be a compelling reason to use KONVA.  I'd think that KONVAs rendering performance should be much faster than SVG.  Am I missing something?  If I'm way off base here, just delete my issue and I'll move on.

**Comment by lavrton** [comment]
It depends on a use case. SVG can be even faster then a native canvas. It depends on what you want to draw, how you want to draw and how you will interact with drawn objects.

For example, It will be better to use canvas (with or without Konva)  if you need some pixel manipulations, filters, or better "toImage" exporting.
