### ISSUE TITLE
Arrow heads do not point in the correct direction if tension != 0

### ISSUE THREAD

**Issue by pxmath** [konvajs/konva#197]
Example:

`var arrow = new Konva.Arrow({points: [0, 0, 50, 50, 100, 20], stroke: 'black',`
`fill: 'black', tension: 1, pointerLength: 12, pointerWidth: 8});`

The arrow head does not point in the correct direction.   Arrow heads are correct only if tension = 0.

**Comment by lavrton** [comment]
Partially fixed.
