### ISSUE TITLE
touchmove event word weird on "wechat" app browser 

### ISSUE THREAD

**Issue by littlee** [konvajs/konva#199]
I tried the Multi-touch Scale Shape Demo (http://konvajs.github.io/docs/sandbox/Multi-touch_Scale_Shape.html) on iOS safari, it works fine.

But on the wechat app built-in browser, the touchmove event work badly.

the object does not move with the finger touching on screen, it only changes its position when the finger leave the screen (touchend)

WeChat App https://itunes.apple.com/us/app/wechat/id414478124?mt=8
this app is so popular in our country, people use it a lot, I hope konva.js can work with it.

**Comment by lavrton** [comment]
@littlee I will test as I get a chance.

**Comment by lavrton** [comment]
I will close the issue. I guess it works ok now.
