### ISSUE TITLE
Group width() and height()

### ISSUE THREAD

**Issue by speedy32** [konvajs/konva#2]
Hi 

Shouldn't this functions calculate width and height? Is there any function which will calculate width and height of grouped objects or layer?

**Comment by lavrton** [comment]
Currently there is no such function. You have to do this manually. Оne day may appear.

**Comment by jovination** [comment]
Here is kind of a raw example of how I achieved this if it helps

```javascript
    _configureOutput: function(obj){
            var groupObj = {},
                currentWidth = obj.getWidth(),
                currentHeight = obj.getHeight();

            if (!this.proportions()) {
                //no restrictions on sizing, set width/height to the next available value
                groupObj.width      = this.width()      || currentWidth;
                groupObj.height     = this.height()     || currentHeight;
            } else {
                //TODO: add max width/height functionality

                var ratio = currentWidth / currentHeight;

                if (this.proportions() == 'height') {
                    if (this.height()) {
                        this.width(Math.floor(this.height() * ratio));
                    }
                } else {
                    if (this.width()) {
                        this.height(Math.floor(this.width() * ratio));
                    }
                }

                groupObj.width      = this.width();
                groupObj.height     = this.height();
            }
            if (!this.output) {
                switch (this.outputType()) {
                    case 'Layer':
                        //this type does not support width/height so remove it to supress warning
                        delete groupObj.width;
                        delete groupObj.height;
                        this.output = new Kinetic.Layer(groupObj);
                        break;
                    case 'Group':
                        this.output = new Kinetic.Group(groupObj);
                        break;
                    case 'FastLayer':
                    default:
                        //this type does not support width/height so remove it to supress warning
                        delete groupObj.width;
                        delete groupObj.height;
                        this.output = new Kinetic.FastLayer(groupObj);
                        break;
                }
            } else {
                switch (this.outputType()) {
                    case 'FastLayer':
                        //this type does not support width/height so remove it to supress warning
                        delete groupObj.width;
                        delete groupObj.height;
                        break;
                    case 'Layer':
                        //this type does not support width/height so remove it to supress warning
                        delete groupObj.width;
                        delete groupObj.height;
                        break;
                }       
                this.output.destroyChildren();
                this.output.setAttrs(groupObj);
            }
     }    
```

proportions are width or height, to calculate a ratio if needed, the last part of the function is just based on the app it is in since it can output any kind of grouping and if its not a group, no need for it. Yes this can be better but its still only a functional concept.

the obj in this function refers to the first (or any) object within the group to take the width and height of that as the "base", so with many objects with different sizes that could get very hard.

Lets say one is 200x500 and another is 500x200 then the width/height is 500x500 or at least should be, but to do that you have to look at every object, or at least track them as they are added.

I feel this always should be a manual process as with the code above, it assumes they are all the same size so looking at the first one only is good, if it gets super technical its going to impact performance.

Just my opinion anyway ^^ Love KineticJS :D

**Comment by speedy32** [comment]
"Lets say one is 200x500 and another is 500x200 then the width/height is 500x500 or at least should be, but to do that you have to look at every object, or at least track them as they are added."

It depends on position of second object (x, y)

**Comment by jovination** [comment]
lol so even more complicated, anyway did not mean saying that as "this is the way" just that with sizing in general you need to keep track of all the children, where in most applications anyway you can assume what the sizing might be and plan for it. If it is automatic those calculations might need to cache some objects like images to be able to get an accurate size. Although overall its not to bad, when you have to do that anytime you add/manipulate an object it could get pretty heavy.

Anyway, that is only my opinion on it, if its added and does not negatively impact performance it would be an awesome feature. One idea might be to do a similar system to filters, like 
`stage.calc([Kinetic.Calc.Size])` and it would make the width/height available to all nodes at all times (layer too, even if it has no real need for it).

**Comment by lavrton** [comment]
Now every `Konva.Node` have new method `getClientRect()`. It returns `{x,y,width,height}` relative to parent container. I made this method for caching purpose, but I think it can be used as stand alone method. You can use it for groups.

**Comment by hatim523** [comment]
> Now every `Konva.Node` have new method `getClientRect()`. It returns `{x,y,width,height}` relative to parent container. I made this method for caching purpose, but I think it can be used as stand alone method. You can use it for groups.

I still got `{x: 0, y: 0, width: 0, height: 0}` for Group node.

Workaround:
Attach transformer to group node, and then use `transformer.getClientRect()` to get the group coordinates and width and height.

**Comment by lavrton** [comment]
@hatim523 demo?
