### ISSUE TITLE
Load handling

### ISSUE THREAD

**Issue by jovination** [konvajs/konva#20]
I don't think there should be any dedicated way to load images or other assets in this library, because so many other stand alone libraries do it so well. However when handling shapes (images mainly) it gets rather strange to constantly make sure that the asset is already loaded before drawing the shape.

So rather then making an area for loading, an area that can tie into other libraries to handle it, but sync the load into konva for loading, so the callbacks are carried over, and the shape will ensure it has loaded beforehand, or at whatever point deemed by the person using it.

I have added something similar into my own library that uses kinetic (soon to be transferred to konva) and it works pretty well to allow assets to be added, without the need to manually ensure the assets have loaded before the draw.

So something like this.

```javascript
var stage = new Konva.Stage(options);
var layer = new Konva.Layer();

var image = new Konva.Image({
   image: url //if it is already an image object it can assume its loaded
});

layer.add(image);
layer.on('ready',function(){
   stage.add(layer);
});
```

This is of course the result without the messing around with the "load" object to handle and connect to the external library but the idea is there.

so here is an example of that

```javascript
var options = {
   loader: new Konva.Loader({
      add: function(url){
         someloader.add(url);
      },
     progress: function(callback){
         someloader.on('asset',callback);
     },
     complete: function(callback){
        someloader.on('complete',callback);
     }
   });
};
```

a very rough example but it should paint the picture, set up the options for the stage and then any assets later will automatically be managed without the need for extra callbacks, also allows the already powerful event system to be more powerful. It would not remove the ability to do it as it is currently, only add an extra option. It could even cache images that are the same so they never have to fire a load event twice and such.

Anyway an idea that I have been wishing this library had as my use of it uses a lot of images. I would like to see if anyone else has an opinion on it before i start trying to do a pull request for it. the above method is far from what the end product will be though, just the original concept as my own implentation uses PreloadJS forcibly.

**Comment by lavrton** [comment]
In this case user may have unexpected results for actions where loaded image is required. For example filtering:

```javascript
var image = new Konva.Image({
   image: url
});
image.cache();
image.filters(filtersList);
layer.add(image);
layer.draw();
```

We can't apply filter before loading. To avoid this we can create special "stack of actions" to apply after loading. But it is too complicated to implement into library.

**Comment by jovination** [comment]
Yes, in what I did i had to deal with that as well, the method was to apply the filters anytime the image was "loaded" and fake a load if it is being loaded from cache. Also if using the load it is likely the user cannot just "draw" it would need to run on complete. so like this

```javascript
var image = new Konva.Image({
   image: url
});
image.on('ready', function(){
   image.cache();
   image.filters(filtersList);
   layer.add(image);
   layer.draw();
});

```
*Note: My examples right now are only concept, I don't intend to say "this is how it will work"* 

It would definitely change the way to think about some objects, but might also streamline the process to use images, making them less different then regular shapes. Though this is only true if the application uses lots of images, if its 1 or 2, its likely easier to just manage the loading yourself.

The reason for this is there is a delay on load events if applied again rather then keeping track of the original image object, an easy thing to miss. If the library handles this for you it will only make Konva easier to use.

But this is only my idea for an enhancement. I feel it could be a useful addition, and one that will improve performance when dealing with images. If I do a pull request for this, I am going to avoid touching functions like cache, or draw. But I am still only at the concept stage. I do have ways to do it, but to make sure it does not integrate deep is my current objective, it should stay optional and configurable, without much adding to the code base.

**Comment by lavrton** [comment]
I like `fabric.js` way:
```javascript
Konva.Image.fromURL(imageURL, function(image){
  // image is Konva.Image instance
  layer.add(image);
  image.cache();
  image.filters(filtersList);
  layer.draw();
});
```

**Comment by jovination** [comment]
That is nice I will admit.

However an issue I see with that is that it sort of forces you to do the images individually rather then combine them together. Although there are ways around that but its outside the library.

I have been playing with the concept a bit, here is what I am doing (first idea anyway, doubt its going to be as good as I hope).

I am adding a new function to `Konva.Node` called `load` this function loops through all children (if a container) or just that node to try to find a `src` parameter (not image). This function passes all the `src` elements it finds to a new class called `Konva.Loader` and will load all the elements, then apply them to the original image object in the `image` parameter. The loader will allow events for individual images loads and complete, allowing you to track progress as well. The progress elements pass the image object right as it is made, allowing caching/filtering and then the complete to add to the stage/draw.

The problems I see is in creating the image object without the image available, I have not dived deep enough to see what will happen, but I assume there is at least some parsing when the object is originally created. Also to make full use of containers, the image needs to be added to the layer first without the image parameter, and then the layer itself handles the load.

**Comment by pronebird** [comment]
I tackled this through a separate preloader object because it's not only images you need but also sounds, and what if you want to display an overall progress? It becomes clear that layers and shapes have nothing to do with that and you need better abstractions.

**Comment by pronebird** [comment]
@lavrton not bad for the first step! Defo will make it easier to work with Konva in basic situations.
