### ISSUE TITLE
Konva not defined | Cannot read webkitBackingStorePixelRatio of null

### ISSUE THREAD

**Issue by ZephD** [konvajs/konva#200]
I'm having difficulty running Konva (via react-konva) with a Mocha test.

When using Konva v1.2.2, i got the error:
```
*/node_modules/konva/konva.js:284
    Konva.Collection = function() {
    ^
ReferenceError: Konva is not defined
```
This is a known issue in #178 and apparently was fixed.

If I update Konva to v1.3.0 i now get the following error:
```
*/node_modules/konva/konva.js:1307
            backingStoreRatio = context.webkitBackingStorePixelRatio
                                       ^
TypeError: Cannot read property 'webkitBackingStorePixelRatio' of null
```

Any help with this one?

I'm using:
jsdom v9.5.0
npm v3.10.3
node v6.4.0

**Comment by ZephD** [comment]
Probably due to this:

https://github.com/konvajs/konva#5-nodejs

**Comment by maxhudson** [comment]
This was useful for me on unix: 
`brew install pkg-config cairo libpng jpeg giflib`
`npm install canvas --save`

**Comment by alireza-bonab** [comment]
This worked for me:
[https://stackoverflow.com/a/53297476/2336607](https://stackoverflow.com/a/53297476/2336607)

**Comment by tan-i-ham** [comment]
> npm install canvas --save

This still work! Thank!
Is anyone know why it work?
