### ISSUE TITLE
Zoom/Scale anchor point

### ISSUE THREAD

**Issue by rob-mccann** [konvajs/konva#205]
Hello - 

I have a draggable stage which has a scale property. I've hooked the scale property to change based on the mousewheel event and it's looking good.

The issue I'm facing is that the canvas is scaling from (0, 0) rather than the mouse pointer location. Do you have any examples/pointers for altering the behaviour?

The same applies to the below example, where the anchor point is (0,0) rather than the midpoint between the two initial touch events.
http://konvajs.github.io/docs/sandbox/Multi-touch_Scale_Stage.html

**Comment by lavrton** [comment]
I don't have examples right now.
But you just need to move your stage on zoom.

**Comment by rob-mccann** [comment]
Do you know how Id move the stage on zoom? I've been trying a few things with no luck:

I've tried moving the layer left and up by the scaled mouse (x,y), performing the scale and moving back again.

**Comment by lavrton** [comment]
@rob-mccann I hope this demo will give you a basic idea. http://konvajs.github.io/docs/sandbox/Zooming_Relative_To_Pointer.html

**Comment by rob-mccann** [comment]
@lavrton absolutely perfect!
