### ISSUE TITLE
Layer.get('Shape').destroy() memory leak

### ISSUE THREAD

**Issue by jaymainal** [konvajs/konva#207]
I had a Layer with some Rectangles and Circles.

I will update the layer periodically.
(Remove all Rectangles and Circles and then add them).
(Due to these Rectangles and Circles maybe different)

I use `Layer.get('Rect').remove() or Layer.get('Rect').destroy()`

But it seems not really release even wait a long time.

Please reference below pictures.

[img1](http://imgur.com/a/CBW0Q)

[img2](http://imgur.com/a/exgrB)

And what is the Konva.Transform, it  also increase by time. 

Finally cause memory leak.

Thanks your help

**Comment by lavrton** [comment]
I guess you just don't need to use `remove()` method.
Take a look here: http://konvajs.github.io/docs/performance/Avoid_Memory_Leaks.html
Reopen if you still have issues.

**Comment by jaymainal** [comment]
Thanks, u are right, directly use destroy works well
