### ISSUE TITLE
Typescript definitions for Konva Events

### ISSUE THREAD

**Issue by cglantschnig** [konvajs/konva#209]
Are there any plans to make some Konva Events in Typescript?

Currently if you expect an Event in a parameter you need to type it as any. I could imagine something like the code below. What do you think about that?

    namespace Event {

        interface Mouse {
            type: "mousedown" | "mouseup"     | "mouseover"   |
                  "mouseout"  | "mouseenter"  | "mouseleave"  |
                  "mousemove";
            target: Node;
            currentTarget: Node;
            evt: MouseEvent;
        }
        interface MouseWheel {
            type: "mousewheel",
            target: Node,
            currentTarget: Node;
            evt: MouseWheelEvent;
        }

    }

**Comment by lavrton** [comment]
Looks good. Personally, I am not interested in better typescript definitions (just because I don't use typescript right now). But I am happy to see pull request.

**Comment by emlynmac** [comment]
I'm in the process of trying to get konva into a typescript-react app. Maybe in a month or so I'll have a PR ready.

**Comment by lavrton** [comment]
Resolved
