### ISSUE TITLE
Should call .draw() on the canvas in stage.toDataUrl() before calling generating base64

### ISSUE THREAD

**Issue by matt-easyagile** [konvajs/konva#211]
I had an issue in which the output of stage.toDataUrl() was a blank image if the stage had been resized after initial render (eg. stage.height(newY)). Similarly, even if the stage was given a fixed size when instantiated, but any objects on the stage that had been resized, the resized objects were not rendered by .toDataUrl().

I fixed this issue by forcing a redraw of the stage (eg. stage.draw()) right before calling stage.toDataUrl(). As a suggestion, this problem may be avoided altogether by calling .draw() on the canvas inside of the .toDataUrl() method on the stage object.

**Comment by lavrton** [comment]
From my point of view, forcing to redraw is totally good solution and we don't need any side effects in `toDataUrl()`
