### ISSUE TITLE
Add support for lineDashOffset

### ISSUE THREAD

**Issue by royra** [konvajs/konva#212]
The [lineDashOffset](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineDashOffset) property is not supported in Konva. The native canvas API includes it in all the major browsers (desktop and mobile). It's quite useful to create "marching ants" animations.

IIUC it looks like adding the support is not a huge task for anyone familiar with the code.

TIA!

**Comment by royra** [comment]
@lavrton Just removed a bunch of code that manually switches the dash according to the offset. Thanks so much!

**Comment by lavrton** [comment]
All thanks to @leMaik :)
