### ISSUE TITLE
'touchstart' sometimes can't get right shape

### ISSUE THREAD

**Issue by ArcRain** [konvajs/konva#217]
I tested a simple page with my iPad mini2 (iOS version: 10.2.1) and iPhone6 Plus (iOS version: 10.2.1). I added three images into one layer. Then I tried to drag images. Sometimes I can dragged all of them. Sometimes I can drag only one or two. The two cases occurred randomly.

I tried to debug sources and found the color key maybe be the problem.
When I touched a image and the event 'touchstart' is triggered, the 'getIntersection' return 'null'. It can't be matched with shapes' colorKey sometimes.

How to resolve this issue?  Thanks.

<img width="666" alt="issue2" src="https://cloud.githubusercontent.com/assets/5145020/24342658/bc8af802-12f4-11e7-9bce-1675690d3ff5.png">
<img width="733" alt="issue" src="https://cloud.githubusercontent.com/assets/5145020/24342662/c86d6af6-12f4-11e7-9e3d-cfc5521fbf9b.png">

**Comment by lavrton** [comment]
take a look here: https://github.com/konvajs/konva/issues/187
The issue is no fixed yet. But you can create a simple workaround.

**Comment by ArcRain** [comment]
Thanks a lot~I'll use the temporary method to fix my problem.
