### ISSUE TITLE
Nested Grouping in konva

### ISSUE THREAD

**Issue by vinupdlm** [konvajs/konva#218]
HI, How to make nested group dynamically in Konva.

I want 7 nested group with respect shapes.

Please help me.

**Comment by lavrton** [comment]
@vinupdlm your question is unclear. What is your problem? Create a group and add it inside another group.

**Comment by vinupdlm** [comment]
Yes @lavrton, My Jason is like this:

[
  {
    "GCRelevent": false,
    "Number": "2",
    "Parent": "-1",
    "Width": "20.0",
    "Height": "26.0",
    "PosX": "0",
    "PosY": "0",
    "Description": "PANELBOARD P1",
    "Movable": "false",
    "Usage": "PANELBOARD",
    "Orientation": "HORIZONTAL",
    "CircuitType": "BY POLES",
    "ContinuousNumbering": "TRUE",
    "Type": "TYZ:PANELBOARD",
    "instanceID": "1"
  },
  {
    "GCRelevent": false,
    "Number": "3",
    "Parent": "2",
    "Width": "",
    "Height": "",
    "PosX": "0.0",
    "PosY": "0.0",
    "Description": "",
    "Type": "TYZ:A7J_WORKBENCH",
    "instanceID": "2"
  },
  {
    "GCRelevent": false,
    "Number": "7",
    "Parent": "2",
    "Width": "20.0",
    "Height": "26.0",
    "PosX": "0.0",
    "PosY": "0.0",
    "Description": "SECTION",
    "Movable": "false",
    "Usage": "",
    "Type": "TYZ:PB_SECTION",
    "instanceID": "4"
  },
  {
    "GCRelevent": false,
    "Number": "8",
    "Parent": "7",
    "Width": "20.0",
    "Height": "26.0",
    "PosX": "0.0",
    "PosY": "0.0",
    "Description": "INTERIOR - P1",
    "Movable": "false",
    "Type": "TYZ:PB_INTERIOR",
    "instanceID": "5"
  },
  {
    "GCRelevent": false,
    "Number": "9",
    "Parent": "8",
    "Width": "18.5",
    "Height": "10.75",
    "PosX": "0.75",
    "PosY": "14.5",
    "Description": "MAIN AREA",
    "Movable": "false",
    "Type": "TYZ:PB_MAIN_AREA",
    "instanceID": "6"
  },
  {
    "GCRelevent": false,
    "Number": "10",
    "Parent": "9",
    "Width": "5.0",
    "Height": "4.0",
    "PosX": "6.75",
    "PosY": "3.38",
    "Description": "125A MLO/Section-1",
    "Movable": "false",
    "Usage": "MAIN",
    "Poles": null,
    "Type": "TYZ:PB_MAINS",
    "instanceID": "7",
    "deviceType": "MLO"
  },
  {
    "GCRelevent": false,
    "Number": "11",
    "Parent": "8",
    "Width": "18.5",
    "Height": "9.0",
    "PosX": "0.75",
    "PosY": "5.5",
    "Description": "UNIT SPACE AREA",
    "Movable": "false",
    "Type": "TYZ:PB_USP_AREA",
    "instanceID": "8",
    "gridXL": "0.75",
    "gridLength": "9.0"
  },
  {
    "GCRelevent": false,
    "Number": "12",
    "Parent": "11",
    "Width": "18.5",
    "Height": "9.0",
    "PosX": "0.0",
    "PosY": "0.0",
    "Description": "BLBQD_KIT",
    "Movable": "false",
    "Usage": "BRANCH",
    "Type": "TYZ:PB_KIT",
    "instanceID": "9",
    "gridXL": "3.76",
    "gridXR": "10.25",
    "gridLength": "9.0"
  },
  {
    "GCRelevent": false,
    "Number": "13",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "3.76",
    "PosY": "8.0",
    "Description": "15 A/1 - BL ",
    "Movable": "true",
    "Usage": "BRANCH",
    "Poles": 1,
    "Type": "TYZ:PB_VL_MCCB",
    "instanceID": "10",
    "deviceType": "BL"
  },
  {
    "GCRelevent": false,
    "Number": "14",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "10.25",
    "PosY": "8.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "11",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "15",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "3.76",
    "PosY": "7.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "12",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "16",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "10.25",
    "PosY": "7.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "13",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "17",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "3.76",
    "PosY": "6.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "14",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "18",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "10.25",
    "PosY": "6.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "15",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "19",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "3.76",
    "PosY": "5.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "16",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "20",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "10.25",
    "PosY": "5.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "17",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "21",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "3.76",
    "PosY": "4.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "18",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "22",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "10.25",
    "PosY": "4.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "19",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "23",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "3.76",
    "PosY": "3.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "20",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "24",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "10.25",
    "PosY": "3.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "21",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "25",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "3.76",
    "PosY": "2.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "22",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "26",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "10.25",
    "PosY": "2.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "23",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "27",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "3.76",
    "PosY": "1.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "24",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "28",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "10.25",
    "PosY": "1.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "25",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "29",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "3.76",
    "PosY": "0.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "26",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "30",
    "Parent": "12",
    "Width": "4.49",
    "Height": "1.0",
    "PosX": "10.25",
    "PosY": "0.0",
    "Description": "B- PROV",
    "Movable": "true",
    "Poles": 1,
    "Type": "TYZ:PB_SPACE",
    "instanceID": "27",
    "deviceType": "B-PROV"
  },
  {
    "GCRelevent": false,
    "Number": "31",
    "Parent": "8",
    "Width": "18.5",
    "Height": "4.75",
    "PosX": "0.75",
    "PosY": "0.75",
    "Description": "SUB FEED AREA",
    "Movable": "false",
    "Type": "TYZ:PB_SFD_AREA",
    "instanceID": "28"
  },
  {
    "GCRelevent": false,
    "Number": "32",
    "Parent": "7",
    "Description": "B26",
    "Usage": "ENCLOSURE",
    "Type": "TYZ:PB_ENCLOSURE",
    "instanceID": "29"
  },
  {
    "GCRelevent": false,
    "Number": "33",
    "Parent": "7",
    "Description": "S26B",
    "Usage": "FRONT",
    "Type": "TYZ:PB_FRONT",
    "instanceID": "30"
  }
]

All item has parent child relation. 
for example. Second Item has property called Parent(Parent: 2). which means it is the child of first item(Number:2). So it has to come inside first item.
I wanted to create as group and append first and second items into it

**Comment by lavrton** [comment]
@vinupdlm what did you try?
