### ISSUE TITLE
Setting fonts does not work in cached nodes

### ISSUE THREAD

**Issue by joachimboggild** [konvajs/konva#219]
I have made an application with Konva, using a lot of text nodes.

However, it is going to be running on some fairly low-end hardware, and I need to improve performance. 

I have tried using node.cache() on a lot of the parts of the system, and that greatly improves performance, however my custom fonts do not work any more.

Any tips for using custom fonts inside a cached node?

**Comment by lavrton** [comment]
@joachimboggild I think it should work just fine. I guess you just need to recache your text when font is loaded or when you set new font to a text.

**Comment by joachimboggild** [comment]
Great :-) How do I recache? Do I do that by calling cache() again on the same element?

**Comment by lavrton** [comment]
Yep.

**Comment by joachimboggild** [comment]
Just to tell my experience: After drawing nodes, I did a setTimeout(() => { node.cache() }, 50), to have the caching happen after the actual drawing. This did a world of difference. It helped on the performance, and the fonts were retained.

**Comment by lavrton** [comment]
A demo for custom font loading: https://konvajs.github.io/docs/sandbox/Custom_Font.html
