### ISSUE TITLE
can you add textrectangle together

### ISSUE THREAD

**Issue by hollaajay** [konvajs/konva#22]
As I use using kinetic javascript before and now I would like to use konva. Kindly try to implement rectangle with text rather the code will be more and more.
Thanks.

**Comment by lavrton** [comment]
What is your issue?

You can use `Konva.Label` for text + rectangle. http://konvajs.github.io/docs/shapes/Label.html

**Comment by hollaajay** [comment]
I will give you a example think I have 100 rectangle and 100 text has to be written separately. Righr now i am using something like this :  var rect = new Konva.Rect({
x: 50,
y: 50,
width: 100,
height: 50,
fill: 'green',
stroke: 'black',
strokeWidth: 4
});
and for text 
 var simpleText = new Konva.Text({
x: 50,
y: 50,
text: 'Simple Text',
fontSize: 30,
fontFamily: 'Calibri',
fill: 'green',
align: 'center'
}); 
it would take me a long time to do this. is it possible to write both the code in 1?

**Comment by lavrton** [comment]
Long time to do what? How do you think it is possible in one line?

**Comment by hollaajay** [comment]
to write like this for 100 rectangle. That's what I am asking is there any new feature Knova ? something like this:
 var rect = new Konva.Rect({
x: 50,
y: 50,
width: 100,
height: 50,
fill: 'green',
stroke: 'black',
strokeWidth: 4
text:'ajay',
position: {X1,Y1,X2,Y2}
});

**Comment by lavrton** [comment]
I don't think this shape will useful. It is much easier to create `Konva.Rect` and `Konva.Text`.
