### ISSUE TITLE
Stage Drag Performance

### ISSUE THREAD

**Issue by te1** [konvajs/konva#220]
Hi!

I use a draggable stage to allow panning of the graphic. I noticed that dragging the stage becomes slower and slower the more nodes you have even if there is no interactivity on those nodes.

See https://jsfiddle.net/513c8s5d/1 for an example. This is a simplified version of the official 20000 nodes demo. If you drag the stage you will noticed it lags behind and depending on your machine/browser may feel very unresponsive.

I tried the performance tips from the docs (more/fewer layers, disable perfect draw, position transformations only, disable hit graph, listening = false, ...) but the results were unchanged. Reducing the total node count (e.g. 2000) helps of course but is not really an option for me.

Is there a way for me to improve performance? Can something be done in the framework to optimize stage dragging with many nodes? Is there maybe a better way to implement "Pan" than draggable stages?

**Comment by lavrton** [comment]
@te1
1. Do not use too many layers. If you create one layer per 1000 nodes you will have 20 layers for 20000 nodes. I think it is too much. 5-6 is max.
You just need to cache your layers. When and how to cache depend a lot on your application.
https://jsfiddle.net/513c8s5d/2/

**Comment by te1** [comment]
Thank you! Caching the layers leads to much better performance.
