### ISSUE TITLE
context.ellipse does not work for the shape creation

### ISSUE THREAD

**Issue by nazarov-dev** [konvajs/konva#221]
When creating a new shape, there is no standard method [context.ellipse()](https://developer.mozilla.org/ru/docs/Web/API/CanvasRenderingContext2D/ellipse) when I assign the function sceneFunc().

```
var ellipse = new Konva.Shape({
    sceneFunc: function(context) {
        context.beginPath();
        // there is context.lineTo, context.arc but no context.ellipse
        context.ellipse(100, 100, 50, 75, 45 * Math.PI/180, 0, 2 * Math.PI);
        context.strokeShape(this);
    },
    stroke: 'black',
    strokeWidth: 2
});
```

For what reason this is not work?

**Comment by lavrton** [comment]
Just because `This is an experimental technology`. It was badly supported by browsers some time ago. But we can add this method too.


You can just do this:
```javascript
// access to native context
context._context.ellipse(100, 100, 50, 75, 45 * Math.PI/180, 0, 2 * Math.PI); 
```
I will be happy to accept Pull Request if someone is interested.

**Comment by nazarov-dev** [comment]
@lavrton Thanks, your answer helped me a lot!

**Comment by lavrton** [comment]
Reopened as eventually I think we should have this method in Konva context wrapper.
