### ISSUE TITLE
layer.getCanvas()._canvas undefined on Chrome

### ISSUE THREAD

**Issue by dameikle** [konvajs/konva#223]
When trying to call toDataURL on a multilayer stage in Chrome, the _canvas is always undefined triggering the following error:

Uncaught TypeError: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'

Interestingly, on Firefox, Safari and Edge this is always set to the appropriate canvas.

Code in question is below:
```
        _context.drawImage(
          layer.getCanvas()._canvas,
          0,
          0,
          width / ratio,
          height / ratio
        );
```

**Comment by lavrton** [comment]
@dameikle can you create a demo?

**Comment by dameikle** [comment]
@lavrton - I am afraid I can't share the code publicly, but have dropped you an email. Thanks
