### ISSUE TITLE
Text.intersects method not working, getAllIntersections not working for Text shape

### ISSUE THREAD

**Issue by septembermd** [konvajs/konva#224]
My usecase:
I have a transparent layer on top of image and text elements.
I use ```const intersections = stage.getAllIntersections(stage.getPointerPosition())``` then I delegate mouse events to elements returned by this method like this 
```
intersections.forEach((el) => {
      if (el.getParent().getClassName() === 'Group') {
        el.fire(e.type, {type: e.type, target: el, evt: e.evt}, true);
      }
});
```
Everything works as expected for image. But seems like `getAllIntersections` dont work with Text shapes. 
Also I tried
```textShape.intersects(stage.getPointerPosition()))```
and this method doesnt work as well.

**Comment by lavrton** [comment]
Fixed. Thanks for report.
