### ISSUE TITLE
Arrows with dotted lines dot arrowhead outline too

### ISSUE THREAD

**Issue by kingllama** [konvajs/konva#225]
End result is really weird looking. I couldn't determine if there was a way around this.

<img width="138" alt="dotted_arrow" src="https://cloud.githubusercontent.com/assets/8138186/25142139/c567aeca-241a-11e7-8eae-c6de7583d908.PNG">

http://jsbin.com/yadiwisovi/1/edit?html,js,output

**Comment by lavrton** [comment]
Fixes with #373
