### ISSUE TITLE
Multiple calls to sceneFunc on render of a custom shape

### ISSUE THREAD

**Issue by bmoquist** [konvajs/konva#226]
When creating a custom shape, is it expected behavior for multiple calls to be made to sceneFunc on a single render?

Example:
http://jsbin.com/vonididacu/edit?html,js,console,output

**Comment by lavrton** [comment]
@bmoquist yes. This is expected. Konva may use `sceneFunc` for hit drawing. So `layer.draw()` will call `sceneFunc` of a shape twice: 1 - for visible canvas, 2 - for invisible hit canvas.

Also for `react-konva` has specific optimizations,  so there is another call on a mount or on stage size change.

**Comment by bmoquist** [comment]
Great - thanks for the information!
