### ISSUE TITLE
step scaling

### ISSUE THREAD

**Issue by kofifus** [konvajs/konva#227]
we are facing an issue where very big images do not shrink well

this is a canvas issue and a common solution is to step-scaling. See for example this fiddle:
 https://jsfiddle.net/AbdiasSoftware/M4cTx/

how can I implement step scaling in konva ? 

where in code is konva doing the actual scaling ? 

Thx

**Comment by lavrton** [comment]
Konva is using just native `scale` of canvas API. You can do exactly the same steps as in jsfiddle and then use generated `canvas` element as `image` property for `Konva.Image`:
```js
const image = new Konva.Image({
   image: generatedCanvas
})
```
