### ISSUE TITLE
TouchEvent position offsetX/Y are undefined

### ISSUE THREAD

**Issue by deanbitan** [konvajs/konva#229]
I've found a bug on `touchstart` event while using onClick event (on chrome dev tools - mobile mode).

It seems like offsetX/Y are deprecated, but it appears that this library still use these functions:
https://github.com/konvajs/konva/pull/215

In the image below you can see the problem.
![photo_2017-04-25_14-17-03](https://cloud.githubusercontent.com/assets/11488090/25382902/4488e334-29c2-11e7-93c4-d5b9e26b0227.jpg)

I guess the previously mentioned Pull Request is the reason for this bug.

@benbenbenbenbenben, please take a look at this.

**Comment by lavrton** [comment]
You are correct. I think we should use `offsetX` if available and fallback to `clientX` if not.

**Comment by benbenbenbenbenben** [comment]
@deanbitan @lavrton okay, well this is a problem because clientX and clientY are not aware of CSS transforms.

**Comment by lavrton** [comment]
I opened the fix issue: https://github.com/konvajs/konva/issues/500
