### ISSUE TITLE
Compositing to "erase" pixels

### ISSUE THREAD

**Issue by confile** [konvajs/konva#23]
Is it possible to define a rubber function on images? 

Would it be possible to create a circle with a transparent background color when you move the circle over an image it will paint transparent on the image, i.e., it erases parts of the image?

**Comment by confile** [comment]
On a blank canvas I dram an image as shown in the figure below. Now I want to create a circle Shape which can be used to erase parts of the image. The red circle in the image is the eraser.

![javascript_-_erasing_parts_of_an_image_on_html5_canvas__-_stack_overflow](https://cloud.githubusercontent.com/assets/64265/6132479/11d6dda4-b153-11e4-9087-9ca62a0143e0.png)

**Comment by lavrton** [comment]
For now I don't see any good ways to implement this inside framework.

Just for completeness I will add links to your questions from stackoverflow. As I think answear are very good for solving the issue.

http://stackoverflow.com/questions/28438034/erasing-parts-of-an-image-on-html5-canvas
http://stackoverflow.com/questions/28441093/how-can-i-combine-alpha-with-compositing-in-images

**Comment by lavrton** [comment]
I am thinking about implementing demo for Konva sandbox with tips from answears.

**Comment by cosoc** [comment]
都没解决咋就关闭了呢？橡皮擦和马赛克功能不是最常用的么？
