### ISSUE TITLE
Shadow "disappear" when scaling

### ISSUE THREAD

**Issue by Flydiverny** [konvajs/konva#230]
When shadows were updated in 1.3.0 scaling of shapes with shadows seems to have broken.
Ie if I want to flip an image by setting scaleX to -1 or scaleY to -1, the shadow "disappears". When testing in 1.5.0 the shadow actually seems to be in the canvas but its not drawn correctly.

Working:
[jsbin 1.2.2](http://jsbin.com/jiqunifete/1/edit?html,js,console,output)

Not working:
[jsbin 1.3.0](http://jsbin.com/fuqalavuju/2/edit?html,js,console,output)

**Comment by lavrton** [comment]
Thanks for the report!

**Comment by lavrton** [comment]
How it looks with latest version: http://jsbin.com/qiluruvemo/1/edit?html,js,console,output

**Comment by Flydiverny** [comment]
Nice, thanks for the quick follow up!

**Comment by Flydiverny** [comment]
would be great if you could make a release with this fix! So we can use it in production :)

**Comment by lavrton** [comment]
Done

**Comment by Flydiverny** [comment]
Much appreciated! 😄
