### ISSUE TITLE
Drag is broken since 1.6.0 update

### ISSUE THREAD

**Issue by septembermd** [konvajs/konva#231]
Drag element is broken since 1.6.0 update, the element jumps to random position when dragging an element (or in my case grous of objects) and mouse cursor is moved out of konva stage or cursor intersects an element that is on top of the rest elements. 
**videos**
Konva 1.5.0 (working ok)
https://www.dropbox.com/s/sdjujkroh45fw3a/konva%201.5.0.mov?dl=0
Konva 1.6.1 (you can see the issue)
https://www.dropbox.com/s/71f11ewe1pxk4o2/konva%201.6.1.mov?dl=0

**Comment by lavrton** [comment]
@septembermd I can not reproduce. Can you create a DEMO?

**Comment by septembermd** [comment]
sorry looks like something was wrong on my end. nevermind.

**Comment by maaso** [comment]
@septembermd do you know what exactly was wrong on your side? I'm seeing behavior similar to what you describe and can't seem to find the cause

**Comment by psivanov** [comment]
This is exactly what started happening in 1.6.0 for me. When the node is dragged outside of stage its position jumps. Here are 4 consecutive dumps of a node from my dragMove handler, while I am slowly dragging it off stage:

"{\"attrs\":{\"draggable\":true,\"offsetX\":471.00000000000034,\"offsetY\":154.00000000000043,\"x\":**652.0000000000003**,\"y\":**193.00000000000043**},\"className\":\"Group\",\"children\":[{\"attrs\":{\"data\":\"M 431.16966000000036 126.17007142857184 L 510.8303400000004 126.17007142857184 510.8303400000004 181.829928571429 431.16966000000036 181.829928571429 Z\",\"stroke\":\"#ffffff\",\"strokeWidth\":1},\"className\":\"Path\"},{\"attrs\":{\"dash\":[3,3],\"dashEnabled\":[3,3],\"data\":\"M 431.16966000000036 126.17007142857184 L 510.8303400000004 126.17007142857184 510.8303400000004 181.829928571429 431.16966000000036 181.829928571429 Z\",\"stroke\":\"#404040\",\"strokeWidth\":1},\"className\":\"Path\"}]}"

DesignObject.tsx:382 "{\"attrs\":{\"draggable\":true,\"offsetX\":471.00000000000034,\"offsetY\":154.00000000000043,\"x\":**653.0000000000003**,\"y\":**193.00000000000043**},\"className\":\"Group\",\"children\":[{\"attrs\":{\"data\":\"M 431.16966000000036 126.17007142857184 L 510.8303400000004 126.17007142857184 510.8303400000004 181.829928571429 431.16966000000036 181.829928571429 Z\",\"stroke\":\"#ffffff\",\"strokeWidth\":1},\"className\":\"Path\"},{\"attrs\":{\"dash\":[3,3],\"dashEnabled\":[3,3],\"data\":\"M 431.16966000000036 126.17007142857184 L 510.8303400000004 126.17007142857184 510.8303400000004 181.829928571429 431.16966000000036 181.829928571429 Z\",\"stroke\":\"#404040\",\"strokeWidth\":1},\"className\":\"Path\"}]}"

DesignObject.tsx:382 "{\"attrs\":{\"draggable\":true,\"offsetX\":471.00000000000034,\"offsetY\":154.00000000000043,\"x\":**13.000000000000341**,\"y\":**8.000000000000426**},\"className\":\"Group\",\"children\":[{\"attrs\":{\"data\":\"M 431.16966000000036 126.17007142857184 L 510.8303400000004 126.17007142857184 510.8303400000004 181.829928571429 431.16966000000036 181.829928571429 Z\",\"stroke\":\"#ffffff\",\"strokeWidth\":1},\"className\":\"Path\"},{\"attrs\":{\"dash\":[3,3],\"dashEnabled\":[3,3],\"data\":\"M 431.16966000000036 126.17007142857184 L 510.8303400000004 126.17007142857184 510.8303400000004 181.829928571429 431.16966000000036 181.829928571429 Z\",\"stroke\":\"#404040\",\"strokeWidth\":1},\"className\":\"Path\"}]}"

DesignObject.tsx:382 "{\"attrs\":{\"draggable\":true,\"offsetX\":471.00000000000034,\"offsetY\":154.00000000000043,\"x\":**13.000000000000341**,\"y\":**7.000000000000426**},\"className\":\"Group\",\"children\":[{\"attrs\":{\"data\":\"M 431.16966000000036 126.17007142857184 L 510.8303400000004 126.17007142857184 510.8303400000004 181.829928571429 431.16966000000036 181.829928571429 Z\",\"stroke\":\"#ffffff\",\"strokeWidth\":1},\"className\":\"Path\"},{\"attrs\":{\"dash\":[3,3],\"dashEnabled\":[3,3],\"data\":\"M 431.16966000000036 126.17007142857184 L 510.8303400000004 126.17007142857184 510.8303400000004 181.829928571429 431.16966000000036 181.829928571429 Z\",\"stroke\":\"#404040\",\"strokeWidth\":1},\"className\":\"Path\"}]}"

**Comment by lavrton** [comment]
@psivanov Did you have this issue with the last version of Konva.

**Comment by psivanov** [comment]
I have the issue with 1.6.1, but I haven't tried 1.6.3.
Maybe I should...?
