### ISSUE TITLE
get intersection of multiple rectangles inside multiple layers

### ISSUE THREAD

**Issue by mayurbaldha** [konvajs/konva#233]
is there a way to determine intersection of multiple shapes inside multiple layers?

**Comment by lavrton** [comment]
For multiple layers you can use this: https://konvajs.github.io/api/Konva.Layer.html#getIntersection
Just call it for each layer.

You you can use https://konvajs.github.io/api/Konva.Stage.html#getAllIntersections for ALL intersections.

**Comment by mayurbaldha** [comment]
Layer 1 has Rect1,Rect2,
Layer 2 has Rect3,Rect4

now is there a way to check if any of rect intersects at any point

**Comment by lavrton** [comment]
Ah. If you mean intersection between rectangles - so no. There is no API for such check. You have to do this manually. You can use `rect.getClientRect()` to find their bounding boxes.

**Comment by mayurbaldha** [comment]
a shot in the dark Solution is 

function intersect(a, b) {
  return (a.left <= b.right &&
          b.left <= a.right &&
          a.top <= b.bottom &&
          b.top <= a.bottom)
}
