### ISSUE TITLE
Cannot attach event "Click" for any shape if they are in a group and group is draggable

### ISSUE THREAD

**Issue by phongca22** [konvajs/konva#236]
Please review this demo. You should change the draggable parameter in the group and check result.
I had shown color value when clicking on every shape.

https://codepen.io/phongca22/pen/WjKBBN?editors=1010

**Comment by lavrton** [comment]
@phongca22 works fine for me. What is not working for you?

**Comment by lavrton** [comment]
Also take a look at this property: https://konvajs.github.io/api/Konva.Node.html#dragDistance
Probably you group trigger dragging, so no click happen.

**Comment by phongca22** [comment]
Hi @lavrton 

I have a Group has draggable = true.
var group = new Konva.Group({
        x: 120,
        y: 40,              	
      	draggable: true
});

I add some Rects to this group and listen to "Click" event.
Rect.on("click", function(e){        
     console.log('click');
});

Rect.on("mouseenter", function(e){        
     console.log('enter');
});

Rect.on("mouseover", function(e){        
     console.log('over');
});

Mouse Enter event always work. But Click event doesn't work.
I have to add some triggers in below:

Rect.on("mouseenter", function(e){        
    group.draggable(false);
});

Rect.on("mouseover", function(e){        
    group.draggable(true);
});

Yesterday I had to fix this issue by this. Today I test again and it's work well. I don't know why...
When I use konvajs in the first time, everything works ok. I think something is missing. If this happens again I will mention you.
