### ISSUE TITLE
getAbsoluteScale may be has a mistake

### ISSUE THREAD

**Issue by zhangyy75** [konvajs/konva#237]
first,thanks for you Selfless dedication,i find 
getAbsoluteScale: function(top) {

      // if using an argument, we can't cache the result.

      if (top) {

        **return this._getAbsoluteTransform(top);**
         return this._getAbsoluteScale(top);

      } else {

        // if no argument, we can cache the result

        return this._getCache(ABSOLUTE_SCALE, this._getAbsoluteScale);

      }

    },

**Comment by lavrton** [comment]
You are correct! Thanks for the report? Did you just read all the code? 👍
