### ISSUE TITLE
Expose measureText from canvas context

### ISSUE THREAD

**Issue by ptorian** [konvajs/konva#24]
It would be convenient to have the canvas context method "measureText" exposed in the Konva.Context class. I'm new to the framework, but it seems like that could be accomplished by adding this function to the Konva.Context prototype:

    measureText: function() {
        var a = arguments;
        return this._context.measureText(a[0]);
    }

Like I said, I'm new to the framework, so feel free to let me know if/why this won't work or doesn't fit as well as how to actually contribute the change if it does fit.

**Comment by lavrton** [comment]
Why do you need such method? You can create `Konva.Text` instance. And then use `width()` and `height()` functions.

**Comment by ptorian** [comment]
You're absolutely right, that works out perfectly. I will make sure I research the rest of the framework thoroughly before I propose a change in the future.

**Comment by lavrton** [comment]
I want to reopen issue. Now I think this code might be useful. Currently if you want to create your own shape you have to use this:
```
var triangle = new Konva.Shape({
      sceneFunc: function(context) {
        context.beginPath();
        context.moveTo(20, 50);
        context.lineTo(220, 80);
        context.quadraticCurveTo(150, 100, 260, 170);
        context.closePath();
        context.fillStrokeShape(this);
      },
      fill: '#00D2FF',
      stroke: 'black',
      strokeWidth: 4
    });
```
`context` argument is not native canvas context. It is Konva wrapper. But users expect here native context (and all available methods from context). So I want to make possible to work with this wrapper in completely same way as with native context.
One more example if want to change context attributes on this function you have to write:
```javascript
context.setAttr('globalCompositeOperation', 'destination-over');
// or
var nativeContext = context._context;
nativeContext .globalCompositeOperation =  'destination-over';
```
It is all unclear.

**Comment by lavrton** [comment]
close by https://github.com/konvajs/konva/commit/18cce13ea51e69374ec0db9b86d3fd9e40005d85
