### ISSUE TITLE
Why not add a zoom property to the stage?

### ISSUE THREAD

**Issue by stccorp** [konvajs/konva#241]
I see one of your examples that have the following code,  Why not hide that complexity and make one like draggable, something like zoom: true| false, zoom_scale:1.0? 
```
 var scaleBy = 1.01;
        window.addEventListener('wheel', (e) => {
            e.preventDefault();
            var oldScale = stage.scaleX();
            var mousePointTo = {
                x: stage.getPointerPosition().x / oldScale - stage.x() / oldScale,
                y: stage.getPointerPosition().y / oldScale - stage.y() / oldScale,
            };
            var newScale = e.deltaY > 0 ? oldScale * scaleBy : oldScale / scaleBy;
            stage.scale({ x: newScale, y: newScale });
            var newPos = {
                x: -(mousePointTo.x - stage.getPointerPosition().x / newScale) * newScale,
                y: -(mousePointTo.y - stage.getPointerPosition().y / newScale) * newScale
            };
            stage.position(newPos);
            stage.batchDraw();
        });
```

**Comment by lavrton** [comment]
Sorry, your suggestion is not clear for me. What do you want to add?

**Comment by stccorp** [comment]
```
  var imageObj = new Image();
    imageObj.onload = function() {
        var background = new Konva.Image({
            x: 0,
            y: 0,
            image: imageObj,
            width: 800,
            height: 600,
            zoom: true //NEW Property **********
            zoomScale: 1.01 //New Property *************
        });
        // add the shape to the layer
        bgLayer.add(background);
        // add the layer to the stage
        stage.add(bgLayer);
    };
```

**Comment by stccorp** [comment]
Sorry, I meant this

stage.zoom(scaleBy);

**Comment by lavrton** [comment]
I don't think it will make code better.
Currently
```
stage.zoom(scaleBy);
```
will be equal to:
```
stage.scaleX(stage.scaleX() * scaleBy);
stage.scaleY(stage.scaleY() * scaleBy);
```

**Comment by stccorp** [comment]
not really,  it will replace all this

 var scaleBy = 1.1;
    window.addEventListener('wheel', (e) => {
        e.preventDefault();
    var oldScale = stage.scaleX();
    var mousePointTo = {
        x: stage.getPointerPosition().x / oldScale - stage.x() / oldScale,
        y: stage.getPointerPosition().y / oldScale - stage.y() / oldScale,
    };
    var newScale = e.deltaY > 0 ? oldScale * scaleBy : oldScale / scaleBy;
    stage.scale({ x: newScale, y: newScale });
    var newPos = {
        x: -(mousePointTo.x - stage.getPointerPosition().x / newScale) * newScale,
        y: -(mousePointTo.y - stage.getPointerPosition().y / newScale) * newScale
    };
    stage.position(newPos);
    stage.batchDraw();
    });

**Comment by stccorp** [comment]
My point is, why do I have to write all the code, just to make my stage zoomable.  It should be like dragable

**Comment by lavrton** [comment]
I agree. Such function can be very useful.

**Comment by lavrton** [comment]
I am going to close the issue. So we already have this demo: https://konvajs.org/docs/sandbox/Zooming_Relative_To_Pointer.html#page-title

It solves that task. And I don't think adding "zoom" property/methods to konva will make much sense. It will very be confusing what is the difference between scale and zoom.

So I just want to make API of the library simpler. Sometimes it comes with the cost of user's code complexity.
