### ISSUE TITLE
Layer on Top

### ISSUE THREAD

**Issue by stccorp** [konvajs/konva#242]
I have 2 layers. one is my background layer and the other my object layer.  the object layer should be on top, but I dont know how to do that

**Comment by stccorp** [comment]
I did layer.moveToTop(); but my objects are still behind

**Comment by lavrton** [comment]
@stccorp can you please provide the demo? This demo works fine: http://jsbin.com/movovabori/1/edit?js,output

**Comment by stccorp** [comment]
https://jsbin.com/kuxonen/edit?html,js,output

drag the image on top.  you will see the rectangles bellow

**Comment by lavrton** [comment]
@stccorp
That is because you are adding background layer in `onload` callback and it happens in an aynchonuos way after the image is loaded.

Fixed version: https://jsbin.com/rokifivupa/1/edit?html,js,output

**Comment by stccorp** [comment]
thank you. thats works
