### ISSUE TITLE
Unable to provide different tooltips for different objects

### ISSUE THREAD

**Issue by stccorp** [konvajs/konva#243]
I want each object that I draw to display some information about that object.   But I am getting the same  on all objects.  I thought that internally the engine will keep some kind of tap about it.

view output
https://jsbin.com/yakidi/edit?html,js,output

in this case I get tooltip with "B" on both, when One is supposed to be "A" and the other "B"

**Comment by lavrton** [comment]
You just need to learn how javascript variable hosting works.
Take a look here: https://stackoverflow.com/questions/750486/javascript-closure-inside-loops-simple-practical-example

It is not related to Konva framework.

**Comment by stccorp** [comment]
I apologize for my ignorance.  Have you consider making tooltip something that is part of the engine and not something you always have to code from sratch?
like: http://gojs.net/latest/samples/kittenMonitor.html

**Comment by lavrton** [comment]
It is not so hard: https://konvajs.github.io/docs/sandbox/Shape_Tooltips.html
