### ISSUE TITLE
intersects() for a custom shape (rectangle/circle/etc)?

### ISSUE THREAD

**Issue by devdoomari** [konvajs/konva#244]
Is it possible to do an efficient intersects() check with custom shapes?

Current intersects() implementation is:
```
intersects: function(point) {
    var stage = this.getStage(),
        bufferHitCanvas = stage.bufferHitCanvas,
        p;

    bufferHitCanvas.getContext().clear();
    this.drawScene(bufferHitCanvas);
    p = bufferHitCanvas.context.getImageData(Math.round(point.x), Math.round(point.y), 1, 1).data;
    return p[3] > 0;
},
```

which: 
  1). draws the shape on the 'hitCanvas'
  2). checks if alpha value > 0 on the given point (hope this isn't wrong...)

But then, is it possible to do a custom-shape intersects?

Here's one use case:
![image](https://user-images.githubusercontent.com/6072026/27372479-cdbdac52-569f-11e7-9c1f-54ff203b4957.png)

(original image from: https://raw.githubusercontent.com/projectstorm/react-diagrams/master/images/mouseDrag.gif )

**Comment by lavrton** [comment]
Currently, Konva has not support for calculation of shapes intersection. 
Konva can calculate the intersection between `Node` and `Point`.

So you have to calculate shapes intersection manually.

**Comment by devdoomari** [comment]
@lavrton how about using paperJS for calculation?
It seems that paperJS can be used in a worker context for performance : )

**Comment by ButsAndCats** [comment]
@lavrton Would you accept a PR for this if I raised one?

**Comment by lavrton** [comment]
@ButsAndCats probably. It depends on the implementation. The intersection methods can be very large and complex because we have many types of shapes and can draw custom shapes.

**Comment by ButsAndCats** [comment]
@lavrton I'm not sure what my implementation will be like yet but was thinking of trying to add something similar to what Phaser 3 has.

https://photonstorm.github.io/phaser3-docs/Phaser.Geom.Intersects.html

Where you have a each combination of shapes as it's own intersection function and it returns points or arrays of points where the two shapes intersect. Of course easier said than done. I will invest some time and and see what I can do.
