### ISSUE TITLE
Tween to Origin

### ISSUE THREAD

**Issue by whiteboxpub** [konvajs/konva#245]
I have a hexagon that moves around the layer with the mouse x, y pos. When I mouseout of the layer I would like the hexagon to tween back to it's original x, y pos. Instead my tween thinks that my hexagon's x,y position is already at it's origin points so it just flashes back.

I have tried using hexagon.setX(mouse.x) & hexagon.setY(mouse.y) for changing the x,y pos, and I have also tried manually updating using hexagon.x = mouse.x & hexagon.y = mouse.y. Is there another way to update the x,y so that my tween can bring me back to the original points?

EDIT:
[jsFiddle](https://jsfiddle.net/c8wxm2f3/2/)

**Comment by lavrton** [comment]
@whiteboxpub how your tween looks? Can you create a demo?

**Comment by whiteboxpub** [comment]
@lavrton here's a jsfiddle with the issue:

[https://jsfiddle.net/c8wxm2f3/2/](https://jsfiddle.net/c8wxm2f3/2/)

**Comment by lavrton** [comment]
You need to create new tween in your case. On initialization, tween is calculating diff between positions. In your case, the diff is 0 (as you are creating hexagon and tween at the same time).
You can use method `node.to()` for a simpler tween. Also, I changed `mouseout` event to `mouseleave` event.
https://jsfiddle.net/c8wxm2f3/4/

**Comment by whiteboxpub** [comment]
Awesome, thanks for your help @lavrton
