### ISSUE TITLE
function "drawScene()" didn't check if layer is null

### ISSUE THREAD

**Issue by wenzhaoxu** [konvajs/konva#247]
There has a exception when shape's layer is null.

Konva.js Version 1.63. 
Line 8404:
   var layer = this.getLayer(),
        canvas = can || layer.getCanvas(),
        context = canvas.getContext(),

**Comment by lavrton** [comment]
@wenzhaoxu can you make a demo? How can a shape with no layer be part of a stage?

**Comment by wenzhaoxu** [comment]
I'm coding a geometry editor by Konva. The code is too large. Maybe I can make a demo after some days.

**Comment by lavrton** [comment]
Please add a comment when you will have more info.
