### ISSUE TITLE
Is there any way to using Material Icons font description, e.g. unicode expression? (FontAwesome is OK but Material Icons is not working)

### ISSUE THREAD

**Issue by bbbbighead** [konvajs/konva#248]
Anyone know how to using Material Icons using unicode expression in Konva Text class?

FontAwesome is ok in the following way. However, Material Icons is not ok for this.
https://stackoverflow.com/questions/32517056/konvajs-html-in-a-text-object

var simpleText = new Konva.Text({
      x: stage.getWidth() / 10,
      y: 15,
      text: "\uf21c",
      fontSize: 300,
      fontFamily: 'FontAwesome',
      fill: 'green'
    });

**Comment by lavrton** [comment]
I am closing this issue, but I am not sure it is really related to `Konva` and what can we do here.

**Comment by RoobieBoobieee** [comment]
For people coming across this issue because this won't work with Font Awesome 5, the fontFamily should be: 
`fontFamily: '"Font Awesome 5 Free"'` 
note the double quotes inside the single quotes.
