### ISSUE TITLE
How can i use it with Angular2? Can you help me with this?

### ISSUE THREAD

**Issue by rs21in** [konvajs/konva#249]
I have installed konva.js with as npm install konva. After that i have imported in my typescript file. how can i use it and work with it in the respective component

**Comment by lavrton** [comment]
I guess you can use `ngAfterViewInit()` method to get access to DOM node of your component. Then you can do everything you want. 
Something like this:
```js
@Component({
  selector: 'my-app',
  template: `
  <div id="container"l>Hello World!</div>`,
  providers: []
})
export class App implements ngAfterViewInit{
  name:any;
  
  constructor() {}
       
  ngAfterViewInit(){
    var width = window.innerWidth;
    var height = window.innerHeight;
    var stage = new Konva.Stage({
      container: 'container',
      width: width,
      height: height
    });
    var layer = new Konva.Layer();
    var rect = new Konva.Rect({
      x: 50,
      y: 50,
      width: 100,
      height: 50,
      fill: 'green',
      stroke: 'black',
      strokeWidth: 4
    });
    // add the shape to the layer
    layer.add(rect);
    // add the layer to the stage
    stage.add(layer);
  }
}
```
http://plnkr.co/edit/k7PtJfsw1fOWqzC3TaDk?p=preview

**Comment by rs21in** [comment]
hi lavrton, thanks for your answer. 
In your code, It is showing Error : Cannot find name 'Konva' on this line var stage = new Konva.Stage()

**Comment by lavrton** [comment]
Demo works fine.
Probably I didn't add Konva to your project. You can import it from `node_modules` or just add to html:
```html
<script src="https://cdn.rawgit.com/konvajs/konva/1.6.3/konva.min.js"></script>
```

**Comment by fvadouko** [comment]
You can put - declare var Konva: any; - before @component. And you can write "../node_modules/konva/konva.min.js" in the scripts section of your angular-cli.json. But after all these writings, you will just do again : ng serve.
