### ISSUE TITLE
Include Pull Requests from KineticJS

### ISSUE THREAD

**Issue by confile** [konvajs/konva#25]
Do you have plans to include the Pull Requests from KineticJS?

https://github.com/ericdrowell/KineticJS/pulls

**Comment by lavrton** [comment]
I already included 1043.
1039 - not useful in my opinion.
991 - bug fixed (don't need to include).
792, 787 - don't need as I made a lot of updates in caching. Now cache will automatically detect size of all basic shapes. It also will take care of styling, shadow and transforming. New version will be ready soon.
734 - may be will be merged. (is it needed feature?)
654 - currently I don't see good ways to include such workaround into framework.
514 - may be will be merged. (is it needed feature?)
158 - may be will be merged. (need a lot of work to test)
