### ISSUE TITLE
Image loading irregularities?

### ISSUE THREAD

**Issue by taffyy** [konvajs/konva#255]
Hi there,

Thanks for the great library.

I'm currently using layers (with an image loaded to each) while building a product customisation tool. What seems to be weird is that while my Chrome DevTools is open and I debug the page, I can refresh and everything loads fine. When I try and refresh with no DevTools (using browser normally), things don't seem to load properly and break my chain of code.

    konva.min.js:29 Konva warning: Node has no parent. zIndex parameter is ignored.
    warn @ konva.min.js:29
    setZIndex @ konva.min.js:30
    setZIndex @ konva.min.js:44
    window.onload @ ?customize&product=46:554
    konva.min.js:29 Konva warning: Node has no parent. zIndex parameter is ignored.
    warn @ konva.min.js:29
    setZIndex @ konva.min.js:30
    setZIndex @ konva.min.js:44
    window.onload @ ?customize&product=46:555
    konva.min.js:29 Konva warning: Node has no parent. moveToBottom function is ignored.
    warn @ konva.min.js:29
    moveToBottom @ konva.min.js:30
    moveToBottom @ konva.min.js:44
    window.onload @ ?customize&product=46:557
    konva.min.js:29 Konva warning: Node has no parent. moveToTop function is ignored.

This is how I'm loading images:

     _bodyImg.onload = function () {
                 bodyImg = new Konva.Image({
                     x: ($(".canvasCol").width() / 2) - (_bodyImg.width / 2),
                     y: ($(".canvasCol").height() / 2) - (_bodyImg.height / 2),
                     image: _bodyImg
                 });
                 bodyLayer.add(bodyImg);
                 blanketStage.add(bodyLayer);
             };
             _bodyImg.src = '...';

And I'm using `window.onload` to wait for the page to load before carrying out ZIndex sorting / aligning / other stuff. Like I say, it works fine if DevTools is open, but not without. Am I going wrong somewhere and being stupid?

**Comment by lavrton** [comment]
@taffyy probably your issue is related to the cache of the browser. Try this for src:
```js
_bodyImg.src = imageSrc + '?cache_invalid=' + Math.random();
```

If possible provide a small demo.
