### ISSUE TITLE
Who is using Konva?

### ISSUE THREAD

**Issue by lavrton** [konvajs/konva#256]
Hello, everyone. ✋
I am going to create a special page on the `Konva` website with a list of products that are using `Konva`.

If you are using `Konva` in your app, please, add a comment on this issue. Any products are welcome: private enterprise apps, startups, games, open-source projects, etc.

Also, please add this information if possible:

1. Product description
2. Screenshot
3. Direct link to a product (or direct link to the page where konva is used)
4. Stack (any other libraries you use here?)

I may not add any projects to the main list.  But it will be still good to have a list here, so other people can check the demos.

**Comment by dymio** [comment]
Hi Anton.

1. [Website](http://life.tsst.su) of apartment complex «Цвета Жизни» ("Colours of life") in Abakan city, Russia. This is information website for clients with [interactive floor plans](http://life.tsst.su/floor-schemes?floor=5&porch=6) made with Konva.
2. ![screen shot 2017-08-07 at 02 38 15](https://user-images.githubusercontent.com/1663746/29006414-9fa0f966-7b19-11e7-9d11-dc84f2a940d5.png)
3. http://life.tsst.su/floor-schemes?floor=5&porch=6
4. Stack: Konva, jQuery in browser, Rails as backend.

**Comment by lavrton** [comment]
1. Pixteller - "Newly redesigned web app aims to make social media graphics simple".
2. <img width="1258" alt="screen shot 2017-08-08 at 14 53 37" src="https://user-images.githubusercontent.com/1443320/29072774-6ae10ae6-7c49-11e7-9ddc-30b66300912d.png">
3. The app: https://pixteller.com/. The page where Konva is used: https://pixteller.com/editor
4. `React`, `Konva`, `react-konva`, `react-redux`

**Comment by pgrodrigues** [comment]
1. CSGO Board provides an interactive board for Valve's game Counter-Strike: Global Offensive which allows the user to design strategies and game plans for competitive matches.
2. ![image](https://user-images.githubusercontent.com/6011892/29453804-d82218d2-8402-11e7-9b21-d6f544bd89a2.png)
3. http://www.csgoboard.com/board
4. `AngularJS`, `Konva`.

**Comment by vladimir-adtargetme** [comment]
Hi Anton

1. Banner designer - preview of dynamic banners for RTB platform [Adtarget.me](https://adtarget.me) before generate sources.
2. 
![screenshot from 2017-08-23 13-16-22](https://user-images.githubusercontent.com/5849677/29611295-a9de0e70-8805-11e7-887c-e266ceeabafe.png)
3. https://system.adtarget.me/dashboard/creatives/551521c74ba487154fbb01cb/bannertool/#container_id=border
4. jQuery, Konva, Jcrop

**Comment by norbertpisz** [comment]
Hi Anton,

1. SystemPro - tool for create soccer tactics and animations.
2.

​
3. Startup not released yet :)
4. JQuery, Konva, Boostrap, ASP .NET Core MVC

Pozdrawiam,
*Norbert Pisz*
CEO & Founder, Risenbit sp. z o. o.
p:886 668 544 | e:norbertpisz@risenbit.com | w:www.risenbit.com | a: Poland,
Rzeszów, Poznańska 2c
<https://www.facebook.com/norbert.pisz>
<https://pl.linkedin.com/pub/norbert-pisz/54/76b/8ba>
<https://twitter.com/norbertpisz>
Spółka zarejestrowana w Rejestrze Przedsiębiorców przez Sąd Rejonowy dla m.
Rzeszowa XII Wydział Gospodarczy KRS: 0000422018, NIP: 8133673127,
REGON:180851860, Kapitał zakładowy: 5000 zł

2017-08-23 12:21 GMT+02:00 Vladimir Poplavskij <notifications@github.com>:

**Comment by slig** [comment]
1. Online jigsaw puzzle
2. ![screenshot of a jigsaw puzzle](https://user-images.githubusercontent.com/37779/30646206-9cb0144c-9dee-11e7-98b2-0ac408ae07c3.jpg)
3. https://www.brainzilla.com/puzzles/jigsaw/
4. Programmed in TypeScript, using Konva and JQuery.

**Comment by feixinghong** [comment]
我完成了一个排房图，比较的low吧，后期会慢慢进行优化，但是我做的应用在safari下面发现内存占用过多，导致擦除绘制几次以后不能再次绘制，原因是safari下memory useage too large。
![image](https://user-images.githubusercontent.com/3965182/30946890-1e0d2728-a439-11e7-846d-df6ecc2b9557.png)

**Comment by kirill3333** [comment]
Hi, thank you for your library. My example:

![](https://media.giphy.com/media/3o7aD1fCeJxzNu2uYg/giphy.gif)

https://github.com/kirill3333/react-avatar

**Comment by uahic** [comment]
I am using it for robotics navigation visualization in conjunction with angular 4 and RxJs

**Comment by JourdanClark** [comment]
# [\<Snake/>](https://github.com/React-Snake/React-Snake)

[Live Demo](https://react-snake.github.io/React-Snake/)

This is a classic game of Snake made using React and Redux!
It uses [React Konva](https://github.com/lavrton/react-konva) to easily interact with Canvas elements.

This was made for a 24 hour Hackathon for [LambdaSchool](https://lambdaschool.com/). We tied for Best Overall - Student Vote as well as Staff Pick.

You can either use the buttons on the console or the following keys:

  - Up Arrow or W
  - Left Arrow or A
  - Down Arrow or S
  - Right Arrow or D
  - Spacebar or Enter

![demo](https://github.com/React-Snake/React-Snake/blob/master/demo.gif?raw=true "Demo")

**Comment by mcalus3** [comment]
Hi,

I am using react-konva and konva for view layer of my game color-wars. Konva library performed great even under excessive amount of operations :)

https://github.com/mcalus3/color-wars-web

![gameplay](https://github.com/mcalus3/color-wars-web/blob/master/resources/gameplay.gif)

**Comment by uahic** [comment]
@mcalus3 @JourdanClark How much effort was it to combine ReactKonva with Redux?  I am also having some concepts to do the same for Angular 5 + konva + Redux and possible to replace konva at some point entirely with redux+Canvas

**Comment by mcalus3** [comment]
@uahic it wasn't any problem, just follow the component-container architecture. Example from my code:
[Players](https://github.com/mcalus3/color-wars-web/blob/master/src/ColorWars/ReactView/components/Players.tsx) component contains multiple [PlayerVisual](https://github.com/mcalus3/color-wars-web/blob/master/src/ColorWars/ReduxStore/containers/PlayerVisual.ts) containers, each wrapping [PlayerVisual](https://github.com/mcalus3/color-wars-web/blob/master/src/ColorWars/ReactView/components/GameElements/PlayerVisual.tsx) component. No data is given through props, all is taken directly from store.

**Comment by SilentXYZ** [comment]
I'm trying to make program for learning english with Angular/Konva
[http://enpuz.ru/online/lessons/hpttr-03-a](http://enpuz.ru/online/lessons/hpttr-03-a)
![screenshot from 2019-02-04 16-04-25](https://user-images.githubusercontent.com/31912716/52198989-57387000-2897-11e9-91c0-b224b71692e8.png)

**Comment by bmoquist** [comment]
**Kuruko - "Create Custom Wall Art with High-Quality Mounted Photo Prints"** 

Konva is used:
- Main drag-and-drop wall design editor
- Image editor (cropping images, creating SplitPics, selecting which image to edit)

![Kuruko Screenshot for Konva](https://user-images.githubusercontent.com/4001159/58354429-03966600-7e37-11e9-86ed-614a2d4ce7f3.jpg)
![Kuruko Screenshot for Konva 2](https://user-images.githubusercontent.com/4001159/58354812-13627a00-7e38-11e9-9093-3c8a5584ebb3.jpg)

Main: https://www.kuruko.com
Konva-based Editor: https://www.kuruko.com/design

Stack: React, Redux, Konva, React-Konva, Semantic UI React, Express, Postgres

**Comment by bluehymn** [comment]
I use it to draw charts in my work

Angular + Konvajs

![TIM截图20191213094829](https://user-images.githubusercontent.com/15361704/70763191-3467c980-1d8e-11ea-960c-c662f8628547.png)

![TIM截图20191213094914](https://user-images.githubusercontent.com/15361704/70763192-3762ba00-1d8e-11ea-8992-ced763dca1d3.png)

![TIM截图20191213094940](https://user-images.githubusercontent.com/15361704/70763196-392c7d80-1d8e-11ea-80d8-3ae68c887d64.png)

**Comment by songoffire** [comment]
### ScriptureMark
**DESCRIPTION:** A free tool that allows users to interact with Bible text on a canvas with a variety of text layout and markup tools.
**LINK:** https://www.blueletterbible.org/smark
**IMAGE:**
 + ![img](https://i.imgur.com/rTDsCu4.png)

**Comment by externuz** [comment]
###Description
Constructor for creating Instagram Stories as part of the scheduled posting service SMMplanner. smmplanner.com

###Direct link
https://smmplanner.com/home/sc

###Stack
React, react-konva, typescript

###Screenshots
<img width="1458" alt="scr1" src="https://user-images.githubusercontent.com/7888156/82424542-00f04000-9a8e-11ea-801b-700a4dcdc886.png">

**Comment by jprevo** [comment]
1. Let's Role allows people from everywhere to play TableTop RPG in a virtual environment

**Comment by wikywin** [comment]
**Description**
tool for designing window and door with drag and drop

**Direct link**
[windoor craft](https://windoorcraft.com) (facebook and google account are supported)

**Stack**
Vue, konva, typescript

**Screenshots**
<img width="1919" alt="WX20200606-085942@2x" src="https://user-images.githubusercontent.com/4850368/83932319-4de54d80-a7d4-11ea-81b3-1998553575f1.png">
<img width="1915" alt="WX20200606-085829@2x" src="https://user-images.githubusercontent.com/4850368/83932304-3a39e700-a7d4-11ea-9104-ee57dee788db.png">
<img width="1919" alt="WX20200606-085846@2x" src="https://user-images.githubusercontent.com/4850368/83932306-402fc800-a7d4-11ea-9a94-06ed62082342.png">
<img width="1919" alt="WX20200606-085913@2x" src="https://user-images.githubusercontent.com/4850368/83932311-4756d600-a7d4-11ea-841c-5ac7cf1b62e5.png">

**Comment by rmdort** [comment]
## SpreadSheet Grid

https://rowsncolumns.app

### Product description

An Excel-like DataGrid component built using Konva and React. Allow users to declarative render grids, cells without sacrificing performance. Some of the popular features are

1. Frozen Rows and Columns
1. Custom Cell Renderers and Editors
1. Custom formatting and Validation
1. Formula support (coming soon)
1. Dark Mode
1. Custom fonts, styling
1. Data validation
1. Render konva components as overlays or as cell


Screenshot
<img width="1121" alt="screenshot-1" src="https://user-images.githubusercontent.com/118231/88262136-36b5dd00-ccfa-11ea-919e-3be6d46ae8ac.png">

<img width="1119" alt="screenshot-12" src="https://user-images.githubusercontent.com/118231/88262202-50572480-ccfa-11ea-8b62-736dbd8426b2.png">


### Direct link to a product (or direct link to the page where konva is used)

https://rowsncolumns.app

### Stack (any other libraries you use here?)

1. React
1. React Konva

**Comment by owendwyer** [comment]
Hi, thanks so much for making Konva.  It's really easy to use and suits my needs perfectly.

### Online Picture Dictionary

A simple vocabulary viewer that shows images, text and plays audio.

![opdome com](https://user-images.githubusercontent.com/23256897/90326038-8c09a500-dfad-11ea-96af-01a122673fdf.png)

[opdome.com](https://www.opdome.com/)

**Stack**
Konva
Howler

**Comment by frizurd** [comment]
**Description**
Create podcast video snippets for social media. 
Use the editor to customize existing templates or create one from scratch.

**Direct link**
[https://app.vokal.co/editor](https://app.vokal.co/editor) (requires registration, Facebook and Google are supported)

**Stack**
Konva, Vue, Nuxt

**Screenshots**
<img width="1920" alt="Screenshot 2020-11-18 at 17 59 23" src="https://user-images.githubusercontent.com/8818588/99561944-d1cc7400-29c7-11eb-9f03-509a5ae4260d.png">
<img width="1438" alt="screenshot app editor" src="https://user-images.githubusercontent.com/8818588/99561603-6da9b000-29c7-11eb-945e-9ec56be1eb6c.png">

**Comment by gherkins** [comment]
https://e-cards.shop/de/cards/create/2/1

Online shop for business ecards.   
Built with Symfony, React & Konva

<img width="1532" alt="Bildschirmfoto 2021-02-22 um 07 59 22" src="https://user-images.githubusercontent.com/824927/108673436-f1ea6280-74e3-11eb-9db6-dc2b3df2950d.png">

**Comment by sarvarunajvm** [comment]
> I use it on facetache!
> Description: Add moustaches to photos!
> Website:https://www.facetache.com/
> 
> ![screen shot 2018-10-17 at 12 25 30 am](https://user-images.githubusercontent.com/1211914/47035052-40182a00-d1a3-11e8-81d2-2f96f850181a.png)

can you please share the snip that you are using to rotate the element

**Comment by lavrton** [comment]
💥  Big update!

Hey, @pgrodrigues @slig @kirill3333 @mcalus3 @bmoquist @songoffire @jprevo @owendwyer @frizurd @gherkins 
I just added your projects to the main konva webpage: https://konvajs.org/

I hope to add new cool projects in the future. Let me know if any information is missed or should be updated.

**Comment by slig** [comment]
Fantastic! Thanks for the project and for the link!

**Comment by songoffire** [comment]
That's Awesome!

Thank you so much for all your hard work maintaining and growing KonvaJS
Anton!

**Comment by frizurd** [comment]
> 💥 Big update!
> 
> Hey, @pgrodrigues @slig @kirill3333 @mcalus3 @bmoquist @songoffire @jprevo @owendwyer @frizurd @gherkins
> I just added your projects to the main konva webpage: https://konvajs.org/
> 
> I hope to add new cool projects in the future. Let me know if any information is missed or should be updated.

That's so awesome! Thank you so much for featuring vokal.co and creating, maintaining, and making Konva more awesome! 🥺🎉

**Comment by LetsRoleRPG** [comment]
Thank you for featuring Let's Role and for this amazing framework ❤️

**Comment by adamw** [comment]
Shelly: a programming language for drawing.
Website: [https://shelly.dev](https://shelly.dev)
Stack: TypeScript + React + Konva + Monaco (editor) 

<img width="1283" alt="Screenshot 2021-02-26 at 09 50 52" src="https://user-images.githubusercontent.com/60503/110806566-7aa62400-8282-11eb-8f81-f980971ec00d.png">

**Comment by mwehnert** [comment]
1. We created [yokanban.io](https://yokanban.io), a new Kanban tool that combines the best of digital and physical kanban boards.

2.
![image](https://user-images.githubusercontent.com/11538167/111774956-6d0b2280-88b0-11eb-9d3c-b69089ee7714.png)

3. https://app.yokanban.io

4. We use konva and react-konva for all the canvas stuff, which made it easy to get started without to much canvas knowledge. Apart from that, we use react, easy-peasy, next.js, chakra-ui, fastify, mongoDB and, sure, some other cool libs.


Cheers to @lavrton

**Comment by superliwei** [comment]
# BoardOS
Online whiteboard collaboration system
## Website
https://boardos.online
## Preview
![https://boardos.online/preview/3.jpg](https://boardos.online/preview/3.jpg)
## Stack
Vue,Konva

**Comment by lavrton** [comment]
@adamw @mwehnert @superliwei  I added your projects to the main page: https://konvajs.org/



> P.S. For anyone reading this, remember to check this page: https://konvajs.org/docs/donate.html

**Comment by superliwei** [comment]
@lavrton awesome! thanks a lot!

**Comment by sta1216** [comment]
1.It's a quantity takeoff product base on the BIM model. The user can simply access it via the browser，instead of the traditional desktop application.
2.SaaS Site: https://service.spdcost.com/
3.Vue, Echarts, written by typescript
4.
![beam](https://user-images.githubusercontent.com/12050499/116060421-727c3980-a6b4-11eb-9cf0-d7c9e360cfaa.png)
![column](https://user-images.githubusercontent.com/12050499/116060434-7445fd00-a6b4-11eb-9b15-fe2ec19e8d56.png)
![slab](https://user-images.githubusercontent.com/12050499/116060440-75772a00-a6b4-11eb-97ee-3e35bce5a13f.png)

**Comment by metaflow** [comment]
1. Recoils practice for Apex Legends
2. ![ezgif-7-a8136dc6c40e](https://user-images.githubusercontent.com/254523/116812594-c4f3a500-ab4f-11eb-93f9-ec4e78810689.gif)
3. https://apexlegendsrecoils.online/
4. Konva + [howler](https://howlerjs.com/) for sound playback.

Thanks for the great lib!

**Comment by TimAstier** [comment]
Thanks for this amazing library! I'm developing a web-based roguelike game using react.

I was using react to render and update the map as the player moves around, and even if it's the beginning of the project, I could already feel it was becoming laggy. This week I switched the game rendering from DOM elements to react-konva and the result was fantastic :)

---

- Name: **React Roguelike**
- Description: **A roguelike game built with React and TypeScript**
- Playable link: https://react-roguelike.herokuapp.com/
- Github: https://github.com/TimAstier/react-roguelike
- Stack: **React, TypeScript, React Konva, Immer**

<img src="https://user-images.githubusercontent.com/8555097/117532703-1c2ec500-afe9-11eb-94df-67ff6689188e.png" />

**Comment by peter1123581321** [comment]
1. Genetic.garden is a website that helps you to arrange your vegetables in your garden beds with the help of a genetic algorithm.
2. 
![geneticgarden](https://user-images.githubusercontent.com/53783118/119044284-4ce40680-b9ba-11eb-9b26-4983d2be4680.png)

3. https://genetic.garden
4. Konva, Chart.js, Bootstrap

**Comment by jamestomasino** [comment]
Oh this is a creative way to share sites using konva! I wrote a crochet pattern generator with it last year called Stitchy.

1. Stitchy is a crochet pattern generator. It's here to help you convert an image into a rectangular pattern of knots. Choose your pattern size and the number of colors you'd like to use, then upload the image you want to use as a pattern. You can resize, move, and rotate the image. When it's just right, click “Render” and generate your pattern.
2. ![stitchy](https://user-images.githubusercontent.com/201422/124138433-2a8fdf00-da76-11eb-969e-cfd22984b7e5.jpg)
3. [Website](https://jamestomasino.github.io/stitchy/) - [Source](https://github.com/jamestomasino/stitchy)
4. Konva, [nearest-color](https://github.com/dtao/nearest-color), [ColorThief](https://github.com/lokesh/color-thief)

**Comment by AshreneRoy** [comment]
### 1. Blackboard

React based Chrome extension to draw and annotate over live web pages, and capture full page screenshots

### 2. Preview

<img width="1680" alt="ss-1" src="https://user-images.githubusercontent.com/46489332/124231238-0c32ed80-db21-11eb-8774-588e994b3b68.png">

![ss](https://user-images.githubusercontent.com/46489332/124231992-12759980-db22-11eb-9475-8a822ec0dacc.png)

### 3. Links

Chrome extension: https://chrome.google.com/webstore/detail/blackboard/mjpaeljbciakgnigdligmdihfhnpbfla
Repo: https://github.com/AshreneRoy/blackboard

### Stack

React-Konva, Styled components

**Comment by weiameili** [comment]
### 1. Pensela: The Swiss Army Knife of Screen Annotation Tools
An app to that allows you to draw and add text on your screen
### 2. Screenshots
![image](https://user-images.githubusercontent.com/74808990/126866290-15eec781-299c-43b9-acb6-dcfa724ce792.png)
![image](https://user-images.githubusercontent.com/74808990/126866295-accb86ae-ff0f-4427-97f2-9f4bede30430.png)
### 3. Github Repo
https://github.com/weiameili/Pensela
### 4. Stack
Konva, Jquery, Electron

**Comment by Albert-cord** [comment]
## 1. A built-in print designer for PaaS system
description: I use it to draw graphics in the main view area of the designer, include the sheet subset table
## 2. Screenshots
![image](https://user-images.githubusercontent.com/31922224/131221252-de22e25d-a5d3-4bcb-bef2-7019bdb956b2.png)
## 3. Stack
Konva, Konva-React, React, TypeScript
