### ISSUE TITLE
Support for strokes with gradients

### ISSUE THREAD

**Issue by dkrutsko** [konvajs/konva#257]
Hey there, I'm trying to implement an effect similar to [this](https://codepen.io/jackrugile/pen/Gving). using [Konva-React](https://github.com/lavrton/react-konva). In that effect, I have the trail implemented as a line with a stroke. Unfortunately I was unable to find a way to add a gradient to a `stroke` similar to how it could be done with a `fill`. Is this something that's supported by Konva? I believe it could be implemented with [`strokeStyle`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/strokeStyle)

**Comment by lavrton** [comment]
https://stackoverflow.com/questions/46559805/unable-to-give-gradient-to-a-line-using-react-konva
