### ISSUE TITLE
No preventDefault on wheel event vs touchmove

### ISSUE THREAD

**Issue by albertogasparin** [konvajs/konva#258]
Looks like `contentWheel` event does not correctly `preventDefault` as all other events do, event when stage `preventDefault` is true (the default) and the stage is listening for the event.

See http://jsbin.com/quraxavexe/1/edit?html,css,js,output

I think it should behave as touchmove, for consistency between desktop/mobile.

**Comment by lavrton** [comment]
Not all events call `preventDefault()`. Only when drag&drop enabled.
`preventDefault()` for `wheel` event will prevent scrolling. But in many cases, we need native scrolling.

You can call it manually if you need.
