### ISSUE TITLE
Inherit visibility by default

### ISSUE THREAD

**Issue by Dannsei** [konvajs/konva#259]
Feature enhancement request: Currently, the default is that children remain visible even if the parent Konva Group is hidden.  i.e. children do not inherit visibility by default, but this has to be manually set for each child.  It would be more intuitive to have parent Group visibility to override visibility of children by default (perhaps have a parent_overrides_child_visibility property for the Konva Group class which is set to true by default).

The current behaviour can be confusing - see e.g.:
https://stackoverflow.com/questions/42232057/using-show-and-hide-in-konva-for-groups

**Comment by lavrton** [comment]
@Dannsei please give more info. To be honest, I don't understand the issue in StackOverflow question.
Take a look at this demo: http://jsbin.com/reraxozega/1/edit?js,output
Works as expected. Children are not visible when I hide the group.

**Comment by Dannsei** [comment]
Yes this does work as expected (and does so even if visibility property of child is not explicitly set).  I no longer have the original code where this wasn't behaving and can't now reproduce the issue.  Apologies, I should have checked to see that I could reproduce the issue before posting.

**Comment by lavrton** [comment]
Good. Please add a comment with a demo, if you will be able to reproduce the issue.
