### ISSUE TITLE
Stage.resize broken on cherry picked core

### ISSUE THREAD

**Issue by albertogasparin** [konvajs/konva#261]
When importing just `konva/src/Core`, `stage.resize()` method throwns an error as `Stage.batchDraw` is not defined.
Indeed, `batchDraw` is defined in `konva/src/Animation`, which is not required by Core.

I would propose add `require(Animation)` to Core.
Moreover, to reduce Animation size a bit, I would clean up `RAF` to be just:

```js
var RAF = Konva.global.requestAnimationFrame || FRAF;
```

As [all browser](http://caniuse.com/#search=requestAnimationFrame) support the unprefixed version (leaving the timeout fallback for old IE).

**Comment by lavrton** [comment]
I am closing the issue for now, because the internal structure of `Konva` is completely changed with version 3. Currently, it is not possible to cherry pick core code at all, but that functionality will be added back later.
