### ISSUE TITLE
offset not updating after dragging shape around

### ISSUE THREAD

**Issue by marcel-silva** [konvajs/konva#262]
Hi,
If this is not something out of the box, can someone tell me how to get the new offset X and Y after dragging a custom shape around and scaling the layer?

I drew the custom shape at a specific position in the canvas, using "sceneFunc".

I made an example. 
Please try moving the shape around and also scaling down.
Offset values remains the same.
Note: Rotating it works fine.

https://jsbin.com/juvevubugi/1/edit?html,output

thanks

**Comment by lavrton** [comment]
`offset` is not changing while dragging. `offset` property is used for defining the "center" of a shape.
But `x` and `y` properties are changing while dragging:
https://jsbin.com/nafoqatufu/1/edit?html,output

**Comment by marcel-silva** [comment]
Sure. I understood that now. thanks!

But if position X/Y and offset X/Y are the same, and using same scenario as before, 
How can i calculate the 4 corners of a custom shape, with a custom center, and that has been dragged around?

Image Example:
![star](https://user-images.githubusercontent.com/18476252/29554191-9059751a-8761-11e7-8da5-36cf4bd582f5.png)

thanks

**Comment by marcel-silva** [comment]
Here is the solution, no thanks to lavrton: https://jsbin.com/socuzocatu/1/edit?html,output

Had to be creative and save in a custom attribute the offset difference from the shape's absolute center to my custom center.

Please let me know of a easier way if you can.

thanks.
