### ISSUE TITLE
Allow imageSmoothingEnabled to be set on Context

### ISSUE THREAD

**Issue by albertogasparin** [konvajs/konva#263]
`imageSmoothingEnabled` is not allowed in `Konva.Context`. Ideally, it would be great to handle vendor prefixes too, with a custom getter/setter.

Currently doing:

```js
let ctx = myLayer.getContext()._context;
if ('imageSmoothingEnabled' in ctx) {
   ctx.imageSmoothingEnabled = false;
} else {
   ctx.mozImageSmoothingEnabled = false;
   ctx.msImageSmoothingEnabled = false;
}
```

**Comment by lavrton** [comment]
With the last version we can do `layer.imageSmoothingEnabled(false);`
