### ISSUE TITLE
Layer not cleared of existing elements before drawing

### ISSUE THREAD

**Issue by justinwyllie** [konvajs/konva#265]
I have a layer on which I have drawn a label and a path.

I have this code:

var b = mylayer.clearBeforeDraw();// returns true (the default)
mylayer.draw();

However. It is not clearing the layer before drawing. It just keeps adding more elements to it. In the source code, 1.6.5, I in a block which starts: Konva.Util.addMethods(Konva.Layer,... and specifically at line 11027 I see this:

 if (this.getClearBeforeDraw()) {
        canvas.getContext().clear();
 }

This is being called. It looks like this is what should be clearing the layer. But is not.

canvas.getContext() returns a Kona.SceneContext object. But it then appears that on this object there is no function clear() defined - this is undefined. This appears to be the problem.

Am I doing something wrong? E.g. not using 'Scenes' - or is this a bug?

Thanks.

**Comment by lavrton** [comment]
@justinwyllie do you have demo?

**Comment by justinwyllie** [comment]
replicated with 1.6.8. Will put up demo in a few minutes. Thanks

**Comment by justinwyllie** [comment]
Thanks @lawton. 

http://mms-oxford.com/konva/index.html

This is an example. What I want to happen is that when the button is pressed the yellow arc goes away and we see only the red arc, What is happening is that the yellow arc stays and the red arc is added to the layer. Thanks.

**Comment by lavrton** [comment]
@justinwyllie ah no. `clearBeforeDraw = true`  do NOT remove nodes from canvas. It just clear canvas before drawing. One each button press you are adding a new element into the layer.
In your case, you should manually remove a node from the layer or call `layer.destroyChildren()`

**Comment by Revannath** [comment]
Thanks Man. it's working fine
