### ISSUE TITLE
Implement transforming tool

### ISSUE THREAD

**Issue by lavrton** [konvajs/konva#270]
Konva doesn't have built-in transforming tool like this:

<img width="80" alt="screen shot 2017-09-05 at 11 19 21" src="https://user-images.githubusercontent.com/1443320/30054343-1806dffa-922c-11e7-8cdd-8d55f379e1fb.png">

I already implement it several times for different applications. I think it will be nice to have it as a part of `Konva` framework or as a separate module.

**Comment by jasie** [comment]
This is a really useful feature in Fabric.js, but since Fabric sucks (sorry) I implemented this feature in my Konva app by myself, too.

**Comment by lavrton** [comment]
> This is a really useful feature in Fabric.js

I agree. This is why I sometimes recommend `Fabric.js` instead of `Konva`

**Comment by uahic** [comment]
Hi guys,

is there any progress on that or maybe @jasie could you please show me your implementation of that? 

Thank you very much

**Comment by uahic** [comment]
I am looking right now how to implement that, one way would be to define it on the node level in low level Canvas drawing (similar to the red debugging rectangle). However, it would be much nicer to define this such that the user might compose/customize its own transforming tools on a higher level using konva Shapes etc.

I see @lavrton has done it like in fabric.js, how did you implement that?

**Comment by uahic** [comment]
What is the current status of this? I need some input here ;)

**Comment by lavrton** [comment]
I will publish my result soon. I think in this month.

**Comment by uahic** [comment]
That would be really great, from my employers side I have to finish this part of our custom editor (robotics stuff) until next week (nope I am not a web developer usually :D) ; But probably that is too soon for you. I will then try to find some dirty workarounds for the moment until your code is out 
:+1:

**Comment by lavrton** [comment]
🦏 Good news everyone!

I am publishing some progress on this.
You can see the first demo here: http://jsbin.com/meqekehofa/edit?js,output

Currently, it works with "rect-like" shapes (text, images, etc).
It doesn't work with circle yet.

The main source is here: https://github.com/konvajs/konva/blob/master/src/shapes/Resizer.js

Have any comments or feedback? Feel free no comment in this issue.

**Comment by uahic** [comment]
In general it looks fine! 

Here are some issues I am running into:
- konva.Line seems always to have position()  of (0,0) (instead of taking the position of the most topLeft point), which then misplaces the konva.Resizer
- In your example, if you rotate the rect like +45 degree clockwise and scale it then, the rect itself "whobbles" quite a bit ;)

**Comment by uahic** [comment]
Further Issue
- The scaling anchors do not seem to respect scaling of the stage, if you trigger the scaling anchors via mouse (if stage is already in a scale different than 1), then the shape "flys away"

**Comment by lavrton** [comment]
@uahic thanks for the feedback. Fixed many bugs.

**Comment by uahic** [comment]
@lavrton Looks excellent! Thank you for the effort you put in.

**Comment by suresh2018** [comment]
![image](https://user-images.githubusercontent.com/30258184/34376144-54e52458-eb10-11e7-8720-f02ce985e80d.png)
If an object has 4 corners, I just want to extend only one corner, another point should not change from their position.

For example: consider rectangle having a,b,c,d corner; the d point only should move.

**Comment by suresh2018** [comment]
this is possible in konva js ?

**Comment by skworden** [comment]
This would be a really helpful feature! Does anyone know when this might be avalible?  I see the [file changed to transformer.js](https://github.com/konvajs/konva/blob/master/src/shapes/Transformer.js) and I tried it out. It's a great start but it's definitely not ready for testing.

**Comment by ErmineKrok** [comment]
Hello, good work for this Transformer, i love it <3 but i have many suggestion for Transformer:
-rotateEnabled -> can desactivate or activate the rotate; default value: true
-lineEnabled -> can desactivate or activate the blue stroke line; default value: true
-widthLimit -> limit the width of the element in pixels; default value -> null
-heightLimit -> limit the height of the element in pixels; default value -> null
-a variable like rotationSnaps but the element rotate only at values; example: [0, 45, 90, 135, 180, 225, 270, 315, 360];  default value -> []

**Comment by uahic** [comment]
Further ideas:

to make it nice for mobile (touch) applications, there might also be an alternative control (a single rect or something) which can be enabled which does all things at once: rotate and scale, the only difference to the already existing would be that it scales the group with respect to the axis in both directions equally.

**Comment by skworden** [comment]
Since it was implemented, I created a separate issue  #323 .

**Comment by Namalee** [comment]
a good feature to add would be some events like "transformstart" and "transformend" to allow people to do some stuff when these events are fired.

**Comment by lavrton** [comment]
I made basic functionality. It is released with new konva v2.0.

**Comment by lbrevity** [comment]
Hello, https://github.com/konvajs/konva/blob/master/src/shapes/Resizer.js this is not working.. 
 Transforming tool is default available?

**Comment by lavrton** [comment]
@lbrevity I ranamed it into `Transformer`.

**Comment by cjmetacrawler** [comment]
> ![image](https://user-images.githubusercontent.com/30258184/34376144-54e52458-eb10-11e7-8720-f02ce985e80d.png)
> If an object has 4 corners, I just want to extend only one corner, another point should not change from their position.
> 
> For example: consider rectangle having a,b,c,d corner; the d point only should move.
> this is possible in konva js ?

is this possible?

**Comment by lavrton** [comment]
Just create a combination of lines and circle and attach events manually.

**Comment by cjmetacrawler** [comment]
> Just create a combination of lines and circle and attach events manually.

But how do you it using konva?

**Comment by lavrton** [comment]
https://konvajs.org/docs/sandbox/Modify_Curves_with_Anchor_Points.html

**Comment by biggestdickus** [comment]
Do you have an example like cjmetacrawler's picture? Thou the Bezier example is pretty fancy, it is also too completed for me to break down for just a simple polyline or polygon. e.g. Simple 4 corner polygon that each vertex can be dragged. Also could you use old style function coding rather than => as I'm not use to that format yet.

**Comment by biggestdickus** [comment]
I like to mention that I just switched to Konva from Fabric.js because their polygon drag vertexs example blows up if you flip it or mirror the polygon. I hope this is not true in Konva.
