### ISSUE TITLE
`contentMouseup` event not triggered on `Konva.stage` if mouse up happens outside of stage

### ISSUE THREAD

**Issue by jainanshul** [konvajs/konva#271]
http://jsbin.com/yokacen/edit?html,js,console,output demonstrating the issue where the `mouseup` doesn't get triggered outside of the `green circle` even though stage area is bigger than the area of the `circle` inside it.

**Comment by lavrton** [comment]
Currently, this works by design. If you need to listen to events of the stage you can use `contentMouseUp`.

https://konvajs.github.io/docs/events/Stage_Events.html

**Comment by jainanshul** [comment]
`contentMouseUp ` is the event that is not working when added on the `stage`? Did you mean some other event?

**Comment by lavrton** [comment]
Ah. Yeah. Typo in the event name: `contentMouseup`
http://jsbin.com/nikugojuxi/1/edit?html,js,console,output
