### ISSUE TITLE
a question about 'fillEnabled'

### ISSUE THREAD

**Issue by zhangyy** [konvajs/konva#272]
1.  hasStroke: function() {
      return **this.strokeEnabled()** && !!this.stroke();
    }
but why the function 
 hasFill: function() {
      return !!(this.getFill() ||
        this.getFillPatternImage() ||
        this.getFillLinearGradientColorStops() ||
        this.getFillRadialGradientColorStops());
    } has no **this.fillEnabled()** condition;

2.when I set fillEnabled=false,strokeEanbled=false, the Konva.Image Object can display the picture,but can't be hittested

**Comment by lavrton** [comment]
1. ¯\\__(ツ)_/¯

2. Am not sure is it a bug or not. `Konva` is using strokes and fill for hit testing. And from my point of view, this is expected behavior.
