### ISSUE TITLE
Chrome bug drawHitFromCache()

### ISSUE THREAD

**Issue by devth8** [konvajs/konva#278]
In drag'n'drop the following example :
https://konvajs.github.io/docs/events/Image_Events.html
```
lion.cache();
lion.drawHitFromCache();
```
does not work as soon as one leaves the window the image which has the function

Ok :
_____________
|                  |
|         O      |
|                  |
_____________

O = image

Bug :

(after drag'n'drop image output window)

_____________
|                  |
|                  |  O
|                  |
_____________

bug Chrome drag'n'drop

group drag'n'drop (with in image cache & drawHitFromCache) is larger than the window

**Comment by lavrton** [comment]
@devth8 Can you provide a demo? I don't see where is the bug.
