### ISSUE TITLE
Rotate anchor

### ISSUE THREAD

**Issue by juanpmarin** [konvajs/konva#279]
Hi, thanks for making this great lib

I seeing this example https://konvajs.github.io/docs/sandbox/Image_Resize.html

I want to add an anchor for drag and rotate the image like ms word does but I cant get it working
Can you give some ideas of how to achieve that ? 

Reference image:
https://i.stack.imgur.com/rVFk6.png

Thanks !
Sorry for my english

**Comment by lavrton** [comment]
You can try to use new `Transformer` shape.
https://konvajs.github.io/docs/select_and_transform/Basic_demo.html

**Comment by juanpmarin** [comment]
@lavrton Has it touch support ?

**Comment by lavrton** [comment]
I think not yet. I will add support for it soon.
