### ISSUE TITLE
Line Interpolation

### ISSUE THREAD

**Issue by confile** [konvajs/konva#28]
Is there some line interpolation build in Konva like proposed in the following post: 

http://stackoverflow.com/questions/28638627/draw-smooth-lines-on-a-canvas

**Comment by lavrton** [comment]
No.

**Comment by confile** [comment]
@lavrton Do you have an example for doing this with Konva?

**Comment by lavrton** [comment]
I have not. I don't think your issue is related to Konva. You have very specific use case and it is related to canvas sketch drawing. In my opinion you should search some general solutions. May be you can try to google something like "canvas freehand drawing".

**Comment by confile** [comment]
Okay thank you
