### ISSUE TITLE
Cannot read property 'documentElement' 

### ISSUE THREAD

**Issue by AlexandrAnash** [konvajs/konva#280]
After update 1.6.8 to 1.7.1, I have Error 

`Uncaught TypeError: Cannot read property 'documentElement' of undefined  at konva.js:12706`
for some reason document - undefined :(

**Comment by nicoja** [comment]
Hi, I confirm also the problem

**Comment by lavrton** [comment]
What environment? Browser? NodeJS?

**Comment by nicoja** [comment]
Environnement is Browser 

```
if (Konva.isBrowser) {
  var html = Kona.document.documentElement;
```

**Comment by lavrton** [comment]
@nicoja how can I reproduce? All demos and tutorials are working fine with the latest version.

**Comment by lavrton** [comment]
I think I found the problem. Making new release.

**Comment by lavrton** [comment]
Please try new version `1.7.2`.

**Comment by DrJonki** [comment]
Had the same problem, fixed now. Thank you!

**Comment by nicoja** [comment]
@lavrton It is fixed. Thanks !
