### ISSUE TITLE
layer.clear() doen't work after stage.size(config) invoked

### ISSUE THREAD

**Issue by xuchaoqian** [konvajs/konva#285]
Feel very confused.  Just check the result: 
http://jsbin.com/toditonufe/edit?html,js,output

And paste code here for fast reading:
> 
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  
</head>
<body>
<div id="container"></div>
<script src="https://cdn.rawgit.com/konvajs/konva/1.7.2/konva.js"></script>
<script>
  var width = window.innerWidth;
  var height = window.innerHeight;

  var stage = new Konva.Stage({
    container: 'container',
    width: width,
    height: height
  });

  var layer = new Konva.Layer();
  stage.add(layer);

  layer.add(new Konva.Rect({
    width: 100,
    height: 100,
    fill: 'red'
  }))

  layer.draw();

  stage.on('contentClick', function (e) {
    stage.size({width: width, height: height});
    stage.clear();
    console.log(e.evt.preventDefault());
    console.log('context click');
  });
</script>
</body>
</html>

**Comment by xuchaoqian** [comment]
The code written in native canvas implementation works well: 
http://jsbin.com/lupigunone/edit?html,output

> 
<body>
<canvas id='c' style = 'position: absolute; left: 0px; top: 0px;' />
<script>
  (function() {

    let htmlCanvas = document.getElementById('c');
    let context = htmlCanvas.getContext('2d');

    // Start listening to resize events and
    // draw canvas.
    initialize();

    function initialize() {
      // Register an event listener to
      // call the resizeCanvas() function each time
      // the window is resized.
      window.addEventListener('resize', resizeCanvas, false);

      // Draw canvas shapes for the first time.
      draw(window.innerWidth, window.innerHeight);
    }

    // Display custom canvas.
    function draw(width, height) {
      htmlCanvas.width = width;
      htmlCanvas.height = height;

      context.strokeStyle = 'blue';
      context.fillStyle = 'gray';
      context.fillRect(0, 0, width, height);
    }

    // Runs each time the DOM window resize event fires.
    // Resets the canvas dimensions to match window,
    // then draws the new borders accordingly.
    function resizeCanvas() {
      let width = Math.floor(window.innerWidth/2);
      let height = Math.floor(window.innerHeight/2);

      console.log(width, height);

      draw(width, height);
      //context.clearRect(0, 0, width, height);
    }
  })();
</script>
</body>
</html>

**Comment by lavrton** [comment]
You are right.
For some performance optimizations changing width and height of a stage will redraw it in async ways.
Now I think this behavior is not correct. Will fix it soon.

**Comment by lavrton** [comment]
Fixed by https://github.com/konvajs/konva/commit/37c2a777c876581c0d7d273226d301691f12b570
Will be released later.

**Comment by xuchaoqian** [comment]
@lavrton Great job! Thank you man!
