### ISSUE TITLE
Cannot find module 'konva-dev' from 'index.js'

### ISSUE THREAD

**Issue by kudlajz** [konvajs/konva#286]
Hey there, it's me again 😄 

I'm trying to use your new `konva-node` package, however, I am getting the error as mentioned in the title.

What is the `konva-dev` package supposed to be? I can't find it in the npm repository.

Thanks! 🙂

**Comment by lavrton** [comment]
@kudlajz republished. Try again.

**Comment by kudlajz** [comment]
@lavrton Now I'm getting ```ReferenceError: document is not defined``` when node is trying to load `konva`.. 😬

**Comment by lavrton** [comment]
@kudlajz try again. Reinstall latest.

**Comment by kudlajz** [comment]
@lavrton It's working great, thanks :) For anyone experiencing the same problem as me: `TypeError: Image or Canvas expected`. Remove your `canvas` dependency from `package.json` and use the one installed by Konva via `Konva._nodeCanvas` 👍
