### ISSUE TITLE
when the height too big the stage on mobile error

### ISSUE THREAD

**Issue by MvCraK** [konvajs/konva#287]
when the height > 3177 。on some mobile the canvas can't show。

**Comment by The-Punk-Programmer** [comment]
I've been having a similar issue with canvas in general on some smaller mobiles (using vanilla JS and P5.js to test - haven't started using Konva yet). It appears this might be a problem with the HTML5 canvas itself. I would be interested if anyone has more information on this issue, whether for Konva or for canvas in general. Thanks!

**Comment by lavrton** [comment]
3177px is VERY big. Probably it leads some memory issues. I think it is better to resize the image if possible. Not sure what can we do here from Konva side.
