### ISSUE TITLE
Why does't container support prepend operation?

### ISSUE THREAD

**Issue by xuchaoqian** [konvajs/konva#288]
The business logic is concerned about the insertion order of the element. But now the only way to add elements is via add() method.

I think the container is lack of FOUR important methods: prepend, last, first, next. Please consider to add them. Thank you so much.

**Comment by lavrton** [comment]
I don't think it is important. Konva already has too many API methods and I am thinking to simplify them.
You can set required zIndex after you added an element.
Or use `node.children` to access any child node.

**Comment by xuchaoqian** [comment]
Oh, I read the source code again. 

1) Collection is Array, so it has all methods of Array. This is very convenient but also very dangerous, since users may misuse them to destroy internal mechanism of Konva.

2) zindex can do my task indeed. I didn't comprehend the meaning of it clearly, because I just treated it the same as HTML zindex. 

Anyway, get helps by Konva and you man, I  save lots of time. Thank you!
