### ISSUE TITLE
Line tension property.

### ISSUE THREAD

**Issue by bensquire** [konvajs/konva#29]
Maybe this is the intended result (I'd be surprised) however the line tension property results in some odd results. Its not obvious if it actually does anything useful:

````
new Konva.Line({
    points: coordUtil.convertArrayObjectToArray(self.coordinates),
    closed: true,
    fillEnabled: false,
    stroke: self.getColour(),
    strokeWidth: self.strokeWidth,
    name: 'markup',
    tension: 0,
    drawHitFunc: function (context) {
        context.beginPath();
        context.lineWidth = 10;
        context.moveTo(self.coordinates[0].x, self.coordinates[0].y);
        _.forEach(self.coordinates, function (coordinate) {
            context.lineTo(coordinate.x, coordinate.y);
        });
        this.setStrokeWidth(10);
        context.fillStrokeShape(this);
        this.setStrokeWidth(self.strokeWidth);
    }
});
````

tension: 0,
![0](https://cloud.githubusercontent.com/assets/600237/6354529/df737bec-bc47-11e4-83a6-6cdda9f77930.png)

tension: 0.1,
![0.1](https://cloud.githubusercontent.com/assets/600237/6354530/df737ba6-bc47-11e4-8d04-1bab24370a05.png)

tension: 1,
![1](https://cloud.githubusercontent.com/assets/600237/6354531/df746750-bc47-11e4-85eb-4d7a58772bba.png)

tension: 10,
![10](https://cloud.githubusercontent.com/assets/600237/6354532/df75bd08-bc47-11e4-8673-1e4d80c96a7a.png)

I checked the Shape.Line documentation but its lacking any real detail.
Thanks!

Ben

**Comment by lavrton** [comment]
Looks like you have A LOT of points in your array. So the result is odd. Look how it works for a few number of points: http://konvajs.github.io/docs/sandbox/Quantum_Squiggle.html

**Comment by bensquire** [comment]
Thanks @lavrton your right they're is quite a few points in the array (hand drawn). I assumed the tension property would be useful for smoothing out and reducing the number of points in the shape. Do you have any suggestions on how that might be achieved? Thank you!

**Comment by lavrton** [comment]
My thoughts:
1. Take, for example, every fifth point,
2. Or use some more complex algorithms to detect "useful" points depend on their distances. (take new point if it is 5px away from previous point)

**Comment by bensquire** [comment]
@lavrton Appreciate the help, thanks!
