### ISSUE TITLE
hit detection in Safari on IOS11 not always working

### ISSUE THREAD

**Issue by everbuild** [konvajs/konva#291]
Hi,

We found an issue with hit detection in Safari on IOS11. Taps on some random shapes (but always the same shapes) sometimes don't register. I traced it down to Stage.getIntersection() not returning the tapped shape because the hit canvas doesn't contain the correct color key at the tapped position for some reason.

It can be reproduced by running the demo found on the homepage (https://codepen.io/lavrton/pen/myBPGo) on aforementioned platform.

**Comment by lavrton** [comment]
@everbuild hmm. I thought it was fixed with the last ios version. Take a look into this issue: https://github.com/konvajs/konva/issues/187. As workaround you can try to rewrite `Konva.Util.getRandomColor` function as suggested in the issue.

**Comment by abrown1982** [comment]
Im getting the same issue, pretty consistent failure in touch on random objects.  Replacing the getRandomColor method does not fix the issue at all.
