### ISSUE TITLE
Objects jumping on rerender after using absolute position data in drag events

### ISSUE THREAD

**Issue by bmoquist** [konvajs/konva#292]
Hi --- Having some troubles with the absolute position methods to move a group of objects together. The dragged object group jumps further on re-renders after a drag end event than where the object ended at the last part of the actual drag end event. Summary below with simple repo reproducing the issue.

* Objective: Move a group of objects together by dispatching Redux actions and using position information from the Redux store for rendering
* Current Approach:
  + Get the absolute position of one of the objects at drag start and the new absolute position of the same object at drag end
  + Calculate the position change (delta)
  + Dispatch the calculated delta to Redux and adjust all of the positions of the objects by the delta in the reducer
* Issue:
  + The objects on canvas jump by more than the amount dragged after the Redux update. The absolute position data doesn't appear to line up with what is rendered and how the drag actually ends.
  + For debugging, the object positions are printed to the Console and Redux Dev tools can be used to examine state.
* Basic CRA with Redux reproducing the issue 
  + https://github.com/bmoquist/konva-position-update-issue
  + Run `yarn install` in the repository local folder and then run `yarn start` -- should launch to localhost:3000
  + Debugging information in the console and Redux Dev Tools

**Comment by lavrton** [comment]
I think I see the issue. When you drag&drop a group your are changing its `{x,y}` position. Konva handle this changes automatically. When you are updating your objects, the old position of Group is still there (even if you didn't set it in `render` function).
To fix the issue you can:
1. set `x={0} y ={0}` in render function for Group
2. Or you can keep position of group (but you need to update state structure for that case).

Does it make sense?

**Comment by bmoquist** [comment]
Thanks for the help, Anton -- I implemented your suggestion to set x and y to 0 for the group (repo updated too). This substantially reduced the jumping -- however, it did not eliminate it entirely. On drag end, a small but noticeable jump back in the direction of the objects original position occurs. Do you have any other suggestions?

**Comment by lavrton** [comment]
You can get position diff from group position:
```javascript
  handleDragEnd() {
    const childPositionDelta0X = this.refs.itemsGroup.x();
    const childPositionDelta0Y = this.refs.itemsGroup.y();
    this.props.dispatch(
      updatePosition(childPositionDelta0X, childPositionDelta0Y)
    );
  }
```

Another tip: don't use this.state for properties, that you are not using in render function. Store them in instance instead. For example:
```javascript
// instead of this
this.setState(
      Object.assign({}, this.state, {
        groupStartX: this.refs.itemsGroup.getAbsolutePosition().x,
      })
    );
// use just this
this.groupStartX = this.refs.itemsGroup.getAbsolutePosition().x
```
I think you have an issue because on `dragstart` event the object is already moved, so calculation of diff is wrong.

**Comment by bmoquist** [comment]
Thanks for the pointers and suggestions -- they worked brilliantly! Using the dragstart event was the root cause of the problem in this last part as the x and y coordinates have already moved from the original position. The solution is to either to use a group with a starting point of (0,0) or to use one of the objects' initial points from the store and then calculate the corresponding difference in dragend. Thanks much for the help!
