### ISSUE TITLE
1 pixel line becomes 2 pixels line on an external display, how can I fix this?

### ISSUE THREAD

**Issue by xuchaoqian** [konvajs/konva#295]
This is corret result on my retina display:
![301511251081_ pic](https://user-images.githubusercontent.com/1064052/33060977-47d733b6-ced5-11e7-8783-2795a2474da3.jpg)

This is wrong result on my external display:
![321511251124_ pic](https://user-images.githubusercontent.com/1064052/33061027-6cde0298-ced5-11e7-85f3-9968cba52a45.jpg)

If I zoom in the wrong result, we will see the local part like this:
![331511251599_ pic](https://user-images.githubusercontent.com/1064052/33061282-86181950-ced6-11e7-9121-bd3dd2d5bc4e.jpg)

**Comment by lavrton** [comment]
@xuchaoqian  https://stackoverflow.com/questions/13879322/drawing-a-1px-thick-line-in-canvas-creates-a-2px-thick-line#13879402

**Comment by xuchaoqian** [comment]
@lavrton Thank you man! But why it works correctly on my retina display? Konvas fixed it for me?

**Comment by lavrton** [comment]
@xuchaoqian No, Konva do nothing in this case. Retina has 4x more pixels, so it looks good.

**Comment by xuchaoqian** [comment]
@lavrton Got it. 

However the page you showed doesn't work correctly on my retina disply:
![351511330359_ pic](https://user-images.githubusercontent.com/1064052/33112359-ca0ec6ba-cf8d-11e7-8e98-d6f5f70a60a6.jpg)

But it works correctly on my external display:
![361511330848_ pic](https://user-images.githubusercontent.com/1064052/33112515-9d286a24-cf8e-11e7-97db-7417612f292e.jpg)

**Comment by xuchaoqian** [comment]
Anyway, thank you very much!
Now I am sure this is one problem related to browsers not to Konva, I will figure it out myself.
