### ISSUE TITLE
Type conflict

### ISSUE THREAD

**Issue by ivan-redooc** [konvajs/konva#297]
I'm using Konva join with Ionic (angular4/cordova) but doing:

```
        let canvas = document.createElement('canvas');
        canvas.width = stage.width();
        canvas.height = stage.height();
        // creted canvas we can add to layer as "Konva.Image" element
        let image = new Konva.Image({
            image: canvas,
            x : 0,
            y : 0,
            //stroke: 'green',
            //shadowBlur: 5
        });
        layer.add(image);

```
I got this error:
Argument of type '{ image: HTMLCanvasElement; x: number; y: number; }' is not assignable to parameter of type 'ImageConfig'. Types of property 'image' are incompatible. Type 'HTMLCanvasElement' is not assignable to type 'HTMLImageElement'. Property 'align' is missing in type 'HTMLCanvasElement'.

I there another way to add the _canvas_ to the _layer_?

**Comment by lavrton** [comment]
Looks like we need to fix typescript definition for that. Quick fix:

```javascript
let canvas : any = document.createElement('canvas');
```

**Comment by ivan-redooc** [comment]
Another fix, just because  explicit may be more coherent, can be this?

In _konva.d:647_ 
```
    interface ImageConfig extends ShapeConfig {
        image: HTMLImageElement|HTMLCanvasElement;
        crop?: SizeConfig;
    }

```

**Comment by lavrton** [comment]
Yeah. That is correct fix.
You can send Pull Request if you are interested.
