### ISSUE TITLE
changing attribute of a single Shape affects all shapes in the layer

### ISSUE THREAD

**Issue by yossi-shasho** [konvajs/konva#299]
When I create two custom shapes in a layer, e.g.
```js
import Konva from 'konva'

var shape1 = new Konva.Shape({...})
var shape2 = new Konva.Shape({...})
layer.add(shape1)
layer.add(shape2)
```

Now the following code will enable stroke for both shapes, and not just for `shape1` like intended.
```js
shape1.strokeEnabled(true)
layer.draw()
```
The same issue repeats in other shape functions, not just `strokeEnabled`. Am I doing something wrong?

using Konva 1.7.6

**Comment by lavrton** [comment]
@yossi-shasho please provide a demo. You can use this as starting point: http://jsbin.com/sewekataxi/edit?js,output

**Comment by yossi-shasho** [comment]
Sure:
http://jsbin.com/ruvozaz/edit?js,output

Notice how after 1 second, using setTimeout, an outline is added to the 2nd shape. but as you can see, both shapes get an outline as a consequence.

**Comment by lavrton** [comment]
That is because your `sceneFunc` was not 100% correct. You need to call `ctx.beginPath` before drawing a new shape.

http://jsbin.com/qepukobuka/1/edit?js,output

**Comment by yossi-shasho** [comment]
Thanks!!
