### ISSUE TITLE
Synchronize the animation of several sprites

### ISSUE THREAD

**Issue by developer-av** [konvajs/konva#301]
Hi.
How can I synchronize the animation of several sprites?

**Comment by lavrton** [comment]
@developer-av how do you want to synchronize them?

**Comment by developer-av** [comment]
@lavrton process all sprite in one func, don't fork setTimeout
If we have many sprites, they will be out of sync
I'm trying to [synchronize](https://user-images.githubusercontent.com/15675868/34463036-5d8dcd66-ee59-11e7-91f0-c866f82e104e.png) the destruction of gems in a match 3

**Comment by TimonLukas** [comment]
If your sprites have the same frame rate, you can use this snippet, it works pretty well until synchronization is implemented:

```javascript
const sprites = this.getSprites()
sprites.map(sprite => {
    sprite.anim.setLayers(sprite.getLayer())
    sprite.anim.start()
})
this.interval = setInterval(() => {
    sprites.map(sprite => {
        const index = sprite.frameIndex(),
            animation = sprite.getAnimation(),
            animations = sprite.getAnimations(),
            anim = animations[animation],
            len = anim.length / 4

        if (index < len - 1) {
            sprite.frameIndex(index + 1)
        } else {
            sprite.frameIndex(0)
        }
    })
}, 1000 / this.sprite.frameRate())
```

But you could of course alter this to support different frame rates relatively easily.

**Comment by developer-av** [comment]
Thx, but i going to pixijs

**Comment by lavrton** [comment]
I am closing the issue for now.
