### ISSUE TITLE
getPointerPosition and Scaling+Panning

### ISSUE THREAD

**Issue by uahic** [konvajs/konva#303]
Hi there,

getPointerPosition does not reflect if there is a scale/translate-transform on the stage. Is this a wanted behavior for some reason or just a missing feature? 

Thank you :)

**Comment by lavrton** [comment]
That may be an interesting feature.

**Comment by RoamingAnt** [comment]
+1
Currently having to do the transformation anytime i need the actual XY coordinates.

` const pointerPos = stage.getPointerPosition()
const mousePointTo = {
    x: (pointerPos.x / stagePosition.scale) - (stagePosition.x / stagePosition.scale),
    y: (pointerPos.y / stagePosition.scale) - (stagePosition.y / stagePosition.scale),
}`

**Comment by skworden** [comment]
@RoamingAnt can you please share how you defined stagePosition

**Comment by weiyuanC** [comment]
@lifedup I'm wondering the code you posted only handle zooming right? This is because when I pan, the x and y value do not change. They will remain 0,0 unless I zoom the stage.

**Comment by lavrton** [comment]
Take a look into this demo https://konvajs.org/docs/sandbox/Relative_Pointer_Position.html

I think it covers the use case of the current issue. So I will close it for now.
