### ISSUE TITLE
Write an article that will explain offset property

### ISSUE THREAD

**Issue by lavrton** [konvajs/konva#304]
There a lot of confusion about `offset` property. Sometimes people confuse it with `position` property.

We need to write an article that will explain at a deep level how it works and how it affects rotation.

**Comment by jasie** [comment]
I totally second that, good catch.

**Comment by thuc101** [comment]
hi, see my demo of offset
https://plnkr.co/edit/sSQotg?p=preview
fun...

**Comment by lavrton** [comment]
Made my first attempt on writing this post.

It is here: https://konvajs.github.io/docs/posts/Position_vs_Offset.html

It is a draft and may have many typos. Let me know if you see ways to improve it.

**Comment by Guria** [comment]
It was surprise for me that unlike position works in opposite direction. Is it expected behaviour? Haven't found it in docs

**Comment by catanon** [comment]
I feel the same way about the direction. Did you find any rationale behind it?
