### ISSUE TITLE
Moving nodes does not involve transformations?

### ISSUE THREAD

**Issue by uahic** [konvajs/konva#305]
When creating a shape, moving it inside a sibling group, transforming it there (dragging or changing its size) and finally moving it back, its position and size gets 'resetted' => the respective transforms which are probably stored on the containers are not taken into account. 

In the implementation of (moveToTop,...) in Node.js it seems there are not transforms involved indeed;  I think it depends very much on the use-case if that behavior is desired or not but at least I found it a bit unexpected (this is why i post it here), but maybe it would break other things if there would be transforms inside of the moving operation.

**Comment by lavrton** [comment]
@uahic can use, please, gave an example and your scenario?
