### ISSUE TITLE
Blurred pixels when using scale

### ISSUE THREAD

**Issue by rafaelalmeidatk** [konvajs/konva#306]
I've tried using the `scale` function on the stage but its content becomes blurred as the scale gets bigger (probably because of the AA). Albeit this behaviour is expected to common images, it is very annoying and unviable when working with pixelated images. I was expecting to have a property to toggle this behavious but I didn't found anything.
Demo: http://jsbin.com/fiseyuwoxi/edit?html,js,output

I tried these solutions but none of them worked:
- http://jsfiddle.net/AbdiasSoftware/TYUUJ/
- http://jsfiddle.net/namuol/VAXrL/1459/

**Comment by lavrton** [comment]
```javascript
// important do that AFTER you added layer to a stage
const nativeCtx = layer.getContext()._context;
nativeCtx.webkitImageSmoothingEnabled = false;
nativeCtx.mozImageSmoothingEnabled = false;
nativeCtx.imageSmoothingEnabled = false;
```
http://jsbin.com/jugulumopu/1/edit?js,output
