### ISSUE TITLE
How do I open multiple pictures?

### ISSUE THREAD

**Issue by ThreeGold233** [konvajs/konva#307]
How do I open multiple pictures by Konva?

When I open a picture, and then open another picture, the first picture will become the second, but the width and height remain unchanged。

**Comment by lavrton** [comment]
@ThreeGold233 please give more info.

**Comment by ThreeGold233** [comment]
I use the code to open the local picture：
`function getFileUrl(sourceId) {
        let url;
        if (navigator.userAgent.indexOf("MSIE") >= 1) { // IE
            url = document.getElementById(sourceId).value;
        } else if (navigator.userAgent.indexOf("Firefox") > 0) { // Firefox
            url = window.URL.createObjectURL(document.getElementById(sourceId).files.item(0));
        } else if (navigator.userAgent.indexOf("Chrome") > 0) { // Chrome
            url = window.URL.createObjectURL(document.getElementById(sourceId).files.item(0));
        }
        return url;
    }

    function preImg(sourceId, targetId) {
        let url = getFileUrl(sourceId);
        let imgPre = document.getElementById(targetId);
        imageObj.src = url;
    }`
but when I open the second picture, the first picture will disappear.
The first open image:
![image](https://user-images.githubusercontent.com/25970075/34144788-16655eca-e4ce-11e7-9888-c2a7422b283f.png)
The second open  image:
![image](https://user-images.githubusercontent.com/25970075/34144814-38453d6c-e4ce-11e7-8d6e-c2c8dd4813ea.png)

**Comment by lavrton** [comment]
The question is for StackOverflow.
