### ISSUE TITLE
How can i make a sprite's transparency invisible ?

### ISSUE THREAD

**Issue by Pi-Bouf** [konvajs/konva#308]
Hello ! :D
First, i will say thank you ! For all this huge "konva.min.js" ! It's really awesome and it help me a lot !

So... I have a question !
I make a tile based game, and tile work with drawHitFromCache, so transparency is not a problem, i can click on each tile without click on other.
But my character is a sprite and when he is on tile, tile can't be selected... Because drawHitFromCache work, but the sprite is frozen !

I have try drawPerfectEnabled, but no... have you some ideas ?

Tu resume: how to make drawHitFromCache (for the click through transparency) and keep my animation ?

Thank you ! :D

**Comment by lavrton** [comment]
Hmmm. I think Konva doesn't support caching for Sprites. But your use case is totally valid. Need to think how to implement it.

**Comment by Pi-Bouf** [comment]
I haven't found a solution... BUT ! My sprite width and height was too big, so i reduce it, it "solve" my problem !

**Comment by Pi-Bouf** [comment]
Have you fix this bug ? :)
