### ISSUE TITLE
perfectDrawEnabled for Konva.Line

### ISSUE THREAD

**Issue by jthrilly** [konvajs/konva#31]
Any chance of supporting 'perfect draw' on line objects? Is it already there?

I am using Konva.Line to draw a convex hull polygon around some other shapes. I need a large stroke width to ensure the convex hull always fully encapsulates the shape (without adding expensive logic calculations).

```
            var poly = new Konva.Line({
              points: hullPoints,
              fill: color,
              stroke: color,
              lineJoin: 'round',
              lineCap: 'round',
              tension : 0.7,
              strokeWidth: 60,
              perfectDrawEnabled : true,
              closed : true
            });
```

![screen shot 2015-02-27 at 20 38 38](https://cloud.githubusercontent.com/assets/1387940/6420729/a9e87e70-bec0-11e4-8f7b-d19f8cc7d21c.png)

**Comment by lavrton** [comment]
Should be already there: http://jsbin.com/supaxu/1/edit

**Comment by jthrilly** [comment]
Thanks. I tracked down the issue. It turns out that using rgba values for stroke and fill color causes this effect. If I don't use alpha channel colors and just set the object opacity, things work as expected.

Thanks again! Great work with the fork by the way...I'm so glad you took it on.
