### ISSUE TITLE
Memory leak, I guess

### ISSUE THREAD

**Issue by developer-av** [konvajs/konva#313]
Hi, if I'm wrong, I'm sorry
konvajs v. 1.7.6
1. create stage
2. take heap snapshot
3. We click on the canvas region a lot of times
4. [take heap snapshot](https://user-images.githubusercontent.com/15675868/34462956-69aaa602-ee57-11e7-9687-aacd9b095c3c.png) and comparison with snapshot 1
5. force garbage collector and take heap snapshot
6. [comparison with snapshot 1](https://user-images.githubusercontent.com/15675868/34462989-ef7ab0e2-ee57-11e7-9b20-133d28843526.png) i have + 107 array, + 10 Object, etc

[code](http://jsbin.com/furonejuvu/edit?html,js,output)

**Comment by lavrton** [comment]
I can't reproduce. Looks ok to me. Can't be something not related to Konva? Like extensions?
