### ISSUE TITLE
why layer.getIntersection always null

### ISSUE THREAD

**Issue by thuc101** [konvajs/konva#314]
rect.on("dragmove", function() {
        var x = rect1.getX();
        var y = rect1.getY();
        var R = rect1.getClientRect();
        var chk = layer.getIntersection({
            x: x,
            y: y
          })
        var A = {
          x: x,
          y: y
        }
        msg('dragmove : ' + JSON.stringify(A) + JSON.stringify(R) + chk);
      });

I make Plunker at https://plnkr.co/edit/CEyI4w?p=preview
and I want to ask why layer.getIntersection always null?
thank you.

**Comment by lavrton** [comment]
For performance reasons, hit graph is disabled when you drag&drop. In 99% cases, getIntersection is used for getting shape under the pointer. In that case, it will be always dragging shape.
If you really need `getIntersection` you can move a shape to another layer on `dragstart`
