### ISSUE TITLE
How can i cancel the contextmenu event on group mousedown

### ISSUE THREAD

**Issue by iceafish** [konvajs/konva#316]
this is the demo code:

`
const stage = new Konva.Stage({
  container: 'container', width: 300, height: 300
});

const layer = new Konva.Layer();
stage.add(layer);

const rect1 = new Konva.Rect({
  width: 100,
  height: 100,
  fill: "red"
});
const group1 = new Konva.Group();
layer.add(group1);
group1.add(rect1);

group1.on('mousedown', (evt) => {
  if (evt.evt.button === 2) {
    console.log('group group');
    evt.cancelBubble = true;
    evt.evt.preventDefault();
    evt.evt.cancelBubble = true;  
  }
});

stage.on('contentContextmenu', (evt) => {
  console.log('stage stage');
  evt.evt.preventDefault();
});

layer.draw();
`

the console log is: 
`
"group group"
"stage stage"
`

when the group1 catch the mouse event, how can i stop it bubble. Or is there a problem with my usage？

**Comment by iceafish** [comment]
@lavrton please help me, thx a lot.

**Comment by lavrton** [comment]
@iceafish all `content` events are out of event bubbling flow. So `contentContextmenu` will be fired in any case. You canceled `mousedown` on group in this case `mousedown` will be not fired on stage.
