### ISSUE TITLE
Individual exports missing from NPM package

### ISSUE THREAD

**Issue by DonGissel** [konvajs/konva#317]
Hey there,

We're trying to use Konva in a setup using Gulp, Rollup and Bublé, and importing Konva in its entirety works fine, if one discounts the immense size difference in payload. However, importing just parts of Konva (either through CommonJS or ES6-syntax) and leaving out the rest isn't an option at the moment, since the entire codebase is exported as one large module with no subparts readily available for consumption. Ideally I'd want to do something like:

```
import { Circle, Rect } from 'konva';
const something = new Circle([...]);
```

or even:

```
import Circle from 'konva/src/shapes/Circle';
import Rect from 'konva/src/shapes/Rect';
const something = new Circle([...]);
```

Instead of this, as it is now:

```
import konva from 'konva';
const something = new konva.Circle([...]);
```

Completely atomizing the code would allow us to trim our bundles for maximum efficiency (`Circle` and `Rect` add up to just 2.7KB of code, pre-gzip, excluding common dependencies), instead of delivering a boatload of JS that the user will never touch anyway, but which the browser still has to download and parse. Loading individual components might be possible by parsing the TS-file instead, but including and parsing a single TypeScript-file in an ES6-based project will lead to a lot more headache for the end users (namely the programmers having to use Konva).

There's hardly any libraries on NPM that do not employ atomized code (hell, even GSAP has it), and RxJS or datefns is a prime example of splitting done well. It doesn't seem an unfair request that Konva should follow suit. :-)

**Comment by te1** [comment]
Have you seen this? https://github.com/konvajs/konva#4-minimal-bundle

It's not exactly what you asked for but it achieves similar goals and has reduced file size for me in the past.

**Comment by lavrton** [comment]
@DonGissel yeah, I know this is important. I and have this feature in my to-do list. But currently, that is not a priority for me, because it is not required in my projects.

I am thinking how to make it good. Any suggestions or PR are welcome.

And as @te1 mentioned this approach https://github.com/konvajs/konva#4-minimal-bundle is a good workaround.

**Comment by DonGissel** [comment]
Cool, thanks guys! Importing the core and the required extras might be a viable solution for now, so I'll try that first. Moving to a fully modular structure would be awesome, but I agree that it's a big task. I'll file a PR with you if I get the time. :-)

**Comment by DonGissel** [comment]
Update: importing the core and adding the various assets individually seems to work like a charm. I would still like to see a fully modular structure, so only the necessary code gets included, but this is a lot better than nothing.

Also: I was wrong about GSAP. Their NPM package is quite a lot worse than this, actually. For shame.

**Comment by lavrton** [comment]
Closing the issue for now as https://github.com/konvajs/konva#4-minimal-bundle solves the issue.
