### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by CoderHar** [konvajs/konva#319]
hello there
  im encountering an issue while i use react-konva with my application.

i have used the following code after npm installation of react-konva  but while i run the app it shows document is not defined
![image](https://user-images.githubusercontent.com/34229360/34823370-20805b9c-f6f0-11e7-998e-a34313963e7c.png) 

![screenshot_1515668768](https://user-images.githubusercontent.com/34229360/34822628-994be3be-f6ed-11e7-977a-47aae326ecb0.png)

and one more thing When i change **render(<App />, document.getElementById('root'))** to a simple export statement **export default App** 
it shows the following error
![screenshot_1515669592](https://user-images.githubusercontent.com/34229360/34823172-7e2c19da-f6ef-11e7-9d1f-4a85a7115867.png)

**Comment by CoderHar** [comment]
![image](https://user-images.githubusercontent.com/34229360/34823370-20805b9c-f6f0-11e7-998e-a34313963e7c.png)

**Comment by lavrton** [comment]
@CoderHar, What is your environment? `react-native`? If so it will not work. `react-konva` supports only browser environment.

**Comment by CoderHar** [comment]
@lavrton yeah it's React-Native and thanks for letting me know this,
would you mind suggesting any good animation package or framework for react-native

**Comment by lavrton** [comment]
@CoderHar currently I have no experience with react-native.
