### ISSUE TITLE
Create an initial change log (from KineticJS to KonvaJS)

### ISSUE THREAD

**Issue by m1erickson** [konvajs/konva#32]
Thanks for taking up authoring of KineticJS in the form of KonvaJS!

Could you create an initial log showing the changes occurring from the forked version of KineticJS to the first version of KonvaJS? 

This change log would help orient all of us who were familiar with KineticJS.

**Comment by lavrton** [comment]
I think the current chengelog is very clear about this: https://github.com/konvajs/konva/blob/master/CHANGELOG.md
right?
