### ISSUE TITLE
Transformer

### ISSUE THREAD

**Issue by skworden** [konvajs/konva#323]
I saw the [transformer.js](https://github.com/konvajs/konva/blob/master/src/shapes/Transformer.js) file was added and I tried it out but there are a few issues.  It seems to be working okay and it's definitely a great start, well done so far.

I have a elements inside of a group that the transformers attach to.  Since they are in a group the rotation x,y are way off as they appear to be based off of the stage x,y. 

If the stage is zoomed and you drag an anchor point the element moves as it scales.

The rotations are also insanely fast and not really usable at that speed but the most important thing is that they rotate off center and should rotate from center. They also seem to not snap to the correct position with a setting like `rotationSnaps: [0, 90, 180]` .

The selection box and anchors don't take the stroke of the targeted element into account as they overlap the element.

It would be nice to also be able to disable the rotation.  

It would also be nice to have rotation and resizeEnabled be disabled and retain the selection box.

I'd personally like to have the option to be able to add some sort of padding to the group (the anchors overlap and make it hard to see small items) and be able to style the selector (line color and width), anchor points (size,hover,mouse pointer, and color).

Here is an example is someone wants to hack around with it. (might not completely work since i had to remove a lot of my custom stuff but it should be really close).

````
const stage = new Konva.Stage(...your_options);

const layer = new Konva.Layer(...your_options);

const circle= new Konva.Circle({
    radius: 20,
    fill: 'yellow',
    stroke: 'black',
    strokeWidth: 4,
    draggable: true
});

layer.add(circle);
stage.add(layer);
stage.draw();

function destroyTransformers() {
    var transformers = stage.find("Transformer");
    for (var n = 0; n < transformers.length; n++) {
        transformers[n].destroy();
    }
    //don't redraw if there aren't active transformers
    if (transformers[0] != null) {
        layer.batchDraw();
    };
}

function createTransformater(target) {
    const transformer = new Konva.Transformer({
       //all available options with their default values
        keepRatio: false,
        resizeEnabled:true,
        rotaionsSnaps:[],
        rotateHandlerOffset:50
    });
    transformer.attachTo(target);
    layer.add(transformer);
    layer.batchDraw();
}

stage.on('click tap', function (e) {
    destroyTransformers();
    createTransformater(e.target);
});

**Comment by lavrton** [comment]
Many features requested in this issue are resolved.
