### ISSUE TITLE
Critsism on the data model in konva

### ISSUE THREAD

**Issue by uahic** [konvajs/konva#324]
Hi, 

after working for a while with konva I would like to point something out that comes in my way over and over again which is namely how the data model is coupled with the visuals.

Imagine having a rather complex application like an editor to manipulate let's say paths. Depending on the settings, the zooming-level and especially the currently choosen tool, one would like to use different visualizations to manipulate the underlying paths (Arrays of coordinates (x,y) ).

I found konva rather non-intuitively to use since the konva objects are kind of a object-oriented non-global representation of the data. In a polygonline for example you have to decompose it into single lines and copy over all of their visual stylings if you the user has for example choosen a tool to manipulate the coordinates within such a polygonline. It would be much simpler to have a dedicated array of coordinates and you just draw the whole thing new if something changes (yep not so performant, to mention one drawback). But the handling in the codebase should be simpler.

In lets say a redux canvas you could 'just' exchange the drawing functions to get another visual output/mouse handlers. I wonder if there isnt a compromise like having object oriented renderes and datamodel splitted. Of course I could build a custom data model and synchronize it with konva Shapes but that feels ... wrong and is overhead.

What do you guys think?

**Comment by lavrton** [comment]
I am not sure I got your issue. Can you give an example or  something like this?

But as I understand you can just use `react-konva` (or react + svg). It will map your `state` to visual representation.
