### ISSUE TITLE
fillLinearGradientEndPoint

### ISSUE THREAD

**Issue by davidm-public** [konvajs/konva#326]
Hi, firstly, thanks for an excellent project!!

My question:
Am struggling to understand the logic for Arc fill gradients?
How exactly do fillLinearGradientStartPoint and fillLinearGradientEndPoint control the gradients?

thanks
David

**Comment by lavrton** [comment]
It just draws a gradient from your starting point to end point.
the start point and the end point should be relative to Arc position. So {x:0, y:0} means center of the arc.

https://jsbin.com/lemavihoci/edit?js,output
