### ISSUE TITLE
Underlying canvas can have floating point values

### ISSUE THREAD

**Issue by uahic** [konvajs/konva#328]
I've got one layer that shows a large image (like 1024x768) and another layer on top to visualize some custom tools, basically interactive stuff.

Now, I need to 'export' the tool-layer as a bitmap and to do that I would like to read-out the underlying canvas as CanvasRenderingContext2D.getImageData(...). However, If I do query the very same context it gives some numbers like [921.599975..., 691.......]  so a bit smaller than the stage and non-integer numbers (this is where getImageData complaints).  Note: the context has always this size, no matter if the tool has added some shapes or not (as it should be). Before exporting, however, I perform caching

@lavrton 
I do not know how Konva operates on all its internal canvas elements, therefore I would like to ask if this is simply a bug or if I need to do it in another way.

Thank you :)

**Comment by lavrton** [comment]
Looks like it is because of caching. I was trying to avoid floating numbers in caching (to be correct in `getClientRect()` function), but it creates some other bugs.

So you can:
1. Avoid caching
2. Use caching but with your own x, y, width and height attributes.
