### ISSUE TITLE
" TypeError: 'undefined' is not a constructor (evaluating 'new Konva._nodeCanvas')  konva.js:29" in Safari

### ISSUE THREAD

**Issue by abdullah1971** [konvajs/konva#330]

**Comment by lavrton** [comment]
I need a demo. Probably the issue fixed with some previous "node-vs-browsers" fixes.

**Comment by t1t2t3t4** [comment]
I have solution of this issue and fixed it at my end. below is complete variable where error appearing

 var canvas = Konva.isBrowser
        ? Konva.document.createElement('canvas')
        : new Konva._nodeCanvas();

isBrowser  function is not detecting Safari.  Add safari detecting code there, it will start working

e.g  decalare this 

var is_safari = navigator.userAgent.toLowerCase().indexOf('safari/') > -1;

then go to isBrowser  function and update it for Safari

isBrowser:
      is_safari || typeof window !== 'undefined' &&

**Comment by lavrton** [comment]
@t1t2t3t4 is what safari it doesn't work for you? It works ok for me.
