### ISSUE TITLE
Can't set height or width after applying filter even after setting height or width can't apply filter on image

### ISSUE THREAD

**Issue by abdullah1971** [konvajs/konva#332]
If I set height or width or both and then try to apply filter like brightness, noise, mask etc then it shows me following error:

 Konva error: Unable to apply filter. Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation konva.js:29

alternatively, if I first apply filter and then try to set height or width then nothing changes.

for your help, i debuged to find where the problem, i found that when i calling layer.draw(), then this type of error are happening.

**Comment by lavrton** [comment]
`Out of memory`? What is a size of your image?

**Comment by abdullah1971** [comment]
size: 104 KB
dimension: 1000x500

**Comment by lavrton** [comment]
Can you provide a demo?

**Comment by lavrton** [comment]
Closing for now. If you have more info, please provide.
