### ISSUE TITLE
Fill opacity / transparency without affecting stroke

### ISSUE THREAD

**Issue by thomasdarvik** [konvajs/konva#333]
Hello, I am currently making an application where I use Konva. I want to set the fill opacity (transparency of the fill) without affecting the stroke / border. Is this possible with the current shapes, such as Rect and Ellipse? Otherwise I will have to make new shapes with a combination of lines and rectangles, which seem really unnecessary. It this by design, or a missing feature?

Ref Konva docs:
https://konvajs.github.io/docs/styling/Opacity.html

**Comment by lavrton** [comment]
You can. Just use rgba values for `fill` property. For instance: `fill: rgba(255, 0, 0, 0.5)`
