### ISSUE TITLE
Add kerning support

### ISSUE THREAD

**Issue by EugeneSqr** [konvajs/konva#334]
Current implementation does not support custom kerning tables. It relies on browser's implementation instead. Having full control over font kerning allows to render texts the same way across all browsers.

Take a look at this [jsfiddle](https://jsfiddle.net/3ct0e6sd/1/). It displays the same text three times (from top to bottom):
- kerning disabled with css (no konvajs)
- kerning enabled with css (no konvajs)
- kerning is always enabled, when browser supports it (with konvajs)

Here is how this jsfiddle looks in different browsers:
1. Chrome, Firefox, Safari. Pay attention to the difference in distance between "A" and "V"
![chrome-kerning-depends-on-css](https://user-images.githubusercontent.com/1623068/35911376-b7591214-0c0a-11e8-99b9-1741f65ed44f.png)
2. IE. The distance is the same no matter what.
![ie11-no-kerning-no-matter-what](https://user-images.githubusercontent.com/1623068/35911494-00dfd3dc-0c0b-11e8-96f0-51d6649c0a4d.png)

**Comment by lavrton** [comment]
Closed by https://github.com/konvajs/konva/pull/337
