### ISSUE TITLE
Cancel all active dragging when going outside stage

### ISSUE THREAD

**Issue by kenanchristian** [konvajs/konva#335]
Hi, if you try to drag the anchor outside the stage on this demo https://konvajs.github.io/docs/sandbox/Modify_Curves_with_Anchor_Points.html when I go back without holding down the mouse button the anchor still sticks to the cursor.

How can I make the anchor didn't stick after I go outside the stage?

**Comment by lavrton** [comment]
```javascript
var dragNode;
stage.on('dragstart', (e) => {
  dragNode = e.target;
})
stage.on('dragend', (e) => {
  dragNode = null;
})
stage.on('contentMouseout', () => {
  if (dragNode) {
    dragNode.stopDrag();
  }
})
```
