### ISSUE TITLE
About the font-weight

### ISSUE THREAD

**Issue by dicklwm** [konvajs/konva#336]
Text can only set the fontStyle but can not set the fontWeight, I want to set the Text to 200 weight or other. 
How can I do ?

**Comment by lavrton** [comment]
`fontStyle: '200'`

https://jsbin.com/bukuyotehi/edit?js,output

**Comment by KimBum** [comment]
> `fontStyle: '200'`
> 
> https://jsbin.com/bukuyotehi/edit?js,output

Can we somehow get this updated in documentation. It currently only states that classic semantic font styles/weights as examples. Would hate for people to have to google, and find this issue like me 🙏
