### ISSUE TITLE
Incorrect element receiving mouse events

### ISSUE THREAD

**Issue by miscalc** [konvajs/konva#34]
The example can be found here: [https://github.com/miscalc/logic-builder](https://github.com/miscalc/logic-builder)

While attempting to drag the second element (OR) the third element (NOT) always receives the event. 

* I have tested with Kinetic 5.1.0 as well and it has the exact same behavior.

* This behavior existed before I added the "cloneFunc" and had the draggable property set to true on each of the shapes.

* I've tried renaming the elements to see if this was a namespace conflict, which did not work.

* When I change the order that the elements are loaded into the layer (loading NOT first), it works until you drag/clone another element before the NOT gate. Example: After adding NOT to the layer first, drag the first element (AND), then drag the third element (NOT). When attempting to drag the cloned AND the event is received by the cloned NOT.

* I've tried putting each element in a different layer and the NOT gate exhibits different behavior in that it infinitely clones across the screen where the others do not.

**Comment by lavrton** [comment]
You need to `context.beginPath()` at NOT shape (https://github.com/miscalc/logic-builder/blob/master/js/logic.js#L109). Otherwise it will fill previous shape.

**Comment by miscalc** [comment]
I thought it might be user error.  Thank you for finding it :)
