### ISSUE TITLE
Pixelate filter produces black boxes on mixed alpha areas

### ISSUE THREAD

**Issue by albertogasparin** [konvajs/konva#340]
When an image contains transparent pixels and we apply the Pixelate filter, the alpha channel of a pixelated area with mixed alpha values is black out instead of being semi-transparent. 
[See this jsbin for an example of the issue](http://jsbin.com/yuzohitohe/edit?html,js,output).

Looks like the bug is the result of the missing normalisation of the alpha channel ([as the filter does for the other channels](https://github.com/konvajs/konva/blob/master/src/filters/Pixelate.js#L82)). By adding:

```js
alpha = alpha / pixelsInBin;
```

The filter correctly returns a semi-transparent block.

**Comment by lavrton** [comment]
That makes sense. Anyone interesting in a Pull Request?

**Comment by albertogasparin** [comment]
Done, see #344
