### ISSUE TITLE
clipFunc not working with Path2D

### ISSUE THREAD

**Issue by SuperNiceDev** [konvajs/konva#343]
Hi Konva Team,
unfortunately clipFunc is not working with Path2D.
I did a small codepen to visualize:
https://codepen.io/anon/pen/jZGNJW

**Comment by lavrton** [comment]
Looks like our current implementation of clipping doesn't allow usage of Path2D.

Is it really required for you?

I have only one very stupid workaround:

```javascript
function getCtxFunc() {
  return (ctx) => {
    // clip with ultra large area first (like no clip)
    ctx.arc(150, 120, 7000, 0, Math.PI * 2, false);
 
    // then clip with path
    const path2D = new Path2D();
    path2D.rect(70, 70, 120, 80);
    ctx._context.clip(path2D);
  }
}
```

**Comment by SuperNiceDev** [comment]
Thank you so much for your reply. This workaround seems to work for us. Maybe someday you find time to implement it :)

**Comment by yinguangyao** [comment]
@lavrton Using `ctx.fill(Path2D) `, the fill color drawn is always black

https://codesandbox.io/s/nostalgic-payne-pqr02u?file=/src/index.js
