### ISSUE TITLE
Any possibilities to temprary disable dragging in event?

### ISSUE THREAD

**Issue by MaxGraey** [konvajs/konva#349]
I'll just show you an example of a idea:

```js
let stage = new Stage({
  ...
  draggable: true,
});

stage.on("dragstart", e => {
  if (e.evt.shiftKey) {
    e.cancelBubble = true; // <-- not helping
    console.log('don\'t drag in this case!');
  } else {
    console.log('start normal drag');
  }
});
```

There are ideas how to do it correctly?) Thanks!

**Comment by lavrton** [comment]
```javascript
circle.on('dragstart', (e) => {
  if (e.evt.shiftKey) {
    circle.stopDrag();
    console.log('don\'t drag in this case!');
  } else {
    console.log('normally drag');
  }
})
```
http://jsbin.com/yeredocuco/1/edit?js,console,output

**Comment by MaxGraey** [comment]
Thanks! But one issue: if move mouse quickly stop happening not immediately and one or two ticks pass to shape that slightly move last one anyway.

**Comment by MaxGraey** [comment]
It will be perfect has something like 'beforedragstart' event.

**Comment by MaxGraey** [comment]
After source code inverigation I found trickly solution:

```js
let stage = new Stage({
  ...
  draggable: true,
  dragBoundFunc: function (pos, e) {
     return e.shiftKey ? this.getAbsolutePosition() : pos;
  }
});
```

**Comment by sarim** [comment]
> After source code investigation I found tricky solution:
> 
> ```js
> let stage = new Stage({
>   ...
>   draggable: true,
>   dragBoundFunc: function (pos, e) {
>      return e.shiftKey ? this.getAbsolutePosition() : pos;
>   }
> });
> ```

this seems like the most sensible solution. Applied it for now. But for my case its a bit tricky, I have a draggable parent group, then I also have small draggable circle shapes over it. I wanted to pass down the drag event to parent group when I disable dragging the circle.

**Comment by lavrton** [comment]
@sarim  like this?

```js
circle.on('dragstart', e => {
  circle.stopDrag();
  circle.getParent().startDrag();
});
```

**Comment by sarim** [comment]
@lavrton Thanks, I applied your solution and it seems to be working.

```js
      var onCircleDragStart = (e) => {
        if (!e.evt.ctrlKey) {
          e.target.stopDrag();
          mapGroup.startDrag();
        }
      }
```
circle is created dynamically at various points. then I attach the handlers.
```js
circle.on('dragstart', onCircleDragStart);
```

It is working, but sometimes I guess there a very vert small delay when passing drag event from `circle` to parent `mapGroup`. But its negligible.
