### ISSUE TITLE
[Suggestion] Viewport culling 

### ISSUE THREAD

**Issue by MaxGraey** [konvajs/konva#351]
It will be great if Stage or special class like Viewport has object culling inbox capability. For now it little bit complicated to implement over existing architecture, because node should have BBOX (```getClientRect``` do it) and boundary circle (not provided) for fast checking in/out of viewport, also we should provide checking routine after changed position and remove/add or show/hide nodes from view. 
Thoughts?

**Comment by igorcouto** [comment]
I'm also trying to make something like that. As we are using redux for render reconciliation, is not so difficult to check if element must be visible or not, but my question is: how can we know visible area of stage?

**Comment by lavrton** [comment]
@MaxGraey can you give an example scenario? Why `getClientRect` is not enough?

**Comment by MaxGraey** [comment]
> can you give an example scenario? Why getClientRect is not enough?
Yes, for huge number of particles (size constant, but has rotation & scale) or for huge number of objects which often rotates. For suck of kind objects boundary box calculation and checking costs much bigger than for circle in rectangle test.

**Comment by lavrton** [comment]
I am closing the issue. I don't see how we can implement it inside Konva core. Probably a user can make such functionality manually.
