### ISSUE TITLE
Missing `globalCompositeOperation` in Typescript Definition

### ISSUE THREAD

**Issue by oott123** [konvajs/konva#362]
Hi,

I found that `globalCompositeOperation` is missing in `konva.d.ts`, neither configs nor getter/setters.

Is that file maintenance manually or generated by scripts ? Can you add it or give some instructions so that I can open a pull request for you?

Thanks.

**Comment by lavrton** [comment]
`konva.d.ts` is created manually.

Just update it with correct edits and make Pull Request.

**Comment by oott123** [comment]
Thanks, I'd glad to send a PR to fix this. I'll update and make a PR in 2 days.
