### ISSUE TITLE
Context.imageSmoothingEnabled = false does not exist

### ISSUE THREAD

**Issue by sarthak-saxena** [konvajs/konva#366]
Disabling image smoothening in canvas, basically set anti-aliasing to false does not exist.

Example for Anti Aliasing - 
![sample_code_aa](https://user-images.githubusercontent.com/9450414/37594508-55beafc2-2b9b-11e8-949f-f4ea2780183d.jpg)
Anti-aliasing is required when we want to do pixel-wise manipulation in image editing

I was able to achieve it by getting canvas element form DOM & then,
```
var canvas = //get canvas element from DOM
var context = canvas.getContext('2d')
context.imageSmoothingEnabled = false
// Reference Link - https://developer.mozilla.org/enUS/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled
```

A built-in method to achieve this does not exist in Konva!

**Comment by lavrton** [comment]
There is no official API yet.

But here is a workaround:
```js
var ctx = layer.getContext()._context;
ctx.imageSmoothingEnabled = false;
```

Demo: http://jsbin.com/dokixarema/2/edit?js,output

**Comment by sarthak-saxena** [comment]
Thanks @lavrton.
Closing this issue then
