### ISSUE TITLE
Add keyboard accessibility for Section 508 Compliance

### ISSUE THREAD

**Issue by carlosandrews** [konvajs/konva#367]
I like this framework but it doesn't support keyboard accessibility when used with an html image map. 

For section 508 compliance, an interface must be able to be used with a keyboard by itself.

**Comment by lavrton** [comment]
I am not sure what can we do here from `Konva` part. Probably it is possible to make it accessible with some manual keyboard bindings.

I will close the issue for now. Feel free to add more info and use cases in the comments, so we can think how to resolve the issue.
