### ISSUE TITLE
Question: how to get the raw buffer ?

### ISSUE THREAD

**Issue by natcl** [konvajs/konva#368]
Hello,
I'm using konvas inside nodejs and I would like access to the raw buffer (canvas.toBuffer('raw') Is this possible ?
Thanks !

**Comment by lavrton** [comment]
There is no public API for that. But I think you can do this:

```js
// get native canvas
const canvas = layer.getCanvas()._canvas;

// get buffer
const buffer = canvas.toBuffer('raw');
```
