### ISSUE TITLE
How can I  realize pictures scrolling in the canvas with the mouse scrolling？

### ISSUE THREAD

**Issue by stupid2013** [konvajs/konva#370]
such as the title,
How can I  realize pictures scrolling in the canvas with the mouse scrolling？
by listening the Konva.Image's on('wheel') events?
but what should i do in the callback ?

**Comment by lavrton** [comment]
Hi. Sorry. I don't get it.

What do you mean by "realize pictures scrolling"? Do you want to scroll a stage? Do you want to move a picture by the wheel?

**Comment by stupid2013** [comment]
yeah, I want to move a picture by the wheel !!!

**Comment by lavrton** [comment]
```
node.on('wheel', e => {
  node.move({
    x: e.evt.deltaX,
    y: e.evt.deltaY
  });
  layer.batchDraw();
});
```

http://jsbin.com/kozifewiqo/edit?js,console,output

**Comment by stupid2013** [comment]
thanks!
