### ISSUE TITLE
findOne performance improvement

### ISSUE THREAD

**Issue by seethroughtrees** [konvajs/konva#371]
I noticed that `findOne()` completes the entire search then returns the first value.  

https://github.com/konvajs/konva/blob/514e60122b63d5f309e004cb967868bbaf135c9a/src/Container.js#L208 

In my case, I'm iterating through large trees, and would benefit from escaping the search immediately after I found a result.  (at least with function as an argument).

feels like others would benefit from it too.  is it worth me putting together a PR that escapes the `findOne` function iterator after the first true result is returned?

**Comment by lavrton** [comment]
Yes. That would be super useful!

**Comment by seethroughtrees** [comment]
Fixed in #375 .  Good to close.
