### ISSUE TITLE
Shadows on svgs rendered incorrectly in Safari

### ISSUE THREAD

**Issue by LaughlinJames** [konvajs/konva#372]
Hello all,

I am noticing that my images, which are svgs are being rendered differently in Safari than they are on Chrome.  You can look at this fiddle in the two browsers and see what I mean: https://jsfiddle.net/LaughlinJames/k0ww5x8z/

In Chrome:
![screen shot 2018-03-25 at 2 32 16 pm](https://user-images.githubusercontent.com/118043/37879150-64bd0418-3039-11e8-931e-3ebb7499b7ad.png)

In Safari:
![screen shot 2018-03-25 at 2 45 59 pm](https://user-images.githubusercontent.com/118043/37879239-415eb7a8-303b-11e8-8655-78f15f33f877.png)

If you know what I'm doing wrong, I'd really appreciate a nudge in the right direction.

Thanks.

James.

**Comment by lavrton** [comment]
I don't think we can do anything here from Konva part. You may try to fix SVG file somehow or change it to PNG.

Another workaround: add rectangle under the image and add shadow to it.

But this image in not working in Firefox at all. 😕
