### ISSUE TITLE
Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-9.5) is negative.

### ISSUE THREAD

**Issue by stupid2013** [konvajs/konva#374]
my demo is based on [editable text](https://konvajs.github.io/docs/sandbox/Editable_Text.html) and [
image resize](https://konvajs.github.io/docs/sandbox/Image_Resize.html). 
But I've got some trouble on the resize。

I create a group like this
<img width="555" alt="qq20180326-123944 2x" src="https://user-images.githubusercontent.com/16302439/37887162-d837ca18-30f2-11e8-99c7-7851091239bf.png">
<img width="555" alt="qq20180326-124004 2x" src="https://user-images.githubusercontent.com/16302439/37887164-df1b546c-30f2-11e8-8351-b36641e4af6f.png">

but i got an error when i resize it： Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-9.5) is negative.
![qq20180326-124320-hd](https://user-images.githubusercontent.com/16302439/37887271-69abec36-30f3-11e8-9db4-1cc8211c2a6e.gif)

Did I do something wrong？

**Comment by lavrton** [comment]
Please create a small reproducible demo. Probably error is happening because of negative width or height.

**Comment by eoghanmccarthy** [comment]
This error just occurred for me too. In my case it happened because I had given the shape a cornerRadius value greater than 0. Then when I flipped the shape on either axis by transforming over itself, the error occurs.

So, in my case, I just removed the cornerRadius value.

**Comment by lavrton** [comment]
@eoghanmccarthy how did you flip it? Negative width or height? Negative scale?

**Comment by eoghanmccarthy** [comment]
@lavrton Negative width/height

**Comment by lavrton** [comment]
For now, just don't use negative `width` and `height`.  Instead, use a negative scale.

**Comment by deadcoder0904** [comment]
This happened to me when `urlbar.width` went to `199` while setting it like:

```tsx
<Rect width={urlbar.width - 200} />
```

To solve it, I had to add a check if it goes below `0`, then set the `width` to `0`:

```tsx
<Rect width={urlbar.width - 200 < 0 ? 0 : urlbar.width - 200} />
```

**Comment by printmycopy** [comment]
ds

**Comment by printmycopy** [comment]
how do i set width and height on transform i searched for it and also implemented some but facing issues
