### ISSUE TITLE
Unexpected spline shape updated with `setPoints`

### ISSUE THREAD

**Issue by doodlewind** [konvajs/konva#378]
Hi, I'm working with a "curve editor" that draw curve passing through all user clicked points.

`Line` works nice with predefined points array, while with dynamically added points, I'm not sure if `setPoints` is the recommended approach. The resulting line does not pass points in the middle. See [Plunker](http://plnkr.co/edit/Kd5YZdVT78FGDALmG9Fu?p=preview) for a live reproduction. The code snippet looks like below:

``` js
const { Stage, Layer, Circle, Line } = Konva

const stage = new Stage({ container: 'container', width: 640, height: 480 })
const points = []
const layer = new Layer()
const line = new Line({
  stroke: 'black', points, bezier: true, tension: 0.5
})
layer.add(line)

stage.on('click', () => {
  const { x, y } = stage.getPointerPosition()
  points.push(x, y)

  // Update line points here.
  line.setPoints(points)

  const circle = new Circle({
    x, y, radius: 5, fill: 'red', stroke: 'black'
  })
  layer.add(circle)
  layer.draw()
})
stage.add(layer)
```

Am I missing something? Thanks.

**Comment by lavrton** [comment]
Looks like `Konva` is not updating its internals because points array is still the same, so `Konva` skip updating.

As a workaround - pass a new array:

```
line.setPoints(points.concat());
```

**Comment by doodlewind** [comment]
@lavrton thank, this works! Another confusing point is that `setPoint` is not found in [Line documentation](https://konvajs.github.io/api/Konva.Line.html), is this method internal or private?

**Comment by lavrton** [comment]
@doodlewind in the documentation only overloaded versions of methods.

`line.points()` is the same as `line.getPoints()`
`line.points(array)` is the same as `line.setPoints(array)`
