### ISSUE TITLE
methods for scale to fit

### ISSUE THREAD

**Issue by seethroughdev** [konvajs/konva#379]
I have a fixed size stage with dragging/zoom enabled.

*example: a 500x500 stage, with a layer that is 1000x1000 at scale === 1*

I would like to build a button to position and scale the canvas to fit all visible layers on the screen.

```
   stage.setScale({
     x: 0.5,
     y: 0.5,
   })
```

But I'm struggling to find any available methods to calculate the actual size of the layer to do this.  (all methods seem to return max of the stage, which is `500`, where i'm looking for `1000`).

Should there maybe be a `getAbsoluteSize` method for layers?  Curious if there is already a pattern or set of methods for something like this, and if not, and its needed, i'm happy to help.

**Comment by lavrton** [comment]
You can try to use this:

```js
const box = layer.getClientRect({ relativeTo: stage });
const { width, height } = box;
```

**Comment by seethroughtrees** [comment]
For anyone who wants to scale to fit in stage.  I created 2 functions, 1 to get sizes, and 1 to do the moving.  I already knew the biggest layer, but you might have to `stage.getLayers()` and iterate to get the largest dimension.

``` javascript
fitToScreen = () => {
    // get layers
    const nodesLayer = stage.findOne('#nodesLayer')
    const layerSize = nodesLayer.getClientRect({
      relativeTo: stage,
    })

    // calculate sizes
    const stageSize = stage.getSize()
    const scaleX = stageSize.width / layerSize.width
    const scaleY = stageSize.height / layerSize.height
    const scaleValue = u.min(scaleX, scaleY) * 0.9

    // move canvas
    u.moveStage(stage, { x: 0, y: 20 }, { x: scaleValue, y: scaleValue })
  }

export const moveStage = ( stage,  location,  scale) => {
  const { x, y } = location
  const tween = new Konva.Tween({
    duration: 0.35,
    easing: Konva.Easings.EaseInOut,
    node: stage,
    onFinish: () => {
      tween.destroy()
    },
    scaleX: (scale && scale.x) || 1,
    scaleY: (scale && scale.y) || 1,
    x,
    y,
  })

  tween.play()
  stage.batchDraw()
}

```

Hope it helps.

**Comment by annjawn** [comment]
any tips on how to do this in React?
