### ISSUE TITLE
How to ingreted custom fonts with Konva in nodejs environments?

### ISSUE THREAD

**Issue by cactis** [konvajs/konva#38]
Hi, how to ingreted custom fonts(local fonts in server's folder or google web fonts) with Konva in nodejs environments?

thanks for your help~

**Comment by lavrton** [comment]
Hi. You shoud find this in `node-canvas` example:
https://github.com/Automattic/node-canvas/blob/master/examples/font.js

This demo work for me:
```javascript
var fs = require('fs'),
    Konva = require('../dist/konva-dev'),
    Font = require('canvas').Font,
    path = require('path');


// Create stage. Container parameter is not required in NodeJS.
var stage = new Konva.Stage({
    width : 200,
    height : 100
});

var layer = new Konva.Layer();
stage.add(layer);

function fontFile(name) {
  return path.join(__dirname, '/Ubuntu/', name);
}

var font = new Font('Ubuntu', fontFile('Ubuntu-Regular.ttf'));
font.addFace(fontFile('Ubuntu-Bold.ttf'),   'bold');
font.addFace(fontFile('Ubuntu-Italic.ttf'), 'normal', 'italic');
font.addFace(fontFile('Ubuntu-BoldItalic.ttf'), 'bold', 'italic');


var text = new Konva.Text({
    text : 'Go!',
    x : 0,
    y : 0,
    fontSize : 100,
    fill : 'black',
    fontFamily : 'Ubuntu'
});
layer.add(text);
layer.draw();

stage.toDataURL({
    callback: function(data){
        var base64Data = data.replace(/^data:image\/png;base64,/, '');
        fs.writeFile('out.png', base64Data, 'base64', function(err) {
           err && console.log(err);
           console.log('See out.png');
        });
    }
});
```

**Comment by mageprashant** [comment]
@lavrton How to add custom fonts with Konvajs?

**Comment by lavrton** [comment]
Browser or nodejs?

**Comment by mageprashant** [comment]
@lavrton Browser

**Comment by WangCao** [comment]
@lavrton How to add custom fonts with Konvajs in nodejs?

**Comment by WangCao** [comment]
> Browser: https://konvajs.org/docs/sandbox/Custom_Font.html Node: see my message above.

nodejs not work

**Comment by WangCao** [comment]
in nodejs,canvas can read local font files and registerFont, but it cannot be associated with konvajs, as if the two have nothing to do with each other

**Comment by lavrton** [comment]
@WangCao can you please make a repo to reproduce the issue?

**Comment by WangCao** [comment]
`const { registerFont } = require("canvas");
const path = require("path");
const Konva = require("konva");
const fs = require("fs");

registerFont(path.join(__dirname, "fonts", "字魂50号-白鸽天行体.ttf"), {
  family: "字魂50号-白鸽天行体",
});
registerFont(path.join(__dirname, "fonts", "MI Lan Pro_Light.otf"), {
  family: "MI Lan Pro_Light",
});

const stage = new Konva.Stage({
  width: 800,
  height: 600,
});

const layer = new Konva.Layer();
stage.add(layer);

// 添加文字
const text1 = new Konva.Text({
  x: 50,
  y: 100,
  text: "Hello, World!",
  fontSize: 50,
  fontFamily: "字魂50号-白鸽天行体",
  fill: "red",
});

const text2 = new Konva.Text({
  x: 50,
  y: 200,
  text: "Welcome!",
  fontSize: 40,
  fontFamily: "MI Lan Pro_Light",
  fill: "green",
});

layer.add(text1);
layer.add(text2);
layer.draw();

let dataURL = stage.toDataURL().replace(/^data:image\/png;base64,/, "");
fs.writeFile(`hahaha.png`, dataURL, "base64", function (err) {
  console.log(err);
});`. @lavrton

**Comment by lavrton** [comment]
I tried a similar code. It works ok for me. Please make a full repo with all the code.

**Comment by mageprashant** [comment]
@lavrton We need to load a font locally.

```
var fontId = 'font-111';
var myFont = new FontFace(fontId, 'url(../media/fonts/'+ fontId +'.ttf)');
console.log(myFont);
myFont.load().then(function(font) {
    document.fonts.add(font);
    console.log('Font loaded');
});

setTimeout(() => {
    textObj.fontFamily(fontId);
}, 500); 
```

so possible like this?

**Comment by lavrton** [comment]
@mageprashant I never tried such an approach with `new FontFace`. I was adding fonts directly into CSS into the page.
It will probably work. It is better to use font loading detection instead of `setTimeout`

**Comment by juergengunz** [comment]
@WangCao had the same issue. downgrading canvas to v2.10.2 solved it for me

**Comment by mageprashant** [comment]
@lavrton We need to load font when I change fonts dropdown so how to do that?

**Comment by mageprashant** [comment]
@lavrton How to change the default font?

**Comment by mageprashant** [comment]
@lavrton and also I have created css file and added this code.

```
@font-face {
  font-family: 'font-365';
  src: url('https://test.com/media/fonts/font-365.ttf') format('truetype');
}

@font-face {
  font-family: 'font-94';
  src: url('https://test.com/media/fonts/font-94.ttf') format('truetype');
}

var textNode = new Konva.Text({
        text : 'Test Code',
        fontSize : 20,
        fill : '#0000',
        fontFamily : 'font-94',
        x: 100,
        y: 50,
        align: 'center',
});
```

but it's not working so can you please help me?

Thank you

**Comment by lavrton** [comment]
Make online demo. Are you waiting for the font loading?

**Comment by mageprashant** [comment]
Yes

**Comment by soapproject** [comment]
This is an old issue but I want to share how I successful load custom font on both client and server (because it cost me some times to find out solution...)

```typescript
export const RED_THRESHOLD = 250;
export const CANVAS_SIZE = 500;
export const FONT_SIZE = 160;
export const FONT_FAMILY = 'Cubic11';
export const DEMO_TEXT = 'AABBABC';

export async function initStage(container?: HTMLDivElement | null) {
  const stage = new Konva.Stage({
    container,
    width: CANVAS_SIZE,
    height: CANVAS_SIZE,
  } as any);
  const drawLayer = new Konva.Layer();
  if (typeof document !== 'undefined') {
    // frontend
    await document.fonts.load(`1rem ${FONT_FAMILY}`);
  } else {
    // backend
    // You can't import node-canvas at frontend, so we have to dynamic import it here.
    const canvas = await import('canvas');
    const fontPath = path.join(process.cwd(), 'public/fonts', 'Cubic_11.ttf');
    canvas.registerFont(fontPath, { family: FONT_FAMILY });
  }
  const textNode = new Konva.Text({
    fill: 'red',
    text: DEMO_TEXT,
    fontSize: FONT_SIZE,
    fontFamily: FONT_FAMILY,
  });
  drawLayer.add(textNode);
  stage.add(drawLayer);
  stage.batchDraw();

  const ctx = drawLayer.getContext();
  const imageData = ctx.getImageData(0, 0, CANVAS_SIZE, CANVAS_SIZE);
}
```

And don't forget to load font into your css.
```css
@font-face {
  font-family: 'Cubic11';
  src: url('/fonts/Cubic_11.ttf') format('truetype');
  font-display: swap;
}
```
