### ISSUE TITLE
Improve text hit detection for mobile devices (both iOS and Android)

### ISSUE THREAD

**Issue by EugeneSqr** [konvajs/konva#385]
Small and medium texts (up to 20px) are too hard to hit on mobile devices. There are two texts [in the following example](https://jsfiddle.net/s1ds6gh7/24/): the top one is rendered with Konvajs, the bottom one is just a regular html text. Try tapping them one after another multiple times (10 times for each should be enough); an alert should popup on each successful hit.

You should notice that the canvas text produces less alerts. Small canvas texts (size of 10px) are almost impossible to hit on a phone, while the similar html ones remain clickable. This is not the same as #291, it affects both iOS and Android on phones and tablets.

When navigation in an app is done with text elements, users expect them to react as hyperlinks in html. Frequent misses makes it really annoying.  Is there a way to make both texts somewhat equal in terms of hit detection?

**Comment by lavrton** [comment]
I am not sure how hit detection works for HTML elements. Probably browsers increase it somehow.

You can overwrite default behavior of Konva nodes with `hitFunc` property: https://konvajs.github.io/docs/events/Custom_Hit_Region.html. For the `Konva.Text` node you can draw a bigger hit rectangle.
