### ISSUE TITLE
cancelBubble can't working

### ISSUE THREAD

**Issue by stupid2013** [konvajs/konva#387]
this is my code:
```javascript
const stageNode =new  Konva.Stage(...);
const imageNode = new Konva.Image(...);
stageNode.on('mouseover', () => {
        imageNode.on('wheel', (e) => {
          e.cancelBubble = true;
          imageNode.move({
            // x: e.evt.deltaX,
            y: e.evt.deltaY, 
          });
          stageNode.batchDraw();
        });
      });
```
but it seems that `e.cancelBubble = true;` didn't work . and konva version is the latest.

**Comment by lavrton** [comment]
@stupid2013 can you provide a demo? I tried this http://jsbin.com/wivoyerexe/edit?js,console,output, works as expected.

Why you are adding event inside another event?

**Comment by stupid2013** [comment]
@lavrton my fault... actually, my project is based on react-konva and konva... this is my demo repo in github: [https://github.com/stupid2013/react-canvas-demo](url)  you can clone it and try. the main codes of konva is in component>canvas-demo~~ thanks a lot!

**Comment by lavrton** [comment]
Do you mean this part of code?

```
stageNode.on('wheel', (e) => { // 滚动图片
        e.cancelBubble = true;
        imageNode.move({
          // x: e.evt.deltaX,
          y: e.evt.deltaY,  // 上下滚动
        });
        stageNode.batchDraw();
      });
```

What exactly do you want to cancel? `cancelBubble` is for canceling Konva event bubbling.
If you want to cancel native DOM events you may use `e.evt.stopPropagation()`

**Comment by stupid2013** [comment]
@lavrton I tried, it didn't work...

**Comment by lavrton** [comment]
I will close issue for now.

If you still have a question, please make a small demo.
