### ISSUE TITLE
Shadow doesn't work for svg image in edge

### ISSUE THREAD

**Issue by tirli** [konvajs/konva#390]
[Demo](http://jsbin.com/tixugababi/edit?html,js,output)

Shadow replace the whole image in Microsoft Edge 41.16299.371.0

**Comment by lavrton** [comment]
Looks it is Edge bug and we can do nothing with it. Only wait for a fix.

As a workaround, we can draw an image twice: http://jsbin.com/qebitobocu/edit?html,js,output

**Comment by tirli** [comment]
Thank you for response and good idea
