### ISSUE TITLE
[Feature request] grid system for stage + snap to grid

### ISSUE THREAD

**Issue by mihaiserban** [konvajs/konva#394]
Would be interesting to add some built it functionality to the stage, or as a separate component to enable a grid system, and most importantly a snap to grid/align with other elements. 
Any thoughts? Do you see this as an additional feature to konvajs or something external?

**Comment by mihaiserban** [comment]
Agree with you, it might not be a good fit in the Konva core codebase.
I don't have a demo yet.. if i do manage to implement it i'll share it 👍🏻

**Comment by navono** [comment]
Look forward to the demo.

**Comment by Dabnis** [comment]
see a demo here : https://codepen.io/pierrebleroux/pen/gGpvxJ

**Comment by sololance** [comment]
@lavrton any update for a demo on Konva website? Thanks.

**Comment by lavrton** [comment]
Just created this demo. I hope it will be helpful. https://konvajs.org/docs/sandbox/Objects_Snapping.html

**Comment by RaiMX** [comment]
> see a demo here : https://codepen.io/pierrebleroux/pen/gGpvxJ
> 
> Not that difficult, hope it helps

How can I make draggable infinite grid?

**Comment by lavrton** [comment]
@RaiMX take a look here: https://stackoverflow.com/a/58452698/512042

It is made with `react` but I think it will be not hard to make a pure konva version.
