### ISSUE TITLE
Path2D doesn't work in `sceneFunc`

### ISSUE THREAD

**Issue by navono** [konvajs/konva#396]
reproduce [demo](https://codesandbox.io/s/zl38664mp3).

Another question is if use `Konva.Context` in `sceneFunc`, is it possible keep the `Konva` feature like `drag and drop`?

I set the `draggble` property in `sceneFunc` with `ctx(Konva.Context)`, but it's not work.

**Comment by lavrton** [comment]
The ugly solutions is:

```javascript
    const p = new Path2D('M10,10L40,10L40,40L10,40Z');

    ctx.fillStrokeShape(shape);
    ctx._context.stroke(p);
    ctx._context.fill(p);
```

Demo: https://codesandbox.io/s/4rn6zxzk6x

I think we can implement `Konva.Path2D` shape that will work exactly for that case.  As I can see `Path2d` is still experimental. Also it is not clear how to detect bounding box of such shape.
