### ISSUE TITLE
Scaled view port can not work with mouseover( mouseenter...etc) binding event

### ISSUE THREAD

**Issue by ArsenePadthai** [konvajs/konva#397]
I have a scaled page, and I can draw some shapes on this. So far it works so good. But when I try to bind some events to my shapes, it doesnt work properly. The coordinates seem have some offset going on.

**Comment by ArsenePadthai** [comment]
I used a viewport, which will automatically scale the size of the window including the drawing area.
<meta content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no" name="viewport">

**Comment by lavrton** [comment]
Stage container is placed inside scaled `div`. For the current moment, Konva can't work with such containers.

There is an only one-way fix - remove all scaling from CSS.

**Comment by ArsenePadthai** [comment]
Thank you so much! Actual I found a hack method in konva.js,  near line 10870， inside _setPointerPosition
`var ratio=get_transform_scale();

        var x1 = null;
        var y1 = null;
        x1 = x/ratio;
        y1 = y/ratio;`

this is pretty ugly, but it works for my current problem...

**Comment by lavrton** [comment]
I opened the fix issue: https://github.com/konvajs/konva/issues/500
