### ISSUE TITLE
Documentation error: Argument type Object is not assignable

### ISSUE THREAD

**Issue by Krillko** [konvajs/konva#398]
When I use Konva Text, my editor (PHPstorm) says
"Argument type Object is not assignable to parameter type TextConfig"

Example: 

```
let data = {
"text": "Happiness",
"fontFamily": "Masqualero",
"fontStyle": "italic"
}
let konvaText = new Konva.Text(data);
```

My guess is the error is in konva.d.ts

**Comment by lavrton** [comment]
I am not sure what can we do from Konva side. I will close the issue.
