### ISSUE TITLE
cornerRadius only for specific edges

### ISSUE THREAD

**Issue by ahmedlhanafy** [konvajs/konva#400]
I was wondering is there a way to specify the edge of cornerRadius for `Rect`s, something like `cornerRadiusTopLeft`

**Comment by lavrton** [comment]
Currently it is not possible. And I don't have plans to add such support.
It will be simpler to just create custom shape with such edges.

**Comment by lavrton** [comment]
Added that feature: https://konvajs.org/docs/shapes/Rect.html
