### ISSUE TITLE
Transformer 

### ISSUE THREAD

**Issue by Jaszkowic** [konvajs/konva#401]
I'm trying out the experimental Transformer functionality following this example: https://konvajs.github.io/docs/select_and_transform/Basic_demo.html
I have a basic shape (Rectangle and Ellipse) with semi-transparent filling and opaque border stroke.
When I apply some transformation to the shapes, the border stroke is scaled (see attached images).

**Is this expected behavior? I kind of want my border stroke to stay fixed and not being scaled with the actual shape.**

```
var shape = new Konva.Rect({
    x: 300,
    y: 300,
    width: 100,
    height: 100,
    fill: '#ff000033', // Fill with transparency
    stroke: '#ffffff', // Stroke fully opaque
    strokeWidth: 2, // Fixed stroke width 
    draggable: true,
});
```

![bildschirmfoto 2018-06-05 um 14 31 52](https://user-images.githubusercontent.com/10830180/40976061-392b36c2-68cd-11e8-8db3-118d414f39f3.png)
![bildschirmfoto 2018-06-05 um 14 31 39](https://user-images.githubusercontent.com/10830180/40976062-3952910e-68cd-11e8-9f41-a8b4466260cc.png)

**Comment by lavrton** [comment]
As you can see in https://konvajs.github.io/docs/select_and_transform/Basic_demo.html notes, `Konva.Transformer` is changing scale properties. Scale effects stroke.

You have two ways to make stroke fixed:
1. reset node attributes to `scaleX = 1` and `scaleY = 1`. But adjust width and height
2. or use `strokeScaleEnabled = false` for a node
