### ISSUE TITLE
getSelfRect() not typed for TypeScript

### ISSUE THREAD

**Issue by Dampfpfeife** [konvajs/konva#404]
When using the method getSelfRect() of the Shape class with TypeScript, the compiler is complaining. Actually the method is not contained in the konva.d.ts file. After adding the line

getSelfRect(): SizeConfig;

to the Shape class definition it works fine in my system. Maybe you can update your package accordingly.

**Comment by Dampfpfeife** [comment]
I'm very sorry - I never used GIT before (always SVN), nevertheless I tried to create the pull request (after reading several related pages), but unfortunately I failed. So please insert the mentioned single line by yourself - that would be great ...

**Comment by MaxGraey** [comment]
@Dampfpfeife I create PR for this

**Comment by Dampfpfeife** [comment]
Thanks a lot ...!
