### ISSUE TITLE
Initial load of two layers displays incorrectly

### ISSUE THREAD

**Issue by wattsyourwebsite** [konvajs/konva#407]
Here is the code that shows the problem:

http://jsbin.com/yamoxa/edit?css,js,output

If you click on each of the red and blue "wedges" it loads the wheels correctly.
However I want it to load like this from the start.

Any idea if this is a bug?

Tania

**Comment by lavrton** [comment]
https://stackoverflow.com/questions/51062048/konvajs-load-issue-of-2-layers
