### ISSUE TITLE
Regression in attrs initialization flow

### ISSUE THREAD

**Issue by pronebird** [konvajs/konva#41]
Hi,

I am migrating from KineticJS to Konva and everything seems fine except some of attributes are missing on my custom subclass. I pass Kinetic.Image (aka Konva.Image) into `config.image` and it does not make it into attrs dictionary.

Looking at [THIS](https://github.com/konvajs/konva/blob/master/src/Node.js#L624) right now and thinking "You gotta be shitting me".

```javascript
// compatibility
var Kinetic = Konva;

// custom class
var Button = function (config) {
  this._initButton(config || {});
};

Button.prototype = {
  _initButton: function(config) {
    // call super constructor
    Kinetic.Group.call(this, config);
    this.className = 'Button';
  }
};

Kinetic.Util.extend(Button, Kinetic.Group);
Kinetic.Factory.addGetterSetter(Button, 'text', '');
Kinetic.Factory.addGetterSetter(Button, 'image');
```

`config` dump:

```javascript
> config
< Object
fontSize: 16
image: Object
text: "Locked"
__proto__: Object
```

`this.attrs` dump:

```javascript
> this.attrs
< Object
fontSize: 16
text: "Locked"
__proto__: Object

```

**Update:**

Changed this
```js
if (key === CHILDREN || config[key] instanceof Konva.Node) {
```

to this:

```js
if (key === CHILDREN) {
```

Problem solved. It is a very strange unimplemented part of Konva.Node.

**Comment by lavrton** [comment]
Test now. Reopen if need.
