### ISSUE TITLE
Firefox memory issues while dragging a Path with a fillPatternImage

### ISSUE THREAD

**Issue by FSidorov** [konvajs/konva#411]
Hi all,

I am trying to make something like a classical Jigsaw puzzle game and i am using an SVG path with fillPatternImage over it. On small pieces all goes smoothly, but if the pattern image is bigger (over 200x200 px for example), FF starts to leak memory while i am dragging the piece. Faster and longer you drag - more memory is being lost (and not returned back).

The newest FF and other browsers don't have this issue, but at least FF 57.0 ( release date November 14, 2017 ) does, and it is not that old to be just skipped.

That can also be reproduced in the example:
https://konvajs.github.io/docs/styling/Fill.html

If you drag the polygon with Vader long and fast enough, on a not-so-new browser, it will start leaking. Change the image to, say, 1000x1000 and it will leak 2 Gb in a few seconds.

**Comment by lavrton** [comment]
We have an issue that `Konva` is creating a new canvas pattern on each draw. I guess it the root of memory issue.

https://github.com/konvajs/konva/blob/master/src/Context.js#L518

I think we can cache it somehow.

**Comment by lavrton** [comment]
I hope memory bugs will be fixed (or already fixed) by a browser. As a solution, I suggest to cache shapes with gradients.

Closing the issue for now. But it is still interesting to implement automatic caching for a gradient.
