### ISSUE TITLE
Documentation error: fillLinearGradientColorStops vs setFillLinearGradientColorStops

### ISSUE THREAD

**Issue by mn113** [konvajs/konva#420]
The docs at https://konvajs.github.io/api/Konva.Shape.html#fillLinearGradientColorStops__anchor imply that the function mentioned is both getter and setter (setter example takes numerous arguments).

But I've seen at https://konvajs.github.io/docs/styling/Fill.html and in my own code, that you need to use setFillLinearGradientColorStops to set values (and it takes an array).

Perhaps there are some other mistakes from whenever this was changed.

**Comment by lavrton** [comment]
`shape.setFillLinearGradientColorStops(val)` and `shape.fillLinearGradientColorStops(val)` are both valid options.

For all properties we have:
1. getter `shape.getX()`
2. setter `shape.setX(val)`
3. overloaded getter/setter `shape.x(val); console.log(shape.x())`
