### ISSUE TITLE
quoted x/y values breaks draggable option on shapes

### ISSUE THREAD

**Issue by leopold-olsson-cybercom** [konvajs/konva#423]
When setting x/y on a shape using quoted values (ex: "100") draggable stops working on the shape.
example shown here: http://jsbin.com/sebahidowe/edit?html,js,output

If you remove the quotes then it starts working again as expected. Perhaps the values should be parsed to ints before applied.

**Comment by lavrton** [comment]
"100" is a string. Do not use String type for numeric properties.
