### ISSUE TITLE
Types in konva.d.ts not updated for sceneFunc and hitFunc

### ISSUE THREAD

**Issue by mlc-mlapis** [konvajs/konva#424]
There are wrong types for `sceneFunc` and `hitFunc` in `konva.d.ts` for the latest Konva 2.1.8.
```
sceneFunc?: (con: Context) => void;
hitFunc?: (con: Context) => void;
```

**Comment by lavrton** [comment]
Missing `shape` argument? Does anyone want to create a PR?

**Comment by mlc-mlapis** [comment]
@lavrton ... I can do it ... 😄 of course. Just I wasn't sure how `konva.d.ts` is generated. If it is a manual process then I do it. Is it?

**Comment by lavrton** [comment]
Yeah. It is manually created.
