### ISSUE TITLE
Blur filter causing white borders for PNG-24 images

### ISSUE THREAD

**Issue by Harti** [konvajs/konva#428]
Adding a blur filter to an image that has alpha transparency causes its border to turn light.
This is likely to the interpolator treating surrounding/empty pixels as white.

[Example JSbin](http://jsbin.com/taginijame/25/edit?js,output)
(left: 1px blur radius; right: no blur radius/filter)

![image](https://user-images.githubusercontent.com/2056108/43678651-81080d16-9817-11e8-95c5-5db9f8a2e0d2.png)
macOS, any browser

I was wondering if there is any way to work around this? Creating a PR as an outsider is pretty much impossible, considering the cryptic filter code.

Thank you so much!

**Comment by Harti** [comment]
@lavrton any idea?

**Comment by lavrton** [comment]
@Harti yeah, so the code is cryptic and I don't know how to update it too. We may try to find another algorithm or find if the current one is updated.

**Comment by lavrton** [comment]
Closing the task as not a priority. But I am happy to apply any related Pull Requests.
