### ISSUE TITLE
How to use the rotation properties of the group to rotate the group ,and reposition it exactly in Konva.js with react

### ISSUE THREAD

**Issue by sjcUD** [konvajs/konva#429]
First of all, Thank you for taking the time to answer my questions.

  I am working for an small Image Editor project, Basing on konva.js with react.But I've run into some problems，that have bothered me for few days.
I want to use the rotation properties of the group to rotate the group, and all shapes in it, it works exactly, when clicking the rotate Button. But when I click the text Button, and want to draw it on the Image, and reposition exactly, the pic2 is my expected result, but actually, I got the unexpected result show as pic3, the text run to unexpected position ,how can i do to rotate the group and all shapes in it exactly.

<img width="890" alt="firststep" src="https://user-images.githubusercontent.com/24570594/43679137-87ec26e0-9852-11e8-8f64-96bc8ee82cb6.png">

<img width="898" alt="sec_step" src="https://user-images.githubusercontent.com/24570594/43679064-109c5d7c-9851-11e8-87eb-2736fd6be965.png">
<img width="882" alt="third_step" src="https://user-images.githubusercontent.com/24570594/43679072-2fd68bea-9851-11e8-81b7-5135f0dac962.png">

 My simple example show as following:

`
import React, { Component } from "react";
import {Button} from 'antd';
import { Stage, Layer, Image, Group, Text } from "react-konva";
import Konva from 'konva';

class Test extends React.Component{

    constructor(props) {
        super(props)
        this.state = {
            historyArray: [],
            isTexting: true,
            image: new window.Image(),
            layerPos:{
                x: 300,
                y: 100,
            },
            imageWidth: 0,
            imageHeight: 0,
            rotateDegrees: 0,
        }
    }
    componentDidMount() {

        const {historyArray} = this.state;
        this.state.image.setAttribute("crossOrigin", "anonymous");
        this.state.image.src = "https://vd.youniwote.com/homework/44evmey2cbd/submit/44evmey2cbe.jpg";
        this.state.image.onload = () => {
            let imageWidth = this.state.image.width > 620 ? 620 / (parseFloat(this.state.image.height) / parseFloat(this.state.image.width)) : this.state.image.width;
            let imageHeight = this.state.image.height > 620 ? 620 : this.state.image.height;
            let imageObj = {
                mode: 'image',
                image: this.state.image,
                width: imageWidth,
                height: imageHeight,
            }
            historyArray.push(imageObj);
            this.setState({
                historyArray,
                imageWidth,
                imageHeight,
            })
        }
    }
    clickStage = (event) => {
        const {mode, isTexting, historyArray} = this.state;
        if (mode == 'text') {
            if (isTexting) {
                let textarea = document.createElement('textarea');
                document.body.appendChild(textarea);
                textarea.style.position = 'absolute';
                textarea.style.top = event.evt.pageY + 'px';
                textarea.style.left = event.evt.pageX + 'px';
                textarea.style.width = 100;
                textarea.focus();

                this.setState({
                    isTexting: false,
                })

                textarea.addEventListener('keydown',  (e) => {
                    if (e.keyCode === 13) {
                        historyArray.push({
                            mode: "text",
                            x:this.getActualPosInStage(event).x,
                            y: this.getActualPosInStage(event).y,
                            text: textarea.value,
                        })

                        document.body.removeChild(textarea);
                        this.setState({
                            isTexting: true,
                            historyArray
                        })
                    }
                });
            }
        }
    }

    getActualPosInStage = (e) => {
        const {layerPos} = this.state;
        let stageBox = this.stage.getStage().getContainer().getBoundingClientRect();
        let mousePos = {
            x: e.evt.clientX,
            y: e.evt.clientY,
        }
        let x = Math.abs(mousePos.x - stageBox.left - layerPos.x);
        let y = Math.abs(mousePos.y - stageBox.top - layerPos.y);
        return {x,y}
    }
    render() {
        return (
            <div>
                <div style={{top: 0, left: 0}}>
                    <Button onClick={() => {
                        this.setState({
                            mode: 'text',
                            groupDraggable: false,
                        })
                    }}>Text</Button>

                    <Button style={{marginLeft: 20}} onClick={() => {
                        const {rotateDegrees} = this.state;
                        this.setState({
                            rotateDegrees: rotateDegrees + 90,
                            groupDraggable: false,
                            mode: 'rotate',
                        })

                        this.group.offsetX(this.group.width() / 2);
                        this.group.offsetY(this.group.height() / 2);

                        this.group.x(this.group.width() / 2);
                        this.group.y(this.group.height() / 2);

                    }}>Rotate</Button>
                </div>
                <Stage
                    onClick={(e) => {this.clickStage(e)}}
                    width={1000}
                    height={1000}
                    ref={node => {
                        this.stage = node;
                    }}
                >
                    <Layer
                        x={this.state.layerPos.x}
                        y={this.state.layerPos.y}
                        ref={node => {
                            this.layer = node;
                        }}
                    >
                        <Group
                            rotation={this.state.rotateDegrees}
                            width={this.state.imageWidth}
                            height={this.state.imageHeight}
                            ref={node => {
                                this.group = node;
                            }}
                        >
                            {
                                this.state.historyArray.map((item, index) => {
                                    if (item.mode == 'image') {
                                        return (
                                            <Image
                                                key={index}
                                                width={item.width}
                                                height={item.height}
                                                image={this.state.image}
                                                ref={node => {
                                                    this.imageNode = node;
                                                }}
                                            />
                                        )
                                    } else if (item.mode == 'text') {
                                        return(
                                            <Text
                                                key={index}
                                                x={item.x}
                                                y={item.y}
                                                text={item.text}
                                                fontSize={24}
                                                fill='red'
                                            />
                                        )
                                    }
                                })
                            }
                        </Group>
                    </Layer>
                </Stage>
            </div>
        )
    }
}

export default Test;
`

**Comment by lavrton** [comment]
https://stackoverflow.com/a/51701140/512042
