### ISSUE TITLE
Typescript bindings not updated

### ISSUE THREAD

**Issue by gjoseph** [konvajs/konva#434]
In the changelog for 2.2.1, I see a bunch of properties have been added to TransformerConfig, and some were renamed. This doesn't seem to have been reflected in the `konva.d.ts` file.

**Comment by lavrton** [comment]
Fixed.

**Comment by gjoseph** [comment]
Thanks!

**Comment by gjoseph** [comment]
Hey there - there still seems to be a buggy type with `borderEnabled`. I'd suggest the following patch, but it looks like the js code also declares `borderEnabled` as Number!?
eg: `   * @param {Number} [config.borderEnabled] Should we draw border? Default is true`
... this should probably be `Boolean` -- but I've seen code that lets it accept the "inherit" string as well, hence the ts patch below. I've also been wondering if the magic "inherit" string would apply to other boolean properties, and if methods like borderEnabled() should also return that, or strictly a boolean ?

````
diff --git a/konva.d.ts b/konva.d.ts
index 3056e7ea..e35a5128 100644
--- a/konva.d.ts
+++ b/konva.d.ts
@@ -1165,7 +1165,7 @@ declare namespace Konva {
     rotateEnabled?: boolean;
     rotationSnaps?: Array<number>;
     rotateAnchorOffset?: number;
-    borderEnabled?: number;
+    borderEnabled?: boolean | 'inherit';
     borderStroke?: string;
     borderStrokeWidth?: number;
     borderDash?: Array<number>;
````

**Comment by lavrton** [comment]
@gjoseph you are right. Fixed. Will publish later. https://github.com/konvajs/konva/commit/cce200d1911e37bc0b4c21bf0d10a6f7b11c0f51

**Comment by gjoseph** [comment]
thanks :)
