### ISSUE TITLE
Transform issue changing stroke width

### ISSUE THREAD

**Issue by SWebDevelop** [konvajs/konva#437]
Hi,

First of all, thanks for this framework. It's awesome! Great work.

I'm dealing with a weird issue. Let me explain.

I'm using the transform functionality and works fine. But when I change the stroke width, the transform tool break. Take a look:

**Before changing stroke width:**
<img width="184" alt="screen shot 2018-08-21 at 5 06 30 pm" src="https://user-images.githubusercontent.com/3071996/44426860-363cc680-a566-11e8-9159-c21b86e2ddc1.png">

**After changing stroke with, transform tool gets bigger than shape:**
<img width="866" alt="screen shot 2018-08-21 at 5 06 45 pm" src="https://user-images.githubusercontent.com/3071996/44427014-b6632c00-a566-11e8-92d2-9145cb9eedf6.png">

Any ideas of what's the problem?

Thanks in advance.

**Comment by lavrton** [comment]
Can you make a demo?

**Comment by SWebDevelop** [comment]
@lavrton After trying to reproduce the error with no success and scratching my head... finally I found the issue.

The problem is that I was setting a string value to the strokeWidth attribute. It works fine on the shape but it breaks the transformer. Sorry, it was my bad. You can close this issue.

Thanks.

**Comment by lavrton** [comment]
Ok. Try to update `konva` to the last version. It has warnings about such issues.
