### ISSUE TITLE
Shape stroke direction

### ISSUE THREAD

**Issue by SWebDevelop** [konvajs/konva#438]
Hi,

I'm working on a web application using Konva and I have this question:

Is there a way to set the stroke width direction?

I mean, for example, I have shape that has a stroke with opacity, and I get this:
<img width="271" alt="screen shot 2018-08-21 at 6 46 28 pm" src="https://user-images.githubusercontent.com/3071996/44431009-eb757b80-a572-11e8-9009-c8a5ad5310bb.png">

I don't want half the size of the stroke inside the shape. Is there a way to change that?
I don't even know is it's possible with pure canvas.

Thanks.

**Comment by lavrton** [comment]
I see two solutions. Custom shape or two circles:

```js
// soultion 1
const shape = new Konva.Shape({
  x: 180,
  y: 60,
  stroke: 'rgba(0,0,0,0.5)',
  strokeWidth: 20,
  fill: 'green',
  draggable: true,
  sceneFunc: (ctx, shape) => {
    ctx.beginPath();
    ctx.arc(0, 0, 50, 0, Math.PI * 2, false);
    ctx.closePath();
    // first stroke
    ctx.strokeShape(shape);
    // then fill
    ctx.fillShape(shape);
  }
});
layer.add(shape);

// soulution 2
var group = new Konva.Group({
  x: 60,
  y: 180
});
layer.add(group);
group.add(new Konva.Circle({
  radius: 60,
  fill: 'rgba(0,0,0,0.5)'
}))
group.add(new Konva.Circle({
  radius: 50,
  fill: 'green'
}))
```

http://jsbin.com/zusujosaze/3/edit?js,output
