### ISSUE TITLE
Methods which return Konva.Collection have problems with generic typing

### ISSUE THREAD

**Issue by mlc-mlapis** [konvajs/konva#443]
The latest build applied PR https://github.com/konvajs/konva/pull/439 (generic typing). The problem with such partly extension just for collection `Collection<T extends Node = Node>` is that all methods which return collections need also the possibility of generic typing.

For all those methods, like `getChildren()` it is necessary to use **`as`** syntax now (`getChildren() as Shape`) and this is very limiting in chaining and other constructs.

So it would be necessary to add also generic typing for all those methods like `getChildren<T>(filterfunc?: Function): Collection<T>;` and then it would be possible to use `getChildren<Shape>().toArray()`.

**Comment by lavrton** [comment]
Anyone is interested to make a pull request for that?

**Comment by mlc-mlapis** [comment]
@lavrton ... my comment was mainly for @IgorBabkin as the author of the PR https://github.com/konvajs/konva/pull/439, but if there is a problem with it I can do it myself.

**Comment by IgorBabkin** [comment]
@lavrton @mlc-mlapis I'll fix that

**Comment by IgorBabkin** [comment]
sorry for delay
