### ISSUE TITLE
How to keep size border width of shape when resize shape with transformer?

### ISSUE THREAD

**Issue by tanobi92** [konvajs/konva#449]
When I resize a shape, then size of border width also resize. How to keep size of border width?
Before resize: 
![image](https://i.imgur.com/pCS0Lvl.png)
After resize:
![image](https://i.imgur.com/Wndw15n.png)
Help me, please! Thanks!

**Comment by lavrton** [comment]
But default `Transformer` is changing the scaling of a node. You need to change its `width` and `height` instead. Currently, there is no public API for that. But you can reset it manually:

```js
rect.on('transform', () => {
  rect.setAttrs({
    width: rect.width() * rect.scaleX(),
    height: rect.height() * rect.scaleY(),
    scaleX: 1,
    scaleY: 1
  });
})
```

http://jsbin.com/mivezutido/1/edit?js,output

But there is still small issue with calculations of position. I am not sure how bad it for you.

**Comment by tanobi92** [comment]
Hi @lavrton ,
Thank you very much! 👍

**Comment by lavrton** [comment]
Another possible solution is to set `strokeScaleEnabled: false`  to the shape.
