### ISSUE TITLE
fillPriority: combination cases

### ISSUE THREAD

**Issue by LFFATE** [konvajs/konva#452]
There are some cases, when switching filling types is not enough: 

- transparent image with colored background
- transparent gradients with... same colored backgrounds 
- etc

so, by default its "colored background" always white. 

I found a good possibility to customize that behavior and I think this should implemented by konva itself

Easiest way this:

```
      var hasPattern = shape.getFillPatternImage();
      if (hasPattern && fillPriority === 'pattern') {
        this._fillColor(shape); // add this to pattern case
        this._fillPattern(shape);
        return;
      }
```

but would be better create a combine logic: what with which should combine and at what priority, for example, from bottom to top: filling color => gradient => pattern

So we can get something like this:
![image](https://user-images.githubusercontent.com/3839490/45263766-02f0a780-b441-11e8-8469-95826a130d01.png)

**Comment by lavrton** [comment]
Interesting use case. Using both `_fillColor` and `_fillPattern` inside `fillPriority === 'pattern'` looks wrong.

Possible solution from `Konva` side can be `fillPriority('color pattern')`. But I am not sure how simple will be implementation of that API.

As workaround you may try to use two shapes. One for color and another for pattern.

**Comment by LFFATE** [comment]
> looks wrong

Sure. It's just example =)

> fillPriority('color pattern')

it's would be difficult to maintain with TypeScript (needs to specify all possible variants). Better - array instead of string

> As workaround you may try to use two shapes. One for color and another for pattern.

Not bad working example without konva source modifications, but I think it may slow down performance

**Comment by lavrton** [comment]
As your use case is very rare I am not sure we need that functionality in Konva core. But I am happy to see a pull request if it can be small and simple.

Another workaround is to draw all fills manually with private methods access:

```javascript
const circle = new Konva.Shape({
  x: stage.width() / 2,
  y: stage.height() / 2,
  radius: 50,
  fill: 'green',
  fillLinearGradientStartPoint: { x : -50, y : -50},
  fillLinearGradientEndPoint: { x : 50, y : 50},
  fillLinearGradientColorStops: [0, 'red', 0.5, 'rgba(0, 0, 255, 0.4)'],
  sceneFunc: (context, shape) => {
    context.beginPath();
    context.arc(0, 0, shape.getAttr('radius'), 0, Math.PI * 2, false);
    context.closePath();
    // draw all manually
    // warning, private methods
    context._fillColor(shape);
    context._fillLinearGradient(shape);
  },
  hitFunc: (context, shape) => {
    context.beginPath();
    context.arc(0, 0, shape.getAttr('radius'), 0, Math.PI * 2, false);
    context.closePath();
    context.fillStrokeShape(shape);
  },
  draggable: true
});
```
Demo: http://jsbin.com/zowusiyufo/2/edit?js,output
