### ISSUE TITLE
Failed to execute 'addColorStop' on 'CanvasGradient'

### ISSUE THREAD

**Issue by MrVisitor** [konvajs/konva#454]
<img width="539" alt="screen shot 2018-09-10 at 16 40 55" src="https://user-images.githubusercontent.com/7935653/45301006-9cd75380-b518-11e8-9285-947c29833e63.png">
<img width="912" alt="screen shot 2018-09-10 at 16 39 00" src="https://user-images.githubusercontent.com/7935653/45301011-a2cd3480-b518-11e8-9254-3707780bb160.png">

**Comment by lavrton** [comment]
Fixed. Thanks for the report. I will publish later.
