### ISSUE TITLE
[Feature request] support pointer events api

### ISSUE THREAD

**Issue by thebiffboff** [konvajs/konva#455]
It would be good to have support for the pointer events api to give finer grain control over touchscreen events for drawing with a stylus, differentiating between different pointer types etc. 

https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events

**Comment by lavrton** [comment]
Yeah. That is a good support.

**Comment by WrongWay** [comment]
+1 for this

**Comment by lavrton** [comment]
We have partial support for pointer events.

```js
Konva._pointerEventsEnabled = true;
```

Probably one day we will unify it with all other events types. For now, I am going to close the issue.
