### ISSUE TITLE
Stage - Resize stage or grow stage on the fly

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#458]
Hi there,

Lovely library thank you somuch for all the effort.

This is more of a question that could lead to an enahancement if the functionality doesn't already exist.

I want my Stage to be ble to grow according to the number of objects that i place into it. Typically, start at 500wX500h, add three rects 250wX250h, on the third one that i add i would like to increase the width of my stage to 750.

Is this at all possible?

Thanks again for this amazing lib

**Comment by deathblade89** [comment]
> As you control the width of the stage, you can set any value any time as you want. So just change width after you added the third rectangle.

I realised that just after i posted the issue, thanks again, much appreciated.

**Comment by deathblade89** [comment]
Hi there,

I am increasing my Stage width and height without a problem.
I have a rectangle that fills the stage and therefore changes its width and height to the same as the Stage. However, the rectangle dimensions remain unchanged.

Example code using Vue.

<template>
    <v-container fluid>
        <v-btn @click="IncreaseStageSize">Test</v-btn>
        <v-stage ref="stage" :config="configKonva">
        </v-stage>
    </v-container>
</template>

<script>
    import Konva from 'konva'

    export default {
        data() {
            return {
                backplate: null,
                configKonva: {
                    width: 1600,
                    height: 50
                },
                colours: [
                    'red',
                    'green',
                    'blue'
                ]
            };
        },
        created() {
            setTimeout(() => {
                let layer = new Konva.Layer();
                let stage = this.$refs.stage.getStage();
                let rectangle = new Konva.Rect({
                    x: 0,
                    y: 0,
                    width: 1600,
                    height: 50,
                    fill: 'lightgray',
                    stroke: '#ddd',
                    strokeWidth: 1,
                    shadowColor: 'black',
                    shadowBlur: 2,
                    shadowOpacity: 0.4,
                    draggable: false
                });
                this.backplate = rectangle;
                let rectangle2 = new Konva.Rect({
                    x: 0,
                    y: 0,
                    width: 500,
                    height: 500,
                    fill: 'red',
                    stroke: '#ddd',
                    strokeWidth: 1,
                    shadowColor: 'black',
                    shadowBlur: 2,
                    shadowOpacity: 0.4,
                    draggable: false
                });

                layer.add(rectangle);
                layer.add(rectangle2);
                stage.add(layer);
            }, 1000);
        },
        methods: {
            IncreaseStageSize () {
                this.configKonva.height = this.configKonva.height + 50;

                if (this.backplate != null) {
                    this.backplate.height = this.backplate.height + 50;
                }
            }
        }
    };
</script>

**Comment by deathblade89** [comment]
`<template>
    <v-container fluid>
        <v-btn @click="IncreaseStageSize">Test</v-btn>
        <v-stage ref="stage" :config="configKonva">
        </v-stage>
    </v-container>
</template>

<script>
    import Konva from 'konva'

    export default {
        data() {
            return {
                backplate: null,
                configKonva: {
                    width: 1600,
                    height: 50
                },
                colours: [
                    'red',
                    'green',
                    'blue'
                ]
            };
        },
        created() {
            setTimeout(() => {
                let layer = new Konva.Layer();
                let stage = this.$refs.stage.getStage();
                let rectangle = new Konva.Rect({
                    x: 0,
                    y: 0,
                    width: 1600,
                    height: 50,
                    fill: 'lightgray',
                    stroke: '#ddd',
                    strokeWidth: 1,
                    shadowColor: 'black',
                    shadowBlur: 2,
                    shadowOpacity: 0.4,
                    draggable: false
                });
                this.backplate = rectangle;
                let rectangle2 = new Konva.Rect({
                    x: 0,
                    y: 0,
                    width: 500,
                    height: 500,
                    fill: 'red',
                    stroke: '#ddd',
                    strokeWidth: 1,
                    shadowColor: 'black',
                    shadowBlur: 2,
                    shadowOpacity: 0.4,
                    draggable: false
                });

                layer.add(rectangle);
                layer.add(rectangle2);
                stage.add(layer);
            }, 1000);
        },
        methods: {
            IncreaseStageSize () {
                this.configKonva.height = this.configKonva.height + 50;

                if (this.backplate != null) {
                    this.backplate.height = this.backplate.height + 50;
                }
            }
        }
    };
</script>`

**Comment by deathblade89** [comment]
> Hi there,
> 
> I am increasing my Stage width and height without a problem.
> I have a rectangle that fills the stage and therefore changes its width and height to the same as the Stage. However, the rectangle dimensions remain unchanged.
> 
> Example code using Vue.
> 
> `
> 
> <v-btn @click="IncreaseStageSize">Test
> 
> 
> 
> <script> import Konva from 'konva' export default { data() { return { backplate: null, configKonva: { width: 1600, height: 50 }, colours: [ 'red', 'green', 'blue' ] }; }, created() { setTimeout(() => { let layer = new Konva.Layer(); let stage = this.$refs.stage.getStage(); let rectangle = new Konva.Rect({ x: 0, y: 0, width: 1600, height: 50, fill: 'lightgray', stroke: '#ddd', strokeWidth: 1, shadowColor: 'black', shadowBlur: 2, shadowOpacity: 0.4, draggable: false }); this.backplate = rectangle; let rectangle2 = new Konva.Rect({ x: 0, y: 0, width: 500, height: 500, fill: 'red', stroke: '#ddd', strokeWidth: 1, shadowColor: 'black', shadowBlur: 2, shadowOpacity: 0.4, draggable: false }); layer.add(rectangle); layer.add(rectangle2); stage.add(layer); }, 1000); }, methods: { IncreaseStageSize () { this.configKonva.height = this.configKonva.height + 50; if (this.backplate != null) { this.backplate.height = this.backplate.height + 50; } } } }; </script>`

No sure why the code isnt reflecting appropriately using the code snippet in GitHub. I will create a JS Fiddle

**Comment by deathblade89** [comment]
I am not sure why the Code Snippet tool in GitHub is not working.

I also cannot create a JS Fiddle since i am using vue-konva and JS Fiddle cannot find that module.

Is there a better way for me to explain or illustrate to you what the problem is?

**Comment by lavrton** [comment]
Use codesandbox instead. You can use this as a template https://codesandbox.io/s/github/konvajs/site/tree/master/vue-demos/basic_demo?from-embed

**Comment by lavrton** [comment]
To set a new value you should use setter:

```
this.backplate.height(newHeight);
// or
this.backplate.setHeight(newHeight);
```
