### ISSUE TITLE
transformer for elements inside group

### ISSUE THREAD

**Issue by igorcouto** [konvajs/konva#459]
hey!

Using transformer when the attached element is inside group, the node coordinates becames relative and transformer render in incorrect position.

line 261 of transformer.js

      var rect = node.getClientRect({ skipTransform: true });

can be switched to:

var rect = node.getClientRect({ skipTransform: true, relativeTo: node.getStage() });

This approach is correct? Can I submit a PR ?

**Comment by lavrton** [comment]
Currently, `Transformer` is designed in a way that it should be placed in the same parent as an attached node.

Probably we should add a warning if that is not the case.

I am not sure this line will work:
```
var rect = node.getClientRect({ skipTransform: true, relativeTo: node.getStage() });
```

Probably we will need something more complex if we want to cover that use case.
