### ISSUE TITLE
[Feature request] Add cornerRadius for each corner separately

### ISSUE THREAD

**Issue by alex9pro1** [konvajs/konva#460]
Hi!

It would be better to have a possibility add the ability to specify the radius for each corner.

Now we can set corner radius only for all corneres
```javascript
rect.cornerRadius(10);
```

I think it will be great throw down options as array or object
```javascript
var arrayWithRadiusForEachCorner = [10, 0, 10, 0];

rect.cornerRadius(arrayWithRadiusForEachCorner);
````

**Comment by lavrton** [comment]
For the simple code and API, I think we don't need that feature right now.

In case if anyone still really need it I suggest to copy/paste `Rect` shape code and update `sceneFunc` to draw different radiuses.

**Comment by lavrton** [comment]
As many people ask for that feature I decided to add it into the core code.

Demo: https://konvajs.org/docs/shapes/Rect.html
