### ISSUE TITLE
Transformer: wrong mouse pointer after transformation

### ISSUE THREAD

**Issue by Dampfpfeife** [konvajs/konva#463]
I found an issue with the mouse pointer after using transformer. It can be reproduced with the example on the "Basic Demo" page:

https://konvajs.github.io/docs/select_and_transform/Basic_demo.html

The expected behaviour is as follows: You click on one of the coloured rectangles - then the "border" with the eight resizing squares appears. When you click on one of these squares, the mouse cursor changes and indicates the direction of allowed movement. When you release the mouse button, the mouse pointer remains unchanged but goes back to the standard pointer when the pointer is moved out of the small square.
But I found that when you release the mouse button while not being located in the small square the mouse cursor doesn't go back to the standard pointer.  To reproduce it, select one of the coloured rectangles (on the demo page), press the mouse button down when being on the "south" resizing square, move the mouse a bit down and then to the right. When it is outside the square, release it. You will see that it doesn't change back to the standard mouse pointer.

**Comment by lavrton** [comment]
Thanks for the report! I will release a new version soon.
