### ISSUE TITLE
How to cut out in a shape?

### ISSUE THREAD

**Issue by tanobi92** [konvajs/konva#464]
I want cut out a shape(square, rect, eclip,...) in a shape same same the text bellowing:
![image](https://user-images.githubusercontent.com/11570162/46121335-7d8d3580-c23d-11e8-87cb-99964fc2a9ec.png)
Help me, please! Thanks !

**Comment by lavrton** [comment]
As I know there is only one way to make this picture is to use another canvas to generate a white background and cut text from it with `globalCompositeOperation = destination-out`.

```javascript
const canvas = document.createElement('canvas');
const ctx = canvas.getContext('2d');

ctx.fillStyle = 'blue';
ctx.fillRect(0, 0, canvas.width, canvas.height);

ctx.globalCompositeOperation = 'destination-out';
ctx.fillStyle = 'black';
ctx.font = "70px Georgia";
ctx.fillText('Hello', 40, 100);

const image = new Konva.Image({
  image: canvas,
  draggable: true,
  x: 20,
  y: 20
});
layer.add(image);
```

Demo: http://jsbin.com/vaqacefapu/1/edit?js,output

**Comment by tanobi92** [comment]
Hi @lavrton ,
I seen the example, but I want to use Konva :)))

**Comment by lavrton** [comment]
It is ok sometimes to use native canvas with Konva. You see, it is added into the layer as `Konva.Image`.

**Comment by monarezvani** [comment]
> As I know there is only one way to make this picture is to use another canvas to generate a white background and cut text from it with `globalCompositeOperation = destination-out`.
> 
> ```js
> const canvas = document.createElement('canvas');
> const ctx = canvas.getContext('2d');
> 
> ctx.fillStyle = 'blue';
> ctx.fillRect(0, 0, canvas.width, canvas.height);
> 
> ctx.globalCompositeOperation = 'destination-out';
> ctx.fillStyle = 'black';
> ctx.font = "70px Georgia";
> ctx.fillText('Hello', 40, 100);
> 
> const image = new Konva.Image({
>   image: canvas,
>   draggable: true,
>   x: 20,
>   y: 20
> });
> layer.add(image);
> ```
> 
> Demo: http://jsbin.com/vaqacefapu/1/edit?js,output

HI Anton, i have several shapes in layer with specific IDs and i want to draw a rectangle and cut out the interference of them,how to do that? please help
