### ISSUE TITLE
Sprite start() can be called twice but calling stop() doesn't stop the listeners

### ISSUE THREAD

**Issue by rafaelalmeidatk** [konvajs/konva#465]
I am not sure if this is the intended behavior, but here is what is going on:
1. Add a listener to a sprite:
```
sprite.on('frameIndexChange.konva', (event) => {
  console.log('framechanged');
});
```
2. Start it with `sprite.start()`, there is output on the console.
3. Stop it with `sprite.stop()`, there is no output on the console.
4. Start it with `sprite.start()` again but before calling `sprite.stop()`, call it again. Now the animation is running much faster.
5. Stop it with `sprite.stop()`, the animation stops but there is still output on the console, regardless of how much times you call `stop`.

Demo: http://jsbin.com/lupaxocime/1/edit?js,console,output

Currently, I am preventing this problem by stopping the animation before starting it, should this be on the lib?

**Comment by lavrton** [comment]
Thanks for the report! Will be released soon.
