### ISSUE TITLE
Drag Shape from one layer to another

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#467]
Hi again,

Thanks again for such an amazing library 🥇 

I would like to know how to drag one shape from Layer A to Layer B.

Example : Layer A is a toolbox. Layer B is just a placement for the Shape dragged out of Layer A.

Is this currently possible?

**Comment by lavrton** [comment]
@deart1mer you can do `layerB.add(node)` on `dragend` event. Isn't it enough? Or do you have layers in different stages?

**Comment by deart1mer** [comment]
> @deart1mer you can do `layerB.add(node)` on `dragend` event. Isn't it enough? Or do you have layers in different stages?

@deathblade89

**Comment by deathblade89** [comment]
For the time being i have only one stage, but at a later stage i will have two stages.
How would i go about it then?

**Comment by deathblade89** [comment]
@lavrton Have you ever done any planogramming using konva js?

**Comment by deathblade89** [comment]
@lavrton I also attempted to add a layer to a layer, my thinking behind that is, parent layer, childrend layers. Is my thinking incorrect?

**Comment by lavrton** [comment]
A layer can have only shapes and groups as children elements. A layer can't have children layers.


From moving from one stage into another you can you this demo: https://stackoverflow.com/questions/49254624/drag-shapes-between-two-konvajs-canvases

**Comment by deathblade89** [comment]
@lavrton Thanks alot man.
