### ISSUE TITLE
Drag objects outside of main canvas

### ISSUE THREAD

**Issue by marvin-w** [konvajs/konva#474]
Hello,

first of all thank you very much for your awesome work. I've been really enjoying using Konva in my project.

I do have a (more or less) simple question about the drag functions. Is it possible to use the drag and drop features even if the element is outside of the canvas view scope? I've added an example below using a custom transformer. We need to be able to somehow get the object back into the visible canvas and it would be best if this could be done also by drag and drop.

![image](https://user-images.githubusercontent.com/708887/46997935-672e1780-d121-11e8-9634-75ec5bee1331.png)

My first idea was to use the mousedown, mousemove and mouseup events on the custom transformer but then I struggled on how to get it back into konva.

Any ideas would be greatly appreciated.

**Comment by lavrton** [comment]
Can you make an online demo? What is outside canvas?

**Comment by marvin-w** [comment]
Hi @lavrton, thanks for responding - is it possible for you to access https://integration.kartigami.de ?

You need to click through the process though.

1. Top right button saying "Karte erstellen"
2. press the blue button in the middle
3. press the first blue button
4. press the first button
5. then, on the left sidebar are images, click in the text symbol and then on the button
6. move the added object outside of the actual canvas container - then, how would I be able to drag it again (you can reselect it with rectangle selection)

**Comment by lavrton** [comment]
if the object outside of the canvas and a user can't click on it, you can listen to `mousedown` event manually on outside area and call `shape.startDrag()` if it intersects with the mouse.

But if I would build such app I would not use "outside" canvas. So "paper" is just part of large canvas (not canvas itself).

**Comment by marvin-w** [comment]
Thank you! Yea we tried that first but unfortunetly we need to translate the whole canvas into a PDF with a special format for printing, thus requiring the coordinates to be as good as they can possibly get.

**Comment by lavrton** [comment]
"paper" part can be a moved group. So all relative coordinates of the shapes inside a group an organized correctly for later print.

**Comment by marvin-w** [comment]
thanks - I will give it another try!
