### ISSUE TITLE
Group - setX(xNewValue)

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#475]
Hi there,

When you have a group with a bunch of children within it.
Changing the Group X / Y does not move the children as well.

Simply put, if you drag a group, all child elements of the group move relative to the group.

When you set the X/Y co-ordinates of the group, all children are relative to the group container, however the shapes within do not change their co-ordinates as well.

I had to manually find all children of the group and change the X/Y co-ordinates on each child.

Is this the correct behaviour or is this something that can be enhanced?

Thanks for the amazing library again.

**Comment by lavrton** [comment]
> Is this the correct behaviour or is this something that can be enhanced?

Not, it is not correct. Can you show a demo?

**Comment by deathblade89** [comment]
@lavrton 

Sure, will do one for you first thing tomorrow morning.

**Comment by deathblade89** [comment]
@lavrton 
Sorry about this, i forgot to do a demo.

What can i use for the Vue demo again, i know you sent it in previous issue, but i forgot the link.

Will submit it ASAP - Thanks again

**Comment by deathblade89** [comment]
@lavrton 

I have shared this demo to try and illustrate the issue with moving a group progamatically:
https://jsbin.com/yodufojijo/edit?html,js,output

**Comment by lavrton** [comment]
I am closing the issue. Please add more info if you still need help.
