### ISSUE TITLE
node event - Before drag start

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#476]
Hi there,

Do you have or plan to have an event on before drag?

Currently, i have a dragstart event that i then have drag stop if i am trying to ctrl+click to clone. The time between dragstart and node.stopDrag() the node has been moved a few pixels, i would like to prevent this entirely whilst i am holding down the ctrl key

**Comment by lavrton** [comment]
Yes, I am thinking about this use case too. And now I think, can we fire `dragstart` before initial movement?

**Comment by deathblade89** [comment]
@lavrton Seems like a chicken or the egg situation :)

I think you should fire it before any movement as to provide some more control before the physical move. Your thoughts?

**Comment by lavrton** [comment]
The behavior is changed. I will make a release later.

**Comment by deathblade89** [comment]
> The behavior is changed. I will make a release later.

Thank you very much.

**Comment by greengiraffe** [comment]
Had the same issue and it drove me nuts until I figured out what was going on. The dragstart should – in my opinion – definitely fire _before_ anything is moved. Thus v2.5.0 solved the problems I had, thank you!

**Comment by deathblade89** [comment]
@lavrton,  @greengiraffe  Do i just update my npm package and the changes are working?

**Comment by lavrton** [comment]
@deathblade89 yes. Just update it.

**Comment by deathblade89** [comment]
@lavrton Thanks man, drag start event now works like a charm. Many thanks!
