### ISSUE TITLE
Images and  stage.toDataURL() - This export is corrupted

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#477]
Hi there,

Thanks again for such an awesome library 👍 

I recently managed to get export of the stage to download as an image.
This ended up not working once i added an Image to the stage.

Any suggestions?

**Comment by lavrton** [comment]
Do you see any error messages in the console? I guess you have CORS issues. Images are from another domain?

**Comment by deathblade89** [comment]
There is only a warning in the console :

![image](https://user-images.githubusercontent.com/16613924/47069522-68c61100-d1ef-11e8-9ba2-1d553a82e971.png)

The stage looks like this:
![image](https://user-images.githubusercontent.com/16613924/47069593-9743ec00-d1ef-11e8-9473-8ad90023bba5.png)

The image that is downloaded comes up with a message : It appears that we dont support this file type.

If i remove the image from my stage and export, everything works perfectly

**Comment by deathblade89** [comment]
@lavrton Any advice on this?

**Comment by deathblade89** [comment]
> Do you see any error messages in the console? I guess you have CORS issues. Images are from another domain?

I do not have CORS issues, the Image Server that i am using allows for CORS. 

As discussed in the above message, the export works fine up until I add images to my stage. If i remove the image the export works 100%.

**Comment by lavrton** [comment]
I am 100% sure that is CORS issue. https://stackoverflow.com/questions/22710627/tainted-canvases-may-not-be-exported

**Comment by deathblade89** [comment]
> I am 100% sure that is CORS issue. https://stackoverflow.com/questions/22710627/tainted-canvases-may-not-be-exported

Hi there,

Thanks for your reply.

This is the link to the image that is on a image server
http://160.119.248.41/ImageAPI/api/Image?rng=0.21703338673917627&folder=7638900&file=381610.1

Here is the code that i am using to fetch the image and place it within the stage

let group = new Konva.Group({
                        id: uid,
                        name: 'product',
                        x: 0,
                        y: 0,
                        width: width,
                        height: height,
                        draggable: true
                    })

                    var imageObj = new Image();
                    imageObj.onload = function () {

                        var productRect = new Konva.Image({
                            id: uid,
                            name: 'product_rect',
                            x: group.x(),
                            y: group.y(),
                            image: imageObj,
                            width: width,
                            height: height,
                        });

                        group.on('dragend', function (e) {
                            var target = e.target.find('.product');
                            var targetRect = e.target.getClientRect();
                            stage.find('.shelf').each(function (element) {
                                // do not check intersection with itself
                                if (element === target) {
                                    return;
                                }

                                var shelf_Area = element.find('.shelf_area')[0];
                                if (self.hasIntersection(shelf_Area.getClientRect(), targetRect)) {
                                    group.draggable(false);
                                    self.addToShelf(stage, element, group);
                                    layer.draw();
                                }
                                // do not need to call layer.draw() here
                                // because it will be called by dragmove action
                            });
                        })

                        group.on('dblclick dbltap', function () {
                            self.customEmitter.openModal(EventBus, data, "product");
                        });

                        // add the shape to the layer
                        group.add(productRect);
                        layer.add(group);

                        // add the layer to the stage
                        stage.add(layer);
                    };
                    imageObj.src = 'http://160.119.248.41/ImageAPI/api/Image?rng=0.21703338673917627&folder=7638900&file=381610.1';







*****
Please assist me with understanding this as it is hindering my exports, if there is a CORS issue, please help me to identify it :)

**Comment by lavrton** [comment]
You need this: `imageObj.crossOrigin = 'Anonymous';`.

Demo: https://jsbin.com/mohosebede/1/edit?html,js,output

**Comment by deathblade89** [comment]
> You need this: `imageObj.crossOrigin = 'Anonymous';`.
> 
> Demo: https://jsbin.com/hoyobubeke/1/edit?html,js,output

Hi again,

Thank you so much for the help, i completely misunderstood the stackoverflow solution, apologies!
The solution works great and i am once again very thankful for this amazing library!

**Comment by TopDragon523** [comment]
hello  I would like to save stage partly, rectangle  region inside stage  using toDateURL() function, 
How do to this?

**Comment by TopDragon523** [comment]
Hello Anton
Thank you for your message

**Comment by Thamaraiselvam578** [comment]
@lavrton I created a Stage with 3 Layers after I add 4 to 5 images for each layer and resized them with transformer  and export the stage using dataURI but the half bottom image gets hidden. But image doesn't overflow out of the stage.

**Comment by lavrton** [comment]
@Thamaraiselvam578 make a small demo.
