### ISSUE TITLE
Issue when using padding in the Trasformer

### ISSUE THREAD

**Issue by CosmaTrix** [konvajs/konva#479]
Hi there,

I've been adding the Transformer object to a project of mine to be able to scale up/down and rotate shapes. When I apply the Transformer to a text and I add a padding to the Transformer itself, the scaling doesn't properly work. The aspect ratio of the text is not kept, to the point that it sometimes mirrors vertically. :(
Without padding, the Transformer works as expected.

You can try it at this [Code Sandbox](https://codesandbox.io/s/309q0zz4o1) I've just created.

Moreover, there's a `console.log` somewhere in the code. Open the console in the Sandbox to see the library logging at every rotate/scale actions.

Cheers!

**Comment by lavrton** [comment]
Thanks for the report. Will investigate this asap.

**Comment by selfish** [comment]
Is there any update on this?

**Comment by lavrton** [comment]
Sorry, not yet. The fix is more complex than I expected. Not sure when I will have time to fix it. As workaround you may try to use `keepRatio: false` for `Konva.Transformer` it works better in case of padding.

**Comment by selfish** [comment]
@lavrton thanks for your reply.
We really don't want to use `keepRatio: false` so we had to remove the padding, which doesn't look great. If you want to point me at the right direction I'll check if I can create a PR

**Comment by lavrton** [comment]
I made many fixes related to `padding` for `Konva.Transformer`. `keepRatio: true` should work ok now with `konva@4.0.12`.  But there are still some issues with we have a negative scale.

**Comment by lavrton** [comment]
The bug should be fixed with `konva@5.0.0`

**Comment by chentianxin** [comment]
In konva@^8.4.2 this problem reappears
