### ISSUE TITLE
drawHitFromCache issues on retina

### ISSUE THREAD

**Issue by pronebird** [konvajs/konva#48]
Hi,

It seems that `drawHitFromCache` does not work properly anymore.

I have the following configuration:

- Group
    - Image

```js
// get image from group
var image = group.findOne('.image');

// reset offset if was previously set
image.offset({ x: 0, y: 0 });

// cache image
image.cache();

// update hit from image
image.drawHitFromCache();

// restore offset
image.offset({
  x: DRAG_STROKE_WIDTH,
  y: DRAG_STROKE_WIDTH
});

// redraw layer's hit map
this.layer().drawHit();
```

I have a retina display, but if I set `Konva.pixelRatio = 1;` then everything works as expected. I guess this issue is connected to #46

Changing hitCanvas to use the same pixelRatio helps, then the fix is the same as I used for filter canvas:

```js
context.drawImage(hitCanvas._canvas, 0, 0, hitCanvas.width / ratio, hitCanvas.height / ratio);
```
(I had to remove pixelRatio setting for hitCanvas so it could use device pixelRatio)

But hey we could probably use low-detail hitCanvas and stretch it, I guess that was the point of fixing hitCanvas at pixelRatio = 1.

**Comment by lavrton** [comment]
Right. Thanks for good bug reports about pixelRatio. I am going to fix it soon.

**Comment by pronebird** [comment]
Awesome! Thanks! I prepared a live demo for you (see links below), maybe it would give you some better understanding of what's going on. I've spent some time digging hit canvas but it's just too much code to consume in such a short time span.

jsbin: http://jsbin.com/dibuco
gist: https://gist.github.com/pronebird/80c2357f518d8e71d093

**Comment by pronebird** [comment]
It seems that drawHitFromCache is trying to render twice larger image into 1x hit context.

**Comment by pronebird** [comment]
Rendering this image with pixelRatio = 2:

```js
window.open(lion._getCachedSceneCanvas().toDataURL())
```

![index](https://cloud.githubusercontent.com/assets/704044/7120465/a5391ef0-e20d-11e4-84ba-dc97dd47e35b.png)

Snapshot of hit canvas:

```js
window.open(lion._cache.canvas.hit.toDataURL())
```

![hitcanvas](https://cloud.githubusercontent.com/assets/704044/7120467/a7db1276-e20d-11e4-93fe-217b37698e5c.png)

**Comment by pronebird** [comment]
Composition to conclude my finding:

pixelRatio = 2

![mask1](https://cloud.githubusercontent.com/assets/704044/7120753/c1788dec-e20f-11e4-9f11-48abfe5d531b.jpg)

pixelRatio = 1

![mask2](https://cloud.githubusercontent.com/assets/704044/7120754/c2a62c56-e20f-11e4-8d0d-a205b383896c.jpg)

**Comment by pronebird** [comment]
Related PR #49

**Comment by lavrton** [comment]
Can you test?

**Comment by pronebird** [comment]
I will. Although you can draw directly to hit canvas, no need to allocate temp canvas. See my PR #49

**Comment by pronebird** [comment]
I confirm that it works for me.
