### ISSUE TITLE
Transformer Border Padding While Scaling

### ISSUE THREAD

**Issue by AndrejHronco** [konvajs/konva#481]
Hi,
When scaling a shape (that has a shadowOffset or shadowBlur) with a Transformer, the transform border padding and handle padding scale with the shape. can there be an option to keep a constant padding? it starts to look weird when scaling by a large amount.

I've tried setPadding but can't figure out a desirable solution for keeping a constant unscaled padding on the border/handles.

This only seems to happen if the shape with a shadowOffset or shadowBlur.

Thank you for your work. Konva is awesome!

**Comment by lavrton** [comment]
Can you make a demo of your issue, please?

**Comment by AndrejHronco** [comment]
https://codepen.io/hronco/pres/KGexjm

when you resize, the border padding / handles scale away from the shape

**Comment by lavrton** [comment]
I think that is the bug. I made a change that should fix the bug.
Now it works in this way: https://codepen.io/lavrton/pen/bmxGWL?editors=1010
