### ISSUE TITLE
stage.getPointerPosition() - UNDEFINED (Vue)

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#482]
Hi there,

Please could you assist:  I am trying to access the position of the pointer on the stage. when i call the get function, it returns undefined.

getScaledPointerPosition() {
                let stage = this.$refs.stage.getStage();
                console.log(stage, stage.getPointerPosition())
                var pointerPosition = stage.getPointerPosition();
                var stageAttrs = stage.attrs;
                var x = (pointerPosition.x - stageAttrs.x) / stageAttrs.scaleX;
                var y = (pointerPosition.y - stageAttrs.y) / stageAttrs.scaleY;
                return {
                    x: x,
                    y: y
                };
            }

**Comment by lavrton** [comment]
When do you call this function? `getPointerPosition` may return undefined if the mouse is outside of stage and there is no active dragging action.

**Comment by deathblade89** [comment]
@lavrton 

I am not dragging at this point.

What i am trying to achieve is :

I have an external toolbox. I am then dragging the element onto the stage. At this point this is working fine, however when the stage is scaled or panned (dragged to a point) i do not know the co-ordinates of the stage so i cannot drop the element correctly.

I just want to know the mouse position relative to the stage at any given point? 

How can i achieve this?

Thanks

**Comment by deathblade89** [comment]
@lavrton 
Could i maybe achieve this by adding a mouse move event on the stage and using the event args to determine the co-ordinates relative to the stage?

**Comment by deathblade89** [comment]
@lavrton 
Hi there,

Thank you for the demo.

This however did not solve my problem.

I would like to try and explain it to you:

 * I have a html div
 * The div has drag events
 * I drag the div onto the stage
 * When i drop the div onto the stage it must create a rectangle
 * The rectangle must be placed at the exact co-ordinate relative to the stage that the drop event occured.

EG : Almost like dragging a button from a visual studio toolbox onto a form

Please could you assist?

Thanks

**Comment by lavrton** [comment]
So when you are doing this `stage.getPointerPosition()` returns undefined?

**Comment by lavrton** [comment]
Try to listen to window mousemove event. Konva doesn't track events outside of stage container (except when the drag is in action). You may calculate pointer position manually, or register it in Konva manually:

```
window.addEventListener('mousemove', (e) => {
  // register mouse in Konva
  stage._setPointerPosition(e);
  const pos = stage.getPointerPosition();
  text.text('Pointer position is ' + JSON.stringify(stage.getPointerPosition()));
  layer.batchDraw();
});
```

https://jsbin.com/qeyetiheqa/2/edit?js,output

**Comment by deathblade89** [comment]
@lavrton 

Hi there,

Please take a look at the following demo : https://jsbin.com/koxuwahude/edit?html,js,output

Things to see:
* Mouse co-ordinates do not change when dragging
* The stage is draggable, move the stage around and see that the X:Y co-ordinates do not reflect the X:Y co-ordinates of the stage (Moved to the right and down slightly, move it yourself)

**Comment by lavrton** [comment]
Here is another demo I have for you: https://konvajs.github.io/docs/sandbox/Drop_DOM_Element.html

**Comment by deathblade89** [comment]
@lavrton 

Thank you for the demo. The drop doesnt create anything in the gray area. If i yoda and drop on dark gray area, nothing happens.

Also, how would we handle the stage being draggable and scalable?
Since, you would need to place the yoda DOM element into the stage area relative to the mouse position taking into consideration the ScaleY, ScaleX of the Stage and the dragged distance so that you can create the Yoda image at the correct point on the stage with all the above considered.

**Comment by deathblade89** [comment]
> > Thank you for the demo. The drop doesnt create anything in the gray area. If i yoda and drop on dark gray area, nothing happens.
> 
> Hmm. It is working ok for me. But I changed it a bit, should work ok now.
> 
> > Also, how would we handle the stage being draggable and scalable?
> 
> You can calculate position manually or try to use demo [I posted above](https://konvajs.github.io/docs/sandbox/Relative_Pointer_Position.html).

Thank you, it is now working correctly.

I will try to use both posts and get to a working result. Will let you know.

Thank you so much for all the help 👍

**Comment by deathblade89** [comment]
@lavrton 

The solution together works amazingly for a drag drop relative solution.

Thank you for your help and efforts!
