### ISSUE TITLE
Suggestion: How to make a donation? (OpenCollective)

### ISSUE THREAD

**Issue by jonyw4** [konvajs/konva#483]
Hi @lavrton,
I need to thank you for keeping this repository, you did a great job!

As stated on the homepage of the site, many companies use Konva to create their web applications (mine too) and it would be really cool to be able to support the project so that it can stay up to date and also with a strong community.

You could open an OpenCollective account for Konva, so everyone can help you, what do you think?

**Comment by lavrton** [comment]
Thanks for the message. I will make OpenCollective a bit later.

For now, it is possible to use this: https://www.paypal.me/lavrton

Thanks, everyone for the support! 🙏

**Comment by lavrton** [comment]
https://konvajs.github.io/docs/donate.html
