### ISSUE TITLE
Attach text to shape

### ISSUE THREAD

**Issue by jonyw4** [konvajs/konva#484]
Hi guys!
I need to attach a text to a shape in Konva. Reding documentantion I find some options but I didn't find a way yet:

**Tag**
With tag we just have a Rect box, so its limitated.

**TextPath**
I thought about using this, but the path is SVG and in Shape we dont have a way to export the outer lines of shape in SVG format... 

I think that we can have a method in TextPath that attach him to a shape. And then he catch the outlines of shape and change the path automatically (like a transformer). What you think?

**Comment by jonyw4** [comment]
Oh, when I said attach i mean attach this way, but with any shape (rect, circle, polygon):
![images](https://user-images.githubusercontent.com/14056669/47793988-427b9780-dcfe-11e8-8290-dbd21535ff02.png)

**Comment by lavrton** [comment]
`Konva` doesn't have any built-in ways to attach a Text to the Shape.

But `TextPath` should work just fine for your case. You just need to manually generate SVG path for your shape. And that path will depend on the type of the shape.

**Comment by lavrton** [comment]
I do not see any elegant solutions to have in Konva core. There are too many ways how you can "attach" text into the shape. Inside/outside of the shape, with or without padding, on what side of the shape (bottom, right, left, top?), etc.
