### ISSUE TITLE
strokeScaleEnabled is not calculating Shape width/height correctly

### ISSUE THREAD

**Issue by bensteers** [konvajs/konva#486]
I would expect the stroke of the rect to stay lined up with the border of the transformer when scaling, but it is shifting as if strokeScaleEnabled was not enabled.

Here's an example: https://jsbin.com/xopiyusisu/edit?html,js,output

**Comment by bensteers** [comment]
after Googling around, it seems like this might just be a quirk of canvas scale transforms and the way strokeScaleEnabled is [implemented](https://github.com/konvajs/konva/blob/1c863ae389d880409f2b99e95c63620f9e0c1bf3/src/Context.js#L624), (correct me if I'm wrong). So I'm not sure if this issue easily fixable using scaling. 

One solution that I had would be to add a flag to the Transformer which, instead of using scaleX and scaleY, could directly apply the scaling to the width and height of the shape. This wouldn't fix this issue for shapes scaled in other ways, but maybe it's less of an issue for people who aren't using transformers anyway?

e.g. looking at [this line](https://github.com/konvajs/konva/blob/d15c530520c012b3304ce2625ec73ab1e69f9759/src/shapes/Transformer.js#L648)
```javascript
if(this.directScalingEnabled()) { // or whatever it should be called
  // no scaling happening here
  this.getNode().setAttrs({
    width: newAttrs.width,
    height: newAttrs.height,
    // scaleX: 1, scaleY: 1,
    x: newAttrs.x - (dx * Math.cos(rotation) + dy * Math.sin(-rotation)),
    y: newAttrs.y - (dy * Math.cos(rotation) + dx * Math.sin(rotation))
  });
else {
  // original transformation
  this.getNode().setAttrs({
    scaleX: scaleX,
    scaleY: scaleY,
    x: newAttrs.x - (dx * Math.cos(rotation) + dy * Math.sin(-rotation)),
    y: newAttrs.y - (dy * Math.cos(rotation) + dx * Math.sin(rotation))
  });
}
```
I think this would be a good feature either way, actually.

**Comment by lavrton** [comment]
I don't have plans to support direct changing of width/height. That solution has too many cases and it is unclear what to do in case of `Circle` and `Group` (and some other shapes).

We will need to fix `strokeScaleEnabled` size calculation and the demo will work just fine.

**Comment by glisteningly** [comment]
it has same problem with scaling Lines

maybe the transformer should attched not "out" the stroke but "on" (middle of) the stroke?  

looks like padding: -(strokeWidth/2)

like this :  https://jsbin.com/kifujitiwa/edit?js,output

**Comment by lavrton** [comment]
I tried to investigate and fix the issue. Unfortunately, with the current implementation, it is very hard to make correct calculations when a shape has `strokeScaleEnabled = false`.

We can calculate `getClientRect` for one shape just fine. But correct scale calculations inside a `Transformer` are hard to adjust. Also, it is hard to resolve the transforming of a group with both `strokeScaleEnabled = false` and `strokeScaleEnabled = true` shapes.

We can ignore stroke. But the visualization looks weird in this case.

**Comment by glisteningly** [comment]
> We can ignore stroke. But the visualization looks weird in this case.

hi lavrton,  I dont think it looks weird.... because in most vector editor apps, such as Adobe illustrator, Sketch, Affinity Designer, the default way to transform a shape with a transformer is 'ignore stroke'

I made some screenshots in 'Affinity Designer'：

https://imgur.com/daiaJKX

the default setting : stroke align to middle ---- as same as stroke in konva
the transformer is also attach to the middle of the stroke, 

when the stroke set to 'align to inner', the transformer will attach to the outter of the stroke -----as same as transformer in konva

1. single shape selected
2. multi shapes selected
3. path selected
4. set stroke 'align to inner' ---- this is same as transfomer in konva, but we almost not use this way.


is there any way to add some option parameters, to decide whether the transformer will ignore the stroke.

**Comment by lavrton** [comment]
I added a new method to `Konva.Transformer` - `ignoreStroke`. Default value is `false`.

You can set it to `true`. It should work ok, if shape has `strokeScaleEnabled = false`.

Demo: https://jsbin.com/vusifeyisa/1/edit?html,js,output

**Comment by glisteningly** [comment]
Wonderful !  it works perfect~ This is exactly what I want  : )  thanks very much

**Comment by lavrton** [comment]
For now, I will close the issue.

There is a case that not covered is when shape has `strokeScaleEnabled = true` and a transformer has `ignoreStroke = false`. But as I mentioned, it is hard to fix it. I need to deeply think about it.

**Comment by modermo** [comment]
Thanks for implementing this. It works really well @lavrton
