### ISSUE TITLE
Inconsistent shape positions

### ISSUE THREAD

**Issue by fxdave** [konvajs/konva#487]
# The problem:
Shapes eg. reactangle, circle, ellipse are default to an inconsistent position.
Circles and ellipses are centered, but rectangle is not.

## Why is it a problem?
Try to find the absolute position of a random shape's top left corner. 
You couldn't because of this.

**Comment by lavrton** [comment]
You are right. That behavior is not consistent. But it is the most convenient to use. To find bounding box of any shape you can use `shape.getClientRect()`.

**Comment by TheGrandmother** [comment]
Is it possible to move an object by moving it by its client rectangle some how?
Being able to work with a rectangles center coordinates would make life much easier when rotations are involved.

**Comment by TheGrandmother** [comment]
@lavrton 
Thanks for the offset thingy! Had no idea :) But will the offset scale with the `scaleX` and `scaleY`?

**Comment by lavrton** [comment]
Try and see how it works.

**Comment by TheGrandmother** [comment]
Completely missed the jsbin link. It works perfectly, thanks a lot for the help and sorry for being a top tier wanker.
