### ISSUE TITLE
rotationSnaps is not working. 

### ISSUE THREAD

**Issue by zivni** [konvajs/konva#488]
It seems that setting `rotationSnaps` on Transformer does nothing. look at your example in the tutorials : https://konvajs.github.io/docs/select_and_transform/Rotation_Snaps.html

[![Image from Gyazo](https://i.gyazo.com/fc9bb5e95d6352901501e5373a42d0b4.gif)](https://gyazo.com/fc9bb5e95d6352901501e5373a42d0b4)

**Comment by lavrton** [comment]
Works ok for me. It snaps near 0, 90, 180 and 270 deg. I don't see you are trying to snap near that angles.

**Comment by zivni** [comment]
OK. Sorry. now I see. I thought it should only give me to place in the provided angels. Haven't noticed before about the subtle snapping.  

BTW, Great job!!!
