### ISSUE TITLE
Letter spacing, text width calculations and text alignment 

### ISSUE THREAD

**Issue by jakob-fuchs** [konvajs/konva#489]
I've prepared a little demo to show what I mean: https://reverent-kare-bac510.netlify.com/

I've came across this when I tried to right align text with different letter spacing and they just didn't line up.

~~As you can see in the console, Konva reports all the text objects to be the same width.~~ (This is actually because I set the width manually)

It also seems as if the spacing between the words is increased by the letterSpacing property.

Also, I'm using Konva for the first time, so it's quite possible that I'm just doing something wrong here.

**Comment by lavrton** [comment]
The demo looks ok for me, what exactly is not correct here?

> It also seems as if the spacing between the words is increased by the letterSpacing property.

yes, because currently, latter spacing added between ALL characters (and between letter and space too).

**Comment by jakob-fuchs** [comment]
Here is how it looks for me on google chrome:

![screenshot-reverent-kare-bac510 netlify com-2018 11 09-08-14-50](https://user-images.githubusercontent.com/1150242/48267353-bd783880-e3f7-11e8-8ac7-175f86a0a525.png)

The last letter is cut off.

Ideally the spacing should only be added between the characters, in my current project I have to offset the letter spacing manually since it's added before the first character and after the last character. That would make it work more like the CSS property.

**Comment by lavrton** [comment]
I think you are right, we can improve those drawings.

**Comment by jakob-fuchs** [comment]
It would be really nice if the letter spacing would work 'as expected' e.g. like in CSS. I actually chose Konva because it seemed to be the only library that supports that, and it's kind of complicated to create this effect on your own.

I guess this would be a breaking change for most users, since it would alter the layout.

**Comment by lavrton** [comment]
Closing the issue as it seems like a super low priority. I am not sure what is the use cases of that change.

But I am happy to apply any related Pull Requests or more (and very detailed) information about better drawings here.
