### ISSUE TITLE
Wrong return type for fillLinearGradientStartPoint in typings

### ISSUE THREAD

**Issue by halilibrahim** [konvajs/konva#490]
Konva.Shape.fillLinearGradientStartPoint(point: Vector2d) return type is defined as Vector2d in typings definition.
https://github.com/konvajs/konva/blob/d48868621cee57729f3e55a8fd9a0b12bf9408cf/konva.d.ts#L539

It should return "this" as same as in fillLinearGradientEndPoint.
https://github.com/konvajs/konva/blob/d48868621cee57729f3e55a8fd9a0b12bf9408cf/konva.d.ts#L545

**Comment by halilibrahim** [comment]
Actually I wasn't sure if typings file is autogenerated or manually coded.

**Comment by lavrton** [comment]
Currently, it is manually edited. Probably we will migrate to typescript later.
