### ISSUE TITLE
RotationPoint

### ISSUE THREAD

**Issue by Fandangi** [konvajs/konva#494]
Hi - this is a question re usability in relation to rotation by code (not transformer).

Should konvajs include a simple function to move the rotation point.

This question was asked in https://github.com/konvajs/konva/issues/26 too so I am adding to that.

Specifically, the need to recalculate the (x,y) for a shape when setting the offset is not intuitive. IMHO most people will conceptualise the canvas based on early maths lessons, specially when imagining the process of rotation.  If I imagine the chalkboard and my maths teacher talking about rotating a triangle, she would point to the centre of rotation and I could imagine the triangle spinning around her finger. 

I get the point that you want to keep from bloating it out with junk code, but I feel that this confusion hurts the popularity of your excellent library.

An answer may be to provide a wrapper method that applied the offset and reposition of (x,y) in one step, and you can note firmly in the documentation that this will change the position of the affected shape immediately thereafter.

// set the offset for rotation to the given location and re-position the shape
function RotatePoint(shape, pos){  // where pos = {x: xpos, y: yPos}
var initialPos = shape.getAbsolutePosition();
var moveBy = {x: pos.x - initialPos.x, y: pos.y - initialPos.y};

// offset is relative to initial x,y of shape, so deduct x,y.
shape.offsetX(moveBy.x);
shape.offsetY(moveBy.y);

shape.x(initialPos.x + moveBy.x);
shape.y(initialPos.y + moveBy.y);
}

**Comment by lavrton** [comment]
Thanks for your suggestions. I made some edits on https://konvajs.github.io/docs/posts/Position_vs_Offset.html in the hope it will be clear how to use offset to rotate the shape.

But I think the user still have to understand the concept of origin and rotation point (as it may be any point, not just the center of a shape).
