### ISSUE TITLE
Transfomer: add movingResizer to boundBoxFunc

### ISSUE THREAD

**Issue by Botz** [konvajs/konva#495]
I am working with the Transformer and to limit the size of the node i have implemented the boundBoxFunc.
If the user interacts with a corner resizer i will keep the ratio of the node, otherwise not.
For that reason i need the movingResizer in the boundBoxFunc.

Or can i achieve this with another approach? If not i would provide a PR if it is ok for you?

**Comment by Botz** [comment]
No, unfortunately not... i want keep the ratio only when the user interacts with the corner resizers...

**Comment by lavrton** [comment]
But that is what `Konva.Transformer` is doing by default.

See the demo: https://jsbin.com/hejayaxalu/1/edit?html,js,output
On corner anchors (`top-left`, `top-right`, `bottom-left`, `bottom-right`) `Transformer` is saving ratio.

**Comment by Botz** [comment]
Now i see the problem, i had a bug in my boundBoxFunc. Thank you.
