### ISSUE TITLE
How to custom position arrow of Tooltip?

### ISSUE THREAD

**Issue by tanobi92** [konvajs/konva#497]
I create tooltips same: https://codepen.io/TaNoBi/pen/gQRzrb
I set x, y of Label: 0, 0 => tooltip has lost a part, and tooltip only stay between;
pointerDirection of Tag only has: left, up, down, right. Not has: left-down, left-up, right-down,....
![image](https://user-images.githubusercontent.com/11570162/48612515-cb135c80-e9bb-11e8-8edd-09bceb5ff502.png)
How to fix it?
Help me, please! Thanks!

**Comment by lavrton** [comment]
Currently, Konva supports only 4 directions. If you need your own direction (like left-top), you have to implement it manually, by using a custom shape (see demo: https://konvajs.github.io/docs/shapes/Custom.html).
