### ISSUE TITLE
Update versions in konva-node package

### ISSUE THREAD

**Issue by fozcode** [konvajs/konva#499]
The version numbers specified in the konva-node package are rather old:

    "dependencies": {
        "canvas": "^1.6.7",
        "konva": "^1.7.3"
    }

This just caught me out as I'm using node.js / npm for automated testing and have been experiencing bugs that were actually fixed long ago.  Is there any plan to update these to the latest versions?

Thanks for all your work on this project by the way 👍

**Comment by lavrton** [comment]
Updated.

**Comment by fozcode** [comment]
That's great I can see the updated version on npm, thank you.  The code on github still shows the old version numbers: https://github.com/konvajs/konva/blob/master/konva-node/package.json
but perhaps this doesn't matter?
