### ISSUE TITLE
getClientRect returns wrong coordinates

### ISSUE THREAD

**Issue by pronebird** [konvajs/konva#50]
I have the following layout:

* Group { x: 444.6, y: 339, width: 90.8, height: 36 }
  * Shape { x: 0, y: 0, width: 91, height: 39.6 }
  * Text { x: 15, y: 8, width: 50, height: 20 }

Shape has a custom shadow that's why it's height is a little bit larger than the parent group, neglect it. This shape implements `getClientRect` to make sure that custom shade is included into cached canvas:

```js
getClientRect: function () {
  var rect = Konva.Shape.prototype.getClientRect.apply(this, arguments);
  rect.height += this.shadeOffset();
  return rect;
}
```

However clientRect returned for group is:

```
x: 460, y: 347, width: 76, height: 32
```

this matches text's top left corner which is wrong, I guess `getClientRect` should take group's position into consideration.

**Comment by lavrton** [comment]
`getClientRect` should take shadow into account. Can you create example?

**Comment by pronebird** [comment]
Shadow is custom so that's why I override getClientRect. I'll make an example.

**Comment by pronebird** [comment]
Disregard my custom shadow, here is the example:

gist: https://gist.github.com/pronebird/7cbb4ca7d7d909efc560
jsbin: http://jsbin.com/xovewu

Uncached:

![screenshot 2015-04-14 11 58 38](https://cloud.githubusercontent.com/assets/704044/7134511/b04a2f1a-e29d-11e4-8bd2-5d95fa0d3e98.png)

Cached:

![screenshot 2015-04-14 11 59 05](https://cloud.githubusercontent.com/assets/704044/7134514/b2fe31d4-e29d-11e4-988b-698f5181722f.png)

**Comment by pronebird** [comment]
Wow wow, thanks for that!
