### ISSUE TITLE
Add support for CSS transformed containers

### ISSUE THREAD

**Issue by lavrton** [konvajs/konva#500]
Currently hit detection of Konva doesn't work if container DOM element has CSS transforms (like scale). Probably we can add support it with offset https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX mouse properties.

**Comment by lavrton** [comment]
BUT! I can't find `offsetX` and `offsetY` properties for touch events.

It will be super unexpected if the app will work ok on the desktop, but it will not work on a touch device.

**Comment by grydstedt** [comment]
Yeah. Hmm. This is what I did to adjust the coordinates
```
  getMouseCoordinates = e => {
    const {scale} = this.props;
    const pos = e.target.getStage().getPointerPosition();
    const x = pos.x / (scale || 1);
    const y = pos.y / (scale || 1);
    return {x, y};
  };
```
But that does assume that the parent passes in correct scale

**Comment by lavrton** [comment]
Relative discussion why there is not `offset` properties in Touch event: https://github.com/w3c/touch-events/issues/62

**Comment by grydstedt** [comment]
Could you use `clientWidth` vs `width` to move the coordinates?
```
var canvasX = mouseX * canvas.width / canvas.clientWidth;
var canvasY = mouseY * canvas.height / canvas.clientHeight;
```
https://stackoverflow.com/questions/40753016/mouse-coordinates-on-canvas-after-css-scale

**Comment by PikaRules** [comment]
Why does konva doest support this if kinetics does it?, 
I was using kinetics and I migrated to konva but I cannot use it if it does't support this feature.
when are you going to add support for this?

**Comment by lavrton** [comment]
@PikaRules I don't have plans to support it right now.

As for now, we can add support for mouse devices. But if we do, the app will work on the desktop and it will NOT work on touch devices. From my point of view that is very bad user experience. So it makes sense to not support it at all.

**Comment by lavrton** [comment]
I am going to close the issue for now.

`Konva` now works better with a scaled container. But other CSS transforms may not work
