### ISSUE TITLE
Arrow heads do not point in the correct direction if tension != 0

### ISSUE THREAD

**Issue by florianbepunkt** [konvajs/konva#501]
I would like to reopen #197. I'm drawing arrows on a map and as soon as tension is != 0 arrow heads are not working as expected.

**Comment by lavrton** [comment]
@florianbepunkt can you make an online demo of your arrow that you are trying?

**Comment by florianbepunkt** [comment]
@lavrton wow, that was fast. sure, simple codepen… scaled it up: https://codesandbox.io/s/ol9q041zlz

**Comment by ninjapapa** [comment]
Any progress on this? Or is there a workaround?

**Comment by lavrton** [comment]
Just pushed slightly better version. That is not simple math to handle it 100% correctly.

As workoround, you can just draw your own custom `Konva.Shape`.

**Comment by ninjapapa** [comment]
Cool! Thanks a lot for the quick response. For future reference, here is the commit: 85d1cdd09cb44df47b950982230169e4228ae79e

I think it solved the problem 👍

**Comment by david-blanco-a** [comment]
It still happens with Konva version 6
