### ISSUE TITLE
[Malicious Alert] Konva used gulp-connect which used event-stream

### ISSUE THREAD

**Issue by MaxGraey** [konvajs/konva#502]
`event-stream` contain malicious code injected into it:
https://github.com/dominictarr/event-stream/issues/116

**Comment by TheGrandmother** [comment]
Does konva use this !?!?!?!?

**Comment by MaxGraey** [comment]
It seems yes:
https://github.com/konvajs/konva/blob/master/yarn.lock#L1241

Should be locked to `3.3.4` instead `^3.3.2`

**Comment by MaxGraey** [comment]
Currently `gulp-connect` switch `event-stream` from to `map-stream`:
https://github.com/avevlad/gulp-connect/pull/261

So just need update `gulp-connect` to latest version

**Comment by TheGrandmother** [comment]
@MaxGraey 
Thanks a lot for bringing this to our attention!

**Comment by lavrton** [comment]
Updated all dependencies.
