### ISSUE TITLE
Download stage.toDataURL() --> download Failed - Network Error

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#504]
Hi there,

Please could you assist.
I have quite an extensive stage that contains many images.
When i want to export/download the stage image, i get a error on download : Failed - Network error.
This seems to only happen when there is a lot of stuff on the stage.

I have used crossOrigin = 'Anonymous'; on all images.

Please assist thank you

**Comment by lavrton** [comment]
`Failed - Network error.`  is a network error. I guess it may happend if you are making some server requests (download or upload). So it should not be related to `stage.toDataURL()`.

**Comment by deathblade89** [comment]
@lavrton 

Hi,

Thanks for your reply.

So i would agree with you if there were network errors when placing the images.

I have attached an image that has a blue squiggly line to show up until where downloading the image works fine, after that i have the same images from the same source and i then receive the network error.

Is it not the time taken to generate the DataURL that creates the network error? (Just throwing out questions)

![image](https://user-images.githubusercontent.com/16613924/49232929-9234a800-f3fd-11e8-89f9-7346886ef71e.png)

**Comment by deathblade89** [comment]
@lavrton 

Just another thing, i am potentially going to be using 1000 + images on a stage, does konva support this? Each image is interactive and cannot be cached.

I have a sample attached again, where image quality is degrading the more i add to the stage.

![image](https://user-images.githubusercontent.com/16613924/49239360-44bf3780-f40b-11e8-8d10-40e216400c0f.png)

Notice how the image farthest to the right, has more of a blur to the image, they are from the same sources, there is no difference in the way they are being created or added to the stage.

**Comment by lavrton** [comment]
If you have 1000+ images you may have performance issues. Just hide images that out of the visible viewport.

Image may be blur if you are using non-integer position. Like `x = 10.5`.

**Comment by deathblade89** [comment]
> If you have 1000+ images you may have performance issues. Just hide images that out of the visible viewport.
> 
> Image may be blur if you are using non-integer position. Like `x = 10.5`.

Since i am using to scael and factors there are alot of co-ordinates that will be decimal based. Is there anyway to fix this?

**Comment by deathblade89** [comment]
Testing the toDataURL, give back the following output:
![image](https://user-images.githubusercontent.com/16613924/49278696-3a924d00-f48e-11e8-922d-fc702c59bac6.png)

If i copy the output to a online base64 to image converter, it displays the image without a problem.

I do agree with you that this is not an issue with Konva.toDataURL, i just need to try and understand the limitations of the browser when using something like this:

var link = document.createElement("a");
                    link.download = 'planogram.jpg';
                    // Construct the uri
                    var uri = dataURL;
                    link.href = uri;
                    document.body.appendChild(link);
                    link.click();
                    // Cleanup the DOM
                    document.body.removeChild(link);


Do you perhaps have any pointers for me?

**Comment by deathblade89** [comment]
@lavrton 
I have managed to get this working better.

The issue is that the size of the data url is extremely large : 20mb.

I changed the download mechanics to use a blob instead, this seems to work well so far.

The only issue that is remaining is : The quality of images degrading based on co-ordinates in decimal, if you could please assist me with this i will be extremely grateful.

**Comment by lavrton** [comment]
@deathblade89 I see only one way - avoid decimal. Read more info here:
https://www.html5rocks.com/en/tutorials/canvas/performance/#toc-avoid-float
https://stackoverflow.com/questions/12946608/canvas-drawimage-quality
