### ISSUE TITLE
Unable to tween HSL color values

### ISSUE THREAD

**Issue by Jaeiya** [konvajs/konva#505]
When trying to Tween a stroke, Konva is using its `Util.colorToRGBA()` method, which doesn't understand HSL values. Here's the result of the conversion:
![chrome_2018-11-29_13-21-33](https://user-images.githubusercontent.com/2054218/49253086-a1562e80-f3da-11e8-83f5-a5a9f4bce382.png)

**Comment by lavrton** [comment]
Looks like our parsing does not support HSL.  I guess we need to support it. As a workaround, you can convert HSL to rgba.

Anyone wants to make a PR?

**Comment by Jaeiya** [comment]
Yeah I converted all my values to RGB. It's not a huge deal; I tend to use HSL for all my styles so it would just be convenient.
