### ISSUE TITLE
Is it possible to add a custom  anchor icon to Transformer to handle delete event?

### ISSUE THREAD

**Issue by TonyLuo** [konvajs/konva#506]
Is it possible to add a custom  anchor icon to Transformer to handle delete event?
    var tr = new Konva.Transformer({
      anchorStroke: 'red',
      anchorFill: 'yellow',
      anchorSize: 20,
      borderStroke: 'green',
      borderDash: [3, 3],
    });

**Comment by lavrton** [comment]
It is possible, since `Konva.Transformer` is just a group of shapes. For now it works just fine:

```javascript
const tr = new Konva.Transformer({
  node: circle
});

layer.add(tr);


const deleteButton = new Konva.Circle({
  x: tr.getWidth(),
  y: 0,
  radius: 10,
  fill: 'red'
});
tr.add(deleteButton);

tr.on('transform', () => {
  deleteButton.x(tr.getWidth())
})

deleteButton.on('click', () => {
  tr.destroy();
  circle.destroy();
  layer.draw();
})
```

But I can't garantee it will work in the future. https://jsbin.com/dokukiyato/1/edit?html,js,output
