### ISSUE TITLE
[doc request] clarification around events

### ISSUE THREAD

**Issue by bigopon** [konvajs/konva#507]
I was trying to look for docs related to all events available but could not find any. They are particularly related to position and size change events of shapes. Do they exist? If so, would be nice if those event could be added to the doc `event list` section, if not, is it possible to implement? If it's possible then please consider this is a feature request.

**Comment by lavrton** [comment]
Can you clarify what do you need?

Isn't https://konvajs.github.io/api/Konva.Node.html#on and docs on the site enough? Do you mean docs for an event like `xChange`?

**Comment by bigopon** [comment]
@lavrton Cool. I couldn't see that clicking through the nav menu on the left in doc page. I'd like to have it have its own section. Something like: important change events or something.

**Comment by lavrton** [comment]
Thanks for the suggestion. I will think how to add it into the doc.
