### ISSUE TITLE
[Feature Request] Add by index

### ISSUE THREAD

**Issue by bigopon** [konvajs/konva#509]
Current `konva.Container` is lacking a method to insert a child at a certain index. This is quite a surprise as konva DOM api is quite complete. Please consider adding method `insert` that take a child and an index to add.

**Comment by lavrton** [comment]
```javascript
group.add(shape);
shape.setZIndex(index);
```

**Comment by bigopon** [comment]
@lavrton thanks for your response. Setting zIndex is not what I wanted to achieve.

Consider the following HTML DOM scenario:

```js
// add input
form.appendChild(input);
// insert label before input in child list
form.insertBefore(label, input);
```

in order to support the 2nd scenario, I think there would be to be a method to insert either by index, or another node reference. For what I asked for:

```js
let existingShapeIndex = group.children.indexOf(existingShape);
group.insert(shape, existingShapeIndex);
```
Can you consider support this? I think it's needed for when integrated to higher level templating language.

**Comment by lavrton** [comment]
The suggestion is good. But it is just too simple to implement that function with existing API. Currently, Konva already has too many methods, so I am thinking how to reduce the number of methods to make the lib smaller and simpler.

If you need insert before you can do this:

```
group.add(shape);
shape.setZIndex(existingShape.getZIndex());
```
