### ISSUE TITLE
Image() Vs Konva.Image() --> Rotation

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#511]
Hi there,

I have a requirement. An image that is loaded can only be rotated once it has been allocated to a Konva.Image()

I would like to rotate the image before allocating it to the Konva.Image().

Imagine a 3D cube that you would like to bring to 2D with rorations.
The 3D cube could be a box of cigarettes with different dimensions per face.

To move this to 2D, it is a matter of changing the height, width, depth configuration of a 2D rectangle to simulate a cube that is rotating from one face to the other.

Since a Konva.Image() will apply the width and height and rotate around a point, it would not be able to understand the rotation to a new face with different dimensions correctly.

The only way i can see this working is to ratate the image first, then apply it to the rectangle with whatever dimensions (w,h)

Is there a way to rotate an image once its loaded before adding it to Konva.Image() ?

Thanks

**Comment by lavrton** [comment]
You need to draw the image into an external canvas with rotation. Then use created canvas for `Konva.Image`. Something like this:

```javascript

// when image is loaded:
const canvas = document.createElement('canvas');
const ctx = canvas.getContext('2d');

// apply your transform
ctx.rotate(Math.PI / 4);
ctx.drawImage(img, x, y);


const image = new Konva.Image({
   image: canvas
});
```
