### ISSUE TITLE
clip image using Png or svg image via clipFunc of Konva.group

### ISSUE THREAD

**Issue by niranjan-b-prajapati** [konvajs/konva#512]
Hi,

I want to clip image based on png or svg image via konva.group clipFunc. As there are different kinds of various shapes in which user will be uploading the photos and aligning it properly. As the shapes are very much difficult to create using konva. I would prefer using png image of shape or svg image which can act as mask and clip the user image allowing the centre area to show user's photo. I tried various options as clipFunc returns ctx object i tried to use **ctx.drawImage()** to use the svg image of that shape. 

Following is the link to the reference svg image : [hexagon](https://image.flaticon.com/icons/svg/105/105148.svg)

The sample is of hexagon but there area which cannot be categorised as specific shapes.

Following is the code : 

```
objects[i].group = new Konva.Group({
            clipFunc: function (ctx) {
               // ctx.drawImage(maskImage,(canvasWidth / 2) - (maskWidth / 2),(centerY) - maskHeight / 2,maskWidth,maskHeight)
                   
                // var path = new Konva.Path({
                //     x: 0,
                //     y: 0,
                //     data: 'M364.269,453.155H121.416L0,242.844L121.416,32.533h242.853l121.419,210.312L364.269,453.155z M131.905,434.997h221.878l110.939-192.152L353.783,50.691H131.905L20.966,242.844L131.905,434.997z',
                //     fill: 'green',
                //     scale: 1
                //   });
                //   ctx.lineWidth = "12";
                //   ctx.strokeStyle = '#110000';
                //   ctx.stroke(path);
                          
                
                // ctx.arc(350, 120, 50, 0, Math.PI * 2, false);
                                
                // let p = new Path2D('M0,92.375l46.188-80h92.378l46.185,80l-46.185,80H46.188L0,92.375z');
                // ctx.lineWidth = "12";
                //   ctx.strokeStyle = '#110000';
                // ctx.stroke(p);

            },
            draggable: false
        });
```

When i used `ctx.arc();`  or `ctx.rect();` the image is clipped properly. But when i use `ctx.drawImage();`
My Image which is used for masking is visible but the user uploaded image cannot be seen.

I am not able to understand why i can see user's image when using `ctx.arc` or `ctx.rect` but i cannot see user's image when using `ctx.drawImage();`

Later in the process i use ` Konva.Image` to load user's image on the website and process it further with facilities like setting rotation, setting offsetx&y, attaching transformer, etc.

@lavrton can you please help me find solution or guide me to correct way of fixing it. 

@lavrton  i used your solution on the link : https://stackoverflow.com/questions/45094648/konvajs-masking-instead-of-clipfunc-possible 
But it uses image() object and we are using Konva.Image() Object in our project as we are adding Konva transformer to scale images uploaded by user. And your solution doesn't accept Konva.Image() object. Can you please help me solve this issue.

**Comment by lavrton** [comment]
Closing this issue as not enough information.

**Comment by ilomon10** [comment]
@lavrton use how do i handle the masking, because when i use it, it affected the other shape, how to isolate the mask just by the group. Just like photoshop masking, or illustrator masking.

**Comment by lavrton** [comment]
Cache the group to isolate its render.

**Comment by ilomon10** [comment]
i mean it just affected to its group, so i can add background on the different group that must be not affected by the mask
this is my testing project:
https://codesandbox.io/p/sandbox/serverless-meadow-lhwdmg
