### ISSUE TITLE
Stage Zoom -> dragBound changes when applying zoom

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#513]
Hi there,

Using the stage with no zoom as originally intended, dragBoundFunc work perfectly well using bounds of parent position and height / width

When adding zoom, the bound functions are completely out. I can understand that a multiplication on stage.scale must be done.

HOWEVER, why does zoom affect the co-ordinate system? To think of it, should it not just be the perspective that changes and not all the calculations on bounds, width / height?

Another thing : When zooming in on the stage, how can one always look at the bottom left hand corner of the stage?

Imagine that you are building a house, on the screen the bottom of the screen is where you start. I am having a similar issue, where i am using the bottom left hand corner as my "starting point". Whenever i zoom, i would like to always focus on the bottom left hand corner.

![image](https://user-images.githubusercontent.com/16613924/49803168-c3936900-fd57-11e8-9214-63ea3e59841b.png)

Lastly, Gentlement thank you for the amazing library and all the help and support. Donations will be made!

**Comment by lavrton** [comment]
Can you make an online demo of your `dragBoundFunc` issue?

About zooming point, take a look into this demo: https://konvajs.github.io/docs/sandbox/Zooming_Relative_To_Pointer.html
In the demo, the zooming point is mouse position. You can change it to a bottom-left point.

**Comment by deathblade89** [comment]
@lavrton 
I have made a work around for this as it was quite difficult to try and implement.

**Comment by eoghanmccarthy** [comment]
Is there a solution for the `dragBoundFunc` issue above.

I'm building an image annotation tool where the stage is sized exactly to the size of the image. When zoomed in I still want the drag bounds to be the edge of the image (which when zoomed in are beyond the stage edges), not the stage itself.

Is there an example of something like this?
Regards

**Comment by lavrton** [comment]
@eoghanmccarthy please make a demo and create another issue.

**Comment by eoghanmccarthy** [comment]
@lavrton Will do.
