### ISSUE TITLE
Load stage from json VUE --> Konva.Node.create(json, container)

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#519]
Hi there,

I am trying to load my stage up using json.

The images that i had loaded previously, are not visible.
All drag bound functions on the stage, groups, layers have been removed. (not that important right now)

The idea, is to load the stage up as a preview. The preview must contain the stage data at the point of save.

Attached is a json file.

The stage item within the json file contains all the information about the stage at the point of save.
The images have been loaded from a cloud server and therefore are accessible.

Please assist
[test.zip](https://github.com/konvajs/konva/files/2689946/test.zip)

**Comment by lavrton** [comment]
So what is your exact question?

Be default Konva does not serialize images, but you can manually save `src` into any attribute and then load an image from that attribute.

There are no good ways to serialize functions (like `dragBoundFunc`).

**Comment by deathblade89** [comment]
@lavrton 
Ok, i understand using the src attribute. 

I assumed that all relevant data and bounds were saved and restored through Konva.
This is not a problem, i will bypass this with my own draw routine.
