### ISSUE TITLE
Circle blur clipping

### ISSUE THREAD

**Issue by chrisjansky** [konvajs/konva#521]
Hello!
Any idea what might be causing a strange clipping of the circle below? I want to do something along the lines of "overflow: auto".

My code:
```javascript
    var container = document.getElementById("container");
    var width = container.offsetWidth;
    var height = container.offsetHeight;

    var stage = new Konva.Stage({
      container: 'container',
      width: width,
      height: height
    });

    var layer = new Konva.Layer();

    var circle = new Konva.Circle({
      x: width/2,
      y: height/2,
      radius: 500,
      fill: "red",
      stroke: "blue"
    });

    layer.add(circle);
    stage.add(layer);

    circle.cache();
    circle.filters([Konva.Filters.Blur]);
    circle.blurRadius(100);
    circle.draw();
```

![image](https://user-images.githubusercontent.com/5342612/50168349-83019580-02eb-11e9-8e52-2c731304b2e8.png)

**Comment by lavrton** [comment]
When you cache a node, Konva is creating an offscreen canvas for the node and then Konva is making drawing and manipulating on that canvas.

You are using a very large value for `blur`. So the effect goes out of the cached canvas. To fix the issue you just need to tell Konva to increase canvas size with `offset` property:

```javascript
circle.cache({
  offset: 50
});
```

Demo: https://jsbin.com/mawahopexe/2/edit?html,js,output

**Comment by chrisjansky** [comment]
Whoa, amazingly speedy response. Thanks!
