### ISSUE TITLE
Position snaps after changing layer

### ISSUE THREAD

**Issue by TomKita** [konvajs/konva#522]
I have a rect that is in a group which is draggable. After I drag the group and then move the rect to another layer it snaps position back to it's starting point.

I made a fiddle to demonstrate.

https://jsfiddle.net/d2wt6701/ 

I'm assuming the rect is using the position relative to its parent?

**Comment by lavrton** [comment]
> I'm assuming the rect is using the position relative to its parent?

Yes. You have a draggable group. Rect is not draggable. So Konva will change group attributes while dragging. Rect position is keeping the same (50, 50). You can use `rect.getAbsolutePosition()` to adjust position of rect when you move it out of the group.
