### ISSUE TITLE
Curved Text using Konva.Textpath, letter spacing not consistent

### ISSUE THREAD

**Issue by sagarcool89** [konvajs/konva#523]
Dear Team,

I am using wheel of fortune example of konva js and i am facing issue drawing curved text with TextPath using below code. Characters spacings are odd even, not consistent at all.

```
var textpath = new Konva.TextPath({
fill: '#333',
fontSize: 20,
fontFamily: 'Calibri',
text: 'Hello World',
align: 'center',
data: 'M -80.34441853748636 -247.27469423673992 A 260 260 0 0 1 80.34441853748628 -247.27469423673995'
});
```

See attached screenshot FYI.
![screen shot 2018-12-24 at 1 59 48 pm](https://user-images.githubusercontent.com/4920892/50449224-e9219480-094b-11e9-978c-57b68b7d9907.png)

**Comment by zolbatar** [comment]
I'm having the same issue.

**Comment by SnooHD** [comment]
Any progress on this?

**Comment by lavrton** [comment]
As of right now I am not sure how to make it beautiful. I will be happy if someone can provide ideas and make a PR.

As workaround, you can use `kerningFunc` or `letterSpacing` attributes to change spacing manually.
