### ISSUE TITLE
new hitStrokeWidth property

### ISSUE THREAD

**Issue by lavrton** [konvajs/konva#524]
I am thinking to add a new property called `hitStrokeWidth`. Using that property you can increase hit area of the shape without using custom `hitFunc` and without adding another shape into the layer.

The most common use case is clicking on a thin line (strokeWidth < 3). It is hard to click on the line. But we that property we can just write `line.hitStrokeWidth(20)` and its hit area will be much bigger, so it will be simple to click on it. Manual overwriting `hitFunc` may be complex if a line has a complex path or if the line has a `tension`.

**Comment by xuzhaobin** [comment]
+1

**Comment by lavrton** [comment]
Added in `konva@3.2.0`.

Demo: https://konvajs.org/docs/events/Custom_Hit_Region.html

Docs: https://konvajs.org/api/Konva.Shape.html#hitStrokeWidth
