### ISSUE TITLE
Text option wrap: "word" not honored when a word exceeds width

### ISSUE THREAD

**Issue by jessegavin** [konvajs/konva#530]
Here's a Codepen Example of the problem
https://codepen.io/jessegavin/pen/aPKrvL?editors=0010

```
  var text = new Konva.Text({
    text: 'NEIGHBORHOOD PARTY',
    fontSize: 80,
    width: 300,
    wrap: "word"
  });
```

I expect the word "NEIGHBORHOOD" to extend outside the defined width. 

What actually happens is the word is truncated to fit the width and extra characters wrap on the next line. This is what I would expect if `wrap: "char"` was defined.

This feels like a bug to me.  In CSS words don't break by default, you have to explicitly set `word-break: break-all;` to replicate this behavior.

I feel that Konva should use the same behavior.

This code seems to be the source of the "problem". It basically just looks for a substring of a word that will fit the width. I think this should only happen when `wrap: "char"`.
https://github.com/konvajs/konva/blob/master/src/shapes/Text.ts#L376-L391

**Comment by lavrton** [comment]
The `width` property here has a priority over `wrap`. In the case of the canvas app, I think it makes more sense.

`wrap: "word"` is trying to preserve words where it is possible. It split the word only if it can't fit into the required width. If you don't need that effect, you can just set another width.

**Comment by jessegavin** [comment]
We have frequent situation where we have variable length text that needs to fit into a rectangle.

We then have a while loop which decrements the font size of the text until it fits inside the height.

We were under the assumption that `wrap: "word"` would never render word breaks. That assumption was wrong.

Do you have any advice on how we could accomplish this differently? Thanks for your reply.

**Comment by lavrton** [comment]
What if you will use `scale` instead of `fontSize` for changing size of the text?

```
var text = new Konva.Text({
   ...textProps
});

var scale = requiredHeight / text.height();

text.scale({
   x: scale,
   y: scale
});
```

**Comment by jessegavin** [comment]
I don't think that would work in my case. Here's an example, the goal is to scale the font size down so it would fit inside a 600 x 400 rectangle.

Scaling certainly make the text fit, but it wouldn't solve the word-break problem.

![image](https://user-images.githubusercontent.com/78791/50924493-5554cb80-1415-11e9-846d-fd56fbb877d6.png)

**Comment by lavrton** [comment]
Ok. That is the deep issue. We need to think about how to resolve it in a good way.

1. Dirty solution:
take `text.textArr` property (it is no public API).
```
textArr:
0: {text: "NEIGHBORH", width: 484.4921875}
1: {text: "OOD PARTY", width: 463.7890625}
```
and check every `text` property in the array and compare it with original `text` property of `Konva.Text`.  If we see a break - decrease font size again.

Probably we can add a property to `Konva.Text` with a name like `hasWrapedWords`.

2. Fix "word" wrapping behaviour. But currently I am not sure how. If we allow a word to go out of width it may lead to unexpected hit graph behaviour. The part of text that is outside of width will not fire events. That will be super confusing.

**Comment by jessegavin** [comment]
Thank you for the tip on the` textArr` property! I am going to try that out today. I am looking for _any_ fix available in the short term.

> Probably we can add a property to Konva.Text with a name like hasWrapedWords.

I think this would be an excellent option.

Also very interesting to hear your concerns about the hit graph. We don't do anything with interactivity in Konva, so I hadn't even considered that aspect.

Thanks so much for taking the time on this issue. We very much appreciate your work on this!

**Comment by eram1205** [comment]
@jessegavin minor typo in while loop: broken -> brokenWords
```
while(text.getHeight() > boxHeight || brokenWords){
  text.fontSize( text.fontSize()- 1);
  brokenWords = hasBrokenWords(sourceTokens, text.textArr);
}
```
Thanks for sharing, it works!

@lavrton, I agree with @jessegavin that this would be a great property to include in Konva.

**Comment by lavrton** [comment]
I am going to close the issue as not a priority. But I am still open to API suggestions and Pull requests.

**Comment by willyou** [comment]
I use `text.split(/\s+/)` 

[ref](https://stackoverflow.com/questions/25218677/javascript-split-function-to-split-into-array-at-new-line-or-white-space)

**Comment by leonfhl** [comment]
Thanks for your code @jessegavin I added a different way to capture the real height when the string has multiple lines with `textNode.textArr.length * textNode.textHeight `  as sometimes the variable you use keeped showing fontSize value and didn't change with multiple lines. 

```javascript
var textHeight = textNode.textArr.length * textNode.textHeight 
var textAreaHeight = textNode.height()

while ((textHeight > textAreaHeight || brokenWords) && textNode.fontSize() > minFontSize) {
textNode.fontSize(textNode.fontSize() - 1);
brokenWords = hasBrokenWords(sourceTokens, textNode.textArr);
}
``` 

Here is a full demo working on shrinking text both editing or transforming [https://codepen.io/leonfhl/pen/qBLaeBg](url)
