### ISSUE TITLE
Can't Fill Text with Image or Gradient

### ISSUE THREAD

**Issue by websmyths** [konvajs/konva#532]
I'm trying to fill text with an image. It defaults to color and won't use the image. Tried setting the fill to transparent. It still doesn't work. I can fill other shapes with an image. Here's a CodeSandbox link. https://codesandbox.io/s/xj3oy3z2jo

**Comment by lavrton** [comment]
https://stackoverflow.com/a/54112957/512042

Probably I will add a warning when a user is trying to use a pattern or gradient fill for text.

**Comment by lavrton** [comment]
The bug is fixed. Gradient or patterns will work just fine in `Konva` v3. Will be published a bit later.
