### ISSUE TITLE
what are "content events"?

### ISSUE THREAD

**Issue by callagga** [konvajs/konva#534]
(perhaps a doco related request?)

What exactly is a "content event"?  
When would one use these?  (e.g. when to use onContentMouseDown rather than onMouseDown) 
Are these  "Konva" only related items (as opposed to being part of HTML5 say?

(Background: Just trying to understand.  Background is as I'm wanting to track mouse/touch events to setup layer scrolling, however there will still be other shapes on the layer that I will want to have specific events on separately... )

**Comment by lavrton** [comment]
Some time ago all events on stage were relevant to shapes only. So clicking on empty areas of a stage didn't trigger `click` events. `content` events are events of stage container (DOM element). They were useful if you want to listen to events on empty areas.

But that behaviour was changed. So it the current momemt you don't need to use "content" events.
I think I will remove them from the documentation.

**Comment by lavrton** [comment]
I removed all notes from the doc. Use all events directly.
