### ISSUE TITLE
Konva.Text and Konva.TextPath do not recognize fillPatternImage

### ISSUE THREAD

**Issue by davea99** [konvajs/konva#535]
**Konva.Text** and **Konva.TextPath** do not recognize **fillPatternImage**. Other shapes like Konva.Rect do.

See https://jsfiddle.net/4d1235zL/.

**Comment by davea99** [comment]
Would it be ok to update the docs as well to avoid confusion?

**Comment by lavrton** [comment]
I just found there was a bug in Konva core. `fillPatterImage` will be fixed in the next release.
