### ISSUE TITLE
[Konva] Responsive Stage and toDataURL full size

### ISSUE THREAD

**Issue by antyhelion** [konvajs/konva#538]
Hey!

Does anyone have any idea how to create a responsive stage (which is basically 4000px wide, but is scaled to the width of the device) in such a way that all the images added to it are automatically scaled with the ratio maintained?

And when using the "toDataURL" function, the stage was downloaded in the original size (that is just 4000px) and also matched pictures?

Regards!

**Comment by lavrton** [comment]
https://stackoverflow.com/questions/54187464/konvajs-responsive-stage-and-todataurl-full/54190960#54190960
