### ISSUE TITLE
Drag performance

### ISSUE THREAD

**Issue by pronebird** [konvajs/konva#54]
Hi,

Did you experience FPS drop when you have lots of draggable shapes on layer? According to my tests FPS drops a lot with each draggable node, but I am not sure why. I feel like all draggable nodes somehow participate in some sort of repainting process, but sceneFunc does not fire which means that it blits cached canvas..

p.s: I experience this on FF/Mac, Safari runs very smooth. Can be browser bug / poor perf.

**Comment by lavrton** [comment]
Canvas performance for FF might be bad. Konva have to redraw each node on layer while dragging (directly or from cached canvas). You can move node into temp layer while dragging.

**Comment by pronebird** [comment]
Good idea! Can I use separate group or is it important to use separate layer for that?

**Comment by lavrton** [comment]
It is important to use a layer.

**Comment by pronebird** [comment]
It worked! Thank you!
