### ISSUE TITLE
[question]custom component is not draggable

### ISSUE THREAD

**Issue by zzzgit** [konvajs/konva#540]
https://jsfiddle.net/jonkee/086z2ogf/5/

I defined a custom component, but it doesn't support dragging.

**Comment by lavrton** [comment]
There are several issues with the code.

1. As you use an image for drawing you need to define custom `hitFunc`. See demo here: https://konvajs.github.io/docs/events/Custom_Hit_Region.html

2. `sceneFunc` can be called many times per second. Creating and loading images inside `sceneFunc` is not optimal. It will be better to create image outside of `sceneFunc`. And inside `sceneFunc` just call `drawImage`.



```javascript
var triangle = new Konva.Shape({
  sceneFunc: function (context) {
	  var image = this.getAttr('image');
    if (image) {
      context.drawImage(image, 0,0, 40, 40);

      // Konva specific method
      context.fillStrokeShape(this);
    }
  },
  hitFunc: function(context) {
    context.beginPath();
  	context.rect(0, 0, 40, 40);
    context.closePath();
    context.fillStrokeShape(this);
  },
  fill: '#00D2FF',
  stroke: 'black',
  strokeWidth: 4,
  draggable: true
});

layer.add(triangle);
stage.add(layer);
layer.draw();

let image = new Image();
image.src = 'https://www.nedlands.wa.gov.au/sites/default/files/dog1_0.jpeg'
image.onload = () => {
  triangle.setAttr('image', image);
  layer.draw();
}
```

https://jsfiddle.net/qp61ygod/
