### ISSUE TITLE
ZIndexing

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#542]
Hi @lavrton ,

I understand that nodes (shapes) within a layer receive a z-index value and that only those values can be changed not the layers.

In my current design:
* A layer contains many groups and shapes
* A layer represents an "object" that contains all the groups and shapes.
* I have several layers for each that contain different groups and different shapes.
* I have basically created a separation of concerns item. A layer deals with its groups and shapes independently.

EG: 
Layer 1: This is a desk.
Layer 1 - > Group 1: This is a space case
Layer 1 -> Group 1 -> Shapes: These are the erasers, pens and pencils, rulers etc.

Layer 2: This is a desk.
Layer 2 - > Group 1: This is a book
Layer 2 -> Group 1 -> Shapes: These are the pages of the book.

I can move Layer 1 -> Groups to layer 2 and move shapes from Layer 1, Group 1 to layer 2, Group 2.

The issue i am facing is as follows:
Layer 1 + all groups and shapes are added to the stage.
Then Layer  2 + all groups and shapes are added to the stage.
Items to move from layer 1 to layer 2 when dragging is behind layer 2.

I would like to make the z-indexing of each layer the same so that when dragging items around they do not fall behind other layers, groups and shapes.

The only way i can think of doing this is to go through all layers and move their z-index down and the dragged item to move up, but this seems like the long way around?

Could you please assist?

**Comment by lavrton** [comment]
@deathblade89 Sorry, I am not sure what is your issue.

You can change the ordering of all nodes. You can move layers as well.

**Comment by deathblade89** [comment]
@lavrton Thanks for your response.

I have done a demo for you, the demo has a paragraph with my comments.

https://jsfiddle.net/xv8r30cq/4/

**Comment by deathblade89** [comment]
@lavrton 
Have you had a chance to have a look at this?

**Comment by lavrton** [comment]
I just wrote a post that should explain your confusion: https://konvajs.github.io/docs/groups_and_layers/zIndex.html

Please read it and let me know if helps.

**Comment by ffxsam** [comment]
Hopefully no one minds me reviving an old thread...

That page should definitely be updated. It needs to explain that you _can_ use `zIndex` to move layers around, but you can't use arbitrary values like 2, 5, 50. They have to start at 0 and only increase by 1 each time.

So for example, I developed a layer system where I can define layers and use whatever zIndex values I want (like CSS). And then to set the layer order in Konva:

```ts
public setLayerZIndex(layerIndex: number, zIndex: number) {
  if (layerIndex < 0 || layerIndex >= this.layersInfo.length) {
    throw new Error('Invalid layer index');
  }

  /**
   * Regardless of the zIndex numbers we've set in this.layersInfo, Konva
   * always draws the layers in the order they were added to the stage, and
   * assigns strict zIndexes of 0, 1, 2, etc. So we can't just set the zIndex
   * of the layer and expect it to be drawn in the correct order.
   *
   * Instead, we should update this.layersInfo with this layer's new zIndex,
   * then loop through all the layers and set their zIndexes starting at 0.
   */

  this.layersInfo[layerIndex].zIndex = zIndex;

  [...this.layersInfo]
    .sort((a, b) => a.zIndex - b.zIndex)
    .forEach((layerInfo, i) => {
      layerInfo.konvaLayer.zIndex(i);
    });
}
```

I only share this here in case someone else struggles with this for an hour like I did.
