### ISSUE TITLE
Event Delegation when using fire()

### ISSUE THREAD

**Issue by wouldntsavezion** [konvajs/konva#544]
Kind of a bug, kind of a missing feature, event delegation does not work when firing events manually using fire(). 

[JSBIN](https://jsbin.com/paxaxolede/edit?js,console,output)

In this JSBIN, I have the template circle with an event to output the circle's name on click, it works when clicking on the layer itself, but when firing a click event via another layer, it doesn't find the target (even if this layer is a clone of the first one, so we know the coords are the same etc.).

I tried manually creating a custom event using fire()'s second param, but I can't find a way to make it work.

Is this possible in any way?

**Comment by wouldntsavezion** [comment]
I was finally able to achieve the desired behavior by manually passing the original event coords and then using getIntersection() to find the target.

It's fairly simple : [JSBIN](https://jsbin.com/buzaherujo/edit?js,console,output)

I would still expect a "fire()"d event to behave the same way as a normal event though, I would suggest changing [this line](https://github.com/konvajs/konva/blob/60e425c5961c03a61939e47a07cb60733824f1b1/src/Node.ts#L1456) to do the getIntersection() call instead of "|| this", though that would undoubtedly break a few things. Maybe adding another param to fire() is the solution?

**Comment by lavrton** [comment]
Why do you need such weird events? Why do you want to fire events manually?

I don't see any issues with the first demo. When you do this:
```javascript
layer1.fire('click')
```

It will just fire (call all callbacks) an event on a layer instance. Events do not go from top to bottom (from layer to shape). Instead, they go from bottom to top (from shape to all its parents) in case of bubling.

**Comment by lavrton** [comment]
The purpose of `fire` is not to detect the underlying shape and start all delegation process. The purpose of `fire` is just to call all handlers and bubble the event into the parent if necessary.

Currently, you have to detect clicked shape manually.

```javascript
var shape = layer.getIntersection(stage.getPointerPosition());
shape.fire('click', event, true);
```
