### ISSUE TITLE
text don't have attribute of direction

### ISSUE THREAD

**Issue by Kelvin945** [konvajs/konva#552]
I am currently using Text class for rendering Arabic words which is right to left. Canvas render fine if you manual set the attribute of 'dir' to 'rtl'. But if you try to get image from stage. The order of text is still wrong.

**Comment by lavrton** [comment]
Can you make an online demo, please?

**Comment by lavrton** [comment]
I guess we need to add "dir" property to `Text` for that use case.

**Comment by brenoprata10** [comment]
In my case i needed to force `\u200e` unicode inside the Text string

**Comment by lavrton** [comment]
I am closing this issue as not a priority. I am familiar with RTL languages. But I am happy to see any related pull requests here.
