### ISSUE TITLE
Maximum call stack size exceeded - Konvajs

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#553]
@lavrton 
Hi there,

Using a drag bound function, if you erratically move the element around and it doesnt meet its condition, i receive the below error.

Could you perhaps assist?

![image](https://user-images.githubusercontent.com/16613924/51677937-cda9b800-1fe3-11e9-8406-caaf2b8b0434.png)

**Comment by lavrton** [comment]
Can you make a demo?

**Comment by deathblade89** [comment]
@lavrton 
Very difficult as it is an entire system.

Could you perhaps point me in the direction as to when this might happen so i can prevent it in the system?

**Comment by lavrton** [comment]
It looks like a weird tree structure. Like a group is a parent of itself.

**Comment by deathblade89** [comment]
@lavrton 

Thank you, i will take a look and let you know if i overcome the issue.

**Comment by deathblade89** [comment]
@lavrton 
Thank you for your help with this, it was what you expected it to be.
