### ISSUE TITLE
Is it possible to implement undo functionality

### ISSUE THREAD

**Issue by CrashyBang** [konvajs/konva#554]
I am using a lot of draggable images and was wondering if it is possible to implement an 'undo' drag feature, preferably with up to 5 possible undo's?

NOTE: I am using Konva with Vue.

Cheers.

**Comment by lavrton** [comment]
You have to implement it manually. Probably Vue community has some solutions for undo/redo.

Take a look into this demo made with `React` https://codesandbox.io/s/k31j2jjxov. I think it will be simple to adapt it to `Vue`.
