### ISSUE TITLE
Stage scale does not effect uploaded images

### ISSUE THREAD

**Issue by CrashyBang** [konvajs/konva#555]
I have a stage that is `1920x1080` but I have it scaled to about `0.5` however if I upload a `1920x1080` image it is larger than the canvas, in other words the image does not scale down with the canvas scale, is this the intended behavior?

If this is the intended behavior would the best course of action be to set the scale on the stage and images?

Cheers.

**Comment by lavrton** [comment]
Can you make a demo? Just tried this, works ok:

```javascript
const stage = new Konva.Stage({
  container: 'container',
  width: window.innerWidth,
  height: window.innerHeight,
});

var layer = new Konva.Layer();
var imageObj = new Image();
imageObj.onload = function() {

  var yoda = new Konva.Image({
    image: imageObj,
    width: stage.width(),
    height: stage.height()
  });

  // add the shape to the layer
  layer.add(yoda);

  stage.scaleX(0.5);
  stage.scaleY(0.5);
  // add the layer to the stage
  stage.add(layer);
};
imageObj.src = 'https://konvajs.github.io/assets/yoda.jpg';
```

https://jsbin.com/vumuxujobo/edit?html,js,output

**Comment by CrashyBang** [comment]
Sorry it was my fault I needed to scale after adding the image to the layer :).
