### ISSUE TITLE
Text doesn't render in y position like it's browser counterparts

### ISSUE THREAD

**Issue by guenyoo** [konvajs/konva#557]
Hello,

I've created a quick codepen for this issue:
https://codepen.io/anon/pen/MLaNpe

We would have expected the text to render like it's browsers counterpart in the y-position. Instead, depending on each different font, it renders randomly in the y-position and even gets cut-off when positioned on x: 0 and y: 0.

Is this a bug? Is there any way to make sure the text will render on the same height (just like the div's in my example)?.

Thanks in advance!

**Comment by lavrton** [comment]
Interesting issue. Need to think how to resolve such font with unusual metrics.

**Comment by markov00** [comment]
@guenyoo that effect is related to the `line-height`. 
I've played a bit and seems that there are some small difference on how it's computed the text height https://codepen.io/markov00/pen/OdOBKy
When CSS `line-height` is `normal` by default (is 1.2 of the font size by default). If I use the same value on Konva seems to have a better alignment than the one you linked but still is not perfect.
If I configure CSS `line-height:1` and konva `lineHeight:1.2` it align perfectly but not the second line.
So maybe @lavrton there is are some differences between the CSS implementation and Konva implementation on how to handle text translate (https://github.com/konvajs/konva/blob/master/src/shapes/Text.ts#L240-L242)

**Comment by lavrton** [comment]
Yeah. It is possible to have some differences. We have no goals to perfectly match CSS spec. But for sure it will be good to follow it when possible.

As for now, I don't see a clear way to resolve cut-off of such text. Even in HTML version, the text goes out of div container.

As a workaround you can try to use `padding` for Text nodes.

Now about `line-height`, currently Konva is useing `middle` text baseline for drawing. Probably we can switch into another default baseline and make different position calculations, so it will fit better with CSS spec.
