### ISSUE TITLE
Stage.clear()

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#558]
Hi @lavrton 

I am experiencing some weird issues around clearing the stage.

The implementation is : Draw stuff to stage, save to file. Open file.

When opening a file:

Method 1:
stage.clear()
// Expect stage to be cleared
draw elements based on file contents.

Method 2: 
MasterLayer -> get all ancestors, destroy all.
// Expect stage to be cleared excluding the master layer
draw elements based on file contents.

In both cases, when drawing back to the stage there are unexpected results. 

How long does it take to clear the stage? is there an event that can be listened on to know when i can start drawing back to the stage?

**Comment by lavrton** [comment]
`stage.clear()` and `layer.clear()` just clear a part of the canvas. It doesn't remove objects from the stage/layer.

**Comment by lavrton** [comment]
> How long does it take to clear the stage?

It is instant.

**Comment by deathblade89** [comment]
@lavrton 
What is the best way to "refresh" or "clear" a stage and all its nodes, layers and groups so as to start working on a brand new stage?

**Comment by lavrton** [comment]
`stage.destroyChildren()`

**Comment by deathblade89** [comment]
@lavrton 
I will give this a try and let you know if all is well.
Thank you as always for your response.

**Comment by sunilbisht2050** [comment]
We are using konva with angular application...on collapse of animation container, we are destroying stage object  (stage.destroyChildren() & stage.destroy & stage = null)  and on expand of container, we are initializing it....but we are observing many stage objects in chrome memory snapshot..seems like stage is not getting destroyed(released)..any idea what are we doing wrong ?

**Comment by lavrton** [comment]
@sunilbisht2050 hard to say. Can you make a demo?

**Comment by deathblade89** [comment]
@lavrton 
Hi there,

So i have used your advice and i am calling Stage.destroyChildren()

I then re-add a new master layer to the stage where all my groups are then added on.

I am receiving this error: TypeError: Cannot read property 'getCanvas' of null
    at Konva.Rect.drawScene (konva.js?c4b2:9011)
    at eval (konva.js?c4b2:8386)
    at Konva.Collection.each (konva.js?c4b2:296)
    at Konva.Group._drawChildren (konva.js?c4b2:8385)
    at Konva.Group.drawScene (konva.js?c4b2:8327)
    at Konva.Group.draw (konva.js?c4b2:4536)
    at ProductBase.AddText (ProductBase.js?0589:417)
    at ProductBase.ToggleGroups (ProductBase.js?0589:378)
    at ProductBase.Build (ProductBase.js?0589:47)
    at ProductBase.Initialise (ProductBase.js?0589:26)

**Comment by deathblade89** [comment]
@lavrton 
I do not, i re-create all nodes

**Comment by lavrton** [comment]
In that case, I need a demo. It looks like you have a shape on the node tree, that doesn't have access to its parent.

**Comment by deathblade89** [comment]
@lavrton 

Thanks for your assistance. I found another approach.

However, i did test the functions you provided and they all work as expected.
So this is not a Konva issue.

Thanks again.

**Comment by sikinski** [comment]
Why I can't clear the layer? I write layer.clear() and then nothing happens. I need to clear just one layer of the stage or a part of the layer from coords. Please help me

**Comment by huzhaoyu666** [comment]
Have you solved it? I found out `destroyChildren()`.
