### ISSUE TITLE
FastLayer does not respect position

### ISSUE THREAD

**Issue by pronebird** [konvajs/konva#56]
I use position to center layer on screen. FastLayer does not respect position and always renders itself in top/left corner.

**Comment by lavrton** [comment]
Right. It is kind of optimization. Skip any transform, except transform of shapes.

**Comment by pronebird** [comment]
I use stage transforms to scale and center all layers on stage. The only way I found to deal with scaling in browser.

I wrote a post on that 
https://coderwall.com/p/dy_dla/scale-your-kineticjs-game-dynamically

**Comment by pronebird** [comment]
Not sure if this should be addressed, but this makes FastLayer useless for me since I cannot center it on screen and it would be difficult weird to recalculate everything in absolute coordinates.

**Comment by pronebird** [comment]
Closing as #nofix for the time being as I lost an interest in fixing this, since I can easily swap FastLayer with regular Layer and performance is good enough.

**Comment by lavrton** [comment]
I still want to fix it as this behavior might be unexpected.

**Comment by pronebird** [comment]
Yeah I think it's pretty unexpected. I wouldn't mind if FastLayer could only render shapes or had no support for events or hit canvas, but lack of support for position and scale makes it hard to apply.

**Comment by pronebird** [comment]
:party:
