### ISSUE TITLE
Stage - To Image

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#560]
@lavrton 

I am faced with a requirement that i am not too sure on how to achieve.
Is there a way to increase the resolution of the output of the stage image?

The client wants a crisp image export of the stage. I have changed the quality to 1 but would like to know if there is more i can do to produce a clearer more higher quality image export?

**Comment by deathblade89** [comment]
@lavrton 
Hi there,

I found a work around for this, not too sure if its in the documentation, but i would advise to make it clear :)

.toDataURL({
pixelRatio: 2});

**Comment by lavrton** [comment]
I will update `pixelRatio` doc for that use case.

**Comment by lavrton** [comment]
https://konvajs.github.io/docs/data_and_serialization/High-Quality-Export.html
