### ISSUE TITLE
Underline bar is out of position

### ISSUE THREAD

**Issue by Fandangi** [konvajs/konva#566]
Hi - great work, I think Konva is very good.

I am working with text output and notice that when I use the underline text decoration with lineheight > 1 the underline bar is not where it would be by convention, which is on the text baseline.  In the fiddle here https://jsbin.com/luloxotape/edit?html,css,js,output, and seen in the result copied below, the area with the turqoise background is the output from Konva, and the pink is an HTML div element. 

Both have line height set at value 2. Notice though that the HTML version has the underline bar located at the baseline of the text, but the Konva version has the baseline at the bottom of the line.

![image](https://user-images.githubusercontent.com/16245859/52169404-a82d5480-272f-11e9-9910-baca667f0905.png)

**Comment by lavrton** [comment]
Thanks for the report. Fixed in the next `v3`. It will be released later.
