### ISSUE TITLE
toJSON() does not include filters

### ISSUE THREAD

**Issue by CrashyBang** [konvajs/konva#568]
When trying to use `toJSON()` on an `Image` everything is serialized except for the `filters` array, this has become `[null]`.

Cheers.

**Comment by lavrton** [comment]
Can you make a demo?

I tried right now, `json` doesn't have information about filters at all, and I don't think serializing filters is a good idea.

**Comment by CrashyBang** [comment]
Hey @lavrton ,

I can create demo but what you have just tried is exactly what I mean so all good there, I am inclined to agree with you that serializing them is a bad idea, would it be possible to convert them to an array of function names (just as strings) I think some record of the filters that were applied to an element when it was serialized would be useful.

If we are tracking things like the `red`,`green`,`blue` properties of a node shouldn't we also track the associated `RGB Filter`?

Cheers.

**Comment by lavrton** [comment]
@CrashyBang `red`, `green` are just simple numbers. It is simple to store them. But it is not so simple with filters. Serializing filters will make it hard to make `Konva` more modular.

As workaround you can just do this:

```javascript
shape.filters([Konva.Filters.RGB]);
shape.setAttr('filtersNames', ['RGB']);

// after deserialize from JSON:
const names = shape.getAttr('filtersNames') || [];
const filters = names.map(name => Konva.Filters[name]);
shape.filters(filters);
```

**Comment by CrashyBang** [comment]
@lavrton that's totally fair I am happy using something like the above solution to handle it if including it by default effects modularity.

Cheers!

**Comment by CrashyBang** [comment]
@lavrton would it be possible to get the `name` value on the filter functions set, currently it returns an empty string i.e:
```js
const filters = [Konva.Filters.RGBA, Konva.Filters.Emboss];
filters.map(filter => {
    console.log(filter.name); // returns ''
})
```
I have made a quick demo [here](https://codesandbox.io/s/7j1rlpzlkx) showing the issue.

This would be useful when you are working with existing filters i.e I have something like this:

```js
const existing = node.filters() || [];
// where effects.filters is an array of new filters to add to node
const filters = [...new Set([...effects.filters, ...existing])];
node.filters(filters);
```

Here you can see I am not just adding filters so I don't (easily) know the string value of the name of each filter to add it via `setAttr` this is where being able to iterate over the filter names would be useful so I could use `setAttr` before doing a `toJSON()`.

What are your thoughts?
Cheers.

**Comment by lavrton** [comment]
Looks like not all filter functions have names. It is possible, but need some refactoring in Konva core.


But, what is more, important for me, what do you need it at all? What is your use case?

**Comment by CrashyBang** [comment]
Basically I have implemented an `undoTree` and for ever change (drag, new filter, adjusting filter values) I commit a change to the `undoTree` which is essentially a serialized blob of the node state, I then allow the user to traverse the tree and apply the node state like so:

```js
// undoTree.index is the step the user is currently on (undoTree.history index)
// undoTree.history is the array of serialized blobs
Object.entries(undoTree.history[undoTree.index].attrs).map(property => {
          const name = property[0];
          const value = property[1];

          node[name](value);
});
layer.batchDraw();
```

**Comment by lavrton** [comment]
Your approach is good, but I suggest to go differently. I wrote large tutorial about it: https://konvajs.github.io/docs/data_and_serialization/Best_Practices.html
I hope it will be helpful.

About the issue. I don't think we should serialize filters into JSON. You have to implement your workaround.

**Comment by CrashyBang** [comment]
Hey @lavrton,

I checked out your tutorial, while that is a good way to handle the undo state of a lot of nodes, however it still suffers the same problem in the sense that you can not track the filters of the nodes as you undo/redo.

Cheers.

**Comment by lavrton** [comment]
Right, you can't save them directly. But it is very simple to save meta-information about filters. You can see in the demo how filters are handled. In your case, you may need another shape of the state, and probably save filters as an array of names.
