### ISSUE TITLE
Konva Image with PDF

### ISSUE THREAD

**Issue by BG687** [konvajs/konva#570]
I have a bug, but it is time-consuming to reproduce and very quick to describe. I am unable to load a Konva Image object in my canvas if the source is a PDF. Are there any known workarounds for this? Any suggestions welcome.  

Thank you.

**Comment by lavrton** [comment]
As far as I know, PDF is not an image. It is a very complex document format. Probably you can use something like this https://mozilla.github.io/pdf.js/ to render pdf and then use it somehow.

**Comment by theluk** [comment]
Hello there,

because pdf.js is rendering to a canvas, I was wondering if it is possible to use pdf.js and konva together. Maybe there is some kind of wrapping possible where we manage layers, groups with konva and give a mechanism for pdf.js to render to the canvas. 

Currently I render the pdf using pdf.js into a canvas and from there to an image, which I then import back into a canvas using Konva. Seems like there is a unnecessary step in between.

**Comment by dylan-westbury** [comment]
@theluk currently doing the same, wonder if there is a better alternative also. Our use case is so the user can sign the PDF document  then re-convert to PDF.

**Comment by theluk** [comment]
@dylan-westbury 

My solution: 
The idea is simple, because you can render one canvas to another, I just use the pdfjslib to render the pdf on a canvas, and then I use the Shape with which I then simply render the one canvas to the other. 


```
import { Shape } from "react-konva";
import { pdfjsLib } from "../../service/pdf";

type Props = {
  pdfCanvas: HTMLCanvasElement;
  width: number;
  height: number;
};

export const getPdfImageCanvas = async (
  pdf: pdfjsLib.PDFDocumentProxy,
  page: number
): Promise<{
  canvas: HTMLCanvasElement;
  width: number;
  height: number;
}> => {
  const pdfPage = await pdf.getPage(page);
  const viewport = pdfPage.getViewport({ scale: 1.333 });
  const canvas = document.createElement("canvas");
  const context = canvas.getContext("2d");
  if (context) {
    canvas.height = viewport.height;
    canvas.width = viewport.width;
    const renderContext = {
      canvasContext: context,
      viewport,
    };
    await pdfPage.render(renderContext).promise;
  }
  return {
    canvas,
    width: viewport.width,
    height: viewport.height,
  };
};

export default function PDFShape({ pdfCanvas, width, height }: Props) {
  return (
    <Shape
      width={width}
      height={height}
      sceneFunc={(context) => {
        context.drawImage(pdfCanvas, 10, 10);
      }}
    />
  );
}
```

**Comment by FaisalRasheed1174** [comment]
> @theluk currently doing the same, wonder if there is a better alternative also. Our use case is so the user can sign the PDF document then re-convert to PDF.

Have you found any solution to that /
