### ISSUE TITLE
“Total canvas memory use exceeds the maximum limit (256MB)” error on iPad using big canvas

### ISSUE THREAD

**Issue by SWebDevelop** [konvajs/konva#571]
I have a KonvaJS app with a "draw" functionality. On the mouse move event, I'm creating a new Line and adding points to it.

It works perfect on Desktop but it crashes on iPad. This is the issue that I get:

`Total canvas memory use exceeds the maximum limit (256MB)`

It's fired on this part of the KonvaJS library:

```
setHeight: function(t) {
    this.height = this._canvas.height = t * this.pixelRatio, this._canvas.style.height = t + "px";
    var e = this.pixelRatio;
    this.getContext()._context.scale(e, e)
},
```

The line that fires the error is:

`this.getContext()._context.scale(e, e)`

This error only happen when I'm using a big canvas size (example: 1200x1500px).
Any ideas of how to fix this issue?

Thanks in advance!

**Comment by SWebDevelop** [comment]
I'm using just one layer. But I didn't use caching. I'll take a look.

Anyway, I can't find a clear way to fix this issue. I'll continue trying and I'll keep this updated with my progress. I don't know if someone is dealing with the same problem.

**Comment by MaxGraey** [comment]
@SWebDevelop 
https://discussions.apple.com/thread/4975106

So it seems max size is 1024x1024 for iOS in Safari

**Comment by lavrton** [comment]
I had this issue a long time ago. I reduced canvas usage and that helped me.
Also, you can try to reduce pixelRatio: `Konva.pixelRatio = 1`, but the canvas will be blurred a bit.

Fill free to add more info, if you have it.

**Comment by willyou** [comment]
I think this is an issue of Safari. Please check [here](https://developer.apple.com/forums/thread/687866)

**Comment by offs-bach** [comment]
I had that issue `Total canvas memory use exceeds the maximum limit (384 MB)` . I used many tricky solution to solve that, but it does NOT work. @lavrton Do you have any solution for that one?

**Comment by lavrton** [comment]
You need to profile memory. See what exactly consumes that much.

**Comment by offs-bach** [comment]
@lavrton Thanks for your response. I checked and the HTMLCanvas are increasing. Does it enough information for providing solution?
![image](https://user-images.githubusercontent.com/91860521/187593959-5876e9a1-6108-44c0-82db-d85cfa2f16a9.png)
![image](https://user-images.githubusercontent.com/91860521/187594005-a7fa0504-0141-47e8-b71d-70915d820313.png)

**Comment by lavrton** [comment]
Well, solution is on your side. You see that a lot of HTMLCanvasElements are in memory. Do you use cache a lot? Do you destroy shapes correctly? Do you destroy stages?

**Comment by VForsmann** [comment]
Hey @lavrton.
Same case with me.
I use Konva to dynamically print to 3D elements in three.js.
In doing so, I dynamically create and remove Konva Stages.
I also use destroy, & remove.

After a few iterations, I also get a memory problem on iOS - and only on iOS.

The number of canvases remains high, despite destroy & remove.
I'm not entirely sure if this is a Safari problem, but I could imagine it.

**Comment by VForsmann** [comment]
Must correct: Just tested on macOS.
Also in desktop Safari the memory size increases with each iteration.

**Comment by VForsmann** [comment]
Just built a sandbox to rule out the error on my part: 
https://6yvn7o.csb.app/

And surprise: It works as it should. Safari clears the memory correctly.

I searched further in my application: I managed Konva-Stages in React.useState. In doing so, shallowCopys were created.
The old objects are not cleared by the garbage collector - for whatever reason.
Safari definitely does this differently than Chrome here.

Sorry :) Maybe this helps anyways.

**Comment by zarv1k** [comment]
@VForsmann I made PR recently,  #1442. I don't use cache(), but in my SPA I create/remove different stages (render via `react-konva`) many times during one app lifecycle. That PR fixes resources releasing in iOS, I have no issues with that anymore after that fixes applied. Waiting it to be merged & published.
