### ISSUE TITLE
Constrained transformers

### ISSUE THREAD

**Issue by jonathan-roy** [konvajs/konva#572]
Hi,

Is there any easy way to constrain transformations (resizing and rotation) so that the transformed shape never goes beyond the stage size? I know there is `boundBoxFunc` but I find it difficult and tedious to implement this.

By the way, is there a way to get the node attached to a Transformer?

Thanks!

**Comment by lavrton** [comment]
What did you try? In `boundBoxFunc` you have arguments with the full size/position info about your node. Why it is hard for you to use them?

> By the way, is there a way to get the node attached to a Transformer?

This?
```javascript
transformer.getNode();
```
