### ISSUE TITLE
Unable to apply filters to nodes that have been transformed

### ISSUE THREAD

**Issue by CrashyBang** [konvajs/konva#573]
Once I attach a node to the transformer I can no longer apply filters.

I have the following:
```js
const transformerNode = this.$refs.transformer.getStage();
const selectedNode = this.getNodeByIndex(this.activeNode);
transformerNode.attachTo(selectedNode);
```

Then I try to apply filters like so:
```js
const transformerNode = this.$refs.transformer.getStage();
const node = this.getNodeByIndex(this.activeNode);
const layer = node.getLayer();
            
transformerNode.detach();

node.filters([Konva.Filters.RGBA]);
node.red(88);
node.alpha(0.5);

layer.batchDraw();
```

I can create a demo I just wanted to check this wasn't intentional or by design before I attempted to create a demo.

Cheers.

**Comment by lavrton** [comment]
Filters should work just fine with Transformer. Please make a demo.

**Comment by CrashyBang** [comment]
@lavrton my fault was not caching node before layer re draw.
