### ISSUE TITLE
toJSON() serialization does not serialize arrays

### ISSUE THREAD

**Issue by dheil** [konvajs/konva#576]
Hi, 
in the latest version (3.0.0) the serialization of arrays does not work it seems.
When i run the following fiddle: https://jsfiddle.net/48we6as3/1/ 
everything works as expected and both arrays (testArrayRect and testArrayGroup) are there - the Konva version there is 2.6.0.

When is use the code on my computer with Konva version 3.0.0 the arrays are simply missing. 

Am i missing out somewhere or is the toJSON() method really broken?

##EDIT##
i found, that the following extension of 'toObject' is missing in Konva 3.0.0:

    toObject: function() {
      var obj = Konva.Node.prototype.toObject.call(this);
      obj.children = [];
      var children = this.getChildren();
      var len = children.length;
      for (var n = 0; n < len; n++) {
        var child = children[n];
        obj.children.push(child.toObject());
      }
      return obj;
    }

Why has it been removed?

**Comment by lavrton** [comment]
I fixed the bug. Thanks a lot for the report. 👍
