### ISSUE TITLE
getContainer & _setPointerPosition is missing it typescript definitions 

### ISSUE THREAD

**Issue by zivni** [konvajs/konva#578]
I'm flowing the example here: https://konvajs.github.io/docs/sandbox/Drop_DOM_Element.html

and I see that `getContainer` & `_setPointerPosition` is missing in konva.d.ts

**Comment by lavrton** [comment]
use `stage.container()` instead of `stage.getContainer()`. `stage._setPointerPosition()` is deprecated. Please use `stage.setPointersPositions(event);`

I just published new `Konva` version 3 with new typescript definitions. Please let me know if you see any issues with it.
