### ISSUE TITLE
Stage.toDataURL() invalid output on Retina

### ISSUE THREAD

**Issue by pronebird** [konvajs/konva#58]
Works fine on pixelRatio = 1 though.

![screenshot 2015-04-16 00 11 18](https://cloud.githubusercontent.com/assets/704044/7170308/57c0d3f4-e3cd-11e4-8656-9032aea233f7.png)

```js
var image = document.getElementById('tiger');

Konva.pixelRatio = window.devicePixelRatio; // 1

var stage = new Konva.Stage({
    container: 'konva-container',
    width: 640,
    height: 480
});
var layer = new Konva.Layer();
var tiger = new Konva.Image({
    image: image,

    // assume tiger is in 2x scale
    width: image.width * 0.5,
    height: image.height * 0.5,
    
    draggable: true
});

tiger.cache();
tiger.drawHitFromCache();
layer.drawHit();

layer.add(tiger);
stage.add(layer);
stage.draw();

var snapshotStage = new Konva.Stage({
    container: 'konva-container2',
    width: 640,
    height: 480
});

stage.toImage({
    callback: function (image) {
        var imageNode = new Konva.Image({
            image: image
        })
        var snapshotLayer = new Konva.Layer();
        snapshotLayer.add(imageNode);
        snapshotStage.add(snapshotLayer);
        snapshotStage.draw();
    }
});
```

**Comment by lavrton** [comment]
The result is might be unexpected for first look. But I think it is correct.

After using `toImage` you have high resolution picture. So you need to scale in when you add it to layer.
In the same way as 2x images are added to page with css (`images/box-bg@2x.png` is 400X400):
```css
.box{
        background:url('images/box-bg@2x.png') no-repeat top left;
        background-size: 200px 200px;
}
```

**Comment by pronebird** [comment]
That's what I thought first too. toImage returns the same 640x480. It should be twice larger for hi-res right?

**Comment by lavrton** [comment]
Right. Might be another (not only 2x) size depend on ratio.

**Comment by pronebird** [comment]
`toDataURL` uses SceneCanvas with pixelRatio = 1. I have tested once again on my game and 2x is horribly broken. The issue is with cached elements only. Non cached elements are rendered properly. I'll look into this when I think, preliminary I think we forgot to shrink image and I bet we use the same `drawImage` to paint cached elements.
