### ISSUE TITLE
Nested caching doesn't work

### ISSUE THREAD

**Issue by vytisb** [konvajs/konva#581]
Caching a parent element clears caches of all children.

Example: https://jsfiddle.net/vytisbalto/u69vgq4p/17/
Same example with Konva 2.5.1, working correctly: https://jsfiddle.net/vytisbalto/u69vgq4p/18/
In this example, inner group (`maskGroup`) is cached so that `globalCompositeOperation` would work, and outer group (`group`) is cached so that compositing would not clobber the background.
However, with Konva 2.6.0, `group.cache()` clears the `maskGroup` cache and then draws it without `globalCompositeOperation`.

I suspect this is related to this commit: https://github.com/konvajs/konva/commit/2404368ec83f0c55cb8c1568cb36a63542a75dbc
Moving this line below the `if` seems to fix my problem, but i don't know full implications of such fix. https://github.com/konvajs/konva/blob/26d40ae1f909b676cb4d3291abb0ab47382b54c4/src/Node.ts#L188-L193

**Comment by lavrton** [comment]
Thanks for the report. Fixed that bug and other related cases. Will be released later as v3.
