### ISSUE TITLE
Util.haveIntersection not included in typings

### ISSUE THREAD

**Issue by gabrielchiquini** [konvajs/konva#582]
Hi, I've found the typings file about the `Util` class (konva.d.ts, line 95) is missing `haveIntersection` method.  
Maybe a proper correction should add the following line :
 `static haveIntersection(r1: SizeConfig, r2: SizeConfig): boolean;`

**Comment by lavrton** [comment]
Now it is in type definitions. All types are generated from the source code now. Let me know if you have any other issues.
