### ISSUE TITLE
Konva 2.4.2 find() function error

### ISSUE THREAD

**Issue by fdebodinat** [konvajs/konva#583]
I have a piece of code that worked just fine with Konvajs.2.0.2.

`var startCity = mainStage.findOne('#0');`

It would return the node with the ID=0. Works like a charm in the 2.0.2 version.

But know when I udpate to 2.4.2, this does not find the node anymore and returns a JS error (object undefined). It works for any other IDs on the map (2,3,4,etc).

I checked and printed all the node and there is definitely one with ID=0;

Any information or clue on what could have changed in the `find()` or `findone()` function between those 2 releases? Is it something like you cannot have an ID=0 anymore maybe?

Thank you.

**Comment by fdebodinat** [comment]
I have a piece of code that worked just fine with Konvajs.2.0.2.

`var startCity = mainStage.findOne('#0');`

It would return the node with the ID=0. Works like a charm in the 2.0.2 version.

But know when I udpate to 2.4.2, this does not find the node anymore and returns a JS error (object undefined). It works for any other IDs on the map (2,3,4,etc).

I checked and printed all the node and there is definitely one with ID=0;

Any information or clue on what could have changed in the `find()` or `findone()` function between those 2 releases? Is it something like you cannot have an ID=0 anymore maybe?

Thank you.

**Comment by lavrton** [comment]
The behavior was slightly changed.

Now `id` cannot have values that `== null` (like empty string or 0).

To fix the issue you can convert number 0 to string `"0"`. Or use another id.
