### ISSUE TITLE
Why transform changes scale of a Rect instead of height and width?

### ISSUE THREAD

**Issue by adriancubillos** [konvajs/konva#584]
Thank you for submitting an issue!

Please make sure to check current open and closed issues to see if your question has been asked or answered before.
If you have just a question (not a bug or a feature request) it is better to ask it in [Stackoverflow](http://stackoverflow.com/questions/tagged/konvajs).

If you have a bug, please, try to create a reproducible example with jsfiddle (or any similar service).
You can use [this JSBIN](https://jsbin.com/tekehizuta/1/edit?html,js,output) as a template.

**Comment by adriancubillos** [comment]
looking at this doc sample https://konvajs.org/docs/select_and_transform/Transform_Events.html i noticed the width and height of the shape does not change but it scale does isn't it a bug?

**Comment by lavrton** [comment]
It is not a bug. That is by design.
