### ISSUE TITLE
Applying filters causes pixelation on text node transform.

### ISSUE THREAD

**Issue by CrashyBang** [konvajs/konva#587]
Example here: https://codesandbox.io/s/rrk8o7xmoo

If you try to resize "New Test" text it will be pixelated (filters are applied on select) if you remove the filter code:
```js
node.red(200);
node.alpha(0.6);
node.filters([Konva.Filters.RGBA]);
node.cache();
```

And resize pixelation will not occur.

Not sure if this is by design or a bug.

**Comment by lavrton** [comment]
That is correct behavior because the node is cached. As a workaround, you can cache with the high `pixelRatio`.

**Comment by CrashyBang** [comment]
Hey @lavrton,

what would that look like? Do you simply mean a large pixel ratio like:
```
node.cache({
    pixelRatio: 10
})
```

Or can I generate it dynamically based on the transform size?

**Comment by lavrton** [comment]
Yes. Also, you can adjust `pixelRati`o during resizing. Like, recache the shape on `transformend` event.

**Comment by CrashyBang** [comment]
Hey @lavrton,

Ended up caching on resize based off the scale, i.e:

```js
const scale = Math.max(
    node.toObject().attrs.scaleX,
    node.toObject().attrs.scaleY
);
// @NOTE really big text does cost
node.cache({
    pixelRatio: scale
});
```

Cheers.
