### ISSUE TITLE
Serializing stage child information.

### ISSUE THREAD

**Issue by CrashyBang** [konvajs/konva#588]
Hey,

In #568 we discussed the serialization of filters when using `toJSON()`, I understand why you do not want to, however I am now in a position where I am trying to serialize the canvas (`stage`) and while it stores all the children layers/nodes/etc... it does not include any filter information and I am wondering if it is worth including a filter array/object as part of the serialization, something like:

```js
filters: ['RGBA', 'Noise']
```

Now I am going to have to do this either way, what I am interested in is if it would be worth adding to the `konva` core, I would also have to add something like a `stage.fromJSON(blob)` that could take the JSON and re-create the stage.

I know in [this](https://github.com/konvajs/vue-konva/issues/16) issue you talk about serializing the data itself and then just loading that into the stage, however this can get tricky when you have multiple data sources/layers/etc... 

The above method does also not include any of the canvas info (width/size/etc...) if you are trying to create the `stage` somewhere else, finally it suffers from the same filter serialization issue as described above.

Let me know what you think, I think it would be quite neat to be able to take a _snapshot_ of the entire canvas and re-create it somewhere else hassle free, I believe this would also mean you could create a `stage` using something like `vue-konva` then recreate it normal `konva` with one line...

**Comment by lavrton** [comment]
https://konvajs.org/docs/data_and_serialization/Best_Practices.html
