### ISSUE TITLE
Transformer demo bug

### ISSUE THREAD

**Issue by ThoughtZer** [konvajs/konva#589]
Hi:
    When I tried demo on konvajs, I found that transformer sometimes triggered a wireframe that displayed the previously selected graphics. Please take a look at the screenshot.

![image](https://user-images.githubusercontent.com/23690568/53462217-096dec80-3a7e-11e9-859b-ee7f5d758547.png)

**Comment by richpeers** [comment]
noticed this also, issue actually present here https://konvajs.org/docs/select_and_transform/Basic_demo.html

**Comment by ThoughtZer** [comment]
oh, thx. 

I didn't go through the document carefully.

It seems that I have to go to threejs. oh no~

**Comment by lavrton** [comment]
Fixed. Thanks for the report.
