### ISSUE TITLE
darthVaderImg.draggable(true) does not work on mobile

### ISSUE THREAD

**Issue by richpeers** [konvajs/konva#590]
Using the funciton here https://konvajs.org/docs/drag_and_drop/Drag_an_Image.html
The image does not drag on mobile

Tried removing `draggable:true,` from the Konva.Image(options)
and adding`darthVaderImg.draggable(true);`

both ways enable dragging on desktop, but do not work on mobile.

**Comment by richpeers** [comment]
This is version 3.0.0   Seems to work with 2.6.0 only found this library yesterday. Keep up the good work!

**Comment by lavrton** [comment]
Thanks for the report. Will find a fix now.

**Comment by lavrton** [comment]
Fixed and published as `konva@3.1.2`
