### ISSUE TITLE
Overridden fillStrokeShape() isn't used with opacity changes or filters

### ISSUE THREAD

**Issue by shahgahmed** [konvajs/konva#592]
Very related to [#585 ](https://github.com/konvajs/konva/issues/585) - added a comment but I believe  it is a separate issue.

After you override the fillStrokeShape() function (in this case, specifically to draw stroke and then fill), if you use opacity less than 1, or a filter on text, the overridden method is not used.

<img width="335" alt="screen shot 2019-03-01 at 1 09 41 pm" src="https://user-images.githubusercontent.com/33299803/53666591-563ef800-3c23-11e9-8ed3-cea316bd587f.png">

Demo: 
https://codepen.io/anon/pen/NJNPyd

@lavrton Thank you so much for the valuable project!

**Comment by lavrton** [comment]
You need to overwrite `Konva.Context.prototype.fillStrokeShape`. 

https://codepen.io/lavrton/pen/zbdveR

**Comment by shahgahmed** [comment]
Thanks so much @lavrton !
