### ISSUE TITLE
TypeScript support on newer version

### ISSUE THREAD

**Issue by Pi-Bouf** [konvajs/konva#593]
Hello !

In latest updates, there are not konva.d.ts, it will be difficult to use it with TypeScript...
It's normal, or there are a method for generate it ?

Thank's a lot :)

**Comment by lavrton** [comment]
Type definitions are generated from the source code now. They are not included in the repo, but you can find them in `npm` package. So soon it should be much better. But I made a mistake in them in the last release, so `Konva` is just `any` (not very smart types). I am going to fix it soon.

**Comment by Pi-Bouf** [comment]
Ooooh OK ! Thank you !

Just for info: how to generate it ?

**Comment by lavrton** [comment]
`npm run compile` from the root of the repo will generate them.

Now typescript support should be better. Some minor fixes are still in the progress.
