### ISSUE TITLE
Problems with filters and shadows，the filter will affect the shadow

### ISSUE THREAD

**Issue by z411500976** [konvajs/konva#595]
When the filter is used with the shadow, the filter will affect the shadow. Because the PS layer style is needed, the filter does not affect the shadow. Is there any way to achieve it? I am not familiar with konva, thank you.

**Comment by lavrton** [comment]
To do that you can cache and apply filters to a node WITHOUT shadows, then convert node into image https://konvajs.org/api/Konva.Node.html#toImage. Then create `Konva.Image` with that image and apply shadow to it.
