### ISSUE TITLE
Passing children in using `setAttrs()` on stage.

### ISSUE THREAD

**Issue by CrashyBang** [konvajs/konva#597]
I am trying to use a blob similar to this:
```js
{
    attrs: {
        scaleX: 0.58,
        scaleY: 0.58,
        width: 1113.6,
        height: 626.4
    },
    className: "Stage",
    children: [{
            attrs: {
                name: "textLayer"
            },
            className: "Layer",
            children: [{
                    attrs: {
                        fill: "rgba(255, 0, 0, 1)",
                        index: 0,
                        draggable: true,
                        text: "Example Text",
                        fontFamily: "Bangers",
                        fontSize: 60,
                        x: 222.41379310344828,
                        y: 268.9655172413793,
                        scaleX: 4.43772935901027,
                        scaleY: 4.43772935901027
                    },
                    className: "Text",
                    filters: []
                },
                {
                    attrs: {},
                    className: "Transformer"
                }
            ]
        }
    ]
}
```
To the stage via `setAttrs()` unfortunately the stage does not update at all (including the top level attributes like size and scaling).

I have also tried a `batchRedraw()` still no difference.

Cheers.

**Comment by CrashyBang** [comment]
Scratch that, the size and scaling are applying.

**Comment by lavrton** [comment]
What are you trying to do? I see here JSON of canvas stage. You can't use it in `setAttr`. There is `Konva.Node.create(json)` function for that.

**Comment by CrashyBang** [comment]
Hey @lavrton,

I am trying to create a canvas from a blob of data, it looks like `Konva.Node.create()` is what I want but because I am using `Vue` to set everything up and my stage already exists with layers (which are fixed) I think what might be easier is to actually apply the attributes to the stage via `setAttrs` and then to iterate each layer and add manually add the children from the blob using `add()` this way I don't need to destroy/create the stage and it's layers...

**Comment by lavrton** [comment]
If you are using `vue` I don't recommend to change or add nodes manually. You should do everything from your template. If you want to do things manually you can use `Konva.Node.create()` to create a layer and add it into created Stage.

Probably this post will be useful to understand how to work with saving/loading canvas: https://konvajs.org/docs/data_and_serialization/Best_Practices.html
