### ISSUE TITLE
Konva 3.1.7 trouble importing Typescript module.

### ISSUE THREAD

**Issue by skid** [konvajs/konva#598]
Hi, I have trouble importing Konva 3.1.7 in my typescript project. Using VSCode 1.32 and Typescript 3.3.3

Trying with asterisk imports:
```typescript
import * as Konva from 'konva';

const stage: Konva.Stage
// Namespace '"...node_modules/konva/types/index-types"' has no exported member 'Stage'
```

Trying with default imports:
```typescript
import Konva from 'konva';

const stage: Konva.Stage
// Cannot find namespace 'Konva'
```

I installed Konva with yarn: `yarn add konva@3.1.7` (the default listed version is 2.6.0)
Here's my tsconfig:
```json
{
  "compilerOptions": {
    "outDir": "./build",
    "sourceMap": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "jsx": "react",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noImplicitAny": true,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "baseUrl": ".",
    "target": "es6",
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*.ts", "src/**/*.tsx"],
  "exclude": ["build", "node_modules", ".git", ".vscode"]
}
```

**Comment by ChristianSchieder** [comment]
[3.1.0][2019-02-27]
Make Konva modular: import Konva from 'konva/lib/Core';

From the Change-Log

**Comment by lavrton** [comment]
Ah. Typescript is hard. This code will work just fine:
```javascript
import Konva from 'konva';

const stage = new Konva.Stage()
```

Thinking how to resolve the issue.

**Comment by lavrton** [comment]
Should be fixed with the new `konva@3.2.0`. Please try, and let me know how it works.

**Comment by epatters** [comment]
Thank you @lavrton, that seems to have fixed many problems.

Here is a more minor error I'm encountering. In TypeScript, unlike in JavaScript, optional function argument must be explicitly marked as such. For example, the signature for `Node.findAncestors` is

```
findAncestors(selector, includeSelf, stopNode)
```

but should be

```
findAncestors(selector?, includeSelf?, stopNode?)
```

There are probably many such functions that need to be updated.

**Comment by lavrton** [comment]
You are right. Will fix that. Any related Pull Requests are very welcome.

**Comment by skid** [comment]
@lavrton Seems to be working with 3.2.0.
I noticed that `Vector2d` is not available in the Konva namespace, so I need to import it like this:
```
import {Vector2d} from 'konva/types/types`;
```

Is this also as intended?

**Comment by lavrton** [comment]
@skid why do you need `Vector2d`?

**Comment by skid** [comment]
@lavrton One example is when I make a wrapper for Konva's methods - I need to have the same type for the wrapper method parameters if it's being passed down to Konva.

**Comment by lavrton** [comment]
We may make `Vector2d` public as well. But I am not sure it is required. You can just use the same shapes of the types and it will work.

**Comment by nathanloisel** [comment]
I use Vector2d as well and I use it everywhere on my project. My project is based on konva so I use konva's available types ;)

**Comment by lavrton** [comment]
Added `Vector2d` into `Konva`. You can try in version `3.2.4`.

**Comment by RobbertWolfs** [comment]
We have the same problem as you @skid 
We are also using rollup but can't get it to work with the solution above...

any suggestions?

**Comment by skid** [comment]
@RobbertWolfs - If it's added in the Konva namespace as lavrton's comment suggests then you should be able to just import Vector2d properly.

**Comment by RobbertWolfs** [comment]
Sorry I mean I have the same problem as your original issue.. 

> Hi, I have trouble importing Konva 3.1.7 in my typescript project. Using VSCode 1.32 and Typescript 3.3.3
> 
> Trying with asterisk imports:
> 
> ```ts
> import * as Konva from 'konva';
> 
> const stage: Konva.Stage
> // Namespace '"...node_modules/konva/types/index-types"' has no exported member 'Stage'
> ```
> 
> Trying with default imports:
> 
> ```ts
> import Konva from 'konva';
> 
> const stage: Konva.Stage
> // Cannot find namespace 'Konva'
> ```
> 
> I installed Konva with yarn: `yarn add konva@3.1.7` (the default listed version is 2.6.0)
> Here's my tsconfig:
> 
> ```json
> {
>   "compilerOptions": {
>     "outDir": "./build",
>     "sourceMap": true,
>     "module": "commonjs",
>     "moduleResolution": "node",
>     "jsx": "react",
>     "experimentalDecorators": true,
>     "emitDecoratorMetadata": true,
>     "noImplicitAny": true,
>     "noUnusedParameters": true,
>     "noUnusedLocals": true,
>     "baseUrl": ".",
>     "target": "es6",
>     "allowJs": false,
>     "allowSyntheticDefaultImports": true,
>     "skipLibCheck": true
>   },
>   "include": ["src/**/*.ts", "src/**/*.tsx"],
>   "exclude": ["build", "node_modules", ".git", ".vscode"]
> }
> ```

**Comment by skid** [comment]
@RobbertWolfs - it's solved in 3.2.0 - I upgraded and I can confirm that the issue no longer exists.

**Comment by mizunashi-mana** [comment]
I cannot solve this issue on 3.2.5 yet.

```typescript
import Konva from 'konva';

const stage = new Konva.Stage();
```

is compiled correctly and raises error: `TypeError: Konva.default.Stage is not a constructor.` .

Exactly, it seems that konva index does not have `default` property: https://github.com/konvajs/konva/blob/3.2.5/src/index.ts#L7 (, but core has `default` property: https://github.com/konvajs/konva/blob/3.2.5/src/Core.ts#L7 ).

I wrote magic code such as:

```typescript
import * as KonvaW from 'konva';

const Konva: typeof KonvaW.default = <any>KonvaW;

const stage = new Konva.Stage();
```

This works well.  Is there anyone has been running `konva` with TypeScript really?  I think 3.2.x cannot fix this issue completely.

**Comment by lavrton** [comment]
@mizunashi-mana can you make a reproducible repository for your issue?

**Comment by mizunashi-mana** [comment]
Here: https://github.com/mizunashi-mana/konva-ts-webpack-sample

I found this issue happened with webpack .  `webpack` uses `module.exports` for module resolution.

**Comment by lavrton** [comment]
You need to use `allowSyntheticDefaultImports = true` for the ts. Full config, that I was using and works ok:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "esnext",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "declaration": true,
    "declarationMap": true,
    "removeComments": true
  }
}
```

**Comment by mizunashi-mana** [comment]
@lavrton Thanks.  I solved with:

```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "esModuleInterop": true
  }
}
```

However, I am worried this option breaks other module imports.  Are there reasons why konva needs this option for TypeScript and Webpack?

**Comment by lavrton** [comment]
It is not only Konva. Many libs that written not in es modules need those options.

**Comment by mizunashi-mana** [comment]
@lavrton Oh... I remained with old typescript knowledge.  OK, I understand.  Very thanks.

**Comment by Ivanca** [comment]
`"allowSyntheticDefaultImports": true,` created an issue where the browser was setting "Konva" to `undefined`, probably better not use it with webpack

**Comment by julianpoemp** [comment]
> Ah. Typescript is hard. This code will work just fine:
> 
> ```js
> import Konva from 'konva';
> 
> const stage = new Konva.Stage()
> ```
> 
> Thinking how to resolve the issue.

I had the same issue. This fixed it for me. Konva 4.0.9. I didn't need any changes in my tsconfig.json
