### ISSUE TITLE
IE11 does not support Object.assign

### ISSUE THREAD

**Issue by davidsarkany** [konvajs/konva#599]
[IE11 does not support Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility) please use [Polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill)

**Comment by lavrton** [comment]
Fixed in `konva@3.2.0`. Thanks for the report.
