### ISSUE TITLE
Crash in Konva.Animation._runFrames

### ISSUE THREAD

**Issue by pronebird** [konvajs/konva#60]
Hi,

I experience some weird bug in `Konva.Animation._runFrames`. It seems it is related to delayed frame update after Konva.Tween already destroyed.

```
[Error] TypeError: undefined is not an object (evaluating 'layer._id')
	_runFrames (konva.js, line 10124)
	_animationLoop (konva.js, line 10140)
```

There is a warning in code saying that `animations.length` should not be cached as it may change.

The crash happens on the following line:

https://github.com/konvajs/konva/blob/master/src/Animation.js#L235

Scope: 

- `layer = undefined`
- `animations.length = 0`
- `layers` is empty. 
- `func` points to `that.tween.onEnterFrame`

This happens shortly after I destroy all tweens and then all layers on stage.

My tearDown method looks as following:

```js
tearDown: function () {
  log('tearDown');

  // cancel and destroy all tweens
  _.invoke(this._tweens, 'destroy');

  // destroy layers
  _.invoke(this._layers, 'destroy');
},
```

tweens array contains `Konva.Tween` and layers array contains `Konva.Layer`.

I started digging around a little bit and I can't find for example whether `Konva.Sprite` stops animation or interval when it's destroyed. I use animated sprites so that's one of my thoughts why this may happen.

**Comment by pronebird** [comment]
Turns out I destroyed the layer before stopping animation.

**Comment by lavrton** [comment]
Hm.. May be it is a bug. Animation should handle deleted layers, right?

**Comment by pronebird** [comment]
Maybe this can be reproduced if you have couple of Tweens running and you destroy everything in onFinish in one of them.

**Comment by lavrton** [comment]
I can not reproduce. @pronebird it would be nice if you can provide an example.

**Comment by lavrton** [comment]
As I can nit reproduce the bug I will close the issue. Reopen if you have more info.
