### ISSUE TITLE
Tweening of fillPatternImage #enhancement

### ISSUE THREAD

**Issue by dheil** [konvajs/konva#603]
Hi, 
am i missing out a possibility how to tween a fillPatternImage?
I'd like to fade an image into a fill color and vice versa.

A problem i have here is, that the base/default background color of an image is black. And when i start the tween (where i fade in a fill-color) on mouseenter, the image blinks into black.

A quick fix would be, if one could set the background color of a fillPatternImage - like fillPatternBackground or something alike.

**Comment by lavrton** [comment]
As for now, I am not sure how we can implement it from Konva side. Tweening from image to color looks complex. 

As a workaround, I suggest using two shapes. One is with fillImage, another is with fillColor. Then you can opacity to fade in from one into another shape.
