### ISSUE TITLE
white screen in safari when using konva

### ISSUE THREAD

**Issue by vicwang163** [konvajs/konva#608]
I don't know how it happens, but only occur in the safari sometimes.
BTW, I use the native method of canvas to render element，it fails too

**Comment by lavrton** [comment]
Do you have a demo or something?

**Comment by VividWombat** [comment]
I get the same result when using safari on ipad. sometimes no stage at all. sometimes I get lines but no image

I'm investigating how to get all images loaded before making stage visible. as theres a known issue with safari and images that arent loaded when adding to DOM.

I dont understand why sometimes the stage doesnt load when it initially only has lines (grid). it doesnt happen on chrome for IOS on same device.

**Comment by vicwang163** [comment]
maybe it's not a issue of konva framework, as I found that it didn't happen when I try to use native canvas api to draw the geometry

**Comment by lavrton** [comment]
I saw that issue in one app. The main issue was in canvas memory usage. To fix the issue just need to reduce canvas usage. Use as fewer layers as possible. Probably use `Konva.pixelRatio = 1` to reduce canvases sizes.

Closing the issue for now. Feel free to add more info to the issue.
