### ISSUE TITLE
Transformer position after scaling canvas container

### ISSUE THREAD

**Issue by danikristiansen** [konvajs/konva#609]
I'm trying to be able to zoom in and out, not the contents of the canvas but the entire canvas (without resizing canvas size). So i managed to scale the container and it zooms fine, but the transformers loses their positions after scaling the container, the elements on the canvas seems fine, they have their coordinates from before the scaling. I tried to use forceUpdate() on the transformer and draw() on both stage and layer, without any luck. Any tips?

This is what the zoom function looks like: 
zoomOut() {
    let container = this.$refs.canvasContainer;
    let transformer = this.$refs.transformer.getStage();
    let zoom_step = 0.1;

    container.style.transform = 'scale(' + (this.scale -= zoom_step) + ')';

    transformer.forceUpdate();
}

**Comment by lavrton** [comment]
Do not transform container with CSS. It breaks hit detection. Instead, use `Konva` methods:
`stage.scaleX(this.scale)`;

**Comment by danikristiansen** [comment]
Thanks for the quick response!

Yeah i tried that before, and it works perfectly. But only the contents of the canvas scales, i want the canvas itself to scale too. Any way to achieve this without css? 

Imagine i want the canvas size to be 3000x3000 and that doesn't fit in my small container on my page, so i want to zoom out until the canvas shows inside the container.

Again, thanks!

**Comment by lavrton** [comment]
Just change scale and size. You can set `width` and `height` of the stage.

**Comment by masbaehr** [comment]
I'm having the same issue. For example i want a canvas to be 1080x1920, but it should be visible as if it were 540x960 to fit the screen. Using scale on the Stage will scale the content only

stage.getPointerPosition should then return the correct pointer position inside of the real canvas.
Is this possible somehow?

**Comment by lavrton** [comment]
I think this will work just fine:

```javascript
const ratio = Math.min(540 / 1080, 960 / 1920);
stage.setAttrs({
   width: 540,
   height: 960,
   scaleX: ratio,
   scaleY: ratio
});

const clickedPos = {
   x: stage.getPointerPosition().x / ratio
   y: stage.getPointerPosition().y / ratio
};
```

**Comment by masbaehr** [comment]
I don't think this would be the perfect solution, as the canvas itself should stay at a higher resolution to be able to keep the resolution of the drawing / scene, but having it shown in a smaller screen. A use case could be to set the scene to fullscreen and have full-hd but minimized it should be downscaled

**Comment by lavrton** [comment]
> as the canvas itself should stay at a higher resolution

Why?


If you need to make a fullscreen you can just set new width/height.

**Comment by masbaehr** [comment]
Hm okay i will investigate about this if it has any drawbacks. At a certain point im going to call toDataURL for the stage, then all inserted content images etc should scale up without losing quality. Thanks for the hints!

**Comment by lavrton** [comment]
Why you do `toDataURL` you can set width, height and desired quality with `pixelRatio` attribute.
