### ISSUE TITLE
Event Data - show current element on mouseleave

### ISSUE THREAD

**Issue by dheil** [konvajs/konva#610]
Hi,
what is the difference between target and currentTarget in the event data?

I would expect to get the actual current element. Instead both (target and currentTarget) hold the same element. I have an example here: https://jsfiddle.net/7xtgz6qs/

On leaving the blue box, I want to check, if i am over the red one. So the handler is not called because ultimately the mouse is still over the blue box:
`
bluebox.on('mouseleave', function(data){

if (MouseIsOnRed){
//donothing
} else {
callMouseLeaveHandler();
}
});

`
The only other way would be to check for the x and y coordinates of the mouse and the blue box and compare them. But it would be very nice to prevent that and somehow get the element that the mouse currently hovers inside the event.

**Comment by lavrton** [comment]
When the mouse is over red rect, it will trigger `mouseleave` on the blue box. It works just fine for me.

`target` is the node that started the event. `currentTarget` is just an element that listens to the events. For the shape `target === currentTarget`.
