### ISSUE TITLE
move rollup to devDependencies

### ISSUE THREAD

**Issue by seeden** [konvajs/konva#611]
Currently you are using rollup as dependency. But it is used only for build. We can move it to devDependencies. 

"rollup": "^1.1.2",
 "rollup-plugin-commonjs": "^9.2.0",
    "rollup-plugin-node-resolve": "^4.0.0",
    "rollup-plugin-sourcemaps": "^0.4.2",
    "rollup-plugin-typescript2": "^0.20.1"

The second issue is that I can see warning after npm install

npm WARN rollup-plugin-typescript2@0.20.1 requires a peer of typescript@>=2.4.0 but none is installed. You must install peer dependencies yourself.

zlatko-cherry:quizana-ui seeden$ npm ls rollup-plugin-typescript2
quizana-ui@2.0.1 /Users/seeden/Documents/git/quizana-ui
└─┬ konva@3.2.1
  └── rollup-plugin-typescript2@0.20.1

**Comment by seeden** [comment]
Maybe gulp as well.
"gulp-exec": "^3.0.2",
"gulp-typescript": "^5.0.0",

npm WARN gulp-typescript@5.0.1 requires a peer of typescript@~2.7.1 || >=2.8.0-dev || >=2.9.0-dev || ~3.0.0 || >=3.0.0-dev || >=3.1.0-dev || >= 3.2.0-dev || >= 3.3.0-dev but none is installed. You must install peer dependencies yourself.

zlatko-cherry:quizana-ui seeden$ npm ls gulp-typescript
quizana-ui@2.0.1 /Users/seeden/Documents/git/quizana-ui
└─┬ konva@3.2.1
  └── gulp-typescript@5.0.1

zlatko-cherry:quizana-ui seeden$

**Comment by lavrton** [comment]
Ah. That was a stupid error. Thanks a lot for the report! Fixed and published as a new version.

**Comment by seeden** [comment]
Thanks @lavrton . You are doing a good job :)
