### ISSUE TITLE
fillPatternImage not updated on draw in konva 3+

### ISSUE THREAD

**Issue by justswim** [konvajs/konva#612]
I use fillpatternimage to draw video with konva, but it was working in 2.6 but now not working in 3.2. In 3.2, if I play the video, it stays on the first frame.

Demo with 3.2 (video is stuck on first frame):
https://jsbin.com/mewamutaco/edit?html,js,output

Demo with 1.6 (video plays correctly):
https://jsbin.com/tizamupoye/1/edit?html,js,output

Is there a workaround or different way that I am supposed to be using fillpatternimage?

**Comment by lavrton** [comment]
`konva@3` use internal caching for fill patterns. So it improves performance.  The workaround is to clear the cache on every frame update:
```
node._clearCache('patternImage'); // warning, it is public API and not recommended.
```

Probably you can use `Konva.Image` instead: https://konvajs.org/docs/sandbox/Video_On_Canvas.html

**Comment by l1shu** [comment]
> `konva@3` use internal caching for fill patterns. So it improves performance. The workaround is to clear the cache on every frame update:
> 
> ```
> node._clearCache('patternImage'); // warning, it is private API and not recommended.
> ```
> 
> Probably you can use `Konva.Image` instead: https://konvajs.org/docs/sandbox/Video_On_Canvas.html

recommend to remind ‘_clearCache’ in api-docs
