### ISSUE TITLE
Seeking through video with konva causes significant flashing

### ISSUE THREAD

**Issue by justswim** [konvajs/konva#613]
I'm using Konva to render video, but i want to be able to smoothly seek through the video as well. Right now if I seek through the video the video will constantly flash on the canvas

Here is a demo. If you seek through the video, you will see what I mean about the flashing on the konva canvas.
https://jsbin.com/yedurijiwa/1/edit?html,js,output

Is there a possible workaround for this?

**Comment by lavrton** [comment]
I don't see flashing. When I change the time of the video I see an updated frame on canvas.

**Comment by justswim** [comment]
I'm sorry @lavrton, the jsbin got edited after i submitted the issue and wasn't representing the issue correctly when you looked at it.

Here is an updated jsbin which shows the flickering on seek:
https://jsbin.com/yedurijiwa/1/edit?html,js,output

This relates to your post in https://github.com/konvajs/konva/issues/612. 

If I change the video to use `image._clearCache('patternImage');` (or if I use the Image version) as per your workaround described above, then the flickering occurs on video seek.

How can I get the video to play smoothly as well as seek smoothly ?

**Comment by justswim** [comment]
I think I will solve this by selectively using the _clearCache function, unless you have a better suggestion. Thank you!

**Comment by lavrton** [comment]
That is the same demo. 😉
