### ISSUE TITLE
Transformer

### ISSUE THREAD

**Issue by rankaifeng** [konvajs/konva#621]
Package several graphics in the group on react, and then add Transformer to the group. When I stretch the group, the graphics inside will automatically scale, is that ok?

**Comment by gabberr** [comment]
You don't add transformer to the Group, add it to the Layer.
Then, you call `transformer.attachTo(group);` to make the desired group scalable.

**Comment by lavrton** [comment]
You should not add `Transformer` into the group that you are trying to resize. Add it into the parent of that group instead.
