### ISSUE TITLE
Poor filters performance on large images

### ISSUE THREAD

**Issue by optimistiks** [konvajs/konva#625]
https://codesandbox.io/embed/kx323zvmv7

Try clicking the increase/decrease buttons to feel the CPU usage spike every time brightness changes. Careful - if you click too fast, the browser tab might just hang (mine did).

I have an app where users can apply multiple filters to large images. And those spikes create quite an unpleasant user experience. Could there be any workarounds?

**Comment by lavrton** [comment]
That image is HUGE! I don't think we can do anything from Konva part right now. I hope later Konva will be able to apply filters on a Worker, but right now it works on the main thread.

Are you sure you need such images on the client side? You can make them smaller.

**Comment by optimistiks** [comment]
Unfortunately I have to produce high resolution images that are suitable for high DPI printing. So I can't just downscale images at will.

**Comment by lavrton** [comment]
For now, I see only two workarounds:

1. Apply filters manually on `WebWorker`. You don't need to use `Konva` methods here. Just generate new canvas somehow and use it for `Konva.Image` when filters are ready.

2. Use low-res image on the app. Then replaced it with HD image when you need to export for printing.
