### ISSUE TITLE
can't get most events to work in React

### ISSUE THREAD

**Issue by flowen** [konvajs/konva#627]
I'm trying to add eventlisteners on the stage, but for some reason I can't get it to work. 

[Here's an example](https://stackblitz.com/edit/konva-no-events)

only click and mousemove work.. did I do something wrong?

edit: after playing around a bit with the supplied example I found some strange behaviour. After I click on the canvas and start playing an animation, suddenly mouseleave and mouseenter will work

**Comment by lavrton** [comment]
Thanks for the report. That looks like a bug. I will review and work with it soon.

**Comment by lavrton** [comment]
Made a release. You can try the fix.
