### ISSUE TITLE
how to draw lines to connect things like flowchart

### ISSUE THREAD

**Issue by peterremote1980** [konvajs/konva#628]
Hi
   how to draw lines to connect things like flowchart. In a typical flowchart, lines are either vertical or horizontal, and lines are trying to find the way to connect each two things without overlap anything on screen.
thanks
Peter

**Comment by lavrton** [comment]
You just need to update `points` of the line as you need it. Please be more specific.

This demo may help: https://konvajs.org/docs/sandbox/Connected_Objects.html
