### ISSUE TITLE
Layer / Stage Being Cutoff When Another Window Is Visible 

### ISSUE THREAD

**Issue by santosgagbegnon** [konvajs/konva#629]
I've noticed that when I have the chrome developer console opened or I've downloaded something and the little download bar at the button of the screen is covering my Konva Stage, the drawings are cut off, even after closing the window blocking the stage. 

**Steps to Reproduce:**

1. Open Google Chrome

2. Go to this JSFiddle: https://jsfiddle.net/hkbr8zod/

2. Run and see the blue rectangle being drawn:
<img width="1234" alt="Screen Shot 2019-04-04 at 9 38 37 PM" src="https://user-images.githubusercontent.com/40777393/55598685-0374c680-5722-11e9-8aa6-77f5a3cc985f.png">

3. Open the Chrome Developer Console and have it cover a part of the blue rectangle:
<img width="1235" alt="Screen Shot 2019-04-04 at 9 40 04 PM" src="https://user-images.githubusercontent.com/40777393/55598723-37e88280-5722-11e9-961f-3fb2510c6e1c.png">

4. While keeping the Chrome Developer Console, run the JSFiddle again and then close the console and you will see the rectangle has been cut:
<img width="1230" alt="Screen Shot 2019-04-04 at 9 40 48 PM" src="https://user-images.githubusercontent.com/40777393/55598748-56e71480-5722-11e9-91f8-ced87dd0ae48.png">

Any explanation as to why this might be happening would be very helpful, thanks! 😄

**Comment by lavrton** [comment]
Probably because at some point jsfiddle result was restarted. It created a smaller canvas `container.offsetHeight`.

**Comment by santosgagbegnon** [comment]
You're right, it was my fault! Settings a constant size instead of using the containers offsetHeight fixed the issue. Thanks for the quick response 👍
