### ISSUE TITLE
Keep font-size of Text-layer when transforming group

### ISSUE THREAD

**Issue by sinasita** [konvajs/konva#631]
One little question:

Is there a way to keep the font-size of a text-layer, when it's part of the group and the group gets resized via transformer? I found things like transformesEnabled, but it's just for the group and not for the single text-layer...

Thanks for your help...

**Comment by lavrton** [comment]
It really depends on how you want to organize your transforms. You can apply a reversed scale to the text:

```javascript
tr.on('transform', () => {
  const absScale = text.getAbsoluteScale();
  text.scaleX(text.scaleX() / absScale.x);
  text.scaleY(text.scaleY() / absScale.y);
})
```

https://jsbin.com/xeverebeki/1/edit?html,js,output

**Comment by sinasita** [comment]
Oh thanks a lot, that worked perfectly. And is there a way, that on transforming a rectangle with a border, the transformer remains directly attached to the rectangle?

https://jsbin.com/meqofimopo/edit?html,js,output

On scaling, there is a white gap between transformer and rectangle, when a border is set.

**Comment by lavrton** [comment]
At the current moment, `Transformer` doesn't work well with `strokeScaleEnabled = false`.

As workaround, you can use a combination of `ignoreStroke = false` and `padding`:
```javascript
const tr = new Konva.Transformer({
  node: group,
  ignoreStroke: true,
  padding: rect.strokeWidth() / 2
})
```

https://jsbin.com/fahihegexe/2/edit?html,js,output
