### ISSUE TITLE
Rotation tween interpolation issue

### ISSUE THREAD

**Issue by SequenceK** [konvajs/konva#632]
I have an issue when tweening rotation on an object. The tween does a loop each time the angle changes from 360 to 0. Looking at the implementation of tween, it seems that it is generic. I am wondering if it is possible to add custom tweening code for rotation.

examples:
Here is a demo for the current behavior: 
https://codepen.io/jackrugile/pen/aa6515f6e7a4835c95462b2a7e89aa83/

And this is the demo for the desired behavior: 
https://codepen.io/jackrugile/pen/45c356f06f08ebea0e58daa4d06d204f

stackoverflow post:
https://gamedev.stackexchange.com/questions/72348/how-do-i-lerp-between-values-that-loop-such-as-hue-or-rotation

**Comment by lavrton** [comment]
So the SO post has very good answers. Can you use them?

**Comment by SequenceK** [comment]
Yeah, I am using it right now by changing the rotation in an animation. To get similar smoothness as a tween, I can use the TweenEngine class, but the class is not exported in Konva.

Or I can just implement the tween logic myself(timing, etc).

**Comment by lavrton** [comment]
To make it work with the tween you just need to use different values for rotation, so it goes into a required direction (like adding `Math.PI * 2` to "finish" value).
