### ISSUE TITLE
Calculating twice - error

### ISSUE THREAD

**Issue by bjdenhertog** [konvajs/konva#633]
Uncaught (in promise) Error: Calculating structure twice ! Should not happen
    at Object.t.computeStructure (kwift.CHROME.min.js:1)
    at S (kwift.CHROME.min.js:1)
    at callback (kwift.CHROME.min.js:1)
    at kwift.CHROME.min.js:1

https://www.wiskunjetrainen.nl/plotter.php
I get this error after rebuild (press 'Nieuwe opdracht' button) of the complete stage with this piece of code:
			if (layer != null) layer.destroy();
			if (stage != null) stage.destroy();
			stage = new Konva.Stage({

**Comment by lavrton** [comment]
As I can see that the error from `kwift.CHROME.min.js`. I guess it is not related to `Konva` and comes from a Chrome extension.
