### ISSUE TITLE
Flow Diagrams

### ISSUE THREAD

**Issue by Diaskhan** [konvajs/konva#634]
Good Day Commander! Interesting Lib

It possible to make Flow Diagrams ?
https://jgraph.github.io/mxgraph/javascript/examples/helloworld.html

Tutotial of mxgraph 
https://jgraph.github.io/mxgraph/docs/tutorial.html

There have Edges and Vertex !
```
 var v1 = graph.insertVertex(parent, null, 'Hello,', 20, 20, 80, 30);
 var v2 = graph.insertVertex(parent, null, 'World!', 200, 150, 80, 30);
 var e1 = graph.insertEdge(parent, null, '', v1, v2);
```

1.Edge is connection between Vertexes !
And When Vertex is moving Edge is changging 
https://jgraph.github.io/mxgraph/javascript/examples/helloworld.html

2.Possible to serialize json data after Editing of Diagram?

**Comment by lavrton** [comment]
Yes, that is possible. But you will have to implement many features.

For connecting objects take a look here: https://konvajs.org/docs/sandbox/Connected_Objects.html

For JSON saving take a look here: https://konvajs.org/docs/data_and_serialization/Best_Practices.html

**Comment by qinyang1980** [comment]
good
