### ISSUE TITLE
Line Transform Tool

### ISSUE THREAD

**Issue by Diaskhan** [konvajs/konva#635]
It possible to implement Line Tool 
Like Transform Tool
https://github.com/konvajs/konva/issues/270

When arrow is drawing and not in data ?
And we could draw 90 degree lines ?
![image](https://user-images.githubusercontent.com/15046677/56264837-87a75080-6109-11e9-9c70-7e7cde827052.png)
Reposition the line !
![image](https://user-images.githubusercontent.com/15046677/56264936-f2f12280-6109-11e9-9fe6-4a74b2ebfb7f.png)

If Yes how to integrate it like U did in transform tool ?

**Comment by lavrton** [comment]
There are no built-in methods for that case. You have to make a manual implementation.

As an initial demo see: https://stackoverflow.com/questions/55703336/resizing-and-rotating-a-line-with-the-same-anchor-in-konva-js/55707822#55707822
