### ISSUE TITLE
The Konva.Layer is not the subclass of Node?

### ISSUE THREAD

**Issue by JOU-amjs** [konvajs/konva#638]
![image](https://user-images.githubusercontent.com/29848971/56492828-8918b480-651f-11e9-80a0-1b4693cef37c.png)
See the uploaded image, when I use `stage.fineOne('Layer')` to get a Layer object and assign a variable which type is `Konva.Layer`, it throws the error, what happened?

**Comment by lavrton** [comment]
I added generics to find methods. So you can use them like this:

```javascript
const layer = stage.findOne<Layer>('Layer');
```

I will release the new version later.

**Comment by RobbertWolfs** [comment]
@lavrton  is this already released?

**Comment by lavrton** [comment]
Yes, it is.

**Comment by JOU-amjs** [comment]
I see
