### ISSUE TITLE
Refresh hit graph when on stage.listening() changes

### ISSUE THREAD

**Issue by pronebird** [konvajs/konva#64]
There is a problem with layers hit graph when stage is not listening to events. Essentially hit graph is not refreshed when stage starts listening to events.

Currently I workaround this with extra `stage.drawHit()`.

Probably that should be fixed...

**Comment by lavrton** [comment]
@pronebird can you create an example?
I made this test https://github.com/konvajs/konva/commit/1c7c202b681d99114802b4e29473b16af17d676a and it works as expected.

**Comment by pronebird** [comment]
Oh yeah so you call draw() after you flip the flag.

**Comment by pronebird** [comment]
I guess my expectation was that listening() would refresh the hit graph.

**Comment by lavrton** [comment]
Right. You have to call `draw()` or `drawHit()`.
