### ISSUE TITLE
 How do i draw lines in a loop?

### ISSUE THREAD

**Issue by kolserdav** [konvajs/konva#641]
I use the following code to get three lines with a shift `i * 10`, but I only get the latest version of the line. How do i draw lines in a loop?
```
const stage = new Konva.Stage({
        container: 'container',
        width: width,
        height: height
    });
const layer = new Konva.Layer();
writeLines(layer);
stage.add(layer);
function writeLines(layer, i = 0){
    const line = [0 + i*10,0 + i*10,23 + i*10,23 + i*10];
    console.log(line)
    const vector = new Konva.Line({
      points: line,
      stroke: 'green',
      strokeWidth: 2,
      lineCap: 'round',
      lineJoin: 'round'
    });
    layer.add(vector);
    if (i < 2){
      writeLines(layer, i + 1);
    }
}
```
Here I showed recursion, but the same result was obtained with cycle `for`.

**Comment by lavrton** [comment]
Can you make a demo of your issue?

**Comment by kolserdav** [comment]
https://next.plnkr.co/edit/OdX3YOt2CuwvuPLj?open=lib%2Fscript.js&preview

Sorry its my mistake, close it.
I used bad points, and the lines overlapped despite the shift.
