### ISSUE TITLE
Shape flash when using centeredScaling and boundBoxFunc

### ISSUE THREAD

**Issue by ocavue** [konvajs/konva#642]
https://jsbin.com/ziyasukuzu/edit?html,js,output

![May-03-2019 07-06-40](https://user-images.githubusercontent.com/24715727/57112317-0a6b1500-6d72-11e9-9e41-93ee3b4c60bf.gif)

If `centeredScaling` is `false`, this bug will not appear.

**Comment by lavrton** [comment]
Bad bug. Thanks for the report. Need to fix it.

**Comment by ocavue** [comment]
Another example

https://jsbin.com/xujiyelece/1/edit?js,output

[video](https://github.com/konvajs/konva/files/3150778/Shapes.zip)

- darkgreen(`centeredScaling: false`): work well.
- lightgreen(`centeredScaling: true`): Keep flashing.
- black(`centeredScaling: false, boundBoxFunc: boundBoxFunc`): work well.
- gray(`centeredScaling: true, boundBoxFunc: boundBoxFunc`): This shape fly away when its width hit the limit. 😂

**Comment by lavrton** [comment]
Fixed with the last release. It should be better now. But it doesn't work well with that `boundBoxFunc`.

**Comment by ocavue** [comment]
@lavrton Thanks!
