### ISSUE TITLE
Typescript typing typo for contentDblTap in event names, should be contentDbltap.

### ISSUE THREAD

**Issue by Mjinx** [konvajs/konva#645]
Was attempting to develop touch functionality on desktop and came across this typo.

```javascript
 interface KonvaStageEventMap {
    .....
    contentDblTap: Event;
  }
```

=>

```javascript
 interface KonvaStageEventMap {
    .....
    contentDbltap: Event;
  }
```

**Comment by lavrton** [comment]
Fixed. Will be released in `react-konva` later. But also I recommend not to use `contentSomething` events. Just use events directly. All of them should work just fine.

**Comment by Mjinx** [comment]
Thanks for the quick update, may i ask why not to use the content events?  I've followed your examples to zoom and pan the stage (mouse and touch) I further added dblClick/Tab to stage (content events) to do quick zoomin/out functionality.

**Comment by lavrton** [comment]
I just want to get rid of "content" events, because they are confusing. For now "content" events may be required only when you want to handle multitouch `touchmove` events (like in that demo). But I hope to make full multitouch support soon.
