### ISSUE TITLE
Limit the Transformer's rotation angles

### ISSUE THREAD

**Issue by Seblor** [konvajs/konva#648]
Hello,
I was wondering if it was possible to limit the rotations of the Transformer to a set of determined angles.
For example, if I allow only the `[0, 90, 180, 270]` angles, using the Transformer's rotation handle, the Transofrmet will only be rotated after the cursor passes the 45° angle.
A bit like setting a custom snapping angle.

The only way I could do it was to listen for the end of the transformation, and set the resulting rotation to the closest multiple of 90, but the user experience is not great, as while the user keeps the mouse down, the rotation is free, except the snapping.

**Comment by lavrton** [comment]
There are many ways to do that. With the current API, it is a bit complex, because you have to do a lot of math manually. Looks like this will work just fine:

```javascript
function degToRad(angle) {
  return angle / 180 * Math.PI;
}

function getCenter(shape) {
  const angleRad = degToRad(shape.rotation || 0);
  return {
    x:
      shape.x +
      shape.width / 2 * Math.cos(angleRad) +
      shape.height / 2 * Math.sin(-angleRad),
    y:
      shape.y +
      shape.height / 2 * Math.cos(angleRad) +
      shape.width / 2 * Math.sin(angleRad)
  };
}

function rotateAroundPoint(shape, deltaDeg, point) {
  const angleRad = degToRad(deltaDeg);
  const x = Math.round(
    point.x +
      (shape.x - point.x) * Math.cos(angleRad) -
      (shape.y - point.y) * Math.sin(angleRad)
  );
  const y = Math.round(
    point.y +
      (shape.x - point.x) * Math.sin(angleRad) +
      (shape.y - point.y) * Math.cos(angleRad)
  );
  return {
    ...shape,
    rotation: Math.round((shape.rotation + deltaDeg)),
    x,
    y
  };
}

function rotateAroundCenter(shape, deltaDeg) {
  const center = getCenter(shape);
  return rotateAroundPoint(shape, deltaDeg, center);
}

function getSnapRotation(rotation) {
  if (rotation >= 45 && rotation < 135) {
    return 90;
  } else if (rotation >= 135 && rotation < 225) {
    return 180;
  } else if (rotation >= 225 && rotation < 305) {
    return 270;
  } else {
    return 0;
  }
}


var tr = new Konva.Transformer({
  boundBoxFunc: function(oldBoundBox, newBoundBox) {
    const closesSnap = getSnapRotation(newBoundBox.rotation);
    const diff = closesSnap - oldBoundBox.rotation;
    if (Math.abs(diff) > 0) {
      return rotateAroundCenter(oldBoundBox, diff);
    }
    return oldBoundBox;
  }
});
```

Demo: https://jsbin.com/xabegiseti/3/edit?js,output

Is it what you want?

**Comment by Seblor** [comment]
Thank you, this is exactly the behavior I as looking for.

**Comment by acnicolasdc** [comment]
@lavrton but what happen if I'm using react-konva. the above example doesn't works for me

**Comment by lavrton** [comment]
It should work exactly the same with `react-konva`.

**Comment by dustinknopoff** [comment]
This works great! I'm stuck trying to alter this so that I can allow arbitrary resizing but still restrict the rotation to 45 degree angles.

**Comment by safaldas-neoito** [comment]
Is it possible to activate this rotation snapping when CTRL is pressed?

**Comment by Seblor** [comment]
@safaldas-neoito That is possible, you can have a boolean set to `true` with the <kbd>ctrl</kbd> key is pressed, and return the correct bound box depending on that boolean.

Here is an example : https://jsbin.com/lalexevagu/1/edit?js,output

**Comment by safaldas-neoito** [comment]
> @safaldas-neoito That is possible, you can have a boolean set to `true` when the ctrl key is down, and return the correct bound box depending on that boolean.
> 
> Here is an example : https://jsbin.com/lalexevagu/1/edit?js,output

Thanks that worked

**Comment by damontes** [comment]
> @lavrton but what happen if I'm using react-konva. the above example doesn't works for me

@lavrton Hi, i create a CodeSanbox simulating the same code but it doesn`t function for react-konva

https://codesandbox.io/s/nervous-rain-t6snw?file=/src/util.js

**Comment by lavrton** [comment]
@damontes looks like in your demo radians and deg are mixed. Just make sure they used correctly.

**Comment by chojnicki** [comment]
I had same problem, and found this topic. I'm not sure tho why this example code needs to be so complicated? This is what I did:

```
const boundBoxFunc = (oldBoundBox, newBoundBox) => {
  if (Math.abs(newBoundBox.rotation % (Math.PI / 4)) > 0) {
    return oldBoundBox
  }
  return newBoundBox
}
```

plus build-in snapping on transformer:

`:rotationSnaps="[0, 45, 90, 135, 180, 225, 270, 315]"`

and it works - in my case it snaps to multiple of 45 degrees and does not allow to set different one.

Maybe this will help someone.
