### ISSUE TITLE
How to make .toJSON() save the image src attribute

### ISSUE THREAD

**Issue by Ivanca** [konvajs/konva#650]
I saw [this link from a couple of years ago](https://konvajs.org/docs/data_and_serialization/Complex_Load.html) but maybe now there is a better way?

All I need is a way to save in the same JSON the url of the image and then just iterate over the saved JSON to recreate it again; if there was a way to pass a function to the "toJSON" method to do the extra stuff that probably would be enough.

**Comment by lavrton** [comment]
My current recommendation is this: https://konvajs.org/docs/data_and_serialization/Best_Practices.html

For the case of images you can do just this:

```javascript
// save url as a custom attribute
Konva.Image.fromURL(url, image => {
   layer.add(image);
   image.setAttr('source', url);
});



// later restore an image from "source" attribute
const stage = Konva.Node.create(json, 'container');
stage.find('Image').forEach(imageNode => {
  const nativeImage = new window.Image();
  nativeImage.onload = () => {
    imageNode.image(nativeImage);
    imageNode.getLayer().batchDraw();
  }
  nativeImage.src = imageNode.getAttr('source');
})
```

**Comment by Ivanca** [comment]
That should work, thanks.
