### ISSUE TITLE
Text width does not change dynamically

### ISSUE THREAD

**Issue by applezyp** [konvajs/konva#652]

**Comment by applezyp** [comment]
We have a project that need to zoom in and out of the stage. We need to adjust font size of Text dynamically. But after adjusting the font size of Text, the width of Text will not change dynamically. We can not update the width of Text to get one right display. Some thing must be wrong here. I hope you can fix them. Thank you very much.

**Comment by lavrton** [comment]
Can you change text width manually?

**Comment by lavrton** [comment]
Closing as not enough info about the issue.
