### ISSUE TITLE
clearCache() memory leak (IOS Safari 12+)

### ISSUE THREAD

**Issue by EugeneSqr** [konvajs/konva#653]
The problem is caused by Safari 12+ bug described [here](https://stackoverflow.com/questions/52532614/total-canvas-memory-use-exceeds-the-maximum-limit-safari-12). The underlying canvas has to be explicitly "destroyed" by setting its height and width to 0.
Steps to reproduce:
1. Open this jsfiddle https://jsfiddle.net/vkLmwpah/10/ on IOS Safari 12+. It's highly recommended to close all existing tabs to get as much available memory as possible. The large black rectangle object is cached right before the animation starts. When the animation finishes the cache gets cleared by invoking clearCache for the rectangle.
2. Press "tween" button at the top, wait until animation finishes.
3. Repeat 5 to 10 times (depending on the memory available).

Expected result: the animation remains playable no matter how many times it's played.
Actual result: the animation breaks after a certain number of times. The black rectangle starts flashing instead of moving. The following error message appears in remote dev console each time the "tween" button is pressed:

> Total canvas memory use exceeds the maximum limit (224 MB)

In the following jsfiddle https://jsfiddle.net/xv6steoq, the problem is fixed by manually "destroying" the related canvas cache objects before invoking clearCache:
```javascript
rect._cache.get("canvas").scene._canvas.width = 0;
rect._cache.get("canvas").scene._canvas.height = 0;
rect._cache.get("canvas").hit._canvas.width = 0;
rect._cache.get("canvas").hit._canvas.height = 0;
rect._cache.get("canvas").filter._canvas.width = 0;
rect._cache.get("canvas").filter._canvas.height = 0;
```
This breaks Konva abstraction unfortunately. Is it possible to incorporate the suggested workaround into Konva?

**Comment by lavrton** [comment]
I don't think the fix inside Konva core code will be super useful. I am sure that bug will be fixed soon in Safari. As workaround just call that code manually.

**Comment by songoffire** [comment]
This is still a big problem a year later, and Apple still has not addressed the issue.  Does anyone know of a functional workaround?  Thanks!

**Comment by lavrton** [comment]
```js
rect._cache.get("canvas").scene._canvas.width = 0;
rect._cache.get("canvas").scene._canvas.height = 0;
rect._cache.get("canvas").hit._canvas.width = 0;
rect._cache.get("canvas").hit._canvas.height = 0;
rect._cache.get("canvas").filter._canvas.width = 0;
rect._cache.get("canvas").filter._canvas.height = 0;

rect.clearCache();
```

**Comment by lavrton** [comment]
And I don't know how to reproduce the issue. I tried to run some tests right now on my iPhone. It works ok.
