### ISSUE TITLE
z-index group

### ISSUE THREAD

**Issue by deathblade89** [konvajs/konva#654]
Hi @lavrton ,

We have discussed the z-indexing previously, but i would like to ask you for some clarification on how to make certain things possible.

I would like to change the Group z-index, so that I can choose which groups are drawn above/below other groups. It has to work with either Group/Layer as the entire group can be moved up/down.

Please see the fiddle below:
https://jsfiddle.net/fb6p9c35/

Please can you guide me in the right direction to achieve this?

Thank you

**Comment by lavrton** [comment]
So what exactly is not working for you? Do see warnings in the console?

**Comment by deathblade89** [comment]
Hi @lavrton ,

Ill try to explain as best as i can:

I have 10 groups, each with one rectangle going from left to right.
I would like to change the z-index of each group so that when i drag a group around it is rendered either behind or infront of other groups.

What i am really looking for is for more control on all items within a group, so that i can change the z-index however i want.

Does this clear things up for you?

Thank you for your response.

**Comment by lavrton** [comment]
I still don't understand. So you have a demo. What is not correct in it? What do you want to have? I see in the demo that you are trying to set `zIndex` before adding a node into the parent. It will not work, because `zIndex` is an index in the array of parent's children.

**Comment by deathblade89** [comment]
@lavrton 
Hi there

Ok let me be more specific.
Is  it possible to control the zIndex of a group?

**Comment by lavrton** [comment]
In the same way as any other node.

```javascript
group.zIndex(3);
group.moveToTop();
group.moveToBottom();
```
