### ISSUE TITLE
Perspective transform

### ISSUE THREAD

**Issue by kordix** [konvajs/konva#655]
Is there any possibility to make a perspective transform?
Here you've got an example using scrawl library:
https://codepen.io/kaliedarik/pen/MwPVOR

Is it possible to merge such functionality?

**Comment by lavrton** [comment]
Take a look here https://stackoverflow.com/a/53086385/512042

I am not sure how to merge such functionality.

**Comment by ralppppy** [comment]
How to do this in konva? This is helpful for creating a door to simulate the opening and closing animation especially if you are facing the door perpendicularly, I've tried skew but I think it will only work for some angle.

**Comment by jurnet** [comment]
I have follow this and adapt but how can I drag outside the canvas like konvajs ? 
https://jsfiddle.net/jurnet/3wjcfgub/
Thanks
