### ISSUE TITLE
Typescript Node.on event typing

### ISSUE THREAD

**Issue by nathanloisel** [konvajs/konva#656]
Hi, 
I just updated konva version and noticed that the KonvaEventObject is not used for Node.on callback function parameters. It's usefull to have it for obviouse reason.
Good luck with your typescript refactoring :)

**Comment by lavrton** [comment]
@nathanloisel can you add more info? Types for `node.on` methods are much better in the last release.

**Comment by nathanloisel** [comment]
Yes sure, 
The type of the `Node.on` method is :
```
on<K extends keyof NodeEventMap>(
    type: K,
    listener: (
      this: this,
      ev: {
        target: Shape | Stage;
        evt: NodeEventMap[K];
        currentTarget: Node;
        cancelBubble: boolean;
        child?: Node;
      }
    ) => any
): void;
```
And it's not very convenient to copy past the type of `ev` each time.
A good solution is to export publicly a type like 
```
interface KonvaNodeEvent<K> {
        target: Shape | Stage;
        evt: NodeEventMap[K];
        currentTarget: Node;
        cancelBubble: boolean;
        child?: Node;
}
on<K extends keyof NodeEventMap>(
    type: K,
    listener: (
      this: this,
      ev: KonvaNodeEvent<K>
    ) => any
): void;
```
Like that on my code I can import the KonvaNodeEvent and use it like that :

```
node.on('click', this.onNodeClick.bind(this);
...

onNodeClick(ev: KonvaNodeEvent<'click'>): void {}

```
Moreover if the return value of `listener` is not used, the return type must be `void` and not `any` I think.

**Comment by lavrton** [comment]
Ok. Added `KonvaEventObject` and `KonvaEventListener` into `Konva` namespace. Will publish later.
