### ISSUE TITLE
Is it a straight replacement of the keyword from "Kinetic" to "Konva"?

### ISSUE THREAD

**Issue by jun1432** [konvajs/konva#660]
I just want to ask this question just to clarify.

Is it just a plain replacement of the keywords?

Example:
"kinetic_stage = new Kinetic.Stage();" to "konva_stage = new Konva.Stage();"

**Comment by lavrton** [comment]
Yeah. It should work in most of the cases. In case of errors, you can check https://github.com/konvajs/konva/blob/master/CHANGELOG.md
