### ISSUE TITLE
First test with konvaJS

### ISSUE THREAD

**Issue by carlNOMBO** [konvajs/konva#662]
Hi! I get started using KonvaJS, but when I'm including it to do first tests with the first minimal code example in the overview, it doesn't work, and I've this error " konva.min.js:12 Uncaught Can not find container in document with id container ". 
I need your help please!

html :

<script src="https://unpkg.com/konva@3.2..."></script>
<script type="text/javascript" src="test.js"></script>
<div id="container">test</div>

js:

// first we need to create a stage
var stage = new Konva.Stage({
container: 'container', // id of container <div>
width: 500,
height: 500
});

// then create layer
var layer = new Konva.Layer();

// create our shape
var circle = new Konva.Circle({
x: stage.width() / 2,
y: stage.height() / 2,
radius: 70,
fill: 'red',
stroke: 'black',
strokeWidth: 4
});

// add the shape to the layer
layer.add(circle);

// add the layer to the stage
stage.add(layer);

// draw the image
layer.draw();

**Comment by hgasoft** [comment]
you should describe canvas container in html side like below:

<div id="container"></div>

**Comment by lavrton** [comment]
http://disq.us/p/226npy4

**Comment by carlNOMBO** [comment]
Sorry for being late. The solution was to wait the complet load of my html using the DOM like window.addEventListener("load",function function_name(){})
