### ISSUE TITLE
No SemiCircle Class?

### ISSUE THREAD

**Issue by mpaccione** [konvajs/konva#663]
Hello, thank you for creating an excellent canvas library.

I was rather shocked that there is no SemiCircle class... I am creating a flight simulator and need semicircles for the instrument panels. Arcs will not work. 

Any advise or comments on this? I need it in the Konva framework ideally.

**Comment by mpaccione** [comment]
Nevermind by having an inner radius of 0 it works ...

Silly me! Apologies!

**Comment by marc-thomas** [comment]
Hey @mpaccione - what parameter did you need to change specifically to make a semi circle?

Do you know if it's also possible with an ellipse? https://konvajs.org/docs/shapes/Ellipse.html
