### ISSUE TITLE
hitStrokeWidthProperty on <Text /> Component

### ISSUE THREAD

**Issue by mitaxe** [konvajs/konva#664]
Hi, I've encountered a bug when I am trying to use hitStrokeWidthProperty on Text but nothing changes. I've tried different values. Could you have a look at it, please?

**Comment by lavrton** [comment]
Can you make a demo? What exactly is not changed?

**Comment by lavrton** [comment]
Probably you don't see the result because a text has no stroke. Just set any stroke for it. You can make it transparent if you don't want to make it visible.
