### ISSUE TITLE
Konva.Rect -  cornerRadius

### ISSUE THREAD

**Issue by s0urcelab** [konvajs/konva#666]
`Konva.Rect({
        x: 50,
        y: 50,
        width: 100,
        height: -50,
        cornerRadius: 4
      });`

Rect() support a negative width and height, but with 'cornerRadius' props will throw a error:

**Uncaught DOMException: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-111) is negative.**

i guess cornerRadius is based on ctx.arc() but it doesn't support negative value.

**Comment by lavrton** [comment]
The negative never officially supported by Konva. Just canvas API allows in some browsers to use negative values for width/height. But I don't recommend to do it. If you need to revert a shape use `shape.scaleY(-1)`.
