### ISSUE TITLE
konva-node dependencies

### ISSUE THREAD

**Issue by optimistiks** [konvajs/konva#667]
The `konva-node` package of version `0.9.0` has the following dependencies:

```
  "dependencies": {
    "canvas": "^1.6.7",
    "konva": "^2.5.1"
  },
```

Is there a way to upgrade to konva v3 and node-canvas v2?

**Comment by lavrton** [comment]
Updated. Try `konva-node@0.10.0`. Please let me know how it works for you.

**Comment by optimistiks** [comment]
Thanks for the quick response! Unfortunately, the update breaks my app. The problem is the injection of `window` to `global`. A lot of libs depend on `typeof window !== undefined` check to determine if you are on a server or in a browser, in my case it's Firebase JS SDK and NextJS. Maybe there is a way to avoid window injection?

**Comment by lavrton** [comment]
Right, I was thinking about a similar case. Yeah, I will think about how to fix it.

**Comment by lavrton** [comment]
Just made some fixes in both `konva` and `konva-node`. Try the latest version `0.11.0`.

**Comment by optimistiks** [comment]
Seems to be working fine. Thanks a lot!
