### ISSUE TITLE
Layer.ts and BaseLayer.ts missing arguments types

### ISSUE THREAD

**Issue by Ivanca** [konvajs/konva#669]
For example on Layer.ts
```
tsgetIntersection(pos, selector) {`
```

should be 
```ts
getIntersection(pos:Vector2d, selector?:string) {
```
See that the "?" is also missing on some methods, right now I'm passing '' as second argument to `getIntersection` but it should be optional.

**Comment by lavrton** [comment]
You are right. Do you want to make a Pull Request?

**Comment by lavrton** [comment]
Fixed. Will be published later.
