### ISSUE TITLE
Typescript Error for BaseLayer

### ISSUE THREAD

**Issue by sezginriggs** [konvajs/konva#670]
Hello,

I'm trying use Konva 3.3.3 with Ionic Framework 3.9.5 / Angular Core 5.2.9 / TypeScript 3.5.1 and I'm getting these errors while building for IOS simulator. Interesting part is sometimes it doesn't show this and screen with Konva seems working fine. But also when building for device, it always shows this error.

Could this be my mistake or is it related with Konva? Thank you for your help...

![Simulator Screen Shot - iPhone 8 - 2019-06-13 at 01 53 04](https://user-images.githubusercontent.com/10950287/59392412-3b326700-8d80-11e9-99ab-98550e2bcd93.png)

**Comment by lavrton** [comment]
That looks strange. Looks like typescript is trying to compile declarations as normal `.ts` file. I don't see what can we do here from `Konva` side.

**Comment by sezginriggs** [comment]
@lavrton I don't know, the strangest part is when I change code and try to build for the first time, it works.. But with same code, second build occurs this error. Now this is blocking my development and I really really need help about this. May I provide any other information to help resolving this? Could this be related with RxJS or Angular?

**Comment by sezginriggs** [comment]
@lavrton After reading your answer and issues about RxJS, I've updated my project's TypeScript from 2.6.2 to 3.5.2 (latest version) and RxJS from 6.3.3 to 6.5.2.

And it seems it works as expected right now :) Thank you very much for your help!
