### ISSUE TITLE
set alpha in free draw but it seems like a bug？

### ISSUE THREAD

**Issue by tczj199076** [konvajs/konva#671]
Hello.
I set alpha in free draw, but there seems to be a problem. There are many point in the  layer. why？

**Comment by lavrton** [comment]
What bug? Can you make a demo of your issue?

**Comment by tczj199076** [comment]
yes,I was use https://konvajs.org/docs/sandbox/Free_Drawing.html，and I set:

>  var context = canvas.getContext('2d');
    context.strokeStyle = 'grey';
    context.lineJoin = 'round';
    context.lineCap = 'round';
    context.lineWidth = 10;
    context.globalAlpha = 0.2;

when I set the globalAlpha and draw in canvas,Although transparent, there are a lot of overlaps.

it seems like 'move to' overlaps,you can try this demo,and set the globalAlpha <1.

at last,thanks for reply.

**Comment by lavrton** [comment]
That is not a bug, that is how canvas API is working. If you don't want to overlaps you have to use external canvas for each drawing.

**Comment by lavrton** [comment]
While drawing on external canvas you should not use opacity. But later, when you are drawing that canvas into visible canvas on the page you have to apply your opacity.

**Comment by tczj199076** [comment]
> While drawing on external canvas you should not use opacity. But later, when you are drawing that canvas into visible canvas on the page you have to apply your opacity.

tanks for reply,but I can't understand how to use external canvas for each drawing,would you please make a demo?

**Comment by lavrton** [comment]
Probably it will be simpler for you to use "object oriented" approach. Take a look into the updated demo. https://konvajs.org/docs/sandbox/Free_Drawing.html

**Comment by 5201314999** [comment]
@lavrton when I use you first demo code (new Konva.Line) and set alpha ,It has not overlap ，but when I make the cursor move in same line ,the color can not be more deep ，and why I draw the second line in the same place it will become more deep color ，It seems to be strange

**Comment by lavrton** [comment]
I think that is how 2d canvas API works. I don't see what can we do here from `Konva` side.
