### ISSUE TITLE
Possible Typescript definition problem

### ISSUE THREAD

**Issue by sezginriggs** [konvajs/konva#674]
Hello,

When I try to use Konva.Filters.Blur filter, I get definition error. All other Filters accepting imageData as "any" but Blur filter requires Node and CanvasImageData. Here is the screenshot of occuring error.

I use Konva 3.3.3, TypeScript 3.5.2

![Simulator Screen Shot - iPhone 8 - 2019-06-18 at 22 22 13](https://user-images.githubusercontent.com/10950287/59713413-1c1c5500-9218-11e9-92b7-8c1c7d29427f.png)

**Comment by lavrton** [comment]
Yeah. that is incorrect types in `Blur` filters. As workaround you can use this:

```
shape.filters([Konva.Filters.Blur as any]);
```

The fix will be published in the next release.
