### ISSUE TITLE
大数据不断重绘的时候浏览器内存会不断的上涨，有优化点么？

### ISSUE THREAD

**Issue by zqler** [konvajs/konva#675]
Thank you for submitting an issue!

Please make sure to check current open and closed issues to see if your question has been asked or answered before.
If you have just a question (not a bug or a feature request) it is better to ask it in [Stackoverflow](http://stackoverflow.com/questions/tagged/konvajs).

If you have a bug, please, try to create a reproducible example with jsfiddle (or any similar service).
You can use [this JSBIN](https://jsbin.com/tekehizuta/1/edit?html,js,output) as a template.

**Comment by lavrton** [comment]
Please provide more info.

**Comment by zqler** [comment]
现在的场景是几千条的位置数据用konvas渲染坐标点，1s渲染一次，发现浏览器内存会不断的上涨，有没有可以优化的地方呢？

**Comment by lavrton** [comment]
Hard to say without more info. If you have konva nodes for each data you have it may consume a lot of memory. Try not to create nodes for not visible data.

**Comment by iceafish** [comment]
重绘你是不是只调用了 remove，而不没有调用 destroy ，remove 并不会回收内存，而且如果重绘涉及到频繁新增节点的话，建议做一个 nodes pool。
