### ISSUE TITLE
Using SVG image

### ISSUE THREAD

**Issue by 3zzy** [konvajs/konva#677]
I'm trying to use SVG instead of a raster image but it doesn't seem to work. 

```
var imageObj = new Image();
imageObj.onload = function() {
    var image = new Konva.Image({
        image: imageObj,
        width: size,
        height: size,
        offsetX: size / 2,
        offsetY: size / 2,
    });
    group.add(circle);
    group.add(image);
    my.layer.add(group);
    my.layer.draw();
}
imageObj.src = '/path/to/image.svg';
```

Is it supported at all? If not, is there a workaround?

**Comment by lavrton** [comment]
Yes. With modern browsers, it should work just fine. Can you share an image? Did you try in other browsers?

**Comment by 3zzy** [comment]
@lavrton Thanks for the prompt reply. 

Here's the image (just a simple icon): https://svgshare.com/i/Dj4.svg

I'm testing in Firefox, Chrome and Safari all latest versions.

**Comment by 3zzy** [comment]
@lavrton  My bad, it seems to work in Safari and Chrome (Webkit) but not Firefox (Quantum). Wondering if it would work in IE11 at all?

Either way, is there a way to ensure cross-browser compatibility? Do I have to convert SVG to PNG and then use?

**Comment by 3zzy** [comment]
Okay, turns out its a longstanding Firefox bug: https://stackoverflow.com/questions/28690643/firefox-error-rendering-an-svg-image-to-html5-canvas-with-drawimage

**Comment by lavrton** [comment]
Hah. That is a very good workaround. Thanks for sharing. I am going to create a tutorial about drawing svg images. Will link to your sample.

**Comment by lavrton** [comment]
https://konvajs.org/docs/sandbox/SVG_On_Canvas.html#How-to-show-SVG-image-on-canvas
