### ISSUE TITLE
konva-node canvas.Canvas is not a constructor

### ISSUE THREAD

**Issue by ByronMorley** [konvajs/konva#680]
I cant seem to get konva-node to work.

The first error I get is canvas.Canvas is not a constructor.

I have checked the docs for canvas and they say that the constructor has been removed in version 2, I tried using version 1 but couldnt get it to compile. node-gyp build error. 

Before I direct my efforts towards canvas I wanted to confirm whther the issue isnt konva-node as your dependencies show version 2 and i cant get it to work with it.

I managed to override the canvas injection with

```
Konva.Util.createCanvasElement = () => {
        const node = new createCanvas();
        node.style = {};
        return node;
    };
```

but then the stage throws a container not found error.

any help is much appreciated, thank you.

**Comment by lavrton** [comment]
Can you make a repo to reproduce the problem?

**Comment by lavrton** [comment]
Closing as there is no enough info.
