### ISSUE TITLE
有关版本升级的问题

### ISSUE THREAD

**Issue by abcsimon** [konvajs/konva#681]
vue 工程 直接将 konva 从 2.6.0 升级到 3.3.3   vue-conva 从 2.0.0 升级到 2.0.7 可以不

**Comment by lavrton** [comment]
So what is your issue? It doesn't work?

**Comment by abcsimon** [comment]
> 那么你的问题是什么？它不起作用？

Can the vue project directly upgrade konva from 2.6.0 to 3.3.3 and vue-conva from 2.0.0 to 2.0.7?

**Comment by lavrton** [comment]
Yes, you may read breaking changes in `konva@3.0.0` here https://github.com/konvajs/konva/blob/master/CHANGELOG.md#3002019-02-25

But almost all of them a "private" and with internal rewrites. So the app should continue to work without any changes.

**Comment by abcsimon** [comment]
> 是的，您可以在`konva@3.0.0`这里阅读重大更改https://github.com/konvajs/konva/blob/master/CHANGELOG.md#3002019-02-25
> 
> 但几乎所有这些都是“私人”并且内部重写。所以应用程序应该继续工作而不做任何更改。

ok,  thanks
