### ISSUE TITLE
Delay onDragEnd when dragging with 3 fingers

### ISSUE THREAD

**Issue by Maiko1100** [konvajs/konva#682]
I'm using an `onDragEnd` function to execute some logic. This works great, but when I drag by using the 3 finger gesture on my Macbook the `onDragEnd` function gets called with a delay. I recreated the problem in a Code Sanbox: https://codesandbox.io/s/react-konva-basic-demo-0jnwl?fontsize=14 

`onDragEnd` will fire an alert. When dragging with a mouse or a using 2 finger drag the `onDragEnd` will execute immediately but when using the 3 finger drag there is a delay.

**Comment by lavrton** [comment]
At the current moment, `Konva` doesn't have good multitouch support. How do you use 3 finger drag? Dragging different objects? Dragging just one?

**Comment by lavrton** [comment]
`Konva` now has much better support for multitouch events. Closing the issue. If you still have problems - just add more information.
