### ISSUE TITLE
How to set Text Background Color?

### ISSUE THREAD

**Issue by kushalbacancy** [konvajs/konva#684]
I want to make the Text background color to other than the default(white).
Is there any way to set the background color to Text.  Like as showing below:-
![screenshot-docs google com-2019 07 09-12-03-15](https://user-images.githubusercontent.com/50192385/60864560-8f2a5180-a241-11e9-8f65-81a4a7f6ccec.png)

In this image, I set the background color and give the border style and text to the center.

**Comment by lavrton** [comment]
Use https://konvajs.org/docs/shapes/Label.html or just two shapes: `Konva.Rect` for background and `Konva.Text`

**Comment by kushalbacancy** [comment]
I am using the VueJS, So is that possible in VueJS?

**Comment by AniruddhRathod** [comment]
this is not working with a resizable text how I can set bgColor on resizable text

**Comment by sTone3** [comment]
I used sceneFunc to set the background color of the Text.
could be resized

Like this:
```
let t = new Konva.Text({
  x: 0,
  y: 0,
  text: "Sample text!",
  sceneFunc: function(context, shape) {
    context.fillStyle = 'rgb(255,255,204)';
    context.fillRect(0,0,shape.width(),shape.height());
    (shape as Konva.Text)._sceneFunc(context);
  },
});
```

I tried with Label, Text, and Tag, but Transformer couldn't handle it easily, so I decided to deal with it here.
