### ISSUE TITLE
free drawing  problem

### ISSUE THREAD

**Issue by 5201314999** [konvajs/konva#685]
1 https://konvajs.org/docs/sandbox/Free_Drawing.html
free drawing: when I move slow the whole line is not smoother than
https://canvas.apps.chrome/，maybe it is due to the points are too dense  and when I move it quick it will show many small straight lines. maybe it is due to the numer of points is too few。can it be improve 

2 when I set the apacity ,the color can not make a  overlap at the same point. example:
 https://codepen.io/buhaoyisiwoyao/pen/EBRrOb

**Comment by lavrton** [comment]
1. you may need a lot of extra logic to make lines smooth. That is a complex problem. For the simple solution, you can try to use `tension` property for `Konva.Line`.

2. What do you expect here? I don't get it.

**Comment by 5201314999** [comment]
1. **tension** is not effect
2.  I expect like https://5201314999.github.io/jrNoteWebsite/docs/20pic.html

**Comment by 5201314999** [comment]
a new question: when I draw a lot of graphic ，it will have a deplay 。I want to know whether it does partial updates during draw . does it take a lot of time to match node?  this is my program: http://dev-whiteboard.tvflnet.com/index.html#/home/50

**Comment by 5201314999** [comment]
> 1. you may need a lot of extra logic to make lines smooth. That is a complex problem. For the simple solution, you can try to use `tension` property for `Konva.Line`.
> 2. What do you expect here? I don't get it.

tension is not effect
I expect like https://5201314999.github.io/jrNoteWebsite/docs/20pic.html

**Comment by lavrton** [comment]
As for now, I don't see any ways to implement darker overlap for strokes. That is how 2d canvas API works.

**Comment by 5201314999** [comment]
https://canvas.apps.chrome/  I think it is very good, but  I don't how to do it 。do you have some advices？

**Comment by lavrton** [comment]
Hard to say. It is complex. And probably it doesn't use 2d API at all. As I can see it is using `webgl2` context. You may try to find other demos and apps with similar behavior to make a similar implementation.
