### ISSUE TITLE
Missing type definition for dashOffset

### ISSUE THREAD

**Issue by Avejack** [konvajs/konva#686]
Hello!

I am very happy about the feature implementation of lineDashOffset (issue: #212, merged pull request: #214) sadly typescript isn't able to recognize the dashOffset() Getter/Setter.

Example:
```ts
const line = new Konva.Line();
line.dashOffset(); // Property 'dashOffset' does not exist on type 'Line<LineConfig>'.
```

At the moment we can just do:
```ts
const line = new Konva.Line();
(line as any).dashOffset();
```

Thanks for this amazing library, cheers!

**Comment by lavrton** [comment]
I will make a release later. Thanks for the report.
