### ISSUE TITLE
how to define different border-radius when i use Konva.Rect()

### ISSUE THREAD

**Issue by EvilChxm** [konvajs/konva#687]
how to define different border-radius for the rect angles when i use Konva.Rect(). Like css attribute border-top-left-radius

**Comment by lavrton** [comment]
Just implemented it. See a demo: https://konvajs.org/docs/shapes/Rect.html

**Comment by frizurd** [comment]
> Just implemented it. See a demo: https://konvajs.org/docs/shapes/Rect.html

Are there any plans to implement this for image objects?

**Comment by lavrton** [comment]
No. Use group with clipping for such a use case.
