### ISSUE TITLE
fillPatternImage requires caching when using crossOrigin images

### ISSUE THREAD

**Issue by optimistiks** [konvajs/konva#688]
https://jsfiddle.net/4bq8td25/4/

The documentation states that we need to cache our nodes to apply filters like blur and contrast. It is shown in the fiddle and it's working as intended. However, it's also shown in the fiddle that `fillPatternImage` does not work at all on the rectangle, unless we cache the rectangle as well, and it only applies to crossOrigin images, images from the same domain work fine without caching. Is it a bug, or is it working as intended?

**Comment by lavrton** [comment]
In your demo, I see a fill pattern on the `rect` without caching.

**Comment by lavrton** [comment]
You may need to set `fillPatternScale` to have the same result as for image.

**Comment by optimistiks** [comment]
As you can see, the rectangle is just plain white when I don't use cache, so it's not about `fillPatternScale`.

However, what is really strange, that it works just fine without cache if I open another browser on my machine, or use any remote browser on browserstack. But in my local Chrome, latest version, all extensions off, private mode even, it works like on the screens below:

![Selection_072](https://user-images.githubusercontent.com/2562823/61182265-95ea0780-a639-11e9-83ac-c51cc5cbd0a3.png)
![Selection_071](https://user-images.githubusercontent.com/2562823/61182266-95ea0780-a639-11e9-9309-fdd8ecd73a1e.png)

So it's probably nothing wrong with Konva and just a strange combination of local factors. Thanks for looking into it.

**Comment by lavrton** [comment]
Hmm. For me, it works exactly the same with and without caching. Trying Chrome and Firefox.
