### ISSUE TITLE
When the stage is shrunk, the mouse event of the line cannot be triggered.

### ISSUE THREAD

**Issue by W-Rick** [konvajs/konva#689]
Hello!

I used Konva to develop applications and encountered some problems.

I set up a mouse event online, and when I shrank the stage, the mouse event could not be triggered.

The following is the line mouse event code:

      **linkObj.on('mouseover', function() {
        stage.style.cursor = 'pointer';
      });**

Here's my code for downsizing the stage:

    **let scaleBy = 1.01;
    this.stage.on('wheel', e => {
      e.evt.preventDefault();
      let oldScale = this.stage.scaleX();

      let mousePointTo = {
        x: this.stage.getPointerPosition().x / oldScale - this.stage.x() / oldScale,
        y: this.stage.getPointerPosition().y / oldScale - this.stage.y() / oldScale
      };

      let newScale = e.evt.deltaY > 0 ? oldScale * scaleBy : oldScale / scaleBy;
      this.stage.scale({ x: newScale, y: newScale });

      let newPos = {
        x:
          -(mousePointTo.x - this.stage.getPointerPosition().x / newScale) *
          newScale,
        y:
          -(mousePointTo.y - this.stage.getPointerPosition().y / newScale) *
          newScale
      };
      this.stage.position(newPos);
      this.stage.batchDraw();
    });**

Please also have a look. Thank you.

**Comment by lavrton** [comment]
Why do you think it doesn't trigger?

**Comment by lavrton** [comment]
I am sure this line `stage.style.cursor = 'pointer';` will not work.

**Comment by W-Rick** [comment]
Thank you very much for taking the time to look at this question.

I am not very convenient to make an online demo for you to see, but I will provide the following two screenshots, and with text to illustrate the problems I encountered:

Legend 1:
![05674966-0F1A-4EDF-9B93-F956E790FA60](https://user-images.githubusercontent.com/38304544/61276393-8823b600-a7e2-11e9-9e84-ea9ed49e1c79.png)
Explain:
           I drew a black line and added a "mouseover" event to the object of the line. When the mouse moved to the line, it changed its shape to "pointer" to trigger the "mouseover" event.

Legend 2:
![C34785C5-2947-4CF4-939A-38D12F31710B](https://user-images.githubusercontent.com/38304544/61276666-0da76600-a7e3-11e9-9e00-021cf911cce4.png)
Explain:
           When I downsized the stage, the scale of the stage ranged from 0.3 to 0.2, and tried again to trigger the "mouseover" event on the line with the mouse. It was found that the event could not be triggered, and there was no trigger event during my debugging of the code.

**Comment by lavrton** [comment]
I think that is because hit area of line is getting too small, so `Konva` can't really trigger it. As workaround, you can use `hitStrokeWidth` to make hit area bigger.

```javascript
const shape = new Konva.Line({
  x: 50,
  y: 50,
  points: [0, 0, 200, 0],
  stroke: 'green',
  hitStrokeWidth: 10
});
layer.add(shape);
```

https://jsbin.com/xoquzayuje/2/edit?html,js,output

**Comment by W-Rick** [comment]
Thank you very much. I set up "hitStrokeWidth" to solve the problem I encountered.
