### ISSUE TITLE
text组件 间距大于0使用emoji显示不正确

### ISSUE THREAD

**Issue by zhangxiaobai97** [konvajs/konva#690]
这是我的代码
const stage = new Konva.Stage({
  container: 'container',
  width: window.innerWidth,
  height: window.innerHeight
});

const layer = new Konva.Layer();
stage.add(layer);

const text = new Konva.Text({
  x            : 150,
  y            :150,
  text         : 'emoji🍎',
  fontSize     : 40,
  letterSpacing: 1
});
layer.add(text);

layer.draw();

**Comment by lavrton** [comment]
As I can see it completely breaks the drawings.

**Comment by lavrton** [comment]
Demo: https://jsbin.com/hiqisogopo/1/edit?html,js,output

Note: current code for splitting text into characters is not correct. As a solution we can try to use https://github.com/lodash/lodash/blob/4.4.0-npm-packages/lodash.toarray/index.js (converting string into array).

**Comment by zhangxiaobai97** [comment]
You mean let me split a Text into multiple Text displays, right?

**Comment by lavrton** [comment]
You can split it. But I think think it is a bug in Konva code. I think it should handle Unicode as expected.

**Comment by GeorgeGkas** [comment]
In case someone tries to solve this, `canvas` can render automatically Unicode characters. [example](https://jsfiddle.net/p1vc34La/)

**Comment by GeorgeGkas** [comment]
Also note that this works as expected with `react-konva`. [example](https://codesandbox.io/embed/react-konva-unicode-6pnm1)

**Comment by GregDev62** [comment]
Issue still existing on _"react-konva": "^16.13.0-3"_, is there a solution ? 
On the left of the screenshot is the konva text and on the right html content editable.
![firefox_edAJxDRZ3b](https://user-images.githubusercontent.com/69753737/93021839-693ad280-f5e5-11ea-8d43-2b6beb7d98b1.png)

**Comment by lavrton** [comment]
Will do a release later.
