### ISSUE TITLE
What can I do if I would like to install 2 libraries with `konva`?

### ISSUE THREAD

**Issue by seta-tuha** [konvajs/konva#691]
If I install 2 libraries which include `konva`, there is an error: `Konva instance is already exist in current eviroment. Please use only one instance`. I see in the issue: https://github.com/konvajs/react-konva/issues/253. How can I deal with this problem?

**Comment by lavrton** [comment]
What libraries do you use?

**Comment by seta-tuha** [comment]
@lavrton Actually they are my org private. When I draw the second canvas, there is an error:
Konva.SceneCanvas is not a constructor

**Comment by lavrton** [comment]
Check `node_modules` for several `Konva` versions. If you have many of them - check why you have them.

**Comment by seta-tuha** [comment]
Let me check! Thank you for quick response!
