### ISSUE TITLE
How can I reverse select a shape on the canvas?

### ISSUE THREAD

**Issue by 2hands10fingers** [konvajs/konva#692]
Hello!

I'm a little stumped with how I can select a shape by clicking on a button in a different component. I have the stage in a global state, and when I click the button, I do this

```

  function reverseSelectionHandler({name}) {
    const shape = context.state.currentStage.find('.' + name);
  }
```

What would I do next?

**Comment by lavrton** [comment]
What do you mean by "select"? Change color? Attach transformer?

**Comment by 2hands10fingers** [comment]
Attaching a transformer would be best!

**Comment by lavrton** [comment]
In case of React, I think you should save information about selected shape somewhere in your state, like:
```javascript
this.setState({
  selectedShapeId: id
})
```

Then create and attach a transformer when `selectedShapeId` is changed.

https://konvajs.org/docs/react/Transformer.html
