### ISSUE TITLE
Can you prevent an object from receiving "pointer-events"?

### ISSUE THREAD

**Issue by heaversm** [konvajs/konva#693]
Hi - I'm trying to make sure an Image that is under another Image (in terms of zIndex) is able to be dragged. Not sure how to do this in Konva / Canvas, but in the DOM I would make sure the `pointer-events` of the top object in CSS were set to `none`. Does Konva have an equivalent?

**Comment by heaversm** [comment]
Gosh, found out right after asking this:

```
<Image
  isInteractable={false}
/>
```

(Konva React)

**Comment by lavrton** [comment]
Hmmm. I don't think there is a `isInteractable` property. It shoud be:

```javascript
<Image
  {...props}
  listening={false}
/>
```
