### ISSUE TITLE
Konva.Rect does not work with three points

### ISSUE THREAD

**Issue by Vadi** [konvajs/konva#694]
Not sure if this is a bug but creating it one here any way. So with this code setup - 

```
const width = window.innerWidth - 10;
const height = window.innerHeight - 10;

const stage = new Konva.Stage({
  container: "container",
  width: width,
  height: height
});

const layer = new Konva.Layer({
  name: "main-layer"
});

const line = new Konva.Line({
  points: [0, 20, 210, 20, 220, 20],
  stroke: "green",
  strokeWidth: 1,
  lineJoin: "round",
  bezier: true
});

layer.add(line);
stage.add(layer);
```

I expect a straight line to be created from `0,20` to `220,20`. However this doesn't produce a line at all, whereas with `point` have 4 (x,y) sets works fine, for example, below draws a line -

```
  points: [0, 20, 210, 20, 220, 20, 220, 20],
```
I just added `220,20` one more time in the array.

Any help is greatly appreciated.

JS Bin: https://jsbin.com/dahusacezi/edit?html,js,output

**Comment by lavrton** [comment]
That is because you are using `bezier: true`. Bezier curve needs three points to make a draw (see docs: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/bezierCurveTo)
With the starting point, you will need 4 points.

**Comment by Vadi** [comment]
Thanks. Isn't we expect a runtime error from framework saying bezier requires 3 points atleast
