### ISSUE TITLE
Turn off anti-aliasing when drawing

### ISSUE THREAD

**Issue by bornfree** [konvajs/konva#695]
I'm using KonvaJS for a drawing app that sends the drawings to backend.
It's been working great so far!

But we have a requirement in the backend that there can only be a limited values of RGB. So I set my brush colors to these. However after I send my user-drawn image to backend, I'm seeing extraneous RGB values possibly due to anti-aliasing.
This also happens when a `transformer` is used to scale a shape.

I've already looked at #366 but setting `context.imageSmoothingEnabled = false` is not working.
Any ideas?

![anti aliasing](https://ageeky.com/wp-content/uploads/2015/08/aaexampleIMG_id1386238400_343178.jpg)

**Comment by lavrton** [comment]
As far as I know, there are no ways to remove antialiasing for canvas shapes (like lines). The only workaround is to make postprocessing to remove semi-transparent pixels.

**Comment by bornfree** [comment]
Got it. 
That sounds like a fair solution. I'm not sure if approximated pixels always going be semi-transparent.
Let me try this out. Thanks for the help! :)
