### ISSUE TITLE
Browser support help!

### ISSUE THREAD

**Issue by qqfei1858** [konvajs/konva#696]
Hello, how about support for different versions of the browser? I found that the browser version can not see the browser version support! Especially the IE series, because the project needs to use IE, IE10, and IE11 support canvas! Please forgive me English not good!

**Comment by lavrton** [comment]
Yeah, I guess we need to add notes about it and make some tests.

I guess it should work just fine with IE11 and you may need `Map` polyfill for EI10 support.

**Comment by lavrton** [comment]
https://github.com/konvajs/konva#browsers-support

**Comment by Emiya0306** [comment]
@lavrton 
Hi~ Does that mean if we add the polyfill of `Array.prototype.find`, `String.prototype.trimLeft`, `String.prototype.trimRight` and `Map`, Konva will work on IE10?
If that's true, I think it is very nice.

**Comment by lavrton** [comment]
Yes, it should
