### ISSUE TITLE
How can Animation run in background mode

### ISSUE THREAD

**Issue by yanxlg** [konvajs/konva#697]
when browser is in background，any animation will stop，what can we do to enable the animation run in background?online resolution is use worker to calc state，when browser go frontend worker will post the result state to js thread.now such as fabricjs also can not run in background.i think this is a very important issue which need to be resolved.

**Comment by lavrton** [comment]
Why do you need animation on the background?

Browsers are trying to minimize the work when possible. So they can "pause" js execution when the tab is not active.

**Comment by yanxlg** [comment]
For more application scenarios，such as Games or Online Education.In Games,we wish animations can run whenever browser is on the background.In Online Education,we want to control student's canvas run as teacher's whenever browser is on the background and so on.

**Comment by lavrton** [comment]
At the current moment, I don't know any ways to guarantee javascript execution when the tab is not active. 

And I don't see why you may need animation on the inactive tab.
