### ISSUE TITLE
API doc of Konva.Image#image parameter and return type are wrong

### ISSUE THREAD

**Issue by naqtn** [konvajs/konva#698]
Konva.Image#image method parameter and return type are noted in
[Image.ts](https://github.com/konvajs/konva/blob/master/src/shapes/Image.ts) as

    * get/set image source. It can be image, canvas or video element
    (snip)
    * @param {Number} y
    * @returns {Number}

Though I don't know how to write type of "image, canvas or video element", at least, `Number` seems wrong,

**Comment by lavrton** [comment]
Thanks for the report. Fixed. Will update the doc on the site later.
