### ISSUE TITLE
drawHitFromCache does not work properly with Groups

### ISSUE THREAD

**Issue by pronebird** [konvajs/konva#70]
Hi,

I have a group with image inside, I can't use `image.drawHitFromCache()` if I want to cache the whole group. Caching group before or after `drawHitFromCache()` does not help. I use group because sometimes I add more nodes to it and I'd like to cache the whole group.

**Comment by pronebird** [comment]
Hmm it seems that this actually works:

```js
var image = group.findOne('.image');
image.cache();
image.drawHitFromCache();
group.cache();
```

**Comment by lavrton** [comment]
For the current moment `drawHitFromCache` is `Konva.Shape` method. I think we can add it to `Konva.Group` and `Konva.Layer`.

**Comment by lavrton** [comment]
Nope. It is not possible to implement `drawHitFromCache` for any `Konva.Node` only for `Konva.Shape`. I just forgot how `drawHitFromCache` is working.
