### ISSUE TITLE
Proper cleaning of stage and refs

### ISSUE THREAD

**Issue by igorcouto** [konvajs/konva#700]
Hi,

We are using a react app with react-konva. Each time we navigate though a route (and then recreate stage/layers) the performances drop off, increasingly. The first access is always ok.

Is there a way to proper cleaning on componentWillUnmount? Or to check if some reference was not cleaned?

Thank you.

**Comment by lavrton** [comment]
If you are using `react-konva` all nodes should be cleared. To check to memory leaks you can try to find it in Dev Tools or just check `window.Konva.stages` and `window.Konva.shapes`.

When exactly do you have a perf drop? On stage load? Or stage destroy?

**Comment by mboperator** [comment]
`window.Konva.stages` doesn't seem to track the canvas being rendered for me.

Anecdotally I'm also experiencing the issue @igorcouto is dealing with. 
Would be happy to add some memory traces later on in the day

**Comment by igorcouto** [comment]
Have checked and stages and shapes are clean. The perf drop is after some stages recreation (using react, after componentUnmount and mount again).

I will take a look at memory in devtools.

Some thoughs?

**Comment by igorcouto** [comment]
Hey,

I guess that have found something suspect. I'm following chrome instructions on finding memory leaks taking heap dumps after forcing garbage collection. What I have done:

- Take and analyze a dump before any Konva component mounted.
- Take and analyze a dump after one stage created/used.
- Create/recreate several times the stage (mount/umount).

Each step forcing garbage collection.

When konva is not loaded, no CanvasRenderingContext.
The first time, 4 CanvasRenderingContext (qty of layers).
Several times: 67 CanvasRenderingContexts, 103 CanvasRenderingContext

@lavrton , do you think that might be causing the performance drop?

<img width="1678" alt="no canvas rendering" src="https://user-images.githubusercontent.com/18398326/62253150-58bc9e00-b3cb-11e9-9661-0dd9340b9757.png">
<img width="1680" alt="just quantity of layers, fist time" src="https://user-images.githubusercontent.com/18398326/62253160-607c4280-b3cb-11e9-88a5-a5c8b925a491.png">
<img width="1483" alt="63 contexts, several times" src="https://user-images.githubusercontent.com/18398326/62253169-670aba00-b3cb-11e9-9a76-77cb61a0ab3c.png">
<img width="1496" alt="103 contexts, several times" src="https://user-images.githubusercontent.com/18398326/62253174-6a9e4100-b3cb-11e9-958f-ee15229eaa72.png">

**Comment by lavrton** [comment]
Do you use any dev tools? Like, react dev tools?
Do you have a working example online to test?
Can you reproduce this with minified production build?

**Comment by lavrton** [comment]
I tried this demo. After toggling stage many many times I don't see huge issues. https://codesandbox.io/s/react-konva-leak-test-356nm

**Comment by igorcouto** [comment]
Hi Anton,

Sorry for the delay. I have inspected your demo using chrome dev tools and behaviour is very different. After about 100x state changes , we have only 9 canvas contexts dettached and about other 4 ones.

I'm thinking on node refs or many layes/shapes preventing garbage collection or another hypothesis. If I don't find anything, perhaps we can get in touch to ask your for some help on optimizations or dig deeper in framework on this specific case (that might be of others too).

<img width="1301" alt="Screen Shot 2019-08-09 at 00 07 21" src="https://user-images.githubusercontent.com/18398326/62751398-f05c6500-ba39-11e9-9da9-9913f41992d3.png">

**Comment by lavrton** [comment]
As I remember I had a similar issue a long time ago. React was saving old props and refs somewhere in DOM elements. So it produces memory leaks. I am not 100% sure, but I think the issue was in development mode or using Chrome React Dev Tools. On production mode with no extensions is was working fine.

**Comment by HmynKhan** [comment]
Memory Usage Issue When Loading Konva Canvas with FFmpeg in React + Vite Project

Hi @lavrton,

I'm encountering a significant memory usage issue when loading a canvas to display media in my React + Vite project, which uses Konva.js for canvas rendering.

The problem arises when I load the canvas for the first time—it immediately consumes a large amount of memory (~2.5GB) in the browser. This is further exacerbated by the fact that I also use FFmpeg (via @ffmpeg/ffmpeg) to record the canvas and convert WebM to MP4. When I load the canvas again, FFmpeg is reloaded alongside the new canvas, adding another ~2.1GB, bringing the total memory usage to ~4.6GB.

Here's a bit more context:

The project involves custom layout creation, where I define divisions and display media within those divisions on the canvas.
Every time I load a new layout, the canvas and FFmpeg are both reloaded, causing significant memory accumulation, especially in Google Chrome.
Despite attempts to optimize, the canvas seems to persist in memory without properly unmounting, and FFmpeg also continues to consume additional resources with every new load.
I’ve been leveraging FFmpeg's multi-threaded WebM to MP4 transcoding, which requires SharedArrayBuffer (meeting the security requirements for this). I've handled cross-origin policies and used SharedBufferArray, ensuring the app runs correctly, but the memory issues remain unresolved.

I’ve tried various methods to reduce memory consumption but haven’t found a solution. Any insights or suggestions to mitigate the memory load when reloading canvas and FFmpeg would be greatly appreciated.
Github Link: https://github.com/HmynKhan/hd2Menu1.1.git
Thank you for your time!

**Comment by lavrton** [comment]
@HmynKhan you have to profile the memory and see what exactly is consuming it.
