### ISSUE TITLE
How to get images' cropWidth  in Vue ?

### ISSUE THREAD

**Issue by iHanyuLee** [konvajs/konva#701]
Hi
I tried to use the method **image.cropWidth()** to get width in **Vue**, but it doesn't work.
I tried to find the answer from docs, but so many pages can't open, like [http://konvajs.org/docs/sandbox/](demo) and [http://konvajs.org/docs/vue/](vue).
Would you please help me?
Thanke you.

**Comment by lavrton** [comment]
Both pages work just fine for me.

Why do you need `image.cropWidth()`? In vue, you usually don't need to read the property. Just set it via config.

**Comment by iHanyuLee** [comment]
Well, thank you. Page works when I close my VPN =,=.
