### ISSUE TITLE
API doc of lastTime property in Animation doesn't match actual implementation

### ISSUE THREAD

**Issue by naqtn** [konvajs/konva#702]
From [Animation.ts](https://github.com/konvajs/konva/blob/master/src/Animation.ts)

      static _runFrames() {
          anim._updateFrameObject(now());
    
      ...(snip) ...
    
      _updateFrameObject(time) {
        this.frame.timeDiff = time - this.frame.lastTime;
        this.frame.lastTime = time;

So `lastTime` holds `now()` value. And `now()` is `performance.now()` or `new Date().getTime()`

On the other hand, doc says about lastTime: `The lastTime property is time in milliseconds that elapsed from the moment the animation started to the last animation frame.`
This doesn't match the implementation.

----
Additionally, I found a typo in time property text `that ellapsed from the moment the animation started`. => "elapsed" (double 'l')

**Comment by lavrton** [comment]
I guess we need to fix the docs for that case. Do you want to make a pull request?
