### ISSUE TITLE
Tension problem

### ISSUE THREAD

**Issue by AkopyanGregory** [konvajs/konva#703]
I create a shape ( like a line ), with tension 0.1. 
Call the function getSelfRect().
There are some times I get rect that 'NaN'.
I checked it and find that part of points in tension array is 'NaN'

**Comment by lavrton** [comment]
Can you make a full demo? Or provide other props for Line?

**Comment by lavrton** [comment]
Just tried this: https://jsbin.com/zipodohece/edit?html,js,console,output
It works ok.

**Comment by AkopyanGregory** [comment]
Hi.
I am very sorry. My mistake. I used "min" version and standard and standard version was different from "min".
