### ISSUE TITLE
Transformer.Box interface not exported => TransformerConfig.boundBoxFunc not usable in Typescript

### ISSUE THREAD

**Issue by andreas-eberle** [konvajs/konva#705]
In version 4.0.2 of your library, the interface Box in the Transformer.d.ts file is not exported. Since the TransformerConfig.boundBoxFunc() requires this type, it cannot directly be used with Typescript. 

Can you add the additional export? Or am I missing something?

Many thanks!

**Comment by lavrton** [comment]
Yeah, probably we should do that, but you can just use this interface:

```javascript
interface Box {
  rotation: number;
  x: number;
  y: number;
  width: number;
  height: number;
}
```

**Comment by lavrton** [comment]
How do you define that function? In many cases, you just don't need that type.

**Comment by andreas-eberle** [comment]
I define it like this:

```
private transformerBoundBoxFunction = (oldBox: Box, newBox: Box): Box => {
   ...
   return {....}
}
```

**Comment by lavrton** [comment]
I see. Also you can try to do this:

```javascript
const transformerBoundBoxFunction : TransformerConfig['boundBoxFunc'] = (oldBox) => {
  return {};
}
```

**Comment by andreas-eberle** [comment]
Well, for now, I copied the Box interface into by code and added a TODO to remove it when you added the export. Thanks in advance!
