### ISSUE TITLE
First transformer on a cloned image which had a transformer fails to transform

### ISSUE THREAD

**Issue by Seblor** [konvajs/konva#706]
Hello,

I noticed an issue when cloning an image which has a transformer attached.

Here is the process :
1. Create a node
2. Attach a transformer
3. Clone the node
4. Destroy the transformer
5. Attach a transformer to the newly cloned image
6. Try to resize the cloned image
7. `Cannot read property 'setAttrs' of undefined`

---

Here is a minimal, reproducible example : https://jsbin.com/vevikerefe/edit?js,console,output

If you try to resize the red rectangle, the error will happen, and the rectangle will be resized in width only.  
Then, if you click the "fix" button, the transformer will be destroyed, and a new one will be created & attached, and this one will work fine.

---

The error seems to be that when cloning a node that has a transformer attached, a "hook" or listener on the first image that links to the transformed is cloned too.  
Thus, when transforming the cloned image, Konva tries to change the dimensions of the now-destroyed transformer as well as the new one.

The error happens on trying to change the forst -top left- anchor :

```js
this.findOne(".top-left").setAttrs({ // this.findOne(".top-left") is undefined
```

One way to fix this is to attach the first transformer after cloning, and destroy it. Now any further transformer on the cloned image works just fine.

---

Konva version : from 2.3.0 to 4.0.3 (I have not tested previous versions)

**Comment by Seblor** [comment]
After taking a quick look, the error makes sense.

Attaching a transformer to a node adds listeners, but the node is anaware of the transformed attached.

When cloning a node, the listeners (including the transformer's) are copied over.

Then, destroying the transformer only removed the listener on the single attached node (https://github.com/konvajs/konva/blob/master/src/shapes/Transformer.ts#L253)

So the only fix I can see would be to either identify and ignore the transformer's listeners or any ` '.tr'` listeners when cloning.

However, I don't have enough knowledge of Konva's codebase to make a pull request myself.

**Comment by lavrton** [comment]
That a lot for a very good bug report and the demo. The bug is fixed. The fix will be released later in the next version.

**Comment by Seblor** [comment]
Thank you for fixing this so quickly.
