### ISSUE TITLE
How to calc shape actual attrs after using transformer in group

### ISSUE THREAD

**Issue by yanxlg** [konvajs/konva#707]
when i used transformer with group,then if use moveTo to move shapes from group to layer,the shapes position and attrs is wrong.if i want to keep it's render as in group,how to deal with it？

**Comment by lavrton** [comment]
I will create a detail demos soon. But for now you can use this:

https://stackoverflow.com/questions/56866900/konvajs-how-to-keep-the-position-and-rotation-of-the-shape-in-the-group-after-d

https://codepen.io/elscorpio/pen/VqvLpG

**Comment by yanxlg** [comment]
Thx，It's very helpful!

**Comment by lavrton** [comment]
`const attrs = shape.getTransform().decompose()`

Also with `konva@5.0.0` you can transform several shapes at once:

`tr.nodes([shape1, shape2]);`
