### ISSUE TITLE
dragstart event dose not work in v 4.0.4

### ISSUE THREAD

**Issue by ziggi111** [konvajs/konva#708]
const line = new Konva.Line({
     points: contour,
     stroke: 'red',
     strokeWidth: 1,
     closed: true,
     draggable: true
     });
     this.layers.tempLayer.add(line);
     line.on('dragstart', ev => console.debug('dragStart', ev));
     line.startDrag();

This code does not work. Although it worked in version 3.4.1

**Comment by lavrton** [comment]
Thanks for the report. Will be published with the new release soon.
