### ISSUE TITLE
How to use clip function with xor mode

### ISSUE THREAD

**Issue by yanxlg** [konvajs/konva#709]
How to use clip function with xor mode in canvas，it's helpful to erase some shapes!

**Comment by yanxlg** [comment]
For this，I want to achieve eraser brush width clip.But now I do not know any way to deal with it.How can I do?Is there any examples?

**Comment by yanxlg** [comment]
In other issues,someone say use globalcompositeoperation to deal with it,but globalcompositeoperation can not solve object transfrom issues,I thought is there any problem use clip with relative object and set globalcompositeoperation equal xor to implement it.

**Comment by lavrton** [comment]
What is your use case?

There is a demo https://konvajs.org/docs/sandbox/Free_Drawing.html#Free-drawing-with-Konva-nodes that shows how to use `globalcompositeoperation` to erase the image.

**Comment by yanxlg** [comment]
I have viewed this page,but when shape object drag and drop or transform,it's bad.so I think about if use erase path and other shape object combine a group,then clip with the object's border,it's will be better.But for this,all shape will be group,Maybe silgle shape will support this.

**Comment by yanxlg** [comment]
I have tried this,every thing is ok but clipFunc is not support with konva.shape.so clip as object's border is difficult

**Comment by lavrton** [comment]
Yeah `Konva.Shape` doesn't support clipping right now. But you can use it just fine for `Konva.Group`. If you have just one shape, you can move it into the group.

**Comment by RuanXuSong** [comment]
Did you solve this problem?I think `globalcompositeoperation` is not the best way to erase shape object.When I move or rotate object.It looks like a bug.I mean if objects in other layers which below this `destination-out` line move here,they are blocked too.It's bad.
