### ISSUE TITLE
Bug with Gifler

### ISSUE THREAD

**Issue by goodwin74** [konvajs/konva#710]
I did the gif-animation loading, following the example in the documentation. However, frames are skipped and frames are displayed incorrectly.

This happens to many gif files. Please, how to fix it, does anyone know?

[https://codepen.io/bulat73/pen/dxEobE](https://codepen.io/bulat73/pen/dxEobE)

**Comment by lavrton** [comment]
That looks like a bug in [gifler](http://themadcreator.github.io/gifler/) library used to parse the GIF file.

So it is better to address the issue there or find another library to use.
