### ISSUE TITLE
getClientRect() return wrong width and height when skipStroke set to false on Line and Arrow

### ISSUE THREAD

**Issue by chuen1118** [konvajs/konva#711]
I wanted to attach a transformer to a line but found that the transformer showing was really large.After some digging, I suspected that was caused by the getClientRect() which returned a really large width and height value. When I set skipStroke to true, the transformer did enclose the line nicely but that does not look good on arrow.

getSelfRect():
{x: 90, y: 88, width: 305, height: 93}

getClientRect():
skipStroke: true
{x: 90, y: 88, width: 305, height: 93}

skipStroke: false
{x: 87, y: 85, width: 873054914, height: 85934916}

version: 4.0.0 (minified)

**Comment by lavrton** [comment]
Can you make a demo? What line did you use?

**Comment by chuen1118** [comment]
https://jsbin.com/wevuwoxoju/edit?html,js,output

draw some lines with the brush then change to pointer and click on the line to attach transformer.

**Comment by lavrton** [comment]
I see the issue. Do not use string for `strokeWidth` property. It breaks the calculations.

The non-minimal version of `Konva` has a warning about that issue.

**Comment by chuen1118** [comment]
Wow, it works now, thanks for your help.

In this case, I would suggest you guys to update the demo code in free drawing. I just copy and paste the demo code and since everything works fine, I didn't notice the quote around the number.
https://konvajs.org/docs/sandbox/Free_Drawing.html

**Comment by lavrton** [comment]
Ops. You are right. Just fixed it.

Thanks for the report. 👍
