### ISSUE TITLE
Tap/touchstart event not recognised on shapes

### ISSUE THREAD

**Issue by renedekat** [konvajs/konva#712]
I've successfully implemented the transformer following this example: https://konvajs.org/docs/select_and_transform/Basic_demo.html

It works great on desktop, but when trying this on a mobile device (iOS 12) the transformer isn't shown.

As a workaround I attaching it upon drag-start and from there it all works.
I've tried registering the touchstart event using Hammer JS , but to no avail. Tapping on a shape doesn't fire any event.

It turns out that on mobile devices 2 events are fired when tapping on a shape. The first one is the stage and after that it fires the click event on the shape.

I found out when I commented the block of code that removes the transformer as seen below.
This is how it works on iOS 12 anyway.

The alert on a desktop fires only once with either 1 (stage) or 3 (the rect)
On my iPhone it fires twice when clicking the rect in this order: 3, 1

```
<!DOCTYPE html>
<html>
<head>
    <!-- USE DEVELOPMENT VERSION -->
    <script src="https://unpkg.com/konva@4.0.4/konva.min.js"></script>
    <meta charset="utf-8" />
    <title>Konva Select and Transform Demo</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #f0f0f0;
        }
    </style>
</head>

<body>
<div id="container"></div>
<script>
    var width = window.innerWidth;
    var height = window.innerHeight;

    var stage = new Konva.Stage({
        container: 'container',
        width: width,
        height: height
    });

    var layer = new Konva.Layer();
    stage.add(layer);

    var rect2 = new Konva.Rect({
        x: 250,
        y: 100,
        width: 250,
        height: 200,
        fill: 'green',
        name: 'rect',
        draggable: true
    });
    layer.add(rect2);
    layer.draw();

    stage.on('click tap', function(e) {
        alert(e.target._id);
        // if click on empty area - remove all transformers
        // if (e.target === stage) {
        //     stage.find('Transformer').destroy();
        //     layer.draw();
        //     alert('destroying transformer');
        //     return;
        // }
        // do nothing if clicked NOT on our rectangles
        if (!e.target.hasName('rect')) {
            return;
        }
      
        stage.find('Transformer').destroy();

        // create new transformer
        var tr = new Konva.Transformer();
        layer.add(tr);
        tr.attachTo(e.target);
        layer.draw();
    });
</script>
</body>
</html>
```

**Comment by renedekat** [comment]
A little hack to make it work on both desktop and iOS

```
....
    var lastEvent = false;

    stage.on('click tap', function(e) {
        // if click on empty area - remove all transformers
        if (e.target === stage && lastEvent !== e.evt) {
            stage.find('Transformer').destroy();
            layer.draw();
            return;
        }

        lastEvent = e.evt;
...
```

**Comment by lavrton** [comment]
That was the bug in the v4 release. I fixed it and published `konva@4.0.5`. Thanks a lot of the report. It should work ok now.

**Comment by renedekat** [comment]
@lavrton Will you update vue-konva too? It still uses  "peerDependencies": {
    "konva": "^3.2.2"
  },

**Comment by lavrton** [comment]
Updated with `vue-konva@2.0.8`.
