### ISSUE TITLE
Strict mode for typescript?

### ISSUE THREAD

**Issue by Reggino** [konvajs/konva#715]
@lavrton Thank you for this awesome project. 

Would you consider switching Typescript to "strict mode" in this project?

If so, i can prepare a PR with all the changes, but i'm afraid the change set will be pretty big... I do think it could improve stability for future releases.

**Comment by lavrton** [comment]
Yes, I am planning to do that. But there are many changes will be required. I am happy to apply any related Pull Request. We don't need to fix it at once. Slowly, step by step with small refactoring.
