### ISSUE TITLE
Transformer and dragBoundFunc()

### ISSUE THREAD

**Issue by aelfannir** [konvajs/konva#718]
Thanks for this awesome library!
When **rotation** is equal to 0 everything works fine.
here a [demo](https://jsbin.com/fekepodude/edit?js,output)
![captured](https://user-images.githubusercontent.com/38046657/63870418-d6b39b00-c9b1-11e9-8c83-49211dbd13fd.gif)

**Comment by lavrton** [comment]
There are many ways to fix the issue. In the case of a rectangle, you should remember that its `{x, y}` is a top left corner. So your math of dragBoundFunc should be more complex. As a workaround, you can use `offset` to set the origin of the shape to its center. So `{x, y}` will point to the center and calculations will be simpler in that case.

https://jsbin.com/gicisaceva/1/edit?js,output

**Comment by aelfannir** [comment]
Thank you @lavrton !
Here's my solution for Rect if someone needs it [Rect](https://jsbin.com/bizahovemu/edit?js,output)

**Comment by harrisjm3** [comment]
> Thank you @lavrton ! Here's my solution for Rect if someone needs it [Rect](https://jsbin.com/bizahovemu/edit?js,output)

FYI, this does not work if you resize the transformer first and then move it around. The rectangle will go beyond the drag boundary on the right side because your func is using the old size as reference.

I am trying to set dragBoundFunc after a resize.
