### ISSUE TITLE
fillPatternScale affects letter size

### ISSUE THREAD

**Issue by Granga** [konvajs/konva#720]
Changing `fillPatternScale` on a `Konva.Text` instance visually affects the text size.
However, `getClientRect()` on the `Konva.Text` instance remains unchanged.

If we were to change `fillPatternScale` on a, for example `Konva.Circle` instance, the circle size stays the same.

I expect `Konva.Text` text size to not be affected by `fillPatternScale`.

Here's a demo of the problem: https://codesandbox.io/s/konva-demo-wts62

![image](https://user-images.githubusercontent.com/6062311/63984321-07d3be80-cacb-11e9-97d3-392250ed9f19.png)

**Comment by lavrton** [comment]
Fixed with the last release. Thanks for the report!

Working demo: https://codesandbox.io/s/konva-demo-o22i1

**Comment by lavrton** [comment]
Bad news. I have to rollback the fix. Because it doesn't work in Firefox. https://github.com/konvajs/konva/issues/720

Need to think about how to resolve the bug in another way.

**Comment by lavrton** [comment]
Looks like it is working ok with FF now. I am going to re-release the fix again.
