### ISSUE TITLE
Tapping quickly after a drag is considered a 'double-tap'

### ISSUE THREAD

**Issue by erlloyd** [konvajs/konva#721]
This problem is reproducible in the multiple object drag-and-drop demo on the konva demos page: https://konvajs.org/docs/sandbox/Drag_and_Drop_Multiple_Shapes.html

Basically, if you are on a mobile device (I reproduced with an android phone using Chrome and a iPad using mobile safari), after you drag an object, if you quickly tap that object, the tap will be handled like a double-tap. 

This doesn't happen on a desktop system with dragging and double-click.

Repro steps:
1) Go to https://konvajs.org/docs/sandbox/Drag_and_Drop_Multiple_Shapes.html on a mobile browser
2) Drag one of the rectangles for a bit around the screen
3) Stop dragging and quickly tap the same rectangle you were dragging

EXPECTED: The rectangle is not removed from the screen since you didn't perform a 'double-tap'.

ACTUAL: The rectangle is removed from the screen

**Comment by lavrton** [comment]
That for the report. The bug is fixed. I will publish it later.

**Comment by erlloyd** [comment]
Thanks for the quick fix!
