### ISSUE TITLE
fillPattern on Konva.TextPath is applied per letter, instead of the whole text

### ISSUE THREAD

**Issue by Granga** [konvajs/konva#722]
`fillPattern` of `Konva.TextPath` behaves differently than on `Konva.Text`.
I noticed that (under default settings) `Konva.TextPath` applies only the left beginning of the `fillPattern` image to each letter. However, `Konva.Text` applies the pattern image to the whole text.

In the demo one of the patterns is half red - half yellow image, with width similar to the `Konva.Text`. We can notice yellow part never appears on the `Konva.TextPath`, while it covers half of `Konva.Text`.

The expected behavior is that `fillPattern` should be applied on the box, instead of per letter.

Demo: https://codesandbox.io/s/konva-demo-917vh

In my opinion, current implementation can also be seen as feature, especially the part where it rotates the pattern with every letter. The best case would be if we can choose between:
 - pattern per letter
 - pattern on text box

![image](https://user-images.githubusercontent.com/6062311/64070056-c07b3880-cc58-11e9-9b14-7fdd012fd16f.png)

**Comment by lavrton** [comment]
Hmmm. Need to think about how to resolve it.

As a workaround, you can draw text and place image on top of it with `globalCompositeOperation = destination-in`.

**Comment by lavrton** [comment]
I am closing the issue because I don't see any possible solutions from the Konva side. Only the workaround above.
