### ISSUE TITLE
When zoomed in with image in background, can dragBound be image edge not stage?

### ISSUE THREAD

**Issue by eoghanmccarthy** [konvajs/konva#723]
I'm making an image annotation tool which requires zoom and drag bounds. Using `dragBoundFunc` when the image is not zoomed works great but the problem is when zoom is applied.

Ideally the drag bounds would be the image edge (which when zoomed in are beyond the stage edge), not the stage edge. When you drag a shape that is partially hidden when zoomed in, the shape will jump to stage edge and not allow you to drag it beyond.

Sandbox demo is below. The demo is using the stage edges but I have tried a number of things to achieve what I want but no luck yet. If anyone has experienced this issue and found a solution I would really appreciate a help out.

[https://codesandbox.io/s/21w9w1pk1n](https://codesandbox.io/s/21w9w1pk1n)

**Comment by eoghanmccarthy** [comment]
Fixed the demo link.

**Comment by lavrton** [comment]
`dragBoundFunc` works with the absolute position of a node. So you have make some more complex calculations, because absolute position limit is different, depending of your stage attributes. If that is too hard for you, you can just use `dragmove` event and set local limits in it:

```
onDragMove={e => {
        const stage = e.target.getStage();

        e.target.x(
          Math.max(0, Math.min(e.target.x(), stage.width() - e.target.width()))
        );
        e.target.y(
          Math.max(
            0,
            Math.min(e.target.y(), stage.height() - e.target.height())
          )
        );
      }}
```

https://codesandbox.io/s/konva-demo-4sxey

**Comment by eoghanmccarthy** [comment]
Great that works, thanks :)
Really appreciate it.
