### ISSUE TITLE
Export konva to image in server side without render

### ISSUE THREAD

**Issue by hienlh** [konvajs/konva#724]
I have a template for image and when user change image inside template, server will automatically render a  new image for user. That's all I want to make.

I have a json from template which I created before. And now i want to export it on server side (expressjs, restful api) with Konva init by json.

When I try this code
```typescript
import {Stage} from 'konva/lib/core';
app.get('/', (_req: Request, res: Response, _next: NextFunction) =>
    res.status(200).send({
        message: loadKonvaJson(),
    }),
);


const loadKonvaJson = () => {
    let stage = new Stage({
        container: 'container'
    });
    
    return stage.toDataURL({pixelRatio: 1});
}
```
I have an error `ReferenceError: document is not defined`

**Comment by lavrton** [comment]
https://stackoverflow.com/a/57759816/512042
