### ISSUE TITLE
"dragstart" event is fired with undefined evt field

### ISSUE THREAD

**Issue by IgorDarkov** [konvajs/konva#725]
Hi, in the latest update (v4.0.5) I'm getting incorrect "dragstart" event, where .evt field is undefined.
In v3.4.1 .evt field used to reference instance of MouseEvent in my case.

I suppose that the reason is in the following line of code:
https://github.com/konvajs/konva/blob/0e34a8c9ca078ade8a62589c6c2f22b3bd4de0de/src/Node.ts#L2269
evt is instance of MouseEvent, which doesn't have .evt field.

In version 3.4.1 it was fired in the following way:
https://github.com/konvajs/konva/blob/05324c4eb73f341e31926ee2d3ef0b0bfe5963db/src/DragAndDrop.ts#L55

**Comment by lavrton** [comment]
Yeah, the behavior is slightly changed.  Did you call `node.startDrag()` manually?

**Comment by IgorDarkov** [comment]
> 
> 
> Yeah, the behavior is slightly changed. Did you call `node.startDrag()` manually?

No, I subscribe on "dragstart" event of a node (group in my case):
`this.group.on("dragstart", this.onDragStart);`

**Comment by lavrton** [comment]
I see the bug. It is fixed and published as `konva@4.0.7`. Try it. Does it work ok for you?

**Comment by IgorDarkov** [comment]
> 
> 
> I see the bug. It is fixed and published as `konva@4.0.7`. Try it. Does it work ok for you?

I tried new version (4.0.7) and it works fine now, thank you!
