### ISSUE TITLE
Konva warning: NaN is a not valid value for "radius" 

### ISSUE THREAD

**Issue by DmitryTarasenko149** [konvajs/konva#726]
I have "Konva warning: NaN is a not valid value for "radius" attribute. The value should be a number." warning while create a circle object using Vue.js
I hardcoded data in Vuex, then fetch it and display.
I do have such warning 2 times for each circle item.
Everything is rendered fine, but console is full of warnings.
In another project when I use data not from vuex, but from data() in Vue component it works without warnings

**Comment by lavrton** [comment]
Can you make a demo?  Do you have any calculations in your data or template?

**Comment by DmitryTarasenko149** [comment]
Yes, I do have calculations. 
I create an example demo with warning here:

**Comment by lavrton** [comment]
Can you make a https://codesandbox.io/ demo?

**Comment by lavrton** [comment]
https://codesandbox.io/s/github/DmitryTarasenko149/vue_konva

**Comment by lavrton** [comment]
I see the error. Your `seat` has `size: 50` property. And you pass all properties to `v-circle` component. Konva is tring to set that property. But it expects to have it in a form of `size: {width: 50, height: 50}`, but it is just a number, so calculations are broken and produce `NaN`. To fix the error, just pass the properties that are really required for your seat.

**Comment by DmitryTarasenko149** [comment]
> I see the error. Your `seat` has `size: 50` property. And you pass all properties to `v-circle` component. Konva is tring to set that property. But it expects to have it in a form of `size: {width: 50, height: 50}`, but it is just a number, so calculations are broken and produce `NaN`. To fix the error, just pass the properties that are really required for your seat.

Thank you a lot, it helps.
