### ISSUE TITLE
When the stage is scaled, New added object coordinate offset.

### ISSUE THREAD

**Issue by cenmes** [konvajs/konva#730]
How to deal with this problem?

**Comment by lavrton** [comment]
That is point of the scale. It zooms everying. The size of all objects and the distance between all coordinates.

**Comment by aelfannir** [comment]
```javascript
let scale = stage.scaleX()
let object= new Konva.Rect({
   x: 100*scale , y: 100*scale ,
   width: 10, height:20,
   scale: {x:scale, y:scale},
   fill: '#deb887', stroke: '#b4946f', strokeWidth: 2,
 });
```

**Comment by cenmes** [comment]
var width = window.innerWidth;
      var height = window.innerHeight;

      var stage = new Konva.Stage({
        container: 'container',
        width: width,
        height: height
      });
      var layer = new Konva.Layer({
        width: width,
        height: height
      })
      var rect = new Konva.Rect({
        x: 50,
        y: 50,
        width: 200,
        height: 200,
        stroke: 'red'
      })
      var box = new Konva.Rect({
        width: 0,
        height: 0,
        x: 0,
        y: 0,
        stroke: 'green'
      })
      box.hide();


      // when it was clicked, I want to add the box to it, but when stage is scaled, It's wrong



      stage.scale({
        x: 1.5,
        y: 1.5
      })
      rect.on('click', (e) => {
        let target = e.target;
        let pos = target.absolutePosition()
        box.setAttrs({
          x: pos.x,
          y: pos.y,
          width: target.getAttr('width'),
          height: target.getAttr('height')
        })
        box.show()
        layer.batchDraw()
      })
      layer.add(rect)
      layer.add(box)
      stage.add(layer);
      stage.draw();
![image](https://user-images.githubusercontent.com/21157837/64397336-8617fe00-d093-11e9-9ade-43b6920b77a6.png)

And I want to know how to get the realy size of a container, such as a group, When the elements inside him changed，It's  size should be changed, how to get it?

thanks!

**Comment by lavrton** [comment]
https://konvajs.org/docs/sandbox/Relative_Pointer_Position.html
