### ISSUE TITLE
lineCap: 'round'  Not available

### ISSUE THREAD

**Issue by gitrunfeng** [konvajs/konva#731]
new Arc： lineCap: 'round'  Not available

**Comment by gitrunfeng** [comment]
![image](https://user-images.githubusercontent.com/46260012/64398671-3c7de200-d098-11e9-96ca-b0f5d672f69b.png)

**Comment by gitrunfeng** [comment]
invalid

**Comment by lavrton** [comment]
What do you mean by "invalid"? `lineCap` is used to draw line end points. `Konva.Arc` has no "end points", so I don't think you will see `lineCap` visible here.

**Comment by lavrton** [comment]
https://jsbin.com/qehavebazo/1/edit?html,js,console,output
