### ISSUE TITLE
Transformer resize when scaleX or scaleY < 0 (mirrored node)

### ISSUE THREAD

**Issue by romainprevost** [konvajs/konva#732]
Hello!

I have an issue with the transformer when an Image node has a modified scaleX or scaleY < 0 to get a mirror effect, transformer does not preserve the position of the node, as if the wrong handle is clicked.

I made a codepen with 3 different images, the first has scaleX < 0 (horizontal flip), the second has scaleY < 0 (vertical flip), and a third one with both scaleX and scaleY < 0.

The last one works but not the first two.

[https://codepen.io/romainprevost/pen/MWgrJLd](url)

Thank you for your help!

**Comment by lavrton** [comment]
That fixed is published with `konva@4.0.9`.

**Comment by romainprevost** [comment]
Thank you very much for your quick fix, it works perfectly !!

**Comment by TopDragon523** [comment]
I am implementing image flip but there is an issue 
When the image has  negative scaleX,  the transformer direction  changed  downwards
![image](https://github.com/konvajs/konva/assets/97777348/b650e343-fc82-482a-becb-737eb3665a01)
If anybody knows about this issue, please help me
