### ISSUE TITLE
Konva 4.0.0 breaks touch stage.getPointerPosition()

### ISSUE THREAD

**Issue by songoffire** [konvajs/konva#733]
First and foremost, Konva is awesome and I super appreciate all your hard work on this amazing library.

**Issue:** *On touch devices, calling stage.getPointerPosition() after a touch event produces the following JS console error/warning:* 
- **ERROR**: konva.min.js:12 Uncaught TypeError: Cannot read property 'x' of undefined
- **WARN**: konva.min.js:12 Konva warning: Pointer position is missing and not registered by the stage. Looks like it is outside of the stage container. You can set it manually from event: stage.setPointersPositions(event);

**Steps to reproduce this error:**
  1. Open the Code pen here in the Chrome Dev Tools device simulator, or on a touch device:  https://codepen.io/songoffire/pen/jONYXgP
  2. Tap on the rectangle with the console open
  3. You should see the error fire in the console
  4. Change the Konva Script src in the HTML of the code pen to '...konva@3.4.1/konva.min.js'
  5. Repeat the steps 1-2
  6. Instead of an error, the correct touch position coords are logged to the console as epected.

**Comment by songoffire** [comment]
Thanks, awesome work as always - looking forward to the next release :)

**Comment by lavrton** [comment]
That fixed is published with `konva@4.0.9`.
