### ISSUE TITLE
context.arcTo calls `_context.arc`

### ISSUE THREAD

**Issue by Astray-git** [konvajs/konva#734]
The `arcTo` function calls `_context.arc`
https://github.com/konvajs/konva/blob/master/src/Context.ts#L277-L292

<del>btw. I think `arc` should accept optional 6th arg.
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/arc</del>

**Comment by lavrton** [comment]
Yeah, doesn't look right. Do you want to make a Pull Request?

**Comment by Astray-git** [comment]
PR created
