### ISSUE TITLE
Regression in version 3.2.1 when using multiple selectors in `find`

### ISSUE THREAD

**Issue by Seblor** [konvajs/konva#735]
Hello,

I am currently in the process of upgrading Konva from 2.6.0, and I noticed some breaking changes.

The first one being a regression in the 3.2.1 version, where the `find` and `findOne` function have been reworked ("Better find and findOne lookup" in the changelog).

Previously, I wanted to destroy all images and transformers, so I used this code :

```js
this.stage.find("Image, Transformer").destroy();
```

But now, using multiple selectors separated by a comma returns an empty Collection.

Should I select the 2 group separately or is there something I am missing ?

**Comment by lavrton** [comment]
That was a bug. Thanks for the report. I fixed it. I will make a release later.

**Comment by lavrton** [comment]
As workaround:
```
this.stage.find("Image").destroy();
this.stage.find("Transformer").destroy();
```
