### ISSUE TITLE
The vertical centering of the text does not seem to be correct. It is especially noticeable in Chinese.

### ISSUE THREAD

**Issue by techGay** [konvajs/konva#737]
demo:[https://codepen.io/techgay/pen/MWgrrLe](https://codepen.io/techgay/pen/MWgrrLe)

i try to set offsetY() than seems to look good

**Comment by lavrton** [comment]
What text don't look ok for you? `offsetY = 1` doesn't make much difference (it is just 1px).

**Comment by techGay** [comment]
It seems that all Chinese are like this，in my demo(right text is set offsetY) , i just set offsetY(-1) than look ok.

**Comment by lavrton** [comment]
Closing the issue.
