### ISSUE TITLE
Transformer resize handles and rotate handles not working.

### ISSUE THREAD

**Issue by alpha-hasher** [konvajs/konva#738]
Hi,

I have created a stage and then added a layer to it. Now, I add shapes to it, and attach a transformer to each. All works fine till here. When I resize the stage dynamically using the set size function and then add a shape to the extended area, it gets drawn as intended but the mouse cursor doesn't show upon hovering on the resize/rotate handles (on the transformer attached to this shape).
Let's say initially the stage size was 500 * 300, now I resized it to 800 * 500. Now, when I add any shape or image to the area which is just increased then the transformer doesn't work.

To me it looks like that it might be working but the cursor doesn't show up where it is supposed to.

**Comment by lavrton** [comment]
Closing as no demo provided. If you still have this issue, please make a demo.
