### ISSUE TITLE
Regression in version 4.0.5, Stopping a drag then starting a drag breaks the dragged image coordinates

### ISSUE THREAD

**Issue by Seblor** [konvajs/konva#739]
Hello,

Still upgrading Konva's version in my project, I have found an error with the drag & drop feature that happens from the 4.0.5 version.

How to reproduce :

1. Create a draggable stage
2. Add an image (i.e. a rectangle)
3. Listen on mousedown on the stage
4. In this listener :
   1. Stop the stage drag (with `stage.draggable(false)` or `stage.stopDrag()`)
   2. Start the drag on the image (`image.startDrag()`)

Now, clicking anywhere on the stage will break the image (position will take NaN).
However, if the first click is a right click, the drag & drop will work fine afterwards.

Here is a reproducible example :
https://jsbin.com/reviriyego/1/edit?html,js,console,output

After digging a bit, I found that the issue seem to come from `Node.prototype._createDragElement`.
The method gets called with no issue once from the `mousedown.konva touchstart.konva` listener, but then gets called a second time with the `startDrag()` call, with some issues :
The `pos` object gets the value from `stage._changedPointerPositions[0]`, where the `x` and `y` values are `NaN` (and the id is 999)

**Comment by lavrton** [comment]
Works ok now. Thanks for the report!

**Comment by lavrton** [comment]
Fixed in v `4.0.10`
