### ISSUE TITLE
Narrow down getIntersection() result

### ISSUE THREAD

**Issue by pronebird** [konvajs/konva#74]
Hi, is there any way to filter what node returned from `getIntersection`?

The use case I have is the following:

- Group
  - Image

When I call `stage.getIntersection(x, y)` I get Image, although I am interested in Group.

**Comment by pronebird** [comment]
Currently manually traversing up the tree to find whatever was the node of interest.

**Comment by lavrton** [comment]
Hm.. Is that useful? It is really easy to get parent of shape.
About suggestion. What if a group and a shape have the same name. The result might be unclear.

**Comment by pronebird** [comment]
I need to put more thought in it I guess.
