### ISSUE TITLE
Text direction same as CSS Writing Modes

### ISSUE THREAD

**Issue by Nadoedalo** [konvajs/konva#742]
Hello
Kovnva.Text class misses the option to select "text direction" -> not just standard "left-to-right" or "right-to-left" but also the "up-to-down" or all other variants - just like [CSS Writing Modes](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Writing_Modes) suggests.
I know that I should probably wait when Canvas API will be updated to natively support it since it is a complex issue.

But for now - is there a way to easily support vertical text orientation? I know Konva supports line breaks - one possible solution is just do that.
Is there more elegant way?

**Comment by lavrton** [comment]
As far as I know, Canvas API already have `right-to-left`. But we don't have support for it in Konva yet.

I am not sure about other variants. What vertical orientation do you need?

**Comment by Nadoedalo** [comment]
I've already done what I need by just simply adding a "\r\n" after each character in a string. Thus I've emulated up-to-down behavior and it should be enough for my specific circumstances.

But it doesn't support advanced stuff like multi-column top-to-down text - and I'm just afraid of how much time it may take to implement something like CSS writing modes properly.
I don't think that this should be a feature of the library - since rules may change suddenly(emoji will break my \r\n style of code, as an example). But it is still a nice feature to have.
Underline support is other feature to consider with text direction - since with \r\n style it just draws underline under each character.

For the canvas itself - it has [CanvasRenderingContext2D.direction
](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/direction) - but it is still experimental and is only available in Chrome by a flag.
And it doesn't support up-to-down yet.

Anyhow it is more of a feature request than a bug / issue since proper text direction support requires a lot of stuff to consider and is a big time sink.

**Comment by lavrton** [comment]
Closing the issue for now. I don't think we need deep text rendering inside the Konva core modules as per CSS spec.
