### ISSUE TITLE
how to display the ellipsis after the text is exceeded

### ISSUE THREAD

**Issue by EvilChxm** [konvajs/konva#744]
```
       new Konva.Text({
           x: ICON_WIDTH + NODE_PADDING,
            y: 0,
            text: data.nodeName,
            lineHeight: 1.5,
            fontSize: NODE_NAME_FONTSIZE,
            width: NODE_WIDTH - NODE_PADDING - ICON_WIDTH,
            height: NODE_ITEM_HEIGHT,
            fill: '#ffffff',
            verticalAlign: 'middle',
            padding: NODE_PADDING,
            wrap: 'char'
        })
```
here is my code . I just want to display the ellipsis after the text is exceeded.  How to achieve this function？

**Comment by lavrton** [comment]
This will work with `wrap: none`:

```javascript
const shape = new Konva.Text({
  text: 'Some very long\nmultiline text is placed here',
  lineHeight: 1.5,
  width: 100,
  height: 50,
  ellipsis: true,
  wrap: 'none'
});
```

https://jsbin.com/qacoyifoze/2/edit?html,js,output

**Comment by EvilChxm** [comment]
got it

**Comment by EvilChxm** [comment]
> This will work with `wrap: none`:
> 
> ```js
> const shape = new Konva.Text({
>   text: 'Some very long\nmultiline text is placed here',
>   lineHeight: 1.5,
>   width: 100,
>   height: 50,
>   ellipsis: true,
>   wrap: 'none'
> });
> ```
> 
> https://jsbin.com/qacoyifoze/2/edit?html,js,output

got it !! thanks
