### ISSUE TITLE
event dragend trigger 2 times

### ISSUE THREAD

**Issue by shimingw** [konvajs/konva#745]
I bound a dragend event for the element，Whenever I finish dragging，the dragend function trigger 2 times
```
    group.on('dragend', e => {
      noteData.notesX = group.x()
      noteData.notesY = group.y()
      group.stopDrag()
    })
```

**Comment by shimingw** [comment]
version:3.2.5

**Comment by shimingw** [comment]
version:3.4.1

**Comment by lavrton** [comment]
Can you make a demo? And why do you call `group.stopDrag()` inside `dragend`? dragging is already stopped, why do you need to stop it again?

**Comment by shimingw** [comment]
This has nothing to do with `group.stopDrag()`
No `group.stopDrag()` will trigger 2 times.

**Comment by lavrton** [comment]
Closing the issue as no demo provided.  You should not call `group.stopDrag()` inside `dragend`.
