### ISSUE TITLE
sceneFunc being called an increasing number of times - possible memory leak

### ISSUE THREAD

**Issue by IWMTom** [konvajs/konva#746]
I've been building an application with Konva that utilises compositing to hide areas of a layer - whilst developing, I noticed a significant slow down after numerous calls to a function that would run the compositing using a custom shape and sceneFunc.

I've created a minimal demo - as you move the black box around and drop it, the dragmove event gets fired and the code ran. I put a console.log() inside of the sceneFunc callback and noticed that each time it runs, it runs an increasing number of times, seemingly linearly. I also put a console.log() inside of the callback for toImage() and it only fires once per call.

After dropping the black box 100 times, the sceneFunc will fire 100 times at once - as far as I am aware, it should only run once? I'm not sure if this is the best way to achieve the result but it seemed to be working.

This seems like a memory leak, but I could be wrong and be misunderstanding how sceneFunc works.

Minimal demo is here: https://codepen.io/IWMTom/pen/pozQgXe

If you need more information, let me know.

Console output:
![image](https://user-images.githubusercontent.com/8270461/65261565-791df480-db00-11e9-996f-8447895dba96.png)

**Comment by lavrton** [comment]
`previewLayer.clear();` do not remove elements from the layer. It just clear canvas element.

As I can see you are adding new `imageElement` on every `dragend`. So you have more and more nodes in your stage. So you have move `sceneFunc` calls.

**Comment by IWMTom** [comment]
Aha! That makes sense!

Replaced **previewLayer.clear()** with **previewLayer.destroyChildren()** and all is well - thank you so much!
