### ISSUE TITLE
Transformer glitches when using centeredScaling

### ISSUE THREAD

**Issue by IWMTom** [konvajs/konva#747]
If you grab the top right handle and move the mouse below the shape, the transformer will begin glitching. I've attempted to capture it (http://i.tomwilson.pw/9BbJ8PiK.mp4) but the frame rate of the video is too low to see the glitch very well.

This can be replicated on the demo of centered scaling: https://konvajs.org/docs/select_and_transform/Centered_Scaling.html

The issue does not occur when not using centeredScaling.

**Comment by lavrton** [comment]
Fixed with `konva@5.0.0`
