### ISSUE TITLE
Typescript definitions for minimal bundle

### ISSUE THREAD

**Issue by canastro** [konvajs/konva#749]
While trying to use the minimal bundle with a typescript project the typings are not imported and we get errors such as:

> Could not find a declaration file for module 'react-konva/lib/ReactKonvaCore'. '/Users/.../node_modules/react-konva/lib/ReactKonvaCore.js' implicitly has an 'any' type.

**Comment by wikywin** [comment]
hi lavrton
I upgrade to konva 7.0.0.  I want to use minimal bundle according to readME. i get issue as below:
Could not find a declaration file for module 'konva/lib/Core'. '/Users/wikywin/Documents/ProjectX/vue-learning/webcc/node_modules/konva/lib/Core.js' implicitly has an 'any' type.
  Try `npm install @types/konva` if it exists or add a new declaration (.d.ts) file containing `declare module 'konva/lib/Core';`

**Comment by lavrton** [comment]
For now, I am not sure how to define types for every module file (so it is imported correctly). I will be happy of a typescript ninja can help there with a Pull Request.

**Comment by lavrton** [comment]
The issue will be resolved with the `konva@8` (the next scheduled release).
