### ISSUE TITLE
setCenter / getCenter on Konva.Node

### ISSUE THREAD

**Issue by pronebird** [konvajs/konva#75]
That would be a very useful thing, because there are plenty of situations when you use center, so to avoid all this `x - width * 0.5` etc.. we could introduce a helper method. Currently this also can be achieved with offset but not always desired.

This feature would require certain consideration of course because it should behave the same with or without offset.

**Comment by lavrton** [comment]
I am agree that this method might be useful. But I don't wont include it into `Konva` core.
While answering on stackoverflow I found that for some people not so easy to understand difference between `setPosition` and `setOffset` as both of them are changing position of node on canvas. So adding one more similar method will add more misunderstanding.
