### ISSUE TITLE
getPointerPosition problem with scale/transform

### ISSUE THREAD

**Issue by rebinnaf** [konvajs/konva#751]
I used vue-zoomer alongside konvajs, getPointerPosition returns wrong value after scaleup. This causes another problem with dragging objects.

**Comment by lavrton** [comment]
Can you make a demo? `stage.getPointerPosition()` returns the absolute position of a point on the canvas. Without any transforms from the stage or any other node.

For relative position take a look here: https://konvajs.org/docs/sandbox/Relative_Pointer_Position.html

**Comment by rebinnaf** [comment]
I added vue-zoomer to one of your sandboxes, I want to zoom then edit the shape but I can't. I will be grateful if you give me a proper solution.

https://codesandbox.io/s/vue-konva-transform-and-drag-events-demo-pbopq?fontsize=14

**Comment by rebinnaf** [comment]
I also saw your relative zoom demo at https://konvajs.org/docs/sandbox/Zooming_Relative_To_Pointer.html

But in my case, I need to use a better video player than Konvas's. So, I have to use it with other video player and zoom components.

**Comment by lavrton** [comment]
I don't see any issues, with the last demo you posted. Can you be more specific what exactly is not working for you as expected?

**Comment by rebinnaf** [comment]
Sorry, I just hadn't saved my demo. Would you please take another look at it now? I want to zoom the shape and then transform it.

**Comment by lavrton** [comment]
I see. It will not work in that way. At the current moment, `Konva` doesn't support hit detection for containers transformed/zoomed with CSS.

As a workaround you need to remove `v-zoomer` and implement zooming with the Konva. Like this: https://konvajs.org/docs/sandbox/Zooming_Relative_To_Pointer.html (just update to for the `vue`).
