### ISSUE TITLE
when size change, the function getClientRect go bad

### ISSUE THREAD

**Issue by cenmes** [konvajs/konva#752]
let group = new Konva.Group();
let text = new Konva.Text({
text: 'this is a text',
fill: '#333333',
fontSize: 12
})
group.add(text);
let size1 = getClientRect({ skipTransform: true, skipStroke: true });
text.setAttr('fontSize', 50);
let size2 = getClientRect({ skipTransform: true, skipStroke: true });

// but when I set it to old, the value is the not correct
text.setAttr('fontSize', 12);
let size3 = getClientRect({ skipTransform: true, skipStroke: true });

 the width and height in size1, size3 is not equal， hot to get it ?

**Comment by lavrton** [comment]
Works ok for me. Can you make a demo of your issues?

I tried this: https://jsbin.com/lidiwuzuji/1/edit?js,console,output

**Comment by cenmes** [comment]
Thanks, I have got it. when set background of a group, should hide  the background first.
