### ISSUE TITLE
`node.getAbsolutePosition()` not working with cached parent

### ISSUE THREAD

**Issue by lavrton** [konvajs/konva#753]
While caching, the node is not clearing the absolute positions of all its children. I did it for performance reasons.

But now if we try to get the absolute position of a child, we may have a not correct result.

Should we check cached parents when we are calculating the absolute position?

**Comment by thatodieguyspj** [comment]
After your help, this was my final work around to the bug:
```
    if (this.target.parent.isCached()) {
      this.target._clearCache('absoluteTransform');
      this.target.parent.cache();
    }

    const nodePos = this.target.getAbsolutePosition();
```

**Comment by lavrton** [comment]
I will publish a new version with the fix later.
