### ISSUE TITLE
Nodejs and electronjs with Konva

### ISSUE THREAD

**Issue by meftunca** [konvajs/konva#757]
I apologize for my English. The question I want to ask is this. I want to get high performance from canvas with Electronjs. I have reviewed the node-canvas library and tried to adapt it to your project. But there were many problems. About (createCanvas ()) as an example.

I'd be very happy if you could help me with that. :)

**Comment by lavrton** [comment]
What is your issue? How do you want to use `canvas`? If you are using electron and need to display canvas in the app, you don't need to use `node-canvas`.

**Comment by meftunca** [comment]
My problem stems from the management of large files. As an example (250cm X 250cm) I'm working with files. For this I need high performance in image processing. I have to minimize the recompilation times in the project. I want to use node-canvas as the native module. You shared a sample project (konva-node), but now it's showing errors

**Comment by lavrton** [comment]
What error?

For really fast performance you probably don't need `Konva` at all. Just generate images manually with direct context access.
