### ISSUE TITLE
The problem of Shape Redraw

### ISSUE THREAD

**Issue by aolsx** [konvajs/konva#758]
this.Group = ...
this.Rect = ...

this.Group.add(this.Rect);
this.Group.draw();
// OK 

this.Rect.destroy();
this.Group.draw();
// No Redraw

**Comment by lavrton** [comment]
@aolsx do not use `draw()` methods on groups or shapes. Only on stage or a layer.

**Comment by lavrton** [comment]
https://konvajs.org/docs/performance/Shape_Redraw.html

**Comment by aolsx** [comment]
Thanks
