### ISSUE TITLE
Composite operations cause wrong intersections

### ISSUE THREAD

**Issue by nilsmehlhorn** [konvajs/konva#759]
When applying composite operations to images, `Layer#getIntersection` won't return the top most image but rather - as it seems - the one with the higher alpha value (or maybe rather the darker pixel?).

Here's a reproduction: https://stackblitz.com/edit/konva-composite-hit

The monkey gets the higher zIndex (also visually apparent), yet clicking on different parts of the monkey that are overlaying the lion logs an intersection with the lion instead. Just click around on the monkeys face a bit while the console is open.

I also saw this behaviour for texts. I couldn't reproduce it for simple rectangles yet. I presume texts are actually rendered as images/bitmaps into the canvas, so it's maybe limited to bitmaps and their hit caching.

**Comment by lavrton** [comment]
Thanks for the report. I will publish the release later.
