### ISSUE TITLE
mousewheel event tutorials

### ISSUE THREAD

**Issue by Pmleader** [konvajs/konva#76]
Is it possible to get some tutorials or guidelines on using the mousewheel event?
Currently i'm just using trial and error to find out how it works.
It might be nice to have some solid documenting on the event(or the events in general)

**Comment by lavrton** [comment]
Right. We make soon. Just fast demo:
```javascript
pentagon.on('mousewheel', function(e) {
  var delta = e.evt.deltaY || e.evt.wheelDelta;
  if (delta > 0) {
    pentagon.scaleX(pentagon.scaleX()*1.1);
  } else {
    pentagon.scaleX(pentagon.scaleX()/1.1);
  }
  layer.draw();
})
```
http://jsbin.com/zegomamibu/2/edit?js,output

**Comment by Pmleader** [comment]
A perfect!

I'll try and find some time to set up some tutorials/guidelines pages soon.
I've learned a whole lot just from trial and error working with Konva(and Kinetic).
Time to return something to the project!

**Comment by iandanforth** [comment]
Note for google searchers - this event is now "wheel" NOT "mousewheel"
