### ISSUE TITLE
[Bug] Cannot edit text if drawBorder is enabled

### ISSUE THREAD

**Issue by frozar** [konvajs/konva#760]
Hello there, I'm discovering Konva and the API is really great, thank you.

While I'm experimenting in a mixture of [these](https://konvajs.org/docs/shapes/Text.html) [tutorials](https://konvajs.org/docs/sandbox/Editable_Text.html), I found out that if you enable the `drawBorder` field of a text, you cannot see the render of this text of you edit its content.

To be clearer, here an illustration:
![Peek_2019-10-11 12-45](https://user-images.githubusercontent.com/1025244/66646339-31354d80-ec26-11e9-8d29-5cddca287df8.gif)

You can find the source code of this example here:
https://codepen.io/frozar/pen/QWWjzVz

Is it possible to allow the redraw of a text even if its `drawBorder` cache property is enable? (please ^^)

**Comment by lavrton** [comment]
You need to recache a node if you change any properties.

```
simpleText.text(textarea.value);
// recache
simpleText.cache();
layer.draw();
```

**Comment by frozar** [comment]
Nice, thank you for the quick answer :)
