### ISSUE TITLE
Temperature filter on image with RGB  or Kelvin

### ISSUE THREAD

**Issue by Arrow891** [konvajs/konva#761]
I'd like to apply a temperature filter on an image, there are 2 approaches to achieve this goal:
1- konva js filter (which is not available :)) )
2- handle with RGB filters

I've written a javascript function which receives a number between 1000 to 40000 (kelvin base) as a parameter and returns an array of R,G,B.

But the problem with Konva is that it doesn't change the R, G or B intensity of the image, based on the received values from my algorithm; instead, it applies it to the R, G and B filters that doesn't make the outcome to look like a whiteballancing function, based on temperature. 

As you can see below:

Correct (Generated by Photo Demon  application):
![fluoi-correct](https://user-images.githubusercontent.com/23627951/66721800-ffcda500-ee12-11e9-8099-e403d5804191.jpg)

 Konva RGB:
![incorrect](https://user-images.githubusercontent.com/23627951/66721803-107e1b00-ee13-11e9-8180-4c3e71b84edd.png)

**Comment by lavrton** [comment]
I think for your use case you can just write your own custom filter function. Did you try it?
https://konvajs.org/docs/filters/Custom_Filter.htm

**Comment by Arrow891** [comment]
@lavrton I had a glance on what it does, but it was too complicated, so I didn't dig up much into it, I'll try again, but what I tried 2 approaches and failed.

1. Tried to combine the imageData generated by another library such as Camanjs, and then push the image data into the konvajs canvas image, but I failed

2. Another approach was to get the canvas DOM object and change the rgb and put the new imageData into the canvas, but as soon as I called any function of konvajs, it would append a smaller image to the manipulated canvas like a layer but smaller so I've failed again.

 I really have to fix this issue cause I'm running out of time, I'd be appreciated if anyone can help me more about it.

**Comment by lavrton** [comment]
You can use it just fine with CamanJS. Take a look into this demo: https://jsbin.com/nurutucego/1/edit?html,js,output

**Comment by Arrow891** [comment]
@lavrton  first of all, I would need to thank you for the given link. Otherwise, I experienced two issues; one was the malfunctioning of my former Konva filters after employing the Caman ones, and the other one was the same outcome of colour filters being applied over the image, instead of balancing the colour levels, based on Histogram.

**Comment by lavrton** [comment]
Can you give more info about each issue? I don't understand what kind of help you need here.

**Comment by Arrow891** [comment]
@lavrton 
Sure, there are two issues:

1. The Konva filters are no longer functioning when Caman filters are applied to the canvas. How could I make this combination possible?

2. How would I be able to implement whitebalancing using KonvaJS based on temperature?

An example could be like this with PhotoDemon:
http://www.tannerhelland.com/tag/white-balance/

Or like the LunaPic:
https://www6.lunapic.com/editor/?action=temperature

The problem with Konva RGB section is that it applies Red, Green or Blue filters to the image that makes it hard to implement such a thing; however when using the image histogram to do the whitebalancing, the R, G and B gains are the parameters that are strengthened through the entire image to balance the colour temperature.

**Comment by lavrton** [comment]
> The Konva filters are no longer functioning when Caman filters are applied to the canvas. How could I make this combination possible?

What did you try? How did you combine them? Demo?

> How would I be able to implement whitebalancing using KonvaJS based on temperature?

You can find some implementations online that manipulate `imageData` of the canvas and do the same with `Konva` filter. Personally I don't have time to make such implementation by myself.
