### ISSUE TITLE
Lines are sharp and pixallated

### ISSUE THREAD

**Issue by Ravenglass** [konvajs/konva#762]
Lines drawn via the Line class are noticeably sharper and more "pixallated" compared to strokes drawn via the canvas context. On the attached image, the lines marked "a" are drawn using the Line class and the ones marked "b" are drawn using context.stroke(). Am I missing something or is this how it is set to be?

![a](https://user-images.githubusercontent.com/30006523/66805140-ae6e0480-ef3d-11e9-804f-02c5e6d9cc5b.png)

**Comment by lavrton** [comment]
Line class is using `context.stroke()`, so the result should look similar.

Do you use scale or cache? Can you make a demo?

**Comment by Ravenglass** [comment]
Hi, my apologies. Turns out I made a mistake while trying to test it out. I had the code to create my line inside a loop. So basically, the one marked "a" is a few dozen lines drawn over and over again in the same position. And the one marked "b" is just one single line drawn via context. Once again, my apologies for the waste of time.
