### ISSUE TITLE
Exception thrown when doing custom drags

### ISSUE THREAD

**Issue by IgalOgonov** [konvajs/konva#764]
So, I want to create my own custom drag functionality.  
I give a layer the following property:  

            this.layers.test_Layer.instance.draggable(true);
            var context = this;
            
            ...
            
            this.layers.test_Layer.instance.dragBoundFunc(function(pos){
                context.customResize(
                    context.startingWidth+pos.x*context.xCanvasRatio,
                    context.startingHeight-pos.y*context.yCanvasRatio
                );
            });

I could also leave this function empty.  
Everything works fine, but while dragging, this constantly pops:
![This fucking exception](https://i.imgur.com/M7dLO85.png)  

No, I am not going to return anything because that'd fuck up my own function.  
Whatever internal function that handles dragBoundFunc (or uses it) should be prepared for the possibility that nothing was returned, and just terminate on that case.

**Comment by lavrton** [comment]
We can add some kind of warning in case of undefined value. But that function MUST return a new absolute position. Otherwise, why do we need it at all?

**Comment by IgalOgonov** [comment]
As of now, I have found this function to be the only way to prevent the default onDrag behavior when a node is draggable. 
Let me illustrate the problem:  

I want to resize a node something by dragging it. So, I make it draggable (don't mention Transformer please, it's very broken).  

Now, the first instinct would be to use dragmove, but unless I specify dragBoundFunc, the whole layer will just move when dragged, which is an invalid behavior.  

If I do specify dragBoundFunc, dragmove will be overriden (which is ok, I can use the relative position I got from dragBoundFunc just fine).  

The only remaining problem is this unending exception being thrown,

Of course there might be other ways to resolve this, but none of them are clear from the documentations. And this, being the most intuitive way, should at least be considered default when dealing with this problem.

**Comment by lavrton** [comment]
So first, you can just return something from `dragBoundFunc`. New absolute position or just the old one. I don't see why you can't return a value from `dragBoundFunc`.

From my point of view, if you want to resize something, it is better to use events directly (such as `mousedown`, `mousemove` and `mouseup`) or make another node draggable (it may be invisible shape) and then just update the size of original node from the position of "dragger".

**Comment by IgalOgonov** [comment]
Sure, I can return a value from dragBoundFunc. However, that same resize function has other ways of being triggered.   Doing all the calculations anew and just returning a value would create 2 similar complex segments of code to maintain, which is horrible design.  
Making that function just calculate new (x,y) and return them would also be very bad design, as it is responsible for many other things such as re-rendering just the nodes that changed, may throw alerts, etc.     

The direct mouse events are always an option, and the best one you suggested, but a huge reason for drag&drop (and Im talking about the WebAPI) is to save time compared to that. It makes zero sense to suggest doing something the old way rather than the new way which was created to solve many of that old way problems. And trust me, I still remember designing buttons and draggable elements in Java Applets, and how horrible that was. You are basically suggesting to regress from the advanced drag&drop to that.  

As for the last way, this will solve the issue, but this sounds more like a dirty workaround I'd have to do in some game engine due to its limitations. It would definitely make the code much less logical, thus much less maintainable, not to mention the other problems that need to be solved too (in my program the whole shape is resizeable. If the invisible shape has the default dragging behavour, I need to resize and rerurn it to cover the whole visible shape, and only it, after each drag)

**Comment by lavrton** [comment]
> if nothing is returned, as it is only logical that if you return nothing, you don't want to change the position.

I am not sure that it is the best default behavior. The developer should explicitly set the best behavior.

I added a warning in case of the missing return value.
