### ISSUE TITLE
Stage scale and group node drag issue

### ISSUE THREAD

**Issue by neetin** [konvajs/konva#765]
I am trying to add zoom in/out in canvas. I used stage scale. Zoom in/out works perfectly fine.
I have many grouped layers in canvas. And  all nodes (rect) are connected with lines.
Nodes are draggable. Once dragged, its origins (x, y) are saved to redux. I had to maintain state so I took `node.getAbsolutePosition()` and got absolute coordinates and saved it.

Without zoom it works as expected but after zoom `getAbsolutePosition()` gives wrong coordinate. 

I did not find any documentation for this kind of issue or I missed something.

**Comment by lavrton** [comment]
I don't think you want to save the absolute position at the store. I think you need to save the only relative position of nodes.

**Comment by YouWillBe** [comment]
I have the same questions.
![2019-10-21 16-39-32 的屏幕截图](https://user-images.githubusercontent.com/16474244/67189800-770dc500-f421-11e9-9af7-22710f7186cb.png)
If I zoom or drag the stage, then drag a node, the line between nodes will goes to a wrong place,like this:
![2019-10-21 16-43-42 的屏幕截图](https://user-images.githubusercontent.com/16474244/67190115-f7342a80-f421-11e9-9e5c-0d32a3142b7d.png)
emmm... please help me.

**Comment by neetin** [comment]
@lavrton using relative position of node has the same issue.
I have very similar kind of connected nodes as posted by @YouWillBe

**Comment by lavrton** [comment]
I need a demo. I don't know how you are connecting shapes.

But I am 100% sure you don't want to use an absolute position in the store. Because when you change the zoom, absolute position of ALL nodes will be changed. And probably you should not save these changes in the store.

**Comment by neetin** [comment]
@lavrton I finally solved it using relative position and proper `ref`.

I was using ref for a `<Rect>` and handling drag event from `<Group>`.
Now, I have used `ref` for `<Group>` and used drag event ( onDragMove & onDragEnd ) from the group itself. 

The problem is now solved.

Here is the sample code snippet:

```
     handleDragEnd = e => {
       console.log("darg e:", e)
       const position = this.rectRef.getPosition();
   // use this position as your business logic
    }
```

```
  <Group
                onDragEnd={this.handleDragEnd}
                onDragMove={this.handleDragMove}
               ref={node => {
                    this.rectRef = node; // this is a data structure to keep node data, it can be anything.
                }}
...
```
@YouWillBe Try above.
Please post a demo if there is still a bug in your code.
