### ISSUE TITLE
Transformer collapses while resizing to a specific point

### ISSUE THREAD

**Issue by hk-skit** [konvajs/konva#766]
![issue gif](https://i.ibb.co/5rzRFnS/Kapture-2019-10-18-at-16-36-47.gif)

As you can see in the image above when the shape is resized to its min-height, the transformer collapses.

**Console log** 

```
index.js:27 Konva warning: -Infinity is a not valid value for "scaleY" attribute. The value should be a number.
index.js:27 Konva warning: NaN is a not valid value for "x" attribute. The value should be a number.
index.js:27 Konva warning: NaN is a not valid value for "y" attribute. The value should be a number.
index.js:27 Konva warning: NaN is a not valid value for "x" attribute. The value should be a number. 
    in Stage (created by Anonymous)
    in Anonymous (at src/​index.js:88)
    in App (at src/​index.js:122)
index.js:27 Konva warning: NaN is a not valid value for "y" attribute. The value should be a number. 
    in Stage (created by Anonymous)
    in Anonymous (at src/​index.js:88)
    in App (at src/​index.js:122)
index.js:27 Konva warning: NaN is a not valid value for "height" attribute. The value should be a number. 
    in Stage (created by Anonymous)
    in Anonymous (at src/​index.js:88)
    in App (at src/​index.js:122)
```

Is there something I am missing or it's a bug?

I am using `Chrome Version 77.0.3865.120 (Official Build) (64-bit)`

Playground to reproduce the bug: https://codesandbox.io/s/react-konva-transformer-s3ixi

**Comment by lavrton** [comment]
I see the issue. It is in this line: `width: node.width() * scaleX`

In some cases the width (or height) of the node will be equal to 0. And that will break internal calculations of `Konva.Transformer` because it expects that a shape has some size.

As a workaround I suggest to just set the minimal size of the shape:
```
Math.max(5, node.width() * scaleX)
```

**Comment by lavrton** [comment]
Currently, I am not sure how to resolve such cases from `Konva.Transformer` side.

**Comment by hk-skit** [comment]
Ah, that's why the attributes are having `NaN`. 

Having a fixed minimal size resolves the issue, but transformations are restricted. Setting a minimal size value only when the size is 0 solves both issues 😇.

```
width: (node.width() * scaleX) || 1,
height: (node.height() * scaleY) || 1
```
