### ISSUE TITLE
Use with Paint API

### ISSUE THREAD

**Issue by jcubic** [konvajs/konva#768]
With paint API you can use same code as with Canvas but you already have context.

Here is demo of using Paint Worklet. https://codepen.io/jcubic/pen/KBQxjO

What do you think of adding support for context object in Stage constructor?

**Comment by lavrton** [comment]
Is that CSS api? I am not sure how it is related to `Konva` and canvas.

**Comment by jcubic** [comment]
This is API that is the same as Canvas but used with CSS, you can use the same functions as with canvas. But you don't have canvas element.

It would be nice if you can use Canvas libraries with Paint API.

**Comment by lavrton** [comment]
I don't see any benefits and use cases for that integration.
