### ISSUE TITLE
Transformer appears to have an incorrect scale when 'strokeScaleEnabled = false'

### ISSUE THREAD

**Issue by kwhitaker** [konvajs/konva#769]
I am using a `Transformer` to scale a `Rect`, but the scale/dimensions of the transformer are wrong; the right and bottom sides are offset incorrectly.  My `<Stage />` component is scaled based on another element in the page, and this works fine for the `Rect` component, but not for the `Transfomer`.  Here is an example of the transformer:

![image](https://user-images.githubusercontent.com/108933/62947801-c3e17980-bda8-11e9-8586-23acb54c1723.png)

I've tried forcing the transformer scale to be the same as the stage, but that results in a wildly incorrect `Transformer` size.

Is there some parameter I should be passing to keep things in sync?

Thanks

**Comment by bincute** [comment]
Thanks for the frame firstly. Hope there are more diversified demos in docs. It's really hard to find the 
props needed.

**Comment by lavrton** [comment]
I don't see how to handle such an issue automatically better. `ignoreStroke` is doing good work. So I am going to close the issue for now.

**Comment by rainbowMorelhahahah** [comment]
> Hmmm. Interesting issue. You can use `ignoreStroke` for the `Transformer`:嗯，有趣的问题。您可以使用 `ignoreStroke` `Transformer` ：
> 
> ```
>            <Transformer
>               rotateEnabled={false}
>               keepRatio={false}
>               ref={trRef}
>               ignoreStroke
>             />
> ```
> 
> https://codesandbox.io/s/react-konva-stroke-issue-resolve-hjs9t
In your case, you have added ignoreStroke without the effect of Equal scale.
