### ISSUE TITLE
find by Id on multiple stages

### ISSUE THREAD

**Issue by ddcovery** [konvajs/konva#77]
I have a page with 20 stages representign independent items each one with a picture, shapes,...  Because I don't want to mantain internally objects pointing to specific nodes, I use identifiers (Example:  y use "picture" to refere to the main image of each stage)

My problem is I supossed each stage defines it's own identifiers space, but it's not true:  identifiers are global to all stages nodes... this makes impossible to develop each stage as an issolated object (i.e., an Angularjs directive using identifiers to refer some nodes) and identifiers becomes then useless.

¿Is this the expected behabiour or a bug?

**Comment by lavrton** [comment]
Hello. It is expected behavior. Ids are global.

**Comment by ddcovery** [comment]
Ok, then... how can I Load N stages form N independent jsons and access the "mainText" node of each stage? 

Examples like http://konvajs.github.io/docs/data_&_serialization/Complex_Load.html are completly wrong when I have 2 or more stages in the same page.

**Comment by lavrton** [comment]
What is "mainText"? Id?

Why example is wrong for multiple stages? Can you give an example?

**Comment by ddcovery** [comment]
Hi @lavrton 

"mainText" refers to an hypothetical case of N stages with same node structure were we need to access one concrete node by it's identifier in all stages (the "mainText" node).

In your example, "blueRectangle" and "yodaImage" are the nodes.  See this example "variation"
```
<div id="container_0"></div>
<div id="container_1"></div>
<div id="container_2"></div>
<script>
    // Imagine whe have 2 or more JSON "designs" loaded from external files
    // and we want to edit them at the same time:  all designs follow the same 
    // node structure changing only "data"... The editor needs to instantiate 
    // some nodes using their identifiers. 
    var externalJSON = '{"attrs":{"width":578,"height":200},"className":"Stage","children":[{"attrs":{},"className":"Layer","children":[{"attrs":{"width":"auto","height":"auto","text":"Text Shadow!","fontFamily":"Calibri","fontSize":95,"x":20,"y":20,"stroke":"red","strokeWidth":2,"shadowColor":"black","shadowBlur":2,"shadowOffsetX":10,"shadowOffsetY":10,"shadowOpacity":0.5},"className":"Text"},{"attrs":{"stroke":"green","strokeWidth":10,"lineJoin":"round","lineCap":"round","points":[{"x":50,"y":140},{"x":450,"y":160}],"shadowColor":"black","shadowBlur":10,"shadowOffsetX":5,"shadowOffsetY":5,"shadowOpacity":0.5},"className":"Line"},{"attrs":{"x":280,"y":100,"width":100,"height":50,"fill":"#00D2FF","stroke":"black","strokeWidth":4,"shadowColor":"black","shadowBlur":10,"shadowOffsetX":5,"shadowOffsetY":5,"shadowOpacity":0.5,"rotation":0.3490658503988659,"id":"blueRectangle"},"className":"Rect"},{"attrs":{"x":100,"y":41,"width":106,"height":118,"id":"yodaImage"},"className":"Image"}]}]}';
    var designs = [externalJSON, externalJSON, externalJSON];


    var stages = [];
    for(var ind=0; ind<designs.length;ind++){
        stages.push( Konva.Node.create(designs[ind], 'container_'+ind) );

        stages[ind].get('#blueRectangle').on('mouseover mouseout', function() {
            var stroke = this.stroke();
            this.stroke(stroke === 'black' ? 'red' : 'black');
            stage.draw();
        });
    }
    /*
     * set images
     */
    var imageObj = new Image();
    imageObj.onload = function() {
        for(var ind=0;ind<stages.length;ind++){
            stages[ind].get('#yodaImage')[0].image(imageObj);
            stages[ind].draw();
    };
    imageObj.src = 'http://konvajs.github.io/assets/yoda.jpg';

</script>
```

**Comment by lavrton** [comment]
Ok. Id is unique globally. So this will not work `stages[ind].get('#blueRectangle')`.
In this case I recommend to use `name` instead of `id` attribute.

**Comment by ddcovery** [comment]
Thanks @lavrton... this is the solution.
