### ISSUE TITLE
Does webgl support？

### ISSUE THREAD

**Issue by aolsx** [konvajs/konva#770]
If not, is there a solution?

**Comment by aolsx** [comment]
Konva is great, don't want to give up!

**Comment by lavrton** [comment]
Solution for what?

`Konva` is not going to have WebGL support. It may use WebGL later for filters, but the main architecture will be still 2d canvas API.

I want to make 2d WebGL library, but it will a different solution: https://twitter.com/lavrton/status/1170133352118140929

**Comment by aolsx** [comment]
Thank you. After watching your twitter, I can only support you mentally. Look forward to it!
