### ISSUE TITLE
How to make loading animation?

### ISSUE THREAD

**Issue by aolsx** [konvajs/konva#771]
Use Konva.Tween or Konva. Animation？
With percentage variable，I didn't find a demo.

**Comment by lavrton** [comment]
What do you want to animate? What are you waiting for loading?

Or you can `Konva.Tween` or `Konva.Animation`.

`Tween` is better for "one-time" animations. `Konva.Animation` is better for infinite-like animations.

**Comment by aolsx** [comment]
Thanks, buddy。
