### ISSUE TITLE
Text width on .toJSON() not included when single emoji used

### ISSUE THREAD

**Issue by HightonRidley** [konvajs/konva#772]
Here's a JSON string created for a text item created with a width of 100 and a single emoji:
{\"attrs\":{\"width\":1553,\"height\":478},\"className\":\"Stage\",\"children\":[{\"attrs\":{},\"className\":\"Layer\",\"children\":[]},{\"attrs\":{},\"className\":\"Layer\",\"children\":[{\"attrs\":{\"x\":696,\"y\":160,\"text\":\"🤓\",\"fontSize\":100,\"fontFamily\":\"Roboto\",\"fill\":\"#444444\",\"align\":\"center\",\"draggable\":true,\"name\":\"productImage\",\"id\":\"id1\"},\"className\":\"Text\"}]},{\"attrs\":{},\"className\":\"Layer\",\"children\":[]}]}
As you can see, there's no width attribute.
When there's two emojis, the width IS included:
{\"attrs\":{\"width\":1553,\"height\":478},\"className\":\"Stage\",\"children\":[{\"attrs\":{},\"className\":\"Layer\",\"children\":[]},{\"attrs\":{},\"className\":\"Layer\",\"children\":[{\"attrs\":{\"x\":696,\"y\":160,\"text\":\"🤓🦄\",\"fontSize\":100,\"fontFamily\":\"Roboto\",\"fill\":\"#444444\",\"width\":300,\"align\":\"center\",\"draggable\":true,\"name\":\"productImage\",\"id\":\"id1\"},\"className\":\"Text\"}]},{\"attrs\":{},\"className\":\"Layer\",\"children\":[]}]}

**Comment by lavrton** [comment]
The `Konva` is removing attributes that equal to default values. One emoji with `fontSize = 100` will give width = 100 by default. So it is not necessary to save it into the JSON.

**Comment by HightonRidley** [comment]
Thank you, lavrton. Much appreciated :)
(and thank you and your pixies for the Konva library!)
