### ISSUE TITLE
Setting Konva.Image width/height to zero results natural width/height of image source

### ISSUE THREAD

**Issue by naqtn** [konvajs/konva#774]
From shapes/Image.ts

```
  getWidth() {
    var image = this.image();
    return this.attrs.width || (image ? image.width : 0);
  }
```
(same in `height` case)

I guess this is for the case when `this.attrs.width` is `undefined`. But it also returns `image.width` when `width` is explicitly set to zero.

It was unexpected behavior for me. Is this a specification or a defect?

**Comment by lavrton** [comment]
I think it is a bug. Do you want to make a pull request?
