### ISSUE TITLE
invalid mouse point coordinate on Stage zoom

### ISSUE THREAD

**Issue by neetin** [konvajs/konva#776]
`stage.getPointerPosition()` gives wrong mouse pointer coordinate while stage is on zoom.

sample code: https://jsfiddle.net/zxsuw9eq/

**Comment by lavrton** [comment]
`stage.getPointerPosition()` returns absolute position of the pointer relative to `top-left` edge of stage container. It doesn't include any transforms of your nodes.

**Comment by lavrton** [comment]
Take a look here to make a better implementation: https://konvajs.org/docs/sandbox/Relative_Pointer_Position.html
