### ISSUE TITLE
node.destroy And node.clearCache

### ISSUE THREAD

**Issue by aolsx** [konvajs/konva#777]
node.cache();
......
// destroy 
node.clearCache(); //  Is it necessary?
node.destroy();

-----------------------------------------
//  Before or after cache ?

node.cache();  // before
layer.add(node);

// or

layer.add(node);
node.cache(); // after

**Comment by lavrton** [comment]
```
// destroy
node.clearCache(); // Is it necessary?
node.destroy();
```

No. The memory will be cleaned. Just do `node.destory()`;

```
// Before or after cache ?

node.cache(); // before
layer.add(node);

// or

layer.add(node);
node.cache(); // after
```

It almost doesn't really matter.  Both cases should work just fine.  But I prefer the second (caching after add).

**Comment by aolsx** [comment]
@lavrton 非常感谢！

**Comment by lavrton** [comment]
拜托
