### ISSUE TITLE
How to pan and zoom stage at the same time?

### ISSUE THREAD

**Issue by rlrh** [konvajs/konva#778]
Hello,
I want to make a stage pan and zoom with touches at the same time (like photo gallery apps in modern smartphones/PCs), but am having a hard time figuring out how to do so. 
I've made a demo here: [https://codesandbox.io/s/react-konva-test-4-lo1dy]( https://codesandbox.io/s/react-konva-test-4-lo1dy)
You can use 2 fingers to zoom in and out, and the zoom will be relative to the center of the 2 touches.
However, if I set the "draggable" property on the stage to true, then I can pan and zoom at the same time, but the zoom will become relative to the top left position instead of the touch position.
I have tried not using the built-in drag functionality but can't figure out the math.
How can I can achieve this behaviour?
Thank you very much.

**Comment by rlrh** [comment]
Thanks, I managed to solve it by recording the last pointer position, similar to lastDist in the examples, and then offsetting the stage position by the difference between the current pointer position and last pointer position.

For anyone interested:
```
let lastDist = 0;
let lastPointerPosition = undefined;

// in handleTouchMove
const currX = (touch1.clientX + touch2.clientX) / 2;
const currY = (touch1.clientY + touch2.clientY) / 2;
const pointer = {
    x: currX - stage.getContent().offsetLeft,
    y: currY - stage.getContent().offsetTop
};
const prevX = lastPointerPosition.x;
const prevY = lastPointerPosition.y;
const deltaX = currX - prevX;
const deltaY = currY - prevY;
const oldScale = stage.scaleX();
const startPos = {
          x: (pointer.x - stage.x()) / oldScale,
          y: (pointer.y - stage.y()) / oldScale
};
const newScale = (oldScale * dist) / lastDist);
const newPosition = {
          x: ((pointer.x + deltaX) / newScale - startPos.x) * newScale,
          y: ((pointer.y + deltaY) / newScale - startPos.y) * newScale
        };
lastDist = dist;
lastPointerPosition = { x: currX, y: currY };
```

**Comment by RobbertWolfs** [comment]
@rlrh  do you have a full working example?

**Comment by rlrh** [comment]
> @rlrh do you have a full working example?

I have a rather verbose example [here](https://codesandbox.io/s/canvas-toolbar-5tlds) - the functionality for panning and zooming with two fingers is in the `handleTouchMove` function in `Canvas.tsx`.

**Comment by RobbertWolfs** [comment]
@rlrh  Thanks going to check it out! Because at the moment I think it works.. But when I set `draggable` to true it does some stuff wrong..

**Comment by rlrh** [comment]
> @rlrh Thanks going to check it out! Because at the moment I think it works.. But when I set `draggable` to true it does some stuff wrong..

@RobbertWolfs I had this problem as well, to solve it I set `draggable` to false whenever there are 2 touches.

**Comment by RobbertWolfs** [comment]
@rlrh yeah that was something I also was thinking
