### ISSUE TITLE
Regression in version 3.0.0 with the "setAbsolutePosition" function

### ISSUE THREAD

**Issue by Zamiell** [konvajs/konva#779]
Hello lavrton and thank you for the excellent library!!!

I have found a regression when attempting to upgrade the version of Konva that I use with my website. I've narrowed down that version 2.6.0 works (produces no errors) and version 3.0.0 fails (produces the error below), so it must be this version that introduced the regression. (The latest version, 4.0.16, fails with the same error.)

When booting up my app/website, I get a stack trace as follows:

```
Uncaught TypeError: this.rotation is not a function
    at o.t._getTransform (Node.js:866)
    at o.t._getCache (Node.js:114)
    at o.t.getTransform (Node.js:863)
    at Node.js:828
    at l.t._eachAncestorReverse (Node.js:609)
    at l.t._getAbsoluteTransform (Node.js:825)
    at l.t._getCache (Node.js:114)
    at l.t.getAbsoluteTransform (Node.js:820)
    at l.t.setAbsolutePosition (Node.js:541)
    at o.add (PlayStack.js:13)
```

"Node.js" is the Konva file and "PlayStack.js" is my file. It contains a class:

```
class PlayStack extends graphics.Group {
```

And line 13 is just calling the "setAbsolutePosition" function on a child in the group:

```
    add(child) {
        const pos = child.getAbsolutePosition();
        graphics.Group.prototype.add.call(this, child);
        child.setAbsolutePosition(pos);
        this.doLayout();
    }
```

I'll see about making a reproducible example later if I can, but for now, is this enough information to narrow down the bug?

**Comment by lavrton** [comment]
I need a demo. `this.rotation()` must be defined in all Konva nodes.

**Comment by Zamiell** [comment]
It's going to take me a while to to create a demo, I have to slowly remove parts from a 10,000 line app piece by piece.

In the meantime, can you tell me if the `_getTextSize()` function changed? I have code like this, and it seems to have broken:

```js
rightLabel.setText(` / ${maxScore}`);
rightLabel.setWidth(rightLabel._getTextSize(rightLabel.getText()).width);
const x = leftLabel.getX() + leftLabel._getTextSize(leftLabel.getText()).width;
rightLabel.setX(x);
```

**Comment by Zamiell** [comment]
And another question, my code uses `_setChildrenIndices()` in a Konva.Group, is that also kosher to do in the latest version?

**Comment by Zamiell** [comment]
Ok, I spent around 4 hours and finally generated a working demo for you.

https://github.com/Zamiell/konva-regression

Just clone this repository and read the README.md.

**Comment by lavrton** [comment]
Be very careful when you extend Konva nodes.

You have this:

```javascript
class CardLayout extends Konva.Group {
    constructor(config) {
        config.listening = config.player !== -1; // Discard piles do not need to be listening
        super(config);

        // Class variables
        this.align = config.align || 'left';
        this.reverse = config.reverse || false;
        this.rotation = config.rotation;
        this.empathy = false;
```

The issue is in the line `this.rotation = config.rotation;`.  All Konva nodes have `node.rotation()` method. You are overwriting it with another value. So it breaks internal code.

Probably the old version was using `node.getRotation()`, that why it was working.

**Comment by lavrton** [comment]
> Now I am paranoid about using any undercore method

Yeah. You should avoid using them. They are "private" js methods. And they can change at any version.

**Comment by Zamiell** [comment]
Ok, thank you lavrton. But can you answer though if it is safe to use `_getTextSize()` and `_setChildrenIndices()` in the latest version? I understand that it can change in a future version but I don't want to rewrite the app now, I just want to upgrade to the latest version so that TypeScript works properly.

**Comment by lavrton** [comment]
It is better to replace `node._getTextSize()` with `node.measureSize(text)`. It is a public API now.

`_setChildrenIndices();` is still there.

**Comment by Zamiell** [comment]
Great, thank you very much!!!!
