### ISSUE TITLE
Single Konva.Shape is not fully erased when dragged

### ISSUE THREAD

**Issue by m1erickson** [konvajs/konva#78]
When this Konva.Shape is the only object on the layer then it is not properly erased as it is being dragged.

    spriteRect = new Konva.Shape({
        x: 20,
        y: 30,
        stroke:'black',
        strokeWidth:3,
        draggable:true,
        drawFunc: function(ctx) {
          // clip a sprite from the spritesheet and draw it on spriteRect
          ctx.drawImage(spritesheet, sw*1,0,sw,sh, 0,0,sw,sh);
          // draw a stroked border around the image
          ctx.rect(0,0,sw,sh);
          // tell KonvaJS to draw the image + border on the layer
          ctx.fillStrokeShape(this);
        }
    });
    layer.add(spriteRect);
    layer.draw();   

https://jsfiddle.net/m1erickson/mjqjmqny/

Adding a second Konva.Circle on the layer causes the Konva.Shape to correctly be erased as the .Shape is being dragged

https://jsfiddle.net/m1erickson/rn7yc1xv/

**Comment by lavrton** [comment]
You need to create and then close `context` path while drawing shape. Look at example: http://konvajs.github.io/docs/shapes/Custom.html

Your code should be:
```javascript
ctx.beginPath();
ctx.rect(0,0,sw,sh);
ctx.closePath();
```
https://jsfiddle.net/mjqjmqny/1/

**Comment by m1erickson** [comment]
Ah, yes--my bad! I originally tried strokeRect and then backed down to
.rect and in my haste I forgot .beginPath. Thanks for swatting my bug and
thanks for picking up KineticJS as KonvaJS. :-)
