### ISSUE TITLE
konva Chinese file open error

### ISSUE THREAD

**Issue by 521707** [konvajs/konva#780]
中文文档打不开！
konva chinese file  open error || 404
Konva Chinese document cannot be opened

**Comment by lavrton** [comment]
Hello. We never have official documentation for Chinese docs.
If you are about this repo - https://github.com/madadimy/konva, I don't know how it was maintained.

@madadimy are you interested in supporting the official Chinese version of the docs?

We can have a translated version of the site. But I will need help to support and maintain it.

**Comment by bluehymn** [comment]
@lavrton I had fork konvajs/site to my repository and translated a small part of it; I will continue do the rest in my free time;

website: [https://bluehymn.github.io/cn.konvajs](https://bluehymn.github.io/cn.konvajs)
repository: https://github.com/bluehymn/Konva-site-zh_CN

@521707 有时间的话我们可以一起翻译 😀

**Comment by 521707** [comment]
很棒的， 但愿能够增加更多的demo， 隔壁的fabric.js也挺好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bluehymn"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 下午5:01
收件人:&nbsp;"konvajs/konva"<konva@noreply.github.com&gt;;
抄送:&nbsp;"632 。"<521707@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [konvajs/konva] konva Chinese file open error (#780)




@lavrton I had fork konvajs/site to my repository and translated a small part of it; I will continue do the rest in my free time;
 
website: https://bluehymn.github.io/cn.konvajs
 repository: https://github.com/bluehymn/Konva-site-zh_CN
 
@521707 有时间的话我们可以一起翻译 😀
