### ISSUE TITLE
hitStrokeWidth does not work on shapes that have no stroke declared/visible

### ISSUE THREAD

**Issue by Bart736** [konvajs/konva#782]
Please see the fiddle (red star). 

https://jsfiddle.net/kq6jhpm0/1/

The hitStrokeWidth does not work with the following part commented:

        /*stroke: 'black',
        strokeWidth: 4,*/ 

The hitStrokeWidth should work even when stroke is not declared.

Could I ask to fix that.

**Comment by lavrton** [comment]
Published as `konva@4.0.17`
