### ISSUE TITLE
Use of String.prototype.trimRight breaks in IE.

### ISSUE THREAD

**Issue by dglasser** [konvajs/konva#783]
The file src/shapes/Text.ts contains this line:

`match = match.trimRight();`

This causes a TypeError in IE11:

  TypeError: Object doesn't support property or method 'trimRight'
  at Text.prototype._setTextData (/js/modules/libs/konva.js:13565:27)     
  at Node.prototype._fire (/js/modules/libs/konva.js:4347:19)

**Comment by lavrton** [comment]
Published as `konva@4.0.17`

**Comment by jraack** [comment]
same issue with trimeLeft breaks on IE11

**Comment by lavrton** [comment]
There are some other functions that are not supported by IE11. I am not sure we are going to support it. To make it work you just need to provide some polyfills, such as `Array.prototype.find`, `String.prototype.trimLeft` and `String.prototype.trimRight`.

**Comment by jraack** [comment]
Ok @lavrton i will take a look. Thanks for your reply!
