### ISSUE TITLE
Konva reports click event falsely when releasing drag and drop operation from v. 4.0

### ISSUE THREAD

**Issue by Bart736** [konvajs/konva#784]
Please see the fiddle:

https://jsbin.com/gijijoridu/1/edit?html,js,output

Please start drag move on box and then release on canvas. 

In console there is reported:
startdrag
mouse up
clicked

Where there was no click event. The click event is falsely reported.

In version prior to 4:
https://jsbin.com/weziwapaqe/1/edit?html,js,output

... it worked well:
startdrag 1
mouse up

**Comment by Bart736** [comment]
Please also note that this new erratic behaviour is only on part of the objects (the rest works well as before), but I cannot figure out the pattern. Probably the erratic is only on the last object drawn in a group.

**Comment by Bart736** [comment]
We also noticed that the problem is introduced by: 

box1.stopDrag();

When this is commented out, the normal behaviour is restored. Of course in the particular case we need it in place.

**Comment by lavrton** [comment]
Pushed the fix. It will be released later. You may try a build from `master`.
