### ISSUE TITLE
Text.prototype.setText converts numeric zero to an empty string.

### ISSUE THREAD

**Issue by dglasser** [konvajs/konva#786]
If the value 0 is passed to Text.prototype.setText, this expression converts it to an empty string:

(text || '').toString();

It looks like the same thing would happen with boolean false.

**Comment by lavrton** [comment]
Hmm... What is developer experience better here? I don't think we need to support anything for `text` property but `strings` or `undefined` or `null`.

So I think you have to manually convert a value into string: `node.text(number.toString())`;

**Comment by dglasser** [comment]
As it is now, you're accepting a value of any type without a warning, and silently converting non-strings to strings. In my opinion, if you're going to do that, you should be consistent., If 7 converts to "7", then 0 should convert to "0", rather than "". And if true converts to "true", then false should convert to "false". To me, that is more in keeping with the Principle of Least Astonishment.
