### ISSUE TITLE
Use of Array.prototype.find breaks IE

### ISSUE THREAD

**Issue by dglasser** [konvajs/konva#787]
The Array class in IE11 does not have the find method. That causes this code to throw an exception:

>      Stage.prototype._getPointerById = function (id) {
>           return this._pointerPositions.find(function (p) { return p.id === id; });
>       };

and, although I did not test it, I suspect this line also, which appears in two places:

>                 var pos = stage._changedPointerPositions.find(function (pos) { return pos.id === elem.pointerId; });

**Comment by lavrton** [comment]
There are some other functions that are not supported by IE11. I am not sure we are going to support it. To make it work you just need to provide some polyfills, such as `Array.prototype.find`, `String.prototype.trimLeft` and `String.prototype.trimRight`.

**Comment by dglasser** [comment]
I've already worked around it with a polyfill. If you're not going to fully support IE11, it would be nice to have the needed polyfills and other workarounds documented in one place.

You might also consider a separate "IE11 Support Module" for konva, that contains polyfills needed for IE11. If someone is already polyfilling those methods for general purposes, they wouldn't need to deploy it, and konva.js could be kept lean and clean.

**Comment by lavrton** [comment]
Closing this as not a priority. But I will be happy if someone can provide polyfill examples to place them in README. Any related PR is very welcome.
