### ISSUE TITLE
Multitouch events can break `Konva.Transformer` behavior.

### ISSUE THREAD

**Issue by lavrton** [konvajs/konva#788]
![](https://uploads.disquscdn.com/images/b11423904057bdf4328b634727164f7727e925bb7fb693159ba88777e2decadb.gif)

From here: http://disq.us/p/25hs6pl

**Comment by goodwin74** [comment]
I have found a solution. 
Add the following code (in bold) in konva.js:

`Transformer.prototype._handleMouseDown = function (e) {
            **if(e.pointerId > 0){
                return;
            }**
            this.movingResizer = e.target.name().split(' ')[0];
            // var node = this.getNode();
            var attrs = this._getNodeRect();
            var width = attrs.width;`

`Transformer.prototype._handleMouseMove = function (e) {
            **if(!this.movingResizer) return;
            if(this.movingResizer === '') return;**

            var x, y, newHypotenuse;
            var resizerNode = this.findOne('.' + this.movingResizer);
            var stage = resizerNode.getStage();`

And change the _Transformer.prototype._handleMouseUp_ function code completely
`Transformer.prototype._handleMouseUp = function (e) {
            for(var item in e.changedTouches){
                if(item !== 'length'){
                    if(e.changedTouches[item].identifier === 0){
                        this.movingResizer = '';
                        this._removeEvents(e);
                    }
                }
            }
        };`

Now only one finger is perceived when scaling or rotating! :)

**Comment by goodwin74** [comment]
Код выше работает отлично на смартфонах, однако на ПК оказывается анчорс отклеиваются. 
Чтобы исправить нужно в _handleMouseDown сделать условие:
```
 if(e.type !== "mousedown" && e.pointerId > 0){
        return;
    }
```
А в _handleMouseUp сделать так:
```
 if(e.type === 'mouseup'){
        this.movingResizer = '';
        this._removeEvents(e);
    } else {
        for(var item in e.changedTouches){
            if(item !== 'length'){
                if(e.changedTouches[item].identifier === 0){
                    this.movingResizer = '';
                    this._removeEvents(e);
                }
            }
        }
    }
```

вот пример работы https://codepen.io/bulat73/pen/LYYoePZ

**Comment by lavrton** [comment]
I think the issue should be fixed with `konva@5.0.0`
