### ISSUE TITLE
How to implement drag&drop (panning) of the stage using keyboard arrow keys?

### ISSUE THREAD

**Issue by 4zuko** [konvajs/konva#790]
Hi, is it possible to simulate drag&drop (pan feature) of `Konva.Stage` using just arrow keys? For example, pressing the arrow key should set the panning direction and each press should move the stage for 10px in the corresponding direction. As a reference, I used [this](https://github.com/konvajs/konva/issues/65) but I couldn't make it work. Thanks!

**Comment by lavrton** [comment]
Did you try this https://konvajs.org/docs/events/Keyboard_Events.html ?

**Comment by 4zuko** [comment]
Ok. Thanks a lot. I thought that there is another solution with the manipulation of mouse events. Instead of using `circle` I should use the `stage` and _**layer**.batchDraw_ should be replaced by _**stage**.batchDraw_. You can close this item.
