### ISSUE TITLE
support for border images like https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_border-image

### ISSUE THREAD

**Issue by Amitloh** [konvajs/konva#791]
How do I add border images(not border colors) to have frames around image? and then merge it in canvas(and then save as base 64) I am able to merge multiple images on one canvas but not able to get frame border images.

https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_border-image

**Comment by lavrton** [comment]
There is no way to make the same with Konva API directly.

The workaround is to generate a canvas with such a border manually and place it on top of your shape.
