### ISSUE TITLE
Mouse events broken when container scaled with CSS. (setPointersPositions)

### ISSUE THREAD

**Issue by dglasser** [konvajs/konva#792]
This was not broken in Kinetic 5.1.0.

When the parent of the Stage has been scaled with CSS, the Stage.prototype.setPointerPositions does not read the correct mouse coordinates.

I have created a jsFiddle that shows the problem, and also the solution:

https://jsfiddle.net/ns06ojwc/

The code that fixes the problem was copied (including comments) almost verbatim from Kinetic 5.1.0. (_setPointerPosition).

**Comment by lavrton** [comment]
The fix doesn't work for touch events. So it will be inconsistent behavior.

**Comment by dglasser** [comment]
So you're saying you have no intention of fixing this?

**Comment by lavrton** [comment]
Right now, no. If we can find a good workaround for touch events too - then we can use it.

**Comment by dglasser** [comment]
Did you try that workaround for touch events, and verify that it doesn't work? My code only applied it to mouse events. I suppose the same thing could be done for touch events.

**Comment by lavrton** [comment]
Yes, I tried. You can emulate touch events too with Chrome browser.

**Comment by dglasser** [comment]
What I meant was, before testing it, did you actually change the code that handles touch events to use, instead of clientX/clientY, offsetX/offsetY where available, or layerX/layerY in Firefox?

**Comment by lavrton** [comment]
Touch events don't have `offset` properties. But these properties are required to get transformed pointer position.
I was trying to use many methods to make it work with touch. But didn't find yet.

**Comment by dglasser** [comment]
Anton, please look at this:

https://jsfiddle.net/swxzvb7q/

I don't know how robust or efficient this is, but it fixes the problem with touch events also. It even works for multiple touches.

**Comment by dglasser** [comment]
Correction: Multiple touches work on Chrome, but not on Firefox. Single touch works on Firefox however.

**Comment by lavrton** [comment]
Yeah. It is a bit better, but very far from perfect. The container can also be rotated and transformed in 3d. I don't know how to handle those situations.

**Comment by dglasser** [comment]
I just tried it with rotateX(45deg), rotateY(45deg),  and rotateZ(45deg), and my patch worked beautifully, both in desktop and touch.

This is all of the effort I'm going to put into this, Anton. You can decide what to do with this ticket.

Thanks for your time.
