### ISSUE TITLE
setZIndex() does not apply it's new value

### ISSUE THREAD

**Issue by Propfun** [konvajs/konva#796]
When trying to rearranging the shapes using the zIndex methods (zIndex or setZIndex) nothing happens, even when sticking to the maximum length. 
https://jsfiddle.net/16jq3uen/

**Comment by lavrton** [comment]
I see js error in the console. Can you post the updated version?

**Comment by Propfun** [comment]
Apologies, i figured out that it was due to a problem in my own code, when i fixed the jsfiddle it worked right in the intended example, so it could not be the framework.
