### ISSUE TITLE
 How to add a ruler for konva

### ISSUE THREAD

**Issue by 521707** [konvajs/konva#797]
![效果图](https://user-images.githubusercontent.com/37111718/69137860-86ebf800-0af8-11ea-93ac-a2f02bf05bd7.png)
如图所示
How to add a ruler for konva like in Photoshop, move the picture to appear auxiliary line, know where the item is moving. The aim is to know the exact location of the item's movement
请问如何给konva添加像Photoshop里的标尺一样， 移动图片出现辅助线，知道物品所移动的位置。
目的是掌握物品移动的准确位置

**Comment by lavrton** [comment]
Do you mean the coordinates line?

Just draw them.

**Comment by hsluoyz** [comment]
We need this feature too. It would be nice if the official library has this feature.

**Comment by 521707** [comment]
We can do it together

**Comment by 521707** [comment]
We can do it together







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yang Luo"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月22日(星期五) 中午1:11
收件人:&nbsp;"konvajs/konva"<konva@noreply.github.com&gt;;
抄送:&nbsp;"632 。"<521707@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [konvajs/konva]  How to add a ruler for konva (#797)




We need this feature too. It would be nice if the official library has this feature.

**Comment by lavrton** [comment]
Closing the issue. If you need such shape, just draw. As a text + many lines, or a custom shape (for better perf).

**Comment by tacman** [comment]
This would be kinda cool.  Or at least documented.  The closest I could find was this thread, but it's basic and doesn't come anywhere close to the example at the top of this thread.

https://kognitium.com/thread/edafeb01-f0da-467d-8459-703336f555c4

**Comment by tacman** [comment]
In fact, it would be great to see this as example, especially if the ruler were based on physical units (like meters), then an example could show how to properly use scaleX and scaleY.
