### ISSUE TITLE
Konva.Transformer can be broken when use with centeredScaling and mirrored transform

### ISSUE THREAD

**Issue by lavrton** [konvajs/konva#799]
![](https://uploads.disquscdn.com/images/ab136b28ecac7617b2d17a9216b6312949f1525aa22a80065e82cab4348eb068.gif?w=800&h=640)

http://disq.us/p/25nhp2d

**Comment by goodwin74** [comment]
Anton Lavrenov, я полностью пересмотрел код Transformer и сделал другой подход к масштабированию. Все глюк и дерганья больше не беспокоят. Так же код может спокойно обрабатывать мультитач и слушать только 1 палец. 

Думаю вам или может другим будет полезен этот код. Однако там стоит немного доработать код, если работать с другими anchor (topLeft,bottomLeft,topRight и middles), так как я активирую только bottomRight anchor - но добавить в другие anchors код не займет много времени :)
Код сделан как переназначающий существующий код (чтобы иметь возможность обновлений)

Вот сам код и пример работы:
https://codepen.io/bulat73/pen/LYYoePZ

**Comment by lavrton** [comment]
Fixed with `konva@5.0.0`
