### ISSUE TITLE
Create relevant demos

### ISSUE THREAD

**Issue by ShashankaNataraj** [konvajs/konva#80]
Hi,

I see a lot of interest in this library but people are getting turned off due to the lack of demos. Can we create a series of basic demos which can be included in konva.github.io?

**Comment by pgrodrigues** [comment]
Well there are many demos in konvajs website, the problem I see is that they might be hard to find due to being in the bottom of `DOCS` page in `Sandbox` section. Maybe the examples should be in a separate page like: 'DOCS   DEMOS   API   SUPPORT`.

**Comment by ShashankaNataraj** [comment]
@pgrodrigues  +1

**Comment by lavrton** [comment]
Might be good idea. I will try to do this when I have time.

**Comment by ShashankaNataraj** [comment]
@lavrton I would be willing to contribute!

**Comment by lighterletter** [comment]
I'm in the process of designing a physics based javascript game and I'm considering using konva. If I do I'll post it. It would be nice to see some more comments in the demos' code on the website though.

**Comment by lavrton** [comment]
Done. It will be nice to add image preview for each demo in sandbox. But I have to time for this right now...
