### ISSUE TITLE
How can i use sharpening filter?

### ISSUE THREAD

**Issue by zmqp111** [konvajs/konva#800]
Hi.

I am using Konva to make image processing program

How can i use sharpening filter?

Thanks

**Comment by lavrton** [comment]
What is a sharpening filter?

**Comment by zmqp111** [comment]
sharpening filter means High pass filter

This filter increases the clarity of the image.

![image](https://user-images.githubusercontent.com/13760439/69771135-10718900-11cf-11ea-9aa7-ebfd4358b949.png)

**Comment by lavrton** [comment]
I don't know any implementations of that filters for HTML5 canvas. You may try to find it and make your own Konva filter.
I only found this link https://gist.github.com/mikecao/65d9fc92dc7197cb8a7c it may help.
To create a Konva filter you just need to make a function that mutate imageData of the canvas. For demos you can check any filters in the repo. Like https://github.com/konvajs/konva/blob/master/src/filters/Brighten.ts
