### ISSUE TITLE
Konva.Node.create Issue

### ISSUE THREAD

**Issue by arjunoccudiz** [konvajs/konva#803]
Can't draw anything after using Konva.Node.create. I tired everything but it's not working.

Please check below fiddle.

 https://jsfiddle.net/dxvh6zj8/6/

**Comment by lavrton** [comment]
What are you trying to do here? Why do you need `Konva.Node.create(stage, "container");`?

`Konva.Node.create` a function is used to create nodes from JSON. https://konvajs.org/docs/data_and_serialization/Simple_Load.html


In your demo the old stage is replaces with its copy. So you don't see changes on the original stage.

**Comment by arjunoccudiz** [comment]
It worked!

```
var stage = new Konva.Stage({
    container : "container",
    width : 400,
    height : 300
});

var layer = new Konva.Layer();
stage.add(layer);

var text = new Konva.Text({
  x: 10,
  y: 48,
  text:'Hello, World!',
  align: 'left',
  fontSize: 30,
  fontFamily: 'Calibri',
  fill: 'green',
  draggable: true,
  name: `text_${Date.now()}`
});
layer.add(text);
layer.draw();

var stage = Konva.Node.create(stage, "container");
var layer = stage.getLayers()[0];

var text2 = new Konva.Text({
  x: 40,
  y: 48,
  text:'Hello, World 2!',
  align: 'left',
  fontSize: 30,
  fontFamily: 'Calibri',
  fill: 'green',
  draggable: true,
  name: `text_${Date.now()}`
});
layer.add(text2);
layer.draw();

```
