### ISSUE TITLE
Version 4.0.18 shows less info on getStage than 3.4.1. (Used both with React-Konva)

### ISSUE THREAD

**Issue by BertCatsburg** [konvajs/konva#805]
Hello, 

I have a problem with Konva 4.0.18.
Previously I used Konva 3.4.1, using it in combination with [React-Konva 16.10.1-0](https://www.npmjs.com/package/react-konva) (latest version).

Somewhere in the React code I had the following code: 

        const stage = event.target.getStage();
        console.log(stage);
        const offset = {x: stage.attrs.x, y: stage.attrs.y};

This worked fine. 
The stage variable showed the following in the console:
```
         attrs:
		container: div
		draggable: true
		height: 794
		id: "plaatje"
		offsetX: 0
		offsetY: 0
		rotation: 0
		scaleX: 1
		scaleY: 1
		skewX: 0
		skewY: 0
		width: 1132
		x: 0
		y: 0
```

Migrating Konva to 4.0.18 gives me a lot less information on the getStage function: 
```
	attrs:
		container: div
		draggable: true
		height: 794
		id: "picture"
		width: 1132	
```

But I need those 'x' and 'y' numbers. 
I've seen issue [733](https://github.com/konvajs/konva/issues/733)
but that one is closed mentioning that it is fixed in 4.0.9 version, which that's not true for me. 
(Also tested 4.0.9, problem remains)

[Documentation](https://konvajs.org/api/Konva.Stage.html#getStage__anchor) says that it returns a Konva.Stage.
But a [Konva.Stage](https://konvajs.org/api/Konva.Stage.html) class does include the x and y. 

My question/problem: 
**Where are the x and y gone, they should be returned by getStage according to old versions and latest documentation.**

**Comment by lavrton** [comment]
Just don't use `attr` property. It is "private" and to recommended to use. We don't have any demos or documentation about the property. If you need `x` and `y` just use this:
```
stage.x();
stage.y();
```
