### ISSUE TITLE
Container add more than one child cause a typescript error

### ISSUE THREAD

**Issue by bluehymn** [konvajs/konva#806]
Container.add(node1, node2, node3...) cause following error:
**Expected 1 arguments, but got 0 or more. An argument for 'child' was not provided.**

Because the declaration file only provide one argument

```
export declare abstract class Container<ChildType extends Node> extends Node<ContainerConfig> {
    add(child: ChildType): this;

```

I checked the source code, add more than one is ok
```
 /**
   * add a child and children into container
   * @name Konva.Container#add
   * @method
   * @param {...Konva.Node} child
   * @returns {Container}
   * @example
   * layer.add(rect);
   * layer.add(shape1, shape2, shape3);
   * // remember to redraw layer if you changed something
   * layer.draw();
   */
  add(child: ChildType) {
    if (arguments.length > 1) {
      for (var i = 0; i < arguments.length; i++) {
        this.add(arguments[i]);
      }
      return this;
    }
    if (child.getParent()) {
      child.moveTo(this);
      return this;
    }
```
may need to be change to
`add(...child: ChildType[]): this;`

**Comment by lavrton** [comment]
Do you want to make a Pull Request to fix the issue?

**Comment by bluehymn** [comment]
> Do you want to make a Pull Request to fix the issue?

yes, I am glad to fix it

**Comment by alexisfontaine** [comment]
> I checked the source code, add more than one is ok

The current signature for the `add` method is invalid. It doesn't prevent one from providing an empty array, which is not a properly handled case and raises an exception: `TypeError: Cannot read properties of undefined (reading 'getParent')`.

We could update the method signature to something like:
```ts
interface Container<ChildType> {
  add(...children: [ChildType, ...ChildType[]]): this
}
```
introducing a breaking change as the user would be required to manually check for the first element of the array:
```ts
declare const container: Container
declare const children: Node[]

const [head, ...tail] = children

if (head) {
  container.add(head, ...children)
}
```

Or, we could update the method's body to deal with empty arrays at the cost of a few CPU ticks.

**Comment by lavrton** [comment]
Pull Request?

**Comment by alexisfontaine** [comment]
Sure! Let me know how do you want to deal with it and I'll submit one:
1. change the type signature of the function
2. handle empty arrays at runtime

**Comment by lavrton** [comment]
Personally, I would prefer the first. I think a user MUST provide at least one argument.

We can do the second, but we must check that argument is not `undefined`. I am thinking about the case:

```js
const shape = stage.find('.shape-name');
// now assume such shape doesn't, so its value is undefined
// if we call this, it will fail:
container.add(shape);
```

And I think failing is a good design, as user must know that something is not correct.
Just want to make it will not silently continue.
