### ISSUE TITLE
Increase touchmove responsiveness

### ISSUE THREAD

**Issue by ItsEcholot** [konvajs/konva#808]
It noticed that on my Android tablet it took a movement of like ~10px before the first `touchmove` event was fired.
I'm guessing this is an Android / Chrome / Whatever implementation detail that we don't really have control over. However managed to find a way to circumvent that threshold/delay:

```typescript
      document.addEventListener('pointermove', event => {
        if (this.stage) {
          this.stage.setPointersPositions(event);
        }
        this.onTouchMove({ evt: event } as any);
      });
```
Using this dirty code I can bridge the gap before `touchmove` starts being emitted. Interestingly enough `pointermove` then stops being emitted when `touchmove` starts up... Not sure what's up with that. 
So a complete replacement of the `touchmove` event doesn't seem possible.

I'm not sure if there exists any interest in reducing the input event latency for this library and I'm also not sure if my device I use to test on is just an edge case. Feedback on that would be greatly appreciated.

**Comment by lavrton** [comment]
You can also try to enable pointer events in `Konva`:
```
Konva._pointerEventsEnabled = true;
```

Then listen to `pointermove touchmove`.
Will it have any differences?

**Comment by ItsEcholot** [comment]
Yes that works as expected just as well as creating a custom event listener on the document. Makes it a lot more clean but still there's the question why it's even necessary in the first place 🤷‍♂️

**Comment by ItsEcholot** [comment]
Have to take it back after enabling with `Konva._pointerEventsEnabled = true;` it still seems smoother to add a custom pointermove event.

**Comment by lavrton** [comment]
I am going to close the issue for now. I don't see what can we do from the `Konva` side.
