### ISSUE TITLE
trimRight not working in some browsers

### ISSUE THREAD

**Issue by Tendors** [konvajs/konva#809]
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/TrimRight

How i can fix this?

**Comment by lavrton** [comment]
Just provide a polyfill.

**Comment by Tendors** [comment]
var key = 'width';
var val = 100;
textNode.setAttr(key, val);

use browser IE 11

**Comment by lavrton** [comment]
https://github.com/konvajs/konva#browsers-support
