### ISSUE TITLE
Include jshint and jscs into konva

### ISSUE THREAD

**Issue by ShashankaNataraj** [konvajs/konva#81]
if we have a jshintrc and jscsrc added into konva it would help contributors adhere to javascript code style guidelines and ensure we have good contributions coming into this repo.

I could take this up  if need be!

**Comment by lavrton** [comment]
We already have `.eslintrc`. I don't think we need to include all possible linters.

**Comment by ShashankaNataraj** [comment]
and what about jscs?

**Comment by lavrton** [comment]
As I know `eslint` already may cover almost all `jscs` rules. Just need to configure it better. Need to add more rules in configuration file.
