### ISSUE TITLE
image disappear after build the project

### ISSUE THREAD

**Issue by Lexiwu** [konvajs/konva#810]
I use the 'use-image' plugin,
image always undefined after building the project so that the image doesn't show on the canvas.
But it show on the canvas in dev environment.
I don't have any idea why this is happening. Can anyone help me?

"react": "^16.10.2",
"react-dom": "^16.11.0",
 "konva": "^4.0.16",
 "react-konva": "^16.10.1-0",

```
import useImage from 'use-image';

const URLImage = ({
	img,
	imgSelected,
}) => {
	const imgRef = React.useRef();
	const [ image ] = useImage(eleList[img.name]);


	console.log("image---", image) //always return undefined after building project
	


	return (
		<Group>
			<Image ref={imgRef} width={img.width} height={img.height} image={image} />
		</Group>
	);
};

```

**Comment by lavrton** [comment]
Check url for the image. Can you open it?

**Comment by Lexiwu** [comment]
I solved the problem, thank you!
it webpack caused it.
