### ISSUE TITLE
Whether multiple items are selected at the same time after moving the mouse in konva

### ISSUE THREAD

**Issue by 521707** [konvajs/konva#815]
Similar to the fabric JS mouse drag, the items you touch will be selected

 
![1](https://user-images.githubusercontent.com/37111718/71316658-27de2200-24ae-11ea-9639-83a0f67db1da.png)
![3](https://user-images.githubusercontent.com/37111718/71316659-2876b880-24ae-11ea-903b-0bf8c9874b42.png)

**Comment by lavrton** [comment]
Currently, you have to implement such functionality manually. I am planning to make such a demo one day.

**Comment by lavrton** [comment]
Demo: https://konvajs.org/docs/select_and_transform/Basic_demo.html
