### ISSUE TITLE
[FEATURE] Autoredraw stage or layer

### ISSUE THREAD

**Issue by lavrton** [konvajs/konva#816]
Right now we have to redraw a layer on any change of a node.

```javascript
// change color
shape.fill('red');

// redraw layer, so changes are visible on the screen
layer.draw();
```

What if we will allow `Konva` to automatically redraw layer on any change?

```javascript
// change color
shape.fill('red');
// layer is not updated yet
// but Konva will call layer.batchDraw() automatically
// so the change will be visible as soon as possible
```

### How will it work?

Basically we have just three main actions: add, remove, change attribute.
On any of these actions we just need to call `node.getLayer().batchDraw()`.

I don't think it will harm the performance. And we can make a smooth upgrade and make such functionality optional.

```javascript
Konva.autoDrawEnabled = true;
```

**Comment by drawEmoji** [comment]
Auto rendering is a cool function. At the same time, add a switch to turn on auto rendering when you need it, and turn off when you don't need it.

Take my project (diagram editor) for example. Turn on auto rendering when the user edits the picture. Turn off automatic rendering when the user generates GIF motion pictures.

I like this function very much. If it can be, I hope to have it. But at the same time, it is not necessary. It is also convenient to use draw and batchdraw.

**Comment by goodwin74** [comment]
I think this is a good feature, but there may be problems. For example, will it not be that due to auto drawing the load on the browser will increase?

**Comment by lavrton** [comment]
Here is how will it work. Basically we have just three main actions: add, remove, change attribute.
On any of these actions we just need to call `node.getLayer().batchDraw()`.

I don't think it will harm the performance. And we can make a smooth upgrade and make such functionality optional.

```javascript
Konva.autoDrawEnabled = true;
```

_Added info into the first post._
