### ISSUE TITLE
[Feature request] Support touchcancel event on mobile phone

### ISSUE THREAD

**Issue by techGay** [konvajs/konva#817]
In my case,i use mouseleav event to do something when mouseup event not trigger，it work fine when run on PC Desktop Browser,but when run mobile,that is not work。

I have look at all doc about event and source code(stage.ts),i find that seems konva do not support touchcancel event on mobile like mouseleave event on pc so far.

i think it is a useful event ,so can we support touchcancel?

Forgive my pool English，i hope you can understand，thank for your good job。

**Comment by lavrton** [comment]
`touchcancel` is not similar to `mouseleave`.

We can add `touchcancel` support. But it is more similar to `touchend`.

**Comment by techGay** [comment]
ok, thanks .

**Comment by lavrton** [comment]
It will be released with the next `konva@8` release.
