### ISSUE TITLE
[bug] konva's shape to draw custom line not as same as canvas's api

### ISSUE THREAD

**Issue by 5201314999** [konvajs/konva#818]
I have add a smooth line A in canvas and then put the method into scenFunc of shape B ,but the B line is rougher than A.
https://codepen.io/buhaoyisiwoyao/pen/QWwgebX

**Comment by 5201314999** [comment]
I hope the konva can’t let user draw custom something with html5 canvas's api and make it as a konva node.

**Comment by lavrton** [comment]
What difference do you see?

I see only one difference - Konva picture is sharp (not blurred). Because Konva by default supports screens with pixelRatio > 0.

**Comment by 5201314999** [comment]
yes ，it is sharp

**Comment by lavrton** [comment]
1. that is desired default behavior for `Konva`.
2. Currently `Konva.Transformer` doesn't work automatically for custom shape. For the solution take a look here: https://stackoverflow.com/questions/50571367/konvajs-custom-shapes-and-transformers
3. I don't get it. What do you mean?
4. You can learn about pixel ratio and HDPI screen here: https://www.html5rocks.com/en/tutorials/canvas/hidpi/
