### ISSUE TITLE
Can i hide to anchors when on mouseout?

### ISSUE THREAD

**Issue by ErhanBasa** [konvajs/konva#82]
hi, i'm trying to make a mini image editor and i used konva image resize(http://konvajs.github.io/docs/sandbox/Image_Resize.html). right up here but when i tried to generate image, i saw anchor circles in image output. can i toggle the anchors when mouse moves, is it possible?

**Comment by lavrton** [comment]
You just need to implement your own function of hiding and showing anchors.
```javascript
function showAnchors() {
  // some code
}

function hideAnchors() {
  // some code
}

image.on('mouseenter', showAnchors);
image.on('mouseout', hideAnchors);
```

**Comment by ErhanBasa** [comment]
Thanks, but I know it. I don't know how to select the anchors. Can you select yodaGroup anchors at example, please? 

Example: http://konvajs.github.io/docs/sandbox/Image_Resize.html

**Comment by lavrton** [comment]
As you know that anchor is `Konva.Circle` you can you selector with node type:
```javascript
   function showAnchors() {
      this.find('Circle').show();
      layer.draw();
    }

    function hideAnchors() {
      this.find('Circle').hide();
      layer.draw();
    }

    yodaGroup.on('mouseenter', showAnchors);
    yodaGroup.on('mouseleave', hideAnchors);
```
Demo: http://jsbin.com/xonezimoci/edit?js,output



Or you can add `anchor` name to each anchor:
```javascript
var anchor = new Konva.Circle({
            x: x,
            y: y,
            stroke: '#666',
            fill: '#ddd',
            strokeWidth: 2,
            radius: 8,
            name: name + ' anchor',
            draggable: true,
            dragOnTop: false
        });
```
 and then use selector `.find('.anchor')` (but  in this way you also need change some logic in `update()` function)

**Comment by ErhanBasa** [comment]
Thank you for help, now I have a great editor: http://erhanbasa.github.io/thuglifemaker/

**Comment by chapeee** [comment]
do you have any idea how to hide the anchor on text when mouse? moves aways from text
