### ISSUE TITLE
Why `Konva.Transform` is undefined of v4.1.0

### ISSUE THREAD

**Issue by fix777** [konvajs/konva#820]
Thank you for submitting an issue!

Please make sure to check current open and closed issues to see if your question has been asked or answered before.
If you have just a question (not a bug or a feature request) it is better to ask it in [Stackoverflow](http://stackoverflow.com/questions/tagged/konvajs).

If you have a bug, please, try to create a reproducible example with jsfiddle (or any similar service).
You can use [this JSBIN](https://jsbin.com/tekehizuta/1/edit?html,js,output) as a template.

![image](https://user-images.githubusercontent.com/19484638/71790400-35c5a280-306b-11ea-942c-e8dcb3c35756.png)

currently, I should import `Transform` from `konva/lib/Util`.

```jsx
import Konva from 'konva';
import { Transform } from 'konva/lib/Util';
```

**Comment by lavrton** [comment]
Published a fix in `4.1.1`.
