### ISSUE TITLE
Stage.destroy() doesn't get rid of the Stage Object - is this wanted?

### ISSUE THREAD

**Issue by guenyoo** [konvajs/konva#821]
Hello Anton,

while trying to fix memory leaks, I've stumbled over the destroy Method of the Stage.

I would have expected that the stage is cleared. While it is cleared visually, the Stage Object is still defined. Is the reference kept then in konva? Is this intended to behave like this?

I've prepared a fiddle with this behaviour here: https://jsfiddle.net/dbvhxe8z/5/

The reference to children get removed as expected.

Thanks,
Örsan

**Comment by lavrton** [comment]
No, the variable itself will be not cleared. The stage will be automatically removed from the memory by the garbage collector when you HAVE ZERO references to the object.
