### ISSUE TITLE
Canvas add background color, how to always be at the bottom

### ISSUE THREAD

**Issue by 521707** [konvajs/konva#822]
![333](https://user-images.githubusercontent.com/37111718/71948781-2762bc80-320c-11ea-8e45-988dda7c7302.jpg)

**Comment by lavrton** [comment]
First of all, you have a very funny way of writing GitHub issues.

If you need something on the background you basically have two ways:

1. add a `Konva.Rect` or `Konva.Image` into the first layer as the first child. You need to make sure that the size of that node equals to stage size.

2. Style stage container with css: `stage.container().style.backgroundColor = 'red';`.  This solution will work too, but you should remember that it is out of Konva node tree and its control. So if you export stage into the image with konva methods like `stage.toDataURL()` you will NOT have that background.

**Comment by lavrton** [comment]
https://konvajs.org/docs/sandbox/Canvas_Background.html

**Comment by StevenHoppinger24K** [comment]
Seeing the question completly written down on a hand written note really made my day.
