### ISSUE TITLE
Konva.Layer#getIntersection doesn't work with Stage#scaleX < 1 or Stage#scaleY < 1

### ISSUE THREAD

**Issue by tomasfabry** [konvajs/konva#823]
https://codesandbox.io/s/getintersection-bug-linll

When I have the following code then everything works fine. In the console, I see that on coordinates `[0,0]` is an intersection with the line. When I change `scaleY` to `0.5` then the result in the console is `null`. I think it's a bug...

```
import Konva from "konva";

const stage = new Konva.Stage({
  container: "root",
  width: 100,
  height: 100,
  scaleX: 1,
  scaleY: 1
});

const layer = new Konva.Layer();
stage.add(layer);

const line = new Konva.Line({
  x: 0,
  y: 0,
  points: [0, 0, 100, 0],
  stroke: "black"
});

layer.add(line);
layer.draw();

console.log("Intersection", layer.getIntersection({ x: 0, y: 0 }));

```

**Comment by lavrton** [comment]
That may be not expected behavior. But that is how our current hit testing implementation works.

The line is too tiny on the hit graph to produce a correct hit testing pixel color. The workarounds are:

1. Make hit size of a line bigger with `line.hitStrokeWidth(5)`;
2. Increase the quality of hit graph with `layer.getHitCanvas().setPixelRatio(2);`. But that may drop the performance.

I don't have any plans to fix current behavior. Because the described issue is a rare edge case.

**Comment by tomasfabry** [comment]
Thanks for the reply. Can you give me an example of how to use `hitStrokeWidth`? When I modify my line from the example above to:
```javascript
const line = new Konva.Line({
  x: 0,
  y: 0,
  points: [0, 0, 100, 0],
  stroke: "black",
  hitStrokeWidth: 5
});
```

Then the result is still `null`. But when I use `strokeWidth: 5` instead of `hitStrokeWidth: 5` then there is an intersection found. But I don't want to change `strokeWidth`...

Then another weird thing is that `hitStrokeWidth` in API docs has type `Boolean` so I am a little bit confused...

![image](https://user-images.githubusercontent.com/38027246/72050180-d3fe7600-32c0-11ea-9174-0f18661e7f18.png)

**Comment by tomasfabry** [comment]
Sorry, I was using bad version of `konva` dependency in my codesandbox. Now it works! Thank you!

**Comment by lavrton** [comment]
I will fix the docs. Thanks for the report.

**Comment by pranaygoel02** [comment]
> Sorry, I was using bad version of `konva` dependency in my codesandbox. Now it works! Thank you!

Hi, I checked the sandbox, there the intersection is null. Can you tell me what version of konva fixed the issue because I am also facing a similar issue?
