### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 5201314999** [konvajs/konva#824]
1.the cache about arrow still has some error render ， 
and Image. toObject()  misses the width value ，only exists the height value

**Comment by lavrton** [comment]
Can you make a demo for such an arrow? What attrs it has?

> Image. toObject() misses the width value

`toObject()` can make some optimizations if an attribute equals to a default value. Probably that is your case.

**Comment by 5201314999** [comment]
https://codepen.io/buhaoyisiwoyao/pen/QWwOKRe

**Comment by 5201314999** [comment]
https://codepen.io/buhaoyisiwoyao/pen/QWwOKRe

**Comment by lavrton** [comment]
We need to work with it. As a current workaround you can use this `offset` property to increase cache area: `arrow.cache({ offset: 5 });`;

**Comment by 5201314999** [comment]
ok

**Comment by lavrton** [comment]
Right now I am not sure how to better handle such bug.

We can increase the cache area automatically, but that may give unexpected results for `arrow.getClientRect()`. 

So I am closing the issue for now as "won't fix".

And again, as a workaround you can always manually increase the cache area with `arrow.cache({ offset: 5 })`.
