### ISSUE TITLE
Draggable groups and stage

### ISSUE THREAD

**Issue by SuperWiiMan** [konvajs/konva#826]
In konva v2.0.3 you use to be able to have multiple draggable groups and a draggable stage. This no longer seems to be the case?
e.g.
https://konvajs.org/docs/drag_and_drop/Drag_a_Group.html
Use the above example and make the stage draggable and add another group.

**Comment by lavrton** [comment]
It works just fine. Here is the demo with the last version: https://jsbin.com/bibecejofu/edit?html,js,output

I can drag a stage and I can drag a group.

**Comment by SuperWiiMan** [comment]
Would you mind changing it to multiple groups, so I can see it working?

**Comment by lavrton** [comment]
What kind of multiple groups? There are many ways to build a nodes tree. Try to change it as you want it.

**Comment by SuperWiiMan** [comment]
As in 2 groups of the same thing, you only did 1.

**Comment by lavrton** [comment]
Sorry, I don't understand your last message. Can you clarify again, please?

**Comment by lavrton** [comment]
Closing for now. Let me know if you still have any questions.
