### ISSUE TITLE
React-Konva freeze

### ISSUE THREAD

**Issue by quertenmont** [konvajs/konva#827]
For a reason that I don't understand, sometimes react-konva just complete get stuck at first opening
--> I see the CPU usage jumping to 100% and then the web page dies, I can't even close it anymore.  See the screenshot.

If I change anything into my code and recompile and bundle the JS and reopen the same page, quite often the problem is gone.
When I mean changing anything into the code, it could even be just adding a console.log somewhere.

![image](https://user-images.githubusercontent.com/4639944/72610523-e5cac380-3927-11ea-8441-c69a2566ff3c.png)

I haven't see any one reporting this, so I am a bit puzzled about the issue.

My versions are:
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "konva": "^4.1.2",
    "react-bootstrap": "~1.0.0-beta.16",
    "react-konva": "^16.12.0-0",
    "react-redux": "^7.1.0",

I am not doing any fancy thing with the canvas,
mostly drawing an image and some polygons on top of it.

Thanks for your help,
Loic

**Comment by lavrton** [comment]
Try to use different browsers. Also, try to stop code execution when it freezes. You may have some slow loops.

**Comment by quertenmont** [comment]
I tried with brave but got exactly the same thing

When I look where it blocks, it is in the function:
```
handleError (react-reconciler.development.js:14523)
performSyncWorkOnRoot (react-reconciler.development.js:14268)
(anonymous) (react-reconciler.development.js:1931)
unstable_runWithPriority (scheduler.development.js:697)
runWithPriority (react-reconciler.development.js:1881)
flushSyncCallbackQueueImpl (react-reconciler.development.js:1926)
flushSyncCallbackQueue (react-reconciler.development.js:1914)
scheduleUpdateOnFiber (react-reconciler.development.js:13704)
updateContainer (react-reconciler.development.js:17101)
componentDidMount (ReactKonvaCore.js:69)
Pj (react-dom.production.min.js:158)
unstable_runWithPriority (react.production.min.js:25)
pb (react-dom.production.min.js:59)
Ma (react-dom.production.min.js:151)
We (react-dom.production.min.js:132)
(anonymous) (react-dom.production.min.js:60)
unstable_runWithPriority (react.production.min.js:25)
pb (react-dom.production.min.js:59)
Rg (react-dom.production.min.js:60)
ca (react-dom.production.min.js:60)
xi.createPortal (react-dom.production.min.js:238)
cj (react-dom.production.min.js:42)
```
This allowed me to understand that my WebpackCdnPlugin was missing some devlopment and production packages
I disaved that plugin and it seems that the error does not appear anymore.

Thanks for helping,
Loic
