### ISSUE TITLE
How to add delete button/icon on object

### ISSUE THREAD

**Issue by kalitk0** [konvajs/konva#828]
Hello,

I want to achieve something like this on the screenshot, add a delete icon in one of the corners of the selected object. Is it possible ?

![Screenshot 2020-01-18 at 13 17 53](https://user-images.githubusercontent.com/6942744/72662938-82a76280-39f5-11ea-816f-200e5a42bea3.png)

Thank you

**Comment by lavrton** [comment]
You have to manage "delete button" position manually. At the current moment `Konva.Transformer` is just a group with some shape, so you can do this:

```javascript
const tr = new Konva.Transformer({
  node: shape
})
layer.add(tr);

const deleteButton = new Konva.Circle({
  radius: 10,
  fill: 'red'
});

tr.add(deleteButton);

function updatePos() {
   deleteButton.position(tr.findOne('.top-right').position());
}

updatePos();

shape.on('transform', updatePos);
```

https://jsbin.com/zuquzajizo/2/edit?html,js,output

**Comment by danarosca** [comment]
@lavrton is it possible to also keep resize functionality? I'm interested in styling the rotater anchor, but if I use this method the rotation functionality is lost :(
Thanks a lot !

**Comment by lavrton** [comment]
@danarosca how do you want to style it?

**Comment by danarosca** [comment]
@lavrton 
I want to add an image and I have this code: 
  useEffect(() => {
    if (textId == selectedText) {
      trRef.current.setNode(textRef.current);
      trRef.current.setAttrs({
        width: textRef.current.width(),
        height: textRef.current.height,
      });
      trRef.current.update();

      const x = trRef.current.findOne('.rotater');
      x.setAttrs({
        fillPatternImage: rotateImage,
        width: 20,
        height: 20,
        cornerRadius: 50,
        offsetX: 10,
        offsetY: 10,
        fill: null,
        fillPatternScaleX: 0.5,
        fillPatternScaleY: 0.5,
        fillPatternOffset: { x: 0, y: 0 },
        fillPatternRepeat: 'no-repeat',
        strokeWidth: 0,
      });
      trRef.current.getLayer().batchDraw();
    }
  }, [ rotateImage, selectedText, textId, trRef]);

Everything is ok but when I try to transform the text ( rotate or scale) the rotater anchor comes back to the initial style. 

here is the Transformer:

<Transformer
            padding={10}
            flipEnabled={false}
            ref={trRef}
            enabledAnchors={ENABLED_ANCHORS}
            anchorCornerRadius={8}
            anchorSize={12}
            anchorStroke="#00C5C3"
            borderStroke="#00C5C3"
            borderStrokeWidth={2}
            anchorStrokeWidth={2}
            rotateAnchorOffset={30}
            boundBoxFunc={(oldBox, newBox) => getBoundBox(oldBox, newBox, stageRef)}
          />

I've tried to add the style from useEffect on different events ( onTransformEnd for example) and it works, but I should add it in onTransform to ( or in other event, that's what I don't know) because in onTransform seems like it's ignored. 

So my question is: How can I keep that style while transforming? 

Thanks a lot!

**Comment by danarosca** [comment]
@lavrton  and also, is there a chance to move the rotater down and remove that line to the anchor ( but only that one, the ones between the other anchors I want to be there)?

**Comment by ngoctu99** [comment]
@lavrton 
can i ask you a question? like i have a Group with a Rect and a Text. I already added transform for the Group to resize also move them together. Now i want to delete both of Rect and Text the same time, but when i click on it and delete, just Text or Rect would be deleted not all of them?
