### ISSUE TITLE
getClientRect returns wrong results when negative coordinates are involved

### ISSUE THREAD

**Issue by te1** [konvajs/konva#83]
`getClientRect` gives the wrong `y` and `height` if you use negative x coordinates in a `Line`. See console output in this example http://jsfiddle.net/8umaaxx5/

expected result
`{x: -100, y: 0, width: 200, height: 100}`

actual result
`{x: -100, y: -100, width: 200, height: 200}`

**Comment by te1** [comment]
I quickly looked over the code and found `Line.getSelfRect()`

Should this
```JavaScript
var minY = points[0];
var maxY = points[0];
```
be
```JavaScript
var minY = points[1];
var maxY = points[1];
```
instead?

https://github.com/konvajs/konva/blob/master/src/shapes/Line.js#L160

**Comment by lavrton** [comment]
Thanks!
