### ISSUE TITLE
Dragging and Zooming Alter Coordinates

### ISSUE THREAD

**Issue by bengao01** [konvajs/konva#830]
When we drag or zoom in Konva, the x and y coordinates that the mouseClick provides changes. Is there a way to maintain an absolute coordinate system after zooming and panning?

**Comment by lavrton** [comment]
You just need to convert the absolute position of a pointer into a relative position. Take a look into this demo: https://konvajs.org/docs/sandbox/Relative_Pointer_Position.html

The calculations can be a bit simpler if you just move/scale a stage.
