### ISSUE TITLE
Problem with empty layers, when create stage from json

### ISSUE THREAD

**Issue by guru-nemo** [konvajs/konva#831]
Hello, i have a problem with empty layers, when create stage from json. I need to save history of drawing steps. So i save every stap as json object in array and them create its from the stage.
This is my redraw code:
```
stage = Konva.Node.create(jsonArr[currentView-1], 'container');
stage.add(layerImage);
    layerImage.find('.userImg').remove();
    if(Object.keys(arrImg).length > 0) {
        var imges = stage.find('.userImg');
        imges.each(function(image){
            var i = image.id();
            var img = image.image(arrImg[i]);
            layerImage.add(img);
            stage.find('.tr').remove();
        });
    }
 stage.draw();
```
after each step i get one or more empty canvas in container. and in console i have message, that too many layers in stage.
my stage varible is global.

**Comment by lavrton** [comment]
As I can see in this code you are adding a layer into the stage: `stage.add(layerImage);`. If you later convert that stage into JSON if you will one extra layer on every redraw.

Just think how to reuse one layer.

**Comment by guru-nemo** [comment]
it is posible to remove empty layer from stage? for example, to get all layers and remove only empty.

**Comment by lavrton** [comment]
Yes. Check `layer.children.length`. If it is 0, the layer is empty, you can `layer.destroy()` it.

**Comment by guru-nemo** [comment]
but how get all layers in stage?

**Comment by lavrton** [comment]
```
stage.children.forEach(layer => {
   // do something with layer
});

**Comment by guru-nemo** [comment]
thanks, it almost solved my problem. how would be better to save steps of drawing, in json or exists another opportunity?

**Comment by lavrton** [comment]
It depends on how you want to use those steps. You can use Konva JSON or our own state.

https://konvajs.org/docs/data_and_serialization/Best_Practices.html#What-is-the-best-way-to-save-load-full-stage-content-and-how-to-implement-undo-redo
