### ISSUE TITLE
Konva.Node#getClientRect doesn't work properly on rotated objects

### ISSUE THREAD

**Issue by tomasfabry** [konvajs/konva#832]
When I have some object and I set him some `rotation` then the `getClientRect` function doesn't work as expected in my opinion.

For example, when I have a circle then I expect the client rectangle should be the same no matter what value I set to the rotation.

Let's see: https://codesandbox.io/s/konva-demo-048gt

**Comment by lavrton** [comment]
I agree. `node.getClientRect()` is not always returning accurate values for all shapes. It simplifies a shape to a rectangle.

For the demonstration take a look here: https://codesandbox.io/s/konva-demo-q91hk

Fixing such behavior is a very low priority task. You can implement your own function for calculation client rect.
