### ISSUE TITLE
Transformer's anchor doesn't scale when the stage is zoomed in (works for zoom out)

### ISSUE THREAD

**Issue by sebastiendan** [konvajs/konva#834]
Hi,

Using [this code](https://konvajs.org/docs/sandbox/Zooming_Relative_To_Pointer.html) for zooming the stage on scroll and adding on stage click shapes along with rotation transformers, I see that the transformers anchors do not scale on scroll when the stage is zoomed in (works for zoom out).

Here's a screenshot of a normal shape+transformer on the left, and a buggy one on the right. 

The buggy one was created on the very zoomed out stage. Then the stage was zoomed back to normal and the left shape+transformer was inserted.

![Screenshot from 2020-01-27 15-40-10](https://user-images.githubusercontent.com/12198372/73155114-feec2500-411c-11ea-8c60-1b83b607dfc9.png)

**Comment by lavrton** [comment]
Can you make a demo, please?

**Comment by sebastiendan** [comment]
Here it is: [demo](https://codesandbox.io/s/elegant-kapitsa-xui3v?fontsize=14&hidenavigation=1&theme=dark)

- Click on the stage to create an object
- Zoom out
- Create another object
- Zoom in

**Comment by sebastiendan** [comment]
Actually the issue is about the transformer's anchor being drawn with no consideration to the stage scale at the moment of drawing. 

It's not about zooming since the wrongly sized anchor still gets its right scale and position on zoom updates.

**Comment by lavrton** [comment]
I think that is a bug. Probably `Transformer` should know about the parent scale. As a workaround you can just call `forceUpdate()` on a transformer.

https://codesandbox.io/s/festive-raman-ojd5w

**Comment by sebastiendan** [comment]
Thanks for the workaround, and for the awesome library :+1:

**Comment by lavrton** [comment]
We are going to have a lot of changes in a new Transformer. The issue will be fixed in the next release.
