### ISSUE TITLE
React Konvajs cached image + transformer

### ISSUE THREAD

**Issue by staticdreams** [konvajs/konva#835]
I'm trying to use React Konvajs to create a canvas with an image that can be manipulated (with Transformer) and apply ``Konva.Filters`` to it.

Basically I'm combining two example demos: [Transformer](https://codesandbox.io/s/github/konvajs/site/tree/master/react-demos/transformer?from-embed) and [Filters](https://codesandbox.io/s/github/konvajs/site/tree/master/react-demos/filters?from-embed)

But I ran into a problem where Filters require you to cache the image/shape, where as Transformer does not like cached images. The issue comes when trying to resize the bounding box the image goes back to original size while transformer around the image represents correct size.
If I remove ``imageRef.current.cache();`` from ``React.useEffect()`` everything works as it should.

To illustrate the issue here's a forked example [Transformer demo](https://codesandbox.io/s/transformer-with-image-shape-cache-m0lpn). This is exactly what I am getting. Without cache transformer works great, but filters do not.

Is there a way around this issue?

**Comment by lavrton** [comment]
The transformer demo is reseting scale property, so you have to recache images. It may be not trivial how to do that, but here is my demo:

https://codesandbox.io/s/transformer-with-image-shape-cache-and-no-scale-p5gcs

The demo with scaling is a bit simpler: https://codesandbox.io/s/transformer-with-image-shape-cache-scaled-4lrn6


I hope it helps.

**Comment by staticdreams** [comment]
Спасибо большое, Антон!

**Comment by colonist7** [comment]
> The transformer demo is reseting scale property, so you have to recache images. It may be not trivial how to do that, but here is my demo:
> 
> https://codesandbox.io/s/transformer-with-image-shape-cache-and-no-scale-p5gcs
> 
> The demo with scaling is a bit simpler: https://codesandbox.io/s/transformer-with-image-shape-cache-scaled-4lrn6
> 
> I hope it helps.

I Love you <3 :D :D

**Comment by khanzzirfan** [comment]
Thank you so much. This has helped me alot @lavrton

**Comment by Sreya27** [comment]
> The transformer demo is reseting scale property, so you have to recache images. It may be not trivial how to do that, but here is my demo:
> 
> https://codesandbox.io/s/transformer-with-image-shape-cache-and-no-scale-p5gcs
> 
> The demo with scaling is a bit simpler: https://codesandbox.io/s/transformer-with-image-shape-cache-scaled-4lrn6
> 
> I hope it helps.

Hi. The demo seems to solve the problem. But, when I have multiple filters whose values are changing. Then, the problem arises again. Is there a way to solve this issue?
