### ISSUE TITLE
Apply Filters to video

### ISSUE THREAD

**Issue by rebinnaf** [konvajs/konva#836]
I tried to use filters with the Konva image object which is a video, but I get an error: "Konva error: Unable to apply filter. The operation is insecure". I don't know what's the problem exactly, but my code works if I use an image instance instead of the video. Does Konva support Filters for video as well?

**Comment by lavrton** [comment]
You may have such errors when the video is CORS protected. Often use case is when a video is hosted on another domain.

But Konva filters are not fast enough for video. They ok for images (as we need to apply a filter just once). Applying filters for every frame of the video can be very slow.

I think two workarounds:
1. Do not draw a video with Konva. Instead, add Konva stage on top of the video element with an absolute position. You can use CSS filters for video. (CSS filters are much faster)
2. Move video into another layer for video only. Use CSS filters for the canvas element of that layer. For a demo take a look into this post:  https://lavrton.com/case-study-image-labeling-for-machine-learning/
