### ISSUE TITLE
Transformer anchor mouse cursor does not account for layer rotation

### ISSUE THREAD

**Issue by akohring** [konvajs/konva#837]
Konva Version: 4.1.2

Steps to reproduce:
- Create a node, such as a rectangle, with a rotation applied.
- Attach the node to a Transformer.
- Add the Transformer to a layer that has a rotation applied.
- Hover over one of the drag handles and notice the mouse cursor arrow direction is not correct.
- Despite the incorrect mouse cursor, the resize capabilities work as expected.

JSFiddle to demonstrate the issue:
https://jsfiddle.net/tgvhoq15/

![Screenshot_2020-01-29_11-35-33](https://user-images.githubusercontent.com/5578542/73376479-8192f280-428b-11ea-96fd-7dd604986abd.png)

**Comment by lavrton** [comment]
Thanks for the report. Fixed in `4.1.3` version.

**Comment by akohring** [comment]
Perfect, thank you!
