### ISSUE TITLE
React-Konva Shape seems to be generating hitFunc by closing the shape drawn in shapeFunc

### ISSUE THREAD

**Issue by m1h4** [konvajs/konva#838]
When drawing a custom, path based, shape using Shape and shapeFunc, the generated default hitFunc will hit inside the path shape even if the path was not closed.

Example:
https://codesandbox.io/s/epic-night-52ley?fontsize=14&hidenavigation=1&theme=dark

This seems to not be the case when using pure konvajs like in this example where the line shape is properly hit tested with a default hitFunc:
https://konvajs.org/docs/events/Custom_Hit_Region.html

**Comment by lavrton** [comment]
By default `Konva` fills shapes. We have some cases where not filling a shape may be unexpected.

To fix the issue you can:
1. use `context.strokeShape(shape);` instead of `context.fillStrokeShape(shape);`
2. or set `fillEnabled={false}`

**Comment by m1h4** [comment]
Oh… thanks for clarifying this!
