### ISSUE TITLE
Efficient way to detect changes to shape

### ISSUE THREAD

**Issue by friksa** [konvajs/konva#839]
Building a multi-user real-time collaborative Whiteboard and it Konva is working great.  There does not seem to be an easy way to receive an event when an Object is updated by editing, resizing, moving, etc.  Currently, I have to try and track every possible change to notify the server.

It would be nice to have an event that notifies me of all changes to objects.  I have been through all the documentation and StackOverflow and have not found anything yet to simplify this task.

**Comment by lavrton** [comment]
We may probably have a mechanism for that if we decide to implement this feature: https://github.com/konvajs/konva/issues/816

You have all the events to track that changes. There are not many of them. It is `dragend` and `transformend` if you use `Konva.Transformer`. All other changes are made by your code. So I don't think it will be hard to add your own listeners.

**Comment by friksa** [comment]
Probably a better request would be to add an event listener by type.  Instead of adding textNode.on('dragend') to every Text Shape, it would be nice to use layer.on('dragend.text')

**Comment by lavrton** [comment]
`dragend` event bubbles into the top. So you can do this:

```js
stage.on('dragend', (e) => {
   if (e.target instanceOf Konva.Text) {
     // do work
   }
});

**Comment by friksa** [comment]
Awesome!  Assuming that the transform events bubble too, I should be all set and we can close the ticket.  Thanks!

**Comment by lavrton** [comment]
I am not sure `transform` events are bubble too. Probably we didn't implement it yet.

**Comment by friksa** [comment]
Since everything is possible with more code today, it is a low priority nice-to-have that will help to clean up the code later. Thanks.

**Comment by lavrton** [comment]
Closing the issue for now, because I don't see much use cases here.
