### ISSUE TITLE
0.9.5 version getAngle Deg conflict

### ISSUE THREAD

**Issue by gharibyan** [konvajs/konva#84]
Hi there, i have getting this error on 0.9.5 and cant figure out what is the problem
Konva error: getAngleDeg method is deprecated and will be removed soon. Use getAngle instead

Can you help me?

Thanks.

**Comment by lavrton** [comment]
Your code is using old API. You can use stack trace of the error to find place to fix. Probably you have `angleDeg` property on your node. Just replace it with `angle`.
