### ISSUE TITLE
Transformer handles location discrepancy when resizing on scaled stage

### ISSUE THREAD

**Issue by friksa** [konvajs/konva#841]
Using the transformer to edit text based on this example:
[https://konvajs.org/docs/sandbox/Editable_Text.html](https://konvajs.org/docs/sandbox/Editable_Text.html)

When the stage is scaled down with a CSS transform and you resize the text, everything visually looks great, except the handles do not follow the actual mouse location.

Please see this video showing the issue:
[https://www.screencast.com/t/sLaR6NqIMtA](https://www.screencast.com/t/sLaR6NqIMtA)

**Comment by lavrton** [comment]
I think it is fixed now. I will publish the release later.

But in general, I don't recommend to scale stage with CSS. Usually, it is better to use `stage.scale()`

**Comment by friksa** [comment]
Awesome!  Thanks so much.  Will test it as soon as it is available.

We are scaling multiple items at the same time with CSS as the whiteboard is used to annotate on top of other components such as videos, images, and other custom widgets.  Not all of these custom components can be be added to the stage.

**Comment by friksa** [comment]
Confirmed that it is fixed in 4.1.4.  Thanks again for a great project!

**Comment by lavrton** [comment]
Thanks for checking!
