### ISSUE TITLE
Image in middle of rectangle

### ISSUE THREAD

**Issue by guru-nemo** [konvajs/konva#844]
i need make long image with both empty margin(left, right) with width equale image width.
i make rectangle with width imageWidth*3 and trying fillPatternImage. but i got too big image over all rectangle. 
what i should do with image for set it in the middle of rectangle?

**Comment by lavrton** [comment]
There are many properties to control the pattern. You can use `fillPatternRepeat`, `fillPatternX` and `fillPatternY`.

Or you can just use two shapes. One - filled rectangle. Another - image on top.

**Comment by jonybekov** [comment]
It can be achieved like this using `Group`:

```typescript
<Group
      x={0}
      y={0}
    >
      <Rect
        width={48}
        height={48}
        cornerRadius={4}
        fill="white"
        shadowBlur={5}
        shadowOpacity={0.1}
        shadowOffsetY={5}
      ></Rect>
      <Image
        x={4}
        y={4}
        width={40}
        height={40}
        fit="contain"
        image={image}
      />
    </Group>
```
