### ISSUE TITLE
 json.stringify the line or arrow ,onFinish is erro

### ISSUE THREAD

**Issue by jiqwjsiwwkeksds00992** [konvajs/konva#845]
When I use json.stringify (line or arrow) to add to the layer
konva.js in 9454
```
Node.prototype.to = function (params) {
var onFinish = params.onFinish;
params.node = this;
params.onFinish = function () {
this.destroy();
if (onFinish) {
OnFinish ();
}
}
var tween = new Tween(params);
tween.play();
}
```
params.onFinish(Uncaught TypeError: Cannot read property 'onFinish' of undefined)
My version of konva is 4.1.0

**Comment by lavrton** [comment]
How to reproduce it? How do you use `json.stringify`?

**Comment by lavrton** [comment]
Closing the issue. Let me know if you still have the bug. Please make a demo for it.
