### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by rebinnaf** [konvajs/konva#846]
using rgba is much better than using opacity in performance. It would be great if you mention it in your documents. I used opacity for my application and It was slow in dragging; I changed the fill property with rgba and it changed a lot.

**Comment by lavrton** [comment]
I don't see any differences here. Do you use strokes too?
If so, you may have a difference here. See demo: https://konvajs.org/docs/performance/Disable_Perfect_Draw.html

**Comment by rebinnaf** [comment]
I think it is different when you have many layers. I use an image layer in the background and then draw partly transparent shapes on top of it and don't care about strokes. When I use opacity for this purpose, dragging is very slower than when I use rgba instead. I understood that using opacity highly affects the frame rate in action. Also, here is a comparison of using rgba or opacity: https://stackoverflow.com/questions/13385492/css-opacity-vs-rgba-which-one-is-better.

Thanks.

**Comment by lavrton** [comment]
I am not sure how to mention that in the docs.

I created this demo: https://jsbin.com/zukisivobi/1/edit?html,js,output

The FPS is always the same for me. It doesn't matter what opacity method I am using.
I guess there are some cases when `rgba` can be faster. I just don't know how to reproduce such perf trick.

Thank for your note. I am going to close the issue.
It will be really awesome if you can provide a real example, so I can demonstrate it in the docs.
