### ISSUE TITLE
Transformer doesn't work with a horizontal line

### ISSUE THREAD

**Issue by Botz** [konvajs/konva#848]
I have a Line with four points: [10, 10, 20, 10]
With a transformer attached and transforming the transformer collapses and returns Nan for x, y, height, width

This is because the getSelfRect method returns 0 for the height property.

I would recommend to return the strokeWidth as height for this case.
```
      width: Math.max(this.strokeWidth, Math.round(maxX - minX)),
      height: Math.max(this.strokeWidth, Math.round(maxY - minY)),
```
I will provide a PR, or do you have any concerns about this solution?

**Comment by lavrton** [comment]
It already takes a stroke into account. I tried this demo it works ok https://jsbin.com/rakepebuyu/1/edit?html,js,output

But in general, I don't think such horizontal and vertical lines are good for `Konva.Transformer`.  For line transform, it is better to use custom own anchors.

**Comment by Botz** [comment]
Oh you are right, we had a default transformer setting where ignoreStroke was set to true this was the problem

**Comment by ThangLe3111996** [comment]
> It already takes a stroke into account. I tried this demo it works ok https://jsbin.com/rakepebuyu/1/edit?html,js,output
> 
> But in general, I don't think such horizontal and vertical lines are good for `Konva.Transformer`. For line transform, it is better to use custom own anchors.

@lavrton hi, i have a problem like that too but i dont access to link which you tried to fix. Can you help me?
