### ISSUE TITLE
getClientRect returns wrong results when a layer/group is empty

### ISSUE THREAD

**Issue by te1** [konvajs/konva#85]
`getClientRect` returns `NaN` if you have an empty `Layer` or `Group` somewhere in your tree. See console output in this example http://jsfiddle.net/scy8kny5/1/

expected result:
`{x: 50, y: 100, width: 200, height: 75}`

actual result:
`{x: NaN, y: NaN, width: NaN, height: NaN}`

It appears `Container.getClientRect` currently does not handle the no children case.
https://github.com/konvajs/konva/blob/master/src/Container.js#L412

P.S: Thanks for your fast response on the other issue :+1:

**Comment by lavrton** [comment]
Thanks for report!

**Comment by te1** [comment]
This is only partially solved. I updated the example to use the latest Konva dev version http://jsfiddle.net/scy8kny5/2/

expected result:
`{x: 50, y: 100, width: 200, height: 75}`

actual result:
`{x: 0, y: 0, width: 250, height: 175}`

If `{x: 0, y: 0}` is not inside your actual bounding box `Container.getClientRect` yields wrong results with empty Layers or Groups.

**Comment by lavrton** [comment]
Not really sure about expected result. As you have group in `{x:0, y:0}` position this example.

**Comment by te1** [comment]
You are right. I didn't consider that the empty group still has an implicit position and size of 0. For my use case (zoom to fit viewport) it would be convenient if empty groups would simply be ignored for `getClientRect` but I see now this is not something everyone would want all the time.
