### ISSUE TITLE
Stage clone does not clone layer id attribute

### ISSUE THREAD

**Issue by akohring** [konvajs/konva#850]
Konva Version: 4.1.5

Steps to reproduce:
- Create a stage
- Add a layer with an id to the stage
- Clone the stage
- Attempt to find the layer by id on the cloned stage

Expected behavior:
- The layer is found by id on the cloned stage

Actual behavior:
- The layer is not found by id on the cloned stage

JSFiddle to demonstrate the issue:
https://jsfiddle.net/vpb8y94m/

**Comment by lavrton** [comment]
Previously we had a restriction that `id` must be unique. So it was not included in the cloned object. But now we don't have such a restriction. So I think we can keep `id`.

Fixes with the last commits. Will be released later.
