### ISSUE TITLE
Image with transparency options

### ISSUE THREAD

**Issue by dhalldmg** [konvajs/konva#853]
![Capture](https://user-images.githubusercontent.com/58263614/75074783-6736e800-54ca-11ea-87f3-efb485ae3602.JPG)

First - thank you for your work on this project.  It is awesome and has made my current project fun to work on.

I'm noticing some inconsistency with manipulating images with transparency though.  

- Shadow appears to target opaque areas and builds the shadow from that.

- Stroke appears to take the full image as its target

- Gradient Fill targets the transparent area

- RGB filter targets the opaque area.

I'd suggest either a new option so developers could target transparent,opaque,all.   If that is not feasible then could all the manipulations target opaque?

**Comment by lavrton** [comment]
I am not sure how we can handle that from the `Konva` side.

1. Shadow targets opaque areas. That is how canvas API works. And that is what almost all developers expect from shadows.
2. There is no stroke and fill for images in 2d canvas API. But Konva can do that by just drawing a rectangle with the size of the image. So you see a rectangle with a stroke or fill. It works well for "rectangle-like" images.

It is not simple to draw a stroke around image. We have a demo here: https://konvajs.org/docs/sandbox/Image_Border.html
(I hope to write another related demo with a different approach).

**Comment by dhalldmg** [comment]
Thanks for the reply.  Reading about this topic I discovered the marching squares algorithm and looking at https://github.com/sakri/MarchingSquaresJS   as something that could be used on my side.
