### ISSUE TITLE
make destroy ,spend too much time

### ISSUE THREAD

**Issue by runFP** [konvajs/konva#854]
when I make destroy a layer with a lots of group(about 6000), the process it's too slow(15000ms),it's have method to improve it?

**Comment by lavrton** [comment]
@runFP do you have many children inside a group?

**Comment by runFP** [comment]
@lavrton  I read your optimization tutorial,use a new layer for every 1000 group and each group consist of 5 text or rect.

**Comment by lavrton** [comment]
So does it work better with several layers? Are all groups visible at the same time on the screen?

**Comment by runFP** [comment]
@lavrton Yes,It‘s better than before, but also render slowly as every group is visible at the same time on the screen. I think no way to optimize it except reduce the number of elements.

**Comment by lavrton** [comment]
I am going to close the issue for now.

We may think about how to improve the performance of `destroy()` method.

But in general 6000 items is a lot for canvas (it depends on shapes).
Try to reduce the number of elements on the canvas (remove elements that are not visible in a viewport). 

And also you may try to use caching, where possible.

**Comment by arifhussain353** [comment]
@lavrton  I am facing the same issue. I need to display more than 15000 items. All items are visible in a viewport.  
By doing `this.$refs.dashboardStageLayer.getNode().cache();` performance much better but when I do `this.$refs.dashboardStageLayer.getNode().clearCache()` to clear and place new data then it freez my current browser tab.
Any idea?
