### ISSUE TITLE
konva-node text stroke/shadow not working

### ISSUE THREAD

**Issue by tomasziwaszko** [konvajs/konva#855]
Stroke doesn't work for text but for shape does. If you apply this code on NodeJS you can reproduce bug: https://jsfiddle.net/k64deLbt/

I can draw stroked text using canvas-prebuilt api but cannot using konva-node

Konva 7.2.5
canvas-prebuilt 2.0.0-alpha.14

I am using fork: konva-node-prebuilt 1.0.2

**Comment by lavrton** [comment]
I was not able to reproduce the issue with the current development version of Konva. Probably that was an issue from `canvas` package.
