### ISSUE TITLE
TypeScript definitions broken?

### ISSUE THREAD

**Issue by romor** [konvajs/konva#856]
This might be related to #785, but this is closed and the solution there does not work for me.

My TypeScript code is as follow:
```javascript
import Konva from 'konva';
const stage = new Konva.Stage({ container: 'container' });
```

This compiles, but yields the following runtime error: `TypeError: konva_1.default is undefined`

I use `nodejs` with `webpack`. `es2015` and `dom` is set in `tsconfig.json`. The generated JavaScript code is this:
```javascript
var konva_1 = __webpack_require__(/*! konva */ "./node_modules/konva/lib/index.js");
var stage = new konva_1.default.Stage({ container: 'container' });
```

A similar problems appears with the second proposed syntax variant:
```javascript
import * as Konva from 'konva';
const stage = new Konva.default.Stage({ container: 'container' });
```

This compiles to:
```javascript
var Konva = __webpack_require__(/*! konva */ "./node_modules/konva/lib/index.js");
var stage = new Konva.default.Stage({ container: 'container' });
```
yielding again the runtime error: `TypeError: Konva.default is undefined`

What is working, but omitting type definitions, is:
```javascript
import * as Konva from 'konva';
const stage = new (Konva as any).Stage({ container: 'container' });
```

I suppose the cause of the problem lies in the Typescript definitions?
Or is there something I misunderstood?
Is there any work-around where I can still use the type definitions?

**Comment by lavrton** [comment]
Ok. I updated the readme. Looks like `Konva` doesn't work well with the default ts config now.

https://github.com/konvajs/konva#typescript-usage

Take a look into updated readme, please. Does it help?

**Comment by romor** [comment]
Yes, thanks, setting `esModuleInterop`to `true` solves this.
