### ISSUE TITLE
toObject my fail to serialize number, string or boolean

### ISSUE THREAD

**Issue by rfm1201** [konvajs/konva#86]
I use Kinetic, not Konva, but the problem still exists in Konva, so...
The toObject method of the Konva.Node class doesn't want to serialize object. Fine.
But if someone added a method to number, string or boolean, those values won't be serialized anymore.
It's what happens with a lib a use. They add a format method to number.
The result, no number serialized by toObject. BIG problem, because many number should be serialized (position, size, ratio at least).
My solution, change the if in the "for(key in attrs)" loop to
if (typeof val !== 'number' && typeof val !== 'string' && typeof val !== 'boolean' &&
(Konva.Util._isFunction(val) || Konva.Util._isElement(val) ||
(Konva.Util._isObject(val) || Konva.Util._hasMethods(val)))) {

I made this change in Kinetic and had no trouble since.

**Comment by lavrton** [comment]
Thanks.

**Comment by rfm1201** [comment]
With the last version you put this morning I still have the issue.
When I look at the commits, the last one is the modification of this issue. but the change seems to miss in konva.js.
Did you commit the library with the modification?

**Comment by lavrton** [comment]
Right. Forgot to build.

**Comment by lavrton** [comment]
Now done!
