### ISSUE TITLE
hello！Can you help me with the following questions about text 

### ISSUE THREAD

**Issue by jandesign-lee** [konvajs/konva#862]
I try to make a editable and scaleable text  with KonvaJs , but the effect is not what I want. I am new at this and hope to get help，3Q！

first，I need text to scale keep ratio  and indent ，like this:
![IMB_X2WHYA(1)](https://user-images.githubusercontent.com/61448583/75626652-3cecd500-5c04-11ea-94a8-c326bf621941.gif)

But my work is....
![IMB_3qymeQ](https://user-images.githubusercontent.com/61448583/75626700-bdabd100-5c04-11ea-91e6-3c33335caf1e.GIF)

then double clicking the text,text size is the size of the transform。like this:
![IMB_Miwfsd](https://user-images.githubusercontent.com/61448583/75626829-d10b6c00-5c05-11ea-977f-199b69fb1386.GIF)

But my work is....
![IMB_OxTt2K](https://user-images.githubusercontent.com/61448583/75626880-2b0c3180-5c06-11ea-9600-7bf5c7b5d4f8.GIF)

**Comment by lavrton** [comment]
Ok, that is not trivial, but possible.

I am working with the new framework on top of the `Konva` framework, which has very similar functionality.

Here is the example with `react-konva`, I think your can easily adapt it for pure Konva:

```javascript
    <Text
        {...textProps}
        onTransform={e => {
          const anchorName = e.target
            .getStage()
            ?.findOne('Transformer')._movingAnchorName;

          const changingWidth =
            anchorName === 'middle-left' || anchorName === 'middle-right';

          if (changingWidth) {
            // reset scale, change width instead
            const scale = e.target.scaleX();
            e.target.width(
              Math.max(e.target.width() * scale, element.fontSize)
            );
            e.target.scaleX(1);
          }
        }}
        onTransformEnd={e => {
          // reset scale, change fontSize and width instead
          const scale = e.target.scaleX();
          e.target.scaleX(1);
          e.target.scaleY(1);
          element.set({
            fontSize: element.fontSize * scale,
            width: e.target.width() * scale,
            x: e.target.x(),
            y: e.target.y()
          });
        }}
      />
```

Let me know if it helps.
