### ISSUE TITLE
Cannot read property 'apply' of undefined 

### ISSUE THREAD

**Issue by lukasbee1** [konvajs/konva#863]
I asked question on stackoverflow, the lint is [here](https://stackoverflow.com/questions/60516463/cannot-read-property-apply-of-undefined-konva-js)

I got error when use .find method to find from array of `shapes` .
The problem directly in node_modules/konva/lib/Util.js:19

**Comment by lukasbee1** [comment]
https://codesandbox.io/s/keen-haibt-l2c9q?fontsize=14&hidenavigation=1&theme=dark

**Comment by lavrton** [comment]
https://stackoverflow.com/a/60518043/512042

**Comment by lavrton** [comment]
Probably `Konva.Collection` should match all Array methods.

**Comment by lavrton** [comment]
Looks like we should not preserve Array methods. For backward capability, I will save original behavior for now.
