### ISSUE TITLE
How to integrate ParticlesJS with KonvaJS?

### ISSUE THREAD

**Issue by enriqueerrando** [konvajs/konva#865]
Hi,

I was wondering if there is a way to add particles to KonvaJS with [ParticlesJS](https://github.com/VincentGarreau/particles.js/) (or similar) or just simulate them somehow with plain Konva.

Thanks in advance!

**Comment by lavrton** [comment]
How do you want to use it?

As I know,  ParticlesJS is drawing into the canvas element. So you can put that canvas element on top of Konva stage or under it.

Another way is to use `Konva.Image` add use ParticlesJS's canvas element for it. Similar to https://konvajs.org/docs/sandbox/Video_On_Canvas.html

**Comment by enriqueerrando** [comment]
Hehe, that's exactly what I came up with, but the ultimate idea would be to being able to add it to the main konva layer where I add all my shapes to work with that layer zindex, so u could move particles item up/down to positione it between any shapes.

Thanks!

**Comment by lavrton** [comment]
In that case, my last suggestion should work just fine.

**Comment by enriqueerrando** [comment]
Oh, sorry, I missed that last line!!

I've tried the demo but is not very smooth, maybe is just my connection. I'll try it on my project and I'll get back to u ;)

Thanks!
