### ISSUE TITLE
Konva 'removeEventListener' native override removes all listeners

### ISSUE THREAD

**Issue by lauritk** [konvajs/konva#866]
I found that Konva overrides native 'addEventListener' and 'removeEventListener', but remove does not work as it should (least I think so).

See this test https://codepen.io/lauritk/pen/LYVzzdp?editors=1111 Open console and after initial test clear one of the 'removeEventListener' line comments. 'removeEventListener' removes all listeners.

Why native functions are overridden? Is there way to bypass this?

Tested on MacOS Chrome 80.0.3987.122

**Comment by lavrton** [comment]
`Konva` nodes are just JavaScript objects. JavaScript objects don't have native `addEventListener` and `removeEventListener`. So `Konva` overwrites nothing here.

 `addEventListener` and `removeEventListener` - is not a public API. We don't have them in the documentation and demos. They existing only for experimental integration with other third-party libraries.

**Comment by lauritk** [comment]
Yeah, sorry you're right. It's specified in the DOM specification for the EventTarget interface. Still new with Javascript and web stuff. Well did you try the example at least?

**Comment by lavrton** [comment]
@lauritk yes, I  did. I agree that it doesn't work, as expected. But I don't have any plans to change that "private" method for now.

Just use `on` and `off` instead.

**Comment by lauritk** [comment]
Unfortunately `on` and `off` are not suitable for our own "state machine" implementation, but found a workaround `stage.getContent().addEventListener(a, b)`. Thanks for your trouble.

**Comment by lavrton** [comment]
You can use that too, but it will add DOM event listeners of the stage container, not Konva events.
