### ISSUE TITLE
Hit area for non-closed Paths

### ISSUE THREAD

**Issue by adamdva** [konvajs/konva#867]
When a Konva Path is defined using lines and arcs, creating a type or polyline, the hit area acts as the Path is closed (like a polygon). The Path definition does not contain a closing 'Z'

The effect is the line accepts a 'click' event over a potentially large area.

One work around is to 'double-back' the Path definition, then close. But this makes Path drawing less efficient, and corrupts a dash pattern, if used.

**Comment by lavrton** [comment]
@adamdva can you make a demo?

**Comment by adamdva** [comment]
@lavrton It looks like it happens when the hitStrokeHit is set.

https://jsfiddle.net/adamdva/a5qzm14c/12/

**Comment by adamdva** [comment]
Thank you, excellent turn around.
