### ISSUE TITLE
How to change SVG colors?

### ISSUE THREAD

**Issue by enriqueerrando** [konvajs/konva#868]
Hi,

Since a SVG is added to the Konva stage as an image, is there a way to change its colors?

Thanks!

**Comment by lavrton** [comment]
No.

You may try to parse it manually into a set of `Konva.Path` and style them individually.

Or if you want just "fill" with a color (in case you have SVG icon), then you can draw it into an external canvas and use https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation to fill with the color.

**Comment by enriqueerrando** [comment]
Too bad :(

Because of the complexity of the SVGs I'm using would be impossible to use the Konva.Path and because of I need all of them working under the same z-index system, I have to load all of them iside the same canvas.

Is there an alternative way to load a complex SVG to Konva instead of using Konva.Image?

Thanks!

**Comment by lavrton** [comment]
Another workaround is to parse SVG into a DOM element https://stackoverflow.com/questions/24107288/how-to-create-a-svg-dom-element-from-a-string

Then change SVG as you want and set your own colors. Then convert that DOM object into base64 string. Use that string as `src` for an image to use with `Konva.Image`

**Comment by enriqueerrando** [comment]
Would that affect Konva performance?

**Comment by lavrton** [comment]
I don't think so, also usually it is simple to cache `Konva.Image`

**Comment by enriqueerrando** [comment]
Would your suggestion let me change colors after adding SVGs to Konva?

**Comment by lavrton** [comment]
No. You have to change colors BEFORE adding into Konva stage. If you need to update colors - just do that with SVG and replace it inside Konva.

**Comment by enriqueerrando** [comment]
> Then convert that DOM object into base64 string. Use that string as `src` for an image to use with `Konva.Image`

I've been trying to do this several ways, including using an online tool to convert SVG source code to Base64 just to make sure I was coding it right, but keeps throwing a 404 error when Konva tries to get the src.

Any ideas?

Thanks in advance!

**Comment by enriqueerrando** [comment]
Never mind, my mistake!! One second after posting my last comment I got it working, sorry to boder ;)

**Comment by enriqueerrando** [comment]
I've been doing lots of testing based on your suggestion because there was some issues that prevented my exported Adobe Illustrator SVGs to be converted to Base64 with btoa(). 

I'm pretty sure issues came from AI because SVGs downloaded from FontAwesome were correctly converted.

This is the workaround I've come up with, is there a better way?

```javascript
let Base64 = {_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(e){var t="";var n,r,i,s,o,u,a;var f=0;e=Base64._utf8_encode(e);while(f<e.length){n=e.charCodeAt(f++);r=e.charCodeAt(f++);i=e.charCodeAt(f++);s=n>>2;o=(n&3)<<4|r>>4;u=(r&15)<<2|i>>6;a=i&63;if(isNaN(r)){u=a=64}else if(isNaN(i)){a=64}t=t+this._keyStr.charAt(s)+this._keyStr.charAt(o)+this._keyStr.charAt(u)+this._keyStr.charAt(a)}return t},decode:function(e){var t="";var n,r,i;var s,o,u,a;var f=0;e=e.replace(/++[++^A-Za-z0-9+/=]/g,"");while(f<e.length){s=this._keyStr.indexOf(e.charAt(f++));o=this._keyStr.indexOf(e.charAt(f++));u=this._keyStr.indexOf(e.charAt(f++));a=this._keyStr.indexOf(e.charAt(f++));n=s<<2|o>>4;r=(o&15)<<4|u>>2;i=(u&3)<<6|a;t=t+String.fromCharCode(n);if(u!=64){t=t+String.fromCharCode(r)}if(a!=64){t=t+String.fromCharCode(i)}}t=Base64._utf8_decode(t);return t},_utf8_encode:function(e){e=e.replace(/\r\n/g,"n");var t="";for(var n=0;n<e.length;n++){var r=e.charCodeAt(n);if(r<128){t+=String.fromCharCode(r)}else if(r>127&&r<2048){t+=String.fromCharCode(r>>6|192);t+=String.fromCharCode(r&63|128)}else{t+=String.fromCharCode(r>>12|224);t+=String.fromCharCode(r>>6&63|128);t+=String.fromCharCode(r&63|128)}}return t},_utf8_decode:function(e){var t="";var n=0;var r=c1=c2=0;while(n<e.length){r=e.charCodeAt(n);if(r<128){t+=String.fromCharCode(r);n++}else if(r>191&&r<224){c2=e.charCodeAt(n+1);t+=String.fromCharCode((r&31)<<6|c2&63);n+=2}else{c2=e.charCodeAt(n+1);c3=e.charCodeAt(n+2);t+=String.fromCharCode((r&15)<<12|(c2&63)<<6|c3&63);n+=3}}return t}};

let svg_encoded = Base64.encode(svg_data);

let konva_img_src = 'data:image/svg+xml;base64,' + svg_encoded;
```
Thanks in advance!

**Comment by lavrton** [comment]
Can you provide an SVG sample?

I just made this demo for another question on the site: https://jsbin.com/texewubuxu/2/edit?html,js,output

**Comment by enriqueerrando** [comment]
That was exactly where I began testing out but didn't work with AI exported SVGs :(

Here u have a sample SVG so u can test it too:

[ai_svg_sample.zip](https://github.com/konvajs/konva/files/4324555/ai_svg_sample.zip)

Thanks in advance!

**Comment by enriqueerrando** [comment]
I'm starting to think that the issue arises when the SVG has multiple g tags. As soon as I leave the SVG with just one it works, so the issue doesn't even comes from the AI extra header code.

**Comment by lavrton** [comment]
In that case, you can just use a library, that can parse SVG correctly. Similar to https://konvajs.org/docs/sandbox/SVG_On_Canvas.htm

```javascript
const SVG = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 24.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 539.97 519.63" style="enable-background:new 0 0 539.97 519.63;" xml:space="preserve">
    <style type="text/css">
        .st0{fill:#FFEDA5;}
    </style>
    <g id="MANCHA">
        <path class="st0" d="M149.06,324.39c-15.75-10.57-30.22-23.37-44.89-36.62c-11.47-10.36-25.39-22.93-41.77-23.32
                             c-33.28-0.8-38.08,42.91-31.56,65.75c16.72,58.56,66.64,107.66,121.02,130.71c72.67,30.79,157.64,43.86,231.83,11.83
                             c16.4-7.08,30.56-17.5,44.64-28.51c26.44-20.68,46.65-49.85,60.78-80.15c13.69-29.36,19.9-60.78,19.9-93.59
                             c0-24.26-13.04-105.41-54.33-84.45c-18.43,9.36-24.84,33.4-33.35,51.1c-9.65,20.05-20.95,39.73-36.04,56.48
                             c-45.69,50.74-117.34,67.78-182.67,54.16C182.43,343.58,165.09,335.15,149.06,324.39z"/>
    </g>
    <g id="PESTAÑAS">
        <g id="Ilustración_5_1_">
            <path d="M296.94,351.94c0,0,8.53-9.11,7.05-18.11c0,0,8.77,4.98,4.11,18.14L296.94,351.94z"/>
            <path d="M303.46,351.96c0,0,12.11-8.29,12.17-17.29c0,0,7.18,12.4-0.04,17.61L303.46,351.96z"/>
        </g>
        <g id="Ilustración_5_2_">
            <path d="M346.99,338.39c0,0,7.67-8.77,5.89-17.02c0,0,8.48,4.24,4.64,16.6L346.99,338.39z"/>
            <path d="M353.13,338.14c0,0,11.08-8.15,10.76-16.48c0,0,7.29,11.17,0.69,16.27L353.13,338.14z"/>
        </g>
    </g>
</svg>
`;
const url =  'data:image/svg+xml;base64,' + window.btoa(SVG);

var canvas = document.createElement('canvas');
canvg(canvas, url, {
  renderCallback: function() {
    var image = new Konva.Image({
      image: canvas,
      x: 0,
      width: 150,
      height: 150
    });
    layer.add(image);
    layer.batchDraw();
  }
});
```

https://jsbin.com/bividijahi/1/edit?html,js,output

**Comment by enriqueerrando** [comment]
Hi lavrton, thanks for that suggestion too. I did come across that one too, but I'm not a big fan of using JS libraries for every single thing that comes up, I use them when are key parts of my projects only, so for now I'll stick to my workaround ;)

**Comment by bhabgs** [comment]
我不理解，为什么不用类似 fabric.loadSvgByUrl 的实现，并回调中能够拿到所有信息.
I don't understand, why not implement something like fabric.loadSvgByUrl and get all the information in the callback
