### ISSUE TITLE
Wrong typescript signature

### ISSUE THREAD

**Issue by zaerl** [konvajs/konva#869]
[Container<ChildType extends Node>.getClientRect(attrs: any): IRect](https://github.com/konvajs/konva/blob/86f847a70247d2ce22f93b32110e4591be02b50f/src/Container.ts#L458) typescript signature should have an optional argument:

`Container<ChildType extends Node>.getClientRect(attrs?: any): IRect`

and in general all methods that fallback to `config = config || {};`

This is a pretty tedious check to do. I can help you if you want.

**Comment by lavrton** [comment]
You are right. We need many similar fixes. I am happy to apply any related PRs.
