### ISSUE TITLE
stage.find(.name) unexpected result

### ISSUE THREAD

**Issue by dbaikov** [konvajs/konva#87]
I cloned the group, than modified name parameter in the cloned shape. After that tried to use stage.find('.name'); function. the result was that I got result corresponding to old name which was updated.
![konva_find](https://cloud.githubusercontent.com/assets/10244040/8402579/3bab3354-1df1-11e5-97a7-aa6e765cb5ba.png)

**Comment by lavrton** [comment]
I can't reproduce the bug (http://jsbin.com/pupiqucive/edit?html,js,output). It will be nice to have an example.

**Comment by lavrton** [comment]
I will close issue for now. Reopen if required.
