### ISSUE TITLE
[Groups] Is it possible to group images across layers

### ISSUE THREAD

**Issue by Seblor** [konvajs/konva#870]
Hello,

I am working on an app where Konva is used to arrange raster images. Those images can be quite large and are expensive to draw.

To lighten the load when moving those images around, I am using a special layer for moving the selected images, that I add in a group and then move the whole group around.

However, if the user selects all the images (and there can be a lot of them), all the images would be in the dragging layer and the optimization will be lost.

I recently decided to use an other optimization suggested, by spreading the images between multiple layers. But the problem is that by spreading the images in multiple layers when dragging a lot of images, I cannot group them anymore.

So I was wondering if it was possible to add images from multiple layers into a single group ?

**Comment by lavrton** [comment]
> So I was wondering if it was possible to add images from multiple layers into a single group ?

No, it is not possible. 

If you have large images then you can:

1. reduce quality of images with rendering images into an external canvas element with lower size

2. Or caching images with lower `pixelRatio`. You can do that on drag events:

```javascript
image.on('dragstart', () => {
  image.cache({ pixelRatio: 0.5});
});
image.on('dragend', () => {
  image.clearCache();
});
```
