### ISSUE TITLE
Does konva provide a single declare file for use?

### ISSUE THREAD

**Issue by mayeths** [konvajs/konva#871]
I'm using konva to do an algorithm visualization, and avoiding using webpack to make things complex. So I use `konva.min.js` in html, do my work in several typescript files. In this way, Konva is available as a global variable, but missing its definition.

The `types` folder in konva's npm module, however, is using import/export syntax. So typescript won't treat them as global declare files, requiring me to import them manually. Then `tsc` will preserve these import syxtax, which won't work in browser.

`declare var Konva: any` may not be optimal. So does konva provide a single declare file for use without project system?

Anyway, thanks for your work here.

**Comment by lavrton** [comment]
Can you try to import just type, without importing modules itself?

`import type Konva from "konva";`

**Comment by mayeths** [comment]
Thanks, it work like a charm, I will close this issue now.

And anyone like me should:
- use typescript 3.8 or higher to support `import type` syntax
- use `Node` in `compilerOptions.moduleResolution`
- append `DOM` to `compilerOptions.lib`
- convert `Konva` from namespace to type:
```typescript
import type NKonva from "konva"
declare const Konva: typeof NKonva
```
---
My `tsconfig.json`:
```
{
  "compilerOptions": {
    "outDir": "dist",
    "moduleResolution": "Node",
    "lib": ["ES6", "DOM"],
    "target": "ES6"
  }
}
```
