### ISSUE TITLE
Question background image is not loaded

### ISSUE THREAD

**Issue by Naberdz** [konvajs/konva#872]
Hallo,
currently came to a following problem:
have mobile version where user can draw on background ( add markers ).
this works just fine.
We have web side where we need to recreate that what was made by user on mobile.

we export data from mobile to web, background image and json from konva. During export we change path of the background image accordingly.

now when we load it from web, the background image is not visible.

this part of the code we use as in mobile version as in web to load images accordingly
```
var stage;
var layer;
// getting data using ajax and do foreach loop 
var json = JSON.parse(data);
$.each(json, function(i,data){
    var img = new Image();
    img.src = data.image; // image is http://dijkoraad.wemessage.nl/1/tmp/2.png
    img.onload = function(){
        stage = Konva.Node.create(data.json, 'mycanvas'); // for json see bellow
        stage.find('Image').forEach(imageNode => {
            const nativeImage = new window.Image();
            nativeImage.onload = () => {
                imageNode.image(nativeImage);
                imageNode.getLayer().batchDraw();
            }
            console.log(imageNode.getAttr('source'));
            nativeImage.src = imageNode.getAttr('source');
        });
        layer = stage.children[1];
        layer.setZIndex(1);
        stage.setScale({x:1,y:1});
        stage.setX(0);
        stage.setY(0);
        stage.batchDraw();
        $('body').append('<img src="'+stage.toDataURL()+'" />');
        console.log(stage.toJSON());
    };
});
```

here is json which is being loaded:
`{"attrs":{"width":2382,"height":1684,"draggable":true},"className":"Stage","children":[{"attrs":{"hitGraphEnabled":false},"className":"Layer","children":[{"attrs":{},"className":"Image"},{"attrs":{"source":"http://dijkoraad.wemessage.nl/1/tmp/2.png"},"className":"Image"}]},{"attrs":{},"className":"Layer","children":[{"attrs":{"draggable":true,"x":306,"y":303,"transformsEnabled":"position"},"className":"Group","children":[{"attrs":{"radius":20,"stroke":"#231fff","strokeWidth":4,"fill":"#ffffff"},"className":"Circle"},{"attrs":{"text":"1","fontSize":14,"originX":"center","originY":"center","fill":"#231fff","x":-5,"y":-5},"className":"Text"},{"attrs":{"data":"M.91,0H29.09A.91.91,0,0,1,30,.91v243a.88.88,0,0,1-.26.63L15.65,258.86a.9.9,0,0,1-1.3,0L.26,244.52a.88.88,0,0,1-.26-.63V.91A.91.91,0,0,1,.91,0Z","originX":"center","originY":"bottom","x":10,"y":15,"angle":-30,"fill":"#231fff","scaleX":0.15,"scaleY":0.15,"rotation":-30},"className":"Path"}]},{"attrs":{"draggable":true,"x":490,"y":557,"transformsEnabled":"position"},"className":"Group","children":[{"attrs":{"radius":20,"stroke":"#231fff","strokeWidth":4,"fill":"#ffffff"},"className":"Circle"},{"attrs":{"text":"2","fontSize":14,"originX":"center","originY":"center","fill":"#231fff","x":-5,"y":-5},"className":"Text"},{"attrs":{"data":"M.91,0H29.09A.91.91,0,0,1,30,.91v243a.88.88,0,0,1-.26.63L15.65,258.86a.9.9,0,0,1-1.3,0L.26,244.52a.88.88,0,0,1-.26-.63V.91A.91.91,0,0,1,.91,0Z","originX":"center","originY":"bottom","x":10,"y":15,"angle":-30,"fill":"#231fff","scaleX":0.15,"scaleY":0.15,"rotation":-30},"className":"Path"}]}]}]}`

any idea what can be wrong here ?

**Comment by lavrton** [comment]
That's loading images for me just fine:

```javascript
const json = '{"attrs":{"width":2382,"height":1684,"draggable":true},"className":"Stage","children":[{"attrs":{"hitGraphEnabled":false},"className":"Layer","children":[{"attrs":{},"className":"Image"},{"attrs":{"source":"http://dijkoraad.wemessage.nl/1/tmp/2.png"},"className":"Image"}]},{"attrs":{},"className":"Layer","children":[{"attrs":{"draggable":true,"x":306,"y":303,"transformsEnabled":"position"},"className":"Group","children":[{"attrs":{"radius":20,"stroke":"#231fff","strokeWidth":4,"fill":"#ffffff"},"className":"Circle"},{"attrs":{"text":"1","fontSize":14,"originX":"center","originY":"center","fill":"#231fff","x":-5,"y":-5},"className":"Text"},{"attrs":{"data":"M.91,0H29.09A.91.91,0,0,1,30,.91v243a.88.88,0,0,1-.26.63L15.65,258.86a.9.9,0,0,1-1.3,0L.26,244.52a.88.88,0,0,1-.26-.63V.91A.91.91,0,0,1,.91,0Z","originX":"center","originY":"bottom","x":10,"y":15,"angle":-30,"fill":"#231fff","scaleX":0.15,"scaleY":0.15,"rotation":-30},"className":"Path"}]},{"attrs":{"draggable":true,"x":490,"y":557,"transformsEnabled":"position"},"className":"Group","children":[{"attrs":{"radius":20,"stroke":"#231fff","strokeWidth":4,"fill":"#ffffff"},"className":"Circle"},{"attrs":{"text":"2","fontSize":14,"originX":"center","originY":"center","fill":"#231fff","x":-5,"y":-5},"className":"Text"},{"attrs":{"data":"M.91,0H29.09A.91.91,0,0,1,30,.91v243a.88.88,0,0,1-.26.63L15.65,258.86a.9.9,0,0,1-1.3,0L.26,244.52a.88.88,0,0,1-.26-.63V.91A.91.91,0,0,1,.91,0Z","originX":"center","originY":"bottom","x":10,"y":15,"angle":-30,"fill":"#231fff","scaleX":0.15,"scaleY":0.15,"rotation":-30},"className":"Path"}]}]}]}';

const stage = Konva.Node.create(json, 'container');

stage.find('Image').forEach((node) => {
  const img = new Image();
  img.src = node.getAttr('source');
  img.onload = () => {
    node.image(img);
    stage.batchDraw();
  }
})
```


Demo: https://jsbin.com/hicojulite/2/edit?html,js,output

**Comment by lavrton** [comment]
Closing for now. Let know if you still have any issues.

**Comment by Naberdz** [comment]
Yes can be closed, i found my problem.. my container was canvas instead of div.
