### ISSUE TITLE
dragBoundFunc() for arrow keys?

### ISSUE THREAD

**Issue by enriqueerrando** [konvajs/konva#873]
Hi Lavrton,

Is there a way to limit shape movement when triggered from arrow keys? Make dragBoundFunc() work with arrow keys or similar solution?

Thanks!

**Comment by lavrton** [comment]
There is no built-in support for arrow keys. So you have write some code manually to move a shape by keyboard - https://konvajs.org/docs/events/Keyboard_Events.html

So if you have all the code, you can easily add your own limits, very similar to `dragBoundFunc`.

**Comment by enriqueerrando** [comment]
Oks, thanks.

That's what I did, I just wanted to check with u if Konva had a secret sauce for this ;)

Thanks!
