### ISSUE TITLE
MouseEnter and Leave not working correctly if more than 1 Group is inbetween

### ISSUE THREAD

**Issue by beatgutzwiller** [konvajs/konva#875]
Hi there

If have an Issue with mousevents which are bound to groups if there are shapes drawn over it that are more than 1 level deeper in the group history.

https://jsbin.com/cecakotoba/1/edit

There you can see that the inner circle does trigger the mouseleave event even though the mouse is not leaving the outer circle.
Interestingly the click event works correctly.
As soon as you remove the middle group (in this case group1_2) it works as intended:

https://jsbin.com/wuribizemu/1/edit?html,js,console,output

**Comment by lavrton** [comment]
Thanks for the report! The fix will be published soon.
