### ISSUE TITLE
How to get an array (or similar) off all shapes with specific attr value?

### ISSUE THREAD

**Issue by enriqueerrando** [konvajs/konva#877]
Hi,

Let's say I have a total of 10 shapes with a custom attr 'multiselection'. 7 have it set it to false and the rest to true, but I don't know which one is which. Is there a way to get an array (or similar) of all shapes with 'multiselection' set to true without having to 'each' loop through all 10?

Thanks a lot!

**Comment by lavrton** [comment]
No. That is trivial filter function:

```javascript
container.find(child => child.getAttr('multiselection'));
```

**Comment by enriqueerrando** [comment]
I started with that, but didn't work, so I changed to the 'each' loop. But now that u gave me that answer, I rechecked my old code and... I jast had a typo I missed... 

I'm embarrassed, sorry to boder u with that...
