### ISSUE TITLE
Text movment on edit

### ISSUE THREAD

**Issue by nasradin07** [konvajs/konva#878]
HI,

I am currently working on a project that involves some text manipulation. User can change font size,  text style, edit text... For text editing I use the way described here (https://konvajs.org/docs/sandbox/Editable_Text.html). 
The problem is that the text moves on edit. And the worst thing is that text movement is different for text with different fonts, font sizes, rotated text. I have noticed slight text movement on konva site too.
I looked for a way to solve this, but i couldn't find it. 
Does anyone knows a way to solve this?

**Comment by lavrton** [comment]
Unfortunately, it is very hard. Text rendering with HTML (like textarea) and canvas via `Konva` can be different.  You may try to march it manually with some offset (like move textarea by several pixels into required direction). Or even find another UX solution, like a popup with text input.
