### ISSUE TITLE
Incorrect client rect for Line when Stage scale is higher than 1

### ISSUE THREAD

**Issue by RvanderLaan** [konvajs/konva#879]
I am working on a tool where I scale the Stage so that one unit equals one meter, and encountered an issue where the Transformer does not correctly surround my Line objects. 
I found out that the `getClientRect` function of a Line, used to compute the dimensions for the Transformer, does not deal well with a Stage that has a scale value higher than 1.

I created a minimal example [here](https://jsbin.com/josasav/edit?html,js,output) and one in React [here](https://codesandbox.io/s/falling-cookies-mflgo). 
In the second one, the Transformer component is drifting off more extremely as you increase the scale, so I'm suspecting it might be a floating point error somewhere. But that would be weird, as it's even noticeable for scale values in the 1 to 10 range.

**Comment by lavrton** [comment]
Released `konva@4.2.2`. Both demos works ok for me. Thanks for the report.
