### ISSUE TITLE
bug in "Drag and Drop Multiple Shapes" Sandbox / demo

### ISSUE THREAD

**Issue by tylers-porch** [konvajs/konva#88]
http://konvajs.github.io/docs/sandbox/Drag_and_Drop_Multiple_Shapes.html

there appears to be a problem with the demo, the instructions say 
"Drag and drop the shapes or remove them by double clicking or double tapping."

but double clicking seems to only remove the 'top' purple rectangle, no matter which rectangle is clicked. after the purple rectangle is gone, no more rectangles are removed.

looking at the code, it seems like the selected rectangle should move to top whenever it is dragged, that doesn't seem to happen either (in `dragstart`), so perhaps the bug is in `box.moveToTop()` ? 

tested in Firefox, Chrome, Safari on OSX Yosemite

**Comment by lavrton** [comment]
Fixed. Thaks for report.
