### ISSUE TITLE
Vue and Konva: fillPatternRepeat dosen't work

### ISSUE THREAD

**Issue by SchoppAx** [konvajs/konva#880]
Hi guys,

I use konva in my vue application. If I set the fillPatternRepeat to "no-repeat" i get the following:
![grafik](https://user-images.githubusercontent.com/18134256/77675391-2df00d00-6f8d-11ea-82cc-7edeb7bd4c56.png)

The options "repeat-x" or "repeat-y" don't work at all.

For an example please visit your [Sandbox](https://codesandbox.io/s/github/konvajs/site/tree/master/vue-demos/images) and replace the App.vue `v-image` with the following code:
```
<v-rect :config="{
      width: 500,
      height: 500,
      fillPatternRepeat: 'no-repeat',
      fillPatternImage: image
}" />
```

**Comment by lavrton** [comment]
As I can see that is behavior from the Firefox browsers. Other browsers work fine for me. I am not sure what can we do here from `Konva` side.

**Comment by SchoppAx** [comment]
Hi Anton,

thanks for your response.
I combied the `fillPatternImage` with an `fillLinearGradient`. If I set the `fillPatternImage` the background changes from my gradient to white.

Is it possible to use both settings or another `fill` than white?

**Comment by lavrton** [comment]
At the current moment, `Konva` is doing only one type of fill.
