### ISSUE TITLE
react-konva Transformer not working properly

### ISSUE THREAD

**Issue by nesibeyyubov** [konvajs/konva#881]
Hi guys. I have a problem where i have some texts on screen , and i want to resize them with Transformer. It works normal on pc, but on mobile devices it doesn't work. I can only drag and drop texts.

I searched but in the documentation itself there was codesandbox project and even there it was not working

Please help me

**Comment by lavrton** [comment]
Can you post a link to a demo that doesn't work for you?

**Comment by nesibeyyubov** [comment]
> Can you post a link to a demo that doesn't work for you?
https://codesandbox.io/s/github/konvajs/site/tree/master/react-demos/transformer?from-embed

It is demo by react-konva docs.Just turn on responsive mode in devtools or mobile view, you'll see that i cant resize elements.Just i can drag them

**Comment by lavrton** [comment]
Yeah. The demo just listened to only mouse events. Such as `click` and `mousedown`. I added touch events too: `tap` and `touchstart`. The demo will work on mobile too.
