### ISSUE TITLE
Feature request: polyline round corners

### ISSUE THREAD

**Issue by lumenier1** [konvajs/konva#882]
![konva-line](https://user-images.githubusercontent.com/23046497/77752730-2b4af180-7039-11ea-8959-2c331937c418.jpg)
I've tried to implement such result by using `bezier` option either `tension` but it is really painful.
Also it's not a good idea to assemble such figure from lines and arcs or use a path.
It would be nice if new option appeared for smoothing polyline corners like this:
```
var line = new Konva.Line({
   points: [0,0, 90,0, 100,10, 100,100, 200,100, 300,0],
   stroke: 'red',
   strokeWidth: 5,
   lineCap: 'round',
   lineJoin: 'round',
   bezier: true,
   roundedCorners: true,
   cornerRadius: 5
});
```

**Comment by lavrton** [comment]
Thanks for your suggestion. I don't think I want to include such functionality into the core codebase. Such a function may require a lot of code to cover all edge cases.

If you want such like you can just:
1. Create custom shape and draw line manually with lines and arcs
2. Define `Konva.Path` and generated the required SVG path `data` for it.
