### ISSUE TITLE
Video doesn't load with Video On Canvas example

### ISSUE THREAD

**Issue by seta-hungDang** [konvajs/konva#883]
Hi guys,

I ran into this issue when trying to convert [the video example](https://konvajs.org/docs/sandbox/Video_On_Canvas.html) to React Hook

The video which is Big Bunny video constantly returned either 429 error code or 206. In both cases, the video doesn't shows.

I have record a screenshot here for reference. Thank you so much!
![image](https://user-images.githubusercontent.com/50004479/78352202-2b676600-75d2-11ea-9397-465950e850ab.png)

**Comment by lavrton** [comment]
I updated the demo with another link and better messages.

**Comment by seta-hungDang** [comment]
Thank you so much! It was quite funny because I tried my video and the same thing happened but yours is working well. Anyway this would do. Thanks!
