### ISSUE TITLE
imageSmoothingEnabled property does not work after Stage is resized.

### ISSUE THREAD

**Issue by luisbc92** [konvajs/konva#884]
[Example project](https://codesandbox.io/s/kova-imagesmoothingenabled-demo-k3v61) demonstrating the issue.

Note that setting the property again after resizing the stage does not fix the issue.

Thanks!

**Comment by lavrton** [comment]
Fix. Will be published later. Probably with a major release update.

**Comment by luisbc92** [comment]
Excellent. Thank you!
