### ISSUE TITLE
mousedown & click event not fired on iPadOS when clicking shape

### ISSUE THREAD

**Issue by wikywin** [konvajs/konva#886]
dear  lavrton.
stage.on('click', function(e){});

if a shape is added to stage, and I tap stage on iPadOS.  click event will be fired properly.
but if I tap on that shape,  click event will not be fired!
please help me figure out where's problem?

btw:  if i run above code on PC or iOS, everything is OK

**Comment by lavrton** [comment]
On iPadOS with a trackpad?

I don't expect that `mousedown` and `click` should work here. You need to use `touchstart` and `tap` events for touch devices.

**Comment by wikywin** [comment]
> On iPadOS with a trackpad?
> 
> I don't expect that `mousedown` and `click` should work here. You need to use `touchstart` and `tap` events for touch devices.

safari already request desktop webpage on iPadOS, I debug into code to find that click event will be fired properly when I use mouse on iPad, but If i use finger, tap event will be fired.
stage.on('click tap', function(e){})  will fix my problem.   thx a lot!
