### ISSUE TITLE
Optionally exclude filter canvas from cache.

### ISSUE THREAD

**Issue by raphael-papazikas** [konvajs/konva#887]
Hello, 

in my case, i dont use any filters and after calling the cache method there is an empty canvas with the same memory size as the main scene canvas. 

Could you please create an option for this? 
A workaround could be, to just set the 
https://github.com/konvajs/konva/blob/865d6c7618e932980984a658ac30fac23cc2ddae/src/Node.ts#L390-L394
to:
```javascript
cachedFilterCanvas = new SceneCanvas({
  pixelRatio: 0,
  width: 0,
  height: 0
}),
```
if the option is passed to the cache method.

**Comment by lavrton** [comment]
That makes sense. I will publish the update later.

Thanks for the suggestion!
