### ISSUE TITLE
Rotation Snap Tolerance

### ISSUE THREAD

**Issue by kaptenpeter** [konvajs/konva#888]
I was looking into the rotationSnapTolerance feature added a while back. 

My goal was to snap the transform rotation to 90 degrees of rotation or, rather 0, 90, 180, 270 degrees.

I tried using this

        rotationSnaps: [0, 90, 180, 270],
        rotationSnapTolerance: 45,

And it works for 0-270 degrees of rotation, but breaks between 270 and 0 degrees.

I have made an example here https://jsfiddle.net/ru5L7ze2/

There is of course another way of doing it as shown here  https://jsbin.com/xabegiseti/3/edit?js,output

**Comment by kaptenpeter** [comment]
After reading the transformation code I see that my use case is probably an edge case. But the problem still existst when using moderate tolerances.


I have run some tests on different angle difference calculation methods and come up with a possible problem in the current implementation. These are some simplified examples and not taken directly from the codebase.

```
// New function
function angleDiff(a,b) {
	return Math.PI - Math.abs(Math.abs(a - _degToRad(b)) - Math.PI); 
}
```

```
// Old function
function angleDiff2(a,b) {
	return Math.abs(a - _degToRad(b)) % (Math.PI * 2);
}
```
If you test these for the full 360 degrees of rotation you will see that the distribution of snaps will differ. (This is with standard 5 degrees of snap tolerance). The numer denotes the number of angles that will snap to specified angle.

```
{
  "newDistribution": {
    "0": 11,
    "90": 11,
    "180": 11,
    "270": 11
  },
  "oldDistribution": {
    "0": 6,
    "90": 10,
    "180": 11,
    "270": 11
  }
}
```

**Comment by kaptenpeter** [comment]
Even if using the second approach there is an issue

```
var tr = new Konva.Transformer({
  boundBoxFunc: function(oldBoundBox, newBoundBox) {
    const closesSnap = getSnapRotation(newBoundBox.rotation);
    const diff = closesSnap - oldBoundBox.rotation;
    if (Math.abs(diff) > 0) {
      return rotateAroundCenter(oldBoundBox, diff);
    }
    return oldBoundBox;
  }
});
```
newBoundBox.rotation is negative when rotating counter-clockwise but if you snap to 360 instead of 0, it will work.


```
function getSnapRotation(rotation) {
  var el = document.getElementById('output');
  el.textContent = rotation;
  if (rotation < 0) {
    if (rotation < -45) {
    return 360;
    }
  }
  else if (rotation >= 45 && rotation < 135) {
    return 90;
  } else if (rotation >= 135 && rotation < 225) {
    return 180;
  } else if (rotation >= 225 && rotation < 315) {
    return 270;
  } else {
    return 0;
  }
}
```

https://jsbin.com/ramofutowu/1/edit?js,output

**Comment by lavrton** [comment]
That is a very good report and good comments.

I made some fixes for snap calculations. It should work ok now.
