### ISSUE TITLE
Drag/Wheel performance issues with multiple rectangles

### ISSUE THREAD

**Issue by akohring** [konvajs/konva#890]
Konva Version: 4.2.2

I am noticing significant performance differences with stage drag and wheel events when using Konva.Rect vs. Konva.Shape with a sceneFunc to draw rectangles.  Ideally, I would like to be able to draw a few hundred rectangles with shape settings that include opacity, stroke, stroke width, and corner radius on a draggable/zoomable stage with hit detection.  The following examples demonstrate the performance issues.

1. Konva.Rect.  When using a desired opacity of 0.5, there are significant performance issues with drag/wheel events.  If the opacity is set to 1 (not desired), the performance issues are resolved.
https://jsfiddle.net/t4nsxgd9/1/

2. Konva.Shape with sceneFunc.  When using a Konva.Shape with a sceneFunc, I am able to use the desired opacity setting, however, the stoke introduces significant performance issues.  If the stroke is set to null (not desired), the performance issues are resolved.
https://jsfiddle.net/g9xj1t8r/2/

Why does the Konva.Rect have performance issues with the opacity, but not the stroke, and the Konva.Shape with a context rectangle have performance issues with the stoke, but not the opacity?  Is it possible to draw several rectangles with opacity, stroke, stroke width, and corner radius on a draggable/zoomable stage without performance issues?  I have read through the Konva performance tips list, and the problem seems to be related to the buffer canvas.  Setting perfectDrawEnabled to false resolves the performance issue, but the darker line intersection is not desired.

**Comment by lavrton** [comment]
As you mentioned, the combination of "stroke + opacity" triggers buffer canvas rendering (which is very slow).

So you have to set `perfectDrawEnabled: false`. If you don't want overlap of fill and stroke, then you have to draw stroke manually with small padding (or reduce fill area): https://jsfiddle.net/hgxzw6n5/


But even better, if you have such a static grid, it will be much better to cache a whole layer (or canvas).
