### ISSUE TITLE
Proposal: Introduce a "onUpdate()" callback in Konva.Tween

### ISSUE THREAD

**Issue by m1h4** [konvajs/konva#891]
Currently, tweens have a onFinish() and a onReset() callback, but there are use-cases where an onUpdate() callback would be extremely helpful. This would get called after a tween did its prop update.

This can be used for a tween to also drive other state updates that need to happen that are not necessarily related to the node that the tween is operating on.

**Comment by lavrton** [comment]
Probably. Does anyone want to make a pull request?

**Comment by m1h4** [comment]
Will setup a test environment locally and push one as soon as I can.

**Comment by lavrton** [comment]
Resolved by merged PR.
