### ISSUE TITLE
Anti-aliasing Canvas in Konva.Image

### ISSUE THREAD

**Issue by goodwin74** [konvajs/konva#892]
I load canvas into Konva.Image. Large canvas, and when I shrink it in Konva Stage, rough pixelation defects appear
How to fix it? maybe you need to enable anti-aliasing?

**Comment by lavrton** [comment]
Can you show what kind of `pixelation`? anti-aliasing is enabled by default.

**Comment by goodwin74** [comment]
> Can you show what kind of `pixelation`? anti-aliasing is enabled by default.

This is clearly visible if you take a high-quality image with text and reduce its scale. Pixelization appears on the edges of text and objects.

Example (Text VISION has torn edges of pixels):
![Безымянный](https://user-images.githubusercontent.com/15101984/79848658-0c3a4800-83ca-11ea-8eaa-f789b3fa4110.png)

**Comment by lavrton** [comment]
That is how browser rendering works. 

The solution is not simpler. I don't think we should do anything special from `Konva` side. You have to make scaling manually in such a case.

For more info take a look here: https://stackoverflow.com/questions/18922880/html5-canvas-resize-downscale-image-high-quality
