### ISSUE TITLE
How can I get the updated children position when group is transformed?

### ISSUE THREAD

**Issue by yaswanthakula** [konvajs/konva#893]
Thank you for submitting an issue!

Please make sure to check current open and closed issues to see if your question has been asked or answered before.
If you have just a question (not a bug or a feature request) it is better to ask it in [Stackoverflow](http://stackoverflow.com/questions/tagged/konvajs).

If you have a bug, please, try to create a reproducible example with jsfiddle (or any similar service).
You can use [this JSBIN](https://jsbin.com/tekehizuta/1/edit?html,js,output) as a template.

**Comment by lavrton** [comment]
`const attrs =  shape.getAbsoluleTransform().decompose()`.

Also with the last version `konva@5.0.0`, you can transform several nodes without grouping.

**Comment by yaswanthakula** [comment]
Thank much @lavrton 
It works like a champ :)

**Comment by fix777** [comment]
```js
const top = stage.findOne('#some-top-node');
const attrs = shape.getAbsoluleTransform(top).decompose();
```

For anyone who reached here, this is some kind of solution on top of @lavrton 's answer.
IF you have some `top` node(kind of `Layer`) which transformed, you may pass it into `getAbsoluleTransform(top)` API, and you'll get the proper position.
