### ISSUE TITLE
Bug: Transformer wrong size after scale stage after (v5)

### ISSUE THREAD

**Issue by raphael-papazikas** [konvajs/konva#894]
The Transformer has wrong size, while zooming the stage.
This issue appears only after the v5 release.

Initial: 
![image](https://user-images.githubusercontent.com/33499602/79983609-52fe6f80-84a8-11ea-801b-6ef1601c58bb.png)

After zoom in:
![image](https://user-images.githubusercontent.com/33499602/79983638-5db90480-84a8-11ea-8077-57755875a596.png)

Only after transforming the shape, the size and position of the transformer is correct again.

**Demo:** https://jsbin.com/yobudus/edit?html,js,output

**Demo with v4.2.2:** https://jsbin.com/mihofel/edit?html,js,output

**Comment by lavrton** [comment]
Thanks for the report. I will publish the fix soon.
