### ISSUE TITLE
Transformer position and rotation origin.

### ISSUE THREAD

**Issue by m-inan** [konvajs/konva#895]
Hello, I am doing an annotate operation using `React-Konva` and it works very well. thank you for that. However, I cannot progress on one subject. While doing my drawing, I enter the text on the one hand, and I have to rotate it. I use `Transformer` for this.
```javascript
import React, { Fragment, useEffect, useRef } from 'react'
import { Text, Transformer } from 'react-konva'

import { useStore } from './store'

export default function ({ id, text }) {
  const { regions, selected, setRegions, setSelected } = useStore()

  const { x, y, value, color, rotation, fontSize } = text

  const TextRef = useRef()
  const TransformRef = useRef()

  const onDragEnd = ({ target }) => {
    setRegions(
      regions.map((item) => {
        if (item.id === id) {
          item.text = {
            ...item.text,
            x: target.x(),
            y: target.y(),
            width: target.width(),
            height: target.height(),
          }
        }

        return item
      })
    )
  }

  const onTransformEnd = () => {
    const node = TextRef.current

    const width = node.width()
    const height = node.height()

    const x = node.x()
    const y = node.y()
    const rotation = node.rotation()

    const originX = x + width / 1.3
    const originY = y + height / 1.3

    setRegions(
      regions.map((item) => {
        if (item.id === id) {
          item.text = {
            ...item.text,
            x, // <= it changes when this is rotation
            y, // <= it changes when this is rotation
            rotation,
            originX,
            originY,
          }
        }

        return item
      })
    )
  }


  const isSelected = id === selected

  useEffect(() => {
    if (isSelected) {
      TransformRef.current.setNode(TextRef.current)
      TransformRef.current.getLayer().batchDraw()
    }
  }, [isSelected])

  return (
    <Fragment>
      <Text
        draggable
        name="region"
        x={x}
        y={y}
        text={value}
        fill={color}
        ref={TextRef}
        rotation={rotation}
        fontSize={fontSize}
        onDragEnd={onDragEnd}
        onTransformEnd={onTransformEnd}
      />

      {isSelected && (
        <Transformer
          ref={TransformRef}
        />
      )}
    </Fragment>
  )
}
```

However, when I want to show this in react native with svg, the article stays above according to the `y` position. I achieved this with a temporary solution like `y = y + height / 1.3`. However, I do not work in this way for rotate operation, though. React Native Svg
```javascript
// if the x and y values remain constant it works
<G
    transform={{
        rotation: rotation, // 90 - 180
        originX: x + width / 2,
        originY: y + height / 2,
    }}>

    <Text
        x={x}
        y={y}
        fill={'#fff'}
        fontSize={fontSize}
        textAnchor="start"
    >
        {value}
    </Text>
</G>

```
Here I see the problem `x` and` y` values ​​change as the rotation is done and this deflects the `origin` value from the center.
If I change only `rotation` without changing` x` and `y` values, it works as I expected.

What path should I follow here. Should I edit the data according to React Native Svg on the drawing side? Is there an easy way to do this?

I do not think there is an error for this convention, but when I try to run it directly in svg, there is an inconsistency. I'm sorry you're asking here.

**Comment by lavrton** [comment]
In `Konva`, a text's position is a position of its top-left corner (similar to rectangle). By default, SVG may work differently, I am not sure here. You may need to set `alignment-baseline` to `top` https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline

**Comment by m-inan** [comment]
I understand. I have a temporary solution for this. Rotation of the  `transformer`, which is of notable importance, does not change the values of `x` and` y`. If I leave it still working on the `svg` side. However, it is not as expected on the side of `Canvas`. Is there a way to equalize the values of `x` and` y` in this regard. Or how can I calculate the originX and originY values most accurately? The values of `rotation` and` x-y` which come with `Transformer`.

**Comment by m-inan** [comment]
I found this for transform inside. But I couldn't fully understand. I think adding value up to Rotation for `x` and` y`. These values added on the svg side cause deviations. What is the calculation formula of reversing this for svg? If you have a great help in this matter, it will be useful.

```javascript
// /konva/src/shapes/Transformer.ts 
...
function getCenter(shape: Box) {
  return {
    x:
      shape.x +
      (shape.width / 2) * Math.cos(shape.rotation) +
      (shape.height / 2) * Math.sin(-shape.rotation),
    y:
      shape.y +
      (shape.height / 2) * Math.cos(shape.rotation) +
      (shape.width / 2) * Math.sin(shape.rotation)
  };
}

function rotateAroundPoint(shape: Box, angleRad: number, point: Vector2d) {
  const x =
    point.x +
    (shape.x - point.x) * Math.cos(angleRad) -
    (shape.y - point.y) * Math.sin(angleRad);
  const y =
    point.y +
    (shape.x - point.x) * Math.sin(angleRad) +
    (shape.y - point.y) * Math.cos(angleRad);
  return {
    ...shape,
    rotation: shape.rotation + angleRad,
    x,
    y
  };
}

function rotateAroundCenter(shape: Box, deltaRad: number) {
  const center = getCenter(shape);
  return rotateAroundPoint(shape, deltaRad, center);
}
```

**Comment by lavrton** [comment]
I am not sure why do you need `originX` and `originY` and group here.

By default, `Konva.Text` is using top-left corner for `{x, y}` position. Just to the same for SVG.

**Comment by m-inan** [comment]
Yes, there is no problem by default, everything works.
But when rotating using `Transformer`. The `x` and` y` positions are also changing. This causes the origin values to change every time a rotation is made. If this remains constant while freezing in svg, the turn remains in the center.

I have a two example

Example use in this document. Here `x` and `y` change with transform.
https://codesandbox.io/s/misty-leaf-ixt55?file=/src/Playground.js

I did not include the x and y values that change with transform here. It works for svg, but when I use it again for Konva, it doesn't work correctly.
https://codesandbox.io/s/stupefied-frost-ejmgy?file=/src/Playground.js

I may not have fully understood the problem. But there is only this problem in the drawing editor I wrote in my project, which is about to end. If I can solve this, I saved the day. If there is no solution, I will have to rewrite it with a different library. Thanks in advance for the answers.

**Comment by lavrton** [comment]
This works for me: https://codesandbox.io/s/konva-and-svg-demo-jx7sj?file=/src/Playground.js

**Comment by lavrton** [comment]
> But when rotating using Transformer. The x and y positions are also changing

Right, because the top-left corner of a text is moving, So `{x, y}` is changing.

**Comment by m-inan** [comment]
This was the calculation formula I was looking for. Thanks for helping.
