### ISSUE TITLE
Transformer handles moving draggable stage

### ISSUE THREAD

**Issue by uoa7** [konvajs/konva#896]
If the stage is draggable and a node is attached to a transformer, the transformer handles move the stage instead of scaling/rotating.

This bug was reported and fixed in v4.0.4 - see https://github.com/konvajs/vue-konva/issues/71

It seems to be have been reintroduced in v5.0.0

**Comment by lavrton** [comment]
Fixed with `konva@5.0.1`. Thanks for the report.
