### ISSUE TITLE
A debugger GUI for konva [Feature request]

### ISSUE THREAD

**Issue by Ivanca** [konvajs/konva#897]
It would be great to have a visual debugger, maybe a debug mode that adds an external panel where in a folder/file structure one can click into existing elements, check their properties, inspect their state, perhaps as a Chrome extension would work as well (that one can add a panel to the devtools)

![image](https://user-images.githubusercontent.com/907138/80298269-19e82880-8750-11ea-8de5-751cf14b4c35.png)

There is a jquery plugin one may use for such structures: https://www.jstree.com/demo/

**Comment by lavrton** [comment]
I have no resources to develop that. I am usually just inspecting `Konva.stages` in the console.

**Comment by santiq** [comment]
@lavrton Sorry for reviving old issues. 

Can you explain a little more about inspecting `Konva.stages`? What sort of info can we get from there?

Also, I think a GUI debugger could be very useful

**Comment by lavrton** [comment]
```js
console.log(window.Konva.stages);
```

**Comment by maitrungduc1410** [comment]
Hi everyone, I created a Konva devtool here: https://github.com/maitrungduc1410/konva-inspector

it supports all Konva objects, cross browser (Chrome, Firefox, Edge), live editing, multi stages, dark theme,...

Please have a try, feedback is welcome

**Comment by lavrton** [comment]
@maitrungduc1410 that really looks cool!

**Comment by MatteoGauthier** [comment]
Thanks a lot @maitrungduc1410 ! This will save a lot of time !

**Comment by ZeeshanAhmadKhalil** [comment]
I am using React so keeping JSON to render shapes in the local state and using [React Dev Tools](https://chromewebstore.google.com/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?pli=1) is useful for debugging instead of `console.log`
