### ISSUE TITLE
Background for stage/infinite background

### ISSUE THREAD

**Issue by mikob** [konvajs/konva#898]
This is a feature request.

I need to have a grid like background on a draggable stage. I tried using css, but then the background does not move when I click and drag to pan around the stage. 

Using a rectangle or other shape within the stage wouldn't work because those can't have infinite dimensions AFAIK.

**Comment by lavrton** [comment]
I don't think we need to have such a feature in Konva core. Just draw that grid manually with CSS or shapes.

You can move that grid on every `dragmove` event of the stage.

We have a demo for `react-konva`, but you can rewrite it for pure Konva https://codesandbox.io/s/react-konva-infinite-grid-kkndq

**Comment by mikob** [comment]
@lavrton oh, didn't see that demo. That's perfect! Thanks for the quick reply.
