### ISSUE TITLE
Find orthogonal path between points

### ISSUE THREAD

**Issue by yaswanthakula** [konvajs/konva#899]
Hi,
I have few groups with an image and two rect shapes which can be transformed.
.
I want to find orthogonal path from one rect shape of a group to another rect shape of another group.
How to find the path?
And path should not get overlapped with the group.

Thanks

**Comment by lavrton** [comment]
That is not part of `Konva` library. You have to find your own implementation for "pathfinding algorithms". Probably this https://qiao.github.io/PathFinding.js/visual/
