### ISSUE TITLE
Event bubbling between objects

### ISSUE THREAD

**Issue by mikepombal** [konvajs/konva#90]
I know there is event bubbling happening between an object and the layer where it is drawn. My question is it is possible to have an event of an object to be propagated to another event which is draw just bellow?

I created a [JSFidlle](http://jsfiddle.net/ad221k05/1/) to have a better explanation of my problem.

**Comment by lavrton** [comment]
Currently you can not do this.
Only one way is manually check intersections with all shapes on layer and trigger event. `circle.fire('click', event)`
