### ISSUE TITLE
how to save canvas data about image for knova 

### ISSUE THREAD

**Issue by shuai4983958** [konvajs/konva#901]
solution：
  const canvas = document.createElement('canvas');
    canvas.width = this.stage.width();
    canvas.height = this.stage.height();

 this.image = new Konva.Image({
      image: canvas,
      x: 0,
      y: 0
    });
    this.layer.add(this.image);
    this.stage.draw();

 const json = this.stage.toJSON();

result：

 it is empty for json

**Comment by lavrton** [comment]
`Konva` do not serialize functions, images, or other "complex" objects.

Please read this for best tips: https://konvajs.org/docs/data_and_serialization/Best_Practices.html#What-is-the-best-way-to-save-load-full-stage-content-and-how-to-implement-undo-redo

Or just manually save canvas content as base64 into any custom property of `Konva.Image` and then load from it.

```
// save
image.setAttr('_src', canvas.toDataURL());

// load later:
const url = image.getAttr('_src');
const canvas = document.createElement('canvas');
// draw url into canvas manually
// then
image.image(canvas);
```
