### ISSUE TITLE
Height of class properties list in the API documentations

### ISSUE THREAD

**Issue by rypskar** [konvajs/konva#903]
If you open any class in the API-documentation you will see it is not possible to scroll down and see the last element in the class property list to the right (z-index). Example https://konvajs.org/api/Konva.Circle.html

The CSS for #toc has top: 162px; and max-height: calc(100% - 72px);, so the list will be 90px longer than the page. Changing max-height to calc(100% - 162px); should fix it.

Tested on Firefox and Chrome

**Comment by lavrton** [comment]
Fixed. Thanks for the report!
