### ISSUE TITLE
Stage still initializes mouse events when configuration listening:false

### ISSUE THREAD

**Issue by adamdva** [konvajs/konva#907]
The Stage constructor calls this._bindContentEvents(); even when initial configuration specifies listening:false

We have found (in chrome with hardware acceleration on) that the getImageData call can take up to 700ms+  This results in warnings from chrome, as well as performance issues.

We are having to separately handle mouseover events, but still getting the performance hit, since the mousemove events are still being initialized in konva.

Can the mouse events be dependent on the listening configuration value?

**Comment by lavrton** [comment]
`700ms+` is super long. And that is a strange browser's behavior. 

And I am not sure we should bind/unbind events on `listening` change. Probably the simplest solution is just monkey-patch the stage.

```
stage._mousemove = () => {};
```

**Comment by nathan-muir** [comment]
@adamdva if you use `FastLayer` instead of `Layer`, it will skip drawing the hit layer, and wont call getImageData on events.

**Comment by nathan-muir** [comment]
Does `new Konva.Stage({ listening: false })` actually prevent any interaction?

Can you try, using `new Konva.FastLayer()` instead of `new Konva.Layer()`

or, `layer.disableHitGraph()` should do the trick too.

**Comment by lavrton** [comment]
> `layer.disableHitGraph()` should do the trick too

Right. That is the best solution I think.

> new Konva.Stage({ listening: false }) actually prevent any interaction

Not really. I think current `listening` and `hitGraphEnabled` flags are confusing and we need to simplify them to just `listening`, so `stage.listening(false)` will prevent all interactions.

**Comment by adamdva** [comment]
Thanks for the suggestions. I'm trying disableHitGraph() to try to mitigate the issue, and it seams to be helping.
It's a strange issue, that seams to be related to the chrome hardware acceleration (it's much lessened when I turn it off, but that's not a viable option for most.)
On a refresh, I see chrome issue the following:

[Violation] 'mousemove' handler took 683ms

My code does not utilize any mousemove, mouseover, drag, etc listeners from konva.
If you have any other suggestions, they would be appreciated.
Thanks for a great product.

**Comment by lavrton** [comment]
If you use `disableHitGraph` then `mousemove` should take so long.

If you still have that issue, you need to find what takes so long.
