### ISSUE TITLE
Submit Typescript definitions to DefinitelyTyped

### ISSUE THREAD

**Issue by BasitAli** [konvajs/konva#91]
Hi,

I was giving a try to this library but failed to do so as I am using tsd from DefinitelyTyped and it was missing the typings for this library. Also the resources folder was ignored by bower.json so I had to manually copy the .ts file to my project. Since you are providing an official definition, are you interested in pushing your definition to DefinitelyTyped?

Reference: https://github.com/borisyankov/DefinitelyTyped, http://definitelytyped.org/guides/contributing.html

Thanks,
Basit

**Comment by lavrton** [comment]
Sure. Will do it soon.

**Comment by lavrton** [comment]
`DefinitelyTyped` is a mess. I don't want to add definition to it. It will be hard to maintain it in other repo.

Also typescript supports definition from npm packages. Next version of Konva will have konva.d.ts in package.

Feel free to add konva.d.ts into `DefinitelyTyped` if you are interested.

**Comment by FabianTe** [comment]
> Also typescript supports definition from npm packages.

I know this is off topic, but i can't find any help online. How do i use the konva.d.ts file in typescript?
