### ISSUE TITLE
Konva.Transformer doesn't work in Firefox

### ISSUE THREAD

**Issue by danielcrisp** [konvajs/konva#912]
I've been trying to get the `Konva.Transformer` to work in my app when using Firefox (v77 Developer Edition, running on MacOS) but I found that the event would always be triggered on the `Stage` rather than the `Transformer`, and as a result you can't transform the selected node.

I've just tried these two official examples and I've found that neither of them work in my Firefox too, so I don't think it is a problem with my code:

https://konvajs.org/docs/select_and_transform/Transformer_Styling.html
https://konvajs.org/docs/select_and_transform/Transform_Events.html

There are no errors in the console.

Chrome, Safari and Brave are all fine. I've tested with v6 and v5.0.2

I've checked the issues and haven't found any relevant mentions of issues with Firefox so I wonder if this is a recent problem?

**Comment by lavrton** [comment]
Hmmm. Works ok for me in Firefox, Mac.

**Comment by danielcrisp** [comment]
Just tried with my other computer running Developer Edition v75 and it worked. I updated that to v77 and it stopped working...

**Comment by ines** [comment]
I can confirm that there must have been _some_ change in the latest update to Firefox Developer Edition / Beta that caused `onClick`, `onMouseOver` and related events to stop registering. Most likely [Firefox 77](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77), although I couldn't find anything in the release notes that looks related.

Here's a super minimal reproducible example of a rect with a click handler:
https://codepen.io/ines/pen/eYpbMJz

This works pretty much everywhere, except for the latest FF version.

**Comment by lavrton** [comment]
It is something with colors on the canvas. And it is a very bad issue.

`Konva` is using external canvas for hit graph to detect events on shapes. (more about the approach here https://lavrton.com/hit-region-detection-for-html5-canvas-and-how-to-listen-to-click-events-on-canvas-shapes-815034d7e9f8/)

And colors that `Konva` tells a browser to draw and what is actually drawing don't match.

**Comment by lavrton** [comment]
Simplest demo: https://jsbin.com/jaqaqeboro/edit?js,console,output

**Comment by lavrton** [comment]
I reported to firefox team: https://bugzilla.mozilla.org/show_bug.cgi?id=1639574

**Comment by danielcrisp** [comment]
Very strange. My browser reports `235, 51, 35` instead of `255, 0, 0`.

**Comment by lavrton** [comment]
FF 77 just was released. And I don't see that bug here.

Can anyone confirm that on other versions? I am not sure how FF deploy patches.

**Comment by danielcrisp** [comment]
I've just updated my Developer Edition to 78 and now your jsbin reports the correct values and the demos work fine. 

Looks like they've fixed it then! 

Thanks for investigating.
