### ISSUE TITLE
Text reverse scaling with boundBoxFunc

### ISSUE THREAD

**Issue by matcic** [konvajs/konva#913]
Just a question related to [this previous issue](https://github.com/konvajs/konva/issues/631):

I checked out [this example](https://jsbin.com/xeverebeki/1/edit?html,js,output) which works quite well in most cases. If you keep scaling the group past the size of the text though you'll see some weird behaviour.

What I would like to do is to use the transformer's `boundBoxFunc` to set the minimum width and height of the group to the dimensions of the text. I tried to use `getClientRect` with `relativeTo` to calculate and set these minimum values but the thing is that the `transform` event is still being called and I couldn't find a proper way to fix this problem that would give me a predictable result.

Any help would be greatly appreciated!
Thanks

**Comment by lavrton** [comment]
For now it is hard to use `boundBoxFunc` to set limits. We have this demo https://konvajs.org/docs/select_and_transform/Resize_Limits.html#page-title, but it is far from perfect.

I think that we should add `absoluteMinWidth`, `absoluteMaxHeight` etc.

**Comment by matcic** [comment]
@lavrton thanks, I had seen that demo but it wasn't quite what I needed. In the end I was able to come up with an acceptable solution with the following though:

```javascript
tr.on('transform', () => {
  const absScale = text.getAbsoluteScale();
  text.scaleX(text.scaleX() / absScale.x);
  text.scaleY(text.scaleY() / absScale.y);
})

tr.boundBoxFunc(function (oldBox, newBox) {
  const textBoundingBox = text.getClientRect({
    skipTransform: true,
  });
  const newWidth = Math.abs(newBox.width);
  const newHight = Math.abs(newBox.height);
  const isWidthTooSmall = newWidth < textBoundingBox.width;
  const isHeightTooSmall = newHight < textBoundingBox.height;
  const box = {
    x: oldBox.x,
    y: oldBox.y,
    rotation: newBox.rotation,
    width: isWidthTooSmall ? textBoundingBox.width : newWidth,
    height: isHeightTooSmall ? textBoundingBox.height : newHight,
  };
  if (isWidthTooSmall || isHeightTooSmall) {
    return box;
  }
  return {
    ...newBox,
    width: newWidth,
    height: newHight,
  };
});
```

I'll just leave this for future reference, I will keep an eye on the framework and consider solving this issue in a different way if `absoluteMinWidth` and `absoluteMaxHeight` end up to be added to Konva's `Transformer`.
