### ISSUE TITLE
Cropping of svg

### ISSUE THREAD

**Issue by nasradin07** [konvajs/konva#914]
I have two problems with cropping of svgs.  
If i have svg, with attributes, say of width: 200 and height: 200 and if i give it cropWidth and cropHeight of 100 I sometimes get an empty image.
Before crop
<img width="163" alt="Screenshot 2020-05-29 at 11 07 24" src="https://user-images.githubusercontent.com/28790677/83242568-e9efd300-a19c-11ea-996c-2a7a136d7212.png">
After crop
<img width="190" alt="Screenshot 2020-05-29 at 11 07 48" src="https://user-images.githubusercontent.com/28790677/83242598-f542fe80-a19c-11ea-979d-b2beebe456d5.png">

And also if I sometimes get image, the cropped part changes with stage width and stage height
At start:
<img width="1294" alt="Screenshot 2020-05-29 at 11 00 29" src="https://user-images.githubusercontent.com/28790677/83242806-494de300-a19d-11ea-890b-532a7af51b01.png">
When stage width and height changes.
<img width="1131" alt="Screenshot 2020-05-29 at 11 00 39" src="https://user-images.githubusercontent.com/28790677/83242893-6d112900-a19d-11ea-9084-f15c0e614d85.png">

.

**Comment by lavrton** [comment]
Can you make a demo, please?

**Comment by lavrton** [comment]
I am not sure we can do anything here from `Konva` side. You may need to fix SVG manually.

Take a look here: https://github.com/konvajs/konva/issues/677#issuecomment-504596837

**Comment by nasradin07** [comment]
I managed to solved it in that way. Thank you.
