### ISSUE TITLE
Width change not taken into account (height is OK, though)

### ISSUE THREAD

**Issue by djcaesar9114** [konvajs/konva#915]
When I set a width for my Konva stage, it doesn't seem to be taken into account:

https://codesandbox.io/s/vue-template-4g1b7?file=/src/App.vue

When you change the height, everything works fine, but the width seems stuck to the width of the page.

Thanks for this wonderful tool, Konvais really great!

**Comment by lavrton** [comment]
That is because your container has `display: block` in styles (default for `div`).

You may set it to `display: inline-block`.

**Comment by djcaesar9114** [comment]
Thanks!
