### ISSUE TITLE
Unable to plot {x1, y1, x2, y2} coordinates with boundBoxFunc in new Transformer

### ISSUE THREAD

**Issue by eoghanmccarthy** [konvajs/konva#916]
I use `boundBoxFunc` to keep shapes on the canvas when transforming and I also have to store the box data as `{x1, x2, y1, y2}`. This was simple to calculate with the previous Transformer where the width and height values became negative values if the shape was flipped on either axis, however, with the new Transformer (v6) the shape is rotated when you flip and only the height becomes a negative.

Using this box:
```
{
  x: 200,
  y: 200
  width: 100,
  height: 100
}
```

Previously if flipped on y-axis would become:
```
{
  x: 400,
  y: 200
  width: -100,
  height: 100
}
```

Which was easy to plot coords, `if (width < 0) { // do coords and boundBox calculations }`

But now when flipped on y-axis (or x-axis) becomes:
```
{
  x: 400,
  y: 200
  width: 100,
  height: -100
}
```
Which as far as I can tell makes it impossible to plot the coordinates. Am I missing something really basic? Is there an easy way to plot the `{x1, x2, y1, y2}` coords with the new Transformer? Does anyone have any suggestions?

Also, when I was trying to find a solution I was experimenting in `boundBoxFunc` with:

```
const newWidth = Math.abs(newBox.width);
const newHeight = Math.abs(newBox.height);
```

It didn't help with what I was trying to do but it might have exposed a bug. When you flip on an axis, that axis jumps slightly when using `Math.abs()` on width or height in `boundBoxFunc`.

![captured (1)](https://user-images.githubusercontent.com/21990778/83352642-e303c480-a344-11ea-97b2-d56b59908125.gif)

Repo I'm playing around in: [https://135lj.csb.app/](https://135lj.csb.app/)

**Comment by lavrton** [comment]
Why do you need `{x1, y1, x2, y2}`? What that use case it may be just simpler to use `rect.getClientRect()` to get bounding box of a transformed rectangle.

> When you flip on an axis, that axis jumps slightly when using Math.abs() on width or height in boundBoxFunc

I am not sure it is a bug. {x,y} is changing too. So you have to adjust them as well.. Why do you need to use absolute value?

**Comment by eoghanmccarthy** [comment]
The use case is an image annotation tool. I would guess that all image annotation tools store their data as `{x1 ,y1 ,x2, y2}`. In theory the data must be in a standard format independent of any tool, and that data is then used in AI modules, etc.

I'll try `getClientRect()` but i did notice some values shifting with that at the weekend. But I'll report back after trying.

**Comment by lavrton** [comment]
I am going to close the issue for now, as I don't have additional information. If you still have an issue, please clarify it again and provide a demo.
