### ISSUE TITLE
dblClick event for shapes fires with first click outside of shape

### ISSUE THREAD

**Issue by mwehnert** [konvajs/konva#917]
Hey :)
I came across some strange behaviour with double clicks:

When you click outside of a shape with an eventlistener for ``dblclick`` but not on another shape (so onto the blank stage) and manage to do the second click inside the shape, the event fires nonetheless.

[Try it on jsbin](https://jsbin.com/liruzutede/edit?html,js,console,output).

This is currently not captured by konva's testing. I started with writing a test, that detects the probem yesterday, but it looks like I cannot reproduce the problem with ``stage.simulateMouseDown`` and ``stage.simulateMouseUp``.

```javascript
// ======================================================
  test('test dblclick with first click on stage or layer', function () {
    var stage = addStage();
    var layer = new Konva.Layer();
    stage.add(layer);

    var rect = new Konva.Rect({
      x: 20,
      y: 20,
      width: 100,
      height: 100,
      fill: 'red',
    });
    layer.add(rect);

    stage.draw();

    var rectSingleClick = 0;
    var rectDblClick = 0;

    rect.on('click', function () {
      rectSingleClick++;
    });
    rect.on('dblclick', function () {
      rectDblClick++;
    });

    // click outside of rect
    stage.simulateMouseDown({
      x: 10,
      y: 50,
    });
    stage.simulateMouseUp({
      x: 10,
      y: 50,
    });
    
    // click onto rect
    stage.simulateMouseDown({
      x: 50,
      y: 50,
    });
    stage.simulateMouseUp({
      x: 50,
      y: 50,
    });

    assert.equal(rectSingleClick, 1, 'rect trigger a click');
    assert.equal(rectDblClick, 0, 'no dblClick was triggered');     
  });
```

Would be great if you could help out @lavrton :)

**Comment by lavrton** [comment]
Looks like first `dblclick` was working ok, but others are wrong. Fixed.

Thanks for the report.

**Comment by mwehnert** [comment]
Thanks for taking action that quick!

**Comment by J2thearo** [comment]
I am using Konva 8.3.1 and this behaviour is still there. In addition, the double-click event is also triggered when I click a shape first with the right mouse button and then quickly with the left or vice versa. I would be very happy if this would be fixed soon.
