### ISSUE TITLE
Tweening a blob (line) with different numbers of points

### ISSUE THREAD

**Issue by jthrilly** [konvajs/konva#92]
Hello

In my app I generate a polygon that completely surrounds a set of shapes. I would like to animate the polygon to appear to expand when a new shape is added, so that it includes the coordinates of the new shape. 

Unfortunately the tween animation doesn't seem to support adding additional points to a polygon. If I pass a new set of points, the result is truncated. 

Do you have any ideas how I can achieve the effect I'm looking for? One hacky approach would be to generate a point within the polygon, call setPoints() to expand the number of points, and then run the tween. I do think that this sort of logic could be implemented within Konva, though. What are your thoughts?

**Comment by lavrton** [comment]
Good idea. Need to think how to implement array tween.

**Comment by jthrilly** [comment]
I tried my approach and it works, for the most part. I calculated the closest existing point to the one I wanted to add (euclidian distance) and then duplicated it. I then animated the duplicated point to the new position.

I think a better solution would be for Konva to create a point in the centre of the polygon and then animate it to the new position. If this doesn't work how about creating the point at the intersection of the edge of the polygon on the shortest path between the new point and the polygon centre). My maths is not good enough to know how to calculate this off the top of my head.

One issue I am having is that the points are stored as a flat array rather than an array of arrays [[12,43],[24,24],[12,23]] or an array of objects [{x:12,y:10},{x:23; y:65}]. I'm sure this is for performance reasons, but it makes the points themselves much more difficult to work with. If the points must be stored as a flat array, could the get and set methods at least be able to handle different data formats?

**Comment by lavrton** [comment]
Look at the result: http://jsbin.com/yuvofanayu/edit?html,js,output
I think it will work for most of cases.

**Comment by jthrilly** [comment]
Thanks! I'll take a closer look later this week, but at first glance this looks very promising. 

Did you have any thoughts on storing the points in an alternative format (array of arrays or array of objects)?

**Comment by lavrton** [comment]
Yeah. I absolutely dislike current flat array. But I am not sure how to implement more native array of objects without breaking API. Need to think about it.
