### ISSUE TITLE
How to communicate with konva+nodejs from server-side to client-side?

### ISSUE THREAD

**Issue by enriqueerrando** [konvajs/konva#920]
Hi,

I'm working on another part of the project that also requires Konva ;)

Since the client-side is easyly hackable, I'm thinking on building the konva ecosystem (stage, layers, shapes and images) from the server-side (NodeJS) avoiding the urls to get exposed. And using the client-side just for interacting with the DOM for showing/hidding the konva layers.

Is that possible or a workaround? 

I've found the konva-node package, but there is no documentation on it and since I'm pretty new to NodeJS, I was wondering if u could point me in the right direction ;)

Thanks in advance!

**Comment by lavrton** [comment]
I am not sure what is a use case.

`konva-node` is just a way to make konva work in the nodejs env. Like you can build your stage and export it into image.

What kind of communication do you want to make?

**Comment by enriqueerrando** [comment]
In this part of the project the user will be able to customize an image through Konva before purchase, so I need to make sure he cannot steel the images added to Konva, that's why I was trying to add them from server-side, this way once they get to the client-side they'll be inside canvas already making it harder for him to get them (or that's what I believe).

Does this make sense or do u have another idea to secure those files?

Thanks!

**Comment by lavrton** [comment]
I am not sure. On the client-side you need to work with something right? Like change some objects?

You can try to place a watermark on top of such image on the client-side.

**Comment by enriqueerrando** [comment]
I was thinking about a watermark too, but that would only make it hard for the user to save the image by doing some client-side hacking, but the real problem I think it is while adding images to the canvas because those paths are exposed. That's why I was thinking on doing some tasks from the server-side.

**Comment by lavrton** [comment]
I am closing the issue. If you have a question or a bug report, please be specific.

**Comment by enriqueerrando** [comment]
Sorry, I thought I was being pretty specific... Maybe I'm not communicating it right since english is not my native language :( 

1. Is there a way for the end user to access/retrive/download the canvas data as an image?
1.1. If not, is there a way for the end user to intercept the images before they get to the canvas?
1.1.1. If so, it would make a difference at all security wise to add the canvas data images with Konva from the server side, instead of the client-side?

Hope this clarifies it ;)

**Comment by lavrton** [comment]
> Is there a way for the end-user to access/retrieve/download the canvas data as an image?

Yes, at any time a user can open dev console, select canvas element on the page, and save it as image. Or just right click on the canvas and "save as image".
If you need to "secure" canvas on the client-side you can only draw a watermark on it. I don't see any other ways around. Or just don't "secure" it. I am not sure what is a use case to protect the canvas.

>  If not, is there a way for the end user to intercept the images before they get to the canvas?

Sure. A user can always open a dev console and see a network request and its data. You can encrypt image data, but after you draw it on the canvas, a user can download it again (as described above).

> it would make a difference at all security-wise to add the canvas data images with Konva from the server-side, instead of the client-side

Technically all canvas logic can be implemented on the server-side. To the client-side, you will send just a resulted image. Depending on your interaction level, such architecture will be super complex. Because you will have to send all interactions from client-side to the backend, do Konva logic on the backend, and then send the result to the client. But that is hard and will consume a network a lot.

**Comment by enriqueerrando** [comment]
Ok, thanks for the detailed explanations ;)

For what u're saying I understand that the user would only be able to download the whole image, no layer/node by layer/node, right?

Based on that, I'll use the watermark for sure, that would solve part of my problem at least ;)

As u know, my original idea was using SVGs with Konva so if the resolution increases, the quality would too. 

Could the user increase the resolution of the canvas to download a better quality image with right click? If he can, what would be the right way to avoid it, trasforming that SVG data to PNG?

Thanks!

**Comment by lavrton** [comment]
> For what u're saying I understand that the user would only be able to download the whole image, no layer/node by layer/node, right?

It is a bit harder, but still possible. Open dev console -> find Konva in the source -> get access to the stage -> find required node (layer, group, etc) -> convert it into the image.

> As u know, my original idea was using SVGs with Konva so if the resolution increases, the quality would too.

It depends on what you mean here by SVG. Konva doesn't work with SVG DOM. Konva is a canvas framework. But Konva can display SVG image on the canvas.

> Could the user increase the resolution of the canvas to download a better quality image with right click?

No. But they can download better quality with direct Konva nodes access.

**Comment by enriqueerrando** [comment]
Ok, so in conclusion, what I'm trying to achieve here it's pretty difficult. Since the final canvas is going to be always in the client-side, no matter how hard I try a well skilled hacker could still whatever he wants.

So my best chances are adding a watermark and forcing the user purchase before giving him access to the customizable canvas, instead of trying to hide everything from malicious users, right?

**Comment by lavrton** [comment]
> So my best chances are adding a watermark and forcing the user purchase before giving him access to the customizable canvas, instead of trying to hide everything from malicious users, right?

I think it is more about business and product than a technical question. But probably a very tiny amount of users can do such "hacks". So probably shouldn't care about them at all.

**Comment by enriqueerrando** [comment]
Ok, then, I'll try not to worry much about it ;)

U've helped me a ton! Thanks!
