### ISSUE TITLE
Place my shape at center of stage even after zoomIn of react stage

### ISSUE THREAD

**Issue by mdmusaib** [konvajs/konva#921]
Hi, 
I'm implementing copy,Paste, my issue is after the zoomIn if I try to copy paste means the pasted object is not able to view, 
Actually how can I find the exact center point of react stage so that I can place the copied shape ...

**Comment by lavrton** [comment]
You can calculate it manually if you know the zoom. Or you can use some Konva helper functions: https://konvajs.org/docs/sandbox/Relative_Pointer_Position.html#page-title
(just think that pointer position is in the center of the stage)
