### ISSUE TITLE
What is the best method to get line intersection with other shapes 

### ISSUE THREAD

**Issue by mahmuodmasri** [konvajs/konva#923]
So I have a whiteboard and eraser like this 

https://youtu.be/t9vyilds5iM

The problem is that I'm using movemove events and `stage.getIntersection(pos)` to trigger the delete action, so if the mouse moved too fast (like demonstrated in the video), the action won't get triggered on some objects, what is your advice on the best way to implement line intersection in this case?

**Comment by friksa** [comment]
To get the intersection, you will have to remember the previous pos of the mouse.  Think of a line between the previous mouse location and the current mouse location.  You then need to find the intersection of that line with objects.

**Comment by friksa** [comment]
Correct.  You will have to do line intersection detection with shape type.  Quite a job if you need it that precise.

**Comment by lavrton** [comment]
If you have just drawings, then every shape is just a line with several points.
When you do `mousemove`, you just need to manually check the intersection "eraser" with every other line.

There are some good functions https://stackoverflow.com/questions/13937782/calculating-the-point-of-intersection-of-two-lines

**Comment by mahmuodmasri** [comment]
unfortunately we have text and shapes as well, even the drawing lines are not a simple lines, a smoothing curve is applied to them so they're not just an array of a straight lines

**Comment by mahmuodmasri** [comment]
I read the konva source code long time ago (back then it was called KineticJS) as I remember it used a hit canvas with color codes for each shape to detect hits, is it maybe possible to obtain this canvas and apply say a mask similar to the eraser line and get the color codes within this mask?!

**Comment by lavrton** [comment]
yes, hit canvas is still there. But I am not sure how you want to use such a mask.

Calculating all possible intersections can be hard for complex shapes.
What if you will check intersection as you do it now, but not on just every mousemove position. But also in all points between last position and the current one. Probably you can set an optimal "step" for your case. Like every 2px or 1px.

**Comment by friksa** [comment]
I have tried that before, but it did not work well for me.  The bezier freehand lines sometimes did not match even when comparing every single pixel on the line.

**Comment by mahmuodmasri** [comment]
> yes, hit canvas is still there. But I am not sure how you want to use such a mask.
> 
> Calculating all possible intersections can be hard for complex shapes.
> What if you will check intersection as you do it now, but not on just every mousemove position. But also in all points between last position and the current one. Probably you can set an optimal "step" for your case. Like every 2px or 1px.

yeah I guess I could try that, but I think like @friksa mentioned, it will not match the bezier curves (I could get the points projected on the curve but that would complicate things quickly)

what I was thinking about the hit canvas, if I can get a copy of the image to new canvas, draw the line with  "destination-in" global composition (or maybe just copy the line instead of redrawing it), this will leave only the hit pixels intersecting with the line, finally I can simply scan the canvas and get all colored pixels and map them to their shapes

**Comment by lavrton** [comment]
> what I was thinking about the hit canvases is, if I can get a copy of the hit images to new canvas, draw the eraser line with "destination-in" global composition (or maybe just copy the line instead of redrawing it), then this will leave only the hit pixels intersecting with the line on the new canvas, finally I can simply scan the canvas and get all colored pixels and map them to their shapes

You may try this. You can use `layer.getHitCanvas()`  for that. But I am not sure what will be the performance for that case.

From my point of view, checking every point on the line (all pixels between two mouse positions) should work good enough. So I think it should resolve the original issue from the first message.

I am going to close the issue. Let me know if you still need anything.
