### ISSUE TITLE
Question: Strange problem toDataURL() returns: data:,

### ISSUE THREAD

**Issue by PawelGIX** [konvajs/konva#924]
I sometimes have a strange problem.
toDataURL() returns.
`data:,`
Maybe someone already had such a bug? Occurs from time to time. Rather not often. But I don't know what the reason is. I have eliminated the images loaded from the URL and still the problem is repeated. 
Do you have any idea what might be wrong?

**Comment by lavrton** [comment]
Hard to say without demo. Do you have such issues without images?

**Comment by PawelGIX** [comment]
Yes, I changed all icons to data:image/png;base64 to get rid of problems with saving not yet loaded images.  
What i found on internet https://stackoverflow.com/questions/43860035/canvas-todataurl-returns-data-when-cavans-width-height-is-too-large
But is not my case. My canvas has fixed size 820x600px.

**Comment by lavrton** [comment]
That demo looks correct to me.

Do you use `pixelRatio` attribute for `toDataURL()`?

**Comment by PawelGIX** [comment]
No, I call simply `.toDataURL();` without attributes.

**Comment by PawelGIX** [comment]
Calling toDataURL() on the unmounting component was a problem. I think we can close this issue
