### ISSUE TITLE
Problem with sub pixels when drawing image on a Konva layer

### ISSUE THREAD

**Issue by Hyreos** [konvajs/konva#925]
I have an image with 3 colors, but when I draw it in a konva layer it ends up creating several subpixels.
I already called imageSmoothingEnabled(false) on the layer where I draw the image.
I'm a little lost in what to do

Pixels before drawing:
![image](https://user-images.githubusercontent.com/21271840/84090971-8b5efc00-a9c9-11ea-844e-d4f600692440.png)

Pixels after drawing:
![image](https://user-images.githubusercontent.com/21271840/84091007-a92c6100-a9c9-11ea-9b6f-996d774e40ee.png)

**Comment by lavrton** [comment]
Hello. I don't understand the meaning of the images above. What is the reference to these RGB values?

Can you make a demo?

**Comment by Hyreos** [comment]
Hi, the top ones were the colors of the image before drawing on the layer, the bottom ones were the colors after drawing on the layer and calling toDataURL() on it (was generating some subpixels even with layer.imageSmoothingEnabled(false)), I managed to solve it by calling layer.getCanvas()._canvas.toDataURL(); instead of layer.toDataURL() directly, I'll try to demo this later.
Thanks!

**Comment by lavrton** [comment]
Looks like our `toDataURL()` method doesn't take into account `imageSmoothingEnabled` property and it doesn't accept such an argument. Probably we should add support for it.

**Comment by lavrton** [comment]
So you can do: `layer.toDataURL({ imageSmoothingEnabled: false });`

**Comment by Hyreos** [comment]
Thanks!
