### ISSUE TITLE
Touch delay with buttons over stage

### ISSUE THREAD

**Issue by Joebayld** [konvajs/konva#927]
Hi, 

I've noticed some strange behavior when having buttons on top of the stage when on mobile devices. If the button is over the stage, there is a 300ms tap delay, but if the button is outside the stage, it's fast and responsive. It seems like a bug because other html elements are fine under a button, it's just the Konva stage that's giving me trouble. It's only on touch screen devices that I have a issue.

I made a test case here:
https://jsbin.com/natokifibo/1/edit?html,js,output

Give it a try on a touch screen device and tap the button fast and notice the delay. 

I found this (which is what looks to be the issue). But setting the touch-action on the css doesn't seem to make a difference.
https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away

**Comment by lavrton** [comment]
Interesting issue. Probably you can try to use `touchstart` or `touchend` events instead of `click` on mobile.

I don't think we can do anything here from the `Konva` side. So I am going to close the issue. But let me know if my suggestion will work.

**Comment by Joebayld** [comment]
@lavrton Tried the various touch events with no luck. Modern browsers got rid of the 300ms delay (which is why the bottom button works properly). I’m not sure what is in Konva that is causing these messages not to work. :/ 

I’ll dig into it a little - but this is definitely a strange one.
