### ISSUE TITLE
Add events to Transformer

### ISSUE THREAD

**Issue by Joebayld** [konvajs/konva#928]
I'm looking to see if it's possible to add support for move events on the transformer. Essentially what I'm after is getting the position of all the nodes attached to the transformer as they are moved around. I tried: 
`    transformer.on('dragmove', function () {
      console.log('transform!')
    })` with no luck. Also tried it with the 'transform' event. It doesn't fire.

The only way I can capture the event is if I grab the first node's move events. Note - I only grab the first node because if I grab all of them, the events are fired for EVERY node (which I don't want). Then in the move event, I iterate the nodes of the transformer and get their position. 
```
    const transformer = this.$refs.transformer.getNode()
    const nodes = transformer.getNodes()
    if (nodes && nodes.length) {
      // get events from the transformer
      nodes[0].on('dragmove transform', this.onTransformerMove)
      nodes[0].on('dragend transformend', this.onTransformerEnd)
    }
```
My 'hack' works, but I think I've found some issues when iterating the transformer nodes and the position() of each node not always being correct. I feel like there should be a more elegant way. :)

**Comment by lavrton** [comment]
That is a good suggestion. I think we should proxy drag events into transformer too.

**Comment by Joebayld** [comment]
Awesome! Does the dragmove also include rotating the transformer?

**Comment by lavrton** [comment]
rotating is a `transform` event.

**Comment by Joebayld** [comment]
Gotcha. 

Should the transform events get proxied over then too? If not, I’d be back in the same situation of my issue. I’m trying to get move and rotate events of the transformer.

**Comment by lavrton** [comment]
You will be able to use `transform dragmove` events on both shape or transformer.

The issue with `dragmove` will be resolved, so your workaround will work. Because `dragmove` will be triggered only after ALL positions are changed. So you will have the correct properties.
