### ISSUE TITLE
[Feature] mimic <img> object-fit and object-position properties in Konva.Image

### ISSUE THREAD

**Issue by IljaDaderko** [konvajs/konva#930]
I was working with a  use case today where I had image of 1000px by 1000px rendered onto `Kanva.Image` that had size set to 700px by 500px. 2 Ways I got to render that image was to scale it down to 500px by 500px or cut off some of its contents.

This is where mimicing `<img>` html tags `object-fit` and `object-position` properties would come in handful. We could tell Image how to behave when its size is not exact to source image i.e. to `cover` or to `contain` it and at the same time tell it where to anchor that image i.e. `center` or `center left` for example.

I believe this is now only achievable by clipping / resizing the image with custom logic to handle all of those use cases. And api for this could be helpful perhaps?

**Comment by lavrton** [comment]
I gave the answer here: https://stackoverflow.com/a/62438162/512042. I think it does work.

**Comment by IljaDaderko** [comment]
Yep, I have similar solution going on at the moment. I guess reason for opening this issue was to chat with you about extra props on the image, something like `fit` and `position` that would abstract this behaviour and expose it through new API.

Is this something that could bring value to konva or should this be beyond its scope?

**Comment by lavrton** [comment]
I think it should be out of `Konva` core because you already can achieve that with current functionality. And I prefer to make `Konva` as small, as possible.

But we can make an official demo, that shows all similar use cases.

**Comment by IljaDaderko** [comment]
Fair enough. I guess this issue can be closed then 👍
