### ISSUE TITLE
Svelte wrapper for konva

### ISSUE THREAD

**Issue by JithinKS97** [konvajs/konva#931]
It would be really awesome if we have a wrapper for Konva in svelte. I'm ready to jump in and help.

**Comment by lavrton** [comment]
That may be interesting. I didn't see any good examples of custom renderers for svelte. Probably this one can be useful: https://svelte.dev/repl/79f4f3e0296a403ea988f74d332a7a4a?version=3.12.1

**Comment by JithinKS97** [comment]
Yes, I also think that this is the best example that we have got in canvas graphics in Svelte. Actually, I haven't worked on developing any graphics libraries before even though I have used a lot of libraries like fabric, konva, p5, processing, d3 etc. I would really like to give back to the open source world and I see that this is a great opportunity. I'll be really greatful if you can give me some guidance as to where to get started.

**Comment by lavrton** [comment]
I am closing the issue. Personally I don't work with Svelte right now. I have not personal interest in Svelte wrapper. 

But if someone is interested - please go ahead and do it. I can provide the help and support the project.

**Comment by PatWie** [comment]
Seems to be straight-forward in Svelte
https://svelte-konvajs.patwie.com/

**Comment by projektorius96** [comment]
Something is happening too [svelte-konva](https://github.com/projektorius96/svelte-konva/releases/tag/v1.1.0)
