### ISSUE TITLE
feature request: lock scaling flip

### ISSUE THREAD

**Issue by adriaanmeuris** [konvajs/konva#932]
we're evaluating this library to replace the current lib in our product.

it ticks all boxes, but one thing i can't seem to find in examples / docs / issues, is to lock scale flipping like in fabric: http://fabricjs.com/docs/fabric.Object.html#lockScalingFlip

This is the behaviour of a `Transformer` in combination with a `Text`:

![lock-scaling-flip](https://user-images.githubusercontent.com/16230038/84882492-9e3f9380-b08f-11ea-8dc1-bdea0c4641b8.gif)

how to prevent horizontal / vertical flipping when scaling in case of a text?

**Comment by lavrton** [comment]
Will it be enough if you will just set the min/max size?

**Comment by adriaanmeuris** [comment]
Do you mean using `boundBoxFunc`? In that case, no. I tried the following:
```js
boundBoxFunc(oldBB, newBB) {
  if (Math.abs(newBB.width) < 0) {
    return oldBB;
  }
  return newBB;
}
```

 but does not help as the flipping happens regardless of the size.

**Comment by lavrton** [comment]
Yeah, `Math.abs(newBB.width) < 0` will never be true.

What about this:
```js
boundBoxFunc(oldBB, newBB) {
  if (newBB.width < 5) {
    return oldBB;
  }
  if (newBB.height < 5) {
    return oldBB;
  }
  return newBB;
}
```

https://jsbin.com/toneheduhi/1/edit?html,js,console,output

**Comment by adriaanmeuris** [comment]
that does the trick - thanks!
