### ISSUE TITLE
Transform is missing from types

### ISSUE THREAD

**Issue by omasback** [konvajs/konva#933]
Cannot import Transform in typescript

neither `import Konva from 'konva'; Konva.Transform` nor `import {Transform} from Konva` work

**Comment by lavrton** [comment]
The fix will be release later.
As a workaround you can do this:

```js
import Konva from 'konva';

const Transfrom = (Konva as any).Transform;
```

Why do you need `Transform` class?

**Comment by omasback** [comment]
Because I'm using an external library (d3-zoom) for zoom/pan, and I need to do some matrix operations before applying the transform to the stage. Thanks!
