### ISSUE TITLE
[BUG] Wiggle / Shake observed on text with scale animation

### ISSUE THREAD

**Issue by IljaDaderko** [konvajs/konva#934]
You can see reproduction of this effect here (click on text to trigger animation): 
https://codesandbox.io/s/boring-booth-feu5y?file=/src/App.tsx

I have tested on latest versions of Chrome and Safari on macOS, while this wiggle / shake presents itself differently in each browser, it is observable on both. It happens when text is animated with scale transforms. Text can be animated either by itself or inside a `Group`, this bug is visible in both cases.
I am using `react-spring` for animations here, I'm not sure if it is creating this effect, but I doubt it would? 

Ideally animating text should not produce this wobbly / shake effect and I believe it is not present in other elements like shapes or images, just text.

Code from the demo above
```tsx
import { a, useTransition } from "@react-spring/konva";
import React, { useState } from "react";
import { Layer, Stage } from "react-konva";

function Master() {
  const [toggle, setToggle] = useState(true);
  const transition = useTransition(toggle, {
    from: { opacity: 0, scaleX: 1.1, scaleY: 1.1 },
    enter: { opacity: 1, scaleX: 1, scaleY: 1 },
    leave: { opacity: 0, scaleX: 1.1, scaleY: 1.1 },
    config: { duration: 1000 },
    trail: 1000
  });

  return (
    <Stage width={window.innerWidth} height={window.innerHeight}>
      <Layer>
        {transition((animation, text) => {
          return (
            <a.Text
              {...animation}
              onClick={() => setToggle(prev => !prev)}
              text={text}
              fontSize={40}
            />
          );
        })}
      </Layer>
    </Stage>
  );
}

export default Master;
```

**Comment by lavrton** [comment]
I think it is just the browser's behavior of drawing text on the canvas. You can convert text into image with `node.cache()` function, so it looks smoother.

https://codesandbox.io/s/friendly-river-ruzqq?file=/src/App.tsx

**Comment by IljaDaderko** [comment]
Still behaves weird for me on safari (as if nothing changed).

**Comment by lavrton** [comment]
It looks like sometimes it is doing unmounts. So need to recache text.

```js
  const textRef = React.useRef();
  React.useEffect(() => {
    textRef.current.cache();
  }, [toggle]);
```

https://codesandbox.io/s/friendly-river-ruzqq?file=/src/App.tsx

Works ok for me in Safari.

**Comment by IljaDaderko** [comment]
You are right, this one does the trick 👍
