### ISSUE TITLE
"fillPatternImage" not working on Safari with SVG

### ISSUE THREAD

**Issue by matcic** [konvajs/konva#936]
Hi,

Trying to set the `fillPatternImage` property on a rectangle I noticed that SVG images are not rendered as expected on Safari (other formats work well though). [This demo](https://jsbin.com/dohomof/edit?html,js,output), inspired by [this example](https://konvajs.org/docs/styling/Fill.html) doesn't really work on Safari while it does on both Chrome and Firefox.

Any clue on why this is the case?

Thanks.

**Comment by lavrton** [comment]
I don't know what Safari doesn't work here. Looks like a browser's bug to me.

As a workaround, you may draw SVG into an external canvas and use it instead.

https://jsbin.com/ditudikemo/1/edit

**Comment by matcic** [comment]
@lavrton thanks for the workaround, I was going to go with a similar solution. I will close this since to me also it looks like a bug in Safari.
