### ISSUE TITLE
Text proprty fontStyle bold not working in IE11

### ISSUE THREAD

**Issue by SirHenry** [konvajs/konva#94]
Using fontStyle: "bold" is not working for me in IE11.
Chrome and FF both look fine.
"italic" works in IE11.
http://jsfiddle.net/4503v93h/2/

**Comment by mmativ** [comment]
we make a ugly solution for this bug, and it is working, 

`_getContextFont: function() {
            var fontWeight;
            switch(this.getFontStyle()){
                case "normal" : fontWeight = 400; break;
                case "bold" : fontWeight = 700; break;
            }
            return fontWeight + f + this.getFontSize() + v + this.getFontFamily()
        },`

We remove the Font variant, maybe this is the reason, and we change the bold to numbers. I hope this way solve the bug.

**Comment by lavrton** [comment]
There were some problems with font variant. I removed it for IE case. Closed by https://github.com/konvajs/konva/commit/175687809eddd6cc2c25c9dfa8d84de798f2844d

**Comment by mmativ** [comment]
thanks for updating,
