### ISSUE TITLE
The long text extends beyond the right side of the transformer border, if the letterSpacing is not 0

### ISSUE THREAD

**Issue by blinkcat** [konvajs/konva#942]
Hi, lavrton
Recently, I encountered this problem in my react project。
It's hard to describe clearly in words, so I made a [simple demo](https://stackblitz.com/edit/js-dqnqbj?embed=1&file=index.js&hideExplorer=1).
It seems to have something to do with the  letterSpacing and fontSize.
After reading Text.ts, I found that [lineTranslateX](https://github.com/konvajs/konva/blob/f4ed8a485a56c2aa70fbca6b48b7926ce5e3ab4c/src/shapes/Text.ts#L282) was the actual width of the text, and sometimes longer than text.getWidth().
Any good suggestions to solve this?

**Comment by lavrton** [comment]
Thanks for the report.
