### ISSUE TITLE
About transfromer rotater's custom position

### ISSUE THREAD

**Issue by Guohjia** [konvajs/konva#944]
Like this [demo](https://jsbin.com/rewukohesi/edit?js,console,output)，I want to place rotater to bottom-left;
 
so i try to set x and y after transformer be declared:

```js
const rotater = transformer.findOne('.rotater')
rotater.x(rotater.x() - 65);
rotater.y(rotater.y() + 130)
```
it works after Initial declaring,but **it doesn't work after rotating**.

it seems like if you set setAttrs x and y for rotater, rotateAnchorOffset will overwrite it after rotating;

How can I achieve it？

**Comment by lavrton** [comment]
Hmmm. I don't think it will work that way, and I am not sure what kind of API can we make to customize anchors positions.

**Comment by lavrton** [comment]
I am going to close the issue. I don't think `Konva` should support custom position for rotater anchor. At least for now...
