### ISSUE TITLE
Typescript issue on 7.0.2 version

### ISSUE THREAD

**Issue by ashot-israelyan** [konvajs/konva#945]
Dear @lavrton,

I have an issue with the latest release.

The issue is in **Typescript** regarding the **findOne** method returnType of **Container** class in **node_modules/konva/types/Container.d.ts**.

In previous, it was returning **ChildNode**. Now it returns **Konva.Node**, which breaks our website.

If I am writing **layer.findOne<Konva.Image>(id)** the return is identified as **Konva.Node** and I get a bunch of errors.

I wanted to let you know about this issue and understand how can I solve it.

**Comment by lavrton** [comment]
I will publish a fix later.

As a current workaround you may try to do this:

```js
const image = layer.findOne(id) as Konva.Image;
```

**Comment by ashot-israelyan** [comment]
Thanks for your fast response.

I did exactly this.

When can we expect the fix?
