### ISSUE TITLE
Rounding to the nearest px when using node.toImage()

### ISSUE THREAD

**Issue by romarybintsev** [konvajs/konva#946]
My main goal is to export the canvas in several images. I'm currently using stage.toImage() to achieve that but sometimes the output dimensions are slightly off (usually 1px lower). I need exact dimensions so it's a big problem to me. My canvas is scaled, and to achieve actual dimensions in the output images I use 1/scale as the pixelRatio param. From my tests, I think the problem lies in the width and height parameters. It looks to me like they are rounding down first before multiplying it by the pixel ratio. Is there any way to work around this problem?

**Comment by romarybintsev** [comment]
Actually, it looks like it's rounding down AFTER multiplying by the pixel ratio. My current fix is to use pixelRatio = 1/(scale - Number.EPSILON) and then the output dimensions are correct

**Comment by lavrton** [comment]
So ok, is your issue resolved or you still need some help? In your case is the problem is in rounding, right?

**Comment by romarybintsev** [comment]
Yes, I just use a slightly larger pixel ratio to compensate for the rounding down.
