### ISSUE TITLE
Euro sign does not render with custom font on Konva-node

### ISSUE THREAD

**Issue by brenoprata10** [konvajs/konva#947]
Hi guys o/

First of all i would like to thank you for your hard work in this project.
I am working with Konva-node on a project and it seems that we have a bit of problem rendering the Euro sign(€) with custom font in it, the custom font is loaded correctly as normal, but the euro sign is defaulted to sans font:
**Template using Konva**
<img width="223" alt="Captura de Tela 2020-07-13 às 15 18 36" src="https://user-images.githubusercontent.com/26099427/87309051-5be96500-c51c-11ea-8d8f-cdc91ac727d6.png">
**Template using Konva-node**
<img width="262" alt="Captura de Tela 2020-07-13 às 15 18 45" src="https://user-images.githubusercontent.com/26099427/87309082-67d52700-c51c-11ea-9db4-7c105fcb2f16.png">

**Comment by lavrton** [comment]
Can you try to draw such text with only `node-canvas`? Probably that is something with it.

**Comment by brenoprata10** [comment]
It seems that the font that we were using on the BE side did not have the glyth for euro sign, i'll be closing the issue :)
