### ISSUE TITLE
Not rendering on Chrome

### ISSUE THREAD

**Issue by grimor** [konvajs/konva#95]
Hello, I don't know if you noticed that but on Chrome `44.0.2403.157 m` most of examples don't rendering. Don't know if these is related witch Chrome, but everything works on Firefox.

I was trying to debug that and found that `fillStyle` isn't correctly set when calling `context.fill()` method. Also when I put breakpoint (rectangles example) on line with `this._context.fill()` and debugger paused it get rendered almost correctly. If i got it renderd and clicked on rectangle to change it color, it update correctly also calling `draw()` on Stage it render correctly (So I assume it's issue on initial render).

Also working well on newer Chrome (47.0.2498.0 canary)

**Comment by lavrton** [comment]
Everything fine for me. Version 44.0.2403.130 (64-bit) Ubuntu.

**Comment by grimor** [comment]
Looks like bug in Chrome, you have slight different version, and on Canary it is fine. I used Windows version of Chrome.

**Comment by arminio** [comment]
Chrome Version 48.0.2564.116 (64-bit) on OSX El Capitan is rendering a Circle as black not honouring the fill and stroke colours. 
Works fine in Firefox.

**Comment by lavrton** [comment]
@arminio Because you are using colors wrong. I have: ` "red ", "blue "`, but should be ` "red", "blue"` (no space)

**Comment by arminio** [comment]
ooops! my bad.
Thanks for that
