### ISSUE TITLE
TextPath Transformation

### ISSUE THREAD

**Issue by muresanandrei** [konvajs/konva#951]
Is it possible to transform a text like on the image bellow ?

![sample](https://user-images.githubusercontent.com/3585748/87861903-73c54c80-c953-11ea-9ec5-b7670ea0c6f8.png)

**Comment by lavrton** [comment]
I don't know any "vector" implementations for such transform. But you can implement your own custom Filter that moves pixels into the required direction.

<img width="357" alt="Screenshot 2020-07-19 at 17 42 38" src="https://user-images.githubusercontent.com/1443320/87887121-ee3fac00-c9e7-11ea-8bdb-0133e8590e9b.png">
