### ISSUE TITLE
Transformer negative scale

### ISSUE THREAD

**Issue by bummey** [konvajs/konva#954]
I noticed that on [this line](https://github.com/konvajs/konva/blob/c13803082c60e14fa4e507fd1b2daea4c51da81f/src/shapes/Transformer.ts#L885) in Transformer.ts a field called `allowNegativeScale` is defined to `true`. Is there a reason this isn't configurable? I'd love to be able to disable this.
Thanks!

**Comment by lavrton** [comment]
Yeah, that is a not finished experiment. I think we will have that configuration one day.

**Comment by AlphaCodeZero** [comment]
Any updates here? I need to disable it, too.
Thanks!

**Comment by lavrton** [comment]
The first simplest solution will be just setting minimal width/height in `boundBoxFunc`.
