### ISSUE TITLE
Image Does not support Retina display?

### ISSUE THREAD

**Issue by CraxGrix** [konvajs/konva#956]
This is the path I drawn using Canvas context
<img width="602" alt="WeChatab15eccbbdf0984d420fbc5849cc9831" src="https://user-images.githubusercontent.com/16173957/88997791-223d9a00-d323-11ea-8f07-297120dfebb2.png">
This is the path I created using Konva Path
![image](https://user-images.githubusercontent.com/16173957/88997837-46997680-d323-11ea-8192-15e578417c66.png)

I tried to enlarge the size of Canvas twice, then call the scale function to zoom Canvas, and then pass it to Konva.Image but it didn’t work, and it also caused the position deviation

**Comment by lavrton** [comment]
How do you scale it? Images should work on retina just fine.

**Comment by CraxGrix** [comment]
I doubled the size of the Canvas and then used the ctx.scale function to zoom the canvas




> How do you scale it? Images should work on retina just fine.

**Comment by lavrton** [comment]
Ok, you scaled your own external canvas. But what about Konva.Image? Did you display it into a smaller size?

**Comment by CraxGrix** [comment]
> Ok, you scaled your own external canvas. But what about Konva.Image? Did you display it into a smaller size?

Okay, I tried to manually adjust the size of the Image to a smaller size, and it seems to work normally, thanks!
