### ISSUE TITLE
How to draw circular around little circle

### ISSUE THREAD

**Issue by wahidin32** [konvajs/konva#957]
i need help, how to make a big circle surrounded by small circles like these https://prnt.sc/tw2e5w using konva.

Thanks in advance ^^

**Comment by lavrton** [comment]
What did you try?

**Comment by wahidin32** [comment]
i want adjust to the middle circle as the table if I add a small circle as the chair by input, so if i input 10 for chair then the middle cicrcle would be getting big and the small one as chair will be adjusted in the path or circle

**Comment by lavrton** [comment]
But still, what did you try? Here is the demo of the circle: https://konvajs.org/docs/shapes/Circle.html#page-title, just create several circles on different positions.

**Comment by raphael-papazikas** [comment]
@wahidin32 check up the following link for a live demo: 
https://codesandbox.io/s/konva-circles-around-circle-xz919

Code: 
```js
import { Stage, Layer, Circle } from "konva";

const stage = new Stage({
  container: document.getElementById("app"),
  width: 600,
  height: 600
});
const layer = new Layer();
stage.add(layer);

const bigCircleRadius = 45;
const circle = new Circle({
  radius: bigCircleRadius,
  fill: "#6B2737",
  x: 150,
  y: 150
});

layer.add(circle);

let itemAmount = 8;
for (var i = 0; i < itemAmount; i++) {
  const smallCircleRadius = 10;
  const distanceToBigCircle = bigCircleRadius + smallCircleRadius + 4;

  const x =
    circle.x() + distanceToBigCircle * Math.cos((2 * Math.PI * i) / itemAmount);
  const y =
    circle.y() + distanceToBigCircle * Math.sin((2 * Math.PI * i) / itemAmount);

  layer.add(new Circle({ radius: smallCircleRadius, fill: "#EF5B5B", x, y }));
}

stage.batchDraw();

```

**Comment by lavrton** [comment]
That is a good demo.
