### ISSUE TITLE
[Feature Request] Add cornerRadius array feature to React Konva's Tag element

### ISSUE THREAD

**Issue by Devwulf** [konvajs/konva#958]
Currently, the cornerRadius attribute of the Tag element for Labels currently only supports a single number to assign a radius to all corners of the tag. It would be great if a feature similar to that of Rect's cornerRadius, which also accepts an array to assign a different radius to each corner.

**Comment by lavrton** [comment]
Thanks to @raphael-papazikas we have that function now. I will make a release with it later.
