### ISSUE TITLE
Stage events mouseover and mouseout occure twice when there's a Konva.Image

### ISSUE THREAD

**Issue by frederic-thibault** [konvajs/konva#959]
Hi,

When I add an event on the Konva.Stage for the mouseover and mouseout, the event occurred twice. The first time when the mouse is over(out) the Stage and another when the mouse over(out) the Image (the image doesn't take the entire space).

I have no event attach to the Layer that contains the Image.

If I remove this layer and let everything else intact, the event occurred once has expected.

**Comment by lavrton** [comment]
Mouse events in Konva are working similar to DOM events.

From MDN:

> The mouseover event is fired at an Element when a pointing device (such as a mouse or trackpad) is used to move the cursor onto the element or one of its child elements.

So from your description is look expected to me.

**Comment by frederic-thibault** [comment]
Thanks for your reply. I understand how the javascript events are bubbling. In this case it is a bit different. The mouseover event occurred when you mouseover from the parent to child (normal behavior), but also when your mouse get back from child to parent, this is not the normal MDN behavior.
