### ISSUE TITLE
'webkitMovementX' is deprecated. Please use 'movementX' instead.

### ISSUE THREAD

**Issue by dooddy** [konvajs/konva#96]
I do not know what is the cause of this warning, but I think the screenshot will help you http://i.imgur.com/jrTO508.png

**Comment by dotJayEss** [comment]
The webkit prefixed movementX and movementY properties have been deprecated in Chrome. I am not sure if the underlying issue was fixed in Chrome which required this check:
```
if ((typeof evt.webkitMovementX !== 'undefined' || typeof evt.webkitMovementY !== 'undefined') && evt.webkitMovementY === 0 && evt.webkitMovementX === 0) {
     return null;
}
```
With some testing this check can possibly be removed entirely or updated to use non-prefixed properties.
```
if ((typeof evt.movementX !== 'undefined' || typeof evt.movementY !== 'undefined') && evt.movementY === 0 && evt.movementX === 0) {
     return null;
}
```
