### ISSUE TITLE
Touch events not propagating throughout window

### ISSUE THREAD

**Issue by Joebayld** [konvajs/konva#960]
Hi, 

I'm running into a weird issue and looking for some insight. I have some popup menus over the stage, and when you click outside the popup to anywhere in the window, the popup should close. This happens on mouse events, but not on touch events. It's as if the touch events are stopping propagation and preventing this from happening. 

This is easier to demonstrate via example so I put the following together. You'll see that when on a touchscreen and tapping outside the stage, the menu closes - but tapping on the stage does nothing. 

I know this might be a weird one so open to any support! Thanks!

Example link:
https://jsfiddle.net/pvkfLcun/32/

**Comment by lavrton** [comment]
`Konva` is preventing some default behavior on touch devices. And looks like the menu widget that you are using is using a `click` event to hide the menu. From my understanding, I am not sure the menu is doing that correctly. But you can change `Konva` behaviour with `preventDefault: false` on shapes and stage.

https://codesandbox.io/s/konva-no-prevent-default-on-touch-8jv7l
