### ISSUE TITLE
FillPatternXY change bug in Firefox.

### ISSUE THREAD

**Issue by srnden** [konvajs/konva#961]
Hi. I need to move the shape background, and I do this by changing fillPatternX and fillPatternY. A bug occurs in firefox.
In Chrome.
![1](https://user-images.githubusercontent.com/16322716/90653845-5df3c180-e248-11ea-9eca-b4b8de757837.gif)
In Firefox 78.0.2.
![2](https://user-images.githubusercontent.com/16322716/90653966-88457f00-e248-11ea-8ab8-3aa0290b3abd.gif)
How can I fix this?

Code: https://codepen.io/srnden/pen/yLOJGBO. Maybe there is another way to do same?

**Comment by lavrton** [comment]
I am not sure it is a "bug", probably it is expected behavior for Firefox. You may need to check their bugtracker.

As a workaround - use external canvas for fill pattern and draw image into it manually.

**Comment by srnden** [comment]
You're right https://bugzilla.mozilla.org/show_bug.cgi?id=1263776
