### ISSUE TITLE
Doesnt work in IE11 or Edge

### ISSUE THREAD

**Issue by damiangreen** [konvajs/konva#963]
The canvas is black in both edge and IE for the example e.g.
https://konvajs.org/docs/react/index.html

However the docs here (https://konvajs.org/api/#toc2__anchor)says it works in modern browsers.

Should it work at all?
![image](https://user-images.githubusercontent.com/1592820/91162984-c1587600-e6c4-11ea-8019-4086ba7b47a5.png)

**Comment by lavrton** [comment]
For me, it works ok on the last Edge. In IE it doesn't work, because looks like codesandbox (the service that we are using for demos) is not working on IE.
