### ISSUE TITLE
The shadow of the off-screen graphics with stroke is incomplete.

### ISSUE THREAD

**Issue by moayuisuda** [konvajs/konva#964]
I'm using stroke to implement innerShadow, however I found that when a graphic with stroke is out of stage, the shadow of the off-screen graphic is incomplete.
![image](https://user-images.githubusercontent.com/37040897/91252844-f7632c00-e790-11ea-9195-ba950afe867f.png)
However, when I remove the stroke, the shadow of the whole graphic display correctly.
![image](https://user-images.githubusercontent.com/37040897/91252914-22e61680-e791-11ea-93bf-f00969d9b6c1.png)
Any help? [Codepen](https://codepen.io/moayuisuda/pen/ZEWeRda)

**Comment by lavrton** [comment]
Interesting. I will check it. As the solution set `perfectDrawEnabled: false` to the shape.

**Comment by lavrton** [comment]
I don't see any simple ways to prevent such default behavior.

The only solutions is to use:

`shape.shadowForStrokeEnabled(false);`
or
`shape.perfectDrawEnabled(false);`
