### ISSUE TITLE
konva3. X has the problem of tanrsformer not following?

### ISSUE THREAD

**Issue by codcer** [konvajs/konva#966]
Hello, konva3. X has the problem of tanrsformer not following. See issue:900 konva5.x  This problem has been fixed. If 3. X fixes this problem now, where can I fix it from? Please give some suggestions!

**Comment by lavrton** [comment]
Can you just upgrade to the latest version?

**Comment by codcer** [comment]
According to your modification record, 3. X to 5. X has refactoring and upgrading is refactor. For 3. X, to fix this problem, can you provide some ideas?

**Comment by lavrton** [comment]
I am sorry, I don't understand your problem.

> fix this problem

What problem?

> can you provide some ideas?

Ideas for what?

**Comment by codcer** [comment]
konva3. X has the problem of tanrsformer not following, a week ago, i solved, thanks!
