### ISSUE TITLE
Rendering SVGs with special characters

### ISSUE THREAD

**Issue by cosucosuudu** [konvajs/konva#967]
Hi,

I try to render a svg with some rectangulars and texts within a Konva canvas. This works fine until there are special characters in the text, like ° or something else. If I try to substitute the special character with its HTML entity, in this case `&deg;` the SVG is still not rendered.

I use the konva.min.js library as a local resource, downloaded three days ago.

**Comment by lavrton** [comment]
Can you make a small demo with such svg?

**Comment by cosucosuudu** [comment]
Hi,
this is the working case without special characters: https://jsbin.com/wuvuvosuse/edit?html,js,console,output

This is a copy with a modified variable relation.view[0].text, I've added `&deg;` at the beginning: https://jsbin.com/fehugefodu/1/edit?html,js,console,output

Best regards, Christoph

**Comment by lavrton** [comment]
I don't think there is something we should do from Konva side. It doesn't work as a native image too: https://jsbin.com/wuyimaseve/1/edit?html,js,console,output

**Comment by cosucosuudu** [comment]
If I write the svg directly into the div it will be rendered as expected. I've modified https://jsbin.com/wuyimaseve/1/edit?html,js,console,output this way. 

I will check the structure of my svg string if there is something corrupt.

**Comment by cosucosuudu** [comment]
I've tried several variations of my svg string now. If I take a shortened version of my svg string like this: `<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="320px" height="320px" x="0px" y="0px" viewbox="0 0 320 320"  style="transform: translate(0,0)"><g transform="translate(10, 10)" style="fill:#000000;"><rect x="150" y="120" width="120" height="70" fill="white" stroke="black" stroke-width="4" fill-opacity="0.1" stroke-opacity="0.9"></rect></g><text x="165" y="145" font-size="0.7em">I am a test.</text></svg>`
it will be rendered with Konva and with my checking tool https://www.rapidtables.com/web/tools/svg-viewer-editor.html

If I add my special char in the svg in the text element like this: `<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="320px" height="320px" x="0px" y="0px" viewbox="0 0 320 320"  style="transform: translate(0,0)"><g transform="translate(10, 10)" style="fill:#000000;"><rect x="150" y="120" width="120" height="70" fill="white" stroke="black" stroke-width="4" fill-opacity="0.1" stroke-opacity="0.9"></rect></g><text x="165" y="145" font-size="0.7em">I am a &deg; test.</text></svg>` 
my checking tool still renders the SVG, but Konva won't do it anymore https://jsbin.com/qikivurece/edit?js,output

The different behaviour with or without the special char is obvious and I'm out of ideas now.

**Comment by lavrton** [comment]
Again, as I can see the browser can't render such SVG natively: https://jsbin.com/ramebopoga/edit?js,output

You may need to use some tools to parse the SVG manually. Like https://github.com/canvg/canvg. https://konvajs.org/docs/sandbox/SVG_On_Canvas.html#page-title
