### ISSUE TITLE
bug of Text

### ISSUE THREAD

**Issue by 18sby** [konvajs/konva#968]
For Text, the attribute lineHeight can not more than 1.2

**Comment by lavrton** [comment]
Can you make a demo? Just tried this: https://jsbin.com/yilahimuhi/edit?html,js,output

Works fine for me. Any value works well.

**Comment by 18sby** [comment]
I am so sorry, I try again, The bug that I saw, because I set a small height for text, so I don't see the second line. I am so sorry. I will close the issue.
