### ISSUE TITLE
get active anchor position

### ISSUE THREAD

**Issue by rebinnaf** [konvajs/konva#969]
I want to set up guidelines according to the active anchor of the transformer, I made a sandbox, I couldn't reach the position of the anchor relative to the stage. In my code, when I use the zoom on the stage everything ruins. can you please help me? 

https://codesandbox.io/s/sharp-sky-k6yp2?file=/src/App.vue:3758-3768

**Comment by lavrton** [comment]
You need to use absolute position of the anchor. And adjust it to stage transforms.

```js
      // this function will return pointer position relative to the passed node
      function getRelativePosition(node, pos) {
        var transform = node.getAbsoluteTransform().copy();
        // to detect relative position we need to invert transform
        transform.invert();

        // now we can find relative point
        return transform.point(pos);
      }

      const transformerNode = this.$refs.transformer.getNode();
      let anchor = transformerNode.findOne(
        "." + transformerNode.getActiveAnchor()
      );

      const absPos = anchor.absolutePosition();
      const relative = getRelativePosition(anchor.getStage(), absPos);
      this.pos = relative;
```

Demo: https://codesandbox.io/s/react-vue-anchor-position-for-guidelines-7em2t

**Comment by rebinnaf** [comment]
Thanks a lot! We use Konva to develop an annotation Tool and it's great! Many thanks for all your great work :)
