### ISSUE TITLE
Konva.Text enhancement

### ISSUE THREAD

**Issue by 18sby** [konvajs/konva#970]
This tool is very good, But I wish the Text of class could support multi-row ellipsis, because it is a common scene.

**Comment by lavrton** [comment]
I wish that too...

**Comment by lavrton** [comment]
Try it with `konva@7.1.0`

**Comment by mwehnert** [comment]
Hey @lavrton, 
looks like the multi-row ellipsis you introduced with `konva@7.1.0` broke with `konva@7.1.2`. Starting with that release (and until current stable version) I get "..." on every line of the text.
``js
<Text
  text="Try to drag a star and by yourself"
  wrap="word"
  width="40"
  height="40"
  ellipsis
/>
``
![image](https://user-images.githubusercontent.com/11538167/102634276-e11f1880-4151-11eb-8bf6-bd8a0807d250.png)

**Comment by lavrton** [comment]
Thanks for the report. Just released a fix with `konva@7.2.2`. Please let me know if it fixed the issue for you.

**Comment by mwehnert** [comment]
It makes it better. Anyways: When there is a word to long for an entire line (and you have `wrap="word"`) the ellipsis "..." appears on that line. That looks somewhat unexpected :D

**Comment by lavrton** [comment]
@mwehnert can you make a demo? I tried this https://jsbin.com/furehaloqo/edit?html,js,output words ok for me.

**Comment by mwehnert** [comment]
> When there is a word to long for an entire line (and you have wrap="word") the ellipsis "..." appears on that line. That looks somewhat unexpected :D

Strange. in the same codesandbox with the same konva version (`konva@7.2.2`) I can now not reproduce it, but in our production app (also `konva@7.2.2`) I can. :persevere:  Will try around some time, hopefully it is just some bug at our side!

Thanks @lavrton for now :smile:
