### ISSUE TITLE
On version 7.0.7 we get an error when drag and drop object 'cannot read property '_getPointerById' of undefined'

### ISSUE THREAD

**Issue by SuroHak** [konvajs/konva#972]
On version 7.0.7 fixed older issue with e.evt undefined, but now we get error 'cannot read property '_getPointerById' of undefined'
![Screen Shot 2020-09-03 at 10 11 42](https://user-images.githubusercontent.com/48720978/92077807-3404d800-edce-11ea-8cfa-71b6810d6c69.png)

**Comment by lavrton** [comment]
How to reproduce it? Can you make a demo?

**Comment by SuroHak** [comment]
I only add object on canvas and attach the transformer to that's. When I drag and drop that's an object I get an that's an error.

**Comment by SuroHak** [comment]
![Screen Shot 2020-09-04 at 15 27 19](https://user-images.githubusercontent.com/48720978/92234467-267d4a00-eec3-11ea-9a1f-c81a932063fe.png)
Can you check please?

**Comment by SuroHak** [comment]
![Screen Shot 2020-09-04 at 15 28 04](https://user-images.githubusercontent.com/48720978/92234514-3f85fb00-eec3-11ea-85f1-dadba690b860.png)
Can you check please ?

**Comment by lavrton** [comment]
I can't check just from the code screen. As I can see it says that `stage` is undefined. Look like a node was removed from the stage. Why? When?

**Comment by SuroHak** [comment]
But here not removed.

**Comment by SuroHak** [comment]
Here I drag and drop the object.

**Comment by lavrton** [comment]
I need a demo. I don't know how to reproduce it.

**Comment by SuroHak** [comment]
https://codesandbox.io/s/strange-butterfly-eb1s2?file=/src/App.js like this

**Comment by lavrton** [comment]
I don't see that error in the demo.

**Comment by SuroHak** [comment]
If I attach once transformer to object and remove from stage click and after that's when I drag and drop object I can see that's an error.

**Comment by SuroHak** [comment]
Sorry for this issue from my side. I will close the issue.
