### ISSUE TITLE
Casting children of Konva.Layer from type Node to a real Shape, e.g. Rect

### ISSUE THREAD

**Issue by haerschKe** [konvajs/konva#974]
Hi,

i am relatively new to Typscript/Angular and Konva.
Is it possible to cast to the type of shapes of a layer?
If you add a shape to one and let it be output with Layer.getChildren(), then the elements of a layer are all of type Node.

Here is a small example:
`var layer = new Konva.Layer();`
`var rect = new Konva.Rect({...}); `
`layer.add(rect);//add more shapes`
`//change fill color of some Rect`
`layer.getChildren().toArray()[0].fill("green");`

The last line of the example shows a warning in typescript "Property 'fill' does not exist on type 'Node<NodeConfig>'" because there is the Type Node<NodeConfig> and not Rect. Is it possible to apply a cast or something else here?

Thanks for your help.

**Comment by lavrton** [comment]
Just do this:

```js
const rect = layer.getChildren().toArray()[0] as Konva.Rect;
rect.fill('green');
```

**Comment by haerschKe** [comment]
Thanks for you help. This works for me.
