### ISSUE TITLE
Transformer doesn't rotate when Shape rotation is set programmatically

### ISSUE THREAD

**Issue by dotmlj** [konvajs/konva#976]
Using react-konva I can't figure out how to make the Transformer (blue box) rotate with the Shape (Table component) when the Shape is selected and its rotation is set programmatically.

If set programmatically as a prop (table.floorPlan.rotation) sent to the Table component, the Shape rotates but the Transformer does not.

Rotating Shape using Transformer (OK):
![image](https://user-images.githubusercontent.com/358602/92367074-40eb3980-f0f6-11ea-86a2-3f85149fde89.png)

Setting Shape rotation programmatically:
![image](https://user-images.githubusercontent.com/358602/92366961-1f8a4d80-f0f6-11ea-97ae-efc1ed828576.png)

I have tries using forceUpdate() when the rotation change but that doesn't help:
```
useEffect(() => {
    if (isSelected) trRef.current.forceUpdate();
}, [table.floorPlan.rotation]);
```

**Stage**
```
<Stage
    scale={{
        x: zoomLevel,
        y: zoomLevel,
    }}
    offsetX={stageOffsetXY.x}
    offsetY={stageOffsetXY.y}
    width={stageWidth}
    height={window.innerHeight - 150}
    onMouseDown={deselectTable}
    onTouchStart={deselectTable}
    draggable
    className={classes.stage}
    ref={stageRef}
    >
    <Layer>
        {tables.map((table, i) => {
            return (
                <Table
                key={i}
                table={table}
                isSelected={selectedTable && table._id === selectedTable._id}
                onSelect={() => {
                    setSelectedTable(table);
                }}
                onChange={newAttrs => {
                    const shapes = tables.slice();
                    shapes[i] = newAttrs;
                    setTables(shapes);
                }}
                />
            );
        })}
    </Layer>
</Stage>
```

**Shape and Transformer** (Table component)
```
<React.Fragment>
    <Shape
        sceneFunc={(ctx, shape) => {
            ctx.beginPath();
            roundRect(ctx, 0, 0, width, height);
            ctx.strokeStyle = tableStrokeColor;
            ctx.lineWidth = tableLineWidth;
            ctx.fillStyle = tableFillColor;
            ctx.stroke();
            ctx.fill();
            ctx.fillStrokeShape(shape);
        }}
        onClick={onSelect}
        onTap={onSelect}
        ref={shapeRef}
        x={table.floorPlan.x}
        y={table.floorPlan.y}
        width={width}
        height={height}
        rotation={table.floorPlan.rotation}
        id={table.id}
        draggable
        onDragEnd={e => {
          const updatedTable = table;
          updatedTable.floorPlan.x = e.target.x();
          updatedTable.floorPlan.y = e.target.y();
          onChange(updatedTable);
        }}
        onTransformEnd={e => {
          const node = shapeRef.current;
          const scaleX = node.scaleX();
          const scaleY = node.scaleY();

          node.scaleX(1);
          node.scaleY(1);

          const updatedTable = table;
          updatedTable.floorPlan.x = node.x();
          updatedTable.floorPlan.y = node.y();
          updatedTable.floorPlan.rotation = node.rotation();
          onChange(updatedTable);
        }}
      />
      {isSelected && (
        <Transformer
          ref={trRef}
          rotateAnchorOffset={20}
          borderStrokeWidth={2}
          resizeEnabled={false} // No resize, only rotate
        />
      )}
</React.Fragment>
```

Thanks :)

**Comment by lavrton** [comment]
Should be fixed with the new version.

**Comment by dotmlj** [comment]
Thanks a lot, the Transformer now moves with the Shape when changed programmatically.

This brought another problem to my attention though; when changing the rotation programmatically that Shape rotates around the top left corner of the Shape, but when rotated using the Transformer it rotates around the center of the shape (which I believe is the preferred way)?

Thanks again

**Comment by lavrton** [comment]
That is how rotation (and origin) works in Konva. If you want to rotate around center programmatically, you have to calculate new {x,y} position manually, or use `offset` to set the origin of the shape in its center.

**Comment by sridharpg** [comment]
> That is how rotation (and origin) works in Konva. If you want to rotate around center programmatically, you have to calculate new {x,y} position manually, or use `offset` to set the origin of the shape in its center.

It would be nice if the rotate method took the rotation offset as a parameter. After all, the transformer is making the required computation to rotate around center.
