### ISSUE TITLE
right-clicking button draggable doesn't work

### ISSUE THREAD

**Issue by jokius** [konvajs/konva#977]
version 2.x works well [example](https://jsbin.com/hewopemuna/edit?html,js,output)
version 3.x and further does not work [example](https://jsbin.com/rubucolaqu/edit?html,js,output)

**Comment by lavrton** [comment]
From the [v3 changelog](https://github.com/konvajs/konva/blob/master/CHANGELOG.md#added)

> You can configure what mouse buttons can be used for drag&drop. To enable right button you can use Konva.dragButtons = [0, 1].

**Comment by jokius** [comment]
Thank you so much
