### ISSUE TITLE
maxWidth parameter missing in Context.fillText()

### ISSUE THREAD

**Issue by dvdmunckhof** [konvajs/konva#979]
The current [`Canvas.fillText()`](https://github.com/konvajs/konva/blob/800df5b110b0c77e3e3c5a37185ebf32963f064b/src/Context.ts#L429) method has 3 parameters:
```typescript
  /**
   * fillText function.
   * @method
   * @name Konva.Context#fillText
   */
  fillText(a0, a1, a2) {
    this._context.fillText(a0, a1, a2);
  }
```

However, the original method [`CanvasRenderingContext2D.fillText()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillText) has the additional and optional parameter `maxWidth`:
```javascript
CanvasRenderingContext2D.fillText(text, x, y [, maxWidth]);
```

It would be great if this could be added. Thanks!

**Comment by lavrton** [comment]
Fixed. Will be relase later.

**Comment by dvdmunckhof** [comment]
Thanks, it works great!
