### ISSUE TITLE
Issue with transformer on stage 'dragstart ' (e.evt undefined)

### ISSUE THREAD

**Issue by SuroHak** [konvajs/konva#981]
When I set **shouldOverdrawWholeArea** this property of the transformer **true**. I get an error in stage on 'dragstart' **e.evt undefined**.

https://stackoverflow.com/questions/62947885/what-is-the-best-way-to-drag-a-transformer-by-dragging-from-empty-areas-in-konva

**Comment by lavrton** [comment]
What `konva` version did you use? There is a related fix in `konva@7.0.7` https://github.com/konvajs/konva/blob/master/CHANGELOG.md#707

**Comment by SuroHak** [comment]
I use version 7.1.0.

**Comment by SuroHak** [comment]
And one more problem. 
When I write `stage.on('dragmove', (e) => console.log(e.target)`, if my transformer attached multiple nodes and I drag one of them I get a target all nodes which are attached transformer.

**Comment by SuroHak** [comment]
???

**Comment by lavrton** [comment]
I fixed it. See the commit reference above. Will publish the release later.

**Comment by SuroHak** [comment]
ok thanks

**Comment by SuroHak** [comment]
I can know when it's will be published ?

**Comment by lavrton** [comment]
released

**Comment by SuroHak** [comment]
Thanks

**Comment by SuroHak** [comment]
@lavrton but the second problem not fixed yet.

**Comment by SuroHak** [comment]
This logic not working from that's a problem.
https://stackoverflow.com/questions/44958281/drag-selection-of-elements-not-in-group-in-konvajs

**Comment by lavrton** [comment]
The second issue is the expected behavior to me. If you use a Transformer, you don't need to implement code from that SO question.
