### ISSUE TITLE
'shouldOverdrawWholeArea' property of Transformer

### ISSUE THREAD

**Issue by SuroHak** [konvajs/konva#982]
When I set 'shouldOverdrawWholeArea' property to true. In all events I don't get my objects which are attached transformer, I get a target from transformer children.

**Comment by lavrton** [comment]
What events? Can you make a demo of your issue?

**Comment by SuroHak** [comment]
for example on stage click I get a target from transformer children.

**Comment by SuroHak** [comment]
https://codesandbox.io/s/elated-pike-1tb41?file=/src/App.js

**Comment by lavrton** [comment]
I don't think we will have a solution for that. That is how `shouldOverdrawWholeArea`works right now.

**Comment by lavrton** [comment]
The whole transformer rectangle will overwrite all its internal content with its own shape.

**Comment by SuroHak** [comment]
but some kind of solution is needed for this problem

**Comment by lavrton** [comment]
The only solution I see is to move shapes on top of the transformer.

**Comment by SuroHak** [comment]
ok thanks.
