### ISSUE TITLE
Issue with Transformer to attached node (scaleY)

### ISSUE THREAD

**Issue by SuroHak** [konvajs/konva#983]
When I flip the object horizontal or vertical with the transformer on both cases changed object scaleY.

**Comment by SuroHak** [comment]
https://codesandbox.io/s/elated-pike-1tb41?file=/src/App.js:94-155

**Comment by lavrton** [comment]
That is how transformation applied in that case. In that case, it has a negative scale + rotation. I don't see any issues here, because negative Y + rotation is equivalent to just negative X scale.

**Comment by SuroHak** [comment]
But when we flip horizontal then we get a negative scaleY instead of negative scaleX

**Comment by lavrton** [comment]
Yes. When you flip horizontally you have (1) negative scaleX and (2) 180 deg rotation. Visually it is the equivalent of a negative scaleX.

**Comment by SuroHak** [comment]
No rotation is -180 but scaleX is positive

**Comment by lavrton** [comment]
Sorry. I hade a type in the previous message (fixed). It should be `scaleY` and rotation.

**Comment by SuroHak** [comment]
But it's not correct behavior sorry.

**Comment by lavrton** [comment]
Why if it is visually the same?

I agree that it will be more expected to have just negative `scaleX`, but right now I am not sure how to do such "expected" attributes updates.

**Comment by SuroHak** [comment]
I agree it is visually  the same but I think it's not correct logic for attributes.

**Comment by SuroHak** [comment]
And please see demo when I flip with the transformer rotater icon moved to the bottom of the transformer.

**Comment by SuroHak** [comment]
@lavrton

**Comment by lavrton** [comment]
> And please see the demo when I flip horizontal with the transformer rotater icon moved to the bottom of the transformer.

I am not sure I understand your issue here. rotater stays where it was for me.

**Comment by SuroHak** [comment]
No sorry rotater moved to the bottom of the transformer.

**Comment by lavrton** [comment]
Can you make a screen recording?

**Comment by SuroHak** [comment]
![Uploading Screen Shot 2020-09-25 at 22.17.44.png…]()

**Comment by SuroHak** [comment]
![Uploading Screen Shot 2020-09-25 at 22.18.23.png…]()

**Comment by SuroHak** [comment]
<img width="435" alt="Screen Shot 2020-09-25 at 22 18 43" src="https://user-images.githubusercontent.com/48720978/94302310-136b1080-ff7d-11ea-9d58-1fc03592e806.png">

**Comment by lavrton** [comment]
That is not a recording. That is a screenshot.

I am trying this with your demo:
![Kapture 2020-09-25 at 14 04 14](https://user-images.githubusercontent.com/1443320/94306133-0972ee80-ff38-11ea-9dd7-87be96051e5e.gif)

Looks correct to me.

**Comment by SuroHak** [comment]
seems this fixed
