### ISSUE TITLE
Konva.Node.create issues

### ISSUE THREAD

**Issue by blue-skyyy** [konvajs/konva#985]
hello. I use konva.js in my project last week. I saw the docs and try to realize  what I want.  However, i failed. 

in my demo. I create two layers (1: display background image.2: free draw and do somethings ) on stage. 

```js
    this.bgImgLayer = new Konva.Layer({
      id: "bg_image_layer"
    });

    this.freeDrawLayer = new Konva.Layer({
      id: "free_draw_layer",
      backgroundColor: "red"
    });

    this.stage.add(this.bgImgLayer);
    this.stage.add(this.freeDrawLayer);

```
it works well. then i saved data after i created path.  I want to use Konva.Node.create(json,"container") to load canvas.
my code:

```js
// state
{
	"attrs": {
		"width": 800,
		"height": 376
	},
	"className": "Stage",
	"children": [{
		"attrs": {
			"id": "bg_image_layer"
		},
		"className": "Layer",
		"children": [{
			"attrs": {
				"id": "bgImg",
				"source": "https:/node/server/20200827/235cd851-2a51-4745-b5a5-5c2451fb8e59.jpg",
				"width": 800,
				"height": 376
			},
			"className": "Image"
		}]
	}, {
		"attrs": {
			"id": "free_draw_layer",
			"backgroundColor": "red"
		},
		"className": "Layer",
		"children": [{
			"attrs": {
				"stroke": "#df4b26",
				"strokeWidth": 5,
				"points": [352, 289, 352, 289, 353, 289, 356, 289, 358, 289, 362]
			},
			"className": "Line"
		}]
	}]
}

```

```js

   this.stage = Konva.Node.create(state, "container");
    this.stage.find("#bgImg").forEach((node) => {
      let img = new Image();
      img.src = node.getAttr("source");
      img.onload = () => {
        node.image(img);
        this.stage.batchDraw();
      };
    });

```
the path and Image all loaded successfully. Howerver, i found my stage event is not work. i cann't free draw.

  after Node.create. the stage is a new instance. i need to add event listener  with new stage? i try but not works and how to do. i expect  i can free draw and handle the free_draw_canvas after load with json. thank you very much.

**Comment by lavrton** [comment]
> Howerver, i found my stage event is not work. i cann't free draw.

Serialization doesn't save event listeners. You have to restore them manaully.

**Comment by blue-skyyy** [comment]
> > Howerver, i found my stage event is not work. i cann't free draw.
> 
> Serialization doesn't save event listeners. You have to restore them manaully.


ok. I understand.   It's a little repetitive.  thanks.
