### ISSUE TITLE
Destroyed objects remain on canvas (especially on mobile)

### ISSUE THREAD

**Issue by Tucaen** [konvajs/konva#986]
Hi, 

first thanks for this amazing framework :)

It seems like I am doing something wrong.
I have built a small TowerDefense. Sometimes objects that are destroyed (e.g. when a bullet is destroyed midair, because the target died `Tower.ts Line 89`) just stay on the canvas. Most of the time they're cleared after a while, but some seem to stay there forever.

I started building a stackblitz to reproduce this here: https://stackblitz.com/edit/konva-canvas-not-cleared
~~Right now the bug doesn't seem to appear. So I will keep adding features, till it does, but maybe you can already see where I am going in the wrong direction.~~

**Comment by lavrton** [comment]
I didn't see such issues. Probably only on android devices several years ago (right now they work much better).

So I don't know what to suggest you here. Try to create a small demo.

**Comment by Tucaen** [comment]
I managed to reproduce the behavior!
I added some more effects, but the thing that caused the bullets to stay on the canvas for some time was to select random targets instead of always the first enemy (`Tower.ts Line 60`).

**Comment by lavrton** [comment]
That doesn't look like an issue from `Konva` side.

**Comment by Tucaen** [comment]
Do you have any suggestions how I could track this done?

My gut feeling is that there is something wrong with the timing of the on-destroy events. But it doesn't make much sense, since the objects are destroyed at some point.

**Comment by lavrton** [comment]
That code is too large to find that for me.

But my guess is:

> What will happen with a bullet if the target is destroyed BEFORE the bullet hit it?

**Comment by Tucaen** [comment]
The bullet should listen to the targets `on-destroyed` event and destroy itself.
I will try to minimize the code.

**Comment by Tucaen** [comment]
I reduced the amount of code. But I guess it's still to much?

Esentially it's only shooting (heat-seaking) bullets at random targets and destroying bullets midair, when the target died, before it got reached. The destroying of bullets midair doesn't seem to work sometimes.
Maybe you can reproduce this with less code needed 😇
