### ISSUE TITLE
hiding anchors by default and showing only when mouse hover

### ISSUE THREAD

**Issue by AlbertArulPrakash** [konvajs/konva#987]
I have two needs: 

1. Creating a rectangle (with text in it) with four anchor points on the center of every side and on mouse hover, want to see the anchor point and mouse out, anchor point to disappear
Problem: Upon the initial load, all anchor points are visible and i need to mousehover the rectangle and mouse out to disappear. 
Expected solution: when page loads, i should see only rectangles and text. Nothing else. 

Even in the issue https://github.com/konvajs/konva/issues/82 thethuglife site, you can see upon load, the anchors are visible. 
I am looking for by default hide and only when the mousehover happens, make anchor visible

2. Want to connect two objects 
Upon clicking on an anchor of object A (source), i should create a line using Bezier/ quadratic curve that ends with another anchor point in the object B (destination). I can click on anchor and drag my mouse across the stage to connect with object B anchor. 

Problem: I am not getting an idea of how to acomplish this. any pointers would be good

Attaching the source i tried as textfile.
[KonvaJSRectWithText.txt](https://github.com/konvajs/konva/files/5274167/KonvaJSRectWithText.txt)

**Comment by lavrton** [comment]
Can you be more specific about your issues?

What did you try for the first? What doesn't' work? Make a small online demo with your issue.

What did you try for the second question?

**Comment by AlbertArulPrakash** [comment]
> Can you be more specific about your issues?
> 
> What did you try for the first? What doesn't' work? Make a small online demo with your issue.
> 
> What did you try for the second question?

iavrton, the txt file attached has my demo that has the issue. 

for the second question, i didn't try anything because i couldn't  find a way/idea (blank brain) on how to implement

**Comment by lavrton** [comment]
> iavrton, the txt file attached has my demo that has the issue.

I am sorry. That is not a demo. That is a plain code. You can create a full demo with http://jsbin.com/ or https://jsfiddle.net/

About the second request:

1. listen to `mousedown` event on anchor
2. create a line in the callback
3. update line positions when you move cursor
4. check intersection with another anchor
5. on mouseup "finish" the line

**Comment by AlbertArulPrakash** [comment]
Thanks for the way to make as demo
https://jsfiddle.net/#&togetherjs=G5S2Crp4RV

Will try the second one and be back soon
