### ISSUE TITLE
transformer.on('dragend') I get two events on one dragend, when 'shouldOverdrawWholeArea' property true

### ISSUE THREAD

**Issue by SuroHak** [konvajs/konva#988]
I get two events on one dragend event.

**Comment by SuroHak** [comment]
@lavrton Why do you close this issue ?

**Comment by lavrton** [comment]
Please learn how GitHub works. You are asking the same questions for the second time.

**Comment by VahanG** [comment]
@lavrton seems `dragstart` has the same issue

**Comment by lavrton** [comment]
@VahanG yeah, thanks for the report. I am going to fix it and publish in the next version.
