### ISSUE TITLE
Contour/border/edges in free drawing tool

### ISSUE THREAD

**Issue by NicolasRannou** [konvajs/konva#990]
Hello,

Is it possible to also display differently the contours/borders/edges of the drawing in a free drawing tool? The idea is to show the edge fully opaque and the inside of the painted region semi-transparent.

https://konvajs.org/docs/sandbox/Free_Drawing.html#Free-drawing-with-Konva-nodes

Could not find any example of that, if that even possible. Ideally, we could decide the width of the contours and be able to zoom in/out nicely.

Awesome work with this library!

**Comment by lavrton** [comment]
Sure. It is just `Konva.Line`. Just close the line and set any stroke/fill.

https://konvajs.org/docs/styling/Fill.html
https://konvajs.org/docs/styling/Stroke.html

**Comment by NicolasRannou** [comment]
Nice! And is there a way, somehow to have this line constant, regardless of the zoom level?

Thanks

**Comment by lavrton** [comment]
Two ways:

1. Update like stroke manually when zoom change
2. Or disable scale for stroke: https://konvajs.org/api/Konva.Shape.html#strokeScaleEnabled
