### ISSUE TITLE
Typescript does not know that the stage / layer children are iterable

### ISSUE THREAD

**Issue by amagee** [konvajs/konva#991]
If I have a Konva `Stage`, I would like to loop over its children with a `for..of` loop:

```
for (let layer of stage.children) {
  for (let node of layer.children) {
    // ...
  }
}
```

However for the first line I get the error: `error TS2488: Type 'Collection<Layer>' must have a '[Symbol.iterator]()' method that returns an iterator.`

and for the second line I get: `Type 'Collection<Group | Shape<ShapeConfig>>' must have a '[Symbol.iterator]()' method that returns an iterator.`

In both cases the `[Symbol.iterator]` *does* exist and the loop works just fine (presumably by virtue of the fact that Konva does `Collection.prototype = [] as any`. It just seems Typescript isn't smart enough to pick up on this.

I'm aware that I can use the `.each` function as a workaround, but ideally it would be nice not to have to do that.

**Comment by lavrton** [comment]
Are you interested to make a PR?

**Comment by amagee** [comment]
Yes, but it's not immediately clear to me how to fix it. Do you have any ideas? I'm happy to have a play around in any case.

**Comment by lavrton** [comment]
I added the iterator type manually. Should work for many cases. https://github.com/konvajs/konva/commit/64373c7eac031938b883d424bb651be66e914e3f

If it doesn't' work, then use some workaround like `forEach` or `toArray()`
