### ISSUE TITLE
konva does not work in webView android

### ISSUE THREAD

**Issue by gionnydeep75** [konvajs/konva#995]
I try to draw line in webView android using konva but it works properly just on desktop.
My js

`var width = window.innerWidth;
      var height = window.innerHeight - 25;

      // first we need Konva core things: stage and layer
      var stage = new Konva.Stage({
        container: 'container',
        width: width,
        height: height,
      });

      var layer = new Konva.Layer();
      stage.add(layer);

      var isPaint = false;
      var mode = 'brush';
      var lastLine;

      stage.on('mousedown touchstart', function (e) {
        isPaint = true;
        var pos = stage.getPointerPosition();
        lastLine = new Konva.Line({
          stroke: '#df4b26',
          strokeWidth: 5,
          globalCompositeOperation:
            mode === 'brush' ? 'source-over' : 'destination-out',
          points: [pos.x, pos.y],
        });
        layer.add(lastLine);
      });

      stage.on('mouseup touchend', function () {
        isPaint = false;
      });

      // and core function - drawing
      stage.on('mousemove touchmove', function () {
        if (!isPaint) {
          return;
        }

        const pos = stage.getPointerPosition();
        var newPoints = lastLine.points().concat([pos.x, pos.y]);
        lastLine.points(newPoints);
        layer.batchDraw();
      });

      var select = document.getElementById('tool');
      select.addEventListener('change', function () {
        mode = select.value;
      });`

as you can see all mobile event are considered

**Comment by lavrton** [comment]
What exactly doesn't work for you? Any errors?

**Comment by gionnydeep75** [comment]
I tocuh the phone screen and nothing happen. No paint.
