### ISSUE TITLE
Transformer repositions nodes incorrectly when scaling the stage while dragging

### ISSUE THREAD

**Issue by dotariel** [konvajs/konva#997]
Scaling the stage (such as with the mousewheel) while dragging causes the nodes in the transformer to be incorrectly positioned.

**Scale Stage w/out Drag**
![transformer-drag-scale-1](https://user-images.githubusercontent.com/5225510/96354474-2026e400-10a5-11eb-9c68-ea70e0be2adc.gif)

**Scale Stage w/ Drag**
![transformer-drag-scale-2](https://user-images.githubusercontent.com/5225510/96354475-21f0a780-10a5-11eb-9bf9-87c93ef2cbcd.gif)

### Demo
https://codepen.io/dotariel/pen/ZEOWdYJ

**Comment by lavrton** [comment]
I can't reproduce the second example. Do you scale and drag at the same time? Or how?

**Comment by dotariel** [comment]
@lavrton To reproduce the second example:

1. Begin dragging the selection
2. While still holding the mouse button down, use the mouse wheel to zoom in/out

This is reproducible in at least the following browsers:

- Firefox 80.0.1 (64-bit)
- Chrome 86.0.4240.80 (Official Build) (x86_64)

**Comment by EyeOfMidas** [comment]
I am also seeing this issue. If I hold the mouse button to drag and scroll the mouse wheel, the next mousemove I do will adjust the shapes position/scale incorrectly.

**Comment by lavrton** [comment]
Ok. On my touchpad, I wasn't able to drag and scroll at the same time.

When you drag a node inside a transformer, the transformer will automatically initiate the dragging of every other attached shape. Changing the scale is breaking some dragging calculations. Such a break is not visible when only one shape is dragged.

I don't think it is something I want to fix from the Konva side. I don't see any simple solutions (but happy to apply any related and good Pull Requests if someone sees are good fix).
I don't think dragging and scaling at the same time is a common user's behavior. So as a workaround I suggest just disable scaling when any node is dragging.
