### ISSUE TITLE
[Suggestion] Dashed underline for text

### ISSUE THREAD

**Issue by Raynesz** [konvajs/konva#999]
First of all, I would like to say thank you for this amazing framework. It has really helped me take advantage of the canvas without prior knowledge of it. Recently, however,i found myself needing a dashed underline for text. Is it something you can add easily and, if no, what would be the best practice to implement it myself? Use a dashed \<Line /> component under the text or try to touch the html canvas myself?
Thanks in advance and keep up the good work!

**Comment by lavrton** [comment]
I am not sure that is a common/popular feature to implement it.
The simple workaround is to just use two shapes. `Konva.Text` and `Konva.Line`.

**Comment by Raynesz** [comment]
I understand. Thanks anyway! Keep up the good work.
